### ISSUE TITLE
can it run on xampp server

### ISSUE THREAD

**Issue by stephenspw** [aspnet/KestrelHttpServer#1024]
Hi Kesterl,

can it be installed on xampp server ? please advice

thanks

**Comment by davidfowl** [comment]
Not sure what you're asking. This is a webserver for ASP.NET Core.

**Comment by Tratcher** [comment]
Reverse proxy behind Apache like we do for IIS?

**Comment by stephenspw** [comment]
Sorry if my question is confusing, 

I have install xampp and postgresql and PHP. but today I saw your post and start thinking if I can host asp.net core on my xampp too and keep using postgresql  as my database ?

**Comment by muratg** [comment]
@stephenspw You can't directly serve ASP.NET Core apps on Apache (the same way as PHP). However, you can possibly use Apache as a reverse proxy and serve your app on Kestrel or WebListener.  Re postgres -- I believe there's an Entity Framework Core provider for postgres.
