### ISSUE TITLE
Graceful shutdown and draining of requests

### ISSUE THREAD

**Issue by synhaptein** [aspnet/KestrelHttpServer#1026]
I don't know if it's fixed yet, because I can not test the current version, but when I'm calling (IApplicationLifetime)lifetime.StopApplication(), every in flight requests are just killed instead of giving them time to finish and send their response back. Is it fixed, by design or a bug?

**Comment by halter73** [comment]
The application should have 5 seconds by default to finish processing any ongoing requests. This timeout is configurable via [KestrelServerOptions.ShutdownTimeout](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Server/Kestrel/KestrelServerOptions/index.html?highlight=kestrelserveroptions#prop-Microsoft.AspNetCore.Server.Kestrel.KestrelServerOptions.ShutdownTimeout) which can be modified in the options callback in [WebHostBuilder.UseKestrel](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Hosting/WebHostBuilderKestrelExtensions/index.html?highlight=usekestrel#meth-Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel). After the timeout, the underlying socket will be unceremoniously closed and Kestrel's shutdown sequence will complete.

@synhaptein  Can you explain how the in-flight requests are being killed? Are there any APIs that are throwing? Does the thread just get aborted as the process exits? Verbose logging might be helpful. If you are using ctrl-c to stop the application you might be running into https://github.com/dotnet/cli/issues/812.

**Comment by muratg** [comment]
This should be fixed in 1.0.0. Please give it a try when you can, and if you still have issues, please file another bug.
