### ISSUE TITLE
Split Http parsing into separate library

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#104]
Kestrel is the only server we have that doesn't pinvoke into Http.Sys. It would be useful to extract the logic that parses the http request so that it could be used for other servers in the future.

**Comment by cesarbs** [comment]
Consdering how Kestrel-specific and perf-focused the code is at this time, I don't think we'll ever do this.

**Comment by davidfowl** [comment]
Wow his is old

**Comment by davidfowl** [comment]
This
