### ISSUE TITLE
about pool recycling process.

### ISSUE THREAD

**Issue by Oger-Me** [aspnet/KestrelHttpServer#1040]
I have such a problem.
when wu use IIS, It will automatically recycle the application pool from time to time should。now we use KestrelHttpServer will have this problem ? 
Now it is actually a console application, so we should not have this problem. Am I right ?

**Comment by davidfowl** [comment]
If you us Kestrel behind IIS, IIS will manage the process like it always did. It'll restart the process from time to time and that will restart your application (which has kestrel loaded). If you use kestrel by itself then nothing will restart.

**Comment by Oger-Me** [comment]
@davidfowl Thanks for your answer!  With my thoughts as.

**Comment by clement911** [comment]
Are you saying that IIS will restart both the iis process AND the .net core process?

**Comment by davidfowl** [comment]
Yes. IIS signals to the module, the module signals to the .NET Core process

**Comment by clement911** [comment]
I see. Thanks.

**Comment by Cal279** [comment]
@davidfowl  - I am encountering the same issue as @hslosangeles - i.e. Kestrel is killed during an app pool recycle event and then not restarted until the next page request comes in. At least, this is the behavior I have observed with core 1.1.
Is there any way to start Kestrel again after a recycle? Also, what is the recommended approach for app pool recycling with Core - Is it necessary?
Thanks.

**Comment by davidfowl** [comment]
@Cal279 are you saying that a server restart is required to make new requests work? I'm not aware of that problem. When a new request comes in it should just start a new process and things should work.

**Comment by Cal279** [comment]
Thanks for the reply @davidfowl. Sorry, I was not clear in my initial comment. A new request does start the process, so in that respect it is not the same as the previous problem. 

However, I do have some background tasks that need to run (using Hangfire). With app pool recycling I need to wait for the next page request for this to occur. Is there any way I can  'preload' the app after a recycle? I assume that the [IIS Application Initialization Module](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization) does not work with Core/Kestrel? 

Again, apologies for not being clear or if this is a slightly tangential question to the original issue.
