### ISSUE TITLE
OnStarting callbacks are called in the wrong order

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1042]
Middleware have two opportunities to observe and modify the response headers: 1) As the stack unwinds (no body/flush), or 2) when the OnStarting event fires (write/flush). However, with Kestrel's current implementation these happen in the opposite order from eachother. This can cause conflicts for auth, caching, etc..

Historically Katana reversed the order of the OnStarting (OnSendingHeaders) callbacks before invoking them in order to mimic stack unwind.

The order of OnCompleted callbacks matters less as everything is considered out-of-scope, but reversing it would also help mimic stack unwind.

**Comment by cesarbs** [comment]
I'll look into it.
