### ISSUE TITLE
Discussion: Kestrel - OnStarting and OnCompleted callbacks are now called in LIFO order to mimic the stack unwind behavior

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1045]
Discussion for https://github.com/aspnet/Announcements/issues/200

**Comment by gdoron** [comment]
Missing milestone.

**Comment by Eilon** [comment]
Discussions go in discussion milestone 😄 The original bug is in the actual product milestone.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
