### ISSUE TITLE
Kestrel applies chunking to "Connection: Upgrade" responses

### ISSUE THREAD

**Issue by anurse** [aspnet/KestrelHttpServer#1048]
Discussed this with @halter73 so he already has most of the context, just filing this for tracking.

Recent changes to the way `Transfer-Encoding` is applied to the response now cause any response with `Connection: Upgrade` in the response headers to have HTTP chunking applied to the response. This is a Bad Thing(TM) because Kestrel shouldn't be messing with the response body of 101 responses because we've switched protocols.

This manifests in failures in our WebSockets code because the chunking metadata is being written out :).

/cc @Tratcher 

/fyi @pakrym @JunTaoLuo (this is causing the WebSockets CI failures)

**Comment by JunTaoLuo** [comment]
Was this the reason for the hangs as well? It's good to know why it's causing failures but if it also causes hangs, it would be nice to change WebSockets to timeout and report a failure instead of hanging our builds.

**Comment by anurse** [comment]
Yes, I plan to do that. As far as I can tell, it is the cause of the hangs (the hangs don't repro with 1.0.0 Kestrel either, which hints extremely strongly at the same cause :))

**Comment by cesarbs** [comment]
@halter73 Shouldn't you have closed this?

**Comment by anurse** [comment]
WebSockets appears to have been unbroken, so I'd also nominate this for closing :)

**Comment by halter73** [comment]
@muratg  Considering this bug was never in a release, should we remove the bug label or milestone so it doesn't show up in the release notes.

**Comment by anurse** [comment]
But leaving it in makes it look like we fixed more stuff :trollface: 

I'd agree, we shouldn't rel-note this, but @muratg or @Eilon can confirm that is the general approach :)
