### ISSUE TITLE
Remove splitting of path and path base in Kestrel

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1050]
This is now implemented as the `UsePathBase` Middleware in HttpAbstractions. We can now remove this feature in Kestrel.

**Comment by davidfowl** [comment]
👏

**Comment by John0King** [comment]
Will this effect .net Core app running with IIS as a subapplication ?

**Comment by brockallen** [comment]
Why add `UsePathBase` and not just use `Map`?

**Comment by Tratcher** [comment]
Map branches, UsePathBase trims (if it matches) and continues.

**Comment by brockallen** [comment]
So UsePathBase is the same as Map, if you had just taken everything in the Configure and moved it into the config inside the Map?

**Comment by Tratcher** [comment]
The path logic is the same, but for Map the other branch would always be empty and 404.

For the urls `http://localhost/favicon.ico` and `http://localhost/PathBase/favicon.ico`, if you use UsePathBase then the two both result in the same `/favicon.ico` for the next middleware, but if you Map then you get two pipelines that may have different middleware. If you only configure the Map pipeline, then the non-Map pipeline always 404s.

**Comment by brockallen** [comment]
I guess all I was getting at was that it seemed odd to have a new API when you can get the same effect with an existing API.

> For the urls http://localhost/favicon.ico and http://localhost/PathBase/favicon.ico, if you use UsePathBase then the two both result in the same /favicon.ico for the next middleware

Wait, so when you said "strip" this is what you mean I guess... meaning if the URL starts with the ~/BaseUrl then it's stripped and then proceeds to the next middleware... Is that what UseUrls used to do? Or am I still confused? Perhaps I guess I need to get the nightlys and test.

**Comment by Tratcher** [comment]
Yes, that's the same as what UseUrls used to do (in Kestrel).

**Comment by brockallen** [comment]
Ok, I setup a quick test sample on v1.1. In short UseUrls("http://localhost:123/foo") still accepts requests to "http://localhost:123/bar", and that's my confusion. This behavior (that I was previously unaware of) is pretty counter intuitive. Your explanation above now makes more sense, but I am left feeling like I'm missing some major context as to why the counter intuitive behavior existed in the first place. I guess it's a "kestrel thing" (or maybe libuv?), as opposed to how I'd expect http.sys reserved URLs to behave?

**Comment by Tratcher** [comment]
Yes, it was a Kestrel thing. Http.Sys routes requests using scheme, host, port, and path base, but Kestrel really only operates on ip and port. Once it has received a request it doesn't reject it if the host or path base are wrong.

**Comment by grantbowering** [comment]
In 1.1, a path base could be set by appending it to an `ASPNETCORE_URLS` environment variable appropriately, which provided a quick way of differing this per deployment.  Since that throws an exception in 2.0, is there an environment variable that can be leveraged equivalent to `app.SetPathBase(path)`, or writing code to set this in Configure the only way to set this up?

**Comment by Tratcher** [comment]
@grantbowering this is only supported via code at the moment. Future improvements are tracked at https://github.com/aspnet/Hosting/issues/1120
