### ISSUE TITLE
Support systemd socket activation

### ISSUE THREAD

**Issue by glennc** [aspnet/KestrelHttpServer#1057]
`systemd` socket activation would allow on-demand activation of ASP.NET Core apps when a request is made on a port instead of starting the process on system start.

See: http://0pointer.de/blog/projects/socket-activation.html

I gather that the difference for us here is that we are handed a file descriptor for a socket, we aren't creating and initializing it.

**Comment by muratg** [comment]
Putting this in 1.1 for now as we're closing on 1.1.0-preview1.

**Comment by muratg** [comment]
Sorry @glennc... moving to 1.2.0 based on the time left in 1.1.0

**Comment by halter73** [comment]
Fixed by #1280
