### ISSUE TITLE
SocketOutput's Monitor.TryEnter(_contextLock) burns cpu

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1068]
The fast fail `Monitor.TryEnter` in `SocketOutput` introduced by https://github.com/aspnet/KestrelHttpServer/pull/562 is more expensive than it first seems when contended.

I originally saw high cpu burn in locks in Kestrel in this issue https://github.com/dotnet/coreclr/issues/6144 but wasn't sure if it was just the normal locking; looks like it can also be caused by extra contention from the TryEnter atm :disappointed: 

See (or blocked by) https://github.com/dotnet/coreclr/issues/6950

**Comment by benaadams** [comment]
Is fixed in coreclr now, close?

**Comment by halter73** [comment]
@benaadams Thanks for the fix :smile:
