### ISSUE TITLE
Flush should not complete immediately

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1093]
Flush and FlushAsync are currently treated as regular writes in SocketOutput; so if they are under the buffer limit they return a CompletedTask and finish immediately.

They do correctly trigger a write on the socket if one is not scheduled (though one will be scheduled if anything has been written to the stream).

However, Flush should be special cased so it returns a non-completed Task if there is any data left to be sent; which shouldn't complete until all that data has been sent.

This will likely mean that using Flush and FlushAsync will produce responses slower; however it is likely also more in line with user expectations.

See: https://github.com/aspnet/KestrelHttpServer/issues/1092

**Comment by txdv** [comment]
Isn't that literally the idea of Flush? To write everything from the buffer to the socket?

**Comment by benaadams** [comment]
Kestrel always flushes anyway; what flush is not doing currently is not *always* blocking until the data has been written.

If you have intermediate streams/mvc etc, then flush will push that to Kestrel; but if you are just using Kestrel directly then using flush will actually slow things down.

**Comment by muratg** [comment]
There's not much value in this proposal. You can set max response buffer size to 0 anyway.
