### ISSUE TITLE
Implement CopyToAsync on FrameRequestStream

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1096]
So we can avoid double buffering up stack.

**Comment by benaadams** [comment]
Something like  #1097?

**Comment by davidfowl** [comment]
Nope 😄

**Comment by davidfowl** [comment]
More details since @benaadams jumped on this:

- MessageBody would implement CopyToAsync https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/MessageBody.cs and pass the bytes (a block at a time) directly to the WriteAsync call.

**Comment by davidfowl** [comment]
👏
