### ISSUE TITLE
Inconsistent package naming

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#11]
Helios, WebListener, and Kestrel all use different package naming systems.

Kestrel: 
- Microsoft.AspNet.Server.Kestrel – The actual server
- Kestrel – IServerFactory, Asp.Net feature interfaces, and a Program.Main that invokes Hosting.Program.Main (??).

WebListener:
- Microsoft.AspNet.Server.WebListener – The IServerFactory & AspNet feature interfaces
- Microsoft.Net.Http.Server – The actual server implementation

Helios:
- Microsoft.AspNet.Loader.IIS - The IServerFactory & AspNet feature interfaces
- (Several other assemblies for IIS interop)
- There is a metapackage called Microsoft.AspNet.Server.IIS.

Recommendation:
- Use the Microsoft.AspNet.Server.* for the components that directly interact with the web stack (IServerFactory, feature interfaces, etc.)
- Use a product specific name for the package that contains the actual server implementation.
- For Kestrel this would mean swapping the names of its two packages.

**Comment by Eilon** [comment]
What if we merge all of Kestrel into the `Microsoft.AspNet.Server.Kestrel` package? I don't think there was a whole lot of value in the short Kestrel name because it wasn't particularly useful on its own.

@Tratcher @lodejard @halter73 @davidfowl

**Comment by halter73** [comment]
@DamianEdwards, @lodejard and I decided we could punt this to beta 7.

**Comment by halter73** [comment]
I'm OK with merging these into a single `Microsoft.AspNet.Server.Kestrel` package. Is there any disagreement with this?

**Comment by Eilon** [comment]
Do it.

**Comment by lodejard** [comment]
Yep
