### ISSUE TITLE
Question: How can I get url and port information from kestrel?

### ISSUE THREAD

**Issue by dodyg** [aspnet/KestrelHttpServer#1100]
I would like to get information about `kestrel` from inside `Configure` method such as port and url. Right now all I can get is `KestrelServerOptions' which contains no such information.

**Comment by smbecker** [comment]
`app.ServerFeatures.Get<IServerAddresses>()`

**Comment by dodyg** [comment]
That does not seems to be a valid type.

**Comment by dodyg** [comment]
Great thanks.
