### ISSUE TITLE
Minimal hosting example in docs won't compile

### ISSUE THREAD

**Issue by BurtHarris** [aspnet/KestrelHttpServer#1106]
I found a [minimal hosting example][1] in the ASP.NET docs, but it won't compile.  Can anyone suggest a fix?  

    var host = new WebHostBuilder()
        .UseKestrel()
        .Configure(app => {
            app.Run( async (context) => await context.Response.WriteAsync("Hi!"));
            })
        .Build();

    host.Run();
    

But using the released 1.0 assemblies from NuGet, I get the following errors on the line starting with `app.Run(`

- CS1929 'IApplicationBuilder' does not contain a definition for 'Run' and the best extension method overload 'WebHostExtensions.Run(IWebHost, CancellationToken)' requires a receiver of type 'IWebHost'	

- CS1660 Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type	

  [1]: https://docs.asp.net/en/latest/fundamentals/hosting.html

**Comment by Tratcher** [comment]
It's missing the Microsoft.AspNetCore.Builder namespace for the Run extension and the Microsoft.AspNetCore.Http namespace for WriteAsync extension.

**Comment by BurtHarris** [comment]
Thank you sir, that gets me past the compile problems, but I guess the docs should be updated.   Now I've got a runtime exception that seems to match up with issue #735.

**Comment by Tratcher** [comment]
Docs feedback should be directed to this repo: https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/hosting.rst
