### ISSUE TITLE
Way to keep response stream open

### ISSUE THREAD

**Issue by tebeco** [aspnet/KestrelHttpServer#1107]
Hi everyone,

I'm trying to use Kestrel as a streaming server with the easiest code base.
Kind of like SignalR does, I'm trying to implement an "SSE Streaming" server

**First, I don't want to use SignalR because I won't consume it (another app will) and depending on SignalR client SDK is cleary NO ;).**

I've found a dummy implementation using API Controler :
https://github.com/bigfont/StackOverflow/tree/master/AspNetCoreServerSentEvents

The client side would probably look like this kind of "simple" :
https://github.com/bigfont/StackOverflow/blob/master/AspNetCoreServerSentEvents/wwwroot/index.html#L23-L35

I've managed to use a similar approach to make a nuget package of it without the ApiController but more like a Middleware
The big issue with both MiddleWare & Controler logic, is that once the pipeline is "done" the connection is closed
For example we can see that the dummy implementation use a "dirty trick" to prevent the request to end (and to close) :

```
for(var i = 0; true; ++i)
{
    await response.WriteAsync($"data: Controller {i} at {DateTime.Now}\r\r");

    response.Body.Flush();
    await Task.Delay(5 * 1000);
}
```

I've tried to take the code from SignalR (based on .Net Core) and remove stuff around Channel / Group / Token etc ... but it's not going that well ;)

So i've started from scratch, i've managed to store CancellationToken for HttpRequest and with the help of David Fowler I have something like that running :

```
        public void Run()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException("Cannot run disposed server");
            }

            _host = new WebHostBuilder()
                .UseKestrel()
                .UseUrls(Url)
                .Configure(app =>
                {
                    app.Run(async context =>
                    {
                        Debug.WriteLine(context.Request.GetDisplayUrl());

                        var token = context.RequestAborted;
                        
                        await _handler(new HttpContextChannel(context, token)).ConfigureAwait(false);

                        await token;
                    });
                })
                .Build();

            _host.Start();
        }

```
The thing is that it has side effect on the http server thread (quite logical because i'm holding these)

What would be the best approach ?

**Comment by benaadams** [comment]
Check if the client `Accept` header contains `text/event-stream` or `text/x-dom-event-stream`

Set your response `Content-Type` to the type e.g. `text/event-stream` and start sending data in the SSE protocol [an example is here](https://hpbn.co/server-sent-events-sse/#event-stream-protocol)

On your earlier example you want to use `await response.Body.FlushAsync();` rather than `response.Body.Flush();`

**Comment by tebeco** [comment]
SSE Specification is not the problem
I think the issue is more around the way i stack the httpContext and await on the cancellation token

The first event is handle immediately, but further request i place a breakpoint on the very first line of the middleware and it trigger 10sec (or so) after I entered the url

I'll try to push the code tomorrow to show a much complex sample

The base idea is simple :
* Accept all request (usually I debug using multiple tabs)
* Stack them in a channel
* when I input a new line in the console host of the sseServer I push it to the channel
* the channel broadcast it to htppContext

It works but I think I'm causing deadlock and/or racecondition

**Comment by benaadams** [comment]
A sample in a github  repo would help

**Comment by davidfowl** [comment]
Could Just be bad code in the custom awaiter

**Comment by tebeco** [comment]
Here is a non finished implementation :

https://github.com/tebeco/MarketData/tree/master/CSharp/NetCore/MarketData

To see the issue :
* Run KestrelTinyServerHost (Press Enter with an empty line will stop/close it)
* Open a new tab on "http://localhost:5000/"
* You should see that you're connected on the page
* Input a string inside the console and press enter
* The string should be sent within an SSE Event to the Tab
* Open another tab on the same adresse

**You'll see that you have to wait a loooooong time**

* The replay buffer will replay the last 5 events to the new tab
* Any new string sent throught the console should be sent to both tab
* Enter an empty line will close all "pending" tabs

**Analysis** :
Chrome debugger create a "Event stream" tab in network so SSE is detected **but not events**
When opening the new tabs the request does not appear immediatly in chrome either (it's like there's no Thread available to process the Request immedialty)

I do know i'm doing something stupid in my code or that some codes could be done better. But I don't know what's the best way to orient the code in order to have a really clean code + working server ;)

**Comment by benaadams** [comment]
You will kill with with this `.Wait()` https://github.com/tebeco/MarketData/blob/master/CSharp/NetCore/MarketData/src/KestrelTinyServer/MulticastChannel.cs#L27 as it will freeze a threadpool thread from further use until the `Wait` completes.

**Comment by benaadams** [comment]
Maybe change to
```csharp
public async Task AddChannel(IEventChannel channel, CancellationToken token)
{
	_channels.Add(channel);
	foreach (var message in _replayBuffer)
	{
	    await channel.SendAsync(message, token).ConfigureAwait(false);
		
		if (token.IsCancellationRequested)
		{
			break;
		}
	}
}
```
Then add the extra await to `ChannelFactory.Create` https://github.com/tebeco/MarketData/blob/master/CSharp/NetCore/MarketData/src/KestrelTinyServer/ChannelFactory.cs#L17-L32
```
public virtual IEventChannel Create(IPAddress host, int port, int bufferSize)
{
	_host = host;
	_port = port;
	var channel = new MulticastChannel(bufferSize);

	var httpServer = new HttpServer(_host, _port, async contextChannel =>
	{
		await HandleSseAsync(contextChannel);
		await channel.AddChannel(contextChannel, contextChannel.Token);
	});
	channel.AttachServer(httpServer);
	httpServer.Run();

	return channel;
}
```

**Comment by tebeco** [comment]
Ooo my bad
I don't now how i missed this .wait in the middle of nowhere. I was looking everywhere but there :s

Makes perfect sense ;)

I'll give it a try and I'll move on
Thx for that one

**Comment by tebeco** [comment]
I' m having a different behavior but there's still the huge deadlock effect ;)

Is there a way to use track it down in studio






I'm still having weird behavior like the deadlock has moved elsewhere

I'll try to track it down but not sure how to use diagnostic tools ;)

**Comment by benaadams** [comment]
Run in debug; open the Task and Threads debug windows; see what Tasks you have waiting; see what thread are waiting (explore their call stacks)

**Comment by tebeco** [comment]
Did i missed something ;) ?
He is what I get when i open lot's of tabs and try to use the debug windows
It seem that the code is stuck within Kestrel code and Task windows does not seems "friendly" to give more detail this time ;)

http://build.pouk.fr/KestrelVsSse.mp4

**Comment by benaadams** [comment]
You want to connect to the event url with an event source rather than directly (e.g. see here http://www.html5rocks.com/en/tutorials/eventsource/basics/) otherwise Chrome will be behaving as if its trying to render html and buffering.

Also I think it only allows 6 open page/resource connections to a server across all tabs http://stackoverflow.com/a/985704/1109918 so that might be effecting it also (I think event sources and websockets don't fall into that bucket though)

**Comment by tebeco** [comment]
I'll create a debug page to check out if the behavior comes from the browser

Thx for the reminder about socket pool ;)

**Comment by tebeco** [comment]
It seems that the behavior DID come from the Browser it self ;)
