### ISSUE TITLE
Regression on stopping the server

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#111]
"For every web template when the server is started with dnx . kestrel I used to be able to hit q or CTRL+C. The only way I've found to stop the server is with CTRL+Z but that keep the port in use. So on the next usage of dnx . kestrel you get a port in use error. More info at https://github.com/OmniSharp/generator-aspnet/issues/191#issuecomment-113790859."

**Comment by muratg** [comment]
@halter73 Can you have a look for Beta5?  If we can have a contained fix in Kestrel package only, we should be able to take this in Beta 5.

cc @danroth27 @DamianEdwards

**Comment by Tragetaschen** [comment]
#9?

Also note that CTRL+Z merely pauses the process and puts it in the background. From there, you could work with it using the `bg` and `fg` command line tools. It's natural that the port isn't released as the process continues to live.

**Comment by sayedihashimi** [comment]
@Tragetaschen I think #9 is a different issue. This was working on Mac in beta3/4. #9 was filed over a year ago.

**Comment by Tragetaschen** [comment]
The reason this becomes visible now is that Hosting was changed. Up until beta4, the clean way to exit the process was to press Enter (`Console.ReadLine`). Now with beta5, this was changed to CTRL+C (`Console.CancelKeyPress`).

Prior to beta5, CTRL+C would kill the process without proper cleanup. Pressing it was using the equivalent of `Environment.Exit` and at most the finalizers of the objects would run (if [at](http://ericlippert.com/2015/05/18/when-everything-you-know-is-wrong-part-one/) [all](http://ericlippert.com/2015/05/21/when-everything-you-know-is-wrong-part-two/)). Now, with beta5, CTRL+C shuts down the program using the expected code paths and properly calls `Dispose` on all objects including the Kestrel ones. This makes this bug visible again—it remained unfixed all the time.

**Comment by sayedihashimi** [comment]
@Tragetaschen ok I see. Let's see what @halter73 finds out in his investigation.

**Comment by muratg** [comment]
I think @Tragetaschen is right.

For now, workaround would be to hit Ctrl-Z to send the process to the background, and than kill it via command line (or with Activity Monitor on a Mac)

**Comment by dougbu** [comment]
Just to be clear: The PR mentioned near the end of the #9 discussion (#60) has never been merged? Would it be relevant if rebased on `dev`?

**Comment by halter73** [comment]
[OnStopRude](https://github.com/aspnet/KestrelHttpServer/commit/b43e5940e5c326bc17cdb88bbfb5db5989079349) along with [@Tratcher's fix in Hosting](https://github.com/aspnet/Hosting/commit/98f8bf6fd380df2992cb822fae0088fe9c0882b8) fix this issue

**Comment by muratg** [comment]
This is going in beta 6
