### ISSUE TITLE
Can't reset the position of FrameRequestStream

### ISSUE THREAD

**Issue by 563203132** [aspnet/KestrelHttpServer#1113]
I write a middleware to log the http request body, but after reading from Request.Body(FrameRequestStream), I can't read it again in other middleware.
Because the position of Body stream has been set to end.

Any ways to make me read it many times?

**Comment by Tratcher** [comment]
This requires fully buffering the request. Kestrel will not do this for you, but there are some helpers available. https://github.com/aspnet/HttpAbstractions/blob/3e69df87f89601a5ede32c6765b736ab922b8fee/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs#L41

**Comment by davidfowl** [comment]
That helper is "Internal" though.

**Comment by 563203132** [comment]
Calling 'EnableRewind' method will change type of the 'Body' and it may affect the next execution of the middleware.

**Comment by 563203132** [comment]
`request.EnableRewind();`
`var body = request.body;`
`if (request.ContentLength != null && request.ContentLength > 0 && body != null)`
`{`
`    byte[] buffer = new byte[request.ContentLength.Value];`
**`    body.Read(buffer, 0, (int)request.ContentLength.Value);`**
`}`

body.Read() will throw exception because the body has been disposed.

**Comment by davidfowl** [comment]
You're hitting a different bug in kestrel that was fixed in 1.0.1 https://github.com/aspnet/KestrelHttpServer/issues/1028. 

Also, avoid synchronous reads on the body in general.

**Comment by benaadams** [comment]
@563203132 you should upgrade to the released 1.0.1 patch https://blogs.msdn.microsoft.com/webdev/2016/09/13/asp-net-core-sept-2016-patch/

**Comment by benaadams** [comment]
With 1.0.0 you have to restore the body at end to work around the bug:
```csharp
request.EnableRewind();
var body = request.Body;
if (request.ContentLength != null && request.ContentLength > 0)
{
byte[] buffer = new byte[request.ContentLength.Value];
await body.ReadAsync(buffer, 0, (int)request.ContentLength.Value);
}
// Add this
request.Body = body;
```

**Comment by davidfowl** [comment]
> I write a middleware to log the http request body

You might also want to consider just wrapping the request body and logging data as it's read rather than eagerly reading the thing into a `byte[]`. What happens if there's a large file upload on your site?

**Comment by 563203132** [comment]
@benaadams I try your code and the 'body.ReadAsync' also throw exception because the body was disposed after calling the 'EnableRewind' method.

I upgrade to 1.0.1 and it's work.

@davidfowl I need to log the request at the begin of pipeline route.

Thank you very much.

**Comment by davidfowl** [comment]
> @davidfowl I need to log the request at the begin of pipeline route.

Beware of the memory concerns listed before. You don't want logging code to destroy your server performance.
