### ISSUE TITLE
Feat needed: NTLM Authentication

### ISSUE THREAD

**Issue by zigzag95** [aspnet/KestrelHttpServer#1114]
When using Windows Authentication, we are obliged to use IIS Express to debug our application.
Running the console command dotnet run will start the application using Kestrel directly exposition and so impossible to authenticate to our MVC API.
This also prevent us using usefull commands such us dotnet watch, etc.

It will be great if you implement NTLM authent in Kestrel or provide us a frontend library such IIS Express that could start in console mode.

Kr

**Comment by Tratcher** [comment]
Kestrel will not be getting its own Windows Authentication implementation.

You can use WebListener from the console for Windows Auth.
https://github.com/aspnet/ServerTests/issues/42

**Comment by zigzag95** [comment]
Yes but MVC routing dosen't work with WebListener.

**Comment by davidfowl** [comment]
Sure it does.

**Comment by zigzag95** [comment]
@davidfowl An example of program.cs and startup.cs please

**Comment by davidfowl** [comment]
Everything is same just swapping UseKestrel form UseWebListener with NTLM turned on like @Tratcher shows in his example above. Do you have an example what something that doesn't work?

**Comment by zigzag95** [comment]
When removing Kestrek and putting a break point in app.use(async (context, next) => ...
It does not fire. I tried removing IISIntegration but it doesn't work too.
I could telnet but querying /api/anyController give me no service error

**Comment by davidfowl** [comment]
Post a broken sample and we can take a look.

**Comment by Tratcher** [comment]
You cannot use WebListener with IIS/Express, only from the console. In VS the default launch profile is for IIS Express, but you can change it to the alternate console profile.

**Comment by mburbea** [comment]
So, if I want NTLM in prod what am I supposed to use? I can understand in testing, but am I relegated to using weblistener or IIS?

**Comment by Tratcher** [comment]
@mburbea correct, WebListener or IIS.

**Comment by davidfowl** [comment]
@Drawes has a kestrel connection filter that supports windows auth. https://github.com/Drawaes/CondenserDotNet/tree/master/src/CondenserDotNet.Server.WindowsAuthentication

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
