### ISSUE TITLE
Poor log message when trying to connect with https to an http endpoint

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1116]
If someone sends an https request to an http endpoint it fails as expected, but the log message does not help them understand why: `"No space character found after method in request line."`

This was found when a site had a redirect to https rule but the site had not yet set up https.

Proposal: If the request line fails to parse consider checking if it has the format of an SSL/TLS handshake and provide a more specific error like `'An invalid SSL/TLS handshake was attempted on an HTTP endpoint."`

@mikaelm12 @muratg @danroth27

**Comment by davidfowl** [comment]
Yea I don't think we should do this as annoying as that error message is. What do other servers do?

**Comment by cesarbs** [comment]
This should be a matter of checking if the first byte in the request is 0x16. Or am I missing something?

**Comment by Tratcher** [comment]
Something like that, but it may vary across versions.

**Comment by mikeharder** [comment]
Is there an RFC which specifies that the first byte of an HTTPS request will be 0x16?

**Comment by cesarbs** [comment]
https://tools.ietf.org/html/rfc5246#page-39

**Comment by cesarbs** [comment]
https://tools.ietf.org/html/rfc5246#section-6.2.1

**Comment by khellang** [comment]
Or, a more visual breakdown of the handshake TLS record; https://en.wikipedia.org/wiki/Transport_Layer_Security#Handshake_protocol

**Comment by Tratcher** [comment]
RFC links make good code comments

**Comment by mikeharder** [comment]
Also listed here: http://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-5
