### ISSUE TITLE
Error -4071 EINVAL invalid argument

### ISSUE THREAD

**Issue by LRPalacios** [aspnet/KestrelHttpServer#1117]
Hello, 

I am currently using version 1.0.0 of AspNet core for a web api project where all of the controller actions are async using the async methods from EF Core, the thing is that the web api randomly crash(particularly at the first run but not always) given a "HTTP Error 502.3 - Bad Gateway" when running from Visual Studio (IIS Express) and net::ERR_CONNECTION_RESET when running from Visual Studio Code

Looking at the exception from kestrel log is always the same,

```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 OPTIONS http://localhost:5000/api/admin/questionnaires  
Microsoft.AspNetCore.Server.Kestrel:Error: TcpListenerPrimary.OnConnection

Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4071 EINVAL invalid argument
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvWriteReq.Write2(UvStreamHandle handle, ArraySegment`1 bufs, UvStreamHandle sendHandle, Action`4 callback, Object state)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerPrimary.DispatchConnection(UvStreamHandle socket)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListenerPrimary.OnConnection(UvStreamHandle listenSocket, Int32 status)
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 31.2465ms 204 
```

The OS is windows 10, Visual Studio and Visual Studio Code are up to date, the problem only happening in development gladly the published version on the server (Windows Server 2012 R2, IIS 8.5) does not gives this problem but for devs this is becoming really frustrating 

Looking at the issues i found #232,  and #378 which is supposed to fix this, i also tried setting the thread count to 16 which by looking at the code i believe is the max value, but is still happening.

Any ideas what could be causing this? if there any more information i need to provide, i will gladly try to provide it

Thank you

**Comment by cesarbs** [comment]
Can you share a small repro app with us?

**Comment by LRPalacios** [comment]
@cesarbs  I will work in a simplified version of the actual code that reproduce the issue and as soon as it ready i will share it.

**Comment by LRPalacios** [comment]
Something i notice is that, using postman i will only fail the first time, but then if an SPA with angular $http service is calling the web api then it may fail, the SPA and wep api are on different domains CORS is enabled, it will take me some time to build the sample repo because i will also have to build a spa in a different project to correctly reproduce the issue

**Comment by cesarbs** [comment]
Have you checked if this repros on 1.0.1?

**Comment by LRPalacios** [comment]
Not yet, we already have planned the upgrade to 1.0.1 for this sprint but we will probably do it at the end of the week if everything goes as planned

**Comment by LRPalacios** [comment]
So we updated to 1.0.1 but the problem still remains, but i finally figured why this was happening, for some still unknown reason one the class library project that the web api was referring to had as dependencies some old rc-1 mvc nutget packages, since i was checking if i need to updates trough the "Manage nutget packages" option from Visual Studio and it never reflected that i needed to updates packages there i thought that project was ok, but looking directly to the project.json file i finally notice that. Everything works if i remove those old dependencies, but the message was not helping me at all, this was really difficult to debug.

Anyway i created a sample repo if you want to take a look it should show bad gateway almost always the first time you run the web api but if you refresh the browser it should work correctly, but then soetimes from time to time it will throw bad gateway again

Repo [Here](https://github.com/LRPalacios/webapi-errorsample/tree/master)

Old reference in the project being referenced by the web api [here](https://github.com/LRPalacios/webapi-errorsample/blob/master/src/Test.Domain/project.json)

**Comment by halter73** [comment]
@LRPalacios It looks like you really were running into #232 which was fixed in rc2. Since you were running rc1, kablooey! Unfortunately, I don't think there's much we can do about bugs in older prereleases other than suggest everyone makes sure they've upgraded to final release version.

**Comment by LRPalacios** [comment]
@halter73 , Yes that was the case, i just never expected that the reference in another project will override or mess with the references of the web api project which were 1.0.1

**Comment by halter73** [comment]
I think the reason there wasn't a downgrade warning is that the packages were renamed. You actually had both versions of Kestrel reference by your project: "Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final" *and* "Microsoft.AspNetCore.Server.Kestrel/1.0.1"

This might have been benign since you were referencing the new namespace in your WebAPI project, but this became an issue because there were two native libuv.dlls in the assembly load path, and the one from "~\.nuget\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes\win7-x64\native\libuv.dll" is being loaded instead of the fixed one from "~\.nuget\packages\Libuv\1.9.0\runtimes\win7-x64\native\libuv.dll". Unfortunately I don't think there is a way for us to only load a specific version of the native assembly.

@davidfowl @anurse Any ideas on how we can improve this?

**Comment by davidfowl** [comment]
File an issue on dotnet.exe and throw if there's a conflict (on build). This came up before and we decided to do nothing. Ideally, you'd get a build error and be forced to pick one of the many dlls.
