### ISSUE TITLE
PR #60 identifiend a couple of issues in Kestrel that need fixing

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/KestrelHttpServer#113]
Issues:

- [ ] Connections need to be tracked. Currently they are just new'ed without assigning them
- [ ] Reading from a socket doesn't distinguish between different kinds of errors (timeout / EOF / etc.)
- [ ] Empty catch blocks
- [ ] Consistent error handling
- [ ] #61
- [ ] #62
- [ ] #63

With these, shutdown should work reliably and kept-alive connections shouldn't be an issue

Cleanup:
- [ ] Most libuv handle classes currently use a rather complicated protocol with `new`, a method call for more parameters
- [ ] Native resource cleanup should follow standard `Dispose` / finalizer logic
- [ ] Handling and calling the actual pinvoke delegates is convoluted
- [ ] Remove `unsafe`

**Comment by shhsu** [comment]
Just curious why this PR is closed. @Tragetaschen are you planning to rewrite a PR based on the current dev branch?
