### ISSUE TITLE
Reject requests that don't set Content-Length or Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1130]
Requests containing a body (POST, PUT, CONNECT, PATCH, OPTIONS) should be rejected with a `411 Length Required` if they don't include a `Content-Length` or `Transfer-Encoding: chunked` header.

**Comment by cesarbs** [comment]
I was re-reading the spec and it says this:

```
The presence of a message body in a request is signaled by a
Content-Length or Transfer-Encoding header field.  Request message
framing is independent of method semantics, even if the method does
not define any use for a message body.
```

https://tools.ietf.org/html/rfc7230#section-3.3

Which means there's no "hard rule" for what methods can or cannot contain a body. We could be prescriptive here and determine that POST and some other methods must send `Transfer-Encoding` or `Content-Length`, but that seems unnecessary.

We already somewhat guard against messages that don't specify a content length by assuming 0. This means things could silently fail or behave strangely for some apps. Deciding on a set of methods and sending a 411 is more explicit. But then the spec doesn't help a lot in deciding which methods to treat like that.

On the other hand, the spec says this:

```
If a message is received with both a Transfer-Encoding and a
Content-Length header field, the Transfer-Encoding overrides the
Content-Length.  Such a message might indicate an attempt to
perform request smuggling (Section 9.5) or response splitting
(Section 9.4) and ought to be handled as an error.  A sender MUST
remove the received Content-Length field prior to forwarding such
a message downstream.
```

https://tools.ietf.org/html/rfc7230#section-3.3.3

Which to me makes the abandoned https://github.com/aspnet/KestrelHttpServer/issues/1164 more relevant. Granted, the specs seems to be referring to intermediate servers that just foward messages. But why shouldn't Kestrel do the same? We can either strip `Content-Length` in those cases and log a warning, or throw an exception to apps attempting to set both headers.

**Comment by cesarbs** [comment]
I'm thinking of making this change for POST and PUT only, leaving OPTIONS out (I'm not familiar with how clients use OPTIONS).

**Comment by cesarbs** [comment]
This seems to be what IIS does btw. I know lighttpd requires `Content-Length` on POST too (and I assume PUT). I'll check nginx.

**Comment by cesarbs** [comment]
Same for nginx.

**Comment by muratg** [comment]
If we can't get this in soon, let's move it to 1.2.0.
