### ISSUE TITLE
Signalr and Websockets

### ISSUE THREAD

**Issue by Tazer** [aspnet/KestrelHttpServer#114]
Hello,

Tried  to deploy an app with singalr on kestrel. (works on IIS)

But doesn't work at all on kestrel. (beta6)

How will Kestrel handle websockets? And guess at least long polling should work, but seem it's not.

I'm doing something wrong , or it's not implemented ?

**Comment by davidfowl** [comment]
When using kestrel, you need to use the websocket middleware

**Comment by Tazer** [comment]
@davidfowl , any samples ? :)

**Comment by Tazer** [comment]
Understand,

        app.UseWebSockets(); 

Will try that out.

**Comment by MJomaa** [comment]
Maybe you have a buggy Mono Version. AFAIK 4.0.1 got some bugs.
After I've upgraded to  >=4.0.2 it worked.
