### ISSUE TITLE
Kestrel null reference exception thrown when port in use

### ISSUE THREAD

**Issue by jonmurrayncc** [aspnet/KestrelHttpServer#116]
Hi,

   When running kestrel as part of a vnext project on Windows, if the port is already in use Kestrel will fail with a null reference exception on startup. It would be nicer if a more verbose error were thrown to stop blondes like myself from wondering what the issue is for > 5 minutes.

Cheers!

**Comment by AspNetSmurfLab** [comment]
It now throws a descriptive error message:
```
System.Exception: Error -4091 EADDRINUSE address already in use
```

(@DamianEdwards)
