### ISSUE TITLE
SSL Client Certificate only for specific routes or controllers

### ISSUE THREAD

**Issue by pwen090** [aspnet/KestrelHttpServer#1162]
Is there support currently or future planned support to allow for more granular SSL Client Certificates for example only for specific routes/controllers in a asp.net core kestrel hosted server? The issue is in wanting to host a combination of an asp.net mvc app and web api within the same process/service and applying client certificate requirements to the web api and not the mvc portion; as an example. This is possible in IIS by creating two virtual directories and then setting SSL settings to Accept on one folder and Ignore on the other. But IIS is not an option in this case; just mentioning as an example of where this does work.

Alternatively would it be possible to instantiate two WebHostBuilder() within a single process so that one binding can do client certificates and the other not? Would two WebHostBuilder in a single process/service be threadsafe/concurrency issues?

**Comment by Tratcher** [comment]
SSL negotiation is per connection, not per request, including client certs. The underlying SslStream only allows negotiating the client cert during the initial handshake. You can set ClientCertificateMode to AllowCertificate so it's optional, but you can't re-negotiate.

You could create two WebHostBuilders, but Kestrel can't share ports between instances to enable vdirs so that wouldn't help you.

Note we don't recommend exposing Kestrel directly to the internet, so you could use vdirs in IIS before proxying to Kestrel.  You could also do most of this with WebListener, it can do port sharing and vdirs, as well as delayed client cert negotiation.

**Comment by pwen090** [comment]
This is for a server application to be hosted within a customers environment. I was hoping to allow it to support both Windows and Linux installations hence asp.net core on kestrel vs. WebListener etc...

I think creating two WebHostBuilders should work for my purposes as I am ok to have the web browser asp.net mvc site on standard (80/443) and then a separate port for essentially software agents  communicating to the same server over web api on a different port. In general it is safe to have two WebHostBuilders running within the same process? 

BTW; I have seen it mentioned a few times about not allowing Kestrel directly to the internet. I am not planning to do that but was wondering why that is? Is it more of a performance/load concern or is there some security concern that should also be taken into consideration that might equally apply to internal networks? thank you so much; love everything you all are doing with .net core related endeavors!

**Comment by Tratcher** [comment]
Multiple WebHostBuilders in an app should be fine.

Kestrel is immature and doesn't have defenses against common DOS attacks yet.

**Comment by pwen090** [comment]
Makes sense - I will look into packaging to leverage Apache/Kestrel for Linux and WebListener for Windows depending which OS customers install on. thank you!

**Comment by pwen090** [comment]
@Tratcher just wondering if any of your guidance here has maybe changed in some way with the release of asp.net core 2.0? I went down the path of hosting multiple WebHostBuilders originally but it seems that becomes problematic in wanting to host the app in azure etc there is not an easy way to configure an azure web app to work properly with two webhostbuilders app running as console app. Wondering what asp.net core 2.0 might change here and alternatively if I just split my solution into two different projects what method do you recommend for having one project web app communicate the other project web app?

**Comment by Drawaes** [comment]
I presume in this scenario you are using renegotiation  (or would like to) to challenge the user if they go to specific controller and haven't authenticated with the correct type of certificate for that controller?

Or does the user only initiate with one and you just want to check it?

**Comment by pwen090** [comment]
I essentially have one WebHost that is a frontend of sorts, set of web apis that are called by a angular interface. I have a second WebHost that is a backend that is SignalR with a lot of agents connected to it. The frontend WebHost needs to be able to call a SignalR call against the backend to signal the agents. Having this in the same process works because I can access the signalr interface from either WebHost. If I split my 2 WebHost into separate projects/processes then I would need the frontend WebHost to somehow call the second backend WebHost. I would assume the two options for this is to add a web api to the backend WebHost and create a secure way to call that from the frontend WebHost. Or alternatively the frontend could write to some shared SQL table that the backend polls on some interval. I had been trying to keep two WebHost within the same process to avoid this type of IPC scenario. So far two WebHost has been working fine in a single process. Just wondering if there is anything in asp.net core 2.0 that might make sense to change the scenario of how I am doing this. thank you much

**Comment by Tratcher** [comment]
Nothing has changed here for 2.0.

**Comment by Drawaes** [comment]
One option by the way is loopback. If one service is coming in via the loopback address you can ignore the authentication.

**Comment by Tratcher** [comment]
@Drawaes that's not a good idea... you should never make assumptions about the caller.

**Comment by Drawaes** [comment]
It's a pretty common practice. Say you have ngnix handing off locally. Or internally you have authenticated users coming through a termiñating proxy. IP address limiting/identification  is often used.

**Comment by benaadams** [comment]
Isn't good for shared hosting though

**Comment by Drawaes** [comment]
Shared hosting? What's that? ;)

Let me be more clear you should never rely on an IP address if it's a public IP or you don't control the entire network. But say you have a local docker isolated virtual network and you service bridges to an outside network, then yeah I have no issue using that for a certain level of trust. 

Systems like this have been through several external independent Pen testing/auditing cycles at financial institutions as never been an issue.
