### ISSUE TITLE
Possible to server PHP through Kestrel?

### ISSUE THREAD

**Issue by UweKeim** [aspnet/KestrelHttpServer#1165]
I'm having an existing PHP installation (i.e. all the files and extensions like php.exe, php-cgi.exe).

Will it be possible for Kestrel to server PHP URLs through some kind of forwarding/CGI to the existing PHP installation?

**Comment by davidfowl** [comment]
Not the way you want to do it but you can use http://www.peachpie.io/ which is php on .NET.

**Comment by UweKeim** [comment]
Thanks, David. Actually I'm trying to utilize a [Laravel](https://laravel.com/) application, which seems out of scope for Peachpie, from a first quick look.
