### ISSUE TITLE
Functional tests failing due to aborted connections

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1167]
Ex:

https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3648#L449
https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3645#L428

This reminds me of https://github.com/aspnet/KestrelHttpServer/issues/1147, but the error is coming from BeginRead instead of EndRead.

**Comment by halter73** [comment]
I'm wondering if re-adding [a line like this](https://github.com/aspnet/KestrelHttpServer/blob/1.0.0-beta8/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L214) to wait for a client FIN/RST prior to calling uv_close is going to be the fix.

I remember removing this because it caused server shutdown to always take the full 5 seconds. Chrome and IE (but not firefox) would take forever to send a FIN back when receiving a FIN on an idle connection. For this reason, we might want to set a pretty aggressive timeout.

**Comment by halter73** [comment]
ZeroContentLengthAssumedOnNonKeepAliveRequestsWithoutContentLengthOrTransferEncodingHeader also failed on OS X now: https://travis-ci.org/aspnet/KestrelHttpServer/jobs/171495305

**Comment by halter73** [comment]
This doesn't seem to be fully fixed. SingleErrorResponseSentWhenAppSwallowsBadRequestException is still failing.

1. https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.3704
2. https://github.com/aspnet/KestrelHttpServer/pull/993#issuecomment-253887152 (From well before)

This is presumably the issue with sending extra data after the request was rejected like we used to in ZeroContentLengthAssumedOnNonKeepAliveRequestsWithoutContentLengthOrTransferEncodingHeader.

**Comment by muratg** [comment]
@halter73 good to close?
