### ISSUE TITLE
Use X-Forwarded-Proto to determine Scheme

### ISSUE THREAD

**Issue by sandermvanvliet** [aspnet/KestrelHttpServer#1169]
I've recently come across an interesting problem with running Kestrel behind a SSL offloading HAProxy where the ASP.Net app is generating redirect URLs that use HTTP instead of HTTPS. 

Obviously ASP.Net doesn't know about the actual URL the client uses (over HTTPS) so it thinks it's doing the correct thing as it uses the `HttpRequest.Scheme` to generate it. 

As most (reverse) proxies include the `X-Fowarded-Proto` header it would be nice to have Kestrel recognise this header and set the Scheme accordingly.

I've prepared a change to implement this behaviour but before I submit a PR I would like to get some feedback if this is a correct approach.

A bit of background:
My first approach was to include a bit of middleware in the ASP.Net pipeline to detect the header and set the scheme accordingly however that has the drawback that every app needs to include that middleware so having the hosting server (Kestrel or IIS) supply it makes life easier for the devs building the app.

**Comment by sandermvanvliet** [comment]
A bit more effort on the googling would have helped. I now tracked down that there is already middleware included by default in the IISIntegration package (specifically here: https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L56) that makes this work.

**Comment by halter73** [comment]
@sandermvanvliet In case you didn't see it, the code you linked to is configuring the [UseForwardedHeaders](https://github.com/aspnet/IISIntegration/blob/359faf7e510714e12f7140144eff25cb580b164d/src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs#L27) middleware which you can get from the [Microsoft.AspNetCore.HttpOverrides NuGet package](https://www.nuget.org/packages/Microsoft.AspNetCore.HttpOverrides/).

**Comment by sandermvanvliet** [comment]
@halter73 yep found it, thanks for the link.
