### ISSUE TITLE
[LTS] Kestrel considers `Connection: keep-alive, upgrade` as non-upgrade request

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#1171]
Original issue: https://github.com/aspnet/KestrelHttpServer/issues/1170.

We'll need to fix this in both 1.1.0 and 1.0.2 versions of Kestrel.

**Comment by muratg** [comment]
Make sure to bump Hosting dependency to 1.0.1 once  https://github.com/aspnet/Hosting/issues/873  is in.

**Comment by Eilon** [comment]
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.

**Comment by cesarbs** [comment]
Was there a particular reason why we decided to port this to 1.0.2? A request with `Connection: keep-alive, upgrade` to Kestrel 1.0.1 gets a `MessageBody` type of `ForRemainingData`, which is expected.

@anurse Did you repro the original issue on Kestrel 1.0.1? Do you know up to what version Firefox was sending `Connection: keep-alive, upgrade`? Latest version sends `Connection: Upgrade`.

**Comment by anurse** [comment]
I did not repro the original issue on 1.0.1, but neither did I try to repro it :). @BrennanConroy had the original repro. If the behavior is already correct in 1.0.1, I don't see a need to port the fix.

**Comment by BrennanConroy** [comment]
I can check tomorrow

**Comment by Eilon** [comment]
Derp 😄 Let's see what happens here - it's easy to *not* check something in 😄

**Comment by BrennanConroy** [comment]
So 1.0.1 worked because it didn't even check for `"upgrade"` and by default returns a `ForRemainingData`, you can see this change https://github.com/aspnet/KestrelHttpServer/commit/73656f6503688b6eb47ed7a5e93b3db76cbb2280 is when it "broke"

So 1.0.2 can probably stay as is.

**Comment by cesarbs** [comment]
Alright I'm gonna close this then.

**Comment by anurse** [comment]
Cool. Could we port the test over so we ensure that the behavior is never regressed?

**Comment by muratg** [comment]
Agreed, @cesarbs could you port the test? Also the labels on this bug :)

**Comment by halter73** [comment]
The tests added in #1178 were mostly unit tests that make ensure Kestrel's properly interprets the header in it's internal data structures.

We need a new test verifying that it's possible to read all the data sent by the client over the upgraded connection given a `Connection: keep-alive, upgrade`  request. This test could be merged into 1.0.* and dev.

**Comment by cesarbs** [comment]
@halter73 Yep, this one should do: https://github.com/aspnet/KestrelHttpServer/pull/1178/files#diff-91e1a141d6812899520ca7d9e201e647R294

**Comment by halter73** [comment]
👍 It looks like that should pass in 1.0.*. A functional test might be nice too.

**Comment by Eilon** [comment]
Ok so we're not fixing any product code, but we're just updating tests?

**Comment by cesarbs** [comment]
@Eilon Correct.

**Comment by Eilon** [comment]
Ok, I'll remove it from my OneNote tracking page. Thanks!

**Comment by muratg** [comment]
Removing the patch-approved label...
