### ISSUE TITLE
An UvException in the console application

### ISSUE THREAD

**Issue by neyromant** [aspnet/KestrelHttpServer#1172]
I have console .net core application with Kestrel. Some time after the launch on Windows 2012 R2, it ceases to respond to http requests. In this case, nothing is recorded log. When I was in the console click on Enter, the application suddenly "wake up" - he begins to respond to http requests and appear in the console following errors:

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 54309213.4406ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKVMJJ7K0FSS" communication error
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081
 ECANCELED operation canceled
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HKVMJJ7K0FT1" communication error
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081
 ECANCELED operation canceled`

What could be the reason? And why the app responds to pressing Enter in the console?
Nowhere in the code I do not work with the keyboard.

Thank you in advance for any response

**Comment by halter73** [comment]
Does this happen somewhat consistently? Can you take a minidump while your app is in an unresponsive state? It would be interesting to see what blocking operations were taking place.

**Comment by moozzyk** [comment]
Unless it was some content marked in the cmd window and pressing the Enter cleared the selection and unblocked the server...

**Comment by neyromant** [comment]
Thank you very much for your answers.
Indeed, the application was blocked due to the fact that the CMD window was seleced text.

**Comment by benaadams** [comment]
Issue with console logger https://github.com/aspnet/Logging/issues/532#issuecomment-268349839
