### ISSUE TITLE
freeze when reading Request.Stream in request by apache bench

### ISSUE THREAD

**Issue by itn3000** [aspnet/KestrelHttpServer#1173]
# Environment

* Windows 8.1 64bit
* dotnet cli version 1.0.0
* apache httpd 2.4.7 64bit

# Step to reproduce

dotnet cli and apache bench(ab) is required.
warning: this program uses 10000/tcp.

1. create new directory
2. extract [kestrelfreeze.zip](https://github.com/aspnet/KestrelHttpServer/files/537997/kestrelfreeze.zip)
3. open terminal in the extracted directory
5. execute `dotnet restore`
6. execute `dotnet run`
7. open another terminal
8. execute `[path to apache bench binary] -n 1 http://localhost:10000`

# Expected

* ab success and output request statistics
* terminal running `dotnet run` output the following text immediately
```
begin read body
0
```

# Actual

* ab failed with timeout
* terminal running `dotnet run` output the `begin read body` immediately, but do not output `0` until ab end

this is not occured in IIS integration, or add '-k'(keepalive) option to ab command,

**Comment by cesarbs** [comment]
You're hitting https://github.com/aspnet/KestrelHttpServer/issues/1104. It will be fixed in 1.1.0.

**Comment by halter73** [comment]
@itn3000 You're free to try out the 1.1.0 fix early by adding the [ASP.NET Core MyGet feed](https://dotnet.myget.org/gallery/aspnetcore-dev) to your NuGet.config and updating your dependency versions.
