### ISSUE TITLE
BadHttpRequestException after client side timeout

### ISSUE THREAD

**Issue by JanEggers** [aspnet/KestrelHttpServer#1174]
im getting this exception for all following requests if the client cancels a request (propably due to timeout)
i use Microsoft.Rest.ClientRuntime with autorest generated code and im not sure if the issue is in the clientruntime (not canceling properly) or if this is a Kestrel issue.

Connection processing ended abnormally	[Microsoft.AspNetCore.Server.Kestrel]
Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: The input string contains non-ASCII or null characters.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Infrastructure.MemoryPoolIteratorExtensions.GetAsciiString(MemoryPoolIterator start, MemoryPoolIterator end)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.TakeStartLine(SocketInput input)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by muratg** [comment]
@halter73 @cesarbs Thoughts? Related to https://github.com/aspnet/KestrelHttpServer/issues/1167?

**Comment by cesarbs** [comment]
@muratg No, that error message only shows up if there are non-ASCII chars in the request line or in a header. Given this is coming from `TakeStartLine()`, that's in the request line.

@JanEggers Can you send us the exact request your client is sending? It seems like it's not percent-encoding non-ASCII characters in the request line.

**Comment by JanEggers** [comment]
@cesarbs sure will do, but looks like im too dump 

fiddler does not capture the request coming from the client app. and i dont know how to configure Tracing to get raw request log. Any hints?

**Comment by JanEggers** [comment]
now it worked with fiddler :) get isnt get so its a client runtime problem

![image](https://cloud.githubusercontent.com/assets/6747376/19588950/65095314-9769-11e6-800d-1cd5b32f5368.png)

**Comment by JanEggers** [comment]
update: i added proxy settings to the client and now was able to capture a session with fiddler
there are several errors in it:

1. chunked encoding iomeimes has fancy values (fiddler lines yellow)
2. looks like parts of the response go in the request stream

really confusing stuff please help


[brokenrequests.zip](https://github.com/aspnet/KestrelHttpServer/files/543768/brokenrequests.zip)

**Comment by cesarbs** [comment]
Looks like a client issue. The client is sending part of the response as the request, and mangling characters in the process. Kestrel threw specifically because there were invalid characters in "HTTP".

But to be sure it's not Kestrel or your app doing something wrong:

1) What version of Kestrel are you using?

2) Are you doing anything besides reading and writing to the request and response streams (e.g. replacing them with another stream)?

**Comment by JanEggers** [comment]
i use the latest official nuget package and i dont mess with streams, just plain standard api controllers and no custom middleware...
