### ISSUE TITLE
Null exception error

### ISSUE THREAD

**Issue by tinganho** [aspnet/KestrelHttpServer#119]
I just tried out your sample application in Yeoman for creating Web API application.

When I run an `ab` test it yield a null exception error after a few thousand requests.

```
ab -n 10000 -c 4 http://localhost:5001/messages
```

yields:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.AspNet.Server.Kestrel.Networking.UvHandle.ReleaseHandle () [0x00000] in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.Dispose (Boolean disposing) [0x00000] in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.Finalize () [0x00000] in <filename unknown>:0
```

**Comment by muratg** [comment]
@halter73

**Comment by muratg** [comment]
We'll investigate in Beta 7

**Comment by tinganho** [comment]
I'm just wondering if Kestrel is suppose to be a production server? or just a development server(and use IIS as production)?

**Comment by loqix** [comment]
A problem with the following code in Mono, gc will free this
UvWriteRequest.cs 
// add GCHandle to keeps this SafeHandle alive while request processing 
_pins.Add(GCHandle.Alloc(this, GCHandleType.Normal));

**Comment by halter73** [comment]
@loqix A "Normal" GCHandle should prevent GC until Free is callded: https://msdn.microsoft.com/en-us/library/vstudio/83y4ak54(v=vs.100).aspx

If this doesn't happen, there is probably a bug in mono. I've run Kestrel on Mono quite a bit, and I have not seen a null ref in UvWriteRequest so far.

We did recently fix a null ref in UvShutdownReq, but there we were only using a "Weak" GCHanlde before the fix: https://github.com/aspnet/KestrelHttpServer/issues/115

Can anyone still repro this with the most recent beta6 builds?

**Comment by muratg** [comment]
@tinganho do you still have issues using Beta 6 bits?

**Comment by tinganho** [comment]
@muratg no it is fixed now thanks!
