### ISSUE TITLE
Attempting to write to HEAD response hangs the request

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1202]
Run the sample app without any connection filters and send a HEAD request and leave the connection open (this part is important). The client will hang waiting for a response.

This issue was introduced in https://github.com/aspnet/KestrelHttpServer/commit/e7e6b896ba5e5c201b61f70fa4ea352027bd6bd8 when we started ignoring writes to HEAD responses. The problem is that writing a response will make `Frame.HasResponseStarted` true, skipping the call to `ProduceEndAwaited` from `ProduceEnd` and therefore skipping the flush call in that method.

I caught this while working on https://github.com/aspnet/KestrelHttpServer/issues/1139. When I changed all tests to call `Send` instead of `SendEnd`, `ResponseTests.HeadResponseCanContainContentLengthHeaderButBodyNotWritten` started timing out on `TestConnection.Receive`.

**Comment by muratg** [comment]
Approved by @Eilon, so triaging this one in.
