### ISSUE TITLE
Add EventSource events

### ISSUE THREAD

**Issue by kichalla** [aspnet/KestrelHttpServer#1211]
Events:
- Connection Id (to establish correlation with the current request)

**Comment by kichalla** [comment]
@davidfowl @rynowak @shirhatti

**Comment by muratg** [comment]
cc @shirhatti

**Comment by muratg** [comment]
See the work done in Hosting for adding EventSource: aspnet/hosting#883

**Comment by halter73** [comment]
I think it might be possible to implement this on top of logging scopes once we do #640.

**Comment by natemcmaster** [comment]
Drafting a list of events we should include. Please add more 

- ConnectionStart:
   - connectionId
   - serverAddress
   - localEndPoint
   - remoteEndPoint

**Comment by muratg** [comment]
@shirhatti Could you review Nate's list?

**Comment by natemcmaster** [comment]
For cross reference, here are the items we send to `ILogger`: https://github.com/aspnet/KestrelHttpServer/blob/e55c62444bdd34274173b011720c03f23c4db2f5/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelTrace.cs

**Comment by natemcmaster** [comment]
@glennc any input on the list of events we should include?

Ping @shirhatti as well.
