### ISSUE TITLE
High CPU in SocketInput.ConsumingXXX

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1214]
From isolated plaintext 16 pipelined request parsing benchmark in https://github.com/aspnet/KestrelHttpServer/pull/1138 

![SocketInput](https://aoa.blob.core.windows.net/aspnet/socketinputcomsuming.png)

Single threaded test so shouldn't be the locks? ConsumingStart has the Iterator .ctor inlined into it otherwise doesn't seem too exciting.

/cc @halter73 @cesarbs @pakrym

**Comment by benaadams** [comment]
To change to something to profile I changed the `Program.Main` in `Microsoft.AspNetCore.Server.Kestrel.Performance` to
```csharp
public static void Main(string[] args)
{
    var bm = new RequestParsing();

    bm.Setup();

    while (true)
    {
        bm.ParsePipelinedPlaintext();
    }
}
```

**Comment by halter73** [comment]
ConsumingStart taking so much "own time" is particularly interesting considering how little it should be doing.

You could switch the LoggingThreadPool to a SynchronousThreadPool in the test to ensure there is no lock contention, but since the data is all added to SocketInput prior to parsing, that *shouldn't* matter.

**Comment by benaadams** [comment]
Yeah Start doesn't make much sense. Profiler only shows single thread; unless it causes added cost from lock tracking...

Will probably have to disassemble and see what's going on 😢 Best I can think of atm is the struct copy in return.

**Comment by benaadams** [comment]
Might also be that everything else is really fast...

**Comment by muratg** [comment]
@benaadams any more ideas on this one?
