### ISSUE TITLE
How to get a list of actual listening sockets

### ISSUE THREAD

**Issue by leak** [aspnet/KestrelHttpServer#1226]
Is there a way to obtain a list of sockets (IP+Port) that Kestrel is listening on during runtime (preferably accessible from a WebAPI controller)?

To be clear, I am not talking about configuration values that a passed into Kestrel. (e.g. 0.0.0.0:80)

Thanks

**Comment by khellang** [comment]
I think you should be able to pull out `IServerAddressesFeature` and look at the addresses; `host.ServerFeatures.Get<IServerAddressesFeature>()`.

**Comment by leak** [comment]
This only returns me a list of strings like "http://0.0.0.0:10000", not the actual sockets.

**Comment by Tratcher** [comment]
No, that information isn't available. What were you going to do with it?

FYI: The open socket in the above sample really is 0.0.0.0:10000, Kestrel doesn't have/use any more detailed info than that.

**Comment by halter73** [comment]
If you want to see what network interfaces `0.0.0.0` likely includes, you could use `NetworkInterface.GetAllNetworkInterfaces()` like we [do in our tests](https://github.com/aspnet/KestrelHttpServer/blob/rel/1.1.0/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs#L375-L378). Kestrel doesn't expose this kind of information.

**Comment by leak** [comment]
@halter73 Thanks for the hint.
