### ISSUE TITLE
Move Int64 parsing logic to HttpAbstractions

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1227]
The logic in https://github.com/aspnet/KestrelHttpServer/blob/29408956f990efba5a04e8b9c6c210058b5e19a3/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameHeaders.cs#L235 should be moved to Abstractions to allow other repos to take advantage of the performance boost.

**Comment by Tratcher** [comment]
Especially request and response content-length headers

**Comment by JunTaoLuo** [comment]
Done in https://github.com/aspnet/KestrelHttpServer/pull/1228/files
