### ISSUE TITLE
Kestrel no response when web page reflesh 2 times/sec in .net 4.5.1

### ISSUE THREAD

**Issue by sampsonye** [aspnet/KestrelHttpServer#1232]
I build the Server on .Net Framework 4.5.1, then I open the url on anohter computer on a LAN network, if I reflesh the web page 2 times/second ,about 1minute after,Kestrel has no response.

```
internal class Startup2 : IStartup
    {
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddDirectoryBrowser();
            return services.BuildServiceProvider();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseFileServer(new FileServerOptions()
            {
                FileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory()),
                EnableDirectoryBrowsing = true,
                StaticFileOptions =
                    {
                        DefaultContentType = "application/x-msdownload",
                        ContentTypeProvider = new FileExtensionContentTypeProvider(new Dictionary<string, string>()
                        {
                            {".config", "text/plain"},
                            {".jpg", "image/jpeg"},
                            {".png", "image/png"},
                            {".mp4", "video/mp4"},
                        })
                    }
            });
        }
    }
```

**Comment by Tratcher** [comment]
Any error logs?

**Comment by sampsonye** [comment]
no, Server never crash,And VS do not report Error Message

**Comment by sampsonye** [comment]
it has happened on .net core
Press F5 on the web page (attention:ijust test image and video)

System info:
windows 10,X64
Visual studio 2015

**Comment by davidfowl** [comment]
Can you reproduce this consistently?

**Comment by benaadams** [comment]
So after 120 requests for images and videos in 60 seconds it stops responding?

Which browser? Is it the browser or the server; i.e. when it has stopped responding if you connect via a different computer, or different browser on same computer; or close the browser completely and reopen it; does it work?

How large are the files you are loading?

If you add logging what is the output? e.g.

```csharp
        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            // Add logging, and add to parameters above
            loggerFactory.AddConsole(LogLevel.Debug);

            app.UseFileServer(new FileServerOptions()
            {
                FileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory()),
                EnableDirectoryBrowsing = true,
                StaticFileOptions =
                    {
                        DefaultContentType = "application/x-msdownload",
                        ContentTypeProvider = new FileExtensionContentTypeProvider(new Dictionary<string, string>()
                        {
                            {".config", "text/plain"},
                            {".jpg", "image/jpeg"},
                            {".png", "image/png"},
                            {".mp4", "video/mp4"},
                        })
                    }
            });
        }
```

**Comment by chrisowhite** [comment]
I've had similar problems after upgrading my Kestrel dependencies to 1.1.0. Server stops responding and the browser will eventually time out the request. Debug output shows nothing after it appears to stop accepting requests, and it requires restarting the application. I haven't had any problems since downgrading to 1.0.1.

**Comment by cesarbs** [comment]
@chrisowhite Is that when using static files too, or does it fail like that on any request?

**Comment by chrisowhite** [comment]
Seems to be failing like that on any request. In my case I'm hosting IdentityServer4 RC5.

**Comment by chrisowhite** [comment]
I'm still actively building out our idsrv so I'll switch back to 1.1.0 and see if I can get any more details. Also, I'm running Kestrel with SSL.

**Comment by cesarbs** [comment]
@sampsonye @chrisowhite Can you check if the issue repros with this code:

```csharp
using System;
using System.Net;
using System.Net.Http;
using System.Threading;

namespace ConsoleApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            const string file = "<some file>";

            ServicePointManager.ServerCertificateValidationCallback +=
                (sender, cert, chain, sslPolicyErrors) => true;
            ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

            using (var client = new HttpClient())
            {
                var i = 0;
                while (true)
                {
                    Console.WriteLine($"Request {++i} for /{file}");
                    var response = client.GetAsync($"https://localhost:5001/{file}").Result;
                    Console.WriteLine($"Received {response.Content.ReadAsByteArrayAsync().Result.Length} bytes");
                    Thread.Sleep(TimeSpan.FromMilliseconds(500));
                }
            }
        }
    }
}
```

**Comment by chrisowhite** [comment]
I ran the above through several thousand requests of a JS file, even tried with a shorter sleep and was not able to reproduce the issue. Whenever it's happened to me it's not necessarily with a lot of traffic. One odd thing that I noticed is that when my app stops responding to requests while I'm debugging, if I hit Ctrl+C in the console window, it starts working again. If the browser has cancelled the request and disconnected then I'll usually see an exception related to the closed connection in the console, but if the browser is still waiting for a response the application seems to proceed accepting the request as normal after hitting Ctrl+C in the console window.

**Comment by cesarbs** [comment]
This sounds a lot like https://github.com/aspnet/KestrelHttpServer/issues/1259, which sounds a lot like https://github.com/aspnet/KestrelHttpServer/issues/1172.

Is QuickEdit Mode enabled in your console window?

**Comment by chrisowhite** [comment]
Yeah #1259 looks like what I'm seeing. Ctrl+C just happened to be what I tried. I've left work for the day but I'll check and get back tomorrow.

**Comment by benaadams** [comment]
https://github.com/aspnet/Logging/issues/532#issuecomment-268349839
