### ISSUE TITLE
POST request contains no Content-Length header

### ISSUE THREAD

**Issue by Socolin** [aspnet/KestrelHttpServer#1234]
Hi,

The commit https://github.com/aspnet/KestrelHttpServer/commit/a1c598733b4d834a8a36359f52e447e99da2f142 break the requests done to kestrel from curl.

`curl -X POST http://...../`

```
[Microsoft.AspNetCore.Server.Kestrel] Connection id "0HL0KNBLTOHIM" bad request data: "POST request contains no Content-Length header"
```

In this case (withou `-d`) curl does not add Content-Length header

In previous version of asp.net mvc the Json method refuse to response on `POST` request by default, so request should be done as `POST` even with no content.

https://msdn.microsoft.com/en-us/library/ee430920(v=vs.118).aspx

It would be nice to have an option to allow POST/PUT request with no `content-length` to avoid breaking old script and allow simple migration from old mvc to this asp.net core

**Comment by davidfowl** [comment]
Out of curiosity, can you run that script on a few other servers and report what the behavior is?

**Comment by Socolin** [comment]
What other server respond is not the problem.

Problem is, on older mvc version default behavior for Json() was to forbid GET, so it lead to using `curl -X POST` which do not add this header. And now its not working, so older client working with previous mvc don't work with new version, and I really don't see why not considering the missing header as a 0 length body.

I don't understant, the benefit in this change except reducing compatibility with http client like `curl` ?

**Comment by cesarbs** [comment]
From [the spec](https://tools.ietf.org/html/rfc7230#section-3.3.2):

```
A user agent SHOULD send a Content-Length in a request message when
no Transfer-Encoding is sent and the request method defines a meaning
for an enclosed payload body.  For example, a Content-Length header
field is normally sent in a POST request even when the value is 0
(indicating an empty payload body).
```

While not a MUST, it's curl that's not doing the proper thing here.

Other HTTP servers (e.g. IIS, nginx) reject POST requests that don't set `Content-Length` or `Transfer-Encoding: chunked`.

**Comment by muratg** [comment]
We're now following the spec. Closing this one.
