### ISSUE TITLE
Patch Azure IPv6 stack trace log

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1239]
This is a support concern, not a functional issue. Azure Web Sites doesn't allow binding to [::1] and Kestrel binds localhost to both 127.0.0.1 and [::1] by default. The app runs fine but there is a giant error stack trace at the start of everybody's logs that A) alarms them so they ask us about it, or B) they assume caused whatever other issue they were trying to investigate.

https://github.com/aspnet/KestrelHttpServer/pull/1238

I recommend we backport this fix to 1.0.x and 1.1.x to reduce the weekly/daily support hits. @muratg @DamianEdwards

**Comment by DamianEdwards** [comment]
Yes please. Would love this to get fixed if we can do so in a non-breaking way.

**Comment by Tratcher** [comment]
The change only affects the log output, not behavior, so it should be low risk.

**Comment by Tratcher** [comment]
Declined for 1.0.3, check-ins are no longer being accepted.

**Comment by muratg** [comment]
Done in dev. Wasn't approved for patch releases.
