### ISSUE TITLE
Kestrel benchmark - can't saturate machine

### ISSUE THREAD

**Issue by ayende** [aspnet/KestrelHttpServer#1240]
I'm testing out the capacity of our software (which uses Kestrel), and I just did a 40% improvement on one of our handlers, which resulted in ~1% improvement in the req/sec.

So I decided to check where the bottleneck is. I created the following simple program:

```
public class Program
{
    public static void Main(string[] args)
    {
        var host = new WebHostBuilder()
            .UseUrls("http://0.0.0.0:5000")
            .UseKestrel(o =>
            {
                o.ThreadCount = 4;
            })
            .UseStartup<Startup>()
            .Build();

        host.Run();
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            var buffer = Encoding.UTF8.GetBytes("Hello World!");
            app.Run(context => context.Response.Body.WriteAsync(buffer, 0, buffer.Length));
        }
    }
}
```

And then run it with:

    ./wrk http://127.0.0.1:5000 -t 2 -c 256

It did about 130K req / sec on my end, but only used 40% of the CPU.
I then tried it with pipelining:

     ./wrk http://127.0.0.1:5000 -t 2 -c 256 -s pipeline.lua -- 512

And I managed to get about a million req / sec, but we are still talking about the machine being maybe 60% - 80% busy.

I'm assuming that those are unavoidable costs related to slinging packets around and that I just can't send enough here to make a real difference?

Note that just increasing the amount of data that is returned from the request (from 14 bytes to about 100) will have an impact on high pipeline values.

Is this expected / valid?
The Tech Empower benchmark is using a pipeline of 16, and with that I'm only able to get to 509K req/sec.

Am I missing something?

Note that this is running on local host, so it is possible that this is part of the problem.

**Comment by cesarbs** [comment]
cc @mikeharder

**Comment by benaadams** [comment]
Increase wrk's threadcount? `./wrk http://127.0.0.1:5000 -t 16 -c 256 -s pipeline.lua -- 512`

**Comment by mikeharder** [comment]
We recommend using separate machines (physical or virtual) for the server and load generator, for two reasons.  First, the loopback network adapter has different performance characteristics than external network adapters.  Second, the server and load generator will be competing for resources which can skew results.

For TechEmpower Plaintext, we use the following command `wrk -c 256 -t 32 -d 10 -s pipeline.lua http://server:port/url -- 16`.

If the server CPU is still below 95-100%, the most likely bottleneck is networking, either overall bandwidth (Mbps) or packets per second (PPS).

**Comment by ayende** [comment]
Okay, the next thing we'll do it test that on 10GB net

**Comment by mikeharder** [comment]
Correct, it's pretty easy to saturate a 1GB network with Plaintext.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
