### ISSUE TITLE
Receiving “Error -4089 EAFNOSUPPORT address family not supported” in .Net Core 1.1 Web App on Azure

### ISSUE THREAD

**Issue by Umplify** [aspnet/KestrelHttpServer#1242]
After publishing a .Net Core 1.1 Web App to Azure app services, the website cannot be browsed and even a static html file i.e. index.html, etc. cannot be viewed. The log file reads the error message / exception mentioned in the subject line of this issue.

**Comment by Tratcher** [comment]
This is not the error you are looking for, this happens in all Azure Web Apps. Keep digging.
https://github.com/aspnet/KestrelHttpServer/issues/1001
