### ISSUE TITLE
Investigate moving from ConcurrentQueue to ConcurrentBag (post corefx merge)

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1243]
When this is merged to corefx https://github.com/dotnet/corefx/pull/14126 it will be worth revisiting ConcurrentBag vs ConcurrentQueue

**Comment by benaadams** [comment]
Although post this fix https://github.com/dotnet/corefx/pull/14254 ... 😁

**Comment by muratg** [comment]
(Putting in 2.0.0 for timeboxed investigation)

**Comment by benaadams** [comment]
Meh :)
