### ISSUE TITLE
Update readme.md to build KestrelHttpServer and  point sample app to it

### ISSUE THREAD

**Issue by suryagh** [aspnet/KestrelHttpServer#1245]
The document need  to be updated to capture at least:

1. How to  build the `KestrelHttpServer` after this repo is cloned locally.
2. How to point the sample `LargeResponseApp`/ `SampleApp` to the compiled binaries from the `step 1`.

Having this for Windows and Mac would be a nice start

**Comment by davidfowl** [comment]
It does this by default if you just open up the project(s) in any editor, VS code, or VS. Did you have problems?

**Comment by suryagh** [comment]
I tried on VS2017 from Windows 2012 server, the project does not build. 
So, tried to build from the command line; but it throws error related to DMX.
Now, uninstalling VS2017...

On Mac and Ubuntu couldn't get the build via `VS Code`. However, command line does work fine here; but when the sample applications is run, I suspect it is not using the `KestrelHttpServer` instance that I just compiled.

**Comment by davidfowl** [comment]
None of the asp.net core projects work with 2017. They are all still using project.json

**Comment by davidfowl** [comment]
If you run the sample, it's using the kestrel you just built, it's a project reference....

**Comment by suryagh** [comment]
Cool, thank you. Can you please point me the code (project definition) part, I'm curious to know how this is done (or happens).

**Comment by davidfowl** [comment]
How what is done? Project references?

**Comment by suryagh** [comment]
I can see the reference set [here](https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/project.json#L4), but there is no `path reference` to say it to use the local instance of `KestrelHttpServer`.

So, it seems I'm looking at the wrong place :)

**Comment by benaadams** [comment]
@suryagh you are looking for the [global.json](https://github.com/aspnet/KestrelHttpServer/blob/dev/global.json#L2-L4)

**Comment by davidfowl** [comment]
With project.json projects are preferred over packages. Projects are either sibling folders of the same name or folders in the projects path declared in global.json https://github.com/aspnet/KestrelHttpServer/blob/dev/global.json#L3

**Comment by suryagh** [comment]
I see. Will this work if I run the sample app like:
```
~/fork/KestrelHttpServer/samples/SampleApp$ dotnet run
```

Note: my current directory is `.../samples/SampleApp`

**Comment by davidfowl** [comment]
The global.json is found based on directory hierarchy. So yes, the project system walks up the tree until it finds a global.json or nothing.

**Comment by suryagh** [comment]
@davidfowl is this the right command to run the tests?

```
/fork/KestrelHttpServer/test/Microsoft.AspNetCore.Server.KestrelTests$ dotnet run
```


Did this after the `dotnet restore` (on a Ubuntu box), but getting the following error:

```
Project Microsoft.AspNetCore.Server.Kestrel (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Server.Kestrel.Https (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.AspNetCore.Server.KestrelTests (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.1.0'.
```

**Comment by benaadams** [comment]
I think you have to 
```
sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
```
for 1.1

(from https://www.microsoft.com/net/core#linuxubuntu )

**Comment by suryagh** [comment]
@benaadams  Thank you, that helped. Is this the right command to build kestrel and run all the tests> For some reason the script hangs after the "Installation finished successfuly." message.

`./build.sh --quiet verify`

Screenshot of the  terminal from Ubuntu:

![build-sh-hang](https://cloud.githubusercontent.com/assets/5177920/20867397/1817cda4-ba11-11e6-9373-8571102e48c3.png)

**Comment by suryagh** [comment]
@davidfowl do you know the command to run all the tests from a command line/VSCode ? Or point me to somewhere this is captured.
