### ISSUE TITLE
Consider renaming KestrelServerLimits properties to indicate unit

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1247]
Per @blowdart's suggestion in https://github.com/aspnet/KestrelHttpServer/pull/1244#discussion_r90983978

Current                                     | New
--------------------------------- | -----
MaxResponseBufferSize           | MaxResponseBufferBytes
MaxRequestBufferSize             | MaxRequestBufferBytes
MaxRequestLineSize                | MaxRequestLineBytes
MaxRequestHeadersTotalSize  | MaxRequestHeadersTotalBytes
MaxRequestBodySize               | MaxRequestBodyBytes

**Comment by cesarbs** [comment]
@muratg Can you triage?

**Comment by Tratcher** [comment]
Informative, but not sufficiently so to warrant breaking changes.

**Comment by benaadams** [comment]
Introduce a `ByteSize` struct type like `TimeSpan` that can parse `KB` etc and implicitly casts from int/long?

**Comment by benaadams** [comment]
Opened issue for data type https://github.com/dotnet/corefx/issues/14234
