### ISSUE TITLE
Revisit defaults for limits

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1248]
Right now we have a mix of default values in `KestrelServerLimits` that were picked from different places. We should revisit those and assign values we believe to me the most appropriate for our users.

Current defaults and sources for their values:

Option                                       | Default       | Source
---------------------------------- | ------------ | ------------------------------------------
`MaxResponseBufferSize`          | 64 KB          | Non-configurable response buffer size in Kestrel 1.0.0
`MaxRequestBufferSize`             | 1 MB          | Default `client_max_body_size` in nginx
`MaxRequestLineSize`                | 8 KB           | Default `large_client_header_buffers` in nginx (single buffer)
`MaxRequestHeadersTotalSize`  | 32 KB         | Default `large_client_header_buffers` in nginx (4 buffers)
`MaxRequestHeaderCount`        | 100            | Default `LimitRequestFields` in Apache httpd
`MaxRequestBodySize`               | approx. 28.6 MB | Default IIS limit
`KeepAliveTimeout`                    | 2 minutes   |  Default `connectionTimeout` in http.sys
`RequestHeadersTimeout`          | 30 seconds | N/A
`MaxConcurrentConnections`    | Unlimited | N/A
`MaxConcurrentUpgradedConnections` | Unlimited | N/A
`MinRequestBodyDataRate`       | 240 bytes/second w/ 5 second grace period | Default `minBytesPerSecond` in http.sys (the rate - no grace period there)
`MinResponseDataRate` | 240 bytes/second w/ 5 second grace period | Default `minBytesPerSecond` in http.sys (the rate - no grace period there)
Request drain timeout | 5 seconds (non-configurable) | N/A

**Comment by cesarbs** [comment]
cc @muratg

**Comment by benaadams** [comment]
RequestHeadersTimeout **ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_timeout) `client_header_timeout` 60s

**Comment by muratg** [comment]
cc @DamianEdwards @davidfowl @Tratcher @blowdart

**Comment by cesarbs** [comment]
Note: we've removed `MaxRequestBodySize`.

**Comment by cesarbs** [comment]
Should we add this to the 2.0.0 milestone?

**Comment by muratg** [comment]
@shirhatti we need to close on this in the next few days.

**Comment by muratg** [comment]
cc  @blowdart

**Comment by blowdart** [comment]
Ship blocker :) What do you need from me?

**Comment by muratg** [comment]
@blowdart please review the default limits and let us know if you're OK with them!

**Comment by blowdart** [comment]
What about the rate thingy that ended up way too low now async is off? Where's that? It should probably be here too. @cesarbs ?

**Comment by cesarbs** [comment]
@blowdart Yep, I'll update this issue.

**Comment by cesarbs** [comment]
Updated.

**Comment by blowdart** [comment]
240 is such a weird number :) As is 28.6,

But sure, those look ok.

**Comment by benaadams** [comment]
> 240 is such a weird number :) As is 28.6,

256 and 32 are elegant numbers for a more civilized age 😉

**Comment by muratg** [comment]
@cesarbs, please update the defaults (if needed) and :shipit:. :)

**Comment by muratg** [comment]
@cesarbs *ping*

**Comment by muratg** [comment]
Talked to @cesarbs in person, and he'll close this one once the change is in today.
