### ISSUE TITLE
Unobserved task exception ECONNRESET 

### ISSUE THREAD

**Issue by jahmai** [aspnet/KestrelHttpServer#1249]
I'm getting the following exception triggering the TaskScheduler.UnobservedTaskException:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.IOException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---<---

The stack is next to useless but that's not my fault :-)

Seems Kestrel isn't catching or inspecting Task.Exception somewhere.

**Comment by halter73** [comment]
@jahmai Do you have any associated stack trace?

**Comment by jahmai** [comment]
@halter73 Sadly, you're looking at it. I've also stopped in the debugger and it actually looks like the exception wasn't actually "thrown" and so doesn't have a stack trace. Kind of like it was allocated and placed into a TaskCompletionSource and never await'd on.

**Comment by cesarbs** [comment]
@jahmai Are you using HTTPS?

**Comment by jahmai** [comment]
@cesarbs Not in Kestral. We terminate HTTPS at our load balancers and talk to Kestral via HTTP.

**Comment by davidfowl** [comment]
@jahmai do you manually read the request body anywhere?

**Comment by muratg** [comment]
@jahmai *ping*.  Do you read the request body in your code?

**Comment by jahmai** [comment]
@muratg @davidfowl Sorry went on holidays and forgot about work for a while. We found one place where we use Request.Form.Files[0].OpenReadStream(), but don't dispose the Stream. Could this be the cause?

**Comment by halter73** [comment]
@jahmai I doubt it. It's more likely that somewhere there is a call to an async API like Stream.ReadAsync(...) without an await or .Wait().

**Comment by jahmai** [comment]
@halter73 Hmm well we don't use Request.Body at all. There a 3 usages of Request.Form.Files[0] as mentioned previously but the Stream content is consumed immediately. Nothing else directly accessing the Request other than that.

Even in these cases though, anywhere an exception is actually thrown will result in a stack being attached to it. You would have to allocate an exception and place it into a TaskCompletionSource, and then not observe the exception in order to get an empty stack exception in the finalizer. Are there many places in Kestral where this might be the case?

**Comment by jahmai** [comment]
The only suspicious code I can find that might cause this is in Connection.cs:

```
        private void OnRead(UvStreamHandle handle, int status)
        {
            if (status == 0)
            {
                // A zero status does not indicate an error or connection end. It indicates
                // there is no data to be read right now.
                // See the note at http://docs.libuv.org/en/v1.x/stream.html#c.uv_read_cb.
                // We need to clean up whatever was allocated by OnAlloc.
                Input.IncomingDeferred();
                return;
            }

            var normalRead = status > 0;
            var normalDone = status == Constants.EOF;
            var errorDone = !(normalDone || normalRead);
            var readCount = normalRead ? status : 0;

            if (normalRead)
            {
                Log.ConnectionRead(ConnectionId, readCount);
            }
            else
            {
                _socket.ReadStop();

                if (normalDone)
                {
                    Log.ConnectionReadFin(ConnectionId);
                }
            }

            IOException error = null;
            if (errorDone)
            {
                Exception uvError;
                handle.Libuv.Check(status, out uvError);

                // Log connection resets at a lower (Debug) level.
                if (status == Constants.ECONNRESET)
                {
                    Log.ConnectionReset(ConnectionId);
                }
                else
                {
                    Log.ConnectionError(ConnectionId, uvError);
                }

                error = new IOException(uvError.Message, uvError);
            }

            Input.IncomingComplete(readCount, error);

            if (!normalRead)
            {
                AbortAsync(error);
            }
        }

        public virtual Task AbortAsync(Exception error = null)
        {
            // Frame.Abort calls user code while this method is always
            // called from a libuv thread.
            ThreadPool.Run(() =>
            {
                _frame.Abort(error);
            });

            return _socketClosedTcs.Task;
        }

```

Note the call to AbortAsync that isn't awaited and the exception not observed. Probably you want to ContinueWith on the returned task and log any exceptions that arise.

**Comment by davidfowl** [comment]
_socketClosedTcs is never set as faulted. It's only every set is completed successfully. AbortAsync can't return a faulted task.

**Comment by jahmai** [comment]
@davidfowl Right, I missed that. I'm code reviewing in Notepad++ at the moment because my VS2017 installation is broken.

In the Connection.OnRead method, SocketInput.IncomingComplete is called which ultimately places the exception inside the SocketInput._tcs member. That appears to be observed externally by calling SocketInput.CheckFinOrThrow, which is called from Frame<T>.RequestProcessingAsync. In that method the loop condition "while (!_requestProcessingStopping)" seems to be able to be satisfied before CheckFinOrThrow is called, which would leave that SocketInput._tcs member with an unobserved exception.

I could be wrong again though, and doubt I can do any better code reviewing without VS, so I'll leave it at that for now until I can reproduce it better.

**Comment by jkells** [comment]
Connection passes that error to Frame.Abort()
`_frame.Abort(error);`

Which sets it on FrameRequestStream
`_frameStreams?.RequestBody.Abort(error);`

Which is returned from FrameRequestStream.ReadAsync which I'm guessing propagates back to a Read call in the application code.

**Comment by jahmai** [comment]
@jkells It's the _tcs member of SocketInput that needs to be observed, not the exception instance itself, though if the exception was eventually thrown _somewhere_, it should have a stack even when the tcs is finalized.

**Comment by jkells** [comment]
That error which is set in FrameRequestStream is put in a TaskCompletionSource and the associated Task is returned from ReadAsync()

`        private Task<int> ValidateState(CancellationToken cancellationToken)
        {
            switch (_state)
            {
                case FrameStreamState.Open:
                    if (cancellationToken.IsCancellationRequested)
                    {
                        return TaskUtilities.GetCancelledZeroTask(cancellationToken);
                    }
                    break;
                case FrameStreamState.Closed:
                    throw new ObjectDisposedException(nameof(FrameRequestStream));
                case FrameStreamState.Aborted:
                    return _error != null ?
                        TaskUtilities.GetFaultedTask(_error) :
                        TaskUtilities.GetCancelledZeroTask();
            }
            return null;
        }
`

IMO it's that TCS not being observed, not the one on SocketInput.

**Comment by jahmai** [comment]
Possibly, but that relies on a failure to call ReadAsync / WriteAsync _or_ a failure to observe the faulted Task returned. Inside Kestral both of those methods appear to be await'ted on everywhere, so the options are either Kestral doesn't call ReadAsync / WriteAsync leaving that tcs unobserved, or, the Request body is being incorrectly accessed in our controller code somewhere (which I couldn't find).

**Comment by clement911** [comment]
I'm also getting this error from time to time (in azure app service).
But the vast majority of the time (several times an hour), I get a different error message.
It is still raised as an TaskScheduler.UnobservedException:

`Error from NitroCharts.Web2.UnhandledTaskExceptionWatcher: Unobserved task exception: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Threading.Tasks.TaskCanceledException: The request was aborted

--- End of inner exception stack trace ---
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: The request was aborted<---`
