### ISSUE TITLE
Unobserved task exception TaskCanceledException

### ISSUE THREAD

**Issue by jahmai** [aspnet/KestrelHttpServer#1250]
Getting this exception triggered by TaskScheduler.UnobservedTaskException:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Threading.Tasks.TaskCanceledException: The request was aborted
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: The request was aborted<---

I realise how useless that stack is but it's not my fault :-)

This is similar to #1249 except it's much more vague. Given the similarity in lack of a stack trace, I'm making a punt that this is also coming from Kestrel.

**Comment by cesarbs** [comment]
When are you seeing that? Is it while the server is running, or is it during shutdown?

**Comment by jahmai** [comment]
While running. We might get half a dozen per day during normal operation.

**Comment by cesarbs** [comment]
Closing this one. Let's discuss in #1249.

**Comment by clement911** [comment]
I'm getting that same exception multiple times per hour in a prod azure environment.
The other issue #1249 has a different error message...

**Comment by jordanwallwork** [comment]
I'm experiencing something this too on azure, but #1249 doesn't look related. No stack trace for me either, the log just shows:

    System.Threading.Tasks.TaskCanceledException: The request was aborted

I've got no idea where this is coming from, or how to diagnose/fix it, but it's happening about 50 times a day on a reasonably quiet application

**Comment by yufeih** [comment]
I'm getting both this and https://github.com/aspnet/KestrelHttpServer/issues/1249 on prod coming from UnobservedTaskExceptionHandler, thousands of them per day.

```
System.Threading.Tasks.TaskCanceledException: The request was aborted
```

**Comment by aford22** [comment]
I am getting hundreds of thesee per day too. No stack trace either

**Comment by halter73** [comment]
@aford22 What version of Kestrel are you running?

**Comment by aford22** [comment]
@halter73 Nuget tells me its v1.1.2

**Comment by shlomiw** [comment]
I also see it every once in a while, but from an Orleans **client**.
