### ISSUE TITLE
No `UseHttps` function for KestrelServerOptions

### ISSUE THREAD

**Issue by AtheMathmo** [aspnet/KestrelHttpServer#1251]
I'm trying to follow the approach used in the [sample app](https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L41) to run a HTTPS server.

However I am not seeing the `UseHttps` function on the [`KestrelServerOption`](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.server.kestrel.kestrelserveroptions) class. How should I access this function?

**Comment by khellang** [comment]
You need to install the **Microsoft.AspNetCore.Server.Kestrel.Https** package :smile:

**Comment by AtheMathmo** [comment]
Thank you!
