### ISSUE TITLE
ECANCELED operation canceled, received after request completed

### ISSUE THREAD

**Issue by mateanticevic** [aspnet/KestrelHttpServer#1254]
I was trying to test the cancellation token functionality.

```
        public async Task<string> Get(CancellationToken ct = default(CancellationToken))
        {
            await Task.Delay(5000);

            return "ok";
        }
```

Scenario:

- Send HTTP GET request
- Abort
- Inspect CancellationToken at "return ok" break point

Result:

- IsCancellationRequested = false
- CanBeCanceled = true

Console lists the abort event last, after the HTTP request has finished.

Tried to run the same scenario using WebListener and the IsCancellationRequested was true, as expected.

**Comment by cesarbs** [comment]
There's currently a delay there. We're tracking it here: https://github.com/aspnet/KestrelHttpServer/issues/1139

Will be fixed when https://github.com/aspnet/KestrelHttpServer/pull/1218 gets merged.

**Comment by mateanticevic** [comment]
Obrigado Cesar 👍
