### ISSUE TITLE
Kestrel Jamming?

### ISSUE THREAD

**Issue by simonpbond** [aspnet/KestrelHttpServer#1259]
Hi there,

I have converted a standard MVC 6 template to run as self hosted instead of using IIS.
On random occasions throughout the day, the self hosted server just hangs, or jams up.
I take a look at the console window to look at the logs and there are no errors.

The strange thing is, to fix the problem I just have to hit the enter key inside the console window hosting kestrel.

As soon as I hit entered, it continues processing further http requests and everything continues to work fine.

I have no .READLINE() code in my application.

Has anyone experiences this issue with the webserver jamming up and requiring to press enter inside the console to keep it running?

**Comment by cesarbs** [comment]
It's possible that you made a selection on your console window by clicking on it at some point. Similar to https://github.com/aspnet/KestrelHttpServer/issues/1172.

**Comment by simonpbond** [comment]
Cesar, the description of #1172 does sound correct, I will keep testing to confirm. Thanks for proving the link.

However... if the server does jam when text is selected, or the mouse is clicked inside the cmd window, is this behaviour that should be reported as a bug?

Having written a few console applications, I have never experienced jamming from selecting text - although maybe I have just never observed it before.

**Comment by cesarbs** [comment]
That behavior is an unfortunate "feature" of `cmd.exe`. The current process is suspended when it tries to write to standard output and there's a selection on the window.

**Comment by simonpbond** [comment]
Interesting. Thanks for explaining.

**Comment by benaadams** [comment]
Issue with console logger https://github.com/aspnet/Logging/issues/532#issuecomment-268349839

**Comment by sriram5052** [comment]
change the focus to cmd.exe where the kestrel is running and press ESC, the process will resume!
