### ISSUE TITLE
ASP.Net MVC - Total deadlock accessing Kestrel from another machine

### ISSUE THREAD

**Issue by angelsix** [aspnet/KestrelHttpServer#126]
Create any ASP.Net MVC website that serves a cshtml view in a controller action.

The html file returns itself (html) and inside there have some css, js and images (to create multiple embedded HTML requests while the main HTML request is still running).

Run this via dnx . kestrel, accessing it over the same machine is fine. However access it from another machine on the network and it hangs forever.

If you cancel the request with the escape key it shows the HTML loaded fine and everything else hung.

Manually access resources such as the css, js and image files directly by typing in the URL and it works fine (due to it being a single request).

It appears to be a regression bug that existed in an earlier beta 6 version, but now it seems to exist again.

Drop back to beta4 and all works fine with no code or system changes.

**Comment by muratg** [comment]
@halter73 let's try this in beta 6

**Comment by halter73** [comment]
I just tried accessing [MusicStore](https://github.com/aspnet/MusicStore/tree/dev/src/MusicStore) from another machine and things seem to be working with the exception of some SignalR and Tag Helper errors that are logged.

@angelsix Are you still seeing Kestrel hang with the latest beta 6 bits? Thanks.
