### ISSUE TITLE
Memory Leak in 1.1.0

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1264]
Original issue: https://github.com/aspnet/KestrelHttpServer/issues/1260

Should include this in 1.1.1.

**Comment by cesarbs** [comment]
cc @muratg

**Comment by muratg** [comment]
Putting this in 1.1.1 for consideration.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
@muratg please assign.

**Comment by halter73** [comment]
We should make sure that #1311 also gets backported so the fix doesn't break timeouts on 32-bit platforms.
