### ISSUE TITLE
Kestrel not working on shared socket?

### ISSUE THREAD

**Issue by devatwork** [aspnet/KestrelHttpServer#1265]
I'm running Kestrel 1.0.1 configured to `UseHttps`. Now every once all browsers start reporting issues with reset connection or protocol errors. Google Chrome reports it as `ERR_SSL_PROTOCOL_ERROR`.

I finally figured out why this was happening sometimes: Skype. More specifically, if you run Skype (the regular window app) before you launch a Kestrel app running with with https, you can repro the error. Closing Skype and restarting the Kestrel app will solve the protocol errors.

Now there is a setting in Skype to disable using port 80 and 443 if they are available, it is under `Options > Advanced > Connection`. If you uncheck the problem will not occur.

If I try to repro the same behavior using IIS, I get an error when starting the Kestrel program: `Error -4092 EACCES permission denied`.

My guess is that the socket is somehow shared. Shouldn't Kestrel report the port is already in use in such a scenario?

**Comment by davidfowl** [comment]
> Shouldn't Kestrel report the port is already in use in such a scenario?

That's not a thing. There is no port sharing with Kestrel. On windows, components that use http.sys (like IIS) can run on the same port and be separated by path, this isn't supported using raw kestrel (it's pure sockets). I don't know what skype uses (probably uses http.sys on windows).

**Comment by devatwork** [comment]
I'm not following your reasoning: I can consistently reproduce the reported issue across multiple apps and on multiple machines.

I have little experience with Kestrel/Libuv and no experience with the Skype internals, but based on the repro I can only assume that Kestrel/Libuv opens a socket just fine, even though Skype has apparently already opened it.

I can image this could be expected behavior just as well as a bug in one of the involved systems. If it turns out to be expected behavior, we should document it somewhere. If it is a bug, we should address it or report it to team responsible for the system which caused it.

So I ran a few more tests:

The result of `netstat` with just running Skype:

```
netstat -ab
TCP  0.0.0.0:443    PHOBOS:0    LISTENING   [Skype.exe]
```

The result of `neststat` with running Skype first and then my Kestrel app:

```
netstat -ab
TCP  0.0.0.0:443    PHOBOS:0    LISTENING   [FontoXMLStandardDitaEditor.exe]
TCP  0.0.0.0:443    PHOBOS:0    LISTENING   [Skype.exe]
```

The result of `neststat` with running my Kestrel app first and then Skype:

```
netstat -ab
TCP  0.0.0.0:443   PHOBOS:0     LISTENING   [FontoXMLStandardDitaEditor.exe]
```

This proves that both of them are listening on the same port in the 2nd run right? Will in the 3rd run Skype seems to somehow know that an app is already running.

Or am I completely missing something?

**Comment by devatwork** [comment]
I ran some more tests:

When Skype is already started and it has an open connection, the call to `uv_tcp_bind` results in the status code `0`. While doing the same with IIS running on the port, the call to `uv_tcp_bind` results in the status code `-4092`.

Also the issue cannot be reproduced when binding to `localhost`, one needs to bind to machine name.

So my current assumption is that Skype and Libuv somehow can share the port. Any suggestions on how to debug this further?

**Comment by devatwork** [comment]
More tests when binding to `0.0.0.0` the address is being reported as in use with status code `Error -4091 EADDRINUSE address already in use`.

It looks like it may have something to do with https://github.com/libuv/libuv/blob/v1.9.0/src/win/tcp.c#L286, https://github.com/joyent/libuv/pull/1360 and https://msdn.microsoft.com/en-us/library/windows/desktop/ms740621(v=vs.85).aspx.

Does anyone here have experience with this API?

**Comment by benaadams** [comment]
To share 80/443 you have to go via http.sys; it parses all headers and decides where to dispatch request so essentially its more or less like going via IIS (which also goes via http.sys). If you want to port share this way directly without IIS then use `WebListener` rather than `Kestrel` as that's how it works (via http.sys).

If you reuse us the port on windows with `SO_REUSEADDR` then you end up with unreliable connections (except for multicast UDP)

> If the server application forcibly binds using the SO_REUSEADDR socket option to the same port, then the behavior for all sockets bound to that port is indeterminate.

On linux you get round robin dispatch; which works but only if its all the same application; else you end up with unreliable behaviour also.

**Comment by benaadams** [comment]
You could do an `if debug` `UseWebListener` else `UseKestrel`; as I'd guess you won't be running Skype on your server?

**Comment by devatwork** [comment]
I've tested this with a small node app and I can reproduce the same behavior, which means it is not Kestrel specific.

There are plenty of workarounds available, including the ones suggested in the previous comment.

The question is still: do we consider it a bug that Kestrel starts without complaining in this specific scenario, if so we should do a proper root cause analysis, perhaps with the Libuv community and some Winsock experts. If not, this issue can be closed, and consider adding this behavior to the known issue list/faq/documentation somewhere.

**Comment by davidfowl** [comment]
No it's not a bug, it's by design. What behavior do you want to document exactly? If you use kestrel on a port that's already in use that it fails? Or do we just need better error messages and logging?

**Comment by muratg** [comment]
This is by design.
