### ISSUE TITLE
Kestrel becomes unresponsive when running sample under load

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#127]
If you stress the following benchmark app on Kestrel, the server will become unresponsive:

https://github.com/aspnet/benchmarks/blob/31cad22eb72e2673d74a81de32923dc8aef745cb/src/AspNet5/Startup.cs

Kestrel will stop serving new requests and won't quickly exit when Ctrl+C is pressed.

Here are sample `wrk` params that should reproduce the issue when run against the above benchmark app.

    wrk -t12 -c200 -d30s http://{host}:5000

This might be related to https://github.com/aspnet/KestrelHttpServer/issues/126

**Comment by DamianEdwards** [comment]
@halter73 is this still the case? With your fixes in the various branches I'm not seeing any responsiveness issues.

**Comment by halter73** [comment]
This no longer is an issue. [This PR](https://github.com/aspnet/KestrelHttpServer/pull/152/files) might be partly responsible.
