### ISSUE TITLE
[LTS] Deadlock in SocketOutput

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1282]
Original issue: https://github.com/aspnet/KestrelHttpServer/issues/1278

**Comment by cesarbs** [comment]
cc @muratg

**Comment by muratg** [comment]
(Setting milestone to 1.0.3 to reflect the actual package version to be shipped.)

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.
