### ISSUE TITLE
Graceful crashing, logging

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#129]
Log all caught exceptions, keep running where possible.

**Comment by Tratcher** [comment]
RE:
https://github.com/aspnet/KestrelHttpServer/issues/43
https://github.com/aspnet/KestrelHttpServer/issues/25

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L238

**Comment by muratg** [comment]
@lodejard @Tratcher  Are you working on this? If not, @troydai should be able to look into this.

**Comment by Tratcher** [comment]
@halter73 is making some improvements here. #254
