### ISSUE TITLE
LibUV error -14 EFAULT Bad address is system call argument

### ISSUE THREAD

**Issue by mvkra** [aspnet/KestrelHttpServer#1293]
I'm trying to evaluate Kestrel in my application and am getting faults when Kestrel I think is trying to bind to an address and failing at the LibUV layer. I have LibUV 1.10.1 installed.

The error I'm getting is:

System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -14 EFAULT bad address in system call argument
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer (Microsoft.AspNetCore.Server.Kestrel.ServerAddress address) [0x00144] in <43555eec0dc34d2abb4f01227fa5a2e9>:0 
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -14 EFAULT bad address in system call argument<---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -14 EFAULT bad address in system call argument
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer (Microsoft.AspNetCore.Server.Kestrel.ServerAddress address) [0x00144] in <43555eec0dc34d2abb4f01227fa5a2e9>:0 
---> (Inner Exception #0) Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -14 EFAULT bad address in system call argument<---

Not sure if this is a new bug or something I've done wrong here. Any help would be appreciated.

My app code looks like

```
WebHostBuilder()
            .UseUrls("http://127.0.0.1:8083")
            .UseKestrel()
            .UseStartup<Startup>()
            .Build()
            .Run()
```

**Comment by davidfowl** [comment]
Can you be more specific? What OS? What do you mean you have libuv "installed". It comes with .NET Core, did you install your own copy manually?

**Comment by mvkra** [comment]
Sure - using Debian Jessie with Mono 4.6.2.16 using the Nuget package. Wasn't aware .NET Core shipped with LibUV -tried remvoing my LibUV and using that Net Core one via the LD_LIBRARY_PATH and get the same error.

**Comment by davidfowl** [comment]
ASP.NET Core is unsupported and untested. That said, I don't know why you're getting that error. If you could provide specific repro steps for your setup that would be great.

**Comment by moozzyk** [comment]
1.10.1 is a patch release but so far we have not tried running Kestrel on Libuv newer than 1.10.0.

**Comment by cesarbs** [comment]
@davidfowl I think you meant "Mono is unsupported and untested" 😄

**Comment by davidfowl** [comment]
Fixed 😄

**Comment by dls314** [comment]
I think I'm seeing this issue. Before I try to track down an unreleased Kestrel nuget package, @davidfowl Was "Fixed" joking here?

**Comment by gisek** [comment]
> Fixed 😄

@davidfowl Where can I find the fix? I've got the same problem using latest Mono, latest LibUV, and latest Microsoft.AspNetCore.Server.Kestrel

**Comment by davidfowl** [comment]
I meant, fixed my typo. Mono still isn't a platform we test on.

**Comment by newsash** [comment]
My temporary solution:
1. Downgrade Microsoft.AspNetCore.Server.Kestrel to 1.0.3
2. Remove System.Runtime.InteropServices.RuntimeInformation.dll from outputs (because of dotnet/corefx#9012)
3. Downgrade Microsoft.Extensions.Logging.Console to 1.0.2 (because 1.1.1 refuses to use System.Runtime.InteropServices.RuntimeInformation.dll from mono, but 1.0.2 - don't :confused:)
4. It works! :relieved:

**Comment by newsash** [comment]
I referenced wrong issue. Mine was about "W2_32.dll not found" (because of System.Runtime.InteropServices.RuntimeInformation), I'll try to find it.

**Comment by akoeplinger** [comment]
@davidfowl we're blacklisting certain assemblies from certain nuget packages on Mono 4.8+ now because they contain Windows-specific implementation in lib/net45. System.Runtime.InteropServices.RuntimeInformation is one of those on the blacklist, more specifically from the 4.0.0.0 and 4.3.0.0 nuget packages iirc.

Of course this is still a hack and doesn't work e.g. for myget packages etc but it's the best we can do until the packages are fixed (e.g. via dotnet/corefx#15112)
