### ISSUE TITLE
How to solve Redis timouts solution using aspnet core Kestrel

### ISSUE THREAD

**Issue by marcofranssen** [aspnet/KestrelHttpServer#1310]
I'm running into the following issue using redis with aspnet core kestrel and redis.

There is a solution mentioned here, but I wonder what is the recommended way to solve this with Kestrel.

https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Timeouts.md

**Comment by benaadams** [comment]
Thread pool count which can be done with environment variable

e.g.
`export ComPlus_ThreadPool_ForceMinWorkerThreads=2000` (linux)
or
`set ComPlus_ThreadPool_ForceMinWorkerThreads=2000` (windows)

**Comment by davidfowl** [comment]
I'm confused. What's this issue asking? Are you asking how to change thread pool settings on CoreCLR? If so, this has nothing to do with Kestrel per se and should be moved to github.com/dotnet/coreclr

**Comment by marcofranssen** [comment]
I'm running my webapi product using kestrel. The project I created in visualstudio does contain a web.config. Does Kestrel use this web.config, or is this only for the IIS debug options? @davidfowl you might be right it is just a coreclr question if there is no specific Kestrel config option.

**Comment by Tratcher** [comment]
.NET Core does not read the web.config, it's only for IIS settings.

**Comment by davidfowl** [comment]
Kestrel has options but you haven't provided enough details of the actual problem you are experiencing.
