### ISSUE TITLE
Kestrel UvException when loading multiple videos

### ISSUE THREAD

**Issue by muqeet-khan** [aspnet/KestrelHttpServer#1322]
We load bunch of videos on our webpage in no special way, however, noticed kestrel throwing exceptions when doing so. 

```
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HL24E135NAM3" communication error
```

This is followed by an OperationCanceledException as follows:

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.<CopyToAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.<SendRangeAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Warning: The response has already started, the error handler will not be executed.
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An unhandled exception has occurred: The operation was canceled.
```

The `src` for these videos are direct mp4's so I am fairly sure they are being served by static file middleware. sample html as follows:

```
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="embed-responsive embed-responsive-16by9">
                            <video class="embed-responsive-item" preload="metadata" controls>
<source type="video/mp4" src="/Media/videos/53/5451be9e8cbc41b1af616a1dd8fc017c.mp4">
                            </video>
                        </div>
                    </div>
                </div>
```

The video functions properly, however, I am not sure what is causing a connection cancellation. 

Looked at other places in our program where we load single videos and it's not a problem there, leading me to think this may be a problem with multiple video requests. 

I am seeing this on ASPNET Core 1.0 with IIS Express. 

**Update**: I dont see the error If I change the video `preload="none"`

**Comment by cesarbs** [comment]
How large are those videos? This looks like a timeout. IIS is requesting the video from Kestrel but not receiving the response within a given time, then aborting the request to Kestrel. Try increasing the timeout in IIS/ANCM.

**Comment by muqeet-khan** [comment]
Videos are in the range of 30-50 MB each. I get this response in matter of seconds (almost right away). These are all 206 responses so I dint think timeout mattered. Also, it looks all fine on the web end. I will give it a try.

**Comment by benaadams** [comment]
Are they errors in production log rather then test? e.g. could it be users only partially watching and its logging their disconnections?

**Comment by muqeet-khan** [comment]
Yes. It looks like it users who are partially watching the videos.
