### ISSUE TITLE
Resuming Connection on closed socket hides connection reset

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1331]
https://github.com/aspnet/KestrelHttpServer/blob/448a927a0ffdf8f59bbb2770e24757773d85cd8c/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/Connection.cs#L302

**Comment by davidfowl** [comment]
Fixed in https://github.com/aspnet/KestrelHttpServer/commit/a749939be4fc7a2bec620c35cdf816a844233870
