### ISSUE TITLE
Kestrel not working on AWS ECS with dynamic ports

### ISSUE THREAD

**Issue by erick-thompson** [aspnet/KestrelHttpServer#1332]
I am working on getting a Kestrel/Linux based web service running on AWS ECS, from within a Linux container using the default AMI. One of the features of ECS is that you can define the container port, but leave the host port undefined. ECS will then find an open port on the host, and hook up the application load balancer to that port.

When I attempt to get this working, I get a "connection reset by peer" error when attempting to connect to the container, both from the load balancer, and from the container host. If I don't use the dynamic port assignment, and instead specify the host port to same port used in the Dockerfile and for the ASPNETCORE_URLS environment variable, it works perfectly. I understand that this change was made to Kestrel in the RTM timeframe. The change makes sense, as Kestrel should be bound to a specific port, but it breaks this scenario.

I am still researching if it's possible to get the host port from within the ECS container. In the meantime, is there a way to override this behavior, and have Kestrel respond on all ports, or even better, a range of ports? If not, this would be an extremely valuable feature, as right now it limits the ability to run on ECS.

**Comment by cesarbs** [comment]
> is there a way to override this behavior, and have Kestrel respond on all ports, or even better, a range of ports?

At the moment, Kestrel only supports binding to specific ports (or to port 0, which will dynamically assign a port).

**Comment by erick-thompson** [comment]
When binding to port 0, how does the dynamic assignment work? Does Kestrel attempt to find an open port? I'm wondering if I can leverage this somehow.

**Comment by ayende** [comment]
The operation system will choose one for you.
IIRC, you can can configure what ports the system will choose using

cat /proc/sys/net/ipv4/ip_local_port_range


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by erick-thompson** [comment]
Thanks! 

I'm thinking that I could use this to have Kestrel listen to that range of ports (all 30000 of them). I'm not sure what the performance overhead would be of doing this. I can't seem to find the code that checks the port against ASPNETCORE_URLS to see if I have any options for using an array or range.

**Comment by davidfowl** [comment]
Find what code? You'd have to write it yourself. That's not built in.

**Comment by erick-thompson** [comment]
Sorry I wasn't more clear. 

I was trying to track down the code that uses the ASPNETCORE_URLS environment variable. I got as far as WebHost.EnsureServer(), where the value ends up in IServerAddressesFeature.Addresses, but I can't find where the addresses are checked against the current request. 

The reason why I want to find it is that I was thinking about something like the following:
```

// get port range from cat /proc/sys/net/ipv4/ip_local_port_range 
var serverUrls = Enumerable
    .Range(32768, 60999)
    .Select(p => $"http://0.0.0.0:{p}")
    .ToArray();

var host = new WebHostBuilder()
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseStartup<Startup>()
    .UseUrls(serverUrls)
    .Build();

host.Run();

```

But before I do that, I want to make sure I'm not going to be doing a scan of a 30k item array for every request. Or if I am, are there are other options that could make it more efficient. 

Thanks,
Erick

https://github.com/aspnet/Hosting/blob/master/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs

**Comment by davidfowl** [comment]
> I can't find where the addresses are checked against the current request

That doesn't happen.

**Comment by erick-thompson** [comment]
When running in a container on AWS ECS, if you don't specify the correct port you get a connection reset by peer. What is doing the reset? It's not the OS, as the behavior changed between RC1 and RTM.

**Comment by davidfowl** [comment]
No idea, maybe it's a different problem altogether. Did you try turning on verbose logging to see what the logs say?

**Comment by halter73** [comment]
@erick-thompson I second the request for the logs, but it just occurred to me what might be going on.

Can you still make requests from inside the container? If so, I think the difference between RC1 and RTM is that by default in RC1, Kestrel would bind to "http://*:5000". By RTM (and later RCs), Kestrel's default changed to "http://localhost:5000".

In other words, Kestrel now binds to IPAddress.Loopback instead of IPAddress.Any by default, and will not respond to external requests. This was to make Kestrel's default configuration more secure, particularly for the case when Kestrel is running behind a reverse proxy as we recommend.

Not specifying any URL doesn't instruct Kestrel to use dynamic port assignment. As mentioned above, specifying port 0 does that instead (e.g. "http://*:0") though this seems to be a pretty rarely used feature which requires parsing the IServerAddressesFeature to programmatically determine what port was bound to. Without any other configuration, ASP.NET Core will always bind to port 5000.

**Comment by erick-thompson** [comment]
I must have missed the ability to specify 0 as a port. I'm planning to try this and see if I can't get dynamic ports working in ECS. I'll update the thread once I test it out.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
