### ISSUE TITLE
HTTPS connections are very slow in Kestrel 1.0.X on .NET Framework

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#1335]
# Repro Steps
1. Create an application targeting Kestrel 1.0.X and .NET Framework which listens on both HTTP and HTTPS endpoints.  Sample at https://github.com/mikeharder/KestrelHttpsPerf.
2. Ensure the matching .NET Framework Developer Pack is installed (http://getdotnet.azurewebsites.net/target-dotnet-platforms.html).
3. Build and run.
4. From a Linux machine, run "wrk -c 256 -t 32 -d 10 http://server:port/path".  RPS should be normal.
5. Run the same wrk command against the HTTPS endpoint.  No responses will be sent.  Server CPU is 0%.

# Notes
* Only repros with Kestrel 1.0.X on .NET Framework.
  * Doesn't repro with Kestrel 1.0.X on on .NET Core.
  * Doesn't repro with Kestrel 1.1.0 on .NET Framework.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.
