### ISSUE TITLE
Question: .net 4.6.1 use Vector from nuget package or Vector from framework assembly?

### ISSUE THREAD

**Issue by KLuuKer** [aspnet/KestrelHttpServer#1337]
Imagesharp switched from using the Vector nuget package to the Vector from the .net 4.6.1 assembly in https://github.com/JimBobSquarePants/ImageSharp/pull/84
only when targeting 4.6.1 applications

and since kestrel is still using Vector from nuget and doesn't have a .net 4.6.1 target (only 4.5), i'm stuck and cannot update to the lastest imagesharp package

now the big question: is there any performance difference while having a app target .net 4.6.1 and using the Vector nuget package VS the Vector from the 4.6.1 assembly

if there is @JimBobSquarePants will most likely bring the perf hammer down and switch back to the nuget version.
and if there is no difference would you consider adding a .net 4.6.1 target and use the assembly vector instead of the nuget one?

**Comment by mellinoe** [comment]
The nuget version and the in-box version of System.Numerics.Vectors/System.Numerics should unify; there is no overlap in what they provide. The types are factored like this:

# In-box `net461`
* System.Numerics.dll: Contains `Vector2/3/4`, `Quaternion`, `Plane`, `Matrix4x4/3x2`
* System.Numerics.Vectors.dll: Only a facade type-forwarding those 7 types to System.Numerics.dll
* Note: There is no `Vector<T>` in any in-box assembly, this is always shipped in the nuget package.

# NuGet Package
* `netstandard1.0`: System.Numerics.Vectors.dll containing all of the types.
* `net461`: System.Numerics.Vectors.dll containing `Vector<T>` and type-forwards for the rest.

Does that make sense?

> since kestrel is still using Vector from nuget and doesn't have a .net 4.6.1 target (only 4.5), i'm stuck and cannot update to the lastest imagesharp package

I don't actually understand what you mean. Could you clarify?

> would you consider adding a .net 4.6.1 target and use the assembly vector instead of the nuget one?

Given that Kestrel uses `Vector<T>`, it's not possible to use just the in-box assembly, because that type isn't available there.

**Comment by KLuuKer** [comment]
that makes allot of sense

my app is a mvc core app with project.json targeting framework 4.6.1 ("net461")
in my dependencies i have ImageSharp (1.0.0-alpha1-00054) and Kestrel (1.1.0)
and i end up using System.Numerics.Vectors (4.3.0) according to my reference list in VS2015

if i update to the latest ImageSharp it ends up using version System.Numerics.Vectors (4.0.0)
and i when start debugging i end up with the following exception (i have to empty bin&obj and the lock files and let it rebuild for this to happen)

```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.AspNetCore.Hosting.dll

Additional information: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

**Comment by mellinoe** [comment]
What is the version of System.Numerics.Vectors.dll that is deployed next to your application, if it's there at all?

Would you be able to share a minimal repro that I could try out?

**Comment by KLuuKer** [comment]
after publishing System.Numerics.Vectors.dll has file version: 4.6.24705.1 

i will try making a repro

**Comment by KLuuKer** [comment]
@mellinoe 
here it is https://github.com/KLuuKer/VectorVersionRepro

**Comment by mellinoe** [comment]
@KLuuKer That seems to work fine for me. I cloned the repo, ran `dotnet restore, `dotnet build -f net461`, and was able to run the executable under `bin\net461\net461\win7-x64`. What steps are you running, and what version of `dotnet` do you have?

**Comment by KLuuKer** [comment]
@mellinoe i updated the readme

**Comment by KLuuKer** [comment]
i am online on gitter pm me

**Comment by mellinoe** [comment]
I believe the root problem is that ImageSharp declares that it uses `System.Numerics.Vectors` in its `frameworkassemblies` section, which is not necessary. This is preventing System.Numerics.Vectors.dll from being deployed. I tested removing System.Numerics.Vectors.dll from the frameworkassemblies section of ImageSharp's nuspec, and it then worked correctly.

Taking a step back, I don't think I fully understand the rationale behind https://github.com/JimBobSquarePants/ImageSharp/pull/84, but perhaps we should continue the discussion over there.

**Comment by KLuuKer** [comment]
you are the smart guy over here, so go for it

**Comment by JimBobSquarePants** [comment]
@mellinoe Yeah, move the discussion to there if you like. I find it confusing and I want to get this right.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
