### ISSUE TITLE
double headers when using middleware & calling itself through httpclient

### ISSUE THREAD

**Issue by funkycoding** [aspnet/KestrelHttpServer#1342]
Hi,
Not sure if this is the right repo nor if it is an issue.

 I was playing around with middleware, and i have an issue in which i get back double headers... for example:

**double X-Powered-By**
![double headers](https://cloud.githubusercontent.com/assets/307410/22664851/c04abe40-ecb2-11e6-9a2a-3f92dfe16e28.PNG)

Double content in Vary header
![doubleheaders_1](https://cloud.githubusercontent.com/assets/307410/22664880/d7e42582-ecb2-11e6-8e63-9a24dd4165b2.PNG)

The first one comes from the repo i've added to this ticket, the second one comes from our own code and couldn't repo it right away, but it probably is in the same area.

**What i do?**
Attach a piece of middleware in a seperate branch
From that middleware, call a controller (in that same app)

Can we figure out if this is either a bug or me doing something wrong? If the latter, please let me know what :smile:

Regards,
Mark

PS For some reason, github doesn't like me uploading the repo. Here is the onedrive link:
https://1drv.ms/u/s!Ao72i2duel8vgcRQ3ljryybUytOfRw

**Comment by Tratcher** [comment]
Looks like you should also add Vary and X-Powered-By to your _ignoredResponseHeaders list.

**Comment by funkycoding** [comment]
@Tratcher it be that easy? :squid: Is there any handy list or information about the headers that are being set by kestrel / aspnet? I mean, when i review the headers before it jumps over te wire there is no double Vary or X-PoweredBy header.
