### ISSUE TITLE
SSL Mutual Authentication in .NetCore 1.1 Kestrel

### ISSUE THREAD

**Issue by SudharsanN** [aspnet/KestrelHttpServer#1344]
I am trying to implement SSL mutual authentication using Kestrel web server in a MVC project. In order to do so, I created self signed client and server certificate on my local machine. I enabled SSL settings in Program.cs by using the ClientCertificateMode equals RequiredCertificate enum. After this when I browse a endpoint from browser, it prompts for a certificate and when I choose an invalid certificate, I can see HTTPS authentication failed message in the console and in log file but still the request is being processed and the JSON output is rendered back. Below is the piece code for SSL authentication.

```csharp
var host = new WebHostBuilder()
                         .UseConfiguration(config)
                         .UseKestrel(options =>
                         {
                            var signingCertificate = new X509Certificate2("\\ServerCert.pfx", "Test123");
                            HttpsConnectionFilterOptions httpsOptions = new HttpsConnectionFilterOptions();
                            httpsOptions.ServerCertificate = signingCertificate;
                            httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                            options.UseHttps(httpsOptions);
                          })
                          .UseContentRoot(Directory.GetCurrentDirectory())
                          .UseStartup<Startup>()
                         .Build();
host.Run();
```
What needs to done to prevent the request from getting processed when SSL authentication fails? Since the MVC project will be consumed within our domain network, we are okay to expose Kestrel as the front facing web server.

**Comment by Tratcher** [comment]
RequireCertificate is insufficient, the client did send you a certificate. You need to actually inspect the certificate to make sure it meets your criteria and is for the right user. See HttpContext.Connection.ClientCertificate.

**Comment by SudharsanN** [comment]
Should this be done as part of middleware?  Can you please point me to some samples?

**Comment by SudharsanN** [comment]
@here Can someone point me to samples on checking client certificate through HttpContext? Should this be done as part of middleware?

**Comment by pradeepneo** [comment]
@Tratcher The kestrel server itself is authenticating the certificate as server https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsConnectionAdapter.cs#L93

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
Oh interesting. If it fails then the request should stop IMO.

**Comment by Drawaes** [comment]
I believe that it doesn't.  Instead you get no client certificate in your httpcontext.connection.clientcertificate property. From there it's simple to make middle-aged that rejects you

**Comment by blowdart** [comment]
OK thinking a bit more I think this needs a client cert authentication middleware. It's not really a server concern to make decisions, except perhaps "This cert is revoked, oh heck no", but even then if you're not creating an identity from the cert you're not authenticating or authorizing or acting on it.

**Comment by SudharsanN** [comment]
@Drawaes  HttpContext.Connection.ClientCertificate property still holds the client certificate that was passed in the middleware. It's not NULL.

**Comment by Drawaes** [comment]
No but you can validate it there. Is the Certificate invalid or just wrong?
Eg does the client have the private key for the cert?

**Comment by halter73** [comment]
In case you missed it, you can set `HttpsConnectionFilterOptions.ClientCertificateValidation` which is a `Func<X509Certificate2, X509Chain, SslPolicyErrors, bool>`. Return true if you want to accept the client certificate; false otherwise. The `ClientCertificateValidation` is called in [SslStream's RemoteCertificateValidationCallback ctor argument](https://msdn.microsoft.com/en-us/library/ms145056(v=vs.110).aspx).

**Comment by SudharsanN** [comment]
@halter73  I am planning to use HttpsConnectionFilterOptions.ClientCertificateValidation. By this way, I don't have to introduce a middleware.

**Comment by SudharsanN** [comment]
@halter73 Can you please let me know what authentication is done in the below code ?https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsConnectionAdapter.cs#L93

Is it just validating the root issuer of the client by comparing it against the server certificate?
Also, the callback HttpsConnectionFilterOptions.ClientCertificateValidation will be invoked after or before the above call?  Whether the callback will be invoked irrespective of client certificate being valid or not? 

The reasons I would like to know the above is , in the callback that I am writing should I just do some basic validation like checking the Subject, Issuer properties of the certificate? Or, I should replicate entire logic present in the AuthenticateAsServerAsync method?

**Comment by Drawaes** [comment]
It is only defering to SslStream. If you look in SslStream I think you might find

```
_remoteCertificateOrBytes` = certificate == null ? null : certificate.RawData;
            if (_userCertificateValidationCallback == null)
            {
            if (!_sslState.RemoteCertRequired)
            {
                sslPolicyErrors &= ~SslPolicyErrors.RemoteCertificateNotAvailable;
             }
             return (sslPolicyErrors == SslPolicyErrors.None);
            }
            else
            {
                return _userCertificateValidationCallback(this, certificate, chain, sslPolicyErrors);
            }
```

So I think you will get basic SChannel validation that the certificate is not out of date, and isn't in your list of bad certs, anything else will pass through and you will need to validate to your own criteria.

I could be wrong though.

**Comment by halter73** [comment]
@SudharsanN If you set ClientCertificateValidation, it's your responsibility to check  the SslPolicyErrors flags if you care about them. Without a ClientCertificateValidation callback, Kestrel will require the are no SslPolicyErrors flags set.

Presumably SslStream uses SChannel/OpenSSL to set the SslPolicyErrors flags, but I'm not sure exactly what's being validated at that layer for client certificates.

**Comment by xavierjohn** [comment]
In my case, context.Connection.ClientCertificate is null 
Powershell> Invoke-WebRequest https://localhost:44303/api/values -Certificate $cert

I tried HttpsConnectionFilterOptions with a callback but the function is not getting called.
@SudharsanN: How did you get  context.Connection.ClientCertificate to contain the certificate?

**Comment by Drawaes** [comment]
In my case I used the Http client from .net so I would say it's an issue with the invoke web request. 

Did you check with wireshark or fiddler that your client is sending the cert?

**Comment by xavierjohn** [comment]
Could you post your sample on github?
Invoke-Request should have worked. I also tried a .net client.
https://msdn.microsoft.com/powershell/reference/5.1/microsoft.powershell.utility/Invoke-WebRequest

The code I tried.
        static void Main(string[] args)
        {
            var handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.SslProtocols = SslProtocols.Tls12;
            handler.ClientCertificates.Add(new X509Certificate2("../SampleCert.pfx", "password"));
            var client = new HttpClient(handler);
            var result = client.GetAsync("https://localhost:44367/api/values").GetAwaiter().GetResult();
        }

**Comment by Drawaes** [comment]
Sure. When I get home later I can try to make a sample. Can you give me the asp.net core version you are using?

**Comment by Drawaes** [comment]
I see it's 1.1 I will try to make a sample. I am using it in prod code so  ant copy paste

**Comment by xavierjohn** [comment]
Thanks...  I have tried 2 different sample on two different machines but no success.
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
and

<PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
 </PropertyGroup>

It feels like UseKestrel options seems to have no effect. It seems to behave the same no matter what I put in the options.

**Comment by xavierjohn** [comment]
Finally got it to work by NOT using IIS Express and using the below code... 
```
                .UseKestrel(options =>
                {
                    HttpsConnectionFilterOptions httpsOptions = new HttpsConnectionFilterOptions();
                    httpsOptions.ServerCertificate = certificate;
                    httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                    httpsOptions.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
                    options.UseHttps(httpsOptions);
                })
```

If I don't give the SslProtocols.. It gives error "The client and server cannot communicate, because they do not possess a common algorithm"

This article said not to use IIS Express
http://www.blinkingcaret.com/2017/03/01/https-asp-net-core/

**Comment by Drawaes** [comment]
Normally to get the browser to ask the server side has to list the CA's it will accept certificates from not sure how you can configure that with SSLStream or if it's even possible.

**Comment by xavierjohn** [comment]
I have wrote a sample here 
https://github.com/xavierjohn/ClientCertificateMiddleware
Next steps is to figure out how to create claims based on the client certificate.

**Comment by xavierjohn** [comment]
I noticed client certificate is not getting passed to the code when run in Azure Web App. 
I also saw this post
https://github.com/aspnet/Announcements/issues/69
•	The HttpPlatformHandler currently does not forward client certs (this will be a future enhancement)

Are any of you running it in Azure Web App?

**Comment by Tratcher** [comment]
@xavierjohn that's not a Kestrel related issue, you don't use Kestrel's HTTPS implementation in Azure Web Apps (e.g. in IIS).

**Comment by xavierjohn** [comment]
Could someone share there web.config to get Client Cert to work under IIS Express and Azure  Web App Services?
Thanks.
