### ISSUE TITLE
IDX10803: Unable to obtain configuration from https://<domain>/.well-known/openid-configuration

### ISSUE THREAD

**Issue by mikeesouth** [aspnet/KestrelHttpServer#1352]
Hi. I'm getting this error when upgrading from `Microsoft.AspNetCore.Server.Kestrel` 1.0.0 to 1.1.0. It's a security related issue but I'm posting here since it seems to be related to this specific package.

I'm using the auth0 framework for authentication (auth0.com). I've followed this auth0 guide for .NET Core Web API authentication: [ASP.NET Core Web API Authentication](https://auth0.com/docs/quickstart/backend/aspnet-core-webapi).

I'm including `Microsoft.AspNetCore.Authentication.JwtBearer` but both 1.0.0 and 1.1.0 versions of this library works as long as `Microsoft.AspNetCore.Server.Kestrel` is kept at 1.0.0. As soon as I upgrade Kestrel to 1.1.0 I get this error:
```
System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://mydomain.eu.auth0.com/.well-known/openid-configuration'.
```

Do I need to add something more to my intialization process in addition to the configuration that is specified in the auth0 guide? The only code I'm adding is this:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    var options = new JwtBearerOptions
    {
        Audience = Configuration["auth0:clientId"],
        Authority = $"https://{Configuration["auth0:domain"]}/"
    };
    app.UseJwtBearerAuthentication(options);

    app.UseMvc();
}
```

**Comment by Tratcher** [comment]
Please don't open duplicate issues. We can move the issue once we decide which component is causing the problem.
