### ISSUE TITLE
Is there a reason Closed Connection Adapter should be hidden?

### ISSUE THREAD

**Issue by Drawaes** [aspnet/KestrelHttpServer#1354]
I have two libraries that straight away need the same functionality as

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsConnectionAdapter.cs#L151

Does it need to be a private nested class?

**Comment by halter73** [comment]
I hadn't considered that other adapters would want this, but it makes sense that they would.

I expected the first complaint to be about there being no basic AdaptedConnection class with a settable Stream property and a no-op PrepareRequest method.

**Comment by Drawaes** [comment]
And the closed stream... are you reading my whiteboard?

**Comment by Tratcher** [comment]
Out of curiosity, what are you building?

**Comment by Drawaes** [comment]
All bad bad things... :)

TLS libraries, windows auth without IIS or Http.sys... looking at kerb for linux next

[Leto a better? Https Library]( https://github.com/Drawaes/Leto/blob/master/samples/SampleASPNetServer/Program.cs#L20)

[Windows Auth without HTTP.sys or IIS](https://github.com/Drawaes/CondenserDotNet/tree/master/src/CondenserDotNet.Server.WindowsAuthentication)

[Blog on writing the TLS13 Library](https://cetus.io/tim/TLS-Time-to-make-our-keys/)

**Comment by muratg** [comment]
@shirhatti could you schedule a design meeting?

**Comment by Drawaes** [comment]
No reason for the close?

**Comment by davidfowl** [comment]
We're making this API pubternal for 2.0.0 and this can easily be replicated with the public surface that's there today

**Comment by Drawaes** [comment]
Cool. Good to have an answer for the close :)
