### ISSUE TITLE
what's failing kestrel to run on heroku 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [aspnet/KestrelHttpServer#1357]
I have created an new asp.net core project and it runs on locally but fails when deployed to heroku. Please see this issue and help me understand this problem. What's causing this [issue](https://github.com/friism/dotnet-buildpack/issues/4)

**Comment by halter73** [comment]
This issue was moved to aspnet/Razor#994

**Comment by halter73** [comment]
@AbhimanyuAryan Kestrel happens to be the think at the bottom of the stack reporting the error. The exception is being thrown from Razor where I moved your issue. It might help you to enable the [developer exception page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling#the-developer-exception-page) on a private staging heroku server so you don't need to grab the logs to see exception details.
