### ISSUE TITLE
Investigate "socket read" errors during Plaintext benchmark

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#1360]
`wrk` reports a small number of "socket read" errors during the Plaintext benchmark.  These can be seen in the official results (https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=plaintext) and reproduced locally.

I was able to reproduce on my first try using a pair of Azure F4 VMs:

```
$ wrk -H 'Host: localhost' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 256 --timeout 8 -t 32 http://10.1.0.4:8080/plaintext -s ~/pipeline.lua -- 16
Running 15s test @ http://10.1.0.4:8080/plaintext
  32 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.50ms   47.29ms 542.68ms   97.22%
    Req/Sec    21.06k     2.54k   33.62k    93.45%
  Latency Distribution
     50%    3.42ms
     75%    4.96ms
     90%    5.98ms
     99%  307.84ms
  9670805 requests in 15.10s, 1.19GB read
  Socket errors: connect 0, read 17, write 0, timeout 0
Requests/sec: 640478.70
Transfer/sec:     80.63MB
```

**Comment by halter73** [comment]
Potentially related, but these were write instead of read errors: https://github.com/aspnet/KestrelHttpServer/issues/142#issuecomment-142783133.

**Comment by cesarbs** [comment]
Self-assigning.

**Comment by muratg** [comment]
Closing this as we plan to move to Sockets transport in 2.1.

@DamianEdwards, reactivate if you'd like to keep this open!
