### ISSUE TITLE
Kestrel unable to bypass corporate proxy when run behind IIS

### ISSUE THREAD

**Issue by zemien** [aspnet/KestrelHttpServer#1368]
A common web.config setting for intranet apps that need to talk to Internet services, are the default proxy settings:
```
<system.net>
    <defaultProxy enabled="true" useDefaultCredentials="true">
        <proxy usesystemdefault="true" proxyaddress="http://xxx.xxx.xxx.xxx:1234" bypassonlocal="true"/>
    </defaultProxy>
</system.net>
```
However, this does not seem to get passed on to Kestrel, for understandable reasons. But this means my external requests fail with 407 Proxy Authentication Required.

On the other hand, my app works if I run Kestrel standalone via the dotnet command. It seems to follow IE's Connection settings automatically.

Question: How to get Kestrel via IIS to refer to IE's proxy settings? Alternatively, how can I affect the system.net configuration changes?

**Comment by davidfowl** [comment]
I have a few questions:

- Are you using .NET Framework or .NET Core?
- Which outgoing requests are you trying to impact?

**Comment by zemien** [comment]
Hey David,

I'm using .NET Core, and I'm just doing a simple HttpClient GetAsync request. Looking at wireshark logs the request gets intercepted by the proxy (WebMarshal).

**Comment by zemien** [comment]
The microservice's project.json for reference
`{
  "dependencies": {
    "AutoMapper": "5.2.0",
    "AutoMapper.Extensions.Microsoft.DependencyInjection": "1.2.0",
    "Microsoft.AspNetCore.Cors": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Mvc.Versioning": "1.0.3",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Shared": "1.0.0-*"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by davidfowl** [comment]
1. Kestrel has nothing to do with http client settings. It handles incoming requests not outgoing requests.
2. .NET Core does not have a configuration system for the BCL. `web.config` only works for IIS specific settings, not the settings so the `system.net` section will be ignored.
3. This bug should be on github.com/dotnet/corefx since that's where the HttpClient issues are being tracked.

You'll likely need to change the proxy settings in code (which I know can be a problem in some situations).

**Comment by zemien** [comment]
@mynkow sorry I have forgotten how I got around it but IIRC I joined an
alternative wifi network that did not have a web proxy.
