### ISSUE TITLE
Unable to start Kestrel.

### ISSUE THREAD

**Issue by anuraj** [aspnet/KestrelHttpServer#1374]
I am trying with Heroku - Docker deployment. I build the solution and pushing the image to server and starting the Kerstrel. But I am getting error like this.

> 2017-02-20T06:07:54.034009+00:00 heroku[web.1]: Starting process with command `dotnet helloworld-aspnetcore.dll --server.urls http://\*:\39094`
> 2017-02-20T06:07:56.759685+00:00 app[web.1]: [41m[1m[37mcrit[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[0]
> 2017-02-20T06:07:56.759703+00:00 app[web.1]:       Unable to start Kestrel.
> 2017-02-20T06:07:56.759711+00:00 app[web.1]: System.AggregateException: One or more errors occurred. (Error -13 EACCES permission denied) ---> 

Here is my docker file.

```
FROM microsoft/dotnet:runtime
WORKDIR /helloworld-aspnetcore
COPY output .
CMD ["dotnet", "helloworld-aspnetcore.dll","--server.urls","http://*:$PORT"]
```

The web app is a Web Application created using `dotnet new` command

Here is the full stack trace if required.

[stacktrace.txt](https://github.com/aspnet/KestrelHttpServer/files/786690/stacktrace.txt)

**Comment by cesarbs** [comment]
With Docker you should bind to the loopback interface and map a port from the host to your container.

**Comment by cesarbs** [comment]
This looks weird: `http://\*:\39094`

Instead of using `--server.urls`, can you try setting the `ASPNETCORE_URLS` environment variable with the address to bind to?

**Comment by anuraj** [comment]
Yes if I set the environment variable it is working. But why `--server.urls` is not working? It won't working in any particular environment?

**Comment by halter73** [comment]
It's the backslashes that look suspect. Are you sure that heroku is unnescaping the `--server.urls` param?

**Comment by anuraj** [comment]
Yes. It is happening same of the environment variables as well. 

Here is the log right now.

> 2017-02-22T06:28:02.279227+00:00 heroku[web.1]: State changed from down to starting
> 2017-02-22T06:28:07.215627+00:00 heroku[web.1]: Starting process with command `/bin/sh -c ASPNETCORE_URLS\=http://\*:\21626\ dotnet\ helloworld-aspnetcore.dll`
> 2017-02-22T06:28:11.168654+00:00 app[web.1]: Hosting environment: Production
> 2017-02-22T06:28:11.168671+00:00 app[web.1]: Content root path: /app
> 2017-02-22T06:28:11.169005+00:00 app[web.1]: Now listening on: http://*:21626
> 2017-02-22T06:28:11.169008+00:00 app[web.1]: Application started. Press Ctrl+C to shut down.
> 2017-02-22T06:28:11.665774+00:00 heroku[web.1]: State changed from starting to up

It is escaping the environment variables as well. But right now Kestrel is working :)

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
