### ISSUE TITLE
Check if the request was aborted before logging Content-Length mismatch errors

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1387]
See https://github.com/aspnet/KestrelHttpServer/issues/1376#issuecomment-281529214

Applies only to "too few bytes written" errors.

**Comment by cesarbs** [comment]
@muratg We should make this a patch for 1.1.2.

**Comment by muratg** [comment]
@cesarbs https://github.com/aspnet/KestrelHttpServer/issues/1376 is triaged to 1.1.2 milestone.  Closing this one. (Also, let's make sure that the fix also is in dev branch)
