### ISSUE TITLE
Unable to use System.Net.NetworkCredential inside docker using Kestral

### ISSUE THREAD

**Issue by BharatRajMeriyala** [aspnet/KestrelHttpServer#1420]
I am trying to authenticate my call to a SSRS report server hosted outside the docker application. And to accress the report I do the following:

HttpWebRequest webRequest = WebRequest.Create(sTargetURL) as HttpWebRequest;
webRequest.Credentials = new NetworkCredential(strReportUser, strReportUserPW);
WebResponse HttpWResp = await webRequest.GetResponseAsync();

But I continuesly get 401 unauthorized.

The approach of NetworkCredentials works fine when I am doing the same inside my Azure Hosted App service and also my local.

I suspect this is because I start my docker usung the command below, it internally maps the port 5000 to port 80 for outside world, when I run the container:
docker run  -d –p 80:5000 app/myApp:v1.0.0

The credentials that I set on the header inside the docker environment, simply do not carry forward upto the report server and I get the error.

**Comment by davidfowl** [comment]
Kestrel doesn't have anything to do with this issue (kestrel handles inbound request, not outbound). I recommend filing an issue on https://github.com/dotnet/corefx

**Comment by BharatRajMeriyala** [comment]
So you mean to say its Kestral doesn't deal with the way I set my NetworkCredential into the request? But isn't Kestral supposed to be a replacement to IIS which can both issue requests and access requests?

**Comment by davidfowl** [comment]
> So you mean to say, Kestral doesn't deal with the way I set my NetworkCredential into the request? But isn't Kestral supposed to be a replacement to IIS which can both issue requests and access requests?

What server side behavior are you expecting when you set the network credentials on the web request? What type of auth are you doing? Basic auth?

Does it "work" outside of docker? If yes, what does "working" look like?

**Comment by BharatRajMeriyala** [comment]
When I paste the SSRSReport server URL into the browser, the browser asks me for username and password to access the report on the report server.

Outside docker this works fine. Inside docker I am of the opinion that we use Kestral server provided to run dotnet core application and not the IIS that works on my local machine with Visual Studio and on app service hosted at Azure.

On checking the request response stack on fiddler I think this is NTLM based authentication between the browser and report server.

**Comment by davidfowl** [comment]
Is this docker on windows? Kestrel doesn't handle NTLM auth today and it's not the one rejecting your request with a 401. Sounds more like IIS?

**Comment by BharatRajMeriyala** [comment]
This is Docker on Linux. 

Yes you are correct its not Kestral rejecting the request with 401. Its the SSRS report server. But the request to access the Report Server URL is launched from Dot net core application running inside the docker running on linux. and I expose port 5000 through my docker file. Port 5000 is the port Kestral uses to run the dotnet core application.

Basically this code that I am talking about, is running on my dotnet core application which is expected to launch a request to SSRS report using the network credentials set in the request through WebRequest library of dotnet core.

HttpWebRequest webRequest = WebRequest.Create(sTargetURL) as HttpWebRequest;
webRequest.Credentials = new NetworkCredential(strReportUser, strReportUserPW);
WebResponse HttpWResp = await webRequest.GetResponseAsync();

**Comment by davidfowl** [comment]
Then corefx is the right repository to ask these questions.
