### ISSUE TITLE
Kestrel and IIS Express handle URI slash character encoding differently

### ISSUE THREAD

**Issue by TylerJBrown192** [aspnet/KestrelHttpServer#1425]
When making a HTTP request from a client to a .NET Core project where the request URL has encoding characters in it, Kestrel and IIS Express handle the request strings differently. Note: I have not tested if this occurs in the query parameters, but it does occur in the request path.

dotnet CLI and the Kestrel server will maintain the encoding characters as they are (e.g. `GET /api/vehicles/cars%20%2F%20trucks` to get 'cars / trucks'), whereas IIS Express running in Visual Studio 2015 Update 3 will maintain the whitespace encoding characters (%20) but will serialize the slash encoding character (%2F) as a forward slash literal.

**Comment by Tratcher** [comment]
Kestrel has the correct behavior. This is a long standing complaint against IIS/Express and Http.Sys.
