### ISSUE TITLE
Is URL #fragment Supported?

### ISSUE THREAD

**Issue by hismichael** [aspnet/KestrelHttpServer#1430]
I didn't find the URL fragment part in HttpContext or the IFeatureCollection object. Shouldn't #fragment be a legitimate URL component?

**Comment by davidfowl** [comment]
See https://github.com/aspnet/HttpAbstractions/issues/33

**Comment by Tratcher** [comment]
No, HTTP does not allow fragments to be sent to the server, they are only for client side navigation.

**Comment by hismichael** [comment]
Thanks
