### ISSUE TITLE
How to log something to stdout?

### ISSUE THREAD

**Issue by tinganho** [aspnet/KestrelHttpServer#144]
I'm just curious how do I log something to stdout? I cannot get debugging messages with `Console.WriteLine(...)`. All it says is:

```
$ dnx . kestrel
Started
```

**Comment by smbecker** [comment]
Add a reference to Microsoft.Framework.Logging.Console and add a call to AddConsole extension method on ILoggerFactory.

**Comment by tinganho** [comment]
Just added this lines of code in my ASP.NET 5 application:
```
//This method is invoked when ASPNET_ENV is 'Development' or is not defined
//The allowed values are Development,Staging and Production
public void ConfigureDevelopment(IApplicationBuilder app, ILoggerFactory loggerFactory)
{
    loggerFactory.AddConsole(minLevel: LogLevel.Warning);
}
```
