### ISSUE TITLE
Add tests to verify binding to default address when one loopback is already bound to port 5000

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1452]
As a follow-up to https://github.com/aspnet/KestrelHttpServer/pull/1451#pullrequestreview-25352477

**Comment by JunTaoLuo** [comment]
It's tricky to replicate the expected behaviour in the tests. We fail to start localhost if either of the localhost addresses (ipv4 and ipv6) is already bound. However, if we receive an UVException that is not EADDERINUSE then we try the other address and only fail if neither address works.

**Comment by muratg** [comment]
@JunTaoLuo Is this good to close now?

**Comment by JunTaoLuo** [comment]
We did not come up with a good way to test this. As mentioned above, it's hard to reproduce the expected behaviour.

**Comment by cesarbs** [comment]
Oh yeah, this was about trying to replicate the behavior we see in Antares (where we fail to bind on IPv6 but not due to EADDRINUSE and just log a warning). EADDRINUSE is already covered in existing tests.
