### ISSUE TITLE
Make the code in ListenerSecondary less intense

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#146]
It's very hard to verify correctness, and it's likely unmaintainable

See #145

**Comment by benaadams** [comment]
Resolved by https://github.com/aspnet/KestrelHttpServer/pull/320 which has been merged?

e.g. https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/ListenerSecondary.cs

**Comment by muratg** [comment]
:+1:
