### ISSUE TITLE
MSCVRT12.DLL

### ISSUE THREAD

**Issue by NoralK** [aspnet/KestrelHttpServer#147]
**Suggestion**

In the README.md you might mention that the "Visual C++ Redistributable Packages for Visual Studio 2013" is a prerequisite to run Kestrel on Windows Machines.  It would also be good to list the minimum .Net Framework as well.  I am working on Windows boxes with no software installed except .Net 4.5.2, the beta runtimes/packages, Node.js and Visual Studio Code.

**Comment by moozzyk** [comment]
This should be fixed now that we build libuv differently. The changes should be in the next Kestrel build and in the final beta-8 bits.
