### ISSUE TITLE
Primary headers

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1482]
Add `Accept` and `Connection` the Request primary headers

**Comment by davidfowl** [comment]
Agreed, surprised they weren't to begin with. Why is that?

**Comment by benaadams** [comment]
They weren't plaintext headers :)

**Comment by natemcmaster** [comment]
I must be missing something....isn't Accept already a primary request header?

https://github.com/aspnet/KestrelHttpServer/blob/200d8debc005bac2c15424b20c6b7bb4a50483cc/tools/CodeGenerator/KnownHeaders.cs#L130

**Comment by benaadams** [comment]
Ok, just connection then :)

**Comment by cesarbs** [comment]
That blank line there was just waiting to have Connection inserted in it.
