### ISSUE TITLE
Move IConnectionFilter to internal namespace

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1495]
This API is going to change a bunch so we should internalize it.

**Comment by Drawaes** [comment]
So you can't write connection filters anymore? I have them in prod so there will be a version of released kestrel that can't be extended?

**Comment by davidfowl** [comment]
> So you can't write connection filters anymore? I have them in prod so there will be a version of released kestrel that can't be extended?

It's already broken in 2.0. We *could* keep them public and break them again in the next version but I'd rather not do that. The .Internal namespace lets you write filters but tells you this isn't the final API.

**Comment by Drawaes** [comment]
Ahh so .internal but not internal class modifier... cool have at it

**Comment by muratg** [comment]
@DamianEdwards Are you OK with this?  This will prevent breaking users (again) when we expose pipelines in the future.
