### ISSUE TITLE
Write tests for methods added during improving socket output performance

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#1508]
In this PR: https://github.com/aspnet/KestrelHttpServer/pull/1504
/cc @davidfowl

**Comment by muratg** [comment]
Two tests:
- Write numeric
- Write ASCII

**Comment by natemcmaster** [comment]
I'm looking at the unicode issue. @davidfowl you seemed to thing the Unicode + WriteAscii method is okay. What was the justification?

Before #1504, we used Encoding.ASCII.GetBytes which does a range change on data and replaces out-of-range characters with '?'. The new implementation doesn't range check. 
Comparison:
```
Before: WriteAscii("ñ٢⛄⛵") => "????"
After:  WriteAscii("ñ٢⛄⛵") => "ñbõÄ"
```

The concern here is that it's possible this method will transform non-ascii into ascii, e.g. `٢` => `b`.
cc @benaadams

**Comment by benaadams** [comment]
@natemcmaster as per current Kestrel. 

They are response headers and [ValidateHeaderCharacters](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Http/FrameHeaders.cs#L237-L259) is run on them when they are added to the collections (so they throw an exception in user code when added if not ascii) so there is no need to check them again on output.

**Comment by davidfowl** [comment]
@natemcmaster if you want to feel better about the method, you can rename it to `WriteAsciiNoValidation`

**Comment by natemcmaster** [comment]
Thanks for clarifying.
