### ISSUE TITLE
Add flag to disable synchronous IO 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1521]
Because blocking threads is bad so we want a way to turn this off synchronous IO by default to let you shoot yourself in the foot if you want this behavior.

**Comment by benaadams** [comment]
`throw new NotWiseException()`?

**Comment by Drawaes** [comment]
Throw new Bang (Target.Foot)

**Comment by DamianEdwards** [comment]
@davidfowl you planning to get this added this week?

**Comment by davidfowl** [comment]
@DamianEdwards I'm not sure we can do this for preview. There's too much churn and too many other important things to do in Kestrel right now (like stabilize the build).

**Comment by muratg** [comment]
@davidfowl @DamianEdwards We'd like to punt this out to 2.1.  That OK with you guys?

**Comment by muratg** [comment]
Talked to @DamianEdwards in person, we'll try to do this in 2.0.0.
