### ISSUE TITLE
[1.1.2] "Unexpected end of request content" preventing terminating chunk from being sent

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#1535]
Original issue: https://github.com/aspnet/KestrelHttpServer/issues/1530.

We should fix this in Kestrel 1.1.2.

**Comment by muratg** [comment]
@Eilon, this is a patch candidate.

cc @davidfowl

**Comment by muratg** [comment]
Assigning to @halter73 because @cesarbs is OOF this week.

https://github.com/aspnet/KestrelHttpServer/issues/1544 is the issue tracking 1.0.4 fix.

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
