### ISSUE TITLE
FrameRequestStream - Seek not supported

### ISSUE THREAD

**Issue by joseftw** [aspnet/KestrelHttpServer#1548]
Hello, [I've created a repro of the problem here ](https://github.com/joseftw/dotnetcore-streamissue)

I have a middleware where I look at the request body, I read the body to a string and then I validate that it's valid json.

If it's valid, I rewind the stream and then call next.Invoke.

This works perfectly in my integration tests where I use new TestServer...

But when I then startup Kestrel and use postman and sending the same request, I recieve the following error:

An unhandled exception occurred while processing the request.

NotSupportedException: Specified method is not supported.
Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestStream.Seek(long offset, SeekOrigin origin)

When I debug I can see that context.Request.Body is of type **MemoryStream** when I run my tests.
When I run Kestrel the stream is of type **FrameRequestStream** and it seems that it doesn't support the Seek method?

1. Is this expected behaviour?
2. If so, how can I read a request body in my middleware and then rewind it?
3. Why does the behaviour differ between TestServer and actuall results?

**Comment by Tratcher** [comment]
By design, the server does not buffer the request body by default. There are a few tools that can help you do this.
https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.Http/Internal/BufferingHelper.cs#L41

**Comment by benaadams** [comment]
Call `request.EnableRewind()`?

Though you really want to be calling `await xxx.ReadToEndAsync()` rather than [`xxx.ReadToEnd()`](https://github.com/joseftw/dotnetcore-streamissue/blob/master/StreamIssue/StreamIssue/JsonValidationMiddleware.cs#L29) on line 29

**Comment by joseftw** [comment]
Thanks guys! :)
