### ISSUE TITLE
Edge-readiness Tracking Question

### ISSUE THREAD

**Issue by antmdvs** [aspnet/KestrelHttpServer#1567]
Hi, what's the best way to track Kestrel's edge-readiness, (i.e. get a unified view of all the issues that are precluding lifting the reverse proxy recommendation)? Would it make sense to add an "edge-readiness" label or something to that effect?

**Comment by cesarbs** [comment]
@muratg

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
We don't list all the issues, because, despite our recommendations, you know someone somewhere is going to have it hanging out over the internet, and a list would just be a nice list of things to attack.

**Comment by muratg** [comment]
@antmdvs We'll announce the readiness on aspnet/announcements repo once we're ready. :)

**Comment by antmdvs** [comment]
@muratg, @danroth27 alluded that this was done (https://youtu.be/ry_vrIn9RBI?t=13m59s). Are you able to check that all-important checkbox in https://github.com/aspnet/Announcements/issues/243?

**Comment by muratg** [comment]
@antmdvs We implemented most of the features in preview2 and you should see more details when we release 2.0.0-preview2.  We'll have a couple more tweaks for 2.0.0 RTM.

Please note that preview2 does not have a go-live license, so while it's good for testing, I recommend waiting until 2.0.0 RTM to take this to production.
