### ISSUE TITLE
How to configure purge policy on stdOut.log files?

### ISSUE THREAD

**Issue by varcario** [aspnet/KestrelHttpServer#1568]
Does Kestrel support defining a purge policy on the stdOut.log files it writes.  So if I need to make sure my server doesn't run out of disk space.  Can I set a rolling file policy with a limit on the number of files I would like to retain, writing a new file each day, and a max disk space policy that deletes oldest files first when the max limit is met.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#83

**Comment by benaadams** [comment]
Kestrel doesn't write any log files; the logging component does https://github.com/aspnet/Logging and there are adaptors for various types which handle that sort of thing for example [serilog](https://serilog.net/), [NLog](http://nlog-project.org/), etc

Unless you are using console logger and going via AspNetCoreModule stdout mapping; which you probably shouldn't do for production
