### ISSUE TITLE
PipeOptions controlled by Transport/ConnectionHandler

### ISSUE THREAD

**Issue by tmds** [aspnet/KestrelHttpServer#1574]
I am implementing a Transport and this is what I'd like to do:
```
        PipeOptions InputPipeOptions = new PipeOptions()
        {
            // Limit prefetching to a single receive
            MaximumSizeHigh = 1,
            MaximumSizeLow =  1
        };

        PipeOptions OutputPipeOptions = new PipeOptions()
        {
            // Buffer as much as we can send in a single system call
            // Wait until everything is sent.
            MaximumSizeHigh = MaxSendLength,
            MaximumSizeLow = 1
        };
```
This isn't possible because:
- the input prefetching is tied to the protocol: https://github.com/dotnet/corefxlab/issues/1355
- the Transport isn't in control of these values (the ConnectionHandler is)

**Comment by davidfowl** [comment]
You don't get to control both sides of the pipe options here (which we already discussed). We won't be taking any action here in the short term.

**Comment by tmds** [comment]
From the discussion I failed to understand if this is something that will be considered at some point. Since the issue wasn't close, I'll assume it will. If the design stays as-is, I'd like to understand why because this change makes sense in my head. No problem if this isn't at the top of the list.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by davidfowl** [comment]
@tmds we can revisit this once we have implemented the body pipes.
