### ISSUE TITLE
[Announcement] The Kestrel package/namespace has been renamed to Microsoft.AspNet.Server.Kestrel

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/KestrelHttpServer#159]
Discussions for https://github.com/aspnet/Announcements/issues/53

**Comment by Michael-DST** [comment]
That namespace looks awesome. :)  I have been impressed with the organization and namespaces I have seen so far. :+1: 

Quick question from a newb: is "Kestrel" also the same as references to "K" that have been used throughout the history of this project?  Is there a link/backstory behind this for the curious?

**Comment by halter73** [comment]
"Project K" was the old code name for ASP.NET 5 as a whole. The k command was what is now dnx.

The fact that Kestrel happens to start K is a happy coincidence as far as I know. @lodejard or @davidfowl probably know whether or not this was intentional.

**Comment by davidfowl** [comment]
We like birds

**Comment by NeelBhatt** [comment]
awesome! Use of "Kerstel" is limited to local development or it would be used in production in future?

**Comment by Eilon** [comment]
@NeelBhatt the goal is both.

**Comment by developer1998** [comment]
I've noticed that --config option to store settings in another file is no longer supported. 
like
Server = Microsoft.AspNet.Server.Kestrel
Server.Urls = http://191.145.10.145:5000
```
"Microsoft.AspNet.Server.Kestrel --config hosting_local.ini"
```

**Comment by Tratcher** [comment]
@developer1998  `--config` is still supported, but the file format was changed to json.  If you don't specify the `--config` option RC1 will look in `hosting.json` by default.

**Comment by developer1998** [comment]
@Tratcher thanks, do you have a link to schema to see what is supported, or give me a sample... Thanks

**Comment by developer1998** [comment]
I've figured out the JSON
```
{
    "server": "Microsoft.AspNet.Server.Kestrel",
    "server.urls": "http://196.145.2.133:5000"
}
```

**Comment by Tratcher** [comment]
FYI: https://github.com/aspnet/Hosting/issues/453

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
