### ISSUE TITLE
Change request trace ID format

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#1591]
Follow up to https://github.com/aspnet/KestrelHttpServer/pull/1578. In this PR, we Kestrel started generating request IDs instead of letting aspnet/Hosting do this. At the moment, request IDs use the same code to generate connection ID and request ID.

We want to enhance this change further by making the requestID to the following format:

```c#
//pseudocode
var count = ++_connection.RequestCount;
HttpContext.TraceIdentifier = $"{_connection.ConnectionId}:{count.ToString("X").PadLeft(5, '0')}";
```

Result:
```
Connection 1 Id = 001BCA
  Request 1: Id = 001BCA:00000
  Request 2: Id = 001BCA:00001
...
  Request 11: Id= 001BCA:0000B

Connection 2 Id = 001BCB
  Request 1: Id = 001BCB:00000
  Request 2: Id = 001BCB:00001
```

In the unlikely event there are more than 0xFFFFF (1,048,575) requests per connection, the counter must not truncate to 5 characters, but use as many characters required to express request count in hex.

**Comment by muratg** [comment]
Let's make it future-proof. (`PadLeft(10, '0')`) maybe?

**Comment by muratg** [comment]
@shirhatti FYI. We should connect this with the ETW work you're planning in ANCM.

**Comment by natemcmaster** [comment]
Decided to go with this:
```
//pseudocode
uint count = ++_connection.RequestCount;
HttpContext.TraceIdentifier = $"{_connection.ConnectionId}:{count.ToString("X8")}";
```
The X8 format represents the full range of info in `uint`. 
FYI - `uint.MaxValue` is 4.2 billion.
