### ISSUE TITLE
Implement IHttpSendFileFeature

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1593]
This could be done by reading from a file pipeline and appending the buffers to the output pipeline? (Cutting out most of the stream busy work)

/cc @davidfowl

**Comment by davidfowl** [comment]
Breaks with SSL that's why we don't do it today

**Comment by tmds** [comment]
On Linux, true sendfile (i.e. kernel copying fd to fd), doesn't support encryption. Don't know how it is on Windows.
So it would be nice to be able to provide an http only sendfile at the Transport.

**Comment by Tratcher** [comment]
On Windows SendFile with a raw socket doesn't get you encryption either, but Http.Sys does have an implementation that support encryption.

**Comment by Drawaes** [comment]
So does BSD. Go look up how Netflix got HTTP working, inserting crypto in the sendfile pipe. TBH it is a non goal anyway. You can lift the buffers into userspace with technologies like RIO and PD, encrypt in userspace and cache in userspace.

**Comment by benaadams** [comment]
Doesn't need the actual SendFile api; just doesn't need to go through the full stack.

Frame implements `IHttpSendFileFeature`; Kestel reads file straight into output (pipe buffers)
KestelHttps overrides Kestrel's `IHttpSendFileFeature` reading into the TLS output(pipe/stream)

Currently up stack it reads from file into an array, then passes the array to Kestrel which then copies it to the output buffers. Implementing `IHttpSendFileFeature` means you can copy out a step of copying; also allocation for the read buffers.

**Comment by tmds** [comment]
It can be optimized at different levels.
- If http, most Transports can do the work.
- If https, some Transports can do the work.
- If the Transport can't do the work, improved kestrel implementation.

**Comment by muratg** [comment]
We don't plan to do this. Eventually the middleware could be made to expose pipelines.
