### ISSUE TITLE
Access to raw headers.

### ISSUE THREAD

**Issue by random-username** [aspnet/KestrelHttpServer#160]
I'm wondering if there are plans on adding the ability to access raw headers in Kestrel like ALL_RAW in IIS does.

I ask because I'm building a system to detect potentially dangerous traffic and one of the metrics is based on how raw headers are delivered to the server.

This is an edge user case, so I understand if there are no plans to add this to Kestrel, and since it's open source I can add this capability myself, but I thought I would ask.

**Comment by Eilon** [comment]
In the meantime we generally recommend putting such protections at an edge server, such as a proxy/firewall (e.g. nginx).

**Comment by random-username** [comment]
Thanks Eilon for your quick reply and for adding this to the backlog, it's much appreciated.

**Comment by benaadams** [comment]
@random-username 
The header values are as Raw (the string chars are values between 0-255 as per the raw bytes)

The header names capitalization are set for the pre-set group (group here https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/FrameHeaders.Generated.cs#L16-L59)

Other header names will be set to their first occurrence capitalization if they occur more than once.

**Comment by benaadams** [comment]
Related https://github.com/aspnet/KestrelHttpServer/issues/594
