### ISSUE TITLE
VS 2017 ASPNETCORE_URLS is ignored

### ISSUE THREAD

**Issue by kubal5003** [aspnet/KestrelHttpServer#1604]
I have an issue with starting Kestrel server from VS2017. In VS2015 in `launchSettings.json` I was able to set the port like this:

    "Kestrel": {
      "launchUrl": "http://localhost:5010/api",
      "environmentVariables": {
        "ASPNETCORE_URLS": "http://localhost:5010"
    }

Now this setting is ignored by kestrel. If I change the name of the setting to: `"ASPNETCORE_SERVER.URLS"` I'm getting the warning about the setting being deprecated, which suggests that the `launchSettings.json` file is still being processed.

I also tried other options of setting the port - setting environment variable (`ASPNETCORE_URLS`) still works, but using `dotnet run --server.urls http://0.0.0.0:5010` doesn't.

**Comment by Tratcher** [comment]
Here's a repro using the latest template:
```
    "WebApplication70": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://localhost:5401"
      },
      "applicationUrl": "http://localhost:32329"
    }
```
Note VS 2017 automatically sets ASPNETCORE_URLS to the applicationUrl, and this takes precedence over the env variable you specified. You shouldn't need to set the variable yourself.

Also, WebHostBuilder automatically reads environment variables but not command line params. If you want the command line params to work you need to build that config provider in your Main method and pass it to WebHostBuilder.UseConfiguration.

**Comment by kubal5003** [comment]
I'm not sure if I understand - does that mean that the logic in kestrel did not change, but what's different is how VS processes the launchSettings.json ?

That would mean that if I had no value for applicationUrl then the setting ASPNETCORE_URLS was overwritten with empty value.

**Comment by Tratcher** [comment]
Correct, Kestrel/Hosting did not change, VS did. What address does it end up starting on for you? http://localhost:5000? That's Kestrel's default?

**Comment by muratg** [comment]
cc @BillHiebert

**Comment by leak** [comment]
The current state is rather displeasing. I wouldn't want VS to interfere with the overriding mechanic of IConfigurationRoot at all. Personally i have the listening URL in a config.json and right now there are two unfortunate effects:

1) The value of my config file is ignored altogether because of the forceful setting of ASPNETCORE_URLS

2) The Debug page in VS forces you to enter a value otherwise you can't save your other changes at all

Is there any chance this will be changed?

**Comment by BillHiebert** [comment]
@leak  I opened an issue internally (TFS [410354](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=410354)) to look at improving this.

**Comment by Tratcher** [comment]
@leak You can change the priority of env variables vs config by reordering the config code providers in Startup:
https://github.com/aspnet/Templates/blob/c91664a01f6b429b9ff3ac17cacd906037f11b19/src/BaseTemplates/StarterWeb/Startup.cs#L21

**Comment by leak** [comment]
I'm aware of that option, but shouldn't a sane system always be

Command Line > Environment > Config ?

**Comment by poonampatilExt** [comment]
Hi,
We have build with .net core 1.1 in by using VS 2017 Professional Edition. If we deploy it in IIS its working fine but when try to host in docker then we are getting below error.
Error:
**warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to HYPERLINK "http://localhost:5000/"http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)**  
Can u please advise me on this?

**Comment by cesarbs** [comment]
@poonampatilExt `localhost` will attempt to bind to both the IPv4 and IPv6 loopback interfaces. If IPv6 is not available or fails to bind for some reason, you will see that warning. Try binding to 127.0.0.1 instead, that should get rid of the warning.
