### ISSUE TITLE
Revert workaround for "Kestrel tests fail with `unable to load DLL 'libuv'` on net46 and CLI 2.0.0-preview1-005685 or newer"

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#1618]
Once "Explicit RID still required for .NET Framework test projects (https://github.com/dotnet/sdk/issues/909)" is fixed, the workaround added for "Kestrel tests fail with `unable to load DLL 'libuv'` on net46 and CLI 2.0.0-preview1-005685 or newer (https://github.com/aspnet/KestrelHttpServer/issues/1617)" should be reverted.

**Comment by muratg** [comment]
@natemcmaster is tracking this across several repos. Closing this one.
