### ISSUE TITLE
Notification needed to identify when the server is listening and ready to accept web requests.

### ISSUE THREAD

**Issue by budcribar** [aspnet/KestrelHttpServer#1631]
We have an app with Kestrel and an embedded web browser control. We would like some way to be notified that the server is accepting requests before we surf to the index.html with the embedded web browser control. Any ideas ?

**Comment by Tratcher** [comment]
This is all in the same process, right? Resolve the IApplicationLifetime service and hook ApplicationStarted
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/IApplicationLifetime.cs

**Comment by budcribar** [comment]
Perfect.. thanks Tratcher
