### ISSUE TITLE
Kestrel listeners

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#1645]
I'm writing a multitenant application and would like to dynamically start/stop kestrel listeners on a given IP/PORT is this possible? if so how/if not would/could there be a work around or feature added to support this with the refresh of kestrel?

**Comment by grahamehorner** [comment]
maybe an option would be to include methods of 

Start( endpoint ) - a listener on a given endpoint

Stop( ) - all listeners
Stop( endpoint ) - stop a listener on a given endpoint

Restart( ) - restart all listeners 
Restart( endpoint ) - restart a listener on a given endpoint 

to the IServer interface; having these methods exposed would allow for the developer to control things like turning on/off administration ports dynamical at runtime by way of some external/secured trigger (azure message queue) and more

**Comment by davidfowl** [comment]
You can't change the end point during the call to Start/Stop, nor can you restart the server. That would require some bigger design changes that we don't plan to do. There is working happening here to add a Stop method for different reasons, https://github.com/aspnet/Hosting/pull/995. We could look at allowing restart after stop but would require some more thought.

Why do you need this functionality? What are you building?

**Comment by grahamehorner** [comment]
Thanks for pointing out the aspnet/Hosting#995; We are developing a multitenant application where the tenant administrator(s) have the ability to remote control the availability of endpoint services, we have a requirement to allow NON technical business administrators to turn on/off functionality/services according business needs; one example is a requirement to have security administration endpoints disabled by default for the tenant and only enabled via a two factor authentication process; for a limited duration and for a given action with is recorded in a configuration management log.

BTW, this idea came for a business security person as a reduce surface of attack requirement; so I don't really have the level of knowledge/experience/seniority in this area to override/argue against them ;)

**Comment by Drawaes** [comment]
I do, and would... it's a somewhat stupid idea that security will be provided through shutting down a listening endpoint in Kestrel. What stops someone from using anyone of the other endpoints to access the same code?

Aside from that... if you really want to have your situation work (which seems a bad idea from your security people but hey)... why don't you run another kestrel in the same process with the endpoint and dispose it when you are done?

**Comment by grahamehorner** [comment]
@davidfowl could the _transports not be changed into a IDictionary key on the endpoint; and the the transport could be started/stopped created/bound dynamically?  the Start<TContext> would need to change to hold the type of the initial call; so to verify when call subsequent times the TContext is of the same type; 

to start stop create endpoint simply pass the new listenOptions to start ?
or explicitly call start/stop/create( listenOptions )

just thinking aloud

**Comment by grahamehorner** [comment]
@Drawaes I'm of the same opinion but need some hard points on why it's not advisable; or going against what they are saying is best practise for reduce surface of attack ?

BTW, all endpoints are also protected using OpenIDConnect so simple turning on the endpoint or access other endpoint wont get you access to the tenant services.

**Comment by Drawaes** [comment]
Sure but what does having a separate endpoint give you? Anyway that aside why not run more than 1 kestrel in proc?

**Comment by Drawaes** [comment]
You wouldn't like my argument which is if you want reduced attack surface it should run out of process in another process, And but shutdown there and the code should never be available in the "lesser" privileged process... But not sure that will make your life easier ;)

**Comment by grahamehorner** [comment]
@Drawaes We may have a reasonable idea here that would keep the security people happy ;) We are think that we'll automated via script of a docker the build/start-up of the tenant administrator portal; complete separation of concern :D

**Comment by grahamehorner** [comment]
oh, just been asked about multi-homing now :'( feeling like ground-hog-day

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
