### ISSUE TITLE
Obtaining HttpContext within ClientCertificateValidation

### ISSUE THREAD

**Issue by pwen090** [aspnet/KestrelHttpServer#1647]
We have an asp.net core self hosted application within Kestrel. Part of the configuration is using .ClientCertificateValidation functionality of HttpsConnectionFilterOptions. We have the func override and validation happening correctly for client certificates but within our validation function we need to obtain HttpContext so that we can add an asp.net identity role to the connection whose certificate we just validated.

How do we obtain HttpContext or perform such functionality within the .ClientCertificateValidation function? Normally we would do dependency injection but given ClientCertificateValidation is specified as part of the .UseKestrel options within our Program.cs Main() it does not seem that dependency injection is available? thank you

Originally asked on stackoverflow: http://stackoverflow.com/questions/43227978/how-to-get-httpcontext-from-within-function-performing-clientcertificatevalidati

**Comment by Drawaes** [comment]
Do it in 2 phases... validate the cert in the validate... then middleware for the user identity.

**Comment by pwen090** [comment]
We originally were doing certificate validation as middleware but that seemed to invoke on every request vs. initial session establishment; therefore was a performance hit. We moved to ClientCertificateValidation because that seems to only call validation once per session establishment. 

When you say to do the user identity in middleware - is there a way to do that only once when the session is established vs. every request?

**Comment by Drawaes** [comment]
Then you need to write a connection adapter... and inject something in the features collection you can drag out

**Comment by pwen090** [comment]
Thanks @Drawaes I will look into that! Anyone else from Microsoft have other recommendations here? Is custom middleware and or connection adapter the only path forward?

**Comment by pwen090** [comment]
Has anything changed possibly related to this in asp.net core 2.0? thank you

**Comment by khellang** [comment]
I still think @Drawaes' solution is the way to go. Do the validation in the delegate, then pull out `HttpContext.Features.Get<ITlsConnectionFeature>` and set the user identity using the `ClientCertificate` in middleware.

**Comment by Tratcher** [comment]
What you're asking isn't possible with the HTTP protocol. The ClientCertificateValidation runs before the HTTP request is even received. You can do the validation in there, but you'll need middleware to associate it with a user on a per-request basis.

**Comment by Drawaes** [comment]
You could write a connection adapter and  attach it as a feature. But I wouldn't I would just make the middleware

**Comment by pwen090** [comment]
We ended up going the middleware route. We host two WebHostBuilder within our single project on different ports. One that is https for normal "front end" user authentication. And a second WebHostBuilder that is doing client certificate auth (for backend services that connect). For the second instance we leveraged middleware similiar to what is done here:
 https://github.com/xavierjohn/ClientCertificateMiddleware

Essentially this ties back to another discussion with @Tratcher in issue #1162 In that IIS handles this more easily with being able to do client cert on some paths and not others. I realize this is not possible with Kestrel given it leverages SslStream and can only negotiate client SSL during initial handshake. Is it crazy to even consider that Kestrel might at some point allow client cert negotiation in the same way IIS does? Happy to open a feature request but maybe this is to unique a case and not in the realm of consideration?

**Comment by Drawaes** [comment]
This is just my opinion and I have no say/influence but anyway

I don't think you will see this anytime soon if ever and here is why.

It's not supported by SslStream at all. SslStream supports the otherside triggering a renegotiation but not triggering one itself so would require an API design/Review and implementation.

With that Http/2 actually completely disallows the practice, so any service using this mechanism will be completely boxed into Http1.1. The solution we use is similar to yours, in that different ports/IP addresses have different authentication mechanisms with a shared trusted cert for server2server and NTLM/Kerberoes for SSO users. 

(Don't tell anyone but we actually use the same port and IP but that might make people 😱 ;) )

**Comment by pwen090** [comment]
@Drawaes that is what I am thinking re: SslStream, guy has to dream though! Makes sense on server2server via cert etc... your last comment though can you expand on it? I would think there would be errors in binding two WebHostBuilder's to the same port and IP? or are you not using Kestrel in that case?

**Comment by Drawaes** [comment]
We are using non ssl and ssl. Ssl for server to server and ntlm/kerb for client browsers... there is a trick.. the first byte tells you what type of connection it is. But it's not something for the faint hearted, but taken from the go protocol muxing idea. Another thought with sni coming soon maybe that is your solution. You server to server connections can use a different host name and therefore a separate set of certificates. That is http/2 compliant.

**Comment by Drawaes** [comment]
If you feel like reading a ton of discussion on SSLStream including SNI there is some here

https://github.com/dotnet/corefx/issues/23177

It's an active discussion around an API proposal to allow for ALPN and potentially SNI.
