### ISSUE TITLE
Pool UvWriteReq objects

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/KestrelHttpServer#165]
It might help.

**Comment by AspNetSmurfLab** [comment]
Was started here https://github.com/aspnet/KestrelHttpServer/tree/shalter/write-req-pool

**Comment by benaadams** [comment]
Resolved by #363 Resuse writes, initalize queues

**Comment by muratg** [comment]
Thanks @benaadams

**Comment by benaadams** [comment]
@muratg is in PR "SocketOutput Allocation Reductions" #466 which is currently unmerged.

**Comment by halter73** [comment]
I plan on merging this today. I just wanted to make sure others got a chance to look at the combined PR.

**Comment by muratg** [comment]
:+1:
