### ISSUE TITLE
Delay config of listen options until server starts

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#1654]
Currently ListenOptions are configured immediately when Listen is called. We should delay this until we have determined to use the ListenOptions or IServerAddressesFeature since we may be throwing away the configured endpoints in https://github.com/aspnet/KestrelHttpServer/blob/99278c469161370b1015c67d18ae9388591a49af/src/Microsoft.AspNetCore.Server.Kestrel.Core/KestrelServer.cs#L119. This could potentially help when configuring HTTPS for Kestrel, see https://github.com/aspnet/KestrelHttpServer/issues/1290. 

cc @glennc @danroth27 @muratg

**Comment by Tratcher** [comment]
Scenario: Kestrel is configured for https with a cert file for development, but then the app is published to IIS and that cert is not needed/appropriate. Even running the app in IIS Express would fail today if the self-host cert was not present, which is unnecessary.

**Comment by Tratcher** [comment]
Fixed by https://github.com/aspnet/KestrelHttpServer/pull/2003/files#diff-319ef184f2f31b202bc2f4566a710afe ?

**Comment by davidfowl** [comment]
Yes
