### ISSUE TITLE
Website is not updated till server restart

### ISSUE THREAD

**Issue by firedeepan** [aspnet/KestrelHttpServer#1660]
I have configured reverse proxy to kestrel with nginx. When I redeploy the new DLLs using a script the site is not getting updated. I can see only the old site. When I try to kill dotnet process also it doesn't work. Even I tried restarting nginx, still no luck. I have to restart the server to see the changes. Why is it happening? 

I want kestrel to detect changes when I update the files and automatically restart itself (or do something to publish the new site).

**Comment by mikes-gh** [comment]
Could this be done with a drop file like IIS app_offline.htm 
Also I run kerstrel under systemctl as recommened by docs so killing the process should recycle it.

**Comment by davidfowl** [comment]
Kestrel is a web server, it doesn't detect files on disk (it's just s library), doesn't and won't ever handle any deployment of your application itself. 

Unfortunately there's no easy cross platform way to do what you want currently. app_offline only works for IIS scenarios. This should be handled at higher layers with a deployment technology that understands swapping out and restarting the running site.

**Comment by mikes-gh** [comment]
@davidfowl Makes sense.  Is acceptable to run dotnet watch for this senario

**Comment by natemcmaster** [comment]
dotnet-watch is a development tool and relies on having your csproj file available. I would not recommend it for production scenarios.
