### ISSUE TITLE
Make StopAsync multi-thread safe

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1666]
@davidfowl wants any parallel calls to KestrelServer.StopAsync to gate on the first call rather than no-op. IWebHost.StopAsync may need this logic, though putting it in both places seems redundant.

**Comment by davidfowl** [comment]
It's not that I want it, I just want it to be right 👍

**Comment by muratg** [comment]
@cesarbs We need to do the same in HttpSysServer.

**Comment by cesarbs** [comment]
I've opened https://github.com/aspnet/HttpSysServer/issues/377 to track this on HttpSysServer.
