### ISSUE TITLE
Questions on HEAD requests

### ISSUE THREAD

**Issue by jchannon** [aspnet/KestrelHttpServer#1675]
When executing a GET request that returns "Hi", the output from curl looks like so:

```
> GET / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 13 Apr 2017 19:00:05 GMT
< Server: Kestrel
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
HI%
```

When executing with a HEAD request with the same body being set (I know you are not supposed to have a body on a HEAD) we get:
```
> HEAD / HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 13 Apr 2017 19:00:55 GMT
< Server: Kestrel
* no chunk, no close, no size. Assume close to signal end
```

We get no `Transfer-Encoding: chunked` header and we get a `* no chunk, no close, no size. Assume close to signal end` message with the curl command left in a limbo state and hung.

Why is this? I partly understand the `Transfer-Encoding: chunked` header as HEAD should not be returning data (Does Kestrel automatically check for HEAD requests and not output the body even if one is returned?) but the connection doesn't appear to be left intact.

**Comment by jchannon** [comment]
This answers a couple of questions but the connection should not be left in a limbo state - https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/ResponseTests.cs#L437-L498

**Comment by Tratcher** [comment]
curl shouldn't be expecting a body from a HEAD request, even if we did specify transfer-encoding or content-length. Note HEAD responses should include transfer-encoding or content-length just like the real response would have.

**Comment by Tratcher** [comment]
Hmm, technically those headers are optional: https://tools.ietf.org/html/rfc7231#section-4.3.2

**Comment by jchannon** [comment]
Kestrel looking at the tests won't set TranferEncoding on a head request but I think it should then set a ContentLength header which led me to raise #1680 

However still not sure what the output on CURL really means when it is a HEAD

**Comment by benaadams** [comment]
It shouldn't set a content-length header for chunked as that differs from what the GET would be

**Comment by jchannon** [comment]
But it's not chunked on a HEAD as kestrel doesn't emit that header

**Comment by benaadams** [comment]
> The HEAD method is identical to GET except that the server MUST NOT
   send a message body in the response (i.e., the response terminates at
   the end of the header section).  The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted.  This method can be used for obtaining
   metadata about the selected representation without transferring the
   representation data and is often used for testing hypertext links for
   validity, accessibility, and recent modification.

I assume it doesn't just need an extra `CRLF` on end?

**Comment by jchannon** [comment]
Maybe ¯\_(ツ)_/¯ 😄

**Comment by muratg** [comment]
@Tratcher why is this a bug?

**Comment by Tratcher** [comment]
Nevermind, the content headers are optional. However, someone should at least repro it to make sure head requests are completing properly.

**Comment by jchannon** [comment]
👀

**Comment by muratg** [comment]
Assigning to @natemcmaster for investigation.

**Comment by muratg** [comment]
Moving out to 2.1.

**Comment by natemcmaster** [comment]
As the HTTP/1.1 spec says, a server may omit payload headers (e.g. Content-Length, Transfer-Encoding, Content-Range, and Trailer) on HEAD requests. 

I also see the "no chunk, no close, no size. Assume close to signal end" message from cURL output when issuing a request like this
```
$ curl -X HEAD http://localhost:5000
```
However, the cURL client also issues this warning: 

```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
```

If you use `curl --head` instead, the client behaves better with HEAD requests and will close without issuing the "no chunk, no close, no size" message.

Closing as this is expected behavior.
