### ISSUE TITLE
Remove optional whitespace in header responses

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#168]
The header value whitespace is optional: https://tools.ietf.org/html/rfc7230#section-3.2.4

> A field value might be preceded and/or followed by optional whitespace (OWS); a single SP preceding the field-value is preferred for consistent readability by humans.

Will shave off 5 bytes per response for plaintext test; which is about 150 bytes? 

So for every 30 responses enough bandwidth is saved to send an extra response; which is an extra 5k responses per 150k responses for same bandwidth.

[At line 480](https://github.com/aspnet/KestrelHttpServer/blob/753d64660d24b2f8a113cac94e030b37bd7d3bb3/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L480)
```writer.Write(' ');``` 
[At line 498](https://github.com/aspnet/KestrelHttpServer/blob/753d64660d24b2f8a113cac94e030b37bd7d3bb3/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L498)
```writer.Write("Transfer-Encoding: chunked\r\n");``` 
[At line 507](https://github.com/aspnet/KestrelHttpServer/blob/753d64660d24b2f8a113cac94e030b37bd7d3bb3/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L507)
```writer.Write("Connection: close\r\n\r\n");``` 
[At line 511](https://github.com/aspnet/KestrelHttpServer/blob/753d64660d24b2f8a113cac94e030b37bd7d3bb3/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L511)
```writer.Write("Connection: keep-alive\r\n\r\n");```

**Comment by shrayasr** [comment]
Is this still open?

**Comment by muratg** [comment]
@cesarbs could you do the investigation?  Especially client support. Older IEs, android, etc.

**Comment by benaadams** [comment]
Last I tried, `ab` gets upset - but not sure that's relevant - also may have been a different problem.

**Comment by muratg** [comment]
Cool.  Cesar can give a shot at `ab` as well.

**Comment by shrayasr** [comment]
Can I be of any help? Would love to learn.

**Comment by muratg** [comment]
@shrayasr Absolutely!  Thank you for your offer with helping.  You could build a custom Kestrel with the changes @benaadams is suggesting (basically removing whitespace from a bunch of places in header responses.)  And trying client compatibility, IE8..10, Edge, Chrome, FireFox, devices etc. And tools like `ab` as well.  The potential issue is that some clients may not abide fully with the RFC in their parsing logic, so we'd like to find that out before making a decision on this one. And if we decide to take this change in, you can send a pull request with the changes.  If you have trouble building Kestrel, @cesarbs can share a private when he has one.

**Comment by Tratcher** [comment]
You want to get rid of the space in `Transfer-Encoding: chunked`? I do not recommend it for interop reasons.

@shrayasr, feel free to verify the behavior of different clients, but you'll have a hard time covering all the possible implementations. E.g. IE8 and later, oldest supported versions of chrome, firefox, and safari.  Language SDKs (.NET, Java, Pearl, etc.).  Smart phone browsers and SDKs. You get the idea.

**Comment by cesarbs** [comment]
I'll close this since it could cause compatibility issues that are not worth the small improvement.
