### ISSUE TITLE
Basic stress tests

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#1685]
There has been a lot of churn in the code base around pipelines, transport abstraction etc. Let's do some basic stress testing before 2.0.0. 

Simple idea to get started: run functional tests on a CI agent in a loop.

cc @davidfowl

**Comment by pakrym** [comment]
@davidfowl do you want this on all OS?

**Comment by pakrym** [comment]
`Win2012-Kestrel` build configuration is up and running.

**Comment by davidfowl** [comment]
We need Linuz

**Comment by pakrym** [comment]
@davidfowl  `Ubuntu-Kestrel` is up and running
