### ISSUE TITLE
Socket Transport 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1686]
- [x] - The functional tests support running both on both transports but tests aren't running for sockets right now. We need to parameterize these. 
- [x] - ~~TimeoutServerTests hard code the libuv transport, this needs to support any transport.~~
- [x] - Get the socket transport on the benchmarks server (https://github.com/aspnet/benchmarks/issues/250)
- [x] - Add logging to the SocketsTransport, today it has nothing
- [x] - Add thread pool dispatching by default. We may not get time to do this properly for 2.0.0 https://github.com/aspnet/KestrelHttpServer/issues/1641, so until then, we should just abuse thread pool dispatch and offer knobs on the transport to turn it off.
- [x] - The systemd activation test assumes we can bind using a unix pipe and an open file descriptor. We need to only run that test when using the libuv transport as sockets only supports binding via and IPEndPoint.
- [x] - Implement graceful server shutdown
- [x] - Throw reasonable exceptions for unsupported ListenOptions
- [ ] - Add SocketTransportOptions
- [ ] - Smarter Output Buffering 
- [ ] - 0 byte reads to help the memory issues
- [x] - Use the new Memory<byte> APIs in .NET Core 2.1
- [ ] - Security review

None of the performance work is listed here specifically since that will be on going. We need to experiment with different ways of using `SocketAsyncEventArgs` to see if what we have is the most efficient.

One other note is that we aren't doing 0 byte reads right now (which libuv *does* so), this is usually done to avoid allocating until data is ready but we'll see how it affects both memory and throughput.

/cc @geoffkizer @stephentoub

**Comment by vancem** [comment]
>  Add thread pool dispatching by default. We may not get time to do this properly for 2.0.0 #1641, so until then, we should just abuse thread pool dispatch and offer knobs on the transport to turn it off.

Why do we want thread pool dispatching by default?    For Sockets there is no need to hop threads, so we should not.   There is this issue that we would like some batching of outgoing writes, but that seems like a separate issue which we would solve differently (so that the fast path does NOT involve queuing threadpool work items).

**Comment by benaadams** [comment]
libuv needs dispatching (otherwise application code will block the I/O) and that is currently the default transport

**Comment by davidfowl** [comment]
@vancem It's a stop gap until we decide which layers do how much buffering.

**Comment by davidfowl** [comment]
Some notes:
This test is libuv specific right now - ConnectionResetBetweenRequestsIsLoggedAsDebug
This test fails because the exception is incorrect - EmptyRequestLoggedAsInformation

**Comment by halter73** [comment]
@muratg I updated this check list with new Socket-related work items.

**Comment by muratg** [comment]
@halter73 Thanks, looks good. Though let's make sure we start with the test run changes that we talked about too. :)

**Comment by davidfowl** [comment]
Ok I'm closing this issue out, I've filed other issues for the remaining work items.
