### ISSUE TITLE
Validation and matching of host header

### ISSUE THREAD

**Issue by Drawaes** [aspnet/KestrelHttpServer#1688]
This came up during a discussion about host headers. It was not appropriate there as it was just code to make sure there was/wasn't one. 

After 2.0 is out, and once SNI is available, I would question if there should be by default some mechanism to make sure that a request has the same host as in the SNI request? If not it could lead to a potential issue where someone could authenticate (say with a client cert) for one "application or tenant" on an instance of kestrel but actually request information from another "Host"

Think of it as a protocol level cross site scripting ;)

As said this isn't a problem now but is something that might need to be thought about down the line.

**Comment by davidfowl** [comment]
/cc @Tratcher 

I'm pretty sure we decided we're not doing this because kestrel won't ever support port sharing

**Comment by Drawaes** [comment]
Doesn't have to. With SNI you can have multi sites or "hosts" running off a single port/process such as a multitenant api or website. Different certificates the works.

**Comment by natemcmaster** [comment]
Validation and matching of host headers applies to plain-old encrypted HTTP too.

Today, if Kestrel receives `Host: site.com`, it doesn't actually verify `site.com` is an acceptable hostname. Kestrel doesn't check against IServerAddressesFeatures or ListenOptions.

**Comment by davidfowl** [comment]
I'm not sure, I think we might want to do this in middleware.

**Comment by Drawaes** [comment]
Very possibly. It raises the question of how the TLS surfaces information like this to middleware. Also I think it's too hard to get right not to have it in the core product (middleware or not). It's hard to make a secure and correct host comparison. There is a whole IETF RFC on the topic.

If it was going to be middleware should the issue be moved somewhere ?

**Comment by natemcmaster** [comment]
@Tratcher HttpSysServer handles hostname validation before the request gets to the application, right?

**Comment by Tratcher** [comment]
Yes, all the way down in http.sys. Kestrel is the odd one out.

Note http.sys must check the host header because it can share a port across different apps. Kestrel can't share so the host validation is more about correctness.

**Comment by muratg** [comment]
Closing this based on the discussion..

This can be achieved with a middleware.

**Comment by blowdart** [comment]
And such a middleware is now available - https://github.com/aspnet/BasicMiddleware/tree/release/2.0/samples/HostFilteringSample
