### ISSUE TITLE
Store header values as byte[]

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#169]
Encode and store the header values as byte[] at the point they are added to the header dictionary { set }; encoding back to string if read by user code { get }; and using the byte[] when output to the socket (alternate IEnumerable interface?). 

As strings are immutable this wouldn't break user code; to change the header the value would need to be set again. Response headers aren't read back that much by user code; oauth does it; but oauth is generally slow anyway.

This would mean the server header would only need to be encoded once for the lifetime and date only encoded once per second, rather than both on every response.

Additionally it would move the encoding time out of the socket write path which *may* improve throughput?

More of a suggestion than something backed up by hard metrics.

**Comment by Tratcher** [comment]
FYI: This probably conflicts with the coming change from string[] to StringValues :https://github.com/aspnet/HttpAbstractions/issues/361

**Comment by benaadams** [comment]
Might make it easier as that puts the indirection in place?

**Comment by DamianEdwards** [comment]
Yep this is something that could be supported by StringValues.

**Comment by benaadams** [comment]
This has been more or less addressed

**Comment by benaadams** [comment]
Reopening this in light of https://github.com/aspnet/KestrelHttpServer/pull/367 though would probably want some kind of `hasBytes` type of flag; then switch between using  that or converting the string; e.g. keep it in the version it was set as.

Would likely want the `byte[]` version to be automatically converted and cached as `string` or `string[]` when used as such, but not auto conversion to `byte[]` as that would likely be memory inefficient.

For an example use, in [benchmarks](https://github.com/aspnet/benchmarks/blob/master/src/Benchmarks/PlaintextMiddleware.cs#L31) `ContentType` and `Content-Length` could be set to a static `byte[]`

**Comment by muratg** [comment]
@cesarbs could you check if this is done already?  Feel free to ping @JunTaoLuo and @Tratcher

**Comment by Tratcher** [comment]
https://github.com/aspnet/Common/pull/68

**Comment by JunTaoLuo** [comment]
Will be addressed in the PR mentioned above.
