### ISSUE TITLE
Flaky: Port in use for DirectConfiguration tests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#1701]
http://aspnetci/viewLog.html?buildId=202214&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe
DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfAddressesEmpty
DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse
DoesNotOverrideDirectConfigurationWithIServerAddressesFeature_IfPreferHostingUrlsFalse

**Comment by JunTaoLuo** [comment]
These are EADDERINUSE errors;

```
System.IO.IOException : Failed to bind to address http://127.0.0.1:5001: address already in use.
---- Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.AddressInUseException : Error -4091 EADDRINUSE address already in use
-------- Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException : Error -4091 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<BindToEndpoints>d__19`1.MoveNext()
```

@cesarbs is there a chance that another functional test ends up binding to 127.0.0.1:5001 when given the address of `http://127.0.0.1:0`? Maybe it's worth it to convert these tests to call GetNextPort to ensure no port conflicts.

**Comment by halter73** [comment]
@JunTaoLuo GetNextPort() sounds like a good idea.
