### ISSUE TITLE
Bind Kestrel options to config by default

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#1703]
Since config is in DI now by default we should support binding the Kestrel options to config by default (for `UseKestrel()`).

```json
  "Kestrel": {
    "Endpoints": [ // Order matters!
      {
        "Address": "localhost",
        "Port": "44316",
        "Certificate": { // Implies HTTPS
          "Subject": "danroth27.com", // Pick the cert that matches the subject name with the latest expiry
          "StoreName": "My",
          "StoreLocation": "CurrentUser"
        }
      },
      {
        "Address": "localhost",
        "Port": "8080"
      },
      {
        "Address": "localhost",
        "Port": "44317",
        "Certificate": {
          "Path": "./mysslcert.pfx",
          "Password": "abc!123" // In user secrets: Kestrel:Endpoints:2:Certificate:Password
        }
      }
    ]
  }
```

**Comment by danroth27** [comment]
@glennc @Tratcher @DamianEdwards @davidfowl

**Comment by muratg** [comment]
:eyes:

**Comment by danroth27** [comment]
Or you can name your endpoints:

```json
  "Kestrel": {
    "Endpoints": {
      "CertFromStore": {
        "Address": "localhost",
        "Port": "44316",
        "Certificate": { // Implies HTTPS
          "Subject": "danroth27.com", // Pick the cert that matches the subject name with the latest expiry
          "StoreName": "My",
          "StoreLocation": "CurrentUser"
        }
      },
      "LocalhostWithPort": {
        "Address": "localhost",
        "Port": "8080"
      },
      "CertFromFile": {
        "Address": "localhost",
        "Port": "44317",
        "Certificate": {
          "Path": "./mysslcert.pfx",
          "Password": "abc!123" // In user secrets: Kestrel:Endpoints:CertFromFile:Certificate:Password
        }
      }
    }
  }

**Comment by danroth27** [comment]
This issue was moved to aspnet/MetaPackages#30

**Comment by davidcv5** [comment]
@danroth27 Did this change after MSBuild 2017. I've been trying the exact same setup and I can't get it to work. Tried in the following environments:

Mac OS X - dotnet version 2.1.0-preview1-006919
Mac OS X - dotnet version 2.0.0-preview2-006497
Win 10      - dotnet version 2.0.0-preview2-006497

Could you please point us in the right direction on how to use this properly. The docs at https://docs.microsoft.com/en-us/aspnet/core/security/https describe the exact same setup, but that article is from May, the same time as MSBuild2017 when you presented this feature.

Steps to reproduce:
```
mkdir kestrel
cd kestrel
dotnet new web
```
create `appsettings.json`  with content:
```
{
"Kestrel": {
    "Endpoints": {
      "Localhost": {
        "Address": "127.0.0.1",
        "Port": "5001"
      }
    }
  }
}
```

`dotnet run`

**Logs**
Hosting environment: Production
Content root path: /Users/[user]/projects/demo
Now listening on: **http://localhost:5000** **<---- should be 5001**
Application started. Press Ctrl+C to shut down.

**Thank you!**

**Comment by natemcmaster** [comment]
This feature was cut from 2.0.0. https://github.com/aspnet/KestrelHttpServer/pull/1886#issuecomment-306279884

**Comment by davidcv5** [comment]
@natemcmaster thank you!

**Comment by natemcmaster** [comment]
We will :) We're working on getting our docs ready for 2.0 RTM. https://github.com/aspnet/Docs/issues/3815
