### ISSUE TITLE
Consider pooling all UvRequest objects

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#1719]
We should consider pooling all `UvRequest` objects like we do `UvWriteReq`. The other ones don't show up as much in our benchmarks because we don't test things like heavy connection churn. Writes happens more often than connect/shutdown but we should consider unifying how we pool and handle requests. 

As part of this PR (https://github.com/aspnet/KestrelHttpServer/pull/1698) the weak handles are already being removed and could consider making the WriteReq pool more generic and apply it to all `UvRequest` types.

**Comment by muratg** [comment]
Not planning to do this. Closing.
