### ISSUE TITLE
ThreadPool and thread context issue

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/KestrelHttpServer#1720]
Hi gents

Not yet sure, but looks like a bug in between Kestrel server, IIS integration and security concept, so please move this issue to right section if needed (or just give direction, I will do it).
What we have:
IIS with ASP.NET Core site (self-contained), Windows Authentication enabled, AutomaticAuthentication and ForwardWindowsAuthentication set to true in IISOptions. This configuration works for both, NTLM and Kerberos.
But with NTLM, we have options named "Logging as different user". What we do:
1. Check if user logged in.
2. If it logged in then send Unauthorized response
3. the out-of-box login prompt displayed for the user in all major browsers
4. When he send new credentials, clear session, and log him in.

And here we have issue: the Request.HttpContext.User.Identity is correctly set with new user, but threads still working under old context. We set content of current thread (where logging in happens), but all other are still use old context.
This is not really expected behavior.
For instance:
User logged first time, couple requests are completed (using Impersonation) with different threads (from logs):
_Request: Test1
Current WindowsIdentity user: DOMAIN\USER1
ManagedThreadId: 11
Request: Test2
Current WindowsIdentity user: DOMAIN\USER1
ManagedThreadId: 7_
now user logged in with new user ID:
_Request: Test1
Current WindowsIdentity user: DOMAIN\USER2
ManagedThreadId: 16
Request: Test2
**Current WindowsIdentity user: DOMAIN\USER1
ManagedThreadId: 11**_

So one of the thread was re-used but with same (old) content and this is really unexpected. We used same technic for all ASP.NET frameworks before and it works well (even if thread re-used, it re-used with new context). But not with ASP.NET Core.
Bug or just unsupported scenario?

**Comment by Drawaes** [comment]
I think the problem here is (I could be totally wrong but I will give it a shot). That you are impersonating on a threadpool thread and then this returns to the pool without changing back, but worse than that Kestrel is fully async. So 1/2 of your request mìght be on a totally different thread and I am not sure there is a way you can flow that through.

Not sure that impersonation  plays nice with async to be honest (Not per request impersonation).

**Comment by antonGritsenko** [comment]
Impersonation made per request of course. "Current WindowsIdentity user" from above is the HttpContext.User.Identity output.

**Comment by Drawaes** [comment]
I am confused what do you mean asp.net self hosted with iis?

**Comment by antonGritsenko** [comment]
So, to be exact, the problem here that for some re-used threads the HttpContext.User.Identity also re-used.

**Comment by antonGritsenko** [comment]
@Drawaes self-contained, sorry for using wrong term

**Comment by Drawaes** [comment]
Are you disposing the impersonation?

**Comment by antonGritsenko** [comment]
yes, all impersonated calls are done like this:
`wi = (WindowsIdentity)this.httpContextAccessor.HttpContext.User.Identity;
using (var impersonatedUser = wi.Impersonate())
                {
                    action.Invoke();
                }`

**Comment by Drawaes** [comment]
Very odd maybe a small independent repo that shows the issue would be helpful. I can try to have a crack. I am interested because we use NTLM.

**Comment by antonGritsenko** [comment]
Will try to create some sample app, but later. Trying to dig around, maybe will find the solution or workaround at least.

Strange thing that when we are using cookies authentication above the windows authentication (manual logging process using HttpContext.Authentication.SignInAsync and LogonUser from WinAPI) then everything works well.

**Comment by Drawaes** [comment]
WindowsIdentity.RunImpersonated (wi, () => yourstuff);

Try that

**Comment by Drawaes** [comment]
Should be wi.AccessToken

**Comment by antonGritsenko** [comment]
it will be the same, because the wi is already wrong.

**Comment by Drawaes** [comment]
Yes but I am wondering if the impersonate call is leaving something around that is leaking to other threads.

**Comment by Drawaes** [comment]
I mean is staying on the thread and being used in other contexts

**Comment by antonGritsenko** [comment]
From my understanding (and that's how ASP.NET vPrev works) even if thread still exist with some undisposed variables, this thread should not be re-used for other users.

**Comment by Drawaes** [comment]
Is there any async work inside your impersonate though. I know that execution context needs to be captured/reset if that is the case and maybe asp.net core isn't doing that. I am guess at this point. But it's worth trying the above mentioned method. Also your action.invoke doesn't return a task does it?

**Comment by benaadams** [comment]
ASP.NET Core on full framework (which flows SecurityContext as part of ExecutionContext) or on .NET Core which doesn't flow impersonation?

**Comment by benaadams** [comment]
https://github.com/dotnet/corefx/pull/18510#issuecomment-294953621

**Comment by Drawaes** [comment]
That's kinda my point... I suspect it's an async issue ... there is a context swap inside the impersonate call and you are not "flowing" the response as ben says.

**Comment by benaadams** [comment]
`HttpContextAccessor.HttpContext.User.Identity` will flow across awaits in .NET Core. 

If you want to use `Thread.CurrentPrincipal` then you have to use full framework.

ASP.NET Core will run on both

**Comment by antonGritsenko** [comment]
@benaadams on full framework, 4.6.1, ASP.NET Core 1.0

**Comment by muratg** [comment]
@Tratcher Any thoughts on this one?

**Comment by Tratcher** [comment]
I agree, it's likely calling a into async code under the impersonation. Is it writing to the response body at any point?

**Comment by antonGritsenko** [comment]
@Tratcher no, it's a WebAPI calls, return pure JSON. Same code and same approach works well in ASP.NET (not a Core). 
I still trying to find time to write generic sample. But it looks like this:
1. Main page display current context user (with impersonation for sure), current thread user and current thread id
2. Several AJAX JS calls that get same info as JSON object and then show of the page using JS
3. Button "Sign out with different credentials"

When you are log in first time (SSP or enter Windows Credentials directly) 1) and 2) shows same correct info. 
When you used "Sign out with different credentials" and use different login then 1) will show new correct info, but 2) will be inconsistence: some calls with return new user info, but some of them an old one (with **old thread id**).

**Comment by antonGritsenko** [comment]
OK, gents, here is it:
https://github.com/antonGritsenko/aspnetcoreLogout

Just run the project and try to logout then log in with different user. The output of "container" will contains some unpredicted info.
Sample output for me:
First attempt (current user)

> User from context:**DOMAIN\gritsenko** 
> User from WindowsIdentity:DOMAIN\gritsenko 
> 
> Thread ID:4 
> 
> User from thread: 
> 
> {"Context":"DOMAIN\\gritsenko","WindowsIdentity":"DOMAIN\\gritsenko","ThreadId":15,"ThreadUser":""}
> {"Context":"DOMAIN\\gritsenko","WindowsIdentity":"DOMAIN\\gritsenko","ThreadId":4,"ThreadUser":""}
> {"Context":"DOMAIN\\gritsenko","WindowsIdentity":"DOMAIN\\gritsenko","ThreadId":3,"ThreadUser":""}
> {"Context":"DOMAIN\\gritsenko","WindowsIdentity":"DOMAIN\\gritsenko","ThreadId":16,"ThreadUser":""}



Logged out and logging in with testuser:

> User from context:**SCSMSOL\testuser** 
> User from WindowsIdentity:SCSMSOL\gritsenko 
> 
> Thread ID:4 
> 
> User from thread: 
> 
> {"Context":"SCSMSOL\\gritsenko","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":17,"ThreadUser":""}
> {"Context":"SCSMSOL\\gritsenko","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":4,"ThreadUser":""}
> {"Context":"**SCSMSOL\\testuser**","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":11,"ThreadUser":""}
> {"Context":"SCSMSOL\\gritsenko","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":16,"ThreadUser":""}

So only one of three is correct. If you will continue to pressing refresh you will get same behavior.

Refresh the page in couple minutes later (it tricky, I don't know exact time that needs to be waited):

> User from context:SCSMSOL\testuser 
> User from WindowsIdentity:SCSMSOL\gritsenko 
> 
> Thread ID:3 
> 
> User from thread: 
> 
> {"Context":"SCSMSOL\\testuser","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":18,"ThreadUser":""}
> {"Context":"SCSMSOL\\testuser","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":16,"ThreadUser":""}
> {"Context":"SCSMSOL\\testuser","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":21,"ThreadUser":""}
> {"Context":"SCSMSOL\\testuser","WindowsIdentity":"SCSMSOL\\gritsenko","ThreadId":3,"ThreadUser":""}

So now everything looks good.

**Comment by antonGritsenko** [comment]
BTW, I have big different with my real project: in this test app the ThreadUser is always GenericClaim. And I don't understand why.

**Comment by muratg** [comment]
@cesarbs assigning to you for investigation. Please see the repro app above.

**Comment by muratg** [comment]
@cesarbs Did you get a chance to investigate this one?

**Comment by guylando** [comment]
@antonGritsenko can you try this workaround and say if it solved the problem or not (adding the specified middleware before UseAuthentication): https://github.com/aspnet/Security/issues/1602#issuecomment-356900756

**Comment by Tratcher** [comment]
@antonGritsenko I have debugged your repro app and found that the identity is being cached, but it's happening at the IIS connection layer.  NTLM does this strange thing where it only performs authentication on the first request for a new connection. After that the server re-uses those credentials for all subsequent requests.  Browsers keep multiple connections open at a time so when you force a logout it's only happening for one of the connection, the other connections still have the old credentials. Adding `ret.Add("RemotePort", HttpContext.Connection.RemotePort);` to SampleController.GetUserData helps show that the identities are coming from different ports/connections.

Here's how you can work around this in IIS Express:
In the soultion directory open `.vs\config\applicationhost.config`. This is a VS generated file that's created the first time you run your project.
Change
```
        <windowsAuthentication enabled="false" >
```
To
```
        <windowsAuthentication enabled="false" authPersistSingleRequest ="true" >
```

This disables NTLM connection level identity caching. If you re-run your sample then all outputs immediately switch to to the new identity after logout.

For reference the repro application contains no impersonation. All references to `WindowsIdentity.GetCurrent()` and `Thread.CurrentPrincipal` return the application pool identity. In IIS Express this can be confusing as the same identity is used to both launch IIS Express and log into the page.

Everything here is working as expected.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
