### ISSUE TITLE
Auto-chunk if Transfer-Encoding is manually set to something other than "chunked"

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#176]
Right now, if the user manually sets the Transfer-Encoding header is set to something other than "chunked" (such as "gzip"), Kestrel will not try to automatically chunk the response. It will also not try to set "Content-Lenght: 0" for empty response bodies.

This should be changed so Kestrel specifically checks if the Transfer-Encoding header is manually set to "chunked" before deciding not to auto-chunk.

**Comment by muratg** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/1016
