### ISSUE TITLE
Beta7 - Kestrel does not work on Windows Server 2008 R2 and Windows Server 2012 R2

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/KestrelHttpServer#177]
You end up getting the following error:
![image](https://cloud.githubusercontent.com/assets/2008729/9509396/f54700ae-4c13-11e5-837c-46ff61d14091.png)

This could also happen in other variations of Windows, these are just two that I noticed the issue in.

**Comment by crozone** [comment]
I believe you need the Visual C++ 2015 redistributable installed for DNX:

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by halter73** [comment]
@crozone I think you're right, but shouldn't required. These are redistributable after all.

**Comment by akoeplinger** [comment]
Looks like libuv.dll references it:

![image](https://cloud.githubusercontent.com/assets/1376924/9586643/4294feb6-501e-11e5-925e-3627b8425003.png)

**Comment by halter73** [comment]
@akoeplinger That's correct. AFAIK it shouldn't be necessary to reference both kernel32.dll and vcruntime140.dll.

**Comment by akoeplinger** [comment]
@halter73 I thought that unless you statically link the VC++ runtime you need to install the redistributable package?

**Comment by halter73** [comment]
@akoeplinger Right. We shouldn't need to dynamically link the runtime. I think the same goes for the other redistributables like "api-ms-win-*".

**Comment by michalstepien** [comment]
I have installed Visual C++ 2015 redistributable, now I have error: api-ms-win-core-rtlsupport-l1-2-0.dll
System: Windows 7

**Comment by muratg** [comment]
cc @moozzyk in case he has thoughts on this

**Comment by muratg** [comment]
Also, @victorhurdugaci does this work with the current bits?

**Comment by moozzyk** [comment]
This was fixed in beta-8 I believe. The issue was that the libuv.dll we distributed in dll package was built incorrectly. We now build libuv differently.

**Comment by muratg** [comment]
Closing. If this still repro's in RC1 or RC2 bits, please reopen.
