### ISSUE TITLE
KestrelServerOptions.ApplicationServices is null when using a custom DI container

### ISSUE THREAD

**Issue by feO2x** [aspnet/KestrelHttpServer#1783]
Dear ASP.NET Core team,

today I discovered a bug while trying to enable HTTPS for Kestrel: `KestrelServerOptions.ApplicationServices` is null when the ASP.NET Core app uses a custom DI container.

An MCVE can be found in [this repo](https://github.com/feO2x/KestrelHttpsConfiguration).

However, here is a short description of the error:

### Minimal repro steps

1) Create an empty ASP.NET Core web app
2) Add a custom DI container, which implies to use the variant of `ConfigureServices` that returns an `IServiceProvider` instance:<br />`public IServiceProvider ConfigureServices(IServiceCollection services);`
3) Configure Kestrel options (e.g. `UseHttps`) that use `KestrelServerOptions.ApplicationServices` internally. 

### Expected Result:

The application should startup fine with HTTPS enabled.

### Actual Result

The application crashes during startup because of an `ArgumentNullException`.

### Workaround

This behavior can be avoided by creating a (temporary) DI container and injecting it manually into the `KestrelServerOptions`. However, this might lead to subtle bugs when object graphs are composed of the wrong objects, especially when the application becomes large.

```csharp
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    // The following line would throw the exception
    //services.Configure<KestrelServerOptions>(options => options.UseHttps("customcontainer.net.pfx"));

    // The above ArgumentNullException can be avoided by using the code below,
    // but IMO, it is pretty dirty to instantiate another IServiceProvider instance
    services.Configure<KestrelServerOptions>(options =>
    {
        options.ApplicationServices = services.BuildServiceProvider();
        options.UseHttps("customcontainer.net.pfx");
    });

    return new ServiceContainer().CreateServiceProvider(services);
}
```

**Comment by Tratcher** [comment]
Known issue. This happens if the DI container does not guarantee order.
https://github.com/aspnet/KestrelHttpServer/issues/923

**Comment by feO2x** [comment]
In my repro, I use LightInject. If I understood https://github.com/autofac/Autofac/issues/755 correctly, then the `IStartupFilter` instances should be returned in the same order as they were registered (which does not happen here). I will investigate this further, but I thought that LightInject does not mix up the order of the returned items.

**Comment by feO2x** [comment]
It seems to be a bug in LightInject, I will close this issue and investigate further.

**Comment by davidfowl** [comment]
ping @seesharper

**Comment by seesharper** [comment]
Just tested this with LightInject.Microsoft.DependencyInjection 2.0.2 and it seems to work just fine
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Server.Kestrel;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using LightInject;
using LightInject.Microsoft.DependencyInjection;

namespace issue1783
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<KestrelServerOptions>(options => {Debug.Assert(options.ApplicationServices != null);});
            var container = new ServiceContainer();
            return container.CreateServiceProvider(services);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            
            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });

        }
    }
}

```

**Comment by feO2x** [comment]
@seesharper Yes, I could also confirm that with v2.0.2, it's working. When I created this example, v2.0.1 was the actual version which did not work correctly.
