### ISSUE TITLE
DNX . kestrel killed unexpectly

### ISSUE THREAD

**Issue by JerryBian** [aspnet/KestrelHttpServer#179]
I ran DNX . Kestrel command under Ubuntu to make site running. After it starts, it would print 'Started'. However several minutes later, the site would turns to shutdown, and Console would print 'Killed'.

It always happened like this. I guess maybe some code in the website caused the DNX down. But any way I can quickly find out the root cause, any logging or something?

BTW, the version is beta6, and I run the command in separate Screen host, which would keep running after SSH session disconnected.

**Comment by muratg** [comment]
@JerryBian Are you still hitting this with Beta7 or Beta8 bits?

**Comment by ScottKaye** [comment]
The same thing is happening to me - running beta7 with `nohup dnx kestrel &` launches the server just fine, but it seems to randomly crash overnight.  Sometimes it lasts a few days, sometimes a few hours.  Nginx proxy access logs don't seem to contain anything useful, and the error log is empty.  Are there any logs from Kestrel or ASP.NET that might help track down what's causing the crash?

I'm using entirely beta7 packages in my project (which builds and runs fine), DNVM version 1.0.0-beta8-15506, and DNX 1.0.0-beta7-15532.

**Comment by davidfowl** [comment]
Mono or core clr

**Comment by ScottKaye** [comment]
Sorry!  I can't believe I forgot that info.  I'm running on Mono 4.0.4 off an Ubuntu 14.04.3 digitalocean droplet.  No problems when running it on windows, though.

**Comment by muratg** [comment]
Does this still repro with RC1 or RC2 bits?  Also, did you ever try with CoreCLR?

**Comment by muratg** [comment]
No repro/response. Closing. If you're still hitting this with the latest bits, please feel free to open a new issue.
