### ISSUE TITLE
Question on getting Original Request

### ISSUE THREAD

**Issue by adminnz** [aspnet/KestrelHttpServer#1800]
I'm looking at KestrelHttpServer and wondering if it is possible to get the original request stream (headers + body)
I know I could "rebuild" a _similar_ stream by enumerating context.Request.Headers and writing them (+ CRLF) to a MemoryStream, and then writing CRLF and then the context.Request.Body.
But the headers may be in a different order than what they arrived in and the HttpParser appears to trim whitespace from start/end.

Is it possible to inject/intercept before the HttpParser gets its hands on the stream ?

**Comment by davidfowl** [comment]
What are you trying to do?

The most you can do is write a connection filter, but that's pretty low level, there's no concept of a request, you get the raw bytes. Here's an example of a logging filter https://github.com/aspnet/KestrelHttpServer/blob/rel/1.1.2/src/Microsoft.AspNetCore.Server.Kestrel/Filter/LoggingConnectionFilter.cs.

**Comment by adminnz** [comment]
Ultimately I'm building a AS2 server ([RFC](http://www.ietf.org/rfc/rfc4130.txt)) and while the message parsing is nicely handled by Jeffrey Stedfast's [MimeKit](https://github.com/jstedfast/MimeKit), I'm looking at different options for providing the HTTP server. 

Kestrel looks like a possible solution (as I really would like to avoid all the async IO work you guys have already done). I know the specification for AS2 and virtually every newer commercial implementation I have seen doesn't care about the original order of the headers. But I deal with some old companies  who incorrectly assume that headers will be in the same order as sent. (hence the reason for building an AS2 server).
