### ISSUE TITLE
Investigate removing uv_shutdown call before closing a conneciton

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1808]
It appears that if a FIN might be sent with just a uv_close. At least on Windows this [seems to be the case](https://github.com/libuv/libuv/blob/cb0cc7346d1c2b5bdf2bd89e4006a50fb6f9c3dd/src/win/tcp.c#L1380).

**Comment by davidfowl** [comment]
Fixed in https://github.com/aspnet/KestrelHttpServer/commit/cd1568d7f4c90a1079b8412a7db6cbbf2bc59de4
