### ISSUE TITLE
Connection not terminated for invalid/ill-formed requests

### ISSUE THREAD

**Issue by moozzyk** [aspnet/KestrelHttpServer#181]
If a client sends an incorrect request the connection should be terminated. What happens now is that the connection is not terminated and new data are appended to the buffer but the data from the buffer are never removed so the buffer grows. Kestrel does throw if the data is incorrect (https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L560)  but the exception is then caught logged and swallowed (https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Connection.cs#L87)

Repro steps:
- With telnet send \r\n to the server

Expected behavior:
- the connection is closed

Actual behavior:
- you can continue typing. with each new character an exception will be thrown on the server side. buffer grows. the connection is never closed

Should we do some fuzzing tests in general?

**Comment by Tragetaschen** [comment]
Generally, any malformed request currently throws off Kestrel in various ways. I had created a [couple of failing tests](https://github.com/Tragetaschen/KestrelHttpServer/blob/pinvoke-cleanup-beta6/test/Microsoft.AspNet.Server.KestrelTests/Issues.cs) where generally a connection would leak, but I guess no one looked at it.

BTW, is there any way to test for leaking connections? @DamianEdwards mentioned these in various community standups and I guess they have been fixed, but there doesn't seem to be infrastructure to actually verify it.

**Comment by halter73** [comment]
[This commit](https://github.com/aspnet/KestrelHttpServer/commit/094b8efbf8b760fb3929e821e8eadc5f28d06727) which just made it into RC1 allows Kestrel to handle requests with empty headers.

We still should add fuzz testing and limit start line length, header length, etc...

**Comment by DamianEdwards** [comment]
This is a potential stress issue so I'd like us to take a look at this for RC2.

**Comment by benaadams** [comment]
The last commit of https://github.com/aspnet/KestrelHttpServer/pull/619 should resolve this

**Comment by benaadams** [comment]
Though not all @Tragetaschen's scenarios

**Comment by cesarbs** [comment]
Fixed in https://github.com/aspnet/KestrelHttpServer/issues/683.

**Comment by cesarbs** [comment]
Actually this is a dup of https://github.com/aspnet/KestrelHttpServer/issues/683.
