### ISSUE TITLE
Don't call ConnectionAdapter.OnConnectionAsync on the transport thread

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1813]
#1776 changed the behavior of FrameConnection to no longer call `ThreadPool.UnsafeRun` before invoking any ConnectionAdapter code.

Now if a ConnectionAdapter calls ConnectionStream.Read() instead of ReadAsync(), the LibuvThread would become deadlocked.

**Comment by muratg** [comment]
Not needed anymore.

cc @davidfowl may need to be careful with the bedrock work
