### ISSUE TITLE
Style: ServicesContext

### ISSUE THREAD

**Issue by glennc** [aspnet/KestrelHttpServer#182]
Single base object to pass services through components.

**Comment by DamianEdwards** [comment]
@lodejard isn't this done already?

**Comment by halter73** [comment]
This was finished up as part of this change: https://github.com/aspnet/KestrelHttpServer/commit/52dc37eae740192ef19fbbefc7a2c1375e16bed8

@lodejard Reopen this if you think there is more to do.
