### ISSUE TITLE
IISHosting changes headers for Partial Content

### ISSUE THREAD

**Issue by elangelo** [aspnet/KestrelHttpServer#1823]
I have a service that streams video for which i made an IActionResult. The headers it returns are as followed:
```
HTTP/1.1 206 Partial Content
Date: Wed, 10 May 2017 08:40:28 GMT
Content-Length: 6315677
Content-Type: video/mp4
Accept-Ranges: bytes
Server: Kestrel
Cache-Control: private,max-age=2592000
Content-Range: bytes 0-6315676/6315677
```

This seems to work fine for all tested browsers (Chrome, Edge, Safari and Firefox)

If I host the same service with CGI in IIS the headers are rewritten to:
```
HTTP/1.1 200 OK
Date: Wed, 10 May 2017 08:40:28 GMT
Transfer-Encoding: chunked
Content-Type: video/mp4
Accept-Ranges: bytes
Server: Kestrel
Cache-Control: private,max-age=2592000
X-Powered-By: ASP.NET
Connection: close
```

Unfortunately none of the browsers seem to be able to handle this reliably. Sometimes it just works, sometimes we only get audio, sometimes we get a simple 'this video can not be played'

I also see the folloing message popping up in the log:
```
Microsoft.AspNetCore.Server.Kestrel[]
Connection id "" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
```

**Comment by Tratcher** [comment]
I assume the client requested that range? Or are you sending it even when they did not request it?

Does it behave any differently if you give it real partial content, e.g. only half of the data? It looks like right now you provide the entire content but call it partial content.

**Comment by elangelo** [comment]
ok, you can close this. i fixed this a completely different way and the bug (if it even was a bug) is no longer relevant
