### ISSUE TITLE
Style: Kestrel cleanup

### ISSUE THREAD

**Issue by glennc** [aspnet/KestrelHttpServer#184]
- [x] Members should have appropriate visibility
- [x] One class per file
- [x] Nested classes or enums at bottom of file
- [x] Constructors come before properties
- [x] Remove all commented code
- [x] Sort namespace
- [x] move declarations to the top of the file
- [x] x is a bad variable name

**Comment by glennc** [comment]
@lodejard Given that all these are ticked does that mean you are done?

**Comment by DamianEdwards** [comment]
@lodejard ping
