### ISSUE TITLE
Kestrel run in Kubernetes always got the -104 ECONNRESET error

### ISSUE THREAD

**Issue by TuoNiao** [aspnet/KestrelHttpServer#1841]
I have write two back-end services:
Service 1: a windows service which is run on windows server 2008 use the HttpWebRequest class (.Net framework 4.5) to send POST request in multi-threads
Service 2: a SCD asp.net core service which is run in Kubernetes use asp.net core 1.1, I had removed all MVC references, and write a new middleware to handle all the request. 

On Service 1  I set the KeepAlive option to true and want it can keep the connection always open. But in the  log of Service1, not all request, I found the Operation Timeout Exceptions.  And at the same time Service2 got -104 ECONNRESET error from the Kestrel.

Docker version : 1.12
Kubernetes Version: 1.5

Please help to solve this problem.

**Comment by halter73** [comment]
I'm not sure I completely understand the issue. Some logs might be helpful.

Given that you're trying to keep a connection always open though, you may be hitting Kestrel's [keep-alive timeout](https://github.com/aspnet/KestrelHttpServer/blob/rel/1.1.1/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServerLimits.cs#L153) if said connection is idle for 2 minutes or more at a time.

**Comment by TuoNiao** [comment]
Hi halter73,

Thanks for your help. And I had found the issue. The service1 on windows use Nagle and Delayed_ACK algorithm. These two algorithm use at the same time may cause some transfer problems. So I added below codes one the service1 and the error disappeared.

ServicePointManager.UseNagleAlgorithm = false;
ServicePointManager.Expect100Continue = false;
