### ISSUE TITLE
Account Confirmation error on ASP.NET Core web app running on Apache via reverse proxy

### ISSUE THREAD

**Issue by kimbaudi** [aspnet/KestrelHttpServer#1848]
I have a sample ASP.NET web application built using ASP.NET Core MVC with Account Confirmation enabled using Identity. The web app runs fine and account confirmation works without issue on my local machine (http://localhost:5051).

I have now published my web app to my Ubuntu server running Apache via reverse proxy so that all requests to http://localhost:5051 is forwarded to https://musicstore.paul.kim. I should mention that I have obtained a free SSL certificate from Let's Encrypt. Now when I try to register a new user, I receive a confirmation email with a link to confirm the new user. When I click that link, I am redirected back to the web app with an error. Looking at the log indicates the error as: "warn: Microsoft.AspNetCore.Identity.UserManager[9] VerifyUserTokenAsync() failed with purpose: EmailConfirmation for user cac5f855-cd41-4045-b6ff-2eae40e69087."

Account Confirmation does not seem to work when I use Apache as a reverse proxy for ASP.NET Core web applications running on Kestrel.

I'm not sure at this point whether there is an issue with Kestrel handling forwarding requests from http://localhost:5051 to https://musicstore.paul.kim. 

Is reverse proxy requests from http to https in Kestrel causing issues with account confirmation?

Do I need to enable SSL on my web app so that it runs on https://localhost:5051 instead of http?

Looking for some explanation and possibly a solution.

**Comment by Tratcher** [comment]
@HaoK can you clarify that error message?

**Comment by kimbaudi** [comment]
I was able to get account confirmation to work on ASP.NET Core web app running on Apache via reverse proxy. I was getting the error because I didn't add `RequestHeader set X-Forwarded-Proto "https"` to my apache vhost file.

Basically, you need to add the following lines to `Configure` in `Startup.cs`, which I already did. Note: According to the docs (https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction), this needs to be added before `app.UseFacebookAuthentication` (or any other 3rd party authentication).

	app.UseForwardedHeaders(new ForwardedHeadersOptions
	{
		ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
	});

And don't forget to add the following line to your Apache (or Nginx) vhost .conf file, which I needed to do.

	RequestHeader set X-Forwarded-Proto "https"
