### ISSUE TITLE
Throwing an exception after a successful response in a middleware causes an UnobservedTaskException with "TaskCanceledException: The request was aborted"

### ISSUE THREAD

**Issue by zeroskyx** [aspnet/KestrelHttpServer#1866]
The following code causes Kestrel to properly execute the first middleware and return the 200 with content to the user. However, an unobserved task exception is then thrown:

    IWebHostBuilder HostBuilder = new WebHostBuilder().UseKestrel();
    HostBuilder = HostBuilder.UseUrls("http://+:5000");
    
    HostBuilder.Configure(AspNetBuilder =>
    {
    	AspNetBuilder.Run(async (Context) =>
    	{
    		byte[] Content = Encoding.UTF8.GetBytes(DateTimeOffset.Now.ToString("F"));
    		Context.Response.StatusCode = StatusCodes.Status200OK;
    		await Context.Response.Body.WriteAsync(Content, 0, Content.Length);
    
    		throw new NotImplementedException();
    	});
    });
    
    IWebHost Host = HostBuilder.Build();
    Host.Run();

Exception (there is no stack trace):

    System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The request was aborted) ---> System.Threading.Tasks.TaskCanceledException: The request was aborted
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: The request was aborted<---

Please note that throwing the exception before

    await Context.Response.Body.WriteAsync(Content, 0, Content.Length);

casues a proper 500.

Since unobserved task exceptions are usually thrown randomly when the GC collects the affected block, you have to create some "noise" to enforce the exception faster.
A minimum vscode solution to reproduce the issue can be found here: 
[KestrelUnobserved.zip](https://github.com/aspnet/KestrelHttpServer/files/1032113/KestrelUnobserved.zip)

Simply run and connect to http://localhost:5000 -- the exception is thrown immediately.

**Comment by natemcmaster** [comment]
The behavior is expected. Before the response body can be sent, an HTTP server must send response headers, which includes the status code. By the time the exception is thrown in your sample app, the headers have been sent (with status code 200 per your code), and some of the response body has been sent too. It is too late to rewind that and change the headers to carry a HTTP 500 status code because the bytes have already been pushed to the network interface.

About the missing stack trace comment: you will see the stack trace in the logging. Try adding the console logger. You'll see this in the output:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL54B7Q0QREM": An unhandled exception was thrown by the application.
System.NotImplementedException: The method or operation is not implemented.
   at KestrelUnobserved.Program.<>c.<<Run>b__2_1>d.MoveNext() in C:\tmp\KestrelUnobserved\Program.cs:line 57
```

**Comment by halter73** [comment]
@zeroskyx If you don't like that a 500 HTTP status doesn't get returned if an exception is thrown after the application has started writing to the response body, you can enable response buffering. I describe how here: https://github.com/aspnet/EntityFramework/issues/6684#issuecomment-253927423.
