### ISSUE TITLE
Kestrel listening port is not working

### ISSUE THREAD

**Issue by nimbusparis** [aspnet/KestrelHttpServer#1869]
I try to define 22 profile to launch kestrel:
```
    "Dev": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			},
      "applicationUrl": "http://localhost:5000"
    },
	"PreProd": {
		"commandName": "Project",
		"launchBrowser": true,
		"launchUrl": "http://localhost:6000",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "PreProd"
			},
		"applicationUrl": "http://localhost:6000"
	}
```
Under VS2017, the ASPNETCORE_URLS variable should be set to applicationUrl and when running, kestrel claims to listen "http://localhost:6000" but doesn't, browser can't reach the application.
I've tried to browse port 5000 (default port) it fail too.
What's wrong with kestrel?

**Comment by markrendle** [comment]
If you change `launchUrl` to `http://0.0.0.0:6000` (or `http://*:6000`) does it work?

**Comment by nimbusparis** [comment]
No
http://0.0.0.0:6000 same result.
I've tried to change applicationUrl too and it fail too.

**Comment by muratg** [comment]
`launchUrl` is for the browser when you launch it. Should be `http://localhost:6000`. 

Can you try to change `applicationUrl` to `http://*:6000` instead? (Or some other port :D)

**Comment by muratg** [comment]
Also, could you paste the Kestrel log output.

**Comment by nimbusparis** [comment]
Seems SDK version is guilty. My app use 1.0.4 (not work) and a fresh Webapp using 1.1.2 work like a charm. I'm trying to upgrade and keep you posted.

**Comment by nimbusparis** [comment]
> Can you try to change applicationUrl to http://*:6000 instead? (Or some other port :D)

`http://*:6000` raise an error.

**Comment by nimbusparis** [comment]
Ok, after changing SDK version (still fail), I've the idea to change `"applicationUrl": "http://localhost:6000/"` to `"applicationUrl": "http://localhost:6001/"` that's work...
Seems that port 6000 (and 7000 and ... ?) are reserved and the application cannot run on thos port even if kestrel is claiming to listen on it...

**Comment by muratg** [comment]
@nimbusparis is this Linux?  Perhaps there's something else running on port 6000? You can check with `lsof -i :6000 -S`

**Comment by nimbusparis** [comment]
That was under windows 10, `netstat -a | grep 6000` show nothing

**Comment by potocnika** [comment]
FYI: If someone else comes across this issue: seems like ports 6000 and 7000 are reserved for something. After changing "applicationUrl" in launchSettings.json from 6000 to 5000 it worked fine.

Kestrel claims it's listening on ports 6000 and 7000 but it's not really - would be preferable to throw an error during startup is the ports were already occupied.
