### ISSUE TITLE
Improve certificate binding for Kestrel & support for Update-Database.

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#1880]
_From @blowdart on May 15, 2017 19:47_

Right now it gets the certificate by subject name, and chooses the one whose expiry is furthest in the future. However it doesn't check the purposes, or EKU so you could end up with a certificate which, whilst still valid in terms of expiry, is not valid for HTTPS binding.

In addition the setup, with the current Individual Auth templates, breaks Update-Database through the package manager window because this runs in a production environment, and there is not production config. So, when Update-Database attempts to run through whatever initialization it uses it hits the kestrel certificate setup, can't find any configuration and throws

```
System.InvalidOperationException: Unable to configure HTTPS endpoint. For information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054. ---> 
System.Collections.Generic.KeyNotFoundException: No certificate named 'HTTPS' found in configuration for the current environment (Production).
```

Even when you manually copy the development config to production.config to get your database created you end up with another error from data protection.

```
PM> Update-Database 
rosoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
Update-Database : Exception calling "Substring" with "1" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At line:1 char:1
+ Update-Database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Database], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,Update-Database
```

So right now a new user is going to be blocked when starting a new project.

_Copied from original issue: aspnet/MetaPackages#114_

**Comment by danroth27** [comment]
@bricelam for the Update-Database part of this issue.

**Comment by danroth27** [comment]
_From @blowdart on May 15, 2017 20:5_

On the selection of certs for HTTPS - it's valid to have a cert which no subject, in fact, if a SAN property is there the subject should be ignored. This doesn't matter in the selection for Identity as a Service, because it's not used for HTTPS.

So the selection should be "Give me all certs which I can used for HTTPS, based on their EKU - 

```
Server Authentication (1.3.6.1.5.5.7.3.1)
Client Authentication (1.3.6.1.5.5.7.3.2)
```

and key usuage

```
Digital Signature (80)
```

And then filter based on either the correct DNS name appearing as one entry in the SAN, or, if that doesn't match, a subject name

**Comment by danroth27** [comment]
_From @blowdart on May 15, 2017 21:38_

Or, as an option give either

1. Thumbprint lookup
1. Serial Number lookup

**Comment by bricelam** [comment]
aspnet/EntityFramework#8163 will be fixed in 2.0.0-preview2-final.

**Comment by muratg** [comment]
@javiercn Any chance you can take this one?

cc @Eilon

**Comment by muratg** [comment]
@javiercn Assigning to you for investigation.

**Comment by muratg** [comment]
@javiercn *ping*

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#1263
