### ISSUE TITLE
Add UseKestrel overload that takes a specific config section to bind to

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#1882]
By default kestrel will support a default config schema, but you should be able to bind to a config section of your choice.

**Comment by davidfowl** [comment]
Why?

**Comment by danroth27** [comment]
Correct. We should discuss how important this scenario really is.

**Comment by muratg** [comment]
@danroth27 What was the outcome of the discussion?

**Comment by muratg** [comment]
Putting this in 2.1.0 for now.

**Comment by muratg** [comment]
@danroth27 assigning this to you to make a decision on this one.  If these's an important scenario that requires this, please let me know.  Otherwise please close this  one.

**Comment by halter73** [comment]
We should probably merge this with #1290.

**Comment by danroth27** [comment]
> We should probably merge this with #1290.

Sounds reasonable to me. Closing.
