### ISSUE TITLE
Kestrel raises an exception on disposing 

### ISSUE THREAD

**Issue by strongtigerman** [aspnet/KestrelHttpServer#1883]
Kestrel 1.1.2 running on .net 4.5.1  raises an exception on disposing  when new incoming requests come during disposing process. 
Is there a way to stop Kestrel before disposing or pause incoming requests?

> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4082 EBUSY resource busy or locked
> in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.loop_close(UvLoopHandle handle) in Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.ReleaseHandle() in System.Runtime.InteropServices.SafeHandle.InternalDispose() in System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
> in System.Runtime.InteropServices.SafeHandle.Dispose() in Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)

The question was raised at  [https://stackoverflow.com/questions/44324864/unable-to-stop-asp-net-core-windows-service-when-kestrel-receives-requests](https://stackoverflow.com/questions/44324864/unable-to-stop-asp-net-core-windows-service-when-kestrel-receives-requests)

**Comment by muratg** [comment]
This should be fixed with 2.0.0-preview1+.  

@halter73 will be looking at the stackoverflow question directly.
