### ISSUE TITLE
Running Two Kestrel Processes Through Proxy -- Killed

### ISSUE THREAD

**Issue by sbreed** [aspnet/KestrelHttpServer#1887]
Hello:

I'm running two Kestrel processes on Ubuntu 14.04.  One process is on port 5000 and the other is on 5001.  The processes host the same site; however, one of them is our sandbox.

The proxy is administered by Apache.

The two sites can coexist as long as there is not a web request in one of the controllers.  However, if a method in the controller DOES have a web request, one of the processes is "killed."  There no error or log message; it's just killed.

I've attached a sample project that illustrates this abnormal behavior.  While -- at times -- this sample project will work, our main app is ALWAYS failing.  The sample project is a base project.  I've added one line to the /Home/Index view: a string that indicates the site that your viewing.

The logic for running on port 5000 or 5001 is found in Program.cs.  A quick enum in conjunction with a public const value allows me to change this port.

Finally, the logic for calling a web request is found in the Home controller's Index.  Again, if there's a web call, one of the processes will fail (or be killed).

Thanks for your help.

----- TO REPRODUCE ERROR -----

1.  Compile the program: dotnet publish -c Release -r ubuntu.14.04-x64
2.  Transfer the publish directory to the Linux box
3.  Run command: dotnet KestrelTest.dll (Notice it will be hosted on 5000)
4.  Go back to VS 2017 and change Startup.FORWARD_FACING_SITE to Site2 and compile: dotnet publish -c Release -r ubuntu.14.04-x64
5.  Transfer the publish directory to the Linux box in a new directory
6.  Run the command: dotnet KestrelTest.dll (Notice it will be hosted on 5001)
7.  Load the website.

8.  Now here's the kicker.  Toggle between the two web sites, and reload them from the browser.  Hopefully, they'll work.  Now go back to the command terminal and manually kill one of the Kestrel processes.  Then restart the killed Kestrel process.  Finally, go back to the website and reload it.  If it works again, go to the command terminal and kill a Kestrel process and then respawn it and go to the web browser of the killed process and reload.  *** Eventually one of the Kestrel processes will be killed internally, but I'm not sure what's doing it.  There's no pattern or logic behind the failure that I can see.

If you're still having problems reproducing this error, let me know, and I can get you our production application that is always failing if two or more Kestrel processes are running.

Saul

[KestrelTest.zip](https://github.com/aspnet/KestrelHttpServer/files/1056032/KestrelTest.zip)

**Comment by muratg** [comment]
Hi Saul -- did you figure out what the issue was?

**Comment by sbreed** [comment]
I did not, so I changed the architecture of the website.  Now, I'm checking the URL and adjust it there accordingly.



Saul


________________________________
