### ISSUE TITLE
Determine if Generic Virtual Functions in Kestrel can be avoided.  

### ISSUE THREAD

**Issue by vancem** [aspnet/KestrelHttpServer#1888]
In microsoft.aspnetcore.hosting

Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware 

has an asynchronous method Invoke()

Which is virtual generic method.    This is a hot code path and virtual generic method dispatch is not fast.   Just this one call cost .5% of the Techempower benchmark.

**Comment by davidfowl** [comment]
@vancem Where's the generic?

**Comment by vancem** [comment]
The call that is causing the Virtual
```
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.Microsoft.AspNetCore.Http.Features.IFeatureCollection.Get[[Microsoft.AspNetCore.Http.Features.IHttpRequestFeature, Microsoft.AspNetCore.Http.Features]]()
```

Here is the source code. 
```
    public class RequestServicesContainerMiddleware
    {
       public async Task Invoke(HttpContext httpContext)
        {
            Debug.Assert(httpContext != null);

            // local cache for virtual disptach result
            var features = httpContext.Features;
            var existingFeature = features.Get<IServiceProvidersFeature>();

```

Another reasonably hot use of a virtual function pointer is

```
microsoft.aspnetcore.http!Microsoft.AspNetCore.Http.HttpContextFactory.Create(class Microsoft.AspNetCore.Http.Features.IFeatureCollection)
```

Which calls 
```
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.Microsoft.AspNetCore.Http.Features.IFeatureCollection.Set[[Microsoft.AspNetCore.Http.Features.IFormFeature, Microsoft.AspNetCore.Http.Features]](Microsoft.AspNetCore.Http.Features.IFormFeature):
```

As mentioned, these add up to .5%, not huge, but worth fixing.   If the solution is not obvious, we should discuss it and possible options.

**Comment by davidfowl** [comment]
I figured it was the feature collection. This came up before. I filed a bug for this here https://github.com/aspnet/HttpAbstractions/issues/811. We should move this issue.

**Comment by muratg** [comment]
This is tracked in https://github.com/aspnet/HttpAbstractions/issues/811 now.
