### ISSUE TITLE
Kestrel goes to 100% cpu under high load

### ISSUE THREAD

**Issue by gouffe75** [aspnet/KestrelHttpServer#1895]
Hi,

I am facing a very difficult situation. I migrated a production web site from asp.net 4.5 to asp.net core 1.1. The site in asp.net 4.5 was hosted on IIS 8.5, 3 servers 4 cores / 7Gb RAM, and a traffic of 2 millions users a day. Everything was working fine.

Now, when I run the web site with core, hosted with Debian 8, nginx as a reverse proxy and Kestrel, I often see that the service goes to 100% in many situations.
As there are many controllers on the site, it is difficult to narrow down to one issue. But I think I've managed to reproduce one situation in particular.

The scenario is a generation of multiple images based on parameters sent to an async controller of the site. These parameters let me generate a html, this html is sent to another external service, and this service generates the image with phantomjs.
Most of the time, the image generated has to be split in multiple parts, so that they can be integrated in an html page to be clickable.

So for example, we have a web page having this kind of html:
```
<table>
<tr><td><img src="http://www.my-web-site.com/images/GetImages?index=0&...."></td>
<td><img src="http://www.my-web-site.com/images/GetImages?index=1&...."></td></tr></table>
```

Here are the steps:
- Call to async GetImage

If index = 0
- Html is generated
- Send HTML to HtmlToImageServer with async HttpClient (only one static instance)
- Wait for the image index 0 to be ready by checking a database every 500 ms with `await Task.Delay(500)` (can take up to 2 or 3 seconds)
- Redirects to image url when ready

If index > 0
- Wait for the image index n to be ready with `await Task.Delay(500)`
- Redirects to image url when ready

The scenario works, that's for sure. But as I was saying, from time to time, the cpu goes to 100% and no request is served anymore. The server become unresponsive, and all I can do is kill the process.
The exact same scenario works with asp.net 4.5 with IIS. 

I think my servers are tuned properly, nginx is configured properly (I tried with nginx on a separate server). I also tried with more powerful servers -> 8 core / 14Gb ram, the exact same happens.

I hope my scenario is clear. I don't know if this is a bug from Kestrel. The only thing I can think of is that there is an issue with my use of async / await, and there would be a deadlock somewhere, but to my mind, this wouldn't work at all if this was the case ?
I tried to run the service under Windows to be able to profile it. I solved a lot of issues with that I think. But it's still not working.
What should I be looking for ?

Let me know if I can clarify any point, and many many thanks for your help. I have been working on this issue for a month now, and I am out of ideas.

**Comment by cesarbs** [comment]
Could you capture a core dump of the ASP.NET process when it's spinning at 100%? That would be very helpful to diagnose this issue.

When you run your services on Windows, do you see the same issue?

**Comment by gouffe75** [comment]
I finally found some solution / workaround.

First, I made a mistake by setting the minimum threads of the ThreadPool with a value that is too high (32675). This value was found by getting it from the Windows .net 4.5 site.
When I set this value to min 200 / max 200 / completion 200, it seems that the site handles requests in a better way.

But the other thing is that I configured Nginx to handle 80000 requests per core. The problem here seems to be that if nginx sends too many requests, kestrel keeps accepting new requests and it is overwhelmed because it is waiting for http clients requests to answer,

The strange thing is that it didn't happen with iis + asp.net 4.5. Is there anything I'm missing here ?

Thank you !

**Comment by halter73** [comment]
As @cesarbs suggests, a core dump of the dotnet process taken while the cpu is at 100% (meaning you'll probably have to set nginx to handle 1024 requests per core again) could help us see what the threads are busy doing. Using [the perfcollect script](https://github.com/dotnet/corefx-tools/blob/master/src/performance/perfcollect/perfcollect) and providing the trace.zip output could also help. Just read the comment at the top to see how to use it.

**Comment by gouffe75** [comment]
Will do ASAP ! Thanks

**Comment by gouffe75** [comment]
Hi,

with a long delay, I managed to get a dump when my application goes down in production. This happened with a relative high load, during a peak hour.

If I can get you any other information, please let me know.

Thanks
[sample-down.zip](https://github.com/aspnet/KestrelHttpServer/files/1121475/sample-down.zip)

**Comment by gouffe75** [comment]
Hi,

I have another dump which I think is better and show better details

Thank you !
[samplePerfTrace.trace.zip](https://github.com/aspnet/KestrelHttpServer/files/1123990/samplePerfTrace.trace.zip)

**Comment by halter73** [comment]
@gouffe75 the perf trace shows a ton of samples in SVR::gc_heap::try_allocate_more_space. A core dump would help us identify what's allocating so much.

**Comment by gouffe75** [comment]
Hi,

thanks for your answer. How would I get a core dump of the process ?

Could it be related to the creation of connections (Mongodb, rabbitmq, redis, elasticsearch) ? I can't think that would be the case but maybe I'm wrong here.

Thank you

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
