### ISSUE TITLE
Update Kestrel 1.1.x to use latest Libuv 1.9.x

### ISSUE THREAD

**Issue by Eilon** [aspnet/KestrelHttpServer#1897]
The current public Kestrel 1.1.x is referencing Libuv 1.9.1, but we have a better 1.9.2 build that's public.

https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel/1.1.2

**Comment by Eilon** [comment]
See related bug for 1.0.x: https://github.com/aspnet/KestrelHttpServer/issues/1898

**Comment by Eilon** [comment]
@moozzyk / @muratg - I'm looking at patch candidates but for this bug I can't remember why I opened it (or its companion bug for 1.0.x). I'm looking at the commits for libuv for 1.9.2 at https://github.com/aspnet/libuv-package/commits/1.9.2 but nothing strikes me as "important" or "better."

Do you have any idea why we'd update libuv from 1.9.1 to 1.9.2 in a patch?

**Comment by muratg** [comment]
I don't remember why we had these, perhaps we did the update in 2.0.0 branch and decided to take it in 1.x as well? 

I'm OK with not taking these in the current patch releases unless @moozzyk has a good reason to take these in.

**Comment by Eilon** [comment]
Talked to @moozzyk and we need to take this.

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by Eilon** [comment]
@muratg - can you assign?

**Comment by cesarbs** [comment]
I can grab this.
