### ISSUE TITLE
Update Kestrel 1.0.x to use latest Libuv 1.9.x

### ISSUE THREAD

**Issue by Eilon** [aspnet/KestrelHttpServer#1898]
The current public Kestrel 1.0.x is referencing Libuv 1.9.0, but we have a better 1.9.2 build that's public.

https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel/1.0.4

**Comment by Eilon** [comment]
See related bug for 1.1.x: https://github.com/aspnet/KestrelHttpServer/issues/1897

**Comment by Eilon** [comment]
This patch is *approved* for 1.0.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by Eilon** [comment]
@muratg - can you assign?

**Comment by cesarbs** [comment]
I can grab this.
