### ISSUE TITLE
Consistently handle invalid chunk sizes in request bodies

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1899]
Sometimes invalid chunk sizes in chunked request bodies result in a 400 response, and other times the connection is simply closed. [Here's why.](https://github.com/aspnet/KestrelHttpServer/blob/a97c08843c620171b8ca781fd1d7fe8b7af0ac4a/src/Microsoft.AspNetCore.Server.Kestrel.Core/Internal/Http/MessageBody.cs#L749-L754) Given an OverflowException, I think we should call ThrowRequestRejected like we do for a character out of range which would result in a 4XX response.

**Comment by muratg** [comment]
Mostly an edge case, should be an easy fix.
