### ISSUE TITLE
Externally-provided file handles do not handle unix domain sockets well

### ISSUE THREAD

**Issue by onyxmaster** [aspnet/KestrelHttpServer#1906]
The common scenario for systemd-activated service being placed behind a reverse proxy involves using local Unix domain sockets. While Kestrel itself supports them, systemd activation assumes that socket handle is passed from a parent process. Currently, the [ListenerContext.CreateAcceptSocket](https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0-preview2/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/Internal/ListenerContext.cs#L26) and [Listener.CreateListenSocket](https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0-preview2/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/Internal/Listener.cs#L49) assume that externally passed file handle is always a TCP one. This leads to inability to use Unix domain sockets for systemd-based activation (socket creation fails with ENOTSUP, as expected).

I slapped together a quick "fix", extending UvPipeHandle a bit, and handling passed file handle as a pipe is easy, given that libuv already supports everything that is needed, but determining the socket type only by file handle isn't that easy. Either there is a platform-dependent call (getsockopt), or a try/catching around  socket creation in places mentioned with fallback to pipes instead of tcp. Also, maybe the socket type should be determined in configuration code around [UseSystemd](https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0-preview2/src/Microsoft.AspNetCore.Server.Kestrel.Core/Systemd/KesterlServerOptionsSystemdExtensions.cs#L39), potentially introducing new ListenType (SocketFileHandle?).

I'm not posting the fix here, because without finding out the proper way to determine the socket type it isn't very useful, so I'm asking for some kind of a guidance on the preferred way.

**Comment by onyxmaster** [comment]
Another option would be improved systemd integration with [support for multiple FDs](https://www.freedesktop.org/software/systemd/man/sd_listen_fds.html), then testing for specific FD state would be a part of the integration API ([sd_is_socket_unix](https://www.freedesktop.org/software/systemd/man/sd_is_socket_unix.html)).
Yet, this is probably harder than it should be, because of additional [native dependencies](https://www.freedesktop.org/software/systemd/man/sd-daemon.html).

**Comment by muratg** [comment]
@onyxmaster Is there a way to do it without native calls?  We mainly designed the externally-provided file-handles for SystemD activation, though we'd be happy to hear more of your thoughts. Backlogging this for now.

**Comment by onyxmaster** [comment]
The simplest way to handling this is via exception handling as follows:
If ListenType is a FileHandle, we should try to treat it as a TCP socket. Then, attempting to perform TCP-related initialization operations (like disabling Nagle algorithm) will fail with ENOTSUP. We could handle this exception, assuming this is a non-TCP socket and, hence, a pipe (in libuv terms). The exception presence could be cached to prevent doing unnecessary work on each connection accept.
Would you like to take a look at a PR that implements this method?
Also, I still believe that extending ListenType to contain more specific FileHandle types is an option worth exploring. This might break existing API though, and while its exposure is fairly limited at this point, I don't believe I'm in position to advise you on this one.

**Comment by onyxmaster** [comment]
Let me elaborate a little on ListenType types.
I propose that the ListenType.FileHandle remains as it is and is considered an "autodetected" file handle type.
Then, endpoint info should be cached locally by the Listener/ListenerContext that would convert the ListenType to a more specific type (TcpFileHandle/PipeFileHandle) on listen socket creation and cache it locally again, so the subsequent invocations on the Listener/ListenerContext would not need to go through the detection phase. This will preserve most of the existing code, including potential third-party one, and will allow direct specification of the file handle socket type in the ListenOptions constructor if desired by the caller.

**Comment by halter73** [comment]
I like the ListenType.TcpFileHandle/PipeFileHandle idea.

2.0.0 is being released fairly soon, so I can't make any promises, but if you submit a PR within the next few days, I'd likely accept it.

**Comment by onyxmaster** [comment]
Looks like it's done, thank you!
