### ISSUE TITLE
Flaky test: ThrowsWhenBindingLocalhostToIPv6AddressInUse

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#1927]
Reproes on Ubuntu 
```
  Failed   ThrowsWhenBindingLocalhostToIPv6AddressInUse
  Error Message:
   Assert.Equal() Failure
                                   ↓ (pos 33)
  Expected: ···d to address http://[::1]:50156: address already in use.
  Actual:   ···d to address http://127.0.0.1:50156: address already in use.
                                   ↑ (pos 33)
  Stack Trace:
  at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ThrowsWhenBindingLocalhostToAddressInUse(AddressFamily addressFamily, IPAddress address) in /datadrive/teamcity/33bdfc1cae7b2a38/.r/KestrelHttpServer/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 542
```

**Comment by natemcmaster** [comment]
Wrong stack trace? Issue description says ThrowsWhenBindingLocalhostToIPv6AddressInUse  but stack trace shows RejectsRequestWithContentLengthAndUpgrade

**Comment by pakrym** [comment]
Updated

**Comment by mikeharder** [comment]
Another repro: http://aspnetci/viewLog.html?buildId=256125&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR

**Comment by ryanbrandenburg** [comment]
Another repro http://aspnetci/viewLog.html?buildId=306862&buildTypeId=CoreCLR_Linux&tab=buildLog&_focus=16880

**Comment by muratg** [comment]
@ryanbrandenburg still fails?

**Comment by ryanbrandenburg** [comment]
[Still happening](http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=352560&_focus=141016) as of at least November 3rd.

**Comment by halter73** [comment]
Interesting that this only happens on ubuntu. I wonder if `socket.Bind(new IPEndPoint(IPAddress.IPv6Loopback, 0));` will bind to port currently in use for IPv4.

If so, I guess the only option would be to first try to bind to a port using both IPv4Loopback and IPv6Loopback, unbind one, and only then run the rest of the test.

**Comment by muratg** [comment]
What's the status? @halter73 any updates on the investigation?

**Comment by halter73** [comment]
No update. I'm currently tracking down null reference exceptions (#2223) from the same test project on linux. I haven't personally seen this failure since November.
