### ISSUE TITLE
Increase default MinRequestBodyDataRate to match IIS's default

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#1929]
I believe the ISS default is [240 bytes/second](https://www.iis.net/configreference/system.applicationhost/weblimits#005).

**Comment by halter73** [comment]
@muratg @blowdart ping.

**Comment by blowdart** [comment]
Yup, do it.

**Comment by cesarbs** [comment]
Note that the IIS min rate is the response min rate.

240 bytes/second might be too aggressive and drop legit connections from slow clients. The current default ensures there is at least *some* (1 byte) network activity every second, without dropping clients with limited network resources.
