### ISSUE TITLE
Externally-provided socket ownership in the context of systemd socket activation

### ISSUE THREAD

**Issue by onyxmaster** [aspnet/KestrelHttpServer#1934]
First, I would like to tell you that I understand that the described mode of operation may be out of scope of this specific project and should not be improved on here, with current API it could be solved externally, Yet, I still believe that you should know that there might be an oversight.

Currently, the `KestrelServerOptions.ListenHandle` and the underlying **libuv**-based socket handling code assumes ownership of the passed handle (via `uv_tcp_open`/`uv_pipe_open`), destroying the underlying descriptor when it's being closed. This leads to handle being unusable after listen socket is closed when server is shut down.

Normally, this is not a problem (although it probably should be explicitly mentioned in the documentation comments), but consider the the following scenario. For my project (not yet on Github), I would like to implement support for graceful server reload without the process restart along the lines of:
```c#
public static void Main(string[] args)
{
    while (true)
    {
        using (var host = BuildWebHost())
        {
            host.Run();
        }
    }
}
```
The specific implementation of `BuildWebHost` is irrelevant, it uses `WebHostBuilder`, configuring **systemd** activation with `UseSystemd`.
This allows to declare **systemd** service like this (non-crucial parts omitted):
`some-server.service`
```ini
[Unit]
Requires=some-server.socket

[Service]
ExecStart=/usr/bin/dotnet /opt/some-server/some-server.dll
ExecReload=/bin/kill -INT $MAINPID
NonBlocking=true
```

`some-server.socket`
```ini
[Unit]
PartOf=some-server.service

[Socket]
ListenStream=127.0.0.1:5555
NoDelay=true
```

Since ASP.NET Core installs proper signal handlers, `SIGINT` can be used to reload the server without a process restart, while `SIGTERM` will terminate the process altogether, and it works perfectly, but... since **systemd** provides socket handle (`KesterlServerOptionsSystemdExtensions.SdListenFdsStart`) via forking, the first Kestrel shutdown closes the passed descriptor and it can no longer can be used for subsequent Kestrel instances hosted in the same processe.
I again stress that this might be a less-than-usual case, and not worth your attention, but I still believe you should know of this.

So, was `ListenHandle` designed to destroy the passed descriptor on Kestrel instance shutdown, or is it an unintended consequence? Do you consider this a potential problem, and interested in improving `ListenHandle` itself, or **systemd**-activated scenario, by handling this in `UseSystemd`? Maybe consider splitting **systemd** integration in a separate project?
The only practical solution for this from a technical standpoint is duplication of provided file descriptor (either in `Listener` or in `UseSystemd`, though I believe that the latter being a configuration-related piece of code should not invoke syscalls). Unfortunately, this will require importing two native methods from the RT -- `int dup(int oldfd)` and `int close(int fd)` (the latter only required to handle error cases to prevent descriptor leaks), maybe the `fcntl` + `F_DUPFDCLOEXEC` should be used, but since Kestrel host is unlikely to spawn additional processes, we might as well skip on it. This looks quite easy to implement for Linux, I even hacked together a quick fix and it _works_, but its design and additional native dependencies don't really look good. To make things worse, the Windows version would need another pair of native calls (`DuplicateHandle` and `CloseHandle` respectively).

Thank you for reading this wall of text and considering the potential paths for improvement.

P.S. As a matter of a fact, there were other "victims" of this libuv mode of operation, see https://github.com/libuv/libuv/issues/510 and https://github.com/libuv/libuv/issues/390 (I wonder how Kelly solved it in haywire).

**Comment by halter73** [comment]
Very interesting. I had not considered reusing the listen handle.

It wouldn't be unheard of to add some non-libuv native calls given a compelling reason as long as it's well tested. We've had to make an [OS-specific native call](https://github.com/aspnet/KestrelHttpServer/blob/eea0c6490e1c65d91044b82269a98a790e8b172a/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/Internal/Networking/LibuvFunctions.cs#L617) before to [facilitate duplicating an accepted socket efficiently](https://github.com/aspnet/KestrelHttpServer/blob/eea0c6490e1c65d91044b82269a98a790e8b172a/src/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/Internal/ListenerPrimary.cs#L156). This idea actually came from @saghul's comment in the libuv/libuv#390 issue you mentioned.

My knowledge of using systemd socket activation is pretty much limited to writing that original docker-based test, so I have a few questions about it.

First of all, after the listen handle is closed by Kestrel during shutdown, won't systemd create a new listen handle for the specified TCP and/or Unix domain socket and relaunch the specified service once a new connection is attempted? If so, why does it matter that the listen socket is momentarily closed? If not, why doesn't it work this way?

Secondly, even if Kestrel left the original listen handle open by duping it first, wouldn't it still have to close all the active accepted sockets when it shuts down? Does leaving the original listen handle open prevent connection refused error somehow?

**Comment by onyxmaster** [comment]
At first, let me note that there is no problem with socket activation and server **restarts** (for example via `systemctl restart`), it's the **reload** (in-process disposal of Kestrel instance and re-creation of a new one) that is the problem -- this is why I believe it's a nonstandard scenario.
Now to the questions. 
The activated process can't close the actual socket that is being listened (and that is why I like systemd, don't have to write master process myself), because it's a duplicate of a systemd one (systemd creates socket, then forks and execs the target service, [cloning](https://github.com/systemd/systemd/blob/master/src/activate/activate.c#L210) the socket to use a specific descriptor). But, the activated process can close it's own copy of the socket, preventing it's reuse **inside** the process itself.
And no, I don't _think_ that original socket needs extra handling except duplication itself. Until the service process is dead, it's just an extra descriptor that can be used to start Kestrel instances, and when process dies, it automatically gets destroyed by the OS (since it's a clone of the original systemd socket, the original socket still lives in systemd).

**Comment by halter73** [comment]
@onyxmaster If I'm understanding your scenario correctly, I think it's probably niche enough to leave it to the app developer to dup the socket themselves even though it's not that easy.

If it was as simple as not calling uv_close on the listen socket when it was passed in via ListenHandle, I would probably be willing to do that, but AFAIK there is no other way to unregister the uv_listen callback.

We could keep the callback registered and just stop calling uv_accept when Kestrel shuts down, but I don't know for sure that a new Kestrel instance would be able to configure a second uv_listen callback. I'm not even sure that's worth testing, because it feels very hacky.

**Comment by onyxmaster** [comment]
@halter73 well, I thought along the same lines. I'm planning to do additional systemd integration using native calls anyways (to take advantage of structured logging via journald). Still it's good we had this conversation, might be useful for future reference. Thank you for considering the options.
