### ISSUE TITLE
Kestrel not picking up port from config...

### ISSUE THREAD

**Issue by mastrauckas** [aspnet/KestrelHttpServer#1935]
When creating a new `webapi` project by doing:
`dotnet new webapi -n test_project`

I update `appsettings.json` and add `Kestrel`.  My `appsettings.json` looks like:
```json
{
  "Kresrel": {
    "Endpoints": {
      "Localhost": {
        "Address": "127.0.0.1",
        "Port": "2032"
      }
    }
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  }
}
```
Now on the command line in directory with `test_project.csproj` I run `dotnet run` which still connects to `http://127.0.0.1:5000` and not `http://127.0.0.1:2032`.

I am on `macOS` using `zsh` and I created the template in both
`dotnet core 2.0.0-preview1-005977` and `2.0.0-preview2-006497` and getting the same result.

Not completely sure what I'm doing wrong?

**Comment by davidfowl** [comment]
You misspelt Kestrel in your configuration file

**Comment by mastrauckas** [comment]
@davidfowl Now I feel really stupid!  Thanks for your help!
