### ISSUE TITLE
Make write timeout work on Socket transport

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#1943]
A pending write could be hanging the write loop, so we need to abort it out of band in case of a write timeout. In the libuv transport we do this by disposing the socket in the writer completion callback, which cancels the pending write req.

**Comment by Eilon** [comment]
@muratg / @halter73 - anything to do here for preview1?

**Comment by muratg** [comment]
We'll be overhauling this area as we continue to investigate Sockets transport as a transport.

**Comment by tmds** [comment]
@muratg @cesarbs are you tracking this elsewhere? Sockets transport should not be used in production without a timeout.

**Comment by tmds** [comment]
@davidfowl is this still being tracked? it is important...

**Comment by halter73** [comment]
Yes. We need to rework the write timeout logic in a few places and we're using #2171 to track getting the write timeout logic working the correctly for all transports and configurations.
