### ISSUE TITLE
Validate Key Usage on server certificates

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#1946]
We added validation for the Extended Key Usage extension on server certificates, however there is another extension, Key Usage, that might also indicate restrictions on certificate usage. We should investigate which flags should be required, and how Kestrel should accept handle server certificates that don't have these flags. e.g. should we restrict, warn, or allow?

**Comment by muratg** [comment]
No plans to implement this in 2.x
