### ISSUE TITLE
No way to set base path before startup

### ISSUE THREAD

**Issue by bklooste** [aspnet/KestrelHttpServer#1949]
We do a lot of work before startup which allows switching of hosts and services  eg web lister 
```
    public IWebHostBuilder GetWebHostBuilder(string serviceUrl, Action<IServiceCollection> servicesAction)
        {
            var builder = new WebHostBuilder()
                        .UseLoggerFactory(loggerFactory)
                        .UseWebListener()
                        .ConfigureServices(servicesAction)
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseStartup<Startup>()
                        .UseUrls(serviceUrl);

                builder.UseApplicationInsights(cosmosOptions.MonitoringOptions.ApplicationInsightsKey);

            return builder;
        }

```
However the new changes to Kestrel ( Remove splitting of path and path base in Kestrel #1050 ) seem to make it impossible to change the url before startup is run .. and have a common startup which is pretty ugly ..

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/1120 has been filed for this. You could work around it by registering an IStartupFilter, that's what IISIntegration does.
https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs#L26
