### ISSUE TITLE
Flaky test: ConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#1955]
Saw this test failure on Travis today. Appears to have failed this assertion:
```c#
Assert.True(aborted.Wait(TimeSpan.FromSeconds(60)));
```

```
Failed   ConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<ConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate>d__64.MoveNext() in /home/travis/build/aspnet/KestrelHttpServer/test/Kestrel.FunctionalTests/ResponseTests.cs:line 2499
```

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/252952635#L994-L1000

cc @cesarbs

**Comment by mikeharder** [comment]
Caused 2 failures of the Ubuntu mirror:

* http://aspnetci/viewLog.html?buildId=290526&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux
* http://aspnetci/viewLog.html?buildId=290537&tab=buildResultsDiv&buildTypeId=CoreCLR_Linux

We need to prioritize fixing this test since it's causing slowdowns and manual work in build steps like the mirror.

**Comment by muratg** [comment]
@cesarbs please take a look.

**Comment by davidfowl** [comment]
I'm seeing this fail again and I can't tell if it's because of my changes or if it's because this test is generally flaky.

**Comment by natemcmaster** [comment]
I think this test is still flaky. Just failed again.

http://aspnetci/viewLog.html?buildId=339030&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

```
The request was not aborted within the timeout period.
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.ConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate() in C:\b\w\33bdfc1cae7b2a38\.r\KestrelHttpServer\test\Kestrel.FunctionalTests\ResponseTests.cs:line 2496
```

**Comment by ryanbrandenburg** [comment]
And more recently: http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=347655&_focus=191588

**Comment by muratg** [comment]
Is this still failing?

**Comment by ryanbrandenburg** [comment]
It's been long enough since this failed in dev that we can close this. If it starts showing up again we can always re-file.
