### ISSUE TITLE
Websocket stop working? 

### ISSUE THREAD

**Issue by sk29110** [aspnet/KestrelHttpServer#1964]
In my applicartion, I am using the web socket to update the status of data generationin the database. It works perfectly when one person is using. However when multiple users are trying to access this feature. web socket closes all the sudden.
I am trying to get the point where is the bottom neck. I have set up the JMeter to test the websocket and found out I am getting this error message. 

Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HL6FPVS1U8A1" communication error.

I was wondering if any has the similar problem or if there are any workaround I can make.

**Comment by davidfowl** [comment]
Can you put your application (or a representative sample) on github so we can take a look?

**Comment by muratg** [comment]
No repro
