### ISSUE TITLE
Compile error: "cannot convert from 'long' to 'int'"

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#1970]
https://travis-ci.org/aspnet/KestrelHttpServer/builds/257936555

> Internal/Http/MessageBody.cs(693,54): error CS1503: Argument 2: cannot convert from 'long' to 'int' [/home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel.Core/Microsoft.AspNetCore.Server.Kestrel.Core.csproj]
Internal/Http/MessageBody.cs(696,38): error CS1503: Argument 2: cannot convert from 'long' to 'int' [/home/travis/build/aspnet/KestrelHttpServer/src/Microsoft.AspNetCore.Server.Kestrel.Core/Microsoft.AspNetCore.Server.Kestrel.Core.csproj]

/cc @pakrym

**Comment by benaadams** [comment]
From "React to pipeline changes" https://github.com/aspnet/KestrelHttpServer/pull/1969?

**Comment by benaadams** [comment]
ReadChunkedData also needs `(int)` cast before `Math.Min`

**Comment by benaadams** [comment]
Fix https://github.com/aspnet/KestrelHttpServer/pull/1971

**Comment by pakrym** [comment]
@benaadams builds fine on our CI, what version of `microsoft.aspnetcore.internal.corefxlab.sources` package did you get on restore?

**Comment by benaadams** [comment]
Broke on the PR checks for https://github.com/aspnet/KestrelHttpServer/pull/1969 and merge to [aspnet/dev](https://github.com/aspnet/KestrelHttpServer/commits/dev)

Has missing cast in MessageBody.cs

**Comment by benaadams** [comment]
e.g. https://github.com/aspnet/KestrelHttpServer/pull/1971/files

**Comment by pakrym** [comment]
It doesn't. Both of them are `long`s and `Move` takes `long` now too: https://github.com/dotnet/corefxlab/commit/ef85b95b9be2e0f1b65dbee0ebca5d009af125df#diff-fd9ac6176e69e14568677bdda20dcf36R326

**Comment by benaadams** [comment]
Ah, must be laggy packages then

**Comment by benaadams** [comment]
AppVeyor and Travis on GitHub are still failing though https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.5697

**Comment by benaadams** [comment]
Are the changes in corefxlab in the right branch?

**Comment by davidfowl** [comment]
We're still using the aspnetcore branch.

**Comment by pakrym** [comment]
@benaadams we have issues with part of CI that pushes packages to public feed, should be fixed tomorrow.
