### ISSUE TITLE
Make Intellisense comments on Limits include default values

### ISSUE THREAD

**Issue by jkotalik** [aspnet/KestrelHttpServer#1972]
When setting Kestrel's limits, the default values for each should show up in the IntelliSense. For example
![image](https://user-images.githubusercontent.com/8302101/28649359-307f9cd4-7229-11e7-811b-cd103346a971.png)

(sorry for image size) is confusing because by setting the property to null, there is no minimum data rate, making it seem like the default minimum data rate is 0 (which it may or may not be).

**Comment by natemcmaster** [comment]
Should be easy. Just move the comments from `<remarks>` to `<summary>`.

![image](https://user-images.githubusercontent.com/2696087/28649540-81d0af6e-722a-11e7-9afe-915de1bdd5da.png)

**Comment by jkotalik** [comment]
We should probably trim down the summaries though per @halter73

**Comment by priyanshu92** [comment]
How does this look? @jkotalik @natemcmaster 

![image](https://user-images.githubusercontent.com/7589718/35935345-34572d72-0c66-11e8-82a6-1ef29e246f66.png)

**Comment by halter73** [comment]
@priyanshu92 LGTM. I wonder if we should make the doc comments shorter, but I think it's probably fine at the current level of detail.

**Comment by natemcmaster** [comment]
Shorter if you can, or try adding paragraph breaks using `<para>`. Intellisense should honor those.

**Comment by priyanshu92** [comment]
Looks like @redouane64 beat me to it 😄
