### ISSUE TITLE
Remote IP on Reverse Proxy scenarios

### ISSUE THREAD

**Issue by luisgizirian** [aspnet/KestrelHttpServer#1974]
Why is that `Context.Connection.RemoteIpAddress` supplies the Proxy's address in scenarios where `ForwardedHeadersOptions` were applied (either automatically by UseIISIntegration or manually), but `Context.Request.Headers["X-Forwarded-For"][0]` gives me the right address?

If I don't know beforehand the `ForwardedHeadersOptions.KnownProxies`, Is it possible to use the first X-Forwarded-For address to pre-fill `Context.Connection.RemoteIpAddress`? (`ForwardedHeadersOptions.ForwardLimit = 1` its default. And `RequireHeaderSymmetry = false` ) so I always get the Client/Browser IP address no matter what?

Tested scenarios (all based on ASPNET Core 2 preview 2):

* NGINX to Kestrel (single Azure Ubuntu VM)
* NGINX to Kestrel (2 Azure Ubuntu VMs)
* NGINX to Azure App Service to Kestrel (don't ask why, just did)

An app comparing and writing back both values, following this document (https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction) is all you need.

Quick short-circuit: `Configure` in Startup.cs:

```
app.Run(async (context) => await context.Response.WriteAsync("RemoteIPAddress property: " + context.Connection.RemoteIpAddress.ToString() + "\nX-Forwarded-For [0] Header: " + context.Request.Headers["X-Forwarded-For"][0] ));
                })
```

Please advice.

(my apologies if this is not the right place to post this question)

**Comment by Tratcher** [comment]
This issue was moved to aspnet/BasicMiddleware#256
