### ISSUE TITLE
Allow Visual Studio to break on unhandled exceptions

### ISSUE THREAD

**Issue by hultqvist** [aspnet/KestrelHttpServer#1992]
Usually Visual Studio breaks on unhandled exceptions.

When running Kestrel any exceptions in code serving HTTP requests appear to be caught by Kestrel and reported to the console.

`Err.
        [Microsoft.AspNetCore.Server.Kestrel] Connection id "0HL70LNDQA2FS": An unhandled exception was thrown by the application.
        C:\Users\my\Source\bin\Debug\net461\win7-x86\Microsoft.Extensions.Logging.dll.Microsoft.Extensions.Logging.Logger.Log(...)`

Is there a way to prevent kestrel from catching the exception, allowing it to be caught by the Visual Studio IDE?
Without the option "Break when this exception type is thrown"

![image](https://user-images.githubusercontent.com/505330/29211816-844ffd12-7e9b-11e7-88e9-de6956158386.png)

**Comment by Tratcher** [comment]
Unhandled exceptions are the ones that cause your process to crash. We don't want the webserver to crash. First chance exceptions are your best option.

**Comment by Tratcher** [comment]
@halter73 @shirhatti There have been multiple asks for this. What if we added `if (Debugger.IsAttached) Debugger.Break()` to the root exception handler in Kestrel and HttpSys? That would simulate the behavior. The downside is you couldn't control it from VS settings. I wonder if VS has an environment variable that could control this?

**Comment by shirhatti** [comment]
> The downside is you couldn't control it from VS settings

IMO, that would be a deal breaker.
