### ISSUE TITLE
kestrel hosting.ini multiple endpoints

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#200]
_From @grahamehorner on September 10, 2015 14:57_

at present the hosting.ini used by kestrel can only have a single endpoint address; is there any plans to allow multiple endpoints ie. http/https or multi-homing of the site? and/or hosting multiple sites/endpoints under the same instance of dnx kestrel?

_Copied from original issue: aspnet/Home#914_

**Comment by Tratcher** [comment]
A semicolon separated list is already supported: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/KestrelServerInformation.cs#L28

https support is in the works.  https://github.com/aspnet/KestrelHttpServer/issues/83

**Comment by muratg** [comment]
@Tratcher So it's already supported, right? Can we close this?
