### ISSUE TITLE
HTTPS binding configuration for Kestrel

### ISSUE THREAD

**Issue by javiercn** [aspnet/KestrelHttpServer#2016]
We need to figure out how config for HTTPS will work for Kestrel in development. (Config format for setting up an HTTPS binding and how will tooling setup the bindings during development). 

This is part of our plan for HTTPS in 2.1

**Comment by muratg** [comment]
@cesarbs assigning this to you.  I suspect we'll need to design this.  cc @shirhatti and @davidfowl

**Comment by Tratcher** [comment]
How much of this is just bringing back the config feature we cut from 2.0?

**Comment by muratg** [comment]
@shirhatti will schedule a design meeting to plan this work.

**Comment by muratg** [comment]
@shirhatti where are we with this one?

**Comment by muratg** [comment]
@anurse could you sync-up with @Tratcher?

**Comment by anurse** [comment]
I haven't really had a chance to work on this beyond what I've already sent out. We can sync up on Monday though if there are any gaps that haven't been filled.

**Comment by javiercn** [comment]
We have the dev part done. We need to figure out configuration for production scenarios

**Comment by danroth27** [comment]
@Tratcher Is this a dup of #1290?

**Comment by danroth27** [comment]
Nevermind - https://github.com/aspnet/KestrelHttpServer/pull/2186 clarifies that #1290 is tracking "config and code parity".
