### ISSUE TITLE
ObjectDisposedException when UvStreamHandle.ReleaseHandle

### ISSUE THREAD

**Issue by tmds** [aspnet/KestrelHttpServer#202]
I am running a load test using beta7 Kestrel on Windows 10. At some point Kestrel stops with the following stacktrace and messagebox:
```
Unhandled Exception: System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.async_send(UvAsyncHandle handle)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.PostCloseHandle(Action`1 callback, IntPtr handle)
   at Microsoft.AspNet.Server.Kestrel.Networking.UvHandle.ReleaseHandle()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvStreamHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

![screenshot](https://cloud.githubusercontent.com/assets/1025424/9808053/b24858f8-585b-11e5-8cad-0e0ac6140af2.png)

**Comment by tmds** [comment]
The website i am using works with websockets. I am using the websockets 'out-of-spec' since I am doing 1 receive concurrent with multiple sends. When a close message is received, the websockets is closed (and disposed) on the server. Some sends might still be 'in-flight' at that time. I expected those to throw objectdisposed (instead of the webserver exiting).

**Comment by davidfowl** [comment]
@tmds Think you could provide a sample application that mimicks what you're doing?

**Comment by tmds** [comment]
I am trying to benchmark an asp.net 5 sockjs implementation I am developping. The benchmark consists of an test website (ASP.NET) and a sockjs benchmark (forked project, java).

The testwebsite lives here: https://github.com/tmds/Tmds.SockJS/tree/master/test/WebSites/TestWebSite.
```
dnx kestrel
```
The load program lives here (jar): https://github.com/tmds/sock-benchmarking/releases/download/v0.1.0/SocketIOLoadTester.jar
```
java -jar SockIOLoadTester.jar sockjs localhost:8081 logprefix
```

The load tests connects a number of clients (websockets) to the server. Then it sends a number of messages via those clients. When the server receives a message, it broadcasts it back to the clients. This is implemented here: https://github.com/tmds/Tmds.SockJS/blob/master/test/WebSites/TestWebSite/BroadcastMiddleware.cs.

The server implementation currently does one ReceiveAsync and (multiple) SendAsync concurrently on a WebSocket, which is 'undefined behaviour'. (see https://github.com/aspnet/WebSockets/issues/42)

Perhaps the error is the result of a scheduled write on the KestrelThread on a Stream which has been Disposed in the meanwhile.

**Comment by davidfowl** [comment]
Great! This will help reproduce the problem when we get someone to look at it.

**Comment by muratg** [comment]
@halter73 Please have a look when you have some time.

**Comment by tmds** [comment]
@halter73 do you have an idea when you'll have some time?

**Comment by halter73** [comment]
@tmds I haven't gotten a chance to run your repro website yet, but I definitely could see how a UvStreamHandle could be closed before WriteAllPending/uv_write runs. I think at this point we should check if the handle as been closed.

The handle can only be closed on the libuv thread, so there shouldn't be any thread safety issues. I'm working on HTTPS and some refactoring right now, but I hope to be able to fix this by next week.

**Comment by tmds** [comment]
@halter73 In case it has been closed, throwing ObjectDisposed on those pending operations is probably what should happen? When you've implemented this, I can verify the error no longer occurs in my scenario.

**Comment by halter73** [comment]
I'm fairly certain that this was fixed by @lodejard's refactoring. [This change](https://github.com/aspnet/KestrelHttpServer/commit/e5a3bda3a2a6e615da5f01ac03a9e1b26f7b7c0f#diff-73583bec86ef8f12929e8e2190b83484R287) to SocketOutput checks that `_socket.IsClosed` is false before using the socket the Execute, StageTwo or StageThree methods.

This change will be in beta8.

**Comment by troydai** [comment]
@tmds I verified your app under beta8 and the issue went away. (under the same environment I could repo this issue under beta7). It looks the like exception is indeed fixed. I'm going to close this issue. Thanks.

**Comment by tmds** [comment]
Great! Thanks.

**Comment by troydai** [comment]
No problem. If you still encounter similar issue on beta8, please feel free to reopen this issue.
