### ISSUE TITLE
Response.OnCompleted not fired AFTER the Response is sent

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2035]
_From @JeanCollas on August 28, 2017 0:8_

Using ASP.NET Core 2.0
A simple code like this shows the issue:

    public async Task<IActionResult> TestOnComplete()
    {
            Response.OnCompleted(async () =>
            {
                throw new Exception();
            });
    }

Response.OnCompleted is said to be invoked after the response is sent to the user, so the user should already have got the answer, whatever happens there.

https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L75

>         /// <summary>
>         /// Adds a delegate to be invoked after the response has finished being sent to the client.
>         /// </summary>
>         /// <param name="callback">The delegate to invoke.</param>
>         /// <param name="state">A state object to capture and pass back to the delegate.</param>
>         public abstract void OnCompleted(Func<object, Task> callback, object state);

But this breaks the response. You can also set a breakpoint on the OnComplete action, the user will wait for the response until the breakpoint is passed.

This means that the OnCompleted is fired before the response is actually sent.

_Copied from original issue: aspnet/Home#2170_

**Comment by Tratcher** [comment]
Which server? Kestrel? HttpSys? IIS/Express + Kestrel?
Which version?

**Comment by Tratcher** [comment]
_From @JeanCollas on August 28, 2017 9:2_

IIS Express for the debugging, I haven't verified if it was the same behaviour on Full IIS+Kestrel.

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

**Comment by Tratcher** [comment]
Exceptions from OnCompleted should only ever be logged, they should not interfere with the processing of the response or even prevent other OnCompleted callbacks from running.

**Comment by halter73** [comment]
Looks like the issue is that the `OnCompleted` callbacks are called prior to sending the chunked terminator. When an `OnCompleted` callback throws, `_applicationException` is set and `Frame` which then prevents the chunked terminator from being sent.

Not that this makes things much better, but I've verified that the response is unaffected if a Content-Length is specified

**Comment by JeanCollas** [comment]
The OnCompleted is said to be executed after the sent to the user, so the response time and performances should not be affected by the call of this method.
If it should be executed before sending, it should be called "OnBeforeSending" ;) 
BTW for now I have used Task.Run not to affect the performances of the response time.

**Comment by halter73** [comment]
@JeanCollas Agreed. This is definitely a bug.

**Comment by justinwyer** [comment]
I'd like to grab this.

**Comment by halter73** [comment]
@Im5tu Thanks for the reminder!
