### ISSUE TITLE
TestServer w/ WebHostBuilder doesn't read appsettings.json on ASP.NET Core 2.0, but it worked on 1.1

### ISSUE THREAD

**Issue by neooleg** [aspnet/KestrelHttpServer#2042]
## STR
1. Use .NET 2.0
1. Follow [official manual](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) to create integration tests
1. Use the following code for test server
```
_server = new TestServer(new WebHostBuilder()
    .UseEnvironment("Development")
    .UseContentRoot(projectDir)
    .UseStartup<TestStartup>());
```

h3. AR
- appsettings.json doesn't read and TestStartup doesn't receive them.
- It looks like breaking changes (not found anything documented it) because the same code worked on ASP.NET Core 1.1

h3. ER
appsettings.json should be read and passed into Startup.

**Comment by natemcmaster** [comment]
This issue was moved to aspnet/Hosting#1191
