### ISSUE TITLE
Kestrel as an in-process reverse proxy

### ISSUE THREAD

**Issue by austindrenski** [aspnet/KestrelHttpServer#2046]
##  Introduction

I have a project that needs to hook several Kestrel-based microservices to a single endpoint on an internal network. There is a competing requirement to avoid separate reverse proxies, such as IIS/Nginx/Apache.

I've prototyped some middleware that seems to meet my project requirements. But I was hoping that someone with a deeper knowledge of Kestrel, its team, and the associated design/engineering decisions might be able to provide some context on a few topics.

## Approach

After some tinkering, I've prototyped some middleware that allows one Kestrel server to arbitrarily register/unregister targets and internally branch to the target if certain conditions are met, then respond to the caller with the target's response.

This is not altogether different than a URL rewrite approach, but it has the interesting property of being reconfigurable via an API throughout the lifetime of the host server.

There are a number of outstanding issues with this approach—not least of which being that aforementioned reconfiguration....which would allow any caller to register/unregister services, unchecked.

That said, for now—for the specific circumstances I'm working with—the prototype seems to fit the bill.

_Its nothing fancy, but for a reference implementation, see [AD.ReverseProxy](https://github.com/austindrenski/AD.ReverseProxy)._

## Example 
The division has two teams: the __time team__ and the __date team__. These teams want to:

 1. Work independently.
 2. Use Kestrel.
 3. Avoid IIS/Nginx/Apache.
 4. Swap the __time__ and __date__ microservices frequently and without notice.

When the __time__ and __date__ microservices start, they send the following GET requests to the endpoint server for registration:

 - GET: //production/api/register?target=//localhost:00001/time
 - GET: //production/api/register?target=//localhost:00002/date

Then these services are accessible by the following requests:

 - GET: //production/api/time
 - GET: //production/api/date

If the __time__ team wants to redeploy with a new version, they can apply the following pattern:

 1. While the old version is running on port 00001, start the new version on a new port, 00003.
 2. Register the new version:
    - GET: //production/api/register?target=//localhost:00003/time
 3. Unregister the old version:
    - GET: //production/api/unregister?target=//localhost:00001/time 
 4. Shutdown the old version.

The old version continues to serve requests until it is unregistered, at which point the next request finds its way to the new version's registered target.

### Question 1:
From what I've read, it sounds like port-sharing—along the lines of Http.Sys—is an explicit non-goal of the Kestrel team. From a slightly different angle:

Is there any discussion of providing Kestrel-as-a-reverse-proxy functionality?

### Question 2:
The prototype approach is fairly straightforward—it naively does what makes sense. So it seems like this could be the type of functionality that is absent from the framework for a—potentially serious—reason.

Are there known issues or risks in implementing this functionality?

### Question 3:
Is this type of functionality something that the Kestrel team would be interested in incorporating down the road?

**Comment by davidfowl** [comment]
> Is there any discussion of providing Kestrel-as-a-reverse-proxy functionality?

Yes but it's less about kestrel and more about ASP.NET offering a proxy middleware much like the one you've written. In fact there's one here https://github.com/aspnet/Proxy.

> Are there known issues or risks in implementing this functionality?

Exposing public endpoints that allow you to change how requests are routed seems pretty scary and also a bit opinionated. Our team is more about providing low level building blocks (for the most part) that allows you to build higher level functionality.

> Is this type of functionality something that the Kestrel team would be interested in incorporating down the road?

See the answer to your first question. The proxy middleware yes, everything else, highly likely not.

**Comment by khellang** [comment]
Sounds like you're building a mixture of a classic reverse proxy and a service registry, like [Træfik](https://github.com/containous/traefik)...

**Comment by austindrenski** [comment]
@davidfowl Thanks for your answers--the feedback is much appreciated!

Initially, the endpoint-based reconfiguration sounded handy, but with your comments in mind and another look through the code...it does indeed looks like a headache waiting to happen.

I'm going to narrow the functionality to focus on request dispatching and revert to startup configuration files. Thanks again.

@khellang Interesting! That does look similar to what I have in mind, and a project I wouldn't have known to look for. Thanks for the link!
