### ISSUE TITLE
Error -32 EPIPE broken pipe

### ISSUE THREAD

**Issue by suisgrand** [aspnet/KestrelHttpServer#2047]
using Mac OS & generator-aspnet-spa dotnet core application. Using Microsoft.AspNetCore 1.1 for kestrel. the console renders "Error -32 EPIPE broken pipe", and as a result the client/angular2 app remains in loading state.

Here's an extract of the log:

Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
What is confusing me the most is the fact that I am having this issue with all my "1.1" dotnet apps running on my OS machine from the last couple of hours. All of them had no problem running before that. Did I miss something here?

After some research, this could be the cause: the broken pipe error could show up if a request is blocked / takes too long => if a timeout on the client side is generated, the connection gets to be closed while the server would still attempt to write to the socket, throwing that issue.

here my program.cs and my attempt to increase the connection, but to no avail:

[public static void Main(string[] args)
        {
            var config = new ConfigurationBuilder()
                .AddCommandLine(args)
                .Build();
            var host = new WebHostBuilder()
                .UseConfiguration(config)
                .UseKestrel((options)=>
                {
                    options.ShutdownTimeout.Add(new TimeSpan(0, 3, 0));
                })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build();
            host.Run();
        }](url)
Can anybody help me? thanks!

**Comment by cesarbs** [comment]
Can you share a repro app?

**Comment by halter73** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/1978#issuecomment-319838683

**Comment by halter73** [comment]
As of #2547, a ConnectionResetException should be thrown instead of an UvException.
