### ISSUE TITLE
ConnectionResetException 

### ISSUE THREAD

**Issue by israellot** [aspnet/KestrelHttpServer#2048]
**Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException handled at System.Net.WebSockets.ManagedWebSocket+d__61.MoveNext** 

I'm constantly getting this exception ReceiveAsyncPrivate method. Basically all websocket connections eventually fail due to this exception after some minutes. I'm hosting on aspnetcore 2.0 on Azure WebApp.

**Comment by halter73** [comment]
@anurse @BrennanConroy Didn't you have to deal with this in SignalR? As far as I know, the WebSocket protocol defines a closing handshake for gracefully closing the connection. If the connection is severed ungracefully for any reason you will see a ConnectionResetException.

**Comment by anurse** [comment]
If the underlying TCP connection is severed ungracefully I'd expect something like this. If the TCP connection is being shut down gracefully (`FIN` frames, etc.) but the WebSocket close handshake isn't completed, then you'd get a `WebSocketException`

**Comment by muratg** [comment]
@israellot Could you provide a repro and details?

**Comment by israellot** [comment]
I've tried to create a repro but it turns out I was only able to notice the behavior when deployed to an Azure App Service. After creating a new AppService the problem didn't present itself as well.

**Comment by muratg** [comment]
OK thanks. Please let us know if you hit this again.
