### ISSUE TITLE
Port localhost:5000 not released causing error System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use.

### ISSUE THREAD

**Issue by foo-baar** [aspnet/KestrelHttpServer#2050]
Hi,

I installed dotnet core on Mac Sierra in order to build .net mvc application & while build a project I learned that donet\kestrel doesn't release the port 5000 after I stop a project causing port already in use error on next run.

I couldn't find any command\manual way to release\stop the port 5000 or localhost:500.

Please enlighten me if any such commend exists or any other possible solution.
error:
`System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.AddressInUseException: Error -48 EADDRINUSE address already in use ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -48 EADDRINUSE address already in use`

Thanks much 👍

**Comment by Tratcher** [comment]
Are you sure the process has exited? The OS ensures no port lock ever survives that, there's nothing Kestrel can do about it.

**Comment by foo-baar** [comment]
@Tratcher Hey, I Exited\stopped the process by clicking on "stop debug" button or using shortcut, I don't believe there is any other way of doing, is there so ?

`lsof -s:5000` 
shows its been occupied by dotnet

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
