### ISSUE TITLE
404 for static files with names starting with dots

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/KestrelHttpServer#2061]
Kestrel return 404 for static files which names starting with dot (".").
Like `http://localhost:5000/client/lib/interop/.interop.types.js`
Request for such files don't reach asp.net. I checked it via `OnPrepareResponse` handler for StaticFileMiddleware's options:
```
	app.UseStaticFiles(new StaticFileOptions
	{
		OnPrepareResponse = ctx =>
		{
			var f = ctx.File;
			if (f.Name.StartsWith("."))
			{
				Debugger.Break(); // we won't get here
			}
		},
		ServeUnknownFileTypes = true
	});
```

Is there any workaround for the issue?

**Comment by davidfowl** [comment]
This isn't a kestrel issue, by default files that start with `.` are blocked, see https://github.com/aspnet/FileSystem/issues/186. In 2.1 there's a new API you can use to change the defaults but in 2.0 you'd need to write a custom file provider that allowed finding files that started with `.`. 

See https://github.com/aspnet/FileSystem/issues/186 for more details.
