### ISSUE TITLE
HTTP/2: add flag to configure an endpoint as HTTP/2-only

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#2067]
Support HTTP/2 with prior knowledge per [Section 3.4](http://httpwg.org/specs/rfc7540.html#known-http) of RFC 7540. This can be done per-endpoint.

**Comment by Tratcher** [comment]
Your link is broken.

So you'd end up with some sort of protocol negotiation enum like HTTP1, HTTP2, HTTP1 | HTTP2... that you could translate to ALPN values.

**Comment by cesarbs** [comment]
Fixed the link.

No, the spec allows for direct HTTP/2 cleartext connections. There's no protocol negotiation in that case.

**Comment by Tratcher** [comment]
Sure, the same enum could be used for plaintext too, though the combine values wouldn't be valid.

**Comment by cesarbs** [comment]
@muratg I wouldn't call this a bug. It's more like an enhancement, or even a task (since we haven't shipped HTTP/2 support yet, this would look a bit odd showing up in the release notes - just HTTP/2 should suffice).
