### ISSUE TITLE
Perf Regression: Merge code paths duplicated between HTTP/1.x and HTTP/2 implementations

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2085]
"Merge code paths duplicated between HTTP/1.x and HTTP/2 implementations" (https://github.com/aspnet/KestrelHttpServer/issues/2017) seems to have caused a 5% regression in Plaintext on both Cloud and Physical hardware.  You can repro the regression by comparing branch `mikeharder/perf-test-before` to 1470ee0.

Hardware | mikeharder/perf-test-before | 1470ee0 | Ratio
------------ | ------------- | ------------ | ------------
Cloud | 560k | 534k | 0.95
Physical | 1.30M | 1.22M | 0.94

**Comment by anurse** [comment]
It does look like the RequestParsingBenchmark has also regressed by 5%. On mikeharder/perf-test-before I get these results: 

|               Method |     Mean |     Error |    StdDev |      Op/s | Scaled |  Gen 0 | Allocated |
|--------------------- |---------:|----------:|----------:|----------:|-------:|-------:|----------:|
| PlaintextTechEmpower | 1.093 us | 0.0258 us | 0.0386 us | 915,216.8 |   1.00 | 0.0019 |     416 B |

But on `dev` I get:

|               Method |     Mean |     Error |    StdDev |      Op/s | Scaled |  Gen 0 | Allocated |
|--------------------- |---------:|----------:|----------:|----------:|-------:|-------:|----------:|
| PlaintextTechEmpower | 1.144 us | 0.0296 us | 0.0443 us | 874,088.6 |   1.00 | 0.0019 |     416 B |

Going to start exploring that a little bit.

**Comment by anurse** [comment]
Resolved by #2123 (30010a103bb20f913d00f64d49a9914d37eb8650)
