### ISSUE TITLE
Remove automatic Upgrade header logic from UpgradeAsync

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2086]
https://github.com/aspnet/KestrelHttpServer/blob/a31d1e024ca86a4a9053e0be105fde17c5ccae10/src/Kestrel.Core/Internal/Http/Http1Connection.FeatureCollection.cs#L42-L50
This code copies the request Upgrade header to the response. However, the request Upgrade header is a list of suggestions, while the response is the ordered list of actually selected protocols. Setting any of these response headers is the caller's responsibility. The WebSocket middleware sets these.
https://github.com/aspnet/WebSockets/blob/31c1e9d7d727fda23ae657cb3598c7c3f3950d15/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs#L66-L75

https://tools.ietf.org/html/rfc7230#section-6.7

This method is also missing a HasResponseStarted check. It will fail only when it tries to set the StatusCode.

**Comment by brightcr** [comment]
I would like to work on this if this is still pending

**Comment by Tratcher** [comment]
There's an incomplete pull request you could try finishing. https://github.com/aspnet/KestrelHttpServer/pull/2300

**Comment by davidfowl** [comment]
Fixed
