### ISSUE TITLE
Set the Microsoft.AspNetCore.Server.Kestrel nuget package projectUrl element to this repository

### ISSUE THREAD

**Issue by rgl** [aspnet/KestrelHttpServer#2089]
It would be more useful to be able to easily jump from the nuget package at https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel/ to this source code repository (instead of linking to the asp.net site).

**Comment by muratg** [comment]
Thanks for reporting. It looks like this is an issue across the packages (and not just Kestrel) so I filed an internal bug to track this across the repos. Closing this one.
