### ISSUE TITLE
Multiple projects (Beta-7)

### ISSUE THREAD

**Issue by jrock2004** [aspnet/KestrelHttpServer#209]
In my solution I have multiple projects, one for serving the api, the other is a web project? What is the best way to run both of these projects at the same time? Do I have to execute a kestrel command for each project? Can I go to the root solution directory and add something to the global.json to all kestrel to start both? Thanks

**Comment by davidfowl** [comment]
Is this a kestrel question or a tooling question? Kestrel is part of the application's dependencies. It's like running 2 console applications.
