### ISSUE TITLE
[2.0.x] Builds are not reproducible without Microsoft.AspNetCore.Internal.CoreFxLab.Sources

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#2105]
The 2.0.x branch of Kestrel has a package dependency on Microsoft.AspNetCore.Internal.CoreFxLab.Sources, however, there is no open-source way to figure out exactly how to generate this package. 

Recommendations:

Either
 - Add corefxlab as a git submodule
 - Add scripts to kestrel to generate the package
 - Add scripts to aspnet/Universe to generate this package

cc @pakrym @mikeharder

**Comment by pakrym** [comment]
Do we have the version used to build 2.0 kestrel? We can just drop it into kestrel repo as source project.

**Comment by natemcmaster** [comment]
According to the TeamCity logs from the 2.0.0 rtm build, we used this package: https://dotnet.myget.org/feed/aspnetcore-release/package/nuget/Microsoft.AspNetCore.Internal.CoreFxLab.Sources/2.0.0-rtm-21470

**Comment by natemcmaster** [comment]
Fixed in #2118
