### ISSUE TITLE
Kestrel "ignores" listenOptions.UseHttps on asp.net Core 2.0 on Ubuntu - uses http instead - but works on Windows

### ISSUE THREAD

**Issue by netsfx** [aspnet/KestrelHttpServer#2110]
I want to run Kestrel on Ubuntu with https and do:

```
public static void Main(string[] args)
		{
			var host = new WebHostBuilder()
				.UseKestrel(options =>
				{
					options.ApplicationSchedulingMode = SchedulingMode.Inline;
					options.Listen(IPAddress.Any, 80);
					options.Listen(IPAddress.Any, 443,
				   listenOptions =>
						{
							try
							{
								listenOptions.NoDelay = true;
								listenOptions.UseHttps("cert.pfx", args[0]);
								listenOptions.UseConnectionLogging();
							}
							catch (Exception) { }
						});
					options.UseSystemd();
				})
				
				.UseContentRoot(Directory.GetCurrentDirectory())
				.UseStartup<Startup>()
				.Build();
			host.Run();
		}
```
On Windows, that works as expected:
Now listening on: http://0.0.0.0:80
*Now listening on: https://0.0.0.0:443*

But the same on Ubuntu yields *http* instead of *https* on port 443:
Now listening on: http://0.0.0.0:80
*Now listening on: http://0.0.0.0:443*

The result is that on Ubuntu port 443 will not serve https but http, which is of course not what I want.

Any ideas?

**Comment by halter73** [comment]
Why are you catching and ignoring exceptions from the listen callback?

My guess is that UseHttps cannot find "cert.pfx" and is throwing. This could be caused by case sensitivity on Linux.

**Comment by netsfx** [comment]
@halter73 no, the cert.pfx loads correctly. They try/catch is just for other devs, that don't have a cert. It will listen only on port 80 then. Also, as I wrote above, on Windows it works just fine and the problem is best indicated that on Linux 'http' instead of 'https' is printed, see above!

IMO here is really a bug on Linux!

**Comment by halter73** [comment]
@netsfx How do you know cert.pfx is loading correctly on Linux?

What happens when you try to run [this sample app](https://github.com/aspnet/KestrelHttpServer/tree/dev/samples/SampleApp) on Linux? I get the following output on Ubuntu 16.04:

```
$ dotnet run -f netcoreapp2.0                                                                                                                                                 
Hosting environment: Production
Content root path: /home/shalter/KestrelHttpServer/samples/SampleApp
Now listening on: http://127.0.0.1:5000
Now listening on: https://127.0.0.1:5001
Application started. Press Ctrl+C to shut down.
```

You can see Kestrel is serving HTTPS on port 5001. We regularly test HTTPS on Linux, so I doubt the scenario is completely broken.

If I modify the sample app to load "testcert.pfx" instead of "testCert.pfx" and wrap the UseHttps call in a try/catch, I get exactly the behavior you describe in your issue where HTTPS works on windows but both ports use HTTP on Linux.

**Comment by netsfx** [comment]
@halter73 you were right, passing the the filename can go wrong and passing the password can also go wrong. That was the problem. So I can confirm it's actually working!
