### ISSUE TITLE
How to configure Https in servicefabric with kestrel if no port is specified.

### ISSUE THREAD

**Issue by thengakkola** [aspnet/KestrelHttpServer#2114]
My internal stateful service doesn't expose a port in Service Endpoint. I.e no  Endpoints in ServiceManifest.xml. In this case if I want to configure ListenOptions with https how will I  use this ListenOptions?

 .UseKestrel(options =>
 {
    options.Listen(System.Net.IPAddress.Any, "what here?" , listenOptions =>
     {     
       listenOptions.UseHttps(certificate);
     });
  })

**Comment by halter73** [comment]
Do you wan't to use the default port for HTTPS? If so, just use 443.

**Comment by benaadams** [comment]
@alligator86 if you don't expose a specific port in `ServiceManifest` they you will need to get the port from Service Fabric depending on what it has assigned your microservice 

It will pass the url to use to your CommunicationListener: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore

**Comment by alligator86** [comment]
No my Service fabric instance creator dynamically assign ports to service listners. So I do not want to use the default 443 port.

**Comment by alligator86** [comment]
@benaadams - I will try that option.

**Comment by alligator86** [comment]
@benaadams  - We havent mentioned any service end points in serviceManifest.xml so when it comes to creating the service instance url comes as wildcard urlprefix (https://+:0). So when I bind the Listen using the below code service is always getting created at https://0.0.0.0:<some random port> in SF cluster.
`  .UseKestrel(options =>
                                    {
                                        options.Listen(IPAddress.Any, port , listenOptions =>
                                        {                                            
                                            // Enable https
                                            listenOptions.UseHttps(certificate);
                                        });
                                    })`
 
the port value I just split it from the wildcardurl prefix but it always comes as 0. Am I missing something?

**Comment by benaadams** [comment]
You should probably specify an endpoint; though you don't need to specify any ports :)

As you aren't specifying an endpoint its not assigning you one so you get port 0; which is just any free port. i.e. its doing what you told it to.

However, the issue is as you have no assigned port/endpoint, you also don't have any real registration; so other services won't be able to discover how to communicate with your service

**Comment by alligator86** [comment]
@benaadams - Even if we give the serviceendpoint in servicemanifest `  <Endpoint Name="ServiceEndpointHttps" Type="Internal" Protocol="https" />` and not assigning any ports, the url which you will get to use for the KestrelCommunicationListener is still the wildcard url prefix  (https://+:0).  So my question here is,  if there is a way to set the listen options as it handled by the KestrelCommunicationListener?

**Comment by alexgman** [comment]
I'm wondering if there was any resolution here?

I'm attempting to run a ASP.NET CORE 2 service on my cluster, and it is assigning https://0.0.0.0:3000:
```
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            return new ServiceInstanceListener[]
            {
                new ServiceInstanceListener(serviceContext =>
                    new KestrelCommunicationListener(serviceContext, "ServiceEndpoint", (url, listener) =>
                    {
                        ServiceEventSource.Current.ServiceMessage(serviceContext, $"Starting Kestrel on {url}");

                        return new WebHostBuilder()
                                    .UseKestrel(options=>
                                {
                                    options.Listen(IPAddress.Any, 3000,
                                            listenOptions =>
                                            {
                                                listenOptions.UseHttps(GetCertificateFromStore());
                                            });
                                })
                                    .ConfigureServices(
                                        services => services
                                            .AddSingleton<StatelessServiceContext>(serviceContext))
                                    .UseContentRoot(Directory.GetCurrentDirectory())
                                    .UseStartup<Startup>()
                                    .UseServiceFabricIntegration(listener, ServiceFabricIntegrationOptions.None)
                                    .UseUrls(url)
                                    .Build();
                    }))
            };
        }
```

Here's my servicemanifest:
```

    <Endpoints>
      <!-- This endpoint is used by the communication listener to obtain the port on which to 
           listen. Please note that if your service is partitioned, this port is shared with 
           replicas of different partitions that are placed in your code. -->
      <Endpoint Protocol="https" Name="ServiceEndpoint" Type="Input" Port="3000"/>
    </Endpoints>
```

finally, these were added to my applicationmanifest:

```
    <Policies>
      <EndpointBindingPolicy EndpointRef="ServiceEndpoint" CertificateRef="Certificate" />
    </Policies>
```

and

```
  <Certificates>
    <EndpointCertificate X509StoreName="Root" X509FindValue="[CertificateThumbprint]" Name="Certificate" />
  </Certificates>
```

sf explorer is showing me that the service is ready:

![image](https://user-images.githubusercontent.com/4227695/37988524-bfc911c4-31c6-11e8-854c-7cdda81d3287.png)

when navigating directly to that 0.0.0.0 address in the browser, i get:

![image](https://user-images.githubusercontent.com/4227695/37988595-ec15be26-31c6-11e8-95f1-7a6a5774b15b.png)

when attempting to go to the service through the reverseproxy using postman, i get a 504 timeout. 

**What am I doing wrong? How do we expose https with kestrel in SF?**

**Comment by Tratcher** [comment]
0.0.0.0 means to bind to any/all addresses on the local machine, but it's not an address you're allowed to type into the browser. You need to find out what the real IP is and connect to that.

**Comment by jothipandiyan-bizruntime** [comment]
Instead of IPAddress.Any,

Try this, 
**var ipString = FabricRuntime.GetNodeContext().IPAddressOrFQDN;
IpAddress ip = null;
             if (ipString =="localhost")
                    ip = (Dns.GetHostEntry(Dns.GetHostName()).AddressList.FirstOrDefault(i => i.AddressFamily == AddressFamily.InterNetwork) ?? IPAddress.Loopback);
         else 
                  IpAddress.TryParse(ipString,ip);**
