### ISSUE TITLE
Support port command line argument

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/KestrelHttpServer#2115]
`CreateDefaultBuilder(args).UseConfiguration(configuration)` works fine and allows to supply an url via cli: `dotnet run --urls http://localhost:5000`. 
But it'd nice to support `--port` argument as well: 
`dotnet run --port 5000`
Usually we don't need specify IP but only port. 
It was suggested by many people in https://github.com/aspnet/KestrelHttpServer/issues/639. I saw this suggestion many times in many issues but all of them are closed and it's still not supported.

**Comment by Tratcher** [comment]
This has come up a few times but nobody ever agrees what the default host/IP should be for that port. E.g. is it the same as `http://localhost:5000` or `http://*:5000`?

**Comment by evil-shrike** [comment]
Well, my feeling is it should be "localhost " (meaning that "allow only local connections`). "Secure by default".
If someone wants to allow remote connection to his/her server he'll specify IP/`*` in `urls`. But usually we'll have a reserve proxy which accesses Kestel locally so port will enough.

**Comment by Tratcher** [comment]
The other trouble is that localhost doesn't work well in docker.

**Comment by evil-shrike** [comment]
I'm not an expert here but how will it work in docker with defaults? I mean without `--urls` or explicit `Listen` option?

**Comment by Tratcher** [comment]
I meant that in docker you need `http://*:5000`

**Comment by muratg** [comment]
Yeah if we change this, we'll need to keep docker running.

cc @shirhatti for his thoughts.

**Comment by muratg** [comment]
Tentatively putting this in 2.2.

**Comment by davidfowl** [comment]
This should be moved to Hosting

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#1326
