### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel[0] 

### ISSUE THREAD

**Issue by chtbof** [aspnet/KestrelHttpServer#2117]
run a razor example in linux docker, show some error

warn: Microsoft.AspNetCore.Server.Kestrel[0]                                                                                                                                             
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Error -99 EADDRNOTAVAIL address not available'.                                                           
Hosting environment: Production                                                                                                                                                          
Content root path: /PEGA                                                                                                                                                                 
Now listening on: http://localhost:5000                                                                                                                                                  
Application started. Press Ctrl+C to shut down.

**Comment by tmds** [comment]
> on the IPv6 loopback

Does your server have ipv6 on loopback?

**Comment by tmds** [comment]
Probably you don't want loopback in docker. Set ASPNETCORE_URLS to `http://*:<port>` (replace \<port> with the port your image is exposing).

**Comment by chtbof** [comment]
After add -e ASPNETCORE_URLS http://*:5000, the issue no longer exist.
