### ISSUE TITLE
Flaky test: ConnectionFilterDoesNotLeakBlock

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2127]
This test have been failing a lot lately: http://aspnetci/project.html?tab=testDetails&testNameId=-4993250607788692606&projectId=XPlat&buildTypeId=Lite_KestrelStressTest. The error message given is something like "An existing connection was forcibly closed by the remote host".

**Comment by halter73** [comment]
Fixed by #2133.
