### ISSUE TITLE
Kestrelserver ReasonPhrase formatting

### ISSUE THREAD

**Issue by Tornhoof** [aspnet/KestrelHttpServer#2129]
I know that reason phrase is not in Http/2 anymore and even optional in Http/1.1, but according to RFC spec the current calculation is wrong:
https://github.com/aspnet/KestrelHttpServer/blob/3fbfba63f813de004030615546546360b565b8d5/src/Kestrel.Core/Internal/Http/ReasonPhrases.cs#L223-L227

According to the RFC https://tools.ietf.org/html/rfc7230#section-3.1.2 you need to print the space regardless if the reason phrase is empty.
>  status-line = HTTP-version SP status-code SP reason-phrase CRLF

I know this is nit-picking, but I actually stumbled across while writing my http batch handler middleware.

**Comment by muratg** [comment]
@Tornhoof thanks for the bug!  Interested in sending a PR?

**Comment by Tornhoof** [comment]
I opened a pull request with a fix.
The fix is straight forward, the only question is where do you want the tests for it. I couldn't find any file with existing tests for the reasonphrase, nor any file with utility tests.

**Comment by muratg** [comment]
Thanks @Tornhoof!  @Tratcher could you take a look when you get the chance?
