### ISSUE TITLE
Handling BadHttpRequestException

### ISSUE THREAD

**Issue by shravan2x** [aspnet/KestrelHttpServer#2131]
I have an MVC action to upload files. For this, I use `await HttpContext.Request.Body.ReadAsync(buffer, 0, buffer.Length)` in a loop and then return an `Ok()` at the end.

This works fine, except when a client closes the connection before the upload is complete. When this happens, the `ReadAsync` method throws a `BadHttpRequestException`. In my action, I would like to handle this exception, mark the upload as failed in the database and then just return. However, I'm not sure what the right type to return would be. Returning null throws another `InvalidOperationException` with the message "Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'".

How could I return from an action while indicating to MVC to just not respond at all?

**EDIT**: Returning an `Ok()` seems to not throw an exception, but is this the right behavior?

**Comment by Tratcher** [comment]
That's fine. If the client has disconnected then it doesn't really matter what you return.

**Comment by Tratcher** [comment]
You could also rethrow the exception.

**Comment by shravan2x** [comment]
> You could also rethrow the exception.

This shows up as an ugly start trace in the log, which I want to avoid.

I think I'm going to just do `return StatusCode(-1);` for lack of a better solution.

Thanks!

**Comment by benaadams** [comment]
`return new BadRequestResult()`

**Comment by shravan2x** [comment]
> return new BadRequestResult();

The problem with `BadRequestResult` is that it is backed by a valid HTTP status code (400).

**Comment by benaadams** [comment]
If you want an non-official status code how about 

`return StatusCode(499);`

"499 Client Closed Request" its what [ngnix uses](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#nginx) to signal "Used when the client has closed the request before the server could send a response."
