### ISSUE TITLE
bad pfx file from sample ?

### ISSUE THREAD

**Issue by dabretin** [aspnet/KestrelHttpServer#2134]
Hello !
The file `testCert.pfx` from the `sampleApp` seems to have problem:
When I try a simple
`var x509 = new X509Certificate2("/testCert.pfx", "testPassword");
`

It returns:
`Unhandled Exception: Interop+Crypto+OpenSslCryptographicException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
`

I'm on linux 'mint 18.2'...

**Comment by muratg** [comment]
What's your SDK version?  Also, what's the system OpenSSL?

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
