### ISSUE TITLE
Fail to start Kestrel server when using a service. but it runs manually

### ISSUE THREAD

**Issue by avifatal** [aspnet/KestrelHttpServer#2144]
Hi.
Core 2.0
MVC Latest.

When I run in my ubuntu the following server:
```
    [Unit]
    Description=Feeder App

    [Service]
    WorkingDirectory=/var/www/feeder
    ExecStart=/usr/bin/dotnet /var/www/feeder/FeedService.MVC.dll
    SyslogIdentifier=feeder
    User=avi
    Environment=ASPNETCORE_ENVIRONMENT=Production

    [Install]
    WantedBy=multi-user.target
```
I get an error: 

```
kestrel-feeder.service - Feeder App
   Loaded: loaded (/etc/systemd/system/kestrel-feeder.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Wed 2017-11-01 11:28:09 IST; 88ms ago
  Process: 22649 ExecStart=/usr/bin/dotnet /var/www/feeder/FeedService.MVC.dll (code=dumped, signal=ABRT)
 Main PID: 22649 (code=dumped, signal=ABRT)
      CPU: 2.337s

Nov 01 11:28:08 spread feeder[22649]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 01 11:28:08 spread feeder[22649]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
Nov 01 11:28:08 spread feeder[22649]: --- End of stack trace from previous location where exception was thrown ---
Nov 01 11:28:08 spread feeder[22649]:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Nov 01 11:28:08 spread feeder[22649]:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Nov 01 11:28:08 spread feeder[22649]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
Nov 01 11:28:08 spread feeder[22649]:    at FeedService.MVC.Program.Main(String[] args) in C:\Users\avif\Desktop\FeedConnector\FeedService.MVC\Program.cs:line 30
Nov 01 11:28:09 spread systemd[1]: kestrel-feeder.service: Main process exited, code=dumped, status=6/ABRT
Nov 01 11:28:09 spread systemd[1]: kestrel-feeder.service: Unit entered failed state.
Nov 01 11:28:09 spread systemd[1]: kestrel-feeder.service: Failed with result 'core-dump'.
```

But if I run the command manually, the server is starting fine:
```  sudo /usr/bin/dotnet /var/www/feeder/FeedService.MVC.dll```

What can be wrong? the syslog does not have more information.

```

Thanks

**Comment by avifatal** [comment]
So I found the prob problem.
For some reason kestrel  can't bind to port 80. in netstat I see that port 80 is available and not takin.

1. How can I see the error details, as you can see above, the details are not general and there is no real exceltion.  
2. Why can't I bind port 80 in my ubuntu machine?

Thanks

**Comment by halter73** [comment]
> 1. How can I see the error details, as you can see above, the details are not general and there is no real exceltion.

I don't know why systemd isn't capturing the full exception message. The process should crash with the exception like the following:

```
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -13 EACCES permission denied
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.ThrowError(Int32 statusCode)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.tcp_bind(UvTcpHandle handle, SockAddr& addr, Int32 flags)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvTcpHandle.Bind(IPEndPoint endPoint)
...
```

Do you see this exception when you manually launch the process and bind to port 80?

> 2. Why can't I bind port 80 in my ubuntu machine?

Non-root users cannot bind to port numbers below 1024 without special setup. https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Comment by avifatal** [comment]
@halter73  thanks.
1. its odd. most of the errors I have experianced the first time running core on ubuntu was solved by guessing. 
2. I am able to bing port 80 on manual run, but not as a service.

Thanks

**Comment by halter73** [comment]
> 2. I am able to bing port 80 on manual run, but not as a service.

This is probably because you are using sudo.

**Comment by avifatal** [comment]
@halter73
Yes, I'm using sudo with this manual command.
But the user who is configured in the service is with root access. 
Thanks...
Any solution before I switch to iis? I need the service to bind Port 80
Tx

**Comment by benaadams** [comment]
Ports below 1024 are privileged ports

You can use an `iptables` route; use `CAP_NET_BIND_SERVICE`; or `authbind` 

https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443 

https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux
