### ISSUE TITLE
Mac: The specified SDK version [2.1.0-preview1-007042] from global.json [...] not found

### ISSUE THREAD

**Issue by suryagh** [aspnet/KestrelHttpServer#2146]
On my Mac, I had an older version .net sdk and KestrelHttpServer cloned and compiled few months back.

Scenario, 
1. Today, installed latest .net sdk from (https://www.microsoft.com/net/learn/get-started/macos)
 1.b) Is this the right approach? Should I be upgrading the `.net sdk`? Or, first uninstall the older `.net sdk`?
2. Pulled the latest code from the `KestrelHttpServer` github repo
3. Ran `./build.sh` on the latest `/KestrelHttpServer` with not errors
4. Now, when I run `dotnet run` from the `KestrelHttpServer/samples/SampleApp`, I get following error:

```
The specified SDK version [2.1.0-preview1-007042] from global.json [/Users/.../KestrelHttpServer/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by halter73** [comment]
What if you run `~/.dotnet/dotnet run -f netcoreapp2.0`?

Instead of using the globally installed .net sdk, Kestrel and the other aspnet projects download prerelease sdks into the `~/.dotnet` directory and use that.

**Comment by suryagh** [comment]
That worked. Few clarifications:
1. is the `-f` alias for `--fx-version`?
2. Where did you find the string value need to be exact `netcoreapp2.0`?

Thanks!

**Comment by halter73** [comment]
> 1. is the `-f` alias for `--fx-version`?

Close. It's an alias for `--framework` which you can see in the output of `dotnet run -h`.

```
$ dotnet run -h
Usage: dotnet run [options] [[--] <additional arguments>...]]

Options:
  -h, --help                            Show help information.
  -c, --configuration <CONFIGURATION>   Configuration to use for building the project.  Default for most projects is  "Debug".
  -f, --framework <FRAMEWORK>           Target framework to publish for. The target framework has to be specified in the project file.
  -p, --project                         The path to the project file to run (defaults to the current directory if there is only one project).
  --launch-profile                      The name of the launch profile (if any) to use when launching the application.
  --no-launch-profile                   Do not attempt to use launchSettings.json to configure the application.
  --no-build                            Skip building the project prior to running. By default, the project will be built.
  --no-restore                          Does not do an implicit restore when executing the command.
  --runtime <RUNTIME_IDENTIFIER>        Target runtime to restore packages for.
  --no-dependencies                     Set this flag to ignore project to project references and only restore the root project.
  --force                               Set this flag to force all dependencies to be resolved even if the last restore was successful. This is equivalent to deleting project.assets.json.
Additional Arguments::
  Arguments passed to the application that is being run.
```

> 2. Where did you find the string value need to be exact `netcoreapp2.0`?

From [here](https://github.com/aspnet/KestrelHttpServer/blob/6c82f78c657145404bcdbe403024b2d93ca7699a/samples/SampleApp/SampleApp.csproj#L4). Kestrel's sample app is a little unusual in that it targets both `netcoreapp2.0` and `net461`. If there's only one target framework, `dotnet run` will automatically select it without the need for `-f`.

**Comment by suryagh** [comment]
Thank you, @halter73 !
