### ISSUE TITLE
502.3 An operation was attempted on a nonexistent network connection

### ISSUE THREAD

**Issue by cinaradem** [aspnet/KestrelHttpServer#2148]
hi,
my application on azure web app is working.
asp.net core 2.0 version.
but I often encounter the 502.3 error that I do not know why. When I examine the freb logs, "An operation was attempted on a nonexistent network connection.
  (0x800704cd) "and" There was a connection error while trying to route the request.
"but I have no idea about these faults.
I have checked the previous 502.3 errors and wrote a problem with asp.net core 1.1, but the problem still continues.
The site is a high hit area.
I would appreciate your help.

[freblog.txt](https://github.com/aspnet/KestrelHttpServer/files/1447948/freblog.txt)

**Comment by halter73** [comment]
This issue was moved to aspnet/AspNetCoreModule#235
