### ISSUE TITLE
[2.0.x] PipeCompletionCallbacks root the state object even after callback executes

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2160]
Backport dotnet/corefxlab#1932 to fix dotnet/corefxlab#1722.

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.
