### ISSUE TITLE
No way to configure the endpoint options when using PreferServerUrls

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2167]
I wanted to turn on `listenOptions.UseConnectionLogging();` behind ANCM but there's no way to do this, PreferServerUrls overrides all Kestrel ListenOptions.

**Comment by halter73** [comment]
Hmm. This brings me back to the idea of having something like `KestrelServerOptions.ConfigureAllEndpoints(Action<ListenOptions>)`.

I don't love it, but it's my best idea so far other than just not supporting connection middleware for "ServerUrls".

**Comment by Tratcher** [comment]
Ordering will be an interesting problem for shared middleware no matter what.

Many of the other options will be simpler, we can use that callback (first, so you can override it) or KSO can have properties for defaults like DefaultProtocols.
