### ISSUE TITLE
ASP .NET Core 2.0 Kestrel Support for Kerberos

### ISSUE THREAD

**Issue by rezvanf** [aspnet/KestrelHttpServer#2168]
Is it possible to support Kerberos with just bare bones Kestrel?

Thanks

**Comment by Tratcher** [comment]
No.

**Comment by rezvanf** [comment]
Ok Thanks is there a reason for that? is there plans for it to be supported in the future?

**Comment by Tratcher** [comment]
@blowdart

**Comment by blowdart** [comment]
For Integrated Auth we've always let the OS do the work, and we can do that because it's Windows only. Implementing flows like this in managed code, in a system which doesn't autoupdate is a huge risk I'm unwilling to approve.

**Comment by rezvanf** [comment]
Understood. Many Thanks

**Comment by blowdart** [comment]
You're welcome.
