### ISSUE TITLE
What's the recommended way to tell a Docker App which url to listen on?

### ISSUE THREAD

**Issue by mythz** [aspnet/KestrelHttpServer#2174]
I've tried setting both `ASPNETCORE_URLS` and `--server.urls` command line argument when trying to run a  [.NET Core 2.0 App](https://github.com/NetCoreApps/Chat/tree/master/src/Chat) in Docker:

```
FROM microsoft/dotnet:2.0-sdk
COPY src/Chat /app
WORKDIR /app
RUN ["dotnet", "restore", "--configfile", "NuGet.Config"]
RUN ["dotnet", "build"]
EXPOSE 5000/tcp
ENV ASPNETCORE_URLS https://*:5000
ENTRYPOINT ["dotnet", "run", "--server.urls", "http://*:5000"]
```

Which after upgrading to .NET Core 2.0 and using the recommended bootstrapping code:

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .Build();
}
```

Is now throwing a `InvalidOperationException: HTTPS endpoints can only be configured using KestrelServerOptions.Listen()` Exception on Startup.

The only way I can get it to work is to hard code the url:

```csharp
    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseUrls("http://*:5000")
            .UseStartup<Startup>()
            .Build();
```

Is there another solution I can use to tell Kestrel which URL it should listen on without hard coding it?

**Comment by davidfowl** [comment]
`ASPNETCORE_URLS` is the recommended way. It's what the ASP.NET Core docker image does (https://github.com/aspnet/aspnet-docker)

> Is now throwing a InvalidOperationException: HTTPS endpoints can only be configured using KestrelServerOptions.Listen() Exception on Startup.

Are you trying to configure an HTTPS end point?

**Comment by mythz** [comment]
[No reference to https at all](https://github.com/NetCoreApps/Chat/tree/master/src/Chat), not sure why I started getting this Exception after upgrading to .NET Core 2.0 (I'm running the [Docker container in an AWS AMI managed by AWS ECS](http://docs.servicestack.net/deploy-netcore-docker-aws-ecs)).

**Comment by davidfowl** [comment]
> No reference to https at all, not sure why I started getting this Exception after upgrading to .NET Core 2.0 (I'm running the Docker container in an AWS AMI managed by AWS ECS).

Your docker file *does* have a reference to https on line 7:

```dockerfile
FROM microsoft/dotnet:2.0-sdk
COPY src/Chat /app
WORKDIR /app
RUN ["dotnet", "restore", "--configfile", "NuGet.Config"]
RUN ["dotnet", "build"]
EXPOSE 5000/tcp
ENV ASPNETCORE_URLS https://*:5000
ENTRYPOINT ["dotnet", "run", "--server.urls", "http://*:5000"]
```

Change that to http and it'll work. I recommend using the ASP.NET Core image because it has the ASP.NET Runtime store (which doesn't come with the base .NET Core container).

Side question: Also, why aren't you using multistage builds 😄 ?

**Comment by mythz** [comment]
> Your docker file does have a reference to https on line 7:

OMG, can't believe I didn't see that - think I need to stop coding all nighters!

> I recommend using the ASP.NET Core image

Which image is that?

> Side question: Also, why aren't you using multistage builds

Haven't felt the need, we're using Docker for some small .NET Core Demos and rsync + supervisor + nginx for our own Web Apps.

**Comment by azizj1** [comment]
> `ASPNETCORE_URLS` is the recommended way. It's what the ASP.NET Core docker image does (https://github.com/aspnet/aspnet-docker)
> 
> > Is now throwing a InvalidOperationException: HTTPS endpoints can only be configured using KestrelServerOptions.Listen() Exception on Startup.
> 
> Are you trying to configure an HTTPS end point?

If you were trying to configure a HTTPS endpoint, how would you do it? My cert is managed in AWS through AWS cert manager, and that's for the Application Load Balancer (ALB), but I can't get traffic to route from HTTPS internet to my docker as HTTP. Thoughts?

**Comment by davidfowl** [comment]
cc @javiercn

**Comment by javiercn** [comment]
You have HTTPS termination at the load balancer, so long as the headers are forwarded you don’t need to configure https in the docket image.

The internal traffic between the load balancer and the container will be http, but that’s ok.

I’m not sure what you mean, is traffic not getting to the app at all (then it’s probably something missconfigured between the load balancer and the app) if the app is receiving traffic but it shows up as HTTPS that’s normal as the headers are being forwarded.

If you provide more details we might be able to help you better. I would suggest as a first step to turn on logging on the app to see what’s going on.

**Comment by azizj1** [comment]
Thanks for the tips @javiercn. I got it to work with your tips. Did ALB:443 -> targetGroup:3000 -> dockerContainer: 3000. I was using AWS Fargate, so there's no host port and that was then the only way.
