### ISSUE TITLE
Enable ApiCheck for Socket Transport

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2175]
https://github.com/aspnet/KestrelHttpServer/pull/2173/files#r151965500

**Comment by JunTaoLuo** [comment]
Looks like we have ApiCheck enabled for all of the Kestrel packages. However, it looks like the base lines are out of date since they were last updated to 2.0. We should set the baselines at 2.1 and then see whether anything changed for 2.2
