### ISSUE TITLE
Every connection makes a Http1 and Http2 connection and does a lot of allocating

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/KestrelHttpServer#2178]
The http2 connection allocates at least 40k in byte arrays in the constructors.

Below are the ones I found from a quick search
```
Http2Connection
  - Http2Frame
    - 16k byte[]
  - Http2Framewriter
    - Http2Frame
      - 16k byte[]
  - HPackDecoder
    - 4k byte[]
    - 4k byte[]
    - 4k byte[]
```

@davidfowl @halter73

**Comment by davidfowl** [comment]
@BrennanConroy did you do another pass to verify it works well?

**Comment by BrennanConroy** [comment]
No, I'll try it out

**Comment by BrennanConroy** [comment]
Tried it out, way better now

**Comment by davidfowl** [comment]
@BrennanConroy can you update the SignalR issue with the latest details on the per connection memory
