### ISSUE TITLE
Determine what data type ITlsApplicationProtocolFeature.ApplicationProtocol should have

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2181]
Today it's a string, we could:

1. Make a new type that mirrors SslApplicatonProtocols
2. Make it a Span\<byte\>
2. Leave it alone.

https://github.com/aspnet/KestrelHttpServer/pull/2179#discussion_r153252609

**Comment by anurse** [comment]
You just beat me. #2182

**Comment by davidfowl** [comment]
Yours looks better

**Comment by anurse** [comment]
As I mention in #2182. It could probably be fine as a `byte[]` or `Span<byte>`. I say just do (2) above (make it Span) and be done with it quick :). Wrapping it up in a type isn't that exciting to me, but sure, it would make equality comparison clearer. For (3), I agree it's probably not super necessary to make this change, but it's a simple change that keeps us adhering to the spec, and SslStream saw fit to use something other than a `string`, so I don't see why we should limit this further.

**Comment by anurse** [comment]
Lol, let's just play tag through GitHub issues. You're it.
