### ISSUE TITLE
Change ITlsApplicationProtocolFeature.ApplicationProtocol to Span<byte>

### ISSUE THREAD

**Issue by anurse** [aspnet/KestrelHttpServer#2182]
https://github.com/aspnet/KestrelHttpServer/blob/76de77746dd900058f7bd49f66debdd245cf9260/src/Kestrel.Core/Features/ITlsApplicationProtocolFeature.cs#L7-L10

This property should not be represented as a string because the ALPN spec intentionally defines it as an "opaque byte string" and not a textual string:

> Protocols are named by IANA-registered, opaque, non-empty byte strings, as described further in Section 6 ("IANA Considerations") of this document.
>
> https://tools.ietf.org/html/rfc7301#section-3.1

The fact that the currently-registered values are all valid UTF-8 strings is not required by the spec so we shouldn't require it in our type.

We could use `byte[]`, which is relatively safe performance-wise since in fast paths this will almost always be set to an existing constant value. Or we could go with the new hotness and make it return `ReadOnlyMemory<byte>`. Probably the latter is best even if we always just end up backing it with a predefined constant array.

/cc @benaadams @Tratcher @davidfowl

**Comment by anurse** [comment]
Dupe of #2181

**Comment by anurse** [comment]
Also of note: `SslStream` chose not to use a `string` here, so I don't think we should arbitrarily limit it more than that. They used a custom type wrapping a byte array. We could go that far if we wanted to, it would make equality checks clearer, but I don't really mind either way.

**Comment by benaadams** [comment]
Its a getter only, you want to stash it on heap; single instance them - should be `ReadOnlyMemory<byte>` rather than Span

Also `SslApplicatonProtocol` is an option, except doesn't work for non-Ssl ApplicatonProtocols... (in name)

**Comment by davidfowl** [comment]
SslApplicatonProtocol isn't an option because it's .NET Core 2.0 only.

**Comment by benaadams** [comment]
> SslApplicatonProtocol isn't an option because it's .NET Core 2.0 only.

There's an obvious question here; but I'm not going to ask it 😄

**Comment by benaadams** [comment]
Ah gowan... 

So Apln will be Core 2.x and not Framework, until Framework's SslStream catches up - or an Apln shim for Framework?

Guessing as its security/crypto; will need Framework's SslStream to catch up (i.e. a future version of Framework rather than 4.7.1)

**Comment by anurse** [comment]
Correct, ALPN is a .NET Core 2.x only feature.

> Its a getter only, you want to stash it on heap; single instance them - should be ReadOnlyMemory<byte> rather than Span

Sure, easy fix.

**Comment by Drawaes** [comment]
Ahh the string vs opaque bytes debate, it's like waking up from a bad dream over and over.... Don't please don't make it a string.

**Comment by halter73** [comment]
@Tratcher I [reverted](https://github.com/aspnet/KestrelHttpServer/commit/664055fa4396b72e6914bb1b0f9b98c0030e83ea) the PR due to the following build error:

```
KestrelHttpServer/src/Kestrel.Core/Internal/HttpConnection.cs(325,69): error CS1061: 'ReadOnlyMemory<byte>' does not contain a definition for 'SequenceEqual' and no extension method 'SequenceEqual' accepting a first argument of type 'ReadOnlyMemory<byte>' could be found (are you missing a using directive or an assembly reference?) [/Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj]
KestrelHttpServer/src/Kestrel.Core/Internal/HttpConnection.cs(336,56): error CS1061: 'ReadOnlyMemory<byte>' does not contain a definition for 'SequenceEqual' and no extension method 'SequenceEqual' accepting a first argument of type 'ReadOnlyMemory<byte>' could be found (are you missing a using directive or an assembly reference?) [/Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj]
KestrelHttpServer/src/Kestrel.Core/Internal/HttpConnection.cs(325,69): error CS1061: 'ReadOnlyMemory<byte>' does not contain a definition for 'SequenceEqual' and no extension method 'SequenceEqual' accepting a first argument of type 'ReadOnlyMemory<byte>' could be found (are you missing a using directive or an assembly reference?) [/Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj]
KestrelHttpServer/src/Kestrel.Core/Internal/HttpConnection.cs(336,56): error CS1061: 'ReadOnlyMemory<byte>' does not contain a definition for 'SequenceEqual' and no extension method 'SequenceEqual' accepting a first argument of type 'ReadOnlyMemory<byte>' could be found (are you missing a using directive or an assembly reference?) [/Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/Kestrel.Core.csproj]
```

**Comment by Tratcher** [comment]
Bad rebase.... I'll re-do it tomorrow.

**Comment by Tratcher** [comment]
Fixed.
