### ISSUE TITLE
[2.0.x] BadHttpRequestException at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2187]
Back port https://github.com/dotnet/corefxlab/commit/60dbe3ebda05329239c4df6bcedeebe3ef931ccd from corefxlab to 2.0.5

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by Eilon** [comment]
@muratg - can you assign to someone to port?

**Comment by muratg** [comment]
@halter73 please do the needful. Thanks!

**Comment by halter73** [comment]
@muratg This patch was already backported to the release/2.0.0 by @davidfowl [here](https://github.com/aspnet/KestrelHttpServer/commit/35a9432ce8e1bdd003309785e6ab1fa857c6eecc). I don't think this is a good candidate for a quirks-mode switch considering it's data corruption bug. So what is the needful?

**Comment by muratg** [comment]
@halter73 Cool, porting was it :)

**Comment by Eilon** [comment]
@LiangZugeng this will be Microsoft.AspNetCore.All 2.0.6, which we will release next month.

**Comment by halter73** [comment]
@LiangZugeng You can try out the packages on the https://dotnet.myget.org/gallery/aspnet-2018-feb-patch-public feed which contain the fix for this. It won't be supported until it's published to NuGet.org though.
