### ISSUE TITLE
Listen on https://localhost:5001 by default when a default HTTPS certificate is available

### ISSUE THREAD

**Issue by danroth27** [aspnet/KestrelHttpServer#2188]
Absent any configuration, by default Kestrel listens on http://localhost:5000. Kestrel by default should also listen on https://localhost:5001 *if* a default HTTPS certificate is available (i.e. on a dev machine with the .NET Core SDK and the ASP.NET Core HTTPS development certificate installed).

**Comment by Tratcher** [comment]
IDefaultHttpsProvider will need an IsAvailable property or TryConfigure method. Today's ConfigureHttps throws if the cert is missing.
