### ISSUE TITLE
Backport exception dispatch fix from pipelines

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#2196]

**Comment by muratg** [comment]
@pakrym good to close?

**Comment by pakrym** [comment]
I'm not sure we did backport it.

**Comment by halter73** [comment]
@pakrym Can you link to the corefxlab PR that fixed this?

**Comment by pakrym** [comment]
https://github.com/dotnet/corefxlab/pull/1814

**Comment by muratg** [comment]
Do we need to add test? What other work is remaining on this?

**Comment by halter73** [comment]
I remember this. It just cleans up the stack traces of some exceptions in a way that can make it easier to find the original location the exception was thrown from.

I don't think it's critical to backport to 1.x or 2.0x, but it seemed like an easy patch.

**Comment by davidfowl** [comment]
Are we doing this or not? If not, then lets close the bug but I think we should because we're going to be getting tons of customer reports that we can't decipher on 2.0

**Comment by muratg** [comment]
@Eilon This is a candidate for the "next" patch release.

**Comment by shirhatti** [comment]
@Eilon Is this rejected for 2.0.7?

**Comment by Eilon** [comment]
"Tentatively approved" depending on whether we take the other Kestrel change we discussed.

**Comment by muratg** [comment]
We decided not to take this one.
