### ISSUE TITLE
Flaky test: TestInvalidHeaders

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2211]
Based on [this](http://aspnetci/viewLog.html?buildId=363484&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest) test it looks like in some cases our tests are getting blank responses back.

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/2635
