### ISSUE TITLE
No UWP support on IoT Core

### ISSUE THREAD

**Issue by JeffMarqMetrix** [aspnet/KestrelHttpServer#2218]
Trying to build a Windows IoT Core Background Application that has an AspNetCore web server using MVC. None of the  publicly available servers work for this, but I kind of expected kestrel to, since it is the "cross-platform" option.

One option is to run AspNetCore apps as a standalone Exe on IoT Core. But this removes the ability to communicate to any low level devices like serial ports.

Another option is to create a custom server that implements HttpListener. But that's a lot of work and I'm not sure which downstream Asp.Net features may suffer.

**Comment by davidfowl** [comment]
We don't test any of ASP.NET on UWP. There's been a long standing request for ASP.NET on UWP for IoT scenarios but it's never been high enough priority to investigate. I'd follow up on these issues:

- https://github.com/aspnet/Home/issues/1531
- https://github.com/aspnet/Home/issues/1338
- https://github.com/aspnet/Home/issues/2116
