### ISSUE TITLE
dotnet.exe restart

### ISSUE THREAD

**Issue by ili** [aspnet/KestrelHttpServer#2227]
Hello,

I've faced with strange situation - `dotnet.exe` hosted on IIS (Windows Server 2012 R2) is periodically shut down. 

While testing our application on high load we do see strange situations - periodically we do have long answer time from server (eg normal answer time is 300ms and long one is 15000 - 20000 ms).

While investigating this we've found out that at this times dotnet.exe is restarted (one process is stopped and another is started), no errors, no logs, nothing is saying about the reason.

Switching stdout logs on does not help much, while test we do see that new files like `stdout_9648_20171219125646.txt` are created, with mostly the same content:

```
Hosting environment: Production
Content root path: C:\inetpub\wwwroot
Now listening on: http://localhost:3214             --this line changes for each start
Application started. Press Ctrl+C to shut down. 
Application is shutting down...                     --this line appears on process stopped
```

Looking the documentation & IIS settings I can't find why process is stopped and why it can be stopped.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/AspNetCoreModule#278
