### ISSUE TITLE
Build.cmd fails due to new BenchmarkDotNet RELEASE error

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2232]
build.cmd now fails by default on dev machines because BenchmarkDotNet started issuing a fatal error if the project is not compiled as RELEASE.

workaround: `build /p:configuration=Release`

Proposals:
- Disable BenchmarkDotNet for DEBUG?
- Suppress the error?

**Comment by pakrym** [comment]
Fixed by https://github.com/aspnet/KestrelHttpServer/pull/2233
