### ISSUE TITLE
Set-Cookie shouldn't return secure cookies on http request

### ISSUE THREAD

**Issue by jchannon** [aspnet/KestrelHttpServer#2240]
When using ASP.Net Cookie auth and the `CookieSecure` property is set to `CookieSecurePolicy.Always` and a request is made via http to login the `Set-Cookie` header is returned with a `secure` suffix.  I don't think it should do this if the request is made via `http`, it should only return that header if made via `https`

There is nothing stopping a client taking and using the cookie value to issue a request which leads to the question for maybe https://github.com/aspnet/Security as to whether that should be allowed.

At the moment the onus is on the developer to not allow requests that are made over http when you have `CookieSecurePolicy.Always` set. I would expect the server and/or fwk to step in here.

cc @PinpointTownes

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Security#1584
