### ISSUE TITLE
UseHttps with dotnet run --project fails

### ISSUE THREAD

**Issue by zygimantas** [aspnet/KestrelHttpServer#2242]
**Actual results:**

```
Application startup exception:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException:
The system cannot find the path specified
```

**Reproduction steps**

Pass certificate file path to UseHttps method as string (tested with ../ prefix only):
```
../Certificate.pfx 
```

Launch project like this:

```
cd Content
dotnet run --project ../Website.csproj
```

Project file structure:
```
- Project
      Certificate.pfx
      Website
          Content
          Website.csproj
```

**Expected results**

The same as without --project, application should start and certificate should be loaded.

**Dotnet Info**

.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by Tratcher** [comment]
Several components use the current directory to resolve relative paths. Doing dotnet run in a directory other than the project directory confuses this. Does it work better if you do dotnet run in the same directory as your csproj?

**Comment by zygimantas** [comment]
Yes, in the same directory, ```dotnet run --project Website.csproj``` works as expected.
I have found [this discussion](https://github.com/dotnet/cli/issues/4473#issuecomment-256213294), but I still don't see a solution.

**Comment by zygimantas** [comment]
The problem I am solving is to have a cross-platform way to do
```cd .. & dotnet run```

Looks like the ```dotnet run --project ../Website.csproj``` is not suited for this task.

**Comment by Tratcher** [comment]
If you can figure out the correct project directory in Program.Main then you can set UseContentRoot so it knows where to find assets like the certificate.
