### ISSUE TITLE
Add ParseRequestLineSplitBufferWithoutNewLineDoesNotUpdateConsumed test back

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#2243]
Was removed as part of https://github.com/aspnet/KestrelHttpServer/pull/2234

**Comment by davidfowl** [comment]
https://github.com/aspnet/KestrelHttpServer/pull/2234/files#diff-babc5b9d34240d24428368005d81fe1aL373

**Comment by mikeharder** [comment]
@pakrym: I can take this one unless you already started.
