### ISSUE TITLE
Kestrel crash when ConnectionResetException is thrown

### ISSUE THREAD

**Issue by akramayasrah** [aspnet/KestrelHttpServer#2248]
Hi,
Recently i upgraded my asp.core app from v. 1.0 to v. 2.0, but after the migration i keep seeing ConnectionResetException in the logs, and once this exception is thrown the whole asp.net core app crash! it seems that this exception is not caught internally or something like this.

Please note that i was not seeing this exception in v. 1.0, and am using iis as a reverse proxy.

Below is the exception log details, can anyone help me in this?

Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ConnectionResetException: Error -4077 ECONNRESET connection reset by peer ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4077 ECONNRESET connection reset by peer --->
at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.d__21.MoveNext()

**Comment by halter73** [comment]
Since this is crashing the process, do you see any "Unhandled Exception: ..." at the end of the process's output?

**Comment by akramayasrah** [comment]
After deep investigation in this, i found that there was no unhandled exceptions but what happened is that the iis was killing asp.net core app for a reason that i dont know why yet. however, when i upgraded  asp.net core runtime from version 2.0.4 to 2.0.5, this problem disappeared and no more crashes, but i still see many and many ConnectionResetExceptions, ans this exception is thrown when i try to read http request body as below sample code:

 string jsonObject = null;
 using (StreamReader reader = new StreamReader(context.Request.Body))
{
        jsonObject = await reader.ReadToEndAsync();
}

My question now is: why kestrel 2.0 is throwing this exception while 1.0 was not throwing it?

**Comment by halter73** [comment]
Kestrel introduced a new default minimum request body data rate of 240 bytes/second. There's info about this on https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#how-to-use-kestrel-in-aspnet-core-apps.

If this is the cause, and you are collecting Information-level logs, you should see traces like `"Connection id ""{ConnectionId}"", Request id ""{TraceIdentifier}"": the request timed out because it was not sent by the client at a minimum of {Rate} bytes/second."`.

**Comment by akramayasrah** [comment]
I was thinking that those settings are useful when kestrel is used as a stand alone web server, but in my case I use IIS as a reverse proxy. However, I tried to set those new settings (MinRequestBodyDataRate & MinResponseDataRate) to null so no minimum data rate will be enforced, but i still see a lot of ConnectionResetExceptions. Is there any other setting that i should look at? and how to adapt the same settings in kestrel 1.0?

**Comment by halter73** [comment]
A ConnectionResetException like the one shown in the original issues is caused by the client disconnecting mid-request. You could capture network logs to verify that the client is sending the server RST packets.
