### ISSUE TITLE
BadHttpRequestionException: Request timed out on OSEv3

### ISSUE THREAD

**Issue by rezvanf** [aspnet/KestrelHttpServer#2249]
Hi,

I am running ASP .NET Core 2.0 on OSEv3. My ASP .NET Web API is a simple controller that is responsible for uploading dat files in the region of ~300MB. After the initial request all subsequent requests fail with the following error 

`  Connection id "0HLANMLGCKEGN", Request id "0HLANMLGCKEGN:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request timed out.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()`

My controller code is taken from the Microsoft mvc asp .net core examples  for the streaming controller [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads)

My kestrel setup is as 

`  WebHost.CreateDefaultBuilder(args)
                .UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = null;
                    options.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(30);
                    options.Limits.RequestHeadersTimeout = TimeSpan.FromMinutes(30); ;
                })`

My client post call uses  httpclient as such

`            using (var content = new MultipartFormDataContent())
            {

                var bytes = File.ReadAllBytes(@"c:\FILEA.dat");
                content.Add(new StreamContent(new MemoryStream(bytes))
                {
                    Headers =
                    {
                        ContentLength = bytes.Length,
                        ContentType = new MediaTypeHeaderValue("application/octet-stream"),

                    }
                }, "FILEA.dat", "FILEA.dat");
       
                content.Add(new StringContent("XXX"), "XXX");
                using (var message = await Client.PostAsync(_BASE_URL, content))
                {
                    result = message.Content.ReadAsStringAsync();
                }

            }

The code has no problems when running on kestrel directly on windows.

Through debugging i have the issue seems to happen at this part in the controller that is provided in the Microsoft example

` await section.Body.CopyToAsync(targetStream);`

Also just to add the container/pod this runs is setup with https 1.1.  Further more the ENVIRNOMEN variables for ASPNETCORE_URLS is set  to http://*:5000

I am a bit confused why subsequent requests are failing over. I assume somewhere some resource is not shutting down properly.

The other thing i noticed for the 1st successful post in Fiddler i see the clienttoserverbytes value at around 270MB, on the next failing posts the clienttoserverbytes is around 1/2 a MB. That is also very weird.

Any help/assistance welcome.

`

**Comment by halter73** [comment]
@rezvanf Can yan try [our public nightly feed for the upcoming ASP.NET patch](https://dotnet.myget.org/gallery/aspnet-2018-feb-patch-public)? It includes a fix for #2151 which might be related.

These packages are not yet final or supported, so use them at your own risk.

**Comment by muratg** [comment]
We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
