### ISSUE TITLE
TLS restrictions for HTTP/2

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2251]
https://tools.ietf.org/html/rfc7540#section-9.2.1

**Comment by Tratcher** [comment]
Also review the other TLS requirements to make sure they're in place.

**Comment by Tratcher** [comment]
- MUST disable compression
- MUST disable renegotiation
- MUST support ephemeral key exchange sizes of at least
   2048 bits for cipher suites that use ephemeral finite field Diffie-
   Hellman (DHE) [TLS12] and 224 bits for cipher suites that use
   ephemeral elliptic curve Diffie-Hellman (ECDHE) [RFC4492]
- SHOULD NOT use any of the cipher
   suites that are listed in the cipher suite black list
- MUST support TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 [TLS-ECDHE]
   with the P-256 elliptic curve [FIPS186].

**Comment by Tratcher** [comment]
@blowdart renegotiation is the only thing on this list we can control via SslStream, the rest are controlled at the OS level. Are there any of these we should ask SslStream to expose (compression?), or do we fall back do documenting the recommended OS configurations.

**Comment by Drawaes** [comment]
With ref

https://en.m.wikipedia.org/wiki/Comparison_of_TLS_implementations#Compression

**Comment by Tratcher** [comment]
Blocked on https://github.com/aspnet/KestrelHttpServer/issues/2661
Things we need to surface:
- Tls version
- CipherAlgorithm 
- KeyExchangeStrength
