### ISSUE TITLE
CoreCLR `dnx kestrel` on OS X consistently fails after ~16500 requests

### ISSUE THREAD

**Issue by jstclair** [aspnet/KestrelHttpServer#226]
(This appears to be the case across multiple betas - I've tested beta7 and various beta8 releases)

I've created a simple WebApi site using `yo` and the `generator-aspnet` on OS X Yosemite 10.10.5

After starting the site and running an `ab` test, the load test consistently fail after approx. 16,384 requests. Note that this is cumulative (i.e., if you run 4 tests of 4000 requests, it will fail on the 5th test after approx. 384 requests -- assuming you are not restarting `kestrel` between each run).

At no time does `kestrel` itself report an error.

Latest tested version: 

```
dnvm: 1.0.0-beta8-15519
dnu/dnx: CoreClr-x64-1.0.0-beta8-15654

Microsoft.AspNet.Mvc 6.0.0-beta8-15875
Microsoft.AspNet.Server.Kestrel 1.0.0-beta8-15674
Microsoft.AspNet.StaticFiles 1.0.0-beta8-15649
```

Failure: (after running 4 previous tests)

```
$ ab -c 8 -k -n 4000 http://localhost:5004/api/values
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
apr_socket_recv: Operation timed out (60)
Total of 373 requests completed
```

Second run (after restarting kestrel):

```
$ ab -c 8 -k -n 17000 http://localhost:5004/api/values
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1700 requests
Completed 3400 requests
Completed 5100 requests
Completed 6800 requests
Completed 8500 requests
Completed 10200 requests
Completed 11900 requests
Completed 13600 requests
Completed 15300 requests
apr_socket_recv: Operation timed out (60)
Total of 16389 requests completed
```

**Comment by jstclair** [comment]
I'm including my project.lock.json file (as requested in other issues):

https://gist.github.com/jstclair/31cc14b24eda8c4139f7

(note: file contents were too long for a comment, so created a gist instead...)

**Comment by cesarbs** [comment]
@jstclair Are you still seeing this? I can't repro it.

**Comment by jstclair** [comment]
I can try again on the latest bits and close if not.

**Comment by cesarbs** [comment]
Ok, let us know.

**Comment by cesarbs** [comment]
Closing this since no repro (cc @muratg).
