### ISSUE TITLE
Kestrel Freezes

### ISSUE THREAD

**Issue by NPSF3000** [aspnet/KestrelHttpServer#2262]
Kestrel based websocket app becomes unresponsive at random intervals in production.  Reproduction is difficult, and relies upon running with load and monitoring for unresponsiveness.  Once unresponsive the only remedy is to stop the process gracefully and restart.

Environment: AWS, Ubuntu 16.04, Kestrel 2.0.0, AspNetCore 2.0.0

LLDB shows two threads with `System.ObjectDisposedException` exceptions, both with similar call-stacks:
```

00007FDC4EFFC4E0 00007fdf29543360 [HelperMethodFrame: 00007fdc4effc4e0] 
00007FDC4EFFC600 00007FDEB0424623 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.ValidateState(System.Threading.CancellationToken)
00007FDC4EFFC630 00007FDEB042444F Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameResponseStream.WriteAsync(Byte[], Int32, Int32, System.Threading.CancellationToken)
00007FDC4EFFC690 00007FDEB040D793 Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameDuplexStream.WriteAsync(Byte[], Int32, Int32, System.Threading.CancellationToken)
00007FDC4EFFC6B0 00007FDEB06DBCCE System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode, Boolean, System.ArraySegment`1<Byte>)
00007FDC4EFFC750 00007FDEB06DC20A System.Net.WebSockets.ManagedWebSocket.SendKeepAliveFrameAsync()
00007FDC4EFFC790 00007FDEB06DE2B9 System.Net.WebSockets.ManagedWebSocket+<>c.<.ctor>b__38_1(System.Object)
00007FDC4EFFC7A0 00007FDEAE701011 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00007FDC4EFFC7F0 00007FDEAE7B0DF4 System.Threading.TimerQueueTimer.CallCallback()
00007FDC4EFFC830 00007FDEAE7B0C16 System.Threading.TimerQueueTimer.Fire()
00007FDC4EFFC880 00007FDEAE7C6EA5 System.Threading.TimerQueue.FireNextTimers()
```

We have identified and removed a .Dispose made on a websocket which may be a cause, but shouldn't lead to this level of repercussions.  Also updating Asp/Kestrel to 2.0.1

[Websocket Crash Logs.txt](https://github.com/aspnet/KestrelHttpServer/files/1647648/Websocket.Crash.Logs.txt)

**Comment by Tratcher** [comment]
@anurse does this look like the issue you recently took a fix for?

**Comment by davidfowl** [comment]
@NPSF3000 what does your websocket loop look like?

**Comment by NPSF3000** [comment]
@davidfowl Each wss connection is collected from Kestrel and put into a async wait loop where it reads and processes incoming messages.  The readloop exits when the ws is no longer open (` while (WebSocket.State == WebSocketState.Open)`) and basic cleanup is done (including disposing of WS in this instance, though we've started leaving that to kestrel). 

Sending messages are 

Outbound messages are handled via a ActionBlock.

**Comment by davidfowl** [comment]
I'd like to see the code to make sure it looks right. Seems like lately I've seen lots of people writing incorrect async websocket loops.

**Comment by NPSF3000** [comment]
@davidfowl I understand.  I'm reasonably confident that the code is not the problem (written TCP socket servers in past, LLDB error message appears in Kestrel code, etc) but... it's always a possibility.

If you can provide a private method of uploading (email, ticket etc) I'll see about getting permission.

**Comment by davidfowl** [comment]
I see the callstack looks like a race condition in the ManagedWebSocket implementation itself.

**Comment by anurse** [comment]
I see the WebSocket code is running in a Timer, which indicates you are passing the socket off to a background thread. Unfortunately, when you do that, you have to ensure the underlying TCP connection stays open. The call stack being in Kestrel isn't really relevant since the issue is an ObjectDisposedException which indicates that someone disposed the underlying response stream while another task was still using it. The essential thing with WebSockets is that the request pipeline **must not** be allowed to complete while the socket is open. You are responsible for ensuring this in your client code. If you do something like this in your middleware:

```
app.Use(async (context, next) => {
  var socket = await context.WebSockets.AcceptWebSocketAsync();
  SocketManager.Add(socket);
});
```

The request pipeline will end and Kestrel will shut down the underlying TCP connection and dispose the response stream out from under the WebSocket. This is by-design, but we are looking at ways to improve documentation, see https://github.com/aspnet/Home/issues/2462

You need to ensure your background socket management process is given a [TCS](https://msdn.microsoft.com/en-us/library/dd449174(v=vs.110).aspx) or something to signal and the request thread needs to `await` the task from that TCS in order to avoid this.

**Comment by anurse** [comment]
If you do want a private way to communicate code so we can take a look, you can contact me directly at anurse@microsoft.com

**Comment by NPSF3000** [comment]
@anurse Thank you for you feedback.

"The call stack being in Kestrel isn't really relevant since the issue is an ObjectDisposedException..."

I'm a little confused here.  If we were talking about connections being dropped I can understand, but we're talking about code within kestrel locking up and forcing the entire application to be unresponsive.  

I do note that we did accidentally have a unnecessary dispose, that could cause issues if kestral wasn't prepared for that.  However, again, that shouldn't cause rare, hard to reproduce lockups.

"The essential thing with WebSockets is that the request pipeline must not be allowed to complete while the socket is open. "

Agreed.  Our code awaits the completion of a WS before allowing the request to proceed.

Request Received:

```
app.Use(async (context, next) =>
{
    ....
    WebSocket websocket = await context.WebSockets.AcceptWebSocketAsync();
    await new ClientConnection(websocket).Run();
});
```

After carefully examining our code I do note that it is possible for the following to be send after returning the socket to kestrel (in rare circumstances).

```
await WebSocket.CloseAsync(closeStatus: WebSocketCloseStatus.NormalClosure,
                                           statusDescription: "Closed by the WebSocketManager",
                                           cancellationToken: CancellationToken.None);
```

Or

`await WebSocket.SendAsync(new ArraySegment<byte>(bytes), WebSocketMessageType.Text, true, CancellationToken.None);`

In addition to the .Dispose that has been removed since posting the issue.  I am going to see if I can try to avert these race conditions.

**Comment by anurse** [comment]
> ```
> 00007FDC4EFFC750 00007FDEB06DC20A System.Net.WebSockets.ManagedWebSocket.SendKeepAliveFrameAsync()
> ```

Just noticed this one in the frame. This is https://github.com/dotnet/corefx/issues/24055 which wasn't ported to our WebSockets fork. It'll be fixed when https://github.com/aspnet/WebSockets/pull/220 is merged.

**Comment by anurse** [comment]
@NPSF3000 Can you confirm that these are just first-chance exceptions and not crashing the process? The keep-alive exception shouldn't be crashing the process or hanging the server. It may be unrelated to the issue you are seeing with freezing.

**Comment by NPSF3000** [comment]
@anurse all I can confirm is the behavior we are seeing.  The exceptions are from a core dump of a frozen  WSS server - they were the only things of note (See .txt for more details).

**Comment by anurse** [comment]
The exceptions shouldn't be causing any negative impact (they are thrown but because they are unobserved in the Task, they are suppressed). As I mentioned, we'll have a fix soon, but that will only suppress the exception, I doubt those exceptions are what's causing your issue.

**Comment by anurse** [comment]
@NPSF3000 to clarify, the server process does not crash and terminate, correct? It is just becoming unresponsive? I'm not sure where to look next to diagnose that, but @davidfowl or @halter73 may have some thoughts there as it could be a thread-pool starvation issue. Ideally, we'd want to look at something like the Parallel Stacks view in VS but I'm not sure if that can be easily applied to a core dump ;). My understanding from looking at the code is that the exceptions you are seeing aren't actually relevant here as they are being thrown but caught and ignored. Hope that helps a bit!

**Comment by halter73** [comment]
Unfortunately I don't know how to use Parallel Stacks with a Linux core dump. You can use Parallel Stacks when remote-debugging a live linux process. And you can use Parallel Stacks when debugging a Windows core dump in VS.

You can [use lldb with SOS](http://blogs.microsoft.co.il/sasha/2017/02/26/analyzing-a-net-core-core-dump-on-linux/) to debug a coredump on linux, but that's a bit of a pain to look at a bunch of stacks at once that way. This will be made easier with the introduction of [clrstack -all](https://github.com/dotnet/coreclr/pull/13302), but I'm not exactly sure which version of the runtime shipped with support for this.

**Comment by benaadams** [comment]
If you add https://github.com/benaadams/Ben.BlockingDetector to your middleware does it output any warnings?

**Comment by NPSF3000** [comment]
Thanks guys for all the suggestions.  We've got a bunch of tests to run, and will keep you up to date as results appear.

**Comment by NPSF3000** [comment]
Issue has not been reproduced since personal fixes.  Recommendation for future readers:

1)  Ensure you have latest .NET Core packages (we are now running 2.0.5).
2)  Ensure you do not dispose the websocket yourself.
3)  Do not interact with websocket after handing it back to kestrel.  We had to use Cancellation Tokens and Semaphores to help synchronous our cleanup code.
