### ISSUE TITLE
Custom CorrelationId Middleware with Kestrel 

### ISSUE THREAD

**Issue by Tadimsky** [aspnet/KestrelHttpServer#2266]
I've created customer CorrelationId Middleware that uses the Connection Id in ASP.NET Core or a client-provided Id to attach to all of my logs.

The code to set the header was like this:
```c#
context.Response.OnStarting(() =>
            {
                SetCorrelationId(context, context.TraceIdentifier);
                return Task.CompletedTask;
            });
```

I ran into an issue where I would not get any header set when there was an unhandled exception. It seems like `OnStarting` was not being called.
I then added a `try/catch` around the `await _next(context)` call to explicitly catch unhandled exceptions and set the header then. However, if I re-threw the exception, then the header that I set there would not be applied either.
I then changed from re-throwing the exception to just returning, but now I don't get any of the default exception handling done in  FrameOfT.cs `ProcessRequestsAsync`. This means that I don't get the default exception logging to Application Insights either as `ReportApplicationError` is no longer being called.

Is there a good way for me to be able to set a custom header on a response, even if it is due to an unhandled server error? Or is me replicating what is normally done the only way?

**Comment by Tratcher** [comment]
That about sums it up. Once an exception reaches Kestrel it will clear all response headers, skip OnStarting, and send an error response. In production you should not rely on the servers's error handling, this is a last ditch effort to keep the server from crashing. Exceptions in production should be handled by middleware. Those middleware can do their own logging such as calling into application insights. If the current diagnostics middleware aren't logging enough for your then please file a bug against them.

**Comment by Tadimsky** [comment]
Ok thanks, that definitely makes sense. We need to get our own exception tracking middleware to handle errors like this then.
Is there any recommended existing middleware for doing this? I've seen the Developer one for Dev environments.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Diagnostics/tree/f90337c1a6d5edd0cfe55466e3f544f3be047917/src/Microsoft.AspNetCore.Diagnostics/ExceptionHandler is for production environments.

**Comment by Tadimsky** [comment]
Ok, thanks @Tratcher - that looks like the right thing to use then.

I noticed that `ExceptionHandlerMiddleware` will set `_next` as the `ExceptionHandler` if no path is specified and the options `ExceptionHandler` is null. Doesn't this mean that it will re-run the request pipeline in the case of a failure? That seems a little strange unless I'm missing something.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Diagnostics/issues/400

**Comment by Tadimsky** [comment]
Thanks! And thank you for the help. Will close this issue.
