### ISSUE TITLE
Error - The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by ankurjasoria** [aspnet/KestrelHttpServer#2269]
Hi All I am facing issue "The specified CGI application encountered an error and the server terminated the process." after hosting it on Azure Web Sites. On Local it works fine. I have developed application on asp.net core 1.0 and deployed on Azure.

Is there any timeout issue or any thing missing when deployed code on azure ?
Please help me out regarding this issue.

**Comment by halter73** [comment]
@ankurjasoria There are a number of possible causes for the "The specified CGI application encountered an error and the server terminated the process." message. I would collect [ASP.NET Core logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore1x#how-to-add-providers) and potentially [IIS logs](https://docs.microsoft.com/en-us/azure/app-service/web-sites-enable-diagnostic-log) to help figure out what's really going on.

**Comment by ankurjasoria** [comment]
@halter73  I have verified log also but only found same CGI related error in html code. I am attaching same file. Please check and let me know how I'll go ahead from same issue.
[AzureLog.txt](https://github.com/aspnet/KestrelHttpServer/files/1664490/AzureLog.txt)

**Comment by halter73** [comment]
Those are the IIS logs, but the errors are likely originating from the dotnet process. To figure out the cause of these errors, you should collect ASP.NET Core logs as described in the link I provided in my last comment.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
