### ISSUE TITLE
Always consume request body for valid non-keep-alive requests before closing connection

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2276]
I'm suggesting that we revert the behavior introduced to fix #418 that doesn't drain the request body for non-keep-alive connections. We should be careful to ensure this doesn't adversely affect nginx scenarios, but I don't think we'd see hangs anymore since we've since gotten rid of `MessageBody.ForRemainingData`.

I'm suggesting changing this now because of the behavior described in [this comment](https://github.com/dotnet/corefx/issues/23504#issuecomment-360639626) in which some clients blow up due to RSTs sent after the entire response was flushed.

**Comment by alefranz** [comment]
I'd like to work on this one. I've submitted PR #2314 and waiting for feedback.
Is there any scripts and nginx config around to easily test #418 after this change?

**Comment by halter73** [comment]
Thanks @alefranz!
