### ISSUE TITLE
Error while shutting down kestrel server

### ISSUE THREAD

**Issue by gthuruv** [aspnet/KestrelHttpServer#2286]
We are seeing some issues while disposing a webhost that uses kestrel. This is the only error message we see during the time period and looks like they are from kestrel logs,

"Disposing listeners failed."

The process gets stuck and has to be killed.

**Comment by davidfowl** [comment]
What version of kestrel?

**Comment by gthuruv** [comment]
2.0.1

**Comment by davidfowl** [comment]
Can you give more information about the application? Is this a normal asp.net core application? Are you explicitly disposing the host or is this normal process shutdown?

**Comment by gthuruv** [comment]
It is a service fabric application that uses aspnet core with kestrel web server. Service fabric reliable services provide us with an option to specify the kind of webhost we want. It will use this logic to build a new webhost whenever necessary and then disposes it once done with it. More details [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-aspnetcore#kestrel-in-reliable-services)

This webhost would be a property of a replica (an instance of the service fabric service within a **_process_**). The same process can spin up and shut down multiple replicas, so create and dispose multiple kestrel web servers with it, all the while serving incoming requests. The dispose could happen anytime and does not mean the process is shutting down.

**Comment by gthuruv** [comment]
Just to be clear, the process is managed by service fabric that will do the creation and disposal of the webhost, so yeah technically, it must be explicitly calling Dispose() on the host.

**Comment by muratg** [comment]
Putting this in Discussions milestones until we can get more details to investigate this deeper.

@gthuruv Any chance you can try 2.1 to see if it fixes your issue in this case?  Also, would it be possible to get a process dump when you hit this?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
