### ISSUE TITLE
Option to get Certificate directly from Azure Key Vault

### ISSUE THREAD

**Issue by onovotny** [aspnet/KestrelHttpServer#2288]
With the new certificate capabilities 2.1, it would be very useful if Kestrel could get certificates directly from Azure Key Vault. This is especially true because Key Vault can auto-renew certificates from providers already.

If done with Managed Service Identities, this can be transparent as well.

**Comment by davidfowl** [comment]
This is something we should think about being part of https://github.com/aspnet/AzureIntegration/. There's a work item about integrating with KeyVault.
