### ISSUE TITLE
Kestrel running inside IIS with HTTPS

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#2289]
I would like to run kestrel under IIS with HTTPS configuration controlled via IIS; 
and kestrel aware that the IIS endpoint is secured, is this possible and/or how 
can the communication between IIS & Kestrel be secured?

**Comment by Tratcher** [comment]
HTTPS between IIS and Kestrel is not supported. However, this connection is strictly over localhost so the possibility of exposure is quite limited.

When IIS is configured for HTTPS externally then it forwards to Kestrel using HTTP and sets the x-forwarded-proto: https  header. UseIISIntegration reads this header and applies it to HttpContext.Request.Scheme so the app knows the external connection is https.

**Comment by grahamehorner** [comment]
@Tratcher thanks that helps; as we currently have a PEN testing company looking at the setup asking these questions

**Comment by Tratcher** [comment]
Ok. If they find anything interesting please report it through our bug bounty program, not on github.

**Comment by benaadams** [comment]
ASP.NET Core 2.1 https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/ may also have an addition interesting option

> ** In-process hosting **
>
> In 2.1, we’re adding a new in-process mode to ANCM for .NET Core based apps where the runtime and your app are both loaded inside the IIS worker process (w3wp.exe). This removes the performance penalty of proxying requests over the loopback adapter. Our preliminary tests show performance improvements of around ~4.4x compared to running out-of-process. Configuring your app to use to use the in-process model can be done using `web.config`, and will be eventually be the default for new applications targeting 2.1:

**Comment by grahamehorner** [comment]
@benaadams thanks for the heads up Ben +1

**Comment by muratg** [comment]
:+1:
