### ISSUE TITLE
Kestrel on Linux not supporting a cipher

### ISSUE THREAD

**Issue by rsrinivasanhome** [aspnet/KestrelHttpServer#2297]
Hi I referred the following issue https://github.com/aspnet/KestrelHttpServer/issues/1865

But not clear with the following  .  
How do we link ciphers to kestrel ?  Are all ciphers available In openssl available in kestrel.  
I tried using an ECC cipher which was visible in the list of the ciphers (found using the command 
openssl ciphers -v ALL ) but  getting the error 

System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake faile
d with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
r
Do we have a list of ciphers supported by kestrel ?

**Comment by Drawaes** [comment]
It should just be using the default list from openssl. Infact there is an open issue to allow configuration of ciphers in SslStream (that Kestrel uses)

**Comment by rsrinivasanhome** [comment]
@Drawaes  you had mentioned in the issue 1865 we would need to "you need to ensure you only call methods on the lib after .net did it's openssl init or you need to do it, otherwise you won't have ciphers loaded.".  How is this achieved ?  Can we call some open ssl command in our docker file will this help load the ciphers ?

**Comment by Drawaes** [comment]
No you need to do it in process, so you would just "touch" the Crypto apis and they will init openssl. Then you would PInvoke the set ciphers method (I can't remember it off by heart), in saying that ECC should be enabled by default by OpenSSL

**Comment by samsosa** [comment]
Should resolved with [https://github.com/dotnet/corefx/pull/25985](url)?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
