### ISSUE TITLE
Obtain all listening endpoints from controller

### ISSUE THREAD

**Issue by leak** [aspnet/KestrelHttpServer#2306]
I used to be able to do this in a controller:

`var serverAddress = ((Microsoft.AspNetCore.Server.Kestrel.Internal.Http.ListenerContext)((DefaultHttpContext)HttpContext).Features).ServerAddress;`

which would give me this:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.serveraddress?view=aspnetcore-2.0

Now the `Internal.Http` seems to be gone or I am missing a reference?

Is there a better way to obtain all listening endpoints from Kestrel itself rather than from config?

**Comment by davidfowl** [comment]
Once you see internal in the name, you’re in dangerous territory. Also these addresses are wrong when you are behind a reverse proxy. What are you using them for?

**Comment by leak** [comment]
I'd be happy to use some solution that doesn't involve internal classes, also I don't care about the reverse proxy case. My use case is very specific (machine with multiple interfaces and unknown networks, etc.) but I think that is beside the point.

Basically I want to create a WebApi that is returning all interfaces Kestrel is actually accessible on.

**Comment by Tratcher** [comment]
You can capture the IServerAddressesFeature at startup:
https://github.com/aspnet/BasicMiddleware/blob/5c3fc3770fd9c88f2a6126c47ab741d40e48b034/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionBuilderExtensions.cs

Don't read it before the first request though, it's contents are updated as the server starts.

**Comment by leak** [comment]
Thank you for your input.

IServer is going in the right direction, what would be really interesting to me is the ListenOptions (marked red). Any way to access those without bringing out the reflection guns?

![image](https://user-images.githubusercontent.com/530056/36036127-53d5f1ac-0db9-11e8-912a-9007bae47a61.png)

**Comment by davidfowl** [comment]
No those are internal for all intents and purposes.

**Comment by halter73** [comment]
Injecting the IServerAddressesFeature into the controller should work, no?

**Comment by Tratcher** [comment]
IServerAddressesFeature isn't a service registered in DI or in the HttpContext FeatureCollection. You can only capture it in Startup.Configure.

**Comment by benaadams** [comment]
Capture to field in `Configure` then register value with DI in `ConfigureServices` against `IServerAddressesFeature`?

**Comment by Drawaes** [comment]
Configure runs after configure services no?

**Comment by benaadams** [comment]
> Configure runs after configure services no?

Good point :)

Capture it in `Configure` set it in FeatureCollection via middleware then?

**Comment by Drawaes** [comment]
As a "why do you want this?" We use it heavily to auto register our API services with a service registry. We need to tell it the IP addresses and ports that are listening (the ports are dynamically allocated at startup) and also the network wants to know the interfaces that are listening so it can start running health checks.

**Comment by Tratcher** [comment]
We've started doing this in 2.1 for detect ports for redirect to https.
https://github.com/aspnet/BasicMiddleware/blob/5a3f9d930329aaed5d641cf1612f4e1df8f5e491/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionBuilderExtensions.cs#L32-L36

**Comment by halter73** [comment]
@Tratcher This should also work in 2.0, right?

**Comment by Tratcher** [comment]
Yes, we've just never consumed it before 2.1.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
