### ISSUE TITLE
Unexpected server behaviour after dotnet core update.

### ISSUE THREAD

**Issue by skynyrd** [aspnet/KestrelHttpServer#2316]
Hi, we have upgraded our dotnet core application from 1.1 to 2.1.4 and got some problems after that. 
We run the application on docker containers (using dotnet core 2.0.5 as runtime version) on Ubuntu servers. 

### Functional impact
After a while server stopped accepting requests and logged:

```
February 12th 2018, 04:30:26.891 | Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -107 ENOTCONN socket is not connected

  | February 12th 2018, 04:30:26.891 | 2018-02-12T04:30:26.3962637+03:00 [Error] [] (Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv) [] ListenerSecondary.OnConnection

  | February 12th 2018, 04:30:26.400 | 2018-02-12T04:30:26.3406994+03:00 [Warning] [] (Microsoft.AspNetCore.Server.Kestrel) [] Heartbeat took longer than "00:00:01" at "02/12/2018 01:30:26 +00:00".

  | February 12th 2018, 04:30:26.398 | 2018-02-12T04:30:26.3381005+03:00 [Warning] [] (Microsoft.AspNetCore.Server.Kestrel) [] Heartbeat took longer than "00:00:01" at "02/12/2018 01:30:26 +00:00".
```

The last two lines repeated few times.

### Minimal repro steps
Its hard to reproduce it, but just happens a few days after running the container.

### Expected result
It should not stop accepting requests.

What can be the problem? Thanks.

**Comment by halter73** [comment]
Did you just get the 2 heartbeat warnings or were there more? Were there any other logs around February 12th 2018, 04:30:26?

Upping the tracing level to the most verbose [trace log level](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#log-level) could help diagnose this. I'd also try using gdb/gcore to collect a memory dump after it stops accepting requests prior to restarting the server.

**Comment by skynyrd** [comment]
Not many, but yes. I am going to try what you have suggested. Thanks.

**Comment by halter73** [comment]
The heartbeat warnings are generally a pretty good indicator of threadpool starvation. That's what I'd be looking for if you collect a memory dump.

**Comment by halter73** [comment]
Not related to the root issue, but as of #2547, ENOTCONN will be reported as a connection reset.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
