### ISSUE TITLE
.net framework support?

### ISSUE THREAD

**Issue by VanCoding** [aspnet/KestrelHttpServer#2317]
currently, kestrel 2.0.1 is only available for .net core, whereas 1.1.3 was available for .net framework 4.5.1 as well.

Do you guys intend to add .net framework support again or will kestrel remain .net core only?

**Comment by Tratcher** [comment]
It's available for net standard which includes core and framework.

**Comment by VanCoding** [comment]
ah well, this was a bit confusing by looking at the nuget page, but looking at https://docs.microsoft.com/en-us/dotnet/standard/net-standard helped. Thanks :)
