### ISSUE TITLE
Investigate startup issues with Kestrel

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2323]
@anurse @pakrym @halter73

**Comment by pakrym** [comment]
Performance

**Comment by anurse** [comment]
I too can use random software engineering terms. Multithreading. Concurrency. Thunk.

What's the context on this? Kestrel being slow to start-up?

**Comment by pakrym** [comment]
Yep, the issue you've seen when trying to start the server for every test.

**Comment by muratg** [comment]
Who is looking into this?

**Comment by muratg** [comment]
I don't understand what this issue is, so closing this.
