### ISSUE TITLE
Multiple webhost instances in same app?

### ISSUE THREAD

**Issue by eklein23** [aspnet/KestrelHttpServer#2325]
I'm porting an existing application from Owin to Kestrel and running into an issue.  The application is split into two components, a front-end UI and back-end API.  Each is implemented in a separate assembly, but they run together in the same self-hosted executable under a common root.  In other words:

http://+:5000/front-end (html/js)
http://+:5000/back-end (web API)

With Owin, each component creates its own instance of "WebApp" with a startup class and associated middleware configuration.  They use the same server address and port, but with different base prefixes.

Kestrel, on the other hand, does not work as expected with multiple instances of "IWebHost" with the same address and port.  You can set a PathBase in the Configure method of the startup class for each instance (i.e., "front-end" for one and "back-end" for the other), but this does not control which web host processes a HTTP request.  All the requests seem to go to the first created host instance.

Is there a way to configure Kestrel to allow multiple web host instances to share a URL root?

**Comment by Tratcher** [comment]
Kestrel doesn't support port sharing. I would have excepted an exception when you started the second site. You could use the HttpSys server instead, it's based on the same infrastructure you were using in Microsoft.Owin.

**Comment by eklein23** [comment]
Thanks for the suggestion.  I forgot to mention the reason I'm using Kestrel is for cross-platform support, so http.sys isn't an option.

**Comment by Tratcher** [comment]
Ah. Cross-plat you'll need to redesign a bit. You can:
A) merge the apps into one instance and distinguish them with routing
B) give them different ports
or C) use a reverse proxy like nginx to forward from a shared port to different processes and/or ports.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
