### ISSUE TITLE
Fix connection management with connection middleware

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2335]
Today Kestrel exposes the `IConnectionBuilder` interface but connection management is only implemented in the HttpConnectionMiddleware. To properly port existing connection adapters to connection middleware, we need to move the connection management up a layer.

**Comment by justinwyer** [comment]
Looks interesting & challenging, would like to have a go at this if no one else is working on it. Do you have any further thoughts to share @davidfowl?

**Comment by davidfowl** [comment]
@justinwyer this is a bit tricky because kestrel has a bunch of logic specific to HTTP that we need to figure out how to decouple first. Another option would be to track raw connections outside of http and perform the shutdown for that before or after the http specific code path.

**Comment by justinwyer** [comment]
@davidfowl I noticed 😂I'll ponder it a bit more over the weekend but we definitely need to decouple. Let's see what I come up with...
