### ISSUE TITLE
IIS Express/Kestrel locks bin files preventing rebuild

### ISSUE THREAD

**Issue by brgrz** [aspnet/KestrelHttpServer#2336]
When debugging an asp.net core from VS 2017 (latest build) and then stopping it the IIS Express keeps running and new build of the app is impossible due to the following compile time errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "obj\Debug\netcoreapp2.0\MyProject.dll" to "bin\Debug\netcoreapp2.0\MyProject.dll". Exceeded retry count of 10. Failed. The file is locked by: "dotnet (13896)"	MyProject	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4106	

```

**Comment by davidfowl** [comment]
This doesn't really have anything to do with Kestrel as it runs as part of your application process. Visual studio usually kills the process when you ctrl + f5. Are you manually right clicking on IIS express in the tray and killing it?

/cc @BillHiebert

**Comment by BillHiebert** [comment]
@brgrz As David says, Visual Studio should be stopping the process prior to the build starting. It does leave IIS Express running but it should not be starting the kestrel process. By any chance is the browser still running and pointing to the site? I wonder if it is making a request and since IIS Express is still running it is re-starting the kestrel process.

**Comment by brgrz** [comment]
@davidfowl @BillHiebert I start it with f5 then stop it by stopping it through the toolbar. I leave the IIS Express running and then try to rebuild. It does not go through so then I go and manually stop IIS Express in the tray.

**Comment by BillHiebert** [comment]
@brgrz do you have a project you can share which reproduces this? So far I have been unsuccessful.

**Comment by brgrz** [comment]
@BillHiebert I'm currently troubleshooting this myself too moving to another machine and doing code changes too see if it is related to any of my code. Will let you know soon, please keep the issue open.

**Comment by brgrz** [comment]
@BillHiebert After moving this project to another machine the same thing happened and it happened without even debugging first (only ctrl+f5). I used Resource Monitor and found out it is dotnet.exe that has an open handle on built dlls. Why would that be happening?

I don't think I am able to provide a project with repro for this at least not at the moment.

**Comment by brgrz** [comment]
@BillHiebert So I closed all browsers windows and Postman desktop app and it still holding a handle on built dlls. The only thing left running now is IIS Express (besides the VS itself).

**Comment by BillHiebert** [comment]
@brgrz  If you Ctrl+F5, look at the process id of dotenet.exe, then build, VS should be terminating dotnet. If it is still running and failing the build is there a different process id for dotnet, or the same one? I am trying to understand if it is being restarted or never being terminated in the first place. I assume a new project does not exhibit this behavior?

**Comment by brgrz** [comment]
I've been testing it for the last couple of minutes..and..it's weird. The dotnet.exe process seems to be restarting, gets a new PID but not always is there an open handle put on the dlls.

**Comment by brgrz** [comment]
@BillHiebert How fast does the dotnet.exe shutdown after last request? Because I'm issuing requests with Postman in few minutes intervals and it seems what happens is dotnet.exe shutdown sometimes in between. Some requests take a couple of ms, while some take 12-30s (apparently when dotnet.exe is asleep).

**Comment by BillHiebert** [comment]
@brgrz I wonder if that is the problem.  VS probably needs to block until the process has completely terminated before allowing the build to proceed. I should be able to simulate your scenario and validate this is what is happening. Thanks.

**Comment by BillHiebert** [comment]
If dotnet.exe is restarting it is likely the browser is pinging the server. This will cause IISExpress to spin up the process again. 

I checked the code and VS does a Process.Kill() on dotnet.exe so it should terminate relatively quickly - though we really need to block until it actually terminates since the Kill is asynchronous. 

I'll look at both of these issues.

**Comment by mikeharder** [comment]
This issue is being tracked here: https://developercommunity.visualstudio.com/content/problem/161811/output-exe-locked-by-iis-express-use-to-debug-same.html
