### ISSUE TITLE
Unable to read big json file from Request.Body

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#234]
_From @anfomin on September 30, 2015 15:1_

I'm trying to read big JSON file (UTF8) from `Request.Body` stream:
```C#
string content;
using (var sr = new StreamReader(Request.Body, Encoding.Default))
	content = sr.ReadToEnd();
```

At the beginning it's ok, but `content` variable contains invalid character sequence after some offset.

Sample repo: https://github.com/anfomin/DNX-MVC-bigfile. There is file `sample.json`. Just run `dnx kestrel` and make:
```http
POST http://localhost:5000
```
with body = `sample.json` file.

You will find mismatches since line 84.

Source:
![2015-09-30 19 58 00](https://cloud.githubusercontent.com/assets/1905503/10196698/9d2e92be-67ad-11e5-8948-254595776df4.png)

Result:
![2015-09-30 19 58 18](https://cloud.githubusercontent.com/assets/1905503/10196702/9e6a8c64-67ad-11e5-8ebc-f5e4432d113f.png)

I've tried latest DNX 1.0.0-beta8-15736 from https://www.myget.org/F/aspnetvnext/api/v2 and 1.0.0-rc1-15775 from https://www.myget.org/F/aspnetcidev/api/v2.

_Copied from original issue: aspnet/Mvc#3235_

**Comment by Tratcher** [comment]
_From @Eilon on September 30, 2015 18:49_

@kichalla can you take a look?

**Comment by Tratcher** [comment]
_From @kichalla on September 30, 2015 19:51_

@anfomin I suppose you are running on Mono on Linux? was curious if Encoding.Default was doing something here but looks like some content is entirely missing based on your snapshot above...just to isolate the issue, can you try saving the read content to a file and see if the contents are any different? also does this issue repro consistently for you?

**Comment by Tratcher** [comment]
_From @anfomin on September 30, 2015 20:38_

@kichalla I tried this sample both on Windows and Mac, result is the same.

Also I tried to save `Request.Body` to a text file via `File.CreateText("...")`. Result file contains the same corruptions. You can remove `Encoding.Default`, the result does not change.

The problem is `Request.Body` because when I change input stream to `File.Open(...)` then output is correct.

**Comment by Tratcher** [comment]
_From @kichalla on September 30, 2015 21:2_

@anfomin you are right, I was able to repro it on a Windows machine now..investigating...

left -> actual file content
right -> content read from request body and saved to a file
![image](https://cloud.githubusercontent.com/assets/6559784/10206427/ad7b9dce-677b-11e5-82a0-c0a9fb0b4bb9.png)

**Comment by Tratcher** [comment]
_From @Eilon on September 30, 2015 21:5_

Weird... putting this on RC. Please enlist @halter73 @lodejard @Tratcher @moozzyk if needed because this might even be a Kestrel issue.

**Comment by Tratcher** [comment]
_From @kichalla on September 30, 2015 21:13_

Yeah, this seems like a Kestrel issue as I cannot repro it with weblistener

**Comment by lodejard** [comment]
I'll take a look also

**Comment by kichalla** [comment]
@loudej Probably you are the best person to take a look at it...I tried to figure it out but I got lost :smile: ..following are some details:
- This issue seems to repro only for specific request sizes and characters...for example, the below repro works fine if the character is ASCII...so my wild guess is that it has something to do with decoder and its flushing...
- You can use the following repro code
I used the `LargeResponseApp` in Kestrel repo for this 
  ```c#
app.Run(async (context) =>
            {
                var reader = new StreamReader(context.Request.Body);
                var content = await reader.ReadToEndAsync();

                using (var sw = new StreamWriter(File.Create(@"C:\Users\kichalla\Documents\files\actual.txt")))
                {
                    await sw.WriteAsync(content);
                }
            });
   ```
  Client app:
  ```c#
public class Program
    {
        public void Main(string[] args)
        {
            var filePath = @"C:\users\kichalla\documents\files\expected.txt";
            using (var streamWriter = File.CreateText(filePath))
            {
                streamWriter.Write((new string('й', 5 * 1024 * 1024)));
            }
            //--------
            var httpClient = new HttpClient();
            var response = httpClient.PostAsync("http://localhost:5000", new StreamContent(File.OpenRead(filePath))).Result;
            Console.WriteLine(response.ToString());
            Console.WriteLine(response.Content.ReadAsStringAsync().Result);
        }
    }
  ```

**Comment by lodejard** [comment]
Perfect! Thanks @Tratcher, @kichalla those should repro very well in a unit test also

**Comment by MJomaa** [comment]
I have the same issue with 1.0.0-beta8-15736. With beta8-15613 it worked fine.

Reproduce:

https://github.com/MJomaa/MalformingDataBug

**Comment by muratg** [comment]
@MJomaa thanks for the info when it started to fail. This should give @lodejard some pointers in investigation.

**Comment by Tratcher** [comment]
@lodejard  Repro functional test checked in: https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNet.Server.Kestrel.FunctionalTests/RequestTests.cs#L19

**Comment by edurdias** [comment]
hi @halter73, thanks for working on this issue. 

Would you be able to confirm which is the package version that contains the fix? 

The last version I was able to use was 1.0.0-beta8-15674. If I try to use 1.0.0-beta8-15697 or 1.0.0-beta8-15702 it doesn't seems to work anymore.

**Comment by halter73** [comment]
@edurdias This should be fixed in the [final beat8 package](https://www.nuget.org/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-beta8) and all the rc1 prerelease packages.

It will probably take a little while digging the CI logs to find the specific build number the fix was introduced in. Do you really need that?

**Comment by edurdias** [comment]
We were using older build version in some of our microservices but I did an experiment and we should fine upgrading them to final beta8 version. 

Thanks for the quick feedback.
