### ISSUE TITLE
Add Hybrid RSA + ECDSA Certificates Support for Speed + Security

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/KestrelHttpServer#2349]
NGINX v1.11.0 has support for [hybrid RSA and ECDSA certificates](https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/) i.e. it uses ECDSA where it can and falls back to RSA certificates where browser support is a problem.

ECDSA has a doubly wammy speed and security boost that people as shown [here](https://scotthelme.co.uk/ecdsa-certificates/), so implementing this would be a win win scenario.

**Comment by shirhatti** [comment]
@RehanSaeed If I understood correctly, you're looking to bind multiple certificates to the same binding.

This is transparent to Kestrel.

I know this already works on Windows where you can you use a tool like [certutil.exe to merge multiple pfx files into a single pfx](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil#BKMK_MergePFX) and use that merged certificate to create your binding.

I'm assuming there is something similar for OpenSSL where you can provide combine multiple certs into a single pem file that OpenSSL will understand.

**Comment by shirhatti** [comment]
@blowdart If he has any inputs here

**Comment by blowdart** [comment]
No comments, it's up to the underlying transport provider, not Kestrel

**Comment by Drawaes** [comment]
Its up to SslStream, and I believe the Schannel implementation from memory takes only a single handle from the X509Certificate2 and passes it to the AuthHandle that is used by SChannel (even though its an array).

I could be wrong it's happened before (and according to my wife is more often than I like to believe).

**Comment by RehanSaeed** [comment]
@shirhatti Was not aware that you could merge pfx files.
@Drawaes So it doesn't work and changes are requried in corefx. I guess nobody has ever tried this before.

**Comment by samsosa** [comment]
X509Certificate2 only load the first (or last?) certificate in a merged pfx collection. I've tested little bit around but because X509Certificate2 always is a single certificate store it cannot be RSA and ECDSA at the same time.

Maybe SslStream.AuthenticateAsXXXX can be extended to accept multiple X509Certificate2 instances sorted by priority, selected by cipher compatibility?

Or just an SslStream.AuthenticateAsXXXX method which accepts X509Certificate2Collection?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
