### ISSUE TITLE
Kestrel should implement IHttpRequestIdentifierFeature to avoid the slow default implementation

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/KestrelHttpServer#235]
Perhaps use the socket handle ID combined with a simple counter of some sort. Make it as "free" as possible :smile:

by @DamianEdwards

**Comment by Tratcher** [comment]
We also need this in order to take full advantage of the static feature collection from https://github.com/aspnet/KestrelHttpServer/issues/162

**Comment by davidfowl** [comment]
I actually think we should make the default implementation not slow :smile:

**Comment by AspNetSmurfLab** [comment]
FYI, CPU profile of latest Kestrel showing that this is currently the most expensive item in the plaintext benchmark, accounting for 7.17% of **all** CPU time.

**Comment by AspNetSmurfLab** [comment]
Trying to make the default implementation in Hosting faster first: https://github.com/aspnet/Hosting/tree/damianedwards/fast-request-id

**Comment by muratg** [comment]
@DamianEdwards Link to your branch doesn't work. Is that merged or deleted?

**Comment by davidfowl** [comment]
Hosting has a very fast implementation that is already merged now.

**Comment by muratg** [comment]
So this one good to close, or do we plan to do more on Kestrel to gain more perf?

**Comment by Tratcher** [comment]
Kestrel could still do better than Hosting, such as https://github.com/aspnet/KestrelHttpServer/pull/243

**Comment by benaadams** [comment]
Can push up to HttpAbstractions and add ```TraceIdentifier``` onto HttpContext which then makes then makes it available for wider use https://github.com/aspnet/HttpAbstractions/pull/435

Then switch to lazy eval? https://github.com/aspnet/Hosting/pull/394

**Comment by muratg** [comment]
Not sure if this is still relevant.  @DamianEdwards feel free to close.

**Comment by SajayAntony** [comment]
@halter73 wanted to get pulse on this issue. Is it still relevant or did you break it into some other issue.

**Comment by halter73** [comment]
I'm closing this issue. Feel free to reopen, but since the time this issue was filed, the default `IHttpRequestIdentifierFeature` was changed to both [lazily evaluate the request identifier and cache the result](https://github.com/aspnet/HttpAbstractions/blob/02363da94eee7311e457e136dc45edf9c5ac3494/src/Microsoft.AspNetCore.Http/Features/HttpRequestIdentifierFeature.cs#L20). I don't think there's anything about generating the identifier in Kestrel itself that could really make this faster.
