### ISSUE TITLE
Reenable ApiCheck when fixed

### ISSUE THREAD

**Issue by pakrym** [aspnet/KestrelHttpServer#2350]
https://github.com/aspnet/BuildTools/issues/592

**Comment by JunTaoLuo** [comment]
Follow up needed in #2424

**Comment by davidfowl** [comment]
@pakrym why did you re-open this?

**Comment by muratg** [comment]
@pakrym do we need anything in RC1? If so, we'll need a shiproom label. Otherwise, could you move it to 2.2.0-mq?

**Comment by pakrym** [comment]
If we want to continue to validate API changes - yes, I don't know if it is fixed to be re-enabled.

Fix is being tracked in https://github.com/aspnet/BuildTools/issues/592
