### ISSUE TITLE
Knowing when Kestrel has stopped and completed finishing processing requests

### ISSUE THREAD

**Issue by FrederickBrier** [aspnet/KestrelHttpServer#2351]
This is a feature request. I just finished digging through the Kestrel source, primarily the KestrelServer class, looking for a way to know the server has stopped accepting connections and all processing of requests is complete. There are no events or reactive extensions, no lambda(s) to inject, no lifecycle methods that could be overridden. All the data members are private. None of the methods are virtual. If StopAsync() were virtual, or the _stoppedTcs were a public property, they could be overridden, or used to know the state of the server (non-null TaskCompletionSource<object>, null, or exception object).

It would be helpful if the KestrelServer class had some extension points or were not quite so locked down.

My use case is that OnShutdown, I want to save the system state in memory to a database. Thank you.

**Comment by Tratcher** [comment]
You're looking for IApplicationLifetime.ApplicationStopped 
https://github.com/aspnet/Hosting/blob/23b4ecd8d328c46954caca444410487991a485e8/src/Microsoft.AspNetCore.Hosting.Abstractions/IApplicationLifetime.cs#L30

**Comment by FrederickBrier** [comment]
That is possible. I am a read-the-source-luke kind-of-guy, and I am just not seeing where ApplicationStopped is done after all the tasks are complete. ApplicationStopped is called in an exception block in SocketTransport and in LibuvThread, but I am not seeing where it called as part of an orderly shutdown, stopping listening, letting all the requests (Task)s be serviced and completed.

The closest I see is StopAsync() which is called from Dispose(), and looks like it is just killing the main listening port/socket.

The ConnectionHandler.OnConnection() method, toward the end, has a comment about graceful shutdown, but all the BeginConnectionScope code it calls in Execute() seems to be logging statements.

There could certainly be an abstraction I am missing, but it isn't clear to me that ApplicationStopped will really tell me that all the processing requested on a connection, is complete. Please tell me where I am missing it. Thank you.

**Comment by Tratcher** [comment]
That's because it's called in Hosting after StopAsync completes.

**Comment by FrederickBrier** [comment]
Ah, so Hosting calls the IServer.StopAsync() passing in its own cancellation token. When that task completes, you know that all connections have been closed. Going a bit further, it looks like WebHostService.OnStop() is the method in which the StopAsync() is eventually called when the application is deployed as a Windows service. After all the connections are closed, it calls OnStopped() which can be overridden. The pattern described in the [article on deploying a .NET Core web app as a Windows service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?tabs=aspnetcore2x), my CustomWebHostService merely implements OnStopped() and calls my state saving methods, and has access to the instances in the DI container via the Services property. This summary is mostly for any who follow in my footsteps. Thank you for the pointers.
