### ISSUE TITLE
Support SNI to enable multiple HTTPS hosts on single server

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/KestrelHttpServer#2357]
There are three parts to this:
1) Work with corefx to define the SslStream API: dotnet/corefx#24553
2) Expose the new configuration in Kestrel's Https APIs.
3) Expose some form of this in Kestrel's config file format

@Tratcher @muratg

**Comment by Tratcher** [comment]
See https://github.com/dotnet/corefx/issues/24553, https://github.com/aspnet/KestrelHttpServer/issues/2103

**Comment by JoshCollinsMSFT** [comment]
Assuming dotnet/corefx#24553 makes it in the .NET Core 2.1 release, will the next release of KestrelHttpServer have support for SNI?

**Comment by Tratcher** [comment]
That's the idea, will see how it goes.

**Comment by Eilon** [comment]
@DamianEdwards / @shirhatti / @Tratcher - is this critical for Preview2?

**Comment by Tratcher** [comment]
Yes. We're trying to take a new CoreFx build today to unblock it.

**Comment by Eilon** [comment]
Got it, thanks!
