### ISSUE TITLE
Abstraction layer for Windows Service and systemd?

### ISSUE THREAD

**Issue by fbrier** [aspnet/KestrelHttpServer#2358]
This is a question. I just finished getting my .NET Core ASP app deployed as a service, and thank you for [the help](https://github.com/aspnet/KestrelHttpServer/issues/2351). But I was trying something that might just not be possible - deploying the same app as a service under Ubuntu, [following instructions to deploy it as a service using systemd](http://pmcgrath.net/running-a-simple-dotnet-core-linux-daemon). It core dumps. So just to confirm, the WebHostService class is Windows specific? It is not an abstraction layer for all OS(s)? If this is the case, is there a way to check the OS you are running on and instantiate a similar class for Linux that provides the same kind of lifecycle execution points, like OnStopped()? Thank you.

**Comment by davidfowl** [comment]
> So just to confirm, the WebHostService class is Windows specific? It is not an abstraction layer for all OS(s)?

That's correct. It depends on ServiceBase which is currently a type that works on windows only.

> If this is the case, is there a way to check the OS you are running on and instantiate a similar class for Linux that provides the same kind of lifecycle execution points, like OnStopped()? Thank you.

There's a way to check the OS you're running on via https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=netcore-2.0#System_Runtime_InteropServices_RuntimeInformation_IsOSPlatform_System_Runtime_InteropServices_OSPlatform_.

There is no equivalent of ServiceBase for linux (yet). See below for more details.

See https://github.com/dotnet/corefx/issues/25384.
