### ISSUE TITLE
Switch default transport to sockets

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KestrelHttpServer#2360]
Currently, it is our goal by 2.1.0 to make sockets the default transport. We made the [switch in early builds of 2.1.0](https://github.com/aspnet/KestrelHttpServer/pull/2100) but reverted that for preview1 (https://github.com/aspnet/KestrelHttpServer/issues/2220) due to performance issues.

Motivations:
 - broad platform support. Wherever managed sockets are supported, Kestrel should work. Doesn't require recompiling libuv to bring up a new OS.
 - source-build. (https://github.com/dotnet/source-build). In current form, Kestrel packages can't be produced in a source-build environment
 - ecosystem. Helps to drive improvement to the .NET sockets implementation, which benefits anyone else using managed sockets.

/cc @halter73 @davidfowl @muratg

**Comment by Suchiman** [comment]
@halter73 shouldn't the announcement prefer `Microsoft.AspNetCore.App` over `Microsoft.AspNetCore.All`?

**Comment by halter73** [comment]
@Suchiman Your edit is correct. That's the main thing that makes the change breaking.

**Comment by ondravondra** [comment]
Do the managed sockets have similar performance compared to libuv?

**Comment by NinoFloris** [comment]
@ondravondra yes that was the prerequisite for the switch and why preview1 still ships with libuv. I think it might even be.a little faster already

**Comment by nickalbrecht** [comment]
Just a heads up, the announcement has the tag `2.0.0-preview2`, not `2.1.0-preview2`

**Comment by natemcmaster** [comment]
@nickalbrecht thanks for spotting that. I updated the milestone on the announcement.

**Comment by kasper3** [comment]
> Do the managed sockets have similar performance compared to libuv?
>> @ondravondra yes that was the prerequisite for the switch and why preview1 still ships with libuv. I think it might even be.a little faster already

Couple of months ago, it was indicated that performance regressed when switching to sockets https://github.com/aspnet/KestrelHttpServer/issues/2220. Are there any before/after performance measurements to bring about concreteness to the mix?

**Comment by Suchiman** [comment]
@kasper3
There is http://aka.ms/aspnet/benchmarks
If you navigate to page 1 with the pager at the bottom, there's a graph that shows Socket I/O by over a million RPS ahead of Libuv.
If you go to page 2 it looks differently so i don't really understand how to read them.
