### ISSUE TITLE
UvReadCb allocating an Exception per request

### ISSUE THREAD

**Issue by rynowak** [aspnet/KestrelHttpServer#237]
I'm not sure what the root cause of this is because the exception is *never actually thrown*. Everything with the site seems to be working fine.

My profiler found this:
![image](https://cloud.githubusercontent.com/assets/1430011/10259194/51eb4b12-691a-11e5-9cfa-f6cfe6091ffc.png)

It's also allocating an `object[]` and calling `string.Concat` as well as a `UvException` which is what causes it to be so visible in the profile.

**Comment by rynowak** [comment]
Looks like the exception is passed here and then ignored - https://github.com/aspnet/KestrelHttpServer/blob/318f3b7145a3aa96a5d90aad4e192d121b1bfb48/src/Microsoft.AspNet.Server.Kestrel/Http/ListenerSecondary.cs#L62

**Comment by muratg** [comment]
Ugh that looks ugly. @halter73 @lodejard
