### ISSUE TITLE
Accept upgrade requests with content

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/KestrelHttpServer#2372]
Upgrade requests are allowed to have content in them, but currently we respond with a 400.

`Connection id ""0HLC5IN9VF1PO"" bad request data: ""Requests with 'Connection: Upgrade' cannot have content in the request body.""`

https://github.com/dotnet/corefx/issues/27912

**Comment by muratg** [comment]
Triage decision: we won't do this.
