### ISSUE TITLE
Broken test: RemoteIPv6Address

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2406]
This test [failed](http://aspnetci/viewLog.html?buildId=422648&buildTypeId=XPlat_Windows_Win8_Universe) with the following error:
```
======= Failed test run #1 ==========
System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.TestRemoteIPAddress(String registerAddress, String requestAddress, String expectAddress) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\KestrelHttpServer\test\Kestrel.FunctionalTests\RequestTests.cs:line 1650
--- End of stack trace from previous location where exception was thrown ---
```

Future instances of this failure will be tracked [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:NoSuccess400,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by Tratcher** [comment]
Partner bug. It looks like the new SocketHttpHandler is missing brackets for the IPv6 host header. I'll get a repro and file a corefx issue.

**Comment by kasper3** [comment]
@Tratcher, there is also a bug in zoneId that IPv6 parser recognize index to only be integer, however, it can be if_name: https://github.com/dotnet/corefx/issues/27529. Can that fix be addressed at the same time?

**Comment by Tratcher** [comment]
@kasper3 that's unrelated, zoneIds are not supposed to be transmitted in the host header.
