### ISSUE TITLE
Kestrel Libuv transport flow control and TCP Window Full / TCP ZeroWindow

### ISSUE THREAD

**Issue by zpodlovics** [aspnet/KestrelHttpServer#2411]
Hi,

I am benchmarking Kestrel with a WebSocket client, and I ran into a problem where the client will hang forever. According to the network traces client flood the server with websocket messages and it works for a while, until the tcp window reduced to zero than the client-server state will go into a weird state where the client will hang forever (at least new clients could connect to the server that seems works). How the tcp flow control supposed to work between the Kestrel Server and the WebSocketClient when everything is async? Would it be possible to have some kind of async backpressure notification (as some kind of callbacks) on both the server and both the client when the they not be able to send/receive more data?

**Update1**: it still have the same problem, when no min response data rate (but no exceptions) limit applied. 
The Program.cs:16 line should be replaced to:
.UseKestrel(options => options.Limits.MinResponseDataRate=null)

Please take a look at the attached screenshots too.

Related issues:
I guess similar tcp flow control problem exists for https://github.com/aspnet/KestrelHttpServer/issues/2171

Additional observations:
changing the linux kernel network parameters (net.core.rmem_max, net.core.wmem_max, net.ipv4.tcp_rmem, net.ipv4.tcp_wmem) (increasing the default rcv/snd buffers) will not solve anything it will only delay the problem a little bit, it will eventually reach the tcp window full state.

Example application (client+server) are attached and a network trace too (it could be viewed with wireshark).
[aspnetwebsocketbenchmark.zip](https://github.com/aspnet/KestrelHttpServer/files/1829772/aspnetwebsocketbenchmark.zip)

[aspnetwebsocketbenchmark_2018-03-20_1.pcapng.zip](https://github.com/aspnet/KestrelHttpServer/files/1829792/aspnetwebsocketbenchmark_2018-03-20_1.pcapng.zip)

TCP Sequence Numbers:

![screenshot from 2018-03-20 15-17-41](https://user-images.githubusercontent.com/8523206/37661678-41de3d94-2c4d-11e8-8396-0684817b6e20.png)

Wireshark screenshots:
![screenshot from 2018-03-20 15-18-48](https://user-images.githubusercontent.com/8523206/37661728-58ee175c-2c4d-11e8-8fca-43a98aaa3778.png)
![screenshot from 2018-03-20 15-19-01](https://user-images.githubusercontent.com/8523206/37661738-5b80a354-2c4d-11e8-890e-9b97ec595254.png)

Server:

```
Hosting environment: Production
Content root path: /tmp/aspnetwebsocketbenchmark
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ws  
info: Microsoft.AspNetCore.Server.Kestrel[28]
      Connection id "0HLCEE0CSQB7N", Request id "0HLCEE0CSQB7N:00000001": the connection was closed becuase the response was not read by the client at the specified minimum data rate.
info: Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv[14]
      Connection id "0HLCEE0CSQB7N" communication error.
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -125 ECANCELED operation canceled
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLCEE0CSQB7N", Request id "0HLCEE0CSQB7N:00000001": An unhandled exception was thrown by the application.
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.TimeoutException: The operation has timed out.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<EnsureBufferContainsAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetWebSocketBenchmark.Server.Startup.<Echo>d__2.MoveNext() in /tmp/aspnetwebsocketbenchmark/src/AspNetWebSocketBenchmark.Server/Startup.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetWebSocketBenchmark.Server.Startup.<<Configure>b__1_0>d.MoveNext() in /tmp/aspnetwebsocketbenchmark/src/AspNetWebSocketBenchmark.Server/Startup.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 7621.6606ms 101 
```

Client:
```
Press any key to stop.
MessageCount: 100000 
MessageCount: 200000 
ConnectAndSendAsync Exception: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to transfer data on the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.ManagedWebSocket.<SendFrameFallbackAsync>d__56.MoveNext()
   at System.Net.WebSockets.ManagedWebSocket.<SendFrameFallbackAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNetWebSocketBenchmark.Client.Program.<ConnectAndSendAsync>d__0.MoveNext() in /tmp/aspnetwebsocketbenchmark/src/AspNetWebSocketBenchmark.Client/Program.cs:line 22 

```

System: Ubuntu 16.04 x86_64 with 4.13-lowlatency kernel

Packages:
```
ii  dotnet-host                                                 2.1.0-preview1-26216-03-1                                   amd64        Microsoft .NET Core Host - 2.1.0 Preview 1
ii  dotnet-hostfxr-2.0.5                                        2.0.5-1                                                     amd64        Microsoft .NET Core Host FX Resolver - 2.0.5 2.0.5
ii  dotnet-hostfxr-2.0.6                                        2.0.6-1                                                     amd64        Microsoft .NET Core Host FX Resolver - 2.0.6 2.0.6
ii  dotnet-runtime-2.0.5                                        2.0.5-1                                                     amd64        Microsoft .NET Core Runtime - 2.0.5 Microsoft.NETCore.App 2.0.5
ii  dotnet-runtime-2.0.6                                        2.0.6-1                                                     amd64        Microsoft .NET Core Runtime - 2.0.6 Microsoft.NETCore.App 2.0.6
ii  dotnet-runtime-deps-2.1.0-preview1-26216-03                 2.1.0-preview1-26216-03-1                                   amd64        dotnet-runtime-deps-2.1.0-preview1-26216-03 2.1.0-preview1-26216-03
ii  dotnet-sdk-2.1.4                                            2.1.4-1                                                     amd64        Microsoft .NET Core SDK - 2.1.4

```

Thanks for your help!

**Comment by benaadams** [comment]
Your client has no receives, so isn't receiving data which will cause a backlog

**Comment by benaadams** [comment]
You could also collate server receives into single sends as follows
```csharp
private async Task Echo(HttpContext context, WebSocket webSocket)
{
    var buffer = new byte[1024 * 4];
    WebSocketReceiveResult result;
    var closed = false;
    while (true)
    {
        var endOfMessage = false;
        var length = 0;
        while (true)
        {
            result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer, length, buffer.Length - length), CancellationToken.None);
            endOfMessage = result.EndOfMessage;
            length += result.Count;
            closed = result.CloseStatus.HasValue;
            if (endOfMessage || closed || length >= buffer.Length)
            {
                // Complete message, receive buffer full or closed
                break;
            }
        }

        if (!closed)
        {
            await webSocket.SendAsync(new ArraySegment<byte>(buffer, 0, length), result.MessageType, endOfMessage, CancellationToken.None);
        }
        else
        {
            // Closed
            break;
        }
    }

    await webSocket.CloseAsync(result.CloseStatus.Value, result.CloseStatusDescription, CancellationToken.None);
}
```

**Comment by zpodlovics** [comment]
Thanks for your help and the idea to have a collated response! If I understand correctly websocket should be full duplex, therefore sending should work without receive call (ping/pong control messages still send/received). With a small Task.Delay on the receive loop the send only client works correctly (as it will not reach the tcp full window/zerowindow state).

According to this documentation the browser websocket client have a bufferedamount property:
https://www.w3.org/TR/websockets/#dom-websocket-bufferedamount

Nodejs  server provide a callback when the real sending happened:
https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_socket_write_data_encoding_callback

Jetty server provide a callback when the real sending happened:

http://download.eclipse.org/jetty/stable-9/apidocs/org/eclipse/jetty/websocket/api/RemoteEndpoint.html#sendBytes-java.nio.ByteBuffer-org.eclipse.jetty.websocket.api.WriteCallback-

Is it possible to have something like to this at the server side to handle the cases when the server send the websocket data faster than the client could receive?

I guess the client websocket flow control (eg.: with a callback) will be an another issue in corefx.

**Comment by benaadams** [comment]
There are no receives in the client, so its receive buffer fills and the server will stop sending
```csharp
async static Task ConnectAndSendAsync(ClientWebSocket ws, System.Uri uri, int reportPeriod, CancellationToken ct)
{
    try 
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes("echo");
        var segment = new System.ArraySegment<byte>(bytes);
        await ws.ConnectAsync(uri, ct);
        var messageCount = 0;
        while (!ct.IsCancellationRequested && WebSocketState.Open == ws.State && !ws.CloseStatus.HasValue)
        {
            await ws.SendAsync(segment,WebSocketMessageType.Text,true,ct);
            messageCount++;
            if (0 == messageCount % reportPeriod) 
            {
                System.Console.WriteLine("MessageCount: {0} ",messageCount);
            }
        }

        await ws.CloseAsync(ws.CloseStatus.Value,ws.CloseStatusDescription,CancellationToken.None);
    } 

    catch (WebSocketException e) 
    {
        System.Console.WriteLine("ConnectAndSendAsync Exception: {0} ", e);
    }
}
```

**Comment by zpodlovics** [comment]
Well, when the message flow reversed (server send messages in loop to the client) it works correctly.  It seems that the libuv vs native socket handle the tcp backpressure (tcp window full / tcp zerowindow) differently. I will create an issue in corefx about the clientwebsocket tcp backpressure. Please do not close this issue yet, I will get back later to test these examples with kestrel 2.1 native sockets. If Kestrel 2.1 works correctly it's a clientwebsocket only thing, otherwise it's related to the new native sockets.

I know, this is seems to be a corner case usage. But with lot's of users the messaging requirements could be really high for a single connection too (I already have message processing core that have to handle millions of messages per second).

Handling millions of connections was already possible with amost a decade ago:
https://www.metabrew.com/article/a-million-user-comet-application-with-mochiweb-part-1

[aspnetwebsocketbenchmarkserversend.zip](https://github.com/aspnet/KestrelHttpServer/files/1830407/aspnetwebsocketbenchmarkserversend.zip)

**Comment by zpodlovics** [comment]
You are right, it was the client receive backlog. My expectation was incorrect in this case. Without the server part SendAsync the client work perfectly.
