### ISSUE TITLE
Unable to load DLL 'libuv': The specified module or one of its dependencies could not be found.

### ISSUE THREAD

**Issue by mihevc** [aspnet/KestrelHttpServer#2415]
I'm building my docker image using the alpine docker image and I get this message when I run the docker container on linux.  The code works on windows outside of docker.

# Dockerfile

FROM microsoft/dotnet:2.1-sdk-alpine

RUN apk update \
	&& apk add libuv

#Set the Working Directory
WORKDIR /app

#Configure the listening port to 80
ENV ASPNETCORE_URLS http://*:80
EXPOSE 80

#Start the app
ENTRYPOINT ["dotnet", "mycode.dll"]

I tried adding Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv but it didn't make any difference.  I also commented out the entry point and ran the container, went into the container and verified that libuv was install.  Then, I ran the app inside the container and got the same error.

**Comment by Tratcher** [comment]
@natemcmaster

**Comment by natemcmaster** [comment]
Known issue - https://github.com/aspnet/libuv-package/issues/23.

We worked around this in the microsoft/aspnetcore docker image already (currently in nightlies only via `microsoft/aspnetcore-nightly:2.1.0-preview2-alpine`

https://github.com/aspnet/aspnet-docker/blob/dev/2.1/alpine/amd64/runtime/Dockerfile#L6-L9
```Dockerfile
# Workaround https://github.com/aspnet/libuv-package/issues/23
# Install libuv globally and link it so coreclr can laod it
RUN apk add --no-cache libuv \
    && ln -s /usr/lib/libuv.so.1 /usr/lib/libuv.so
```
