### ISSUE TITLE
Uncommon memory consumption with Sockets (i.e. a memory leak)

### ISSUE THREAD

**Issue by sebastienros** [aspnet/KestrelHttpServer#2416]
I updated the reliability tests to use Sockets now that it's the default transport.

The memory consumption seems to grow, I would wait for more days to make any conclusion.

![image](https://user-images.githubusercontent.com/1165805/37791801-5af0ff76-2dc7-11e8-8183-4e968954b861.png)

The first line is with Libuv, the one on the right is with Sockets.

NB: Right now I can't track the changes as EF has an issue on the latest bits.

**Comment by Tratcher** [comment]
How long did this take to reproduce? Or is this a chart across multiple builds?

**Comment by Tratcher** [comment]
Can you link to the test you were using?

**Comment by sebastienros** [comment]
DbFortunesMvcEf scenario in benchmarks.
It's a long run, the right one lasted a little more than one day. The left one is over many days.

**Comment by halter73** [comment]
Why is the left graph so stable. Is that using the libuv transport instead of sockets? A horizontal axis and a vertical axis starting at 0 would be nice.

**Comment by sebastienros** [comment]
> The first line is with Libuv, the one on the right is with Sockets.

>  A horizontal axis and a vertical axis starting at 0 would be nice.

https://aka.ms/aspnet/benchmarks

Please help yourself

**Comment by halter73** [comment]
Cool. So we're looking at a zoomed in version the following graph from page 6 of 8?

![image](https://user-images.githubusercontent.com/54385/37800646-cbd48424-2de0-11e8-9c82-d6f82d228d69.png)

How do I know which color line corresponds with which configuration without asking you? I only see time-related info in the hover text.

**Comment by muratg** [comment]
@sebastienros could you help with reading the graph?  Thanks.

**Comment by sebastienros** [comment]
I'll update the graph when I have more log, which hasn't run for many days, then I will explain.

**Comment by sebastienros** [comment]
Update: it's getting worse. 
I took a memory dump this morning, and will do another one this afternoon.

![image](https://user-images.githubusercontent.com/1165805/38206912-ffb4924c-3660-11e8-9e58-c42291bd6096.png)

**Comment by sebastienros** [comment]
Details on current run: 

```
[08:11:42.717] SDK:                         2.2.0-preview1-007522
[08:11:42.717] Runtime:                     2.1.0-preview2-26325-03
[08:11:42.717] ASP.NET Core:                2.1.0-preview3-32064
```

**Comment by DamianEdwards** [comment]
Can we figure out if this affects preview2 bits please? I think the runs are on latest (so preview3 given how long ago we branched) but given the leak shows up as soon as we switched to sockets there's a good chance it affects preview2 as well (which is obviously super high priority).

**Comment by DamianEdwards** [comment]
@sebastienros can you share dump info as soon as you have it please?

**Comment by sebastienros** [comment]
Looks good after an hour of measures:

![image](https://user-images.githubusercontent.com/1165805/38284913-8a66a58a-3772-11e8-9f46-40ec62920e7c.png)

Will update tomorrow

**Comment by muratg** [comment]
:relieved: phew.

**Comment by Eilon** [comment]
Is the work for this done? If not, what is left for Preview2?

**Comment by halter73** [comment]
@Eilon Yes it is.

**Comment by halter73** [comment]
Way ahead of you ;)
