### ISSUE TITLE
chunked transfer encoding response

### ISSUE THREAD

**Issue by srininz77** [aspnet/KestrelHttpServer#2417]
Why does Kestrel always add transfer-encoding: "chunked" response header? IIS doesn't do it. Is this by design or a bug?

**Comment by Tratcher** [comment]
By design. If the application doesn't specify a content-length then the server must either buffer the content or send it as chunked. ASP.NET Core servers do not buffer the full content. IIS has some buffering quirks with response compression, but otherwise it doesn't buffer responses either.

**Comment by srininz77** [comment]
Thanks
