### ISSUE TITLE
Delay loading the default development certificate

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2422]
Today Kestrel first tries to load the default development certificate and assign that to all new HttpsConnectionAdapterOptions.ServerCertificate. 

This shows up as a measurable % of startup time. It also causes log noise.

It also causes additional complexities with the new SNI support were the cert and the cert selector are mutually exclusive. This may need to get refactored as part of https://github.com/aspnet/KestrelHttpServer/issues/2357

**Comment by muratg** [comment]
Costing?

**Comment by davidfowl** [comment]
Once we have the SNI callback then we can use it here.

**Comment by Tratcher** [comment]
No, this is later than we'd want, and invoked per connection. You want to load the cert as the server starts, but only if no other cert was provided.

**Comment by davidfowl** [comment]
Disagree. You want to load the cert only if you’re using https.

**Comment by Tratcher** [comment]
Yes, but inside the SNI callback is way too late. Do it when you set up HTTPS. One of these two places seems the most likely:
https://github.com/aspnet/KestrelHttpServer/blob/a37fa83aee400f621b1f19fca6a777bd3d804f6f/src/Kestrel.Core/ListenOptionsHttpsExtensions.cs#L214
https://github.com/aspnet/KestrelHttpServer/blob/a37fa83aee400f621b1f19fca6a777bd3d804f6f/src/Kestrel.Core/Internal/HttpsConnectionAdapter.cs#L39
