### ISSUE TITLE
[Discussion] Why is ConnectionContext an abstract class and not an interface?

### ISSUE THREAD

**Issue by MuleaneEve** [aspnet/KestrelHttpServer#2430]
This is just a quick question to understand this choice.
I tried to search through the old issues, but couldn't find a discussion on that. I saw that [it used to be IConnectionContext](https://github.com/aspnet/KestrelHttpServer/blob/f3745608af5020eaa3e83cd5a21aeaa2b85b618b/src/Kestrel.Transport.Abstractions/Internal/IConnectionContext.cs), so I'm sure it was discussed somewhere.

By the way, nice work with the ongoing BedRock refactoring :thumbsup:

**Comment by davidfowl** [comment]
We expect to add more methods and properties to this type. We're following a similar pattern to what HttpContext has. In fact one I can think of that we need to add is `Abort()`. HttpContext is basically the set of things we think are first class for Http, the ConnectionContext is the moral equivalent for connection level things.

**Comment by MuleaneEve** [comment]
Thanks for the quick reply.

As far as I understand, the value of an abstract class is that you can provide default implementation to properties/methods. Is that something you are considering? Would extension methods be an interesting alternative?

The equivalence with HttpContext doesn't seem enough on its own to justify this decision which has an implementation cost (being unable to implement ConnectionContext with a different base class, since C# doesn't support multiple base classes).

**Comment by davidfowl** [comment]
> As far as I understand, the value of an abstract class is that you can provide default implementation to properties/methods. Is that something you are considering? Would extension methods be an interesting alternative?

Yes we do. That's one of the benefits, the other is that it can be expanded in the future (we can add properties). 

> The equivalence with HttpContext doesn't seem enough on its own to justify this decision which has an implementation cost (being unable to implement ConnectionContext with a different base class, since C# doesn't support multiple base classes).

I don't see it that way. Not many people will need to implement the base class.

**Comment by MuleaneEve** [comment]
I'm still not clear on the reasoning, but since it is still very early, I will wait and see how things evolve.

**Comment by davidfowl** [comment]
@MuleaneEve thats fair, do you have a scenario in mind where you think you'd need to implement it? Nobody implements their own HttpContext right?

**Comment by khellang** [comment]
It's basically the same reason interfaces are dreaded across the entire BCL; there's no non-breaking way to rev them. With abstract classes, you can add virtual members with default implementations and avoid breaking everyone implementing/deriving it.

**Comment by MuleaneEve** [comment]
@davidfowl I expect ConnectionContext implementations to be a lot more popular since this new Connections layer makes is so much easier to write your own protocol (whereas very few people would write their own HTTP implementation). And I hope that an ecosystem of libraries adding specialized features will be born.

@khellang What's a practical example where that could happen and make sense?
The scenarios that I can think of would involve "specializing" the ConnectionContext which is typically done with a subclass.

In any case, I can't think of any downside today that can't be worked around fairly easily (even the inheritance issue can be solved with an adapter pattern).

**Comment by davidfowl** [comment]
> @davidfowl I expect ConnectionContext implementations to be a lot more popular since this new Connections layer makes it so much easier to write your own protocol (whereas very few people would write their own HTTP implementation). And I hope that an ecosystem of libraries adding specialized features will be born.

Thats the wrong side though, you don't implement a ConnectionContext to implement a protocol, you consume it. You implement a ConnectionContext when you want to implement the transport layer itself. If you were the person writing the serial port transport, then you'd need to derive. If you're the person implementing MQTT you consume a ConnectionContext. That might be where there's confusion.

**Comment by MuleaneEve** [comment]
Sorry, that's what I meant, a custom transport :)
It is indeed less likely than a custom protocol, but it should still happen than custom HttpContexts.

And, even for already implemented transports, I can see some people forking them to "optimize" their behaviors as they see fit.

**Comment by davidfowl** [comment]
> Sorry, that's what I meant, a custom transport :)
It is indeed less likely than a custom protocol, but it should still happen more often than custom HttpContexts.

I think there will be a lot less than you think *and* I don't think the abstract base class will be a problem.

> And, even for already implemented transports, I can see some people forking them to "optimize" their behaviors as they see fit.

Sounds fine, but I'm not seeing a real problem. 

> And, even for already implemented transports, I can see some people forking them to "optimize" their behaviors as they see fit.

Again, this seems completely fine. I don't think interface vs abstraction base class matters here in the slightest.

**Comment by MuleaneEve** [comment]
Like I said in my first post, I just wanted to understand this choice :)

I can see the pros & cons of both approaches, and I can't predict which one would end up being better.

**Comment by davidfowl** [comment]
Time will tell. Lets meet back here in 2 years and see where we landed. If people jump on this thing then it'll be a good problem to have 😄

**Comment by MuleaneEve** [comment]
👍
