### ISSUE TITLE
Move Kestrel benchmarks to this repository

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2439]
Move the platform benchmark and plaintext to this repository. It'll make testing changes a bit easier.

/cc @halter73 @sebastienros

**Comment by sebastienros** [comment]
Or maybe you need a custom benchmark application here too, dedicated to kestrel and the flags you need for local testing? And without having to bother with database, ...

**Comment by davidfowl** [comment]
True, it doesn't need to replace anything per se but it would be nice to avoid duplication. We can use this application.

https://github.com/aspnet/KestrelHttpServer/blob/46ab09ca363f22d37dc326c16d757c81b89f1f40/samples/PlaintextApp/Startup.cs

At this point I wonder if we should just consider benchmarks to be the techempower application and each of the repos should just own their own benchmarks.

**Comment by sebastienros** [comment]
Yes, I think so, we should have the TE scenarios in the app, and have other ones have custom logic. Like IIS, DB, Jil/Utf8/Json, then if we think they make sense for TE just port them over.

We can still add all these specific app results in the charts.

**Comment by davidfowl** [comment]
Right, I would also argue that the middleware tests like response caching should be in their own repositories.

**Comment by muratg** [comment]
@sebastienros I was told that you have a PR on this already.

**Comment by unknowncloud** [comment]
go
	Go source files.
.c, .h
	C source files.
	If the package uses cgo or SWIG, these will be compiled with the
	OS-native compiler (typically gcc); otherwise they will
	trigger an error.
.cc, .cpp, .cxx, .hh, .hpp, .hxx
	C++ source files. Only useful with cgo or SWIG, and always
	compiled with the OS-native compiler.
.m
	Objective-C source files. Only useful with cgo, and always
	compiled with the OS-native compiler.
.s, .S
	Assembler source files.
	If the package uses cgo or SWIG, these will be assembled with the
	OS-native assembler (typically gcc (sic)); otherwise they
	will be assembled with the Go assembler.
.swig, .swigcxx
	SWIG definition files.
.syso
	System object files.

**Comment by davidfowl** [comment]
@sebastienros Can you close this bug?
