### ISSUE TITLE
Use DllImport for Libuv native binaries

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#244]
/cc @moozzyk

**Comment by moozzyk** [comment]
Depends on https://github.com/aspnet/dnx/issues/402

**Comment by muratg** [comment]
@moozzyk where are we with this one?

**Comment by moozzyk** [comment]
@muratg - this worked on Friday. Need to retest after latest changes to native lib loading and possibly change a layout a little bit - "osx" is not a valid fallback anymore. One breaking change is that it will require to link the libuv as `libuv.so` and not `libuv.so.1` on Linux (I think this is why Travis is failing on my branch). Will try to send a PR for this but ultimately in the worst case RC1 can ship with what we have right now.

**Comment by moozzyk** [comment]
Fixed in d4853f9b7c31a28cecac8ac7e965f8f2f783c06b. Needs an announcement for libuv name change on Linux

**Comment by muratg** [comment]
@moozzyk Please post the announcement issue when you're back. That would be still before RC1 release.
