### ISSUE TITLE
Make Kestrel TryAdd when adding it's IServer implementation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/KestrelHttpServer#2440]
For ANCM in-proc to work with scenarios like:
```c#
WebHostBuilder.CreateDefaultWebHostBuilder() // which calls UseKestrel() and UseIISIntegration();
    .UseKestrel();
```
we need the call to UseIISIntegration to always add it's IServer implementation rather than Kestrel overriding it. 

As we want out-of-proc and in-proc to work without code changes, we will need [Kestrel to TryAdd it's server implementation](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel/WebHostBuilderKestrelExtensions.cs#L35).

cc/ @davidfowl @pakrym @Tratcher

**Comment by muratg** [comment]
Who's doing this?

**Comment by Tratcher** [comment]
You tell us 😁

**Comment by Tratcher** [comment]
Side note: Clone this bug for HttpSys.

**Comment by Tratcher** [comment]
Pushback: This pattern won't work for HttpSys and we'd like to use a consistent patern.

**Comment by muratg** [comment]
"Needs-design"?

**Comment by muratg** [comment]
What's happening for preview2 if anything?  @Tratcher @davidfowl @jkotalik do we need to get into a room and talk again?

**Comment by jkotalik** [comment]
@davidfowl @Tratcher implementing IDefaultServer feature right now would be a bit rushed in this timeline, for now we can make it when IISIntegration is called inproc, it can be called multiple times.

**Comment by pakrym** [comment]
We decided not to do IDefaultServer or IServerSelector, just make UseIISIntegration override IServer every time.

**Comment by muratg** [comment]
@pakrym who's doing that?

**Comment by Tratcher** [comment]
https://github.com/aspnet/IISIntegration/issues/741 @pakrym ?
