### ISSUE TITLE
Kestrel randomly crashes

### ISSUE THREAD

**Issue by lkfr** [aspnet/KestrelHttpServer#2441]
We are facing a Kestrel-related issue with an ASP.NET Core 2.0 app running in an Azure App Service.
The server suddenly stops responding and we see a huge number of HTTP 502.3 errors.
The problem occurs a few times a day (during peak hours).

We have looked at a few metrics before the problem occurs and CPU and memory usage are OK, network connections look fine. App Insight does not report anything wrong in the app and the only thing we see in the app logs is related to the app restart: Application 'MACHINE/WEBROOT/APPHOST/X' started process 'xyz' successfully and is listening on port 'xyz'

It should be noted that our app has a lot of HTTP dependencies and we rely heavily on HttpClient.
However we do use only one instance of HttpClient and we think we got the calls right:

Usage 1
```
var client = HttpGateway.Client;
string xml = await client.GetStringAsync(url);
```

Usage 2
```
using (HttpRequestMessage request = CreateRequestMessage())
{
	var client = HttpGateway.Client;
	using (var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, context.RequestAborted))
	{
		// Check response headers
	
		// Get response content
		string content = await response.Content.ReadAsStringAsync();
		
		// More processing
	}
}
```
We have not looked at `ServicePointManager.DefaultConnectionLimit` but it seems that `WinHttpHandler.MaxConnectionsPerServer` is now used and has a default value of `int.MaxValue`.

How can we proceed to understand exactly what is going on and to solve this issue? Needless to say we are fully committed on this as this is a really serious issue in our mind.

Would stdout logging in Kestrel enable us to see the cause of the problem when it occurs? Which log level should we set (we want to keep the log size under control as we have a huge number of requests)?

Any help would be really appreciated.

**Comment by lkfr** [comment]
We have enabled logging with a log level set to warning but unfortunately it does not produce anything before the crash.

We have managed to get a crash dump and it shows there is something wrong in the following stack frame:

```
Thread   9
Current frame: rpcrt4!NdrNsSendReceive + 0x1202
ChildEBP RetAddr  Caller, Callee
0c04f8e8 75473b12 rpcrt4!NdrNsSendReceive + 0x1202, calling ntdll!RtlRaiseException
0c04f924 76fa211e ntdll!_SEH_epilog4_GS + 0xa, calling ntdll!__security_check_cookie
0c04f928 76f59636 ntdll!TppCleanupGroupMemberDestroy + 0xef, calling ntdll!_SEH_epilog4_GS
0c04f948 7544149e rpcrt4!I_RpcGetSystemHandle + 0xbfe, calling rpcrt4!NdrNsSendReceive + 0x11c0
0c04f978 754413cd rpcrt4!I_RpcGetSystemHandle + 0xb2d, calling ntdll!NtAlpcSendWaitReceivePort
0c04f980 754411e0 rpcrt4!I_RpcGetSystemHandle + 0x940, calling rpcrt4!I_RpcGetSystemHandle + 0xb3a
0c04f99c 754416ba rpcrt4!I_RpcGetSystemHandle + 0xe1a, calling rpcrt4!I_RpcGetSystemHandle + 0x8cd
0c04f9b8 75440b3b rpcrt4!I_RpcGetSystemHandle + 0x29b
0c04f9ec 754409cc rpcrt4!I_RpcGetSystemHandle + 0x12c, calling rpcrt4!I_RpcGetSystemHandle + 0x1e0
0c04fa00 75440874 rpcrt4!RpcAsyncCancelCall + 0x54
0c04fa18 723d3ab8 winhttp!PROXY_RESOLVE_HANDLE_OBJECT::CompleteClientGetProxyForUrl + 0x345be, calling rpcrt4!RpcAsyncCancelCall
0c04fa40 7239f6df winhttp!PROXY_RESOLVE_HANDLE_OBJECT::OnMultiWaitComplete + 0x1f, calling winhttp!PROXY_RESOLVE_HANDLE_OBJECT::CompleteClientGetProxyForUrl
0c04fa58 7239f228 winhttp!WaitForMultiObjectsCallback + 0x7b, calling winhttp!PROXY_RESOLVE_HANDLE_OBJECT::OnMultiWaitComplete
0c04fa80 7239fc4f winhttp!MULTI_WAIT_CONTEXT::OnWaitComplete + 0xf, calling winhttp!WaitForMultiObjectsCallback
0c04fa8c 7239f161 winhttp!HTTP_THREAD_POOL::_WaitCallback + 0x81, calling winhttp!MULTI_WAIT_CONTEXT::OnWaitComplete
0c04fac0 76f46435 ntdll!TppExecuteWaitCallback + 0x7a
0c04fae4 76f589e5 ntdll!TppCancelTimer + 0x51, calling ntdll!__security_check_cookie
0c04fb2c 76f4637a ntdll!TppWaitCompletion + 0x8a, calling ntdll!TppExecuteWaitCallback
0c04fb48 76f48d3f ntdll!TppDirectExecuteCallback + 0x9f
0c04fb7c 76f56cb1 ntdll!TppWorkerThread + 0x541, calling ntdll!TppIopExecuteCallback
0c04fb84 76f56d96 ntdll!TppWorkerThread + 0x626
0c04fd20 73e162c4 kernel32!BaseThreadInitThunk + 0x24
0c04fd34 76f80f79 ntdll!__RtlUserThreadStart + 0x2f
0c04fd7c 76f80f44 ntdll!_RtlUserThreadStart + 0x1b, calling ntdll!__RtlUserThreadStart
```
`!analyze -v`  points to `PROXY_RESOLVE_HANDLE_OBJECT::CompleteClientGetProxyForUrl`

We assume the origin of the problem does not come from these system dlls but rather from something that we are doing wrong but we are not used to .net crash dump analysis so not an easy task for us to find out the root cause.

**Comment by muratg** [comment]
@lkfr Not much detail to go on this as it stands.  

Was that a dump of w3wp process?  Is there a way to create a simple repro app?

**Comment by halter73** [comment]
Do you ever not call `await response.Content.ReadAsStringAsync();` because of a non successful status code or something? If so, it's important to dispose `response`, otherwise the underlying connection will stay open because of the `HttpCompletionOption.ResponseHeadersRead` option. It's probably best just to dispose `response` regardless.

**Comment by lkfr** [comment]
@muratg This is a crash dump of the dotnet process. We are going to try to create a repro app and to simulate high traffic load.

@halter73 If we get a non successful status code we throw an exception and `await response.Content.ReadAsStringAsync();` is not called. Does that mean the response is not disposed (even if we wrap it in a using block)?

**Comment by halter73** [comment]
It looks like you're wrapping the HttpRequestMessage in a using block, but you have to dispose the response as well. Normally it wouldn't matter that you don't dispose the response, but the `HttpCompletionOption.ResponseHeadersRead` means you either have to read the entire response it dispose it (or both).

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
