### ISSUE TITLE
302 redirect on apache loses https, returns as http

### ISSUE THREAD

**Issue by CoderJason123** [aspnet/KestrelHttpServer#2443]
Hello.  I've spent some time trying to narrow this down a bit more, but here is what I have.

I am using aspnet core 2.0 on apache (all the latest versions) on ubuntu 16.04.  After my cookie times out or if I manually delete my auth cookie from the browser, and make an ajax call, the 302 is issued, as it should be.

However, my connection starts as https.  The redirect is returned as http, not https.  Then of course things go downhill after that.  

I have followed the instructions at
[https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?tabs=aspnetcore2x](url)

Notes:
I am using aspnet core identity module as well.  If you strongly feel this is not a kestrel issue, I will post this on their GitHub issue list.  So my SSL cert is handled thru apache and I'm running kestrel on the default port.

**Comment by CoderJason123** [comment]
I failed to read the section here.."When using any type of authentication middleware, the Forwarded Headers Middleware must run first. This ordering ensures that the authentication middleware can consume the header values and generate correct redirect URIs."  I am sure this is the cause.

**Comment by Tratcher** [comment]
We just wrote the doc for this: https://github.com/aspnet/Docs/pull/5794

**Comment by CoderJason123** [comment]
I reviewed my code and saw that I have the forwarded headers there...i will need to investigate further from the link you just posted.

**Comment by CoderJason123** [comment]
@Tratcher - looking at that link, I don't fully understand.  Is there a code fix pending, is this just a description of the problem, sorry not following.

**Comment by Tratcher** [comment]
Your app likely needs a configuration update. Adding the middleware, adding x-fowarded-proto headers in Apache, etc..

**Comment by CoderJason123** [comment]
Ok.  I found my way to one of the links which described     RequestHeader set X-Forwarded-Proto "https".  Now, I'm not directly using a balancer, which was the context of the article.  Can i give this a try in my virtual host section?  I'm not seeing any code changes on my side since i already have forwarded headers unless you are saying I need more.

**Comment by Tratcher** [comment]
I don't know how you've configured it. See the debug section at the bottom of the linked doc.

**Comment by CoderJason123** [comment]
I already have forwarded headers, and the debug section didn't really talk about what to configure.  But, none the less, by adding that value to virtual host and enabling the headers module in apache, the problem is gone!  Thank you!
