### ISSUE TITLE
Make Kestrel work with alternative MemoryPool implementations

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#2449]
Today we make some assumptions that the underlying block size will be 4K and swapping out with another pool (like the default array pool) makes the tests fail.

/cc @jkotas

**Comment by jkotas** [comment]
cc @GrabYourPitchforks

**Comment by stephentoub** [comment]
I assume nothing in Kestrel assumes the Memory is already pinned and always calls Retain/Pin when needed?

**Comment by davidfowl** [comment]
> I assume nothing in Kestrel assumes the Memory is already pinned and always calls Retain/Pin when needed?

Correct. But I'm seeing tons of errors.  Up to ~200 errors.

**Comment by davidfowl** [comment]
What's worse is that when I run the test that fail in isolation they pass 😄

**Comment by davidfowl** [comment]
Oh wait, I think I know what it is.

**Comment by davidfowl** [comment]
See https://github.com/aspnet/KestrelHttpServer/pull/2450

**Comment by davidfowl** [comment]
This is done
