### ISSUE TITLE
Regression on Sockets Platform

### ISSUE THREAD

**Issue by sebastienros** [aspnet/KestrelHttpServer#2455]
See this graph for the details

![image](https://user-images.githubusercontent.com/1165805/38206026-b0de7b36-365d-11e8-82c6-7475ac9740bf.png)

Black line is Libuv Plaintext Platform,

**Comment by sebastienros** [comment]
Note that this is only visible on Physical Windows. Doesn't repro on Cloud Windows or Linux.
This might be an environment issue, so if nothing changed around this time then we can discard this issue.

**Comment by muratg** [comment]
@sebastienros Do you have more data on this now? Does it look like an infra/environment issue or no?

@DamianEdwards FYI

**Comment by sebastienros** [comment]
So far I have no more information, what I can add is that I found a similar regression on MvcPlaintext, on the same date, also only on Windows Physical.

![image](https://user-images.githubusercontent.com/1165805/38280010-d9ab3130-3757-11e8-8d23-dd86f769d2ab.png)

I will try to run the benchmark on two different aspnet version to see if I can reproduce it and confirm it's actually some regression and not just the machine that became slower.

**Comment by muratg** [comment]
Sounds good, thanks!

**Comment by sebastienros** [comment]
I identified the issue to be coming from the runtime. Here are the results with only changing the runtime version, using a fixed aspnet version. So nothing to do with Kestrel. I will open another issue once I find more info.

|             Runtime |     RPS | CPU (%) | Memory (MB) | Avg. Latency (ms) | Startup (ms) | First Request (ms) | Latency (ms) |
| ----------------------- | ------- | ------- | ----------- | ----------------- | ------------ | ------------------ | ------------ |
| 2.1.0-preview2-26314-02 | 468,169 |      98 |         392 |               5.9 |          501 |              321.5 |          0.5 |
| 2.1.0-preview2-26325-03 | 442,728 |      97 |         393 |               6.2 |          513 |              324.1 |          0.6 |
