### ISSUE TITLE
Kestrel non-pipelined performance regressed by recent changes

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/KestrelHttpServer#246]
The changes to the flow-control model of Kestrel made recently that increased the pipelined performance (aka the plaintext benchmark) seem to have regressed the non-pipelined performance.

Prior to the changes we were seeing >130K RPS for non-pipelined plaintext benchmark runs. Now we're seeing ~64K RPS.

Note that we're currently only running with one IO thread due to #232 so that's likely affecting the results too.

created by @DamianEdwards

**Comment by muratg** [comment]
Just talked to @lodejard.  Moving is issues to RC2.

**Comment by lodejard** [comment]
@damianedwards is this still relevant?
