### ISSUE TITLE
Investigate HTTP/2 behavior for RequestAborted and Abort

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2462]
For Http/1.x RequestAborted is used to detect early disconnects and Abort is used to force them.

For HTTP/2 requests can be multiplexed over a single connection and it's possible to terminate individual requests while leaving the connection active. Investigate how kestrel surfaces this behavior and if RequestAborted and Abort can be adapted accordingly. We may also need to introduce a lower level connection Abort API to kill the underlying connection.

Mirrors https://github.com/aspnet/IISIntegration/issues/753

**Comment by muratg** [comment]
Backlogging until HTTP/2 support is back.

**Comment by Tratcher** [comment]
Incoming RST_STREAM frames are used to signal abort on the associated request:
https://github.com/aspnet/KestrelHttpServer/blob/ee86e97b6ba561e9c4ee13e53d44551f7e759a6a/src/Kestrel.Core/Internal/Http2/Http2Connection.cs#L471-L474
I'll do some manual verification on this. Also, make sure this doesn't call user code that can block the main connection loop.

Followup: What about Reqeuest.Abort()? Does it terminate the stream or the connection?

**Comment by Tratcher** [comment]
Call stack:
Http2Connection.ProcessRstStreamFrameAsync
HttpProtocol.Abort
HttpProtocol.OnInputOrOutputCompleted (Offloads to new thread)
HttpProtocol.CancelRequestAbortedToken

Problem: This offload depends on ApplicationSchedulingMode.

**Comment by Tratcher** [comment]
On connection tear down all streams have RequestAborted called. Call stack:
Http2Connection.ProcessRequestsAsync - finally block
Http2Stream.Http2Abort
Http2Stream.OnInputOrOutputCompleted
HttpProtocol.OnInputOrOutputCompleted (Offloads to new thread)
HttpProtocol.CancelRequestAbortedToken

Problem: This offload depends on ApplicationSchedulingMode. Blocking abort on one stream could prevent it from being called on others.

**Comment by Tratcher** [comment]
Bug: Response headers and data are still sent after receiving a RST frame for a given stream, only the final end stream data frame is not sent. These should all be discarded. There are even (incorrect) tests for this.

**Comment by Tratcher** [comment]
Bug: The request stream is not unblocked when a RST frame is received.

**Comment by Tratcher** [comment]
Feature:
HttpContext.Abort is intended to reset the stream only. The connection can still be terminated via IConnectionLifetimeFeature.
```
                var connectionFeature = context.Features.Get<IConnectionLifetimeFeature>();
                connectionFeature.Abort();
```
This already works today.

**Comment by Tratcher** [comment]
Bug: HttpContext.Abort() does not sent a RST frame. After the fixes for the other bugs above, no response is sent at all and the client hangs waiting.
