### ISSUE TITLE
SNI callback doesn't have access to the IServiceProvider

### ISSUE THREAD

**Issue by anurse** [aspnet/KestrelHttpServer#2468]
It seems like it would be very useful for the SNI callback to be able to activate services from DI, but I don't see anywhere I can get a ServiceProvider. The `IFeatureCollection` is connection-level and doesn't contain a service provider. I know the RequestServices aren't available, but I presume there are singleton and transient services I could be able to activate.

**Comment by Tratcher** [comment]
Sounds like something that could be added to the feature collection.

**Comment by anurse** [comment]
Yep, that's what I was thinking.

**Comment by muratg** [comment]
Triage: We'll think about this if we hear more customer feedback.
