### ISSUE TITLE
Kestrel takes 2-3 seconds to shutdown if any connections have been made

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/KestrelHttpServer#247]
Kestrel is taking 2-3 seconds to shutdown (e.g. after Ctrl-C) if any connections have been made to it. This is causing the development experience in Visual Studio to be poor due to the long time it takes to get the server going again after making a code change.

## Repro steps
1. Start the server
1. Immediately Ctrl-C to end it without making a request
1. It exits immediately
1. Start the server again
1. Make a request from a browser then close the browser
1. Ctrl-C the kestrel server
1. It takes 2-3 seconds for the process to end

by @DamianEdwards

**Comment by muratg** [comment]
OK, let's investigate what we can do for Beta 8.

**Comment by halter73** [comment]
@muratg I tested the shalter/247 branch referenced above with the new WTE build. This seemed to reduce the time window where you could get a 502.3 response, but didn't eliminate it completely.

Bill thinks that the change to kill iisexpress on ctrl+f5 could fix the 502.3 issue as well, so I'm waiting on that change before doing any further work on this.

**Comment by muratg** [comment]
@halter73 Sounds good.  If WTE change can eliminate the need to do this in Beta 8, please move to RC1.

**Comment by muratg** [comment]
Assigning back to @halter73 as @cesarbs doesn't have cycles currently to work on this.   

@halter73 Please look into this when you're in-progress work is done as it's a bad developer experience problem.

**Comment by salerth** [comment]
Not sure if this is the same bug/related, but kestrel wont respond (at all) to CTRL+C after it has served at least 1 page on OSX + CoreCLR.  If I CTRL+C before serving a page it exits properly.

Mono works fine and exits at any time.

`dnx-coreclr-darwin-x64.1.0.0-rc2-16249`

**Comment by DamianEdwards** [comment]
Need for RC2
