### ISSUE TITLE
1000ms delay when only IPv4 address is used when specifying ListenOptions for Kestrel.

### ISSUE THREAD

**Issue by joshmackey** [aspnet/KestrelHttpServer#2470]
I've noticed that http requests to Kestrel take at least 1000ms if only a IPv4 endpoint is bound to. If a request normally takes 15ms, it will take 1015ms instead.

If you use `UseKestrel()` on its own, it automatically listens to the localhost IPv4 and IPv6 addresses. If you manually specify addresses using `KestrelServerOptions` but only specify a single `Listen` with an IPv4, then you see the bug. If you add a second endpoint that uses IPv6, the bug goes away.

Using a default ASP.NET Core 2 template from VS 2017:

No bug
```
.UseKestrel((options) =>
            {
                options.Listen(IPAddress.Loopback, 5000);
                options.Listen(IPAddress.IPv6Loopback, 5000);
            })
```

Bug
```
.UseKestrel((options) =>
            {
                options.Listen(IPAddress.Loopback, 5000);
            })
```

**Comment by benaadams** [comment]
It would be because you have IPv6 and IPv4 enabled for localhost on your machine, so it will try the IPv6 address first, wait for timeout (1 sec) then try the IPv4 address.

You can easily bind to both with `ListenLocalhost(int port)`
```csharp
.UseKestrel((options) =>
    {
        options.ListenLocalhost(5000);
    })
```

**Comment by Tratcher** [comment]
Note ListenLocalhost is new in 2.1.

**Comment by Drawaes** [comment]
This is a known issue as described by Ben. It's more of an issue with the HttpClient than Kestrel

**Comment by Tratcher** [comment]
Any client would have this problem unless they opened two connections in parallel.

**Comment by Tratcher** [comment]
It's been that way since Vista.

**Comment by Drawaes** [comment]
We only saw it when rolling out windows 10. But you are right about vista. Our desktops probably only had IPV4 enabled on 7

**Comment by benaadams** [comment]
Can always untick this box on the network adapter :)

![image](https://user-images.githubusercontent.com/1142958/38445268-baa47aea-39ea-11e8-9bd3-42edf5517de9.png)

**Comment by Tratcher** [comment]
👀 Doesn't work for loopback though.

**Comment by Drawaes** [comment]
Presuming you don't work for a big company and can tick said boxes ;)

**Comment by muratg** [comment]
Closing as this is not a Kestrel issue.
