### ISSUE TITLE
CPU heavy requests cause other fast requests to be delayed?

### ISSUE THREAD

**Issue by Plasma** [aspnet/KestrelHttpServer#2484]
Hi,

I'm using .NET Core 2, targeting .NET 4.6.1, with Kestrel + IIS Integration.

We have an internal application that:

1) Has a route that will perform some CPU heavy work inline (no task). Sometimes this route will also launch and async/await on another task to complete, that may take 5-10 seconds.

2) We have a "fast" route, that only pings a database, and returns in 10ms, using async/await.

Often, we notice route 2 will take an extra few seconds to complete (likely around the async/await).

I'm wondering whether, when route 2 does an await, does its completion get scheduled on the therad pool thread that is currently processing (and CPU blocked) for thread 1?

Is that a possibility? I'm trying to identify why the delays are occurring on an otherwise fast route. 

Thanks

**Comment by tmds** [comment]
Perhaps the logs can make you wiser in how much time it takes to handle those requests.

If the client sends these requests via the same connection you may be seeing the fast request being delayed because there is a pending slow request (https://en.wikipedia.org/wiki/Head-of-line_blocking).

**Comment by Plasma** [comment]
Thanks for the reply. Are there particular logs I should be checking? 

What's interesting though is that there are latency spikes during the request, not necessarily a delay in the request starting. Thank you.

**Comment by tmds** [comment]
The default info logging shows request finish times:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0679ms 200 
```

To investigate further, what you can do is (without IIS):
- Use a client to verify the fast route is always fast.
- Then add another (separate) client that calls the slow route, and see how that affects the fast route.

**Comment by Plasma** [comment]
Thanks, ill give this a go. Are you able to share some insights into how the request pipeline works?

Are there just ThreadPool threads being allocated to process requests, and when async/await happens. *any* thread pool thread can resume the thread context, unlike legacy ASPNET that requires the original thread (w/ sync context)?

Just trying to understand how its working underneath to better diagnose whats happening.

**Comment by muratg** [comment]
Closing! Thanks for the discussion.
