### ISSUE TITLE
Kestrel blocks for 5s on shutdown if you close the console

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2489]
CTL+C is fast, but if you instead close the console window it blocks for 5 seconds first. From my initial debugging the issue is in KestrelServer.StopAsync.

Repro's on Windows with the SampleApp in the repo. The TFM doesn't matter.

**Comment by halter73** [comment]
This is only an issue for debug builds, but the behavior is really weird. It's getting stuck [here](https://github.com/aspnet/Common/blob/0a744c0b56c53bac050b0996259491608bb6d39b/shared/Microsoft.Extensions.Buffers.Sources/SlabMemoryPool.cs#L168) in GC.WaitForPendingFinalizers(), but the issue only comes up when closing the console window not when exiting with CTRL+C.

![image](https://user-images.githubusercontent.com/54385/38712204-f4787bfc-3e7e-11e8-8380-4b8ceb026596.png)

**Comment by Tratcher** [comment]
The open question is if this is a regression, and if so, at what layer? You said it did not repro on 2.0.

**Comment by halter73** [comment]
The AppDomain.CurrentDomain.ProcessExit event wasn't firing when you close the console window in 2.0.

**Comment by shirhatti** [comment]
Punting to 2.2 since this a dev only issue

**Comment by muratg** [comment]
Triage: We're closing
