### ISSUE TITLE
Odd IsEnd behavior in MemoryPoolIterator2

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#249]
As picked up by @icanhasjonas in https://github.com/aspnet/KestrelHttpServer/commit/0a297688b41db2ceb44f088c3e9b4aa956c29f3d#commitcomment-13674222

The ```else``` block in [```IsEnd``` of ```MemoryPoolIterator2```](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Infrastructure/MemoryPoolIterator2.cs#L52-L64) currently does this

```csharp
else
{
    var block = _block.Next;
    while (block != null)
    {
        if (block.Start < block.End)
        {
            return true;
        }
        block = block.Next;
    }
    return true;
}
```
Previously it did similar [but using a ```for``` loop](https://github.com/aspnet/KestrelHttpServer/commit/091084cfe241d4b17372486624716e036f471f54#diff-6b7953b837b6ad7c921259c907520639R52)
```csharp
else
{
    for (var block = _block.Next; block != null; block = block.Next)
    {
        if (block.Start < block.End)
        {
            return true;
        }
    }
    return true;
}
```
I believe these to be functionally equivalent; could be wrong. 

However both escape in loop and return out of loop return ```true``` and the loop doesn't mutate state, so not sure what it is that should be going on.

**Comment by lodejard** [comment]
Yeah, the code was wrong before, should be returning false from the if (Start < End) inside the loop. That's the less common case where an iterator is pointing at the end of a given block, but that block is actually also pointing to a non-empty next block directly or indirectly. Good catch!

**Comment by benaadams** [comment]
Submitted PR #250
