### ISSUE TITLE
Any reason why upgrading to 2.1-preview2 would break IConnectionAdapter?

### ISSUE THREAD

**Issue by TechnikEmpire** [aspnet/KestrelHttpServer#2494]
I've been searching but to no avail, so I've decided to ask here. Does anyone know of a reason or even a hunch as to why upgrading from 2.0.X to the 2.1 preview2 would cause an `IConnectionAdapter` to stop functioning? I have something like:

```C#
internal class TlsSniConnectionAdapter : IConnectionAdapter
{
      ....

	public Task<IAdaptedConnection> OnConnectionAsync(ConnectionAdapterContext context)
	{
		// This still gets invoked.
		return Task.Run(() => InnerOnConnectionAsync(context));
	}
	
	private async Task<IAdaptedConnection> InnerOnConnectionAsync(ConnectionAdapterContext context)
	{
		// This no longer gets invoked at all. The connection is just IMMEDIATELY closed after
                // the above return Task.Run(() => ...);
	}
}
```

There's nothing special about this class, it just performs a peek on the connection stream to try to read the SNI extension, from which a certificate for the declared host is dynamically generated and then used in the handshake. Like I said, works fine < 2.1.x. Any ideas that might set me on the right path to solving this would be greatly appreciated. :)

**Comment by Tratcher** [comment]
Not sure why it's broken, but have you tried the new SNI support in kestrel? You probably don't need this component anymore.

**Comment by TechnikEmpire** [comment]
@Tratcher Yeah my bad, I remember now reading that, something to do with different SslStream implementations between full and core. Oh well, I can survive that as long as I can figure out why the adapter inner task is never called. Worst case I can drop back down to 2.0.x but I'm trying to escape to the arch-dependent libuv dependency.

**Comment by TechnikEmpire** [comment]
@davidfowl Yeah. Lemme go over it a few more times and make sure I'm not doing something incredibly stupid, and then if I still come up with the same result I'll try to post a repro example somewhere. Thanks.

**Comment by davidfowl** [comment]
> What it does seem like though is that things are cancelled and the connection closed sort of in between, which still doesn't really make sense.

It would still call your function, it just that it would then immediately fail.

**Comment by TechnikEmpire** [comment]
@davidfowl @Tratcher Thanks for your time, it ended up being something stupid on my end. Sorry for the false alarm.
