### ISSUE TITLE
Have you broken Kestrel configuration? #1442 

### ISSUE THREAD

**Issue by Mattacks** [aspnet/KestrelHttpServer#2495]
# Issue Title

Have you broken Kestrel configuration?

# General

In .Net Core 1.0 in Main you used to be able to '.Build()' on the builder to get the configuration resolved, in order to be able to use configuration in .UseKestrel(...)

Unless I am mistaken, that is now not possible in 2.1 - one can only use constants or read from files by hand.
Am I mistaken?

cheers

Matt

(upon advice, copied from [here](https://github.com/dotnet/core/issues/1442))

**Comment by Tratcher** [comment]
2.0 added lots of other ways to configure Kestrel, but the original ways mostly still worked. 2.1 has added even more ways... 

There is one common confusion in 2.x where people try to use ConfigreAppConfiguration in Main  to configure the Urls key, but you need to Configure the host instead.

Please show us how you are trying to configure it.

**Comment by Tratcher** [comment]
The sample you linked to should work. Why are you using ConfigureAppConfiguration instead of UseConfiguration? It's the Urls parameter you're trying to set, correct?

Or you could try the new Endpoints config. https://github.com/aspnet/KestrelHttpServer/pull/2186

**Comment by Mattacks** [comment]
1. Because I want to use multiple configuration files. Can't remember where I got the original pattern from, but you can also it being used [here](https://wildermuth.com/2017/07/06/Program-cs-in-ASP-NET-Core-2-0). And it is also the method used in the Sample [startup.cs](https://github.com/aspnet/KestrelHttpServer/pull/2186/files) found when I follow your #2186 link
2. No. I'm trying to set limits such as MaxRequestBufferSize

**Comment by Tratcher** [comment]
? MaxRequestBufferSize has never been mapped from config, in 1.x or 2.x.

**Comment by Mattacks** [comment]
[It](https://stackoverflow.com/questions/43254585/use-appsettings-to-drive-environment-specific-settings-such-as-useurls/43265773#43265773) does not work any more.

Previously `.Build()returned an `IConfigurationRoot`
Now `.Build()returns an `IWebHost`
In addition, you used to be able to call `.Build()` twice. Now if you do that you get an `InvalidOperationException`.

**Comment by Tratcher** [comment]
There are two builders in that example, a config builder and a web host builder. Make sure you're calling Build on the right one. 

I'm putting this issue on hold until you post a complete code sample and error stack traces as relevant. None of the code samples or errors you've provided have been complete or matched the complaints you've made.

**Comment by Mattacks** [comment]
> There are two builders in that example, a config builder and a web host builder
That was the missing link. Did not realise. Apologies for wasting your time.
