### ISSUE TITLE
Provides extensions method for IServiceCollection similar to WebHostBuilderKestrelExtensions to better support generic host

### ISSUE THREAD

**Issue by chuanboz** [aspnet/KestrelHttpServer#2498]
currently there is a WebHostBuilderKestrelExtensions that provides UseKestrel method to inject default implementation of Kestrel.

followed 
https://github.com/aspnet/Hosting/issues/1369
and https://github.com/aspnet/Hosting/tree/dev/samples/GenericWebHost

to use general web host, which does not use IWebHostBuilder anymore and so require extensions method to inject default Kestrel implementation.

something like below

`

public static IServiceCollection UseKestrel(this IServiceCollection services)
 {
                // Don't override an already-configured transport
                services.TryAddSingleton<ITransportFactory, SocketTransportFactory>();
                services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();
                services.AddSingleton<IServer, KestrelServer>();
                return services;
}

`

**Comment by Tratcher** [comment]
This isn't really useful by itself, Kestrel can't run the site on it's own, it needs a lot of infrastructure that's provided by WebHost today.

We'll be looking at this more in the next major version when it's possible to make breaking changes.

**Comment by chuanboz** [comment]
I'm trying to follow the sample to provide support for Service Fabric to host WebApi with generic host, and I meet this issue. I could for now workaround it by just do that myselves, but would prefer to avoid it if possible.

**Comment by chuanboz** [comment]
or if there is extension method against IApplicationBuilder, so that it is tie to Web, but does not require IWebHostBuilder, that would also work and won't show up as general extension for IServiceCollection but only be used for IApplicationBuilder which tie to web.

**Comment by chuanboz** [comment]
Thanks Chris for the fast response, I could understand your reasoning here, and for this one I could temporary copy that part of code.

for HttpSys, I will need support to at least mark MessagePump class as Public, it's internal currently.
