### ISSUE TITLE
Specify https certificate via config file

### ISSUE THREAD

**Issue by tmds** [aspnet/KestrelHttpServer#2499]
Will 2.1 support specifying the https certificate via the json config file?

**Comment by Tratcher** [comment]
Yes. See the bottom of https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-https-improvements/

**Comment by tmds** [comment]
@Tratcher 
I tried adding 
```
{
  "Certificates": {
    "Default": {
      "Path": "cert.pfx",
      "Password": "<password>"
    }
  }
}
```
to appsettings.json but that didn't work for me. Do you have an example I can copy?

**Comment by Tratcher** [comment]
Copy the whole example from the blog post. The hierarchy matters.

**Comment by Tratcher** [comment]
@danroth27 can you edit the blog post at https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-https-improvements/ to fix the heirarchy for the default certs? It's supposed to be:
```
{
 "Kestrel": {
  "Certificates": {
    "Default": {
      "Path": "cert.pfx",
      "Password": "<password>"
    }
  }
 }
}
```

**Comment by tmds** [comment]
:+1: Thanks @Tratcher! You can close this or leave it open for @danroth27 to close.

**Comment by danroth27** [comment]
Blog post updated.
