### ISSUE TITLE
Perf regression on Linux SSL (ASP.NET plaintext)

### ISSUE THREAD

**Issue by sebastienros** [aspnet/KestrelHttpServer#2504]
Moving https://github.com/dotnet/corefx/issues/28830 here since nothing is showing it is because a corefx change. Now we need to investigate the same way with aspnet.

**Comment by sebastienros** [comment]
The updated commands I ran to pinpoint the regressions:

```
dotnet run -c Release --server http://asp-perf-lin:5001 --client http://asp-perf-load:5002  -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext -m https --webHost KestrelSockets --runtimeVersion 2.1.0-preview2-26330-03 --aspnetCoreVersion 2.1.0-preview3-32107  --markdown
```

```
dotnet run -c Release --server http://asp-perf-lin:5001 --client http://asp-perf-load:5002 -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext -m https --webHost KestrelSockets --runtimeVersion 2.1.0-preview3-26331-01 --aspnetCoreVersion 2.1.0-preview3-32110  --markdown
```

On ASPNET side there was not successful UC build between `2.1.0-preview3-32107` and `2.1.0-preview3-32110`

Here is the link to the version `2.1.0-preview3-32110` that might have triggered the issue in aspnet

http://aspnetci/viewLog.html?buildId=439322&buildTypeId=AspNetCore_Publish&tab=buildChangesDiv

**Comment by sebastienros** [comment]
I have tested all runtime assemblies but these which fail individually:

```
System.Memory.dll
System.Net.Security.dll
System.Runtime.dll
System.Private.CoreLib.dll
libcoreclr.so
```

They probably need to be set all together, and also with compatible Kestrel versions

**Comment by muratg** [comment]
@halter73 Can you check if this recovered, or is it still slow?

**Comment by sebastienros** [comment]
I don't think there is anything to do on this one. There has been many other perf changes since then. Unless the actual regression in corefx/clr is found retroactively, which will be very hard as it's based on very old builds.
