### ISSUE TITLE
Flaky Test: ResponseTests.Sending100ContinueDoesNotStartResponse

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2507]
```
Assert.Contains() Failure
Not found: (filter expression)
In value:  ConcurrentQueue<LogMessage> [LogMessage { EventId = 3, Exception = null, LogLevel = Debug, Message = "Hosting starting" }, LogMessage { EventId = 4, Exception = null, LogLevel = Debug, Message = "Hosting started" }, LogMessage { EventId = 0, Exception = null, LogLevel = Debug, Message = "Loaded hosting startup assembly Libuv.FunctionalTe"... }, LogMessage { EventId = ConnectionStart, Exception = null, LogLevel = Debug, Message = "Connection id \"0HLD6AI9FD4SE\" started." }, LogMessage { EventId = 1, Exception = null, LogLevel = Information, Message = "Request starting HTTP/1.1 POST http:///  " }, ...]
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<Sending100ContinueDoesNotStartResponse>d__46.MoveNext() in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 1685
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

http://aspnetci/viewLog.html?buildId=451859&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

**Comment by Tratcher** [comment]
56 CI failures to date (why is this test still enabled?)
http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=3001934443389466677&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50

IndexOutOfRangeException 
http://aspnetci/viewLog.html?buildId=401977&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=423029&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677

Expected: HTTP/1.1 100 Continue\r\n\r\n
Actual:   
http://aspnetci/viewLog.html?buildId=405894&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=405947&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677

TimeoutException 
http://aspnetci/viewLog.html?buildId=406450&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=444258&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677

NullReferenceException
http://aspnetci/viewLog.html?buildId=413711&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=417842&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=420801&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=441199&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677

InvalidOperationException : Collection was modified;
http://aspnetci/viewLog.html?buildId=419206&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=419685&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677

No stacktrace available
http://aspnetci/viewLog.html?buildId=449380&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450281&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677

Not found: (filter expression)
http://aspnetci/viewLog.html?buildId=417482&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=421321&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=425194&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=448872&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=448864&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=448991&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449193&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win8_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449180&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449348&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449479&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449505&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449517&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449579&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449618&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449626&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449753&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449884&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449912&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449880&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450018&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450024&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win8_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=449992&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450160&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450253&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=450916&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451358&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451390&tab=buildResultsDiv&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451458&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451677&tab=buildResultsDiv&buildTypeId=XPlat_Mac_MacUniverseCoreCLR#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451689&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451859&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest#testNameId3001934443389466677
http://aspnetci/viewLog.html?buildId=451731&tab=buildResultsDiv&buildTypeId=XPlat_HighSierraOsxUniverse#testNameId3001934443389466677

Most of the recent failures fall into this last category.

**Comment by mikeharder** [comment]
@ryanbrandenburg: Should this test be disabled until the issues can be investigated?  My intuition is yes but I'm not sure the protocol we typically follow.

**Comment by mikeharder** [comment]
Also concerning to see a test be flaky in so many different ways.  @halter73, @pakrym: Any concern this could be a product bug?

**Comment by pakrym** [comment]
Seems like a test issue, lot's of the exceptions (InvalidOperationException/IndexOutOfRangeException/NullReferenceException ) point to a race in logging

**Comment by Tratcher** [comment]
I'm investigating now. I'll disable it if I don't find a ready solution.

**Comment by ryanbrandenburg** [comment]
This test still fails in release/2.1, can we port the fix back for RTM?

**Comment by Tratcher** [comment]
When RTM opens...
