### ISSUE TITLE
Investigate xUnit "non-serializable data" warnings

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2509]
Kestrel tests have hundrends of this scary-looking warning from xunit:

```
[12:02:22] : [Step 4/7]   [xUnit.net 00:00:00.3409135] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests: Non-serializable data
('System.Object[]') found for 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.LibuvTransportTests.TransportCanBindUnbindAndStop';
falling back to single test case.
```

http://aspnetci/viewLog.html?buildId=451476&tab=buildLog&buildTypeId=Lite_KestrelHttpServer&logTab=tree&filter=all&_focus=847#_state=350

They started when xUnit diagnostics messages were enabled (https://github.com/aspnet/KestrelHttpServer/pull/2505).  We should investigate what's causing these warnings, what is their implication (does it mean less tests are run than expected), and how to fix them.

**Comment by JamesNK** [comment]
It's caused by non-serializable parameters in xunit tests. SignalR had the same thing - https://github.com/aspnet/SignalR/issues/1649

All tests are still run, you just don't see them as there own nodes in the VS test explorer.

**Comment by mikeharder** [comment]
Partial fix at https://github.com/aspnet/KestrelHttpServer/pull/2520.  Decided the fix was getting too complicated and it would be better to just disable xUnit diagnostic messages.
