### ISSUE TITLE
libuv library

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#251]
consider creation of an abstraction layer that allows replacement of the libuv implementation;
also implement the full libuv api, allowing reuse of the library in other xplatform projects running
under coreclr.

**Comment by Eilon** [comment]
Sounds sort-of kind-of like what's being asked for here: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/148

**Comment by davidfowl** [comment]
@grahamehorner Why? You can already use https://github.com/txdv/LibuvSharp

**Comment by grahamehorner** [comment]
@davidfowl I've just seen the LibuvSharp and yes, it looks good; however if Kestrel used an abstraction layer and dependency injected the implementation of the abstraction layer (eg a fully implemented the libuv wrapper) it would :--

1. allow swapping out of libuv with some other library.
2. allow developers to extend the of functionality of kestrel.
a) to support ftp/smtp or other 
b) to using udp/snmp to monitor kestrel

at present kestrel is dependant on libuv, but having a abstraction layer; would allow the swapping of the libuv wrapper with a 'RIO' wrapper/implement.

**Comment by davidfowl** [comment]
Not saying it's not a good idea but why do you want that? What scenario are you trying to enable?

**Comment by grahamehorner** [comment]
I'd like to extend kestrel with snmp and/or udp messaging for cluster health monitoring; also look at having a hosting platform based on kestrel that can provide other services like smtp with a mvc
management user interface.  If the kestrel implementation had an abstraction layer (a fully implemented libuv) that gave udp/tcp additional udp/tcp services can then be added for these use cases by user kestrel as the base.

This also would allow swapping out the libuv for a more performing wrapper with minimal impact on the implementation. 

This could also be of interest to other teams orleans/trinity allowing the to make use of the kestrel and performance when implementing coreclr versions of the projects.

**Comment by davidfowl** [comment]
> I'd like to extend kestrel with support for protocols such as alljoyn, snmp & udp for messaging and cluster health monitoring

That's just not a scenario for a webserver. Feel free to copy the code out into your own library. Kestrel is not a generic networking abstraction. It's a web server.

**Comment by grahamehorner** [comment]
This idea was to allow developers to extend kestrel with other protocols; and thus make us of the performance work the team has done with kestrel; while I understand kestrel is not intended to be a generic network abstraction server/service; by allowing dependency inject of a network layer (libuv) it allows flexibility and reuse of the kestrel webserver with these types of use cases.

eg. I write a libuv wrapper that extends the minimum kestrel webserver needs and provides access to libuv udp features for my needs; kestrel uses this custom libuv wrapper instead of the (kestrel partiatally implemented libuv wrapper) 

I then can implement my webserver health monitoring and snmp services for my needs; including adding ftp/smtp services etc.

**Comment by davidfowl** [comment]
Like I said, you can copy the code and change it in whatever ways you like. We're not going to be investing in kestrel that way.

**Comment by grahamehorner** [comment]
so what is the use cases for kestrel libuv wrapper? will you be doing a full libuv wrapper?
is kestrel only ever going to be serving HTTP/S? with no tracking of performance/thru-put?

I hate forking code; to achieve extensibility as it makes life difficult to track changes/issues/fixes
from the original project; also libuv may be that option today, but if that was to change tomorrow kestrel would need a re-write?

just need more information about kestrel really and how it is viewed? is kestrel supported? and thus the libuv wrapper supported in production?

**Comment by davidfowl** [comment]
> so what is the use cases for kestrel libuv wrapper? will you be doing a full libuv wrapper?

We use libuv as an internal implementation detail to implement an http server.

> is kestrel only ever going to be serving HTTP/S? with no tracking of performance/thru-put?

Kestrel supports SSL via an extension. You can provide an `IConnectionFilter`, see the Kestrel.Https package.

> I hate forking code; to achieve extensibility as it makes life difficult to track changes/issues/fixes
from the original project; also libuv may be that option today, but if that was to change tomorrow kestrel would need a re-write?

Probably? 

> just need more information about kestrel really and how it is viewed? is kestrel supported? and thus the libuv wrapper supported in production?

Kestrel is a cross platform webserver for ASP.NET, nothing more. It uses libuv to achieve that because libuv implements sockets in a cross platform way (and it does so very efficiently).

You might be reading too much into the fact that the libuv APIs are exposed. It should really be buried in an .Internal namespace. What you should do instead is use something like libuvsharp, it sounds like it is better suited for your use case.

**Comment by aL3891** [comment]
I'm also interested in running kestrel on something else, such as registered io. I also think it would be useful to abstract out the actual socket layer just for testing and profiling kestrel itself. 
I know you're focused on rc and rtm now but how do you feel in principle about less couling between kestrel and libuv?

**Comment by grahamehorner** [comment]
@aL3891 :+1:

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
