### ISSUE TITLE
Lower level middleware

### ISSUE THREAD

**Issue by israellot** [aspnet/KestrelHttpServer#2512]
A lot of applications have to deal with the same pipeline as an http server up until protocol handling. 
An MQTT broker for example could reuse kestrel code from the tcp connection middleware forward. 
Is there any change of decoupling kestrel this way?

**Comment by benaadams** [comment]
Project Bedrock https://github.com/aspnet/KestrelHttpServer/issues/1980

**Comment by israellot** [comment]
That was fast! Thanks
