### ISSUE TITLE
composer require --prefer-dist mihaildev/yii2-elfinder "*"

### ISSUE THREAD

**Issue by AlisherSharopov** [aspnet/KestrelHttpServer#2513]
Салом, ба ҳама.
Вақте, ки ман ин (composer require --prefer-dist mihaildev/yii2-elfinder "*") амалро дар console иҷро кардам, чунин хатогӣ рух дод:

Content-Length mismatch, received 1368303 bytes out of the expected 1695049
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> no matching package found.
    - yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].

What to do to fix this error?

**Comment by AlisherSharopov** [comment]
Hello, to all.
When I did this practice (composer.php requires --prefer-dist mihaildev / yii2-elfinder * * ") in the console, this error occurred:

Content-Length mismatch, received 1368303 bytes out of the expected 1695049
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Your requirements could not be resolved to an installable set of packages.

Problem 1
- yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> no matching package found.
- yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
- Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].

What to do to fix this error?

**Comment by AlisherSharopov** [comment]
Hello, to all.
When I did this practice (composer requires --prefer-dist mihaildev / yii2-elfinder * * ") in the console, this error occurred:

Content-Length mismatch, received 1368303 bytes out of the expected 1695049
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> no matching package found.
    - yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].

What to do to fix this error?

**Comment by Tratcher** [comment]
I don't see how this relates to Kestrel, or even ASP.NET Core. stackoverflow.com may be a more appropriate place for this question.

**Comment by muratg** [comment]
@AlisherSharopov This bug in it's current state is not actionable. If you have questions, please go to stackoverflow.com.  If you think you identified a bug, please file another issue with detailed steps to reproduce the issue. Thank you.
