### ISSUE TITLE
Kestrel resets when running through IIS

### ISSUE THREAD

**Issue by jruckert** [aspnet/KestrelHttpServer#252]
Hi,

When running a simple WebApi controller through IIS and the HttpHandler, we continually get this error logged (we are testing using the latest RC1 version and HttpHandler v1.0)

Failed to process work - Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Microsoft.AspNet.Server.Kestrel.Http.ISocketOutput.Write(ArraySegment`1 buffer, Boolean immediate) at Microsoft.AspNet.Server.Kestrel.Http.Frame.WriteChunked(ArraySegment`1 data) at Microsoft.AspNet.Server.Kestrel.Http.Frame.Write(ArraySegment`1 data) at Microsoft.AspNet.Server.Kestrel.Http.FrameResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count) at Microsoft.AspNet.SignalR.Transports.LongPollingTransport.PerformPartialSend(Object state) at Microsoft.AspNet.SignalR.Infrastructure.TaskQueue.InvokeNext(Func`2 next, Object nextState) at Microsoft.AspNet.SignalR.TaskAsyncHelper.FromMethod[T1,T2,T3](Func`4 func, T1 arg1, T2 arg2, T3 arg3) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.SignalR.Messaging.Subscription.d__25.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.SignalR.Messaging.Subscription.d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.SignalR.Messaging.MessageBroker.d__9.MoveNext()

**Comment by jruckert** [comment]
It seems to be due to the fact i'm using SignalR. Is SignalR supported with Kestrel or will be?

I have tried adding in app.UseWebsockets() however this has not helped.

Cheers,
Jonathan

**Comment by Tratcher** [comment]
FYI: SignalR is not supported for the first release of Asp.Net 5.

**Comment by jruckert** [comment]
@Tratcher thank you for clarifying this. Will there be any alternative (apart from not using Kestrel?) - I'm assuming we won't be in a position to use the WebListener with the IISPlatformHandler.

**Comment by Tratcher** [comment]
SignalR isn't supported at all this release, it's not just a Kestrel issue.

I hope I can get WebListener working with IISPlatformHandler, there are some strange failures I haven't had a chance to debug yet.

**Comment by davidfowl** [comment]
@jruckert That error looks expected though. Looks like a client disconnect during a write which happens all the time. SignalR's logging hasn't been updated as yet so it's probably just being noisy.

**Comment by jruckert** [comment]
@davidfowl Thanks for the info, after some major debugging today, it seems that the connection via JavaScript works fine, however connecting via C# bombs out creating a 500 internal server error, when using the WebListener works fine though.

Specifically (understanding that this is not going to be supported for v1, and knowing I can get burnt :fire: playing with your MyGet branch):

Microsoft.AspNet.SignalR.Client.Infrastructure.StartException: Error during start request. Stopping the connection. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-UA-Compatible: IE=Edge,chrome=1
  Date: Mon, 12 Oct 2015 04:21:51 GMT
  Server: Kestrel
  X-Powered-By: ASP.NET
  Content-Length: 0
}
   at Microsoft.AspNet.SignalR.Client.Http.DefaultHttpClient.<>c__DisplayClass2.<Get>b__1(HttpResponseMessage responseMessage)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.<>c__DisplayClass19`2.<Then>b__17(Task`1 t)
   at Microsoft.AspNet.SignalR.TaskAsyncHelper.TaskRunners`2.<>c__DisplayClass42.<RunTask>b__41(Task`1 t)
   --- End of inner exception stack trace ---

Really keen to though understand how to "enable" NTLM authentication with Kestrel, similar to what we can do with both Weblistener.

I've been playing around with both "Authentication" and "Security" packages, but I am obviously missing something.

**Comment by davidfowl** [comment]
> Specifically (understanding that this is not going to be supported for v1, and knowing I can get burnt :fire: playing with your MyGet branch):

Yah, you'll need to debug it. We're not working on SignalR actively at the moment (as stated in the roadmap and by @Tratcher )

> Really keen to though understand how to "enable" NTLM authentication with Kestrel, similar to what we can do with both Weblistener.

Kestrel doesn't support NTLM and won't. We may eventually have an NTLM stand alone middleware but it's not on schedule for v1. The only way to enable it will be IIS + Kestrel or WebListener.

**Comment by jruckert** [comment]
@davidfowl cool, as long as IIS is supported, then i'll be OK. I have a couple of other alternatives to SignalR although not as pretty :smiley: so should be OK.

**Comment by CarlosFreire** [comment]
@davidfowl I have the same error, you may find some alternative to this error

**Comment by CarlosFreire** [comment]
@jruckert I have the same error, you may find some alternative to this error

**Comment by muratg** [comment]
Closing this one. Please refile another one if you have problems without SignalR.
