### ISSUE TITLE
Asp Net MVC Core App getting Http Bad Request

### ISSUE THREAD

**Issue by joetherod** [aspnet/KestrelHttpServer#2524]
The request doesnt seem to make it to the MVC Core application and no errors are thrown. The browser just returns 400 Bad Request. The url contains an accented character.

uri encoded in javascript and part of url:
Paris%2C%20%C3%8Ele-de-France%20Region
actual value:
Paris, Île-de-France Region

How do I configure Kestrel to allow the characters.
The originial app MVC 4 running in IIS allows the url request.

**Comment by Tratcher** [comment]
Already responded at https://github.com/aspnet/Home/issues/3094#issuecomment-384410319

**Comment by joetherod** [comment]
This was actually related to a cookie set on the client and getting sent to server. Had this issue with not encoding cookies on the server, and they were set to empty. If the cookie is set on the client side, and posted, it shouldnt give a Bad Request page with no way to handle it in code. Another gotcha with cookies in aspnet core.
