### ISSUE TITLE
Sockets Transport is missing OnWriterCompleted handler

### ISSUE THREAD

**Issue by tmds** [aspnet/KestrelHttpServer#2525]
This is still missing from the Sockets transport and allows a client to block the timeout logic by not reading as explained here: https://github.com/aspnet/KestrelHttpServer/issues/1771#issuecomment-297524780.

CC @halter73 @davidfowl

**Comment by blowdart** [comment]
@cesarbs as you looked at the last issue

**Comment by benaadams** [comment]
Looks like **"Make write timeout work on Socket transport"** #1943 was closed as it was being tracked in **"The connection was closed because the response was not read by the client at the specified minimum data rate"** #2171

Then it looks like #2171 was just closed without resolution?

**Comment by muratg** [comment]
Should be in RTM bits.
