### ISSUE TITLE
https kestrel causes script to load 4-5 times slower than without

### ISSUE THREAD

**Issue by p2atran** [aspnet/KestrelHttpServer#2527]
I originally thought the bug was part of mvc, but it might be from kestrel.

Information can be found on this thread:
https://github.com/aspnet/Mvc/issues/7704

But to sum it up, if you follow these instructions to get a new core 2.0 project:
https://docs.microsoft.com/en-us/aspnet/core/getting-started?view=aspnetcore-2.0

Then add https in `UseKestrel` in program.cs, the program loads super slow. A 38mb script when loaded with the new/clean project took me about 8-9 seconds, where as with https kestrel it took 35s to 1min.

If I load the same 38mb script in a clean .NET Core 1.1 project, it takes around 2-3 seconds. So the clean Core 2.0 project without the https kestrel is still approximately 3 times slower than a .NET Core 1.1 project

A reproducible example can be found in the mvc thread in my last comment.

**Comment by p2atran** [comment]
@davidfowl Are there any potential work arounds to get https working without using kestrel to avoid the performance hit?

**Comment by Tratcher** [comment]
You can use IIS or HttpSys.

**Comment by p2atran** [comment]
@Tratcher If i'm using a mac to develop, would HttpSys be out of the picture? I checked the documentation and it says it only supports windows. If my server, however, is on Azure that should be fine right?

**Comment by p2atran** [comment]
@Tratcher Oh so if I'm using the `listenOptions` in kestrel to provide the ssl cert, I can just remove that bit of code and replace it with `useIIS` and place my cert in the azure portal?

**Comment by Tratcher** [comment]
That's the idea.

**Comment by p2atran** [comment]
Oh okay i'll give that a shot. We should probably still investigate why kestrel has a performance hit though right? And would it just be as simple as adding `UseIIS()` to the WebHostBuilder?

**Comment by Tratcher** [comment]
You shouldn't need to add anything, IIS Support is included via WebHost.CreateDefaultBuilder.

**Comment by sebastienros** [comment]
I can run the static files scenario on https with different sizes and compare 2.1 to 2.0.

**Comment by Tratcher** [comment]
Correct. You'll want a flag so you don't tring to publish or load that certificate for production.

This should get easier in 2.1 where we provide a default development cert.

**Comment by muratg** [comment]
@sebastienros Did you add static file scenarios?  Any larger file scenario?

**Comment by sebastienros** [comment]
I measured 2.0 vs 2.1 for diverse file sizes on Linux, under load.

| Description | RPS | Avg. Latency (ms) |
| --- | --- | ------- | 
| 2.0 https 1KB | 38,424 |      85.5 | 
| 2.1 https 1KB | 85,143 |                   82.2 |
| 2.0 https 16KB | 37,307 |                 114.8 |          
| 2.1 https 16KB | 65,120 |                   53.6 |          
| 2.0 https 512KB | 2,044 |                    1260 |         
| 2.1 https 512KB | 2,165 |                   1170 |         
| 2.0 https 1MB | 828 |                    1920 |          
| 2.1 https 1MB | 1,031 |                   1920 |        
| 2.0 https 5MB |  155 |                      3510 |          
| 2.1 https 5MB |  155 |                      3170 |

**Comment by Tratcher** [comment]
Once you hit 5mb I assume you're saturating the network? 

This ask was a bit different. How long does a single large download take on average? And how close does it get to saturating the network on its own?

**Comment by sebastienros** [comment]
Got it, will measure single accesses then.

**Comment by halter73** [comment]
@sebastienros Also note that is not about a perf regression from 2.0->2.1 but from 1.1->2.0.

**Comment by muratg** [comment]
We won't be making any changes here. We recommend moving to 2.0.

**Comment by p2atran** [comment]
@muratg muratg The issue was with 2.0. I did a 1.1 -> 2.0 , which is where I noticed the performance issue. As noted by @halter73.
