### ISSUE TITLE
 I have a question about using Yii2-framework

### ISSUE THREAD

**Issue by AlisherSharopov** [aspnet/KestrelHttpServer#2529]

**Comment by AlisherSharopov** [comment]
Does anyone use Yii2-Framework?

**Comment by davidfowl** [comment]
Nope

**Comment by AlisherSharopov** [comment]
I do not understand your speech

**Comment by AlisherSharopov** [comment]
I have a question for him.

**Comment by AlisherSharopov** [comment]
When I did this practice (composer requires --prefer-dist mihaildev / yii2-elfinder "*") in console, this error occurred:

Content-Length mismatch, received 1368303 bytes out of the expected 1695049
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
Your requirements could not be resolved to an installable set of packages.

Problem 1
- yiisoft/yii2-jui 2.0.7 requires bower-asset/jquery-ui ~1.12.1 -> no matching package found.
- yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.@stable -> no matching package found.
- yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
- Installation request for yiisoft/yii2-jui ^2.0 -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7].


Explain to me what to do to correct this error?
