### ISSUE TITLE
Don't throw on FIN from upgraded connections

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2532]
Once this is fixed, SignalR will no longer have to catch an exception always thrown from UpgradeStream.ReadAsync() when a WebSocket connection is closed. If the WebSocket connection was really terminated prematurely, the WebSocket middleware can turn the end of the stream without a proper close frame into an exception.

**Comment by shirhatti** [comment]
Already fixed. @halter73 will link and close

**Comment by halter73** [comment]
Fixed by #2533
