### ISSUE TITLE
System.InvalidOperationException: Concurrent reads or writes are not supported

### ISSUE THREAD

**Issue by rob-linton** [aspnet/KestrelHttpServer#2563]
### Title
The following warning is thrown intermittently when sending POST requests.
```System.InvalidOperationException: Concurrent reads or writes are not supported```

### Detailed Error
```2018-05-11 00:32:10.911 +00:00 [WRN] Connection processing ended abnormally.
System.InvalidOperationException: Concurrent reads or writes are not supported.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.ReadableBufferAwaitable.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<ConsumeAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

### Version

``` dotnet --info

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by Tratcher** [comment]
Interesting, how did that happen? What was handling that request in your code? An MVC Action? This is the kind of error I would expect if you had used `async void` or some other form of concurrency where the request Task ended but you continued to read in the background.

**Comment by rob-linton** [comment]
It's an MVC action.

``` [Route("api/decrypt")]
        [HttpPost]
        public Object Decrypt([FromBody]dynamic value, string format, [FromHeader]string authorization, [FromServices] IDataService kv)
        {...
```

The only thing that might be different I guess is that it's passing in a a IDataService which is a Singleton service object.

**Comment by benaadams** [comment]
Do you have a Task/Async call in the method you don't await? (e.g. so the execution leaves the method before the method is complete)

**Comment by rob-linton** [comment]
I do have this as the first line in the method actually.

```var backgroundTask = Task.Run(() => CryptoInternal.Purge(kv));
```

It would definitely be possible for the Decrypt method to exit before the thread above has completed.

The thread above kicks off some housekeeping in a background thread while the Decypt method is executing.

**Comment by benaadams** [comment]
Does `CryptoInternal.Purge` access any request/response stuff? Once your method exits you hand back control to the webserver and it errors while dumping the rest of the request data (in `MessageBody.ConsumeAsync`)

**Comment by rob-linton** [comment]
No it's completely independent of the request/response stuff. However it does access the singleton object "kv", which is passed to it via the parameters on the Decrypt method. Once the Decrypt method exists, would that invalidate the "kv" object passed to the background thread, as it was passed as a param, even though it is a singleton object and therefore persistent across calls?

**Comment by benaadams** [comment]
You could await it prior to exiting and see if that helps; may assist with narrowing down the issue?
```csharp
public async Task<Object> Decrypt([FromBody]dynamic value, ...
{
    var backgroundTask = Task.Run(() => CryptoInternal.Purge(kv));

    // ...

    await backgroundTask;
    return theObject;
}
```

**Comment by rob-linton** [comment]
Waiting for the background task to complete before exiting the POST handler method seems to have resolved the problem. Thanks for the suggestion.

There's probably a better way to do housekeeping rather than kicking it off in the background for every request anyhoo, should probably rethink that.

**Comment by benaadams** [comment]
> Waiting for the background task to complete before exiting the POST handler method seems to have resolved the problem. 

That would suggest `CryptoInternal.Purge` is accessing the HttpContext in some way? Perhaps via `IHttpContextAccessor`?

**Comment by rob-linton** [comment]
No, definitely not accessing the HttpContext in any way. Purge mostly deals with shared dictionary objects protected by locks. However I do use a raw Socket to ping dead key providers in the background for recovery, but I would struggle to see the link, other than at the base level the HTTP connection will have an open socket as well.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
