### ISSUE TITLE
Kestral does not understand websocket request if it has content-length header

### ISSUE THREAD

**Issue by Murtuzakabul** [aspnet/KestrelHttpServer#2564]
Here is a test case with two request to kestrel web server. One is successful while another is not

Failed request
```
GET /client HTTP/1.1
user-agent: Dart/2.0 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: 192.168.137.72
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: 0Db/dlrGHU/gQam9r80Q6g==
upgrade: websocket

HTTP/1.1 200 OK
Connection: close
Date: Fri, 11 May 2018 14:57:38 GMT
Server: Kestrel
Content-Length: 0

```

Successful request

```
GET /client HTTP/1.1
Host: 192.168.137.72
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: chrome-extension://pfdhoblngboilpfeibdedpjgfnlcodoo
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Sec-WebSocket-Key: ouTy2cAv7Du/LfDP0zFSlQ==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Date: Fri, 11 May 2018 14:17:16 GMT
Server: Kestrel
Upgrade: websocket
Sec-WebSocket-Accept: V8vCh+hwhn4M4D+IX4JZuWkcnNc=
```

It turns out that when the headers of the request are all in small caps, kestrel cannot understand it properly and instead of replying with 101 - Switching Protocols, it responds with 200 Ok response.

As per standards, it should be able to understand the headers in lowercase also.

https://tools.ietf.org/html/rfc2616#section-4.2

**Comment by Tratcher** [comment]
Interesting. The issue would be near
https://github.com/aspnet/KestrelHttpServer/blob/f04118fca1df0c513e09211fac336dd1c03dee52/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs#L258-L275
or
https://github.com/aspnet/WebSockets/blob/bb70e7077f5749608994b2d590c5df7ef7258a7c/src/Microsoft.AspNetCore.WebSockets/Internal/HandshakeHelpers.cs 
Though I don't see any issues there at first glance.

Next step: repro and narrow down which header is the problem. Start with the sec-websocket headers, Kestrel doesn't check those so they should be easy to eliminate.

**Comment by Tratcher** [comment]
Also, which version are you using?

**Comment by Murtuzakabul** [comment]
I'm using version 2.0.1

**Comment by Murtuzakabul** [comment]
Will try to reproduce the issue as well as I'll also try to investigate the code to figure it out.

**Comment by Murtuzakabul** [comment]
I did some testing and concluded following

In this non working request
```
GET /client HTTP/1.1
user-agent: Dart/2.0 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
content-length: 0
sec-websocket-version: 13
host: 192.168.137.72
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: 0Db/dlrGHU/gQam9r80Q6g==
upgrade: websocket
```

I need to make at least two changes to make it work

First change 

`connection: Upgrade`

to 

`Connection: Upgrade`

and second is to remove the header

`content-length: 0`

It seems like Kestrel does not ignore content-length even if it is a GET request.

**Comment by khellang** [comment]
This sounds an awful lot like https://github.com/aspnet/KestrelHttpServer/pull/2217, no?

**Comment by Murtuzakabul** [comment]
@khellang Sounds similar. Probably it is the same issue. We can merge.

**Comment by Tratcher** [comment]
Can you give 2.1.0-rc1 a try? It looks like content-length: 0 has been fixed. Not sure if anything has changed with connection.

**Comment by Murtuzakabul** [comment]
How do I update the version of kestrel ? I cannot see any reference to get it done properly

**Comment by Tratcher** [comment]
See https://blogs.msdn.microsoft.com/webdev/2018/05/07/asp-net-core-2-1-0-rc1-now-available/

**Comment by Murtuzakabul** [comment]
It is working with rc1. Thanks. When is it planned for release.

**Comment by muratg** [comment]
Closing!

**Comment by muratg** [comment]
Closing!
