### ISSUE TITLE
ConnectionClosed not fired for non-tcp libuv connections

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2577]
https://github.com/aspnet/KestrelHttpServer/blob/release/2.1/src/Kestrel.Transport.Libuv/Internal/LibuvConnection.cs#L47

**Comment by davidfowl** [comment]
Looks like it was intentional? Why was it done this way? Or was it a mistake?

**Comment by shirhatti** [comment]
Tracked by  the PR for #2636
