### ISSUE TITLE
Call new IHttpContextFactory.Dispose(...) from request end

### ISSUE THREAD

**Issue by Eilon** [aspnet/KestrelHttpServer#258]
In here: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L175-L196

Before the `try` do the create, and in the `finally` do the dispose.

See new API in https://github.com/aspnet/Hosting/issues/404.

**Comment by muratg** [comment]
Same as WebListener, your hosting changes have potential to break these.

**Comment by JunTaoLuo** [comment]
merged to dev
