### ISSUE TITLE
BadHttpRequestException: Request timed out

### ISSUE THREAD

**Issue by AlinaSt** [aspnet/KestrelHttpServer#2584]
Hello!
Sometimes this error occured:

error: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request timed out.     at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.PipeCompletion.ThrowFailed()     at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.GetResult(ReadResult& result)     at Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.Pipe.Microsoft.AspNetCore.Server.Kestrel.Internal.System.IO.Pipelines.IReadableBufferAwaiter.GetResult()     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)     at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.FrameRequestStream.ReadAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)     at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)     at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)     at APlus.FilesGateway.Web.Middlewares.UploadMiddleware.Invoke(HttpContext context, FileOptionAccessor fileOptionAccessor, AzureFileProxy azureFileProxy, ILogger`1 logger) in C:\Users\xxx\Source\Repos\pa\Source\APlus.FilesGateway.Web\Middlewares\UploadMiddleware.cs:line 125

In this place of project:
```csharp
using (var memoryStream = new MemoryStream())
                {
                    try
                    {
                        context.Request.EnableRewind();
                        await context.Request.Body.CopyToAsync(memoryStream); //An error occured here
                       ....
                    } 
....  
}
```
Our Kestrel options:
```csharp
return WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                    .UseEnvironment(environment)
                    .UseKestrel(options =>
                    {
                        options.Limits.MaxRequestBodySize = int.MaxValue;
                        options.Limits.MinResponseDataRate = null;
                    })
                    .UseIISIntegration()
                    .UseStartup<Startup>()
                    .Build();
```
How can we solve this problem?

**Comment by shirhatti** [comment]
You need to set your`options.Limits.MinRequestDataRate`to null

**Comment by AlinaSt** [comment]
Thank you! It's working.
