### ISSUE TITLE
Flaky Test:  AddressRegistrationTests.CanRebindToEndPoint

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2590]
Test History: http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=8721960128377588839&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50

Recent Failure: http://aspnetci/viewLog.html?buildId=470609&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

```
System.IO.IOException: Failed to bind to address http://127.0.0.1:53597: address already in use. --->
Microsoft.AspNetCore.Connections.AddressInUseException: Error -4091 EADDRINUSE address already in use ---> 
Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -4091 EADDRINUSE address already in use
```

**Comment by Tratcher** [comment]
6 failures, 2 Mac and 4 Windows

**Comment by mikeharder** [comment]
Also failed on my local Ubuntu 18.04 Hyper-V VM.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=514147&buildTypeId=Releases_22xPublic_UbuntuUniverse).

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=514459&buildTypeId=Releases_22xPublic_UbuntuUniverse).

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=514169&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed again](http://aspnetci/viewLog.html?buildId=518388&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed with about the same error](http://aspnetci/viewLog.html?buildId=519919&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@halter73 - would fixing this be covered by your proposal to re-jigger the Kestrel tests?

**Comment by halter73** [comment]
Part of the plan is to move the AddressRegistrationTests into their own group which should hopefully eliminate or significantly reduce the AddressInUseExceptions that sometimes fail the CanRebindToEndPoint test.

**Comment by ryanbrandenburg** [comment]
CanRebindToEndPoint [failed with about the same error](http://aspnetci/viewLog.html?buildId=521701&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
These tests should be more reliable after 0e99235 moved the binding tests to their own test group.
