### ISSUE TITLE
Flaky Test:  MaxRequestBufferSizeTests.LargeUpload(maxRequestBufferSize: 41943040, connectionAdapter: False, expectPause: False)

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#2594]
# Failure
```
Assert.Contains() Failure
Not found: bytesRead: 41943040
In value:  
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.MaxRequestBufferSizeTests.LargeUpload(Nullable`1 maxRequestBufferSize, Boolean connectionAdapter, Boolean expectPause)
--- End of stack trace from previous location where exception was thrown ---
```
http://aspnetci/viewLog.html?buildId=471920&tab=buildResultsDiv&buildTypeId=Lite_KestrelStressTest

# History
http://aspnetci/project.html?tab=testDetails&testNameId=7127925562766240186&projectId=AspNetEf&order=TEST_STATUS_DESC

# Notes
The test was recently changed to improve the reliability of `LargeUpload(maxRequestBufferSize: 5242880, connectionAdapter: True, expectPause: True)` (https://github.com/aspnet/KestrelHttpServer/pull/2586).  These parameters were failing due to client occasionally *not* being paused, primarily (or exclusively) on Windows 10.  The fix was to increase the length of the uploaded data, to ensure the client is paused even if the OS buffers are large.

The parameters which failed in this instance `LargeUpload(maxRequestBufferSize: 41943040, connectionAdapter: False, expectPause: False)` are quite different.  With these parameters, the client is expecting to upload 40MB and *not* be paused, and the server response should contain the number of bytes read.  It appears the server response was empty when the test failed.

**Comment by Tratcher** [comment]
Note only 1 failure is listed in CI history.
