### ISSUE TITLE
Shutting down issue on Mac OS

### ISSUE THREAD

**Issue by suhasj** [aspnet/KestrelHttpServer#26]
The normal way to shutdown Kestrel server is by pressing enter key. On OSX, if the user hits some other key, for example, 'Ctrl + C', the process is hung and cannot be exited. Pressing 'Ctrl+Z' stop the server but the port is blocked by the process. It would be great if the experience can be made better or at least have a default message that says' Press Enter to Exit"

**Comment by conniey** [comment]
Did someone ever add a message after running `k kestrel` to tell folks how to shut down the server? 

I kept trying Ctrl+C, then eventually just Ctrl+Z and kill -9 <pid> until I stumbled across this thread.

**Comment by rodfraga** [comment]
On OS X just use the terminal.
1.- Open a new terminal windows
2.- type "ps" to see the running processes 
3.- type "kill -9 {ps id of mono running process}"
