### ISSUE TITLE
Guidance on shared hosting platform needed

### ISSUE THREAD

**Issue by las3r** [aspnet/KestrelHttpServer#2613]
I've scourned the documentation as well as the (mostly excellent) guides out there and I'm still left with a few questions regarding my situation that I can't seem to find answered anywhere. Please note: In this case I have  a fully working implementation of asp.net core in the popular cPanel hosting panel using their plugin system.

We all know the shared-hosting LAMP stacks that hosting companies offer for 'cheaper' hosting. I'm trying to plug in to one of these hosting panels by integrating Kestrel so that end-customers can not only run PHP and HTML apps, but also choose to run .net core on their shared linux hosting provider / hosting panel.

With shared hosting come many responsibilities, such as making sure that some settings are enforced from the host, rather than the application and this is exactly where my problem lies. I am wondering if there is a way to override kestrel default settings outside of the running ip and port. Basically I'd like a way to e.g. limit memory usage, limit response / processing times, limit request sizes on a per-app basis overwriting (or limiting) the developer of the app in basically claiming all the "shared" space on a shared hosting server. Right now the startup.cs and the entrypoints allow developers to basically claim all server resources if they are doing it wrong™.

I think .net core is fantastic, but not everyone is hosting IIS servers or Azure Web Apps and this might enable a wider audience to not only use but also host their .net core apps. I'd like to help server owners take control of their .net core customers.

Have you thought about this use case? Are there any plans on supporting this business case and thus plans for supporting usage on shared hosts?

_(updated for clarity)_

**Comment by shirhatti** [comment]
@las3r We currently don't have any blessed or official cPanel/plesx plugins for ASP.NET Core hosting. It's fantastic that you have a working implementation in cPanel already. [If you don't setting up some time, I'd love to talk to you about it](https://calendly.com/shirhatti).

> Basically I'd like a way to e.g. limit memory usage, limit response / processing times, limit request sizes on a per-app basis overwriting (or limiting) the developer of the app in basically claiming all the "shared" space on a shared hosting server

These are concerns outside those solved by an application server. You're more likely to achieve success in accomplish this by using OS features such job objects in Windows and cgroups in linux to achieve this. A lot of our customers have employed docker containers to solve these concerns.

> Have you thought about this use case? Are there any plans on supporting this business case and thus plans for supporting usage on shared hosts?

Yes. We're only in the very early stages of meeting with hosters to identify what we can do to make it easier to adopt ASP.NET Core. If you have inputs, we're all ears right now

**Comment by las3r** [comment]
@shirhatti I set up the appointment. Let's discuss this over skype.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
