### ISSUE TITLE
Doesn't seem to work with Azure Load Balancer

### ISSUE THREAD

**Issue by georgiosd** [aspnet/KestrelHttpServer#2617]
I am running a web app in Ubuntu using Kestrel and trying to set up a load balancer for it.

I have set up a health probe that's excluded from HTTPS redirection, and the rest works as it should. (i.e. the site responds to HTTP with a redirect to HTTPS using the public URL and HTTPS responds fine when loading it on the box directly or through the local network).

For whatever reason, all the requests that I see from the load balancer are the probs (to which I return 200 of course). 

Any ideas??

Note that I'm not using nginx to reverse proxy between the load balancer and Kestrel - this seems to be recommended but seems unnecessary nowadays.

**Comment by georgiosd** [comment]
This is very bizarre. I have managed to pin this down on the network security group.

Usually the default rule AllowAzureLoadBalancerInBound suffices to redirect the requests to the backend.

In this case, I have to add an Allow ANY => ANY for the HTTP+HTTPS port for this to work. 

Why may this be??

**Comment by shirhatti** [comment]
Is your HTTP endpoint listening for your health probe also listening on port 80? If not, you'll need to open that port as well.
Regardless, opening up all ports on your VM seems unnecessary and I would advise against it.

**Comment by georgiosd** [comment]
I am not sure what you mean. 

The app uses custom ports but let's assume 80 for HTTP, 443 for HTTPS and 80 for the probe. 

The `ANY => ANY` rule is for all sources/destinations, I have limited the ports to 80+443.

But why doesn't the default `AllowAzureLoadBalancerInBound` rule suffice?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
