### ISSUE TITLE
http/2: Investigate tools for perf/stress testing

### ISSUE THREAD

**Issue by shirhatti** [aspnet/KestrelHttpServer#2625]
We currently use wrk for perf testing. We'll need to investigate and identify a suitable replacement for http/2

**Comment by Tratcher** [comment]
And get them set up.

@sebastienros

**Comment by sebastienros** [comment]
Aye aye captain

**Comment by Tratcher** [comment]
https://github.com/http2/http2-spec/wiki/Tools

**Comment by shirhatti** [comment]
It be convenient if we had some client that could make prior knowledge http/2 requests.

**Comment by Tratcher** [comment]
H2Load

**Comment by muratg** [comment]
Looks like we have a client currently running.  Closing this one.
