### ISSUE TITLE
Kestrel 2.1 refuses to respond after doing several requests

### ISSUE THREAD

**Issue by hismichael** [aspnet/KestrelHttpServer#2633]
My working code is to create an embedded kestrel instance. While when I upgraded it to based on v2.1 (and from LibUv to Sockets transport), it only serves first several requests once running, and then doesn't respond to subsequent requests (no more calls to `ProcessRequestAsync`() happen), my Chrome browser reports "xxxx refused to connect".
"

The server creation code is as below:

    ```
    SocketTransportFactory transportFactory= new SocketTransportFactory(Options.Create(new SocketTransportOptions()), Lifetime, NullLoggerFactory.Instance);
    ```
    LoggerFactory loggerFactory = new LoggerFactory();
    ```
    // init the embedded server
    KestrelServerOptions options = new KestrelServerOptions();
    server = new KestrelServer(Options.Create(options), transportFactory, loggerFactory );
    ICollection<string> addrs = server.Features.Get<IServerAddressesFeature>().Addresses;
    addrs.Add(someAddr.Trim());
    ```

I guess there should be some incompatible changes that I don't know. Please help me out.

**Comment by hismichael** [comment]
I solved this problem by **not sharing** a transport factory instance among `KestrelServer `instances. Instead each `KestrelServer `instance uses a dedicated `SocketsTransportFactory `instance during construction, and now it works again.

**Comment by muratg** [comment]
@hismichael Could you please create a small repro app and share it on GitHub for us?

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided   in a timely manner and we have been unable to reproduce it. If you have more   details and are encountering this issue please add a new reply and re-open   the issue.
