### ISSUE TITLE
[2.1.3] Consistently handle connection aborts

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2636]
We should backport backport of graceful server shutdown fixes which improve functional test reliability, and followup PRs that normalize the exceptions thrown by the libuv and socket transports while providing better logs and error messages.

Here are the dev PRs that should backported to 2.1 release branch:

#2566
#2574
#2547
#2612

**Comment by halter73** [comment]
Here are some examples of customer-reported issues or comments filed in the last 30 days that I think this also addresses. Some are closed because they are already fixed in dev:

https://github.com/aspnet/KestrelHttpServer/issues/2546#issuecomment-389410626
#2540
https://github.com/aspnet/KestrelHttpServer/issues/2536#issuecomment-386129045
https://github.com/aspnet/KestrelHttpServer/issues/2536#issuecomment-388641974
#2631

There are even more issues older than 30 days.

**Comment by muratg** [comment]
This is approved for 2.1.3.

**Comment by Eilon** [comment]
@halter73 - do you have an update on this patch issue?

**Comment by halter73** [comment]
The backport was merged into our release/2.1 branch 2 weeks ago with #2619. Closing.
