### ISSUE TITLE
MemoryPoolBlock.Dispose can throw and ODE during server shutdown leading to an error log from the Socket Transport 

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2638]
MemoryPoolBlock.Dispose() can throw and ODE (ironic I know) during server shutdown leading to an error log from the Socket Transport. Maybe we should to backport https://github.com/aspnet/Common/pull/344/files#diff-708aafde37872ea09e25cfadd4d95f0eL56

This was originally reported by @seanmars in https://github.com/aspnet/KestrelHttpServer/issues/2254#issuecomment-393830106:

> When i ctrl+c to close the server it will get exception about "Unexpected exception in SocketConnection.StartAsync"

> ```
> Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets|Unexpected exception in SocketConnection.StartAsync
> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'MemoryPoolBlock'.
>    at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
>    at System.Buffers.MemoryPoolBlock.Dispose()
>    at System.IO.Pipelines.BufferSegment.ResetMemory()
>    at System.IO.Pipelines.Pipe.CompletePipe()
>    at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
>    at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
>    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.StartAsync(IConnectionDispatcher connectionDispatcher)
> ```

**Comment by halter73** [comment]
@seanmars What version of the dotnet runtime and Kestrel were you running when you saw this error? Are you able to repro this consistently?

**Comment by seanmars** [comment]
@halter73 the dotnet --info is below, and it 100% happened when i startup the server and accessed the website and ctrl+c the service immediately.
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.0-preview4-004233 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by seanmars** [comment]
Hi, I found the point that caused the problem, It's the `NLog`.
If i use the following script the call the `NLog.LogManager.Shutdown();` in the block of finally, it will must happened when i starpup the server and access some api/webview and close server immediately.

```
            try
            {
                BuildWebHost(args).Build().Run();
            }
            catch (System.Exception ex)
            {
                throw;
            }
            finally
            {
                NLog.LogManager.Shutdown();
            }
```

**Comment by muratg** [comment]
@seanmars could you please share a simple app that reproduces this problem on GitHub? Thanks.

**Comment by 0x53A** [comment]
I have the same (or a similar) issue: it prints a scary red error, but the exception is caught internally and doesn't actually hurt. It occurs ~90% of the time.

```
C:\Users\lr>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007363 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007589 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007597 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

To reproduce, run [Koala.Tests](https://github.com/0x53A/Koala/tree/master/Koala.Tests), it is a console exe.

**Comment by seanmars** [comment]
@muratg No problem, and i found it's doesn't matter the `NLog.LogManager.Shutdown()` is called or not.
If the use `NLog` it is 100% get exception.

https://github.com/seanmars/DotNetCoreObjectDisposedException

**Comment by Tragetaschen** [comment]
I just got that exception as well, although with a slightly different stack trace (see below) when I CTRL+C'ed my application. I'm running on Mono 5.4.1.6 on Linux. I'm not using any logger besides the default console logger.

By the time I stopped the app, there was one active SignalR connection via WebSocket.

The exception message (including the `fail:` prefix) is printed seven times. Two of those messages are interleaved. The `info:` message below is the first message after my app has processed SIGINT.


```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 11686.3476ms 101
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[0]
      Unexpected exception in SocketConnection.StartAsync.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryPoolBlock'.
  at System.Buffers.ThrowHelper.ThrowObjectDisposedException (System.Buffers.ExceptionArgument argument) [0x00006] in <4a9f78c2c95d4848a0234fc6d3575269>:0
  at System.Buffers.MemoryPoolBlock.Dispose () [0x0000d] in <4a9f78c2c95d4848a0234fc6d3575269>:0
  at System.IO.Pipelines.BufferSegment.ResetMemory () [0x00000] in <15ef00bc425842ceab342d03d837ed41>:0
  at System.IO.Pipelines.Pipe.CompletePipe () [0x0003e] in <15ef00bc425842ceab342d03d837ed41>:0
  at System.IO.Pipelines.Pipe.CompleteWriter (System.Exception exception) [0x00070] in <15ef00bc425842ceab342d03d837ed41>:0
  at System.IO.Pipelines.Pipe+DefaultPipeWriter.Complete (System.Exception exception) [0x00000] in <15ef00bc425842ceab342d03d837ed41>:0
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<DoReceive>d__22.MoveNext () [0x001f0] in <a7e4f9d63a934612b7d363ff21d11ee0>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <ccc1ca7b16d64c2a80d4b3c13d7667e4>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <ccc1ca7b16d64c2a80d4b3c13d7667e4>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <ccc1ca7b16d64c2a80d4b3c13d7667e4>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <ccc1ca7b16d64c2a80d4b3c13d7667e4>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <ccc1ca7b16d64c2a80d4b3c13d7667e4>:0
  at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection+<StartAsync>d__20.MoveNext () [0x00089] in <a7e4f9d63a934612b7d363ff21d11ee0>:0
```

**Comment by muratg** [comment]
@Tratcher @halter73 could one of you pick this up for investigation please?  Thanks.

**Comment by baal2000** [comment]
FYI: getting infrequent reports of this error in our production. In some instances the call stack like in #2254, in others:

```
 at System.Buffers.ThrowHelper.ThrowObjectDisposedException(ExceptionArgument argument)
 at System.Buffers.MemoryPoolBlock.Dispose()
 at System.IO.Pipelines.BufferSegment.ResetMemory()
 at System.IO.Pipelines.Pipe.CompletePipe()
 at System.IO.Pipelines.Pipe.CompleteReader(Exception exception)
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

**Comment by halter73** [comment]
@muratg Should we move this to the 2.1.3 milestone?

I don't think there's too much to investigate. Since so many customers are reporting seeing this, we should backport https://github.com/aspnet/Common/pull/344/files#diff-708aafde37872ea09e25cfadd4d95f0eL56.

Merging #2619 and backporting #2646 should also fix this issue, but I would make all 3 changes to be safe.

**Comment by shirhatti** [comment]
@halter73 to take this to shiproom

**Comment by muratg** [comment]
This is approved for 2.1.3.
