### ISSUE TITLE
Does Kestrel support urls/hostnames, or it can only listen to a port?

### ISSUE THREAD

**Issue by yaapelsinko** [aspnet/KestrelHttpServer#264]
I'm trying to start ASP.NET 5 web application so that it could be accessible via public internet address, like "http://hostname.dom". 

I don't want it to be acessible via "http://www.hostname.dom", "http://test.hostname.dom", etc. And I have DNS records configured to point server's ip address by "*.hostname.dom" and "hostname.dom" names.

So I start Kestrel with the parameter:
server.urls=http://hostname.dom

I expect it to ignore any address that is not "http://hostname.dom", but application is available by every "http://justanything.hostname.dom" address and even just by IP address. So it is listening for all requests to 80 port rather than requests to a specific hostname. For example, when configuring IIS site bindings, you can specify binding like "hostname.dom" and it will ignore any other possible prefixes until you specify them explicitly.

Does Kestrel support urls/hostnames, or it can only listen to a port?

**Comment by Tratcher** [comment]
You're correct, it discriminates by ip and port, not host name. WebListener supports this if you need it. Otherwise you can just check the host header yourself and send 503's.

**Comment by yaapelsinko** [comment]
WebListener seems to be Windows-only (I run the application on a Linux-based server), but I've found also a solution involving nginx. Looks like it works too. Link, if anyone facing the same question: http://druss.co/2015/06/asp-net-5-kestrel-nginx-web-server-on-linux/
