### ISSUE TITLE
http/2: Create automation to run h2spec

### ISSUE THREAD

**Issue by shirhatti** [aspnet/KestrelHttpServer#2640]
Initial goal is to create baseline automation and disable it on the CI.
Look at what Websockets has done with Autobahn tests

**Comment by Tratcher** [comment]
https://github.com/summerwind/h2spec

**Comment by Tratcher** [comment]
@muratg are you OK with checking in the pre-compiled binaries for h2spec?
https://github.com/summerwind/h2spec/releases

That seems preferable to having to build them on the fly.

**Comment by shirhatti** [comment]
Can't we do what we've done for libuv? Or is that not worth the complexity?

**Comment by Tratcher** [comment]
This is quite different from libuv, it's a test only tool, not something we want to ship. It also has additional dependencies if we try to build it from source like installing the Go compiler.

The tests run in seconds so I'd like to enable them as normal functional tests in every test pass. It'll be more reliable if the binaries were always available and you didn't have to install the Go compiler on every machine.

**Comment by muratg** [comment]
@Tratcher let's sync-up when you're in office on that part.

**Comment by Tratcher** [comment]
Offline notes: There's been no updates to h2spec for over a year now. We can hand role a nupkg, put it on myget, and reference it from the tests.
