### ISSUE TITLE
Kestrel works very slow when it is operating under IIS

### ISSUE THREAD

**Issue by san-sei** [aspnet/KestrelHttpServer#2642]
We are facing a strange problem with using Kestrel under IIS in which some operations (e.g. getting access CA- [CertEnrolllib ](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374850(v=vs.85).aspx)) take about 100 sec processing time to be complete.
Please note that everything works well with using IIS Express and also [http.sys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.1) (instead of IIS) where every operation takes maximum 5 seconds to be complete.

**Comment by san-sei** [comment]
Here is the code for an action that works on the aforementioned library CertEnrolllib for certificate enrollment purpose.
```
    public class TestController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            var s = Stopwatch.StartNew();
            var type = Type.GetTypeFromProgID("X509Enrollment.CX509CertificateRequestPkcs10");
            var instance = Activator.CreateInstance(type);
            type.InvokeMember("InitializeFromTemplateName",
                BindingFlags.InvokeMethod,
                null,
                instance,
                new object[] { 1, "CertEnrollment" });

            s.Stop();
            return Content(s.ElapsedMilliseconds.ToString());
        }
    }
```

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Home#3188
