### ISSUE TITLE
BadHttpRequestException: Request body too large causes an ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by smartcodinghub** [aspnet/KestrelHttpServer#2643]
Hi all,

When I try to upload a file bigger than my [RequestSizeLimit(10_000_000)] it goes through all the pipeline but it wasn't being redirected by the ExceptionHandler middleware. After a bit of investigation, the Exception Handler goes well but the connection gets reset.

I'm using .Net Core 2.1. Pipeline:

```
if(env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseExceptionHandler("/Home/Error");
}
else
{
    app.UseExceptionHandler("/Home/Error");
}

/* Caching */
app.UseResponseCompression();

/* Static files and resource */
app.UseDefaultFiles();
app.UseStaticFiles(new StaticFileOptions
{
    OnPrepareResponse = ctx =>
    {
        const string header = "public,max-age=3600";// An hour
        ctx.Context.Response.Headers[HeaderNames.CacheControl] = header;
    }
});

/* Authentication */
app.UseAuthentication();

app.UseSession();

/* Mvc */
app.UseMvcWithDefaultRoute();
```

My method is decorated with:

```
[HttpPost]
[ValidateAntiForgeryToken]
[RequestSizeLimit(10_000_000)]
```

Am I doing something wrong or is it a bug?

**Comment by Tratcher** [comment]
Are you using chunked or content-length for the upload? What's the client?

The server will stop reading the request body after the size limit is reached. Many clients don't try to read the response until the request body completes so they might not be able to observe the response you send.

**Comment by smartcodinghub** [comment]
Hi! 

I'm using Chrome and Opera (Chromium). So, how can I handle this scenario?

The request headers are:

Request URL: https://localhost/Home/Upload
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryEv14aEBOom9V2mdY
Origin: https://localhost
Referer: https://localhost/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36 OPR/53.0.2907.68
X-DevTools-Emulate-Network-Conditions-Client-Id: FFF3DE85B793AD899E3BE38F9AA26589

**Comment by Tratcher** [comment]
If it's streaming the file without a content-length header then it has to send that 10gb or data before it fails.

Have you considered doing some client side validation to avoid sending the data at all?
https://stackoverflow.com/questions/3717793/javascript-file-upload-size-validation

**Comment by smartcodinghub** [comment]
Yes I did, but the client side validation didn't replace server side (as the method can be called without UI). The file I'm streaming is about 36 Mb to make it fail, the attribute says 10 Mb max, not 10 Gb. 

¿There's no workaround for this kind of validations to work reliable? I'm using an standard browser. I'm using a simple form submision, but I can use JS to submit programatically if needed.

**Comment by smartcodinghub** [comment]
> If it's streaming the file without a content-length header then it has to send that 10gb of data before it fails.

However, How can I set the Content-Length header when I'm using a `<form id="form-upload" method="post" enctype="multipart/form-data" action="/Home/Upload">`? Can I do it with some JS?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
