### ISSUE TITLE
ThrowResponseAlreadyStartedException while setting StatusCode in a Controller method

### ISSUE THREAD

**Issue by nockawa** [aspnet/KestrelHttpServer#2667]
My use case is pretty simple, I have a method from an asp.net core 2.1 controller that is call for a given `post` request. 

All I want to do is write some binary data in the `Response.Body` and set the `Response.StatusCode`.

No matter what I try it throws a `ThrowResponseAlreadyStartedException` stating: 

`StatusCode cannot be set because the response has already started.`

All I want to do is something like this:

```csharp
Response.ContentType = "application/octet-stream";
Response.Body.Write(someData, 0, someData.Length);
Response.StatusCode = (int) HttpStatusCode.OK;
```
Maybe I'm not using the right way to write binary data in the Response's body but that's the only one I came up with. Changing the signature of my method to return `Task<ActionResult<byte[]>>` won't do the trick to return binary data.

**Comment by nockawa** [comment]
Thing is in this specific case, I need to write to the body first, then the StatusCode depends on something else.
For the async, I wasn't sure it worth as it's a small protobuf buffer...

**Comment by nockawa** [comment]
and by the way, if I return the data on the method return like this:
`return Ok(myBinaryArray)`

I get this in the debug console:

```
warn: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[1]
      No output formatter was found for content type 'application/octet-stream' to write the response.
VoxelService: Warning: No output formatter was found for content type 'application/octet-stream' to write the response.
warn: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      No output formatter was found for content type 'application/octet-stream' to write the response.
```

But I've added this and no change....

```csharp
services.AddMvc(options =>
            {
                options.OutputFormatters.Add(new StreamOutputFormatter());
            })
```

**Comment by nockawa** [comment]
@benaadams WriteAsync doesn't change anything... I'll try to take a look at the implem behind but so far I don't understand the logic behind this. Why can't I set the body's content then set the Status Code?
Thanks for helping

**Comment by davidfowl** [comment]
The response body isn’t buffered m. When you write it will be written (with headers and the start line) to the client.

**Comment by nockawa** [comment]
@benaadams yes, it totally makes sense, I thought about this afterward. Initially, I thought it wouldn't matter because I was in a Controller and not a middleware, but afterward I realized it was the only way to achieve great performances to process everything in order.

@davidfowl is that normal that I can't return a `byte`[] with a body content type of `application/octet-stream` and expect this to work? 

Because the whole initial 'issue' is because of this. I initially wanted to mark the response content as octet-stream, set the Status Code and return a `byte[]` for the data but I never got it worked, so I tried different approach with the Body's stream.

**Comment by davidfowl** [comment]
Seems like an mvc question. You’d need to show the original code you wrote.

There’s nothing special here at the kestrel level.

**Comment by nockawa** [comment]
> Seems like an mvc question. You’d need to show the original code you wrote.
Do you want me to post an issue on the corefx repo?

In the meantime, here's the code:
```csharp
        [Route("cell/{constructId}/{x}/{y}/{z}/{h}/version")]
        [HttpGet]
        public async Task<ActionResult<byte[]>> GetCellHashAndVersion(ulong constructId, long x, long y, long z, byte h)
        {
            // Return the Cell Model, we should always get on, whether the cell is new or not
            var cell = await _service.GetCellAsync(constructId, x, y, z, h);

            // Setup the response
            Response.ContentType = "application/octet-stream";
            using (var ms = new MemoryStream(2048))
            {
                cell.ToPBCellVersion(ms);
                return Ok(ms.ToArray());
            }
        }
```

Doing this display this warning message :
```
warn: Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector[1]
      No output formatter was found for content type 'application/octet-stream' to write the response.
VoxelService: Warning: No output formatter was found for content type 'application/octet-stream' to write the response.
warn: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      No output formatter was found for content type 'application/octet-stream' to write the response.
```
With a Status Code of 406 (I believe this is due to the OutputFormatter not willing to deal with `byte[]`)
Again, I've added this formatter `options.OutputFormatters.Add(new StreamOutputFormatter());`

**Comment by davidfowl** [comment]
@nockawa for future reference MVC issues go here (https://github.com/aspnet/Mvc).

Seems like MVC doesn't support that content type, the StreamOutputFormatter is for Streams, not `byte[]`. https://github.com/aspnet/Mvc/blob/6df28ef09a9d50e4601fc832a787b6d5c6635dc9/src/Microsoft.AspNetCore.Mvc.Core/Formatters/StreamOutputFormatter.cs#L24

```C#

public class HomeController : Controller
{
    [HttpGet("/bin")]
    [Produces("application/octet-stream")]
    public byte[] GetBin()
    {
        return Encoding.UTF8.GetBytes("Hello World");
    }

    [HttpGet("/bin2")]
    public Task GetBinRaw()
    {
        Response.ContentType = "application/octet-stream";
        var buffer = Encoding.UTF8.GetBytes("Hello World");
        return Response.Body.WriteAsync(buffer, 0, buffer.Length);
    }

    [HttpGet("/bin3")]
    [Produces("application/octet-stream")]
    public Stream GetBinStream()
    {
        return new MemoryStream(Encoding.UTF8.GetBytes("Hello World"));
    }
}
```

Seems like MVC just doesn't support returning a `byte[]` directly. The other 2 methods work.

/cc @rynowak for more info

**Comment by davidfowl** [comment]
@nockawa if you want to avoid allocations, you can write directly to the response stream.

**Comment by nockawa** [comment]
@davidfowl thanks for all the help, I think I'll manage from there.
I still do think that returning byte[] should automatically translate to set the `ContentType` as `application/octet-stream` and copy the result in the internal Stream. I assume it's what is done for text counterpart.

**Comment by davidfowl** [comment]
> @davidfowl thanks for all the help, I think I'll manage from there.
I still do think that returning byte[] should automatically translate to set the ContentType as application/octet-stream and copy the result in the internal Stream. I assume it's what is done for text counterpart.

Agreed. File an issue on MVC. I'm not sure why we don't support `byte[]` but Stream works.

**Comment by nockawa** [comment]
that's what I'm doing right now! :) I just make sure I give all the details I can
