### ISSUE TITLE
Response Body written to by Middleware not returned

### ISSUE THREAD

**Issue by johnkwaters** [aspnet/KestrelHttpServer#2676]
I have a net core 2.1 middleware that does this:

```
        public async Task InvokeAsync(HttpContext context, IUserSession session)
        {
            if (context.User.Identity.IsAuthenticated && session.TenantId>0)
            {
                var path = context.Request.Path;

                if (!session.IsConsentGranted)
                {

                }

                if (!session.IsEmailValidated)
                {
                    if (!_validPathsForNonValidatedEmail.Any( p => p.Equals(path, StringComparison.InvariantCultureIgnoreCase)))
                    {
                        if (!context.Response.HasStarted)
                        {
                            using (var writer = new StreamWriter(context.Response.Body))
                            {
                                context.Response.StatusCode = (int)HttpStatusCode.Forbidden;
                                context.Response.ContentType = "application/json";
                                await writer.WriteAsync(JsonConvert.SerializeObject(
                                    new ServerError
                                    {
                                        Code = 1,
                                        Error = "User email has not been validated. Please confirm email."
                                    }));
                            }
                            return;
                        }
                    }
                }
            }

            // Call the next delegate/middleware in the pipeline
            await _next.Invoke(context);
        }
```

The 403 status code is returned, but no response body.

I have tried using await context.Response.WriteAsync instead of the StreamWriter, same issue.

What am I doing wrong?

**Comment by Tratcher** [comment]
Can you check the request logs and share a Fiddler trace ?

**Comment by johnkwaters** [comment]
Found a smoking gun... but don't understand it!

If I put Cors BEFORE my module...it works!

                .UseCors("AllowAllCorsPolicy")
                .UseCheckAccountStatus()

When Cors is after, my angular client gets a 403 on the GET with NO BODY... and some console errors about CORS...

![image](https://user-images.githubusercontent.com/3422637/41620136-a0445294-73bd-11e8-9df3-7141b68ab5d8.png)

**Comment by Tratcher** [comment]
That's what CORS does, it fails requests that don't have the correct CORS headers.

**Comment by johnkwaters** [comment]
So as I originally had it, my code was short circuiting the CORS handler, that much I get. But how come the client saw the 403 response code (in the network tab), but the response body was not returned? That's the part I don't get. What code is cleaning out the response body I had written?

**Comment by johnkwaters** [comment]
![image](https://user-images.githubusercontent.com/3422637/41620597-07d1c486-73bf-11e8-9e3c-7f2c73b43a56.png)

![image](https://user-images.githubusercontent.com/3422637/41620605-10dbd95e-73bf-11e8-9034-9afbd2536508.png)
