### ISSUE TITLE
How to make -p priority work for journalctl when you manage using systemd

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/KestrelHttpServer#2679]
On 

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.0&tabs=aspnetcore2x

you show how to use journalctl, but not how to be able to filter using priority like Errors and higher. Also see question on stackoverflow.

https://stackoverflow.com/questions/50963198/how-to-filter-journalctl-logs-for-errors-for-aspnet-core-application-hosted-on-l

**Comment by halter73** [comment]
Interesting. It seems systemd will log all stdout from its processes with the [info priority by default](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#SyslogLevel=) unless the first line of the output is prefixed with [<{Priority Number}>](https://www.freedesktop.org/software/systemd/man/sd-daemon.html). Maybe we should add support for syslog compatible priority numbers to our console logger.

In the meantime, you could try to [set up serilog](https://github.com/serilog/serilog-aspnetcore) and log to syslog directly using [one of the third-party sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks).

**Comment by tmds** [comment]
I wrote a Microsoft.Extensions.Logging compatible logger for systemd: Tmds.Systemd.Logging.
It is built for .NET Core 2.1+.
It will make the priorities work, it also does structured logging.
Log entries look like:
```js
{
	"PRIORITY" : "6",
	"SYSLOG_IDENTIFIER" : "dotnet",
	"LOGGER" : "Microsoft.AspNetCore.Hosting.Internal.WebHost",
	"EVENTID" : "1",
	"MESSAGE" : "Request starting HTTP/1.1 GET http://localhost:5000/  ",
	"PROTOCOL" : "HTTP/1.1",
	"METHOD" : "GET",
	"SCHEME" : "http",
	"HOST" : "localhost:5000",
	"PATHBASE" : "",
	"PATH" : "/",
	"QUERYSTRING" : "",
	"REQUESTPATH" : "/",
	"CONNECTIONID" : "0HLDSN5JGSU79",
	"REQUESTID" : "0HLDSN5JGSU79:00000001"
}
```
You can find more info at https://github.com/tmds/Tmds.Systemd.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
