### ISSUE TITLE
Lowercase logic modifies non-letter characters in header names

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#2684]
The current logic applies the lowercase mask: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/Internal/Http2/HPack/HPackEncoder.cs#L144. But this logic does not check whether the character is a letter and can change non-letter symbols. For example, it would change `^` to `~` in header names. The fix would be to ensure that the lower case mask is only applied for upper case letters. We can also consider checking for invalid characters in the header here as well.

**Comment by Tratcher** [comment]
The response header character set is validated as the headers are added to the collection. Are there any allowed characters being altered? E.g. `-`?
