### ISSUE TITLE
Kestrel functional tests are flakier in the Win10-Universe build configuration

### ISSUE THREAD

**Issue by dougbu** [aspnet/KestrelHttpServer#2685]
Not sure if this is an issue with the build configuration or the tests themselves. But http://aspnetci/viewType.html?buildTypeId=XPlat_Windows_Win10Universe&tab=buildTypeHistoryList shows recent builds have almost all failed with test failures in the `Microsoft.AspNetCore.Server.Kestrel.FunctionalTests` namespace.

The failures are not particularly consistent beyond their shared namespace / test project. For example `AddressRegistrationTests` holds many of the failing tests. But, that test class isn't among the culprits for all failed builds and the individual tests vary quite a lot.

I've also seen that some of the sometimes-failing tests are flakier in this particular configuration. For example, http://aspnetci/project.html?projectId=XPlat&testNameId=5785442856196240460&tab=testDetails shows that `AddressRegistrationTests.DefaultsServerAddress_BindsToIPv4` passes 99.8% of the time in all Test build configurations. That rate drops to 98.6% when focusing only on Win10-Universe (http://aspnetci/project.html?tab=testDetails&testNameId=5785442856196240460&projectId=XPlat&buildTypeId=XPlat_Windows_Win10Universe). The success rate also looks much worse in builds from the 21st on.

**Comment by dougbu** [comment]
@muratg @ryanbrandenburg this issue covers the remaining flaky tests I noticed over the weekend aka the "pattern" as you described it @muratg. Filed it here because so many of the failures I saw were in one place after I skipped a couple of MvcPrecompilation tests. Of course, issue may still be a quirk of this build configuration.

**Comment by ryanbrandenburg** [comment]
[Looks like](http://aspnetci/viewLog.html?buildId=491868&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId5785442856196240460) standard port binding failures.

**Comment by muratg** [comment]
Why would it be more common with Windows 10?

**Comment by Tratcher** [comment]
It could be an agent issue, there's only one Win10 agent.

**Comment by ryanbrandenburg** [comment]
This problem [continues](http://aspnetci/project.html?tab=testDetails&testNameId=6175992477770058243&projectId=AspNetEf&page=1).

**Comment by JunTaoLuo** [comment]
These address binding tests should be more reliable after 0e99235 moved the binding tests to their own test group.
