### ISSUE TITLE
Kestrel as a service in Centos 7 .netCore 2.1

### ISSUE THREAD

**Issue by popraducj** [aspnet/KestrelHttpServer#2687]
I am using a centos 7 distribution and i just updated the .netcore sdk to 2.1.301. After the update I have a strang behaivior.:
If my app is runing with dotnet run from cli or console it run as expected and static files are displayed.
If the app is run from Kestrel as a service the app does not find the static files(images/js files) or see them as html/text (css files).
The errors that I'm getting in web browser console are:
Refused to apply style from 'http://localhost:5000/css/site.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled
Failed to load resource: the server responded with a status of 404 (Not Found) - for images and js files.

I have tried to add Microsoft.AspNetCore.StaticFiles as a package but with no luck.

I have to mention that I did not change the code after upgrade. I had to upgrade the sdk to .net 2.1 because I am using NWebsec.  

kestrel service configuration looks like this:
`   [Unit]
    Description=Example .NET Web API Application running on CentOS 7

    [Service]

    ExecStart=/usr/bin/dotnet /home/user/Release/Website.dll
    Restart=always
    # Restart service after 10 seconds if dotnet service crashes
    RestartSec=10
    SyslogIdentifier=dotnet-example
    User=radu
    Environment=ASPNETCORE_ENVIRONMENT=Production 

    [Install]
    WantedBy=multi-user.target`
As a side note /usr/bin/dotnet is linked to /usr/shared/dotnet/dotnet.
The project was published with dotnet publish -o home/user/Release/ -c Release
I don't understand what is the difference  when I run the app with dotnet run and as a service.

Any ideas how can I make this work?

**Comment by Tratcher** [comment]
If you check the stdout logs what does it say the content root directory is?

**Comment by popraducj** [comment]
i know this my sound foolish but I don't know how I can  see stdout logs on centos 7. If I  look into journalctl service I have nothing about contentRoot.

In Program.cs I am using this:

                ```
.UseStartup<Startup>()
                .UseContentRoot(Directory.GetCurrentDirectory())
```

**Comment by popraducj** [comment]
Ok found something.. the Directory.GetCurrentDirectory() return "/" instead of /home/user/Release/ which is strange. Once I have change Directory.GetCurrentDirectory() with "/home/user/Release/" it worked this is so strange. I does not work as expect. If for production I need some configuration and for debug I need another one.

**Comment by muratg** [comment]
@popraducj I assume you're aware of this doc: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x ?

@shirhatti, @guardrex  We may want to add `contentroot` instructions to that doc.  Windows one [here](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1#get-started) already has it, but Linux one does not.

**Comment by popraducj** [comment]
@muratg yes I am well aware of it. my problem was not how i should host I think is most of a bug. That on linux(Centos7, the distro that i'm using) with Kestrel Directory.GetCurrentDirectory() return the  root  directory, not the directory in which the app is running.

**Comment by shirhatti** [comment]
Looking over the linux doc again, our guidance has been to set the working directory in the systemd service definition file.
So while it does work, we could do a **much** better warning folks about this.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
