### ISSUE TITLE
Memory limits for embedded server

### ISSUE THREAD

**Issue by DwayneBull** [aspnet/KestrelHttpServer#2688]
We run several game servers and are trying out kestrel as a way to access stats and perform requests on each server, we do this by embedding kestrel in our normal console app ( net core 2.1 )

The problem we have is that kestrel will eat all of the memory it can get its hands on and if we disable server GC we get other issues with GC causing slowdowns for the game server due to cpu spikes.

Is there any way to run kestrel and define an internal limit for memory? or stop it from just using everything it can find? We need to have a large amount of free memory for the game to run well.

**Comment by benaadams** [comment]
If you can run it a separate process (start it from the console app, and shut it down when the console app is shutting down); then on Windows you can create a [Job object](https://docs.microsoft.com/en-us/windows/desktop/ProcThread/job-objects); limit its memory and assign the Kestrel process to that, [the GC will then respect the Job object's memory](https://blogs.msdn.microsoft.com/maoni/2016/05/23/job-support-in-the-gc/)

**Comment by DwayneBull** [comment]
We run on ubuntu inside docker. A separate process/container isn't really feasible as we would need to construct an additional communication layer, we are using kestrel to avoid doing that.
At the moment we have to use the game servers own TCP protocol and write custom admin requests that have to be proxyed from a web server, having kestrel sit next to the game server would allow us to call http requests directly to the game server, a very helpful feature as it removes the need for any proxy http->custom tcp bridge.

**Comment by DwayneBull** [comment]
Yeah, ideally it would be nice to set a limit via code/config/environment so that it could sit alongside other code without starving other elements.

**Comment by halter73** [comment]
@DwayneBull Do you have any memory dumps from a situation where you feel Kestrel is using too much memory?

**Comment by DwayneBull** [comment]
I don't have any, but I will try and get some. It's obvious its kestrel though as toggling it on and off causes memory to climb. I've had that issue when using kestrel "normally" and just switched to workstation GC to cure it.

**Comment by tmds** [comment]
> We run on ubuntu inside docker.

.NET Core detects Docker/cgroup limits, so you can [set the memory limits on your container](https://docs.docker.com/engine/reference/run/#user-memory-constraints).

**Comment by DwayneBull** [comment]
@tmds See above; That won't work as its running in the same process.

**Comment by davidfowl** [comment]
> It's obvious its kestrel though as toggling it on and off causes memory to climb.

Climb how? To a limit? Does it keep growing?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
