### ISSUE TITLE
AuthenticationException with Client Cert Auth, only in Chrome

### ISSUE THREAD

**Issue by WasserEsser** [aspnet/KestrelHttpServer#2697]
Hi,

I'm not quite sure if this is the right repository for this, excuse me if it isn't.

I'm having issues implementing client certificate authentication in ASP.NET Core using Kestrel.
More specifically, I'm getting an exception (System.Security.Authentication.AuthenticationException) when connecting to the server via Chrome with a client certificate. Using Firefox or Edge/IE with the same client certificate works fine. 
When digging into it using Wireshark, the only real difference I can find is that Firefox and Edge are using ecdsa_secp256r1_sha256 as the signature algorithm in the Certificate Verify message while Chrome uses ecdsa_secp384r1_sha384.

This is the stack trace when connecting via Chrome:

> Microsoft.AspNetCore.Server.Kestrel[0]
>       Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The token supplied to the function is invalid
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
>    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
>    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
>    at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
>    at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.FrameConnection.<ApplyConnectionAdaptersAsync>d__50.MoveNext()

Is the signature algorithm supported here? 

Any other ideas what could cause this? 

Chrome is not really helping in debugging this as the only thing it is reporting is ERR_CONNECTION_CLOSED.

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#30847
