### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Core depends simultaneously on both System.Numerics.Vectors nuget package version 4.4.0 and 4.5.0 - the wrong one can end up in the bin dir causing programs not to start

### ISSUE THREAD

**Issue by borland** [aspnet/KestrelHttpServer#2698]
`Microsoft.AspNetCore.Server.Kestrel.Core 2.1.1` depends on nuget package `System.Numerics.Vectors 4.5.0` (assembly is actually System.Numerics.Vectors 4.1.4.0)
*aside: I wish microsoft would please stop mismatching nuget and assembly versions, it makes dependency issues incredibly hard to track down and is super confusing*

`Microsoft.AspNetCore.Server.Kestrel.Core 2.1.1` also depends on package `System.Memory 4.5.1` which in turn depends on `System.Numerics.Vectors 4.4.0` (assembly version 4.1.3.0)

Reference: https://www.fuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Core/2.1.1

Note: aspnetcore 2.1.0 also has this same issue.

This manifests itself in our product (running on desktop framework 4.6.1 targeting netstandard2.0) as randomly sometimes getting different versions of `System.Numerics.Vectors` copied into our debug\bin or release\bin directory. We have an assembly binding redirect to target `System.Numerics.Vectors 4.1.4.0`, which mostly works, but sometimes visual studio/msbuild decides to drop 4.1.3.0 into the bin directory instead and our app crashes on startup with an assembly version mismatch exception.

I haven't been able to determine why exactly sometimes S.N.V 4.1.4.0 is copied and why other times 4.1.3.0 is copied.
I tried putting an explict dependency on the S.N.V 4.5.0 nuget package into our application, to try and force 4.1.4.0 to get put there, however it didn't solve the problem and 4.1.3.0 would sometimes get put there.

So - Could the versions of `System.Numerics.Vectors` please be aligned so that kestrel only depends on a single version?

Also, is there any workaround or something we can do to reliably control which version ends up in the bin dir? I don't mind which version it is, but it needs to be consistent or the assembly binding redirect in our app config will be wrong :-(

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
