### ISSUE TITLE
Flaky test: CanReadAndWriteWithHttpsConnectionAdapter

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2701]
This test [fails](http://aspnetci/viewLog.html?buildId=498343&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
---- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.IO.StreamReader.ReadBufferAsync()
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at Microsoft.AspNetCore.Testing.HttpClientSlim.ReadResponse(Stream stream)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.PostAsync(Uri requestUri, HttpContent content, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.PostAsync(String requestUri, HttpContent content, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsConnectionAdapterTests.CanReadAndWriteWithHttpsConnectionAdapter() in /_/test/Kestrel.FunctionalTests/HttpsConnectionAdapterTests.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
------- Stdout: -------
| [0.002s] TestLifetime Information: Starting test CanReadAndWriteWithHttpsConnectionAdapter at 2018-07-06T03:07:01
| [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [1.185s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLF2TM3SL8AI" started.
| [1.200s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.0 POST https://localhost:55865/ application/x-www-form-urlencoded 22
| [1.200s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLF2TM3SL8AI" received FIN.
| [1.200s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLF2TM3SL8AI" disconnecting.
| [1.200s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLF2TM3SL8AI" sending FIN.
| [1.204s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [1.205s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLF2TM3SL8AI", Request id "0HLF2TM3SL8AI:00000001": started reading request body.
| [1.205s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLF2TM3SL8AI", Request id "0HLF2TM3SL8AI:00000001": done reading request body.
| [1.205s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 5.1166ms 200 
| [1.205s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLF2TM3SL8AI" stopped.
| [1.298s] TestLifetime Information: Finished test CanReadAndWriteWithHttpsConnectionAdapter in 1.2952046s
```

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=514169&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanReadAndWriteWithHttpsConnectionAdapter [failed again](http://aspnetci/viewLog.html?buildId=515831&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Http10KeepAliveNotHonoredIfResponseContentLengthNotSet [failed again](http://aspnetci/viewLog.html?buildId=516438&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=517251&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=517539&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanReadAndWriteWithHttpsConnectionAdapter [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed again](http://aspnetci/viewLog.html?buildId=519454&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed with about the same error](http://aspnetci/viewLog.html?buildId=520819&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed with about the same error](http://aspnetci/viewLog.html?buildId=522517&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanReadAndWriteWithHttpsConnectionAdapter [failed with about the same error](http://aspnetci/viewLog.html?buildId=522663&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestRequestHeadersTimeout [failed with about the same error](http://aspnetci/viewLog.html?buildId=522858&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AllowCertificateContinuesWhenNoCertificate [failed with about the same error](http://aspnetci/viewLog.html?buildId=522955&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=524443&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CanReadAndWriteWithHttpsConnectionAdapter [failed with about the same error](http://aspnetci/viewLog.html?buildId=525059&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=525835&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=526800&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=527419&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=529078&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=529592&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=531094&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=531920&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=533282&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=534415&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=535429&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=536014&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=536808&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=536995&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=537820&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=539104&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
@JunTaoLuo is this resolved?

**Comment by JunTaoLuo** [comment]
This is a different bug than the one I closed. I have not yet looked into this mode of failure so keep it open.

**Comment by ryanbrandenburg** [comment]
Please assign yourself to issues you're working on so we can easily find out who to contact.

**Comment by muratg** [comment]
Is this resolved? Doesn't seem to be failing anymore (or maybe it's reported on a different issue now?)

**Comment by JunTaoLuo** [comment]
We are going to retry these tests while the underlying investigation is ongoing. I'll file an issue to remove the retries when the issue is fixed.
