### ISSUE TITLE
Http2 perf setup

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2704]
Scenarios:
- Most of the exiting 1.1 scenarios should translate with a few modifications
  - Pipelining is the default (Multiplexing)
  - Fewer connections, more requests per connections?
  - Flow control tweaks?
- Http & Https
- Memory usage under load

We need to get Flow Control up and running before we can run any stress or perf scenarios.

edit: Added one more scenario (muratg)

**Comment by JunTaoLuo** [comment]
cc @sebastienros since he's doing a lot of the work.
