### ISSUE TITLE
Unable to use HTTPS certificate with Kestrel indocker

### ISSUE THREAD

**Issue by VenkateshSrini** [aspnet/KestrelHttpServer#2725]
Hi,
I have been trying to dockerize a Simple ASP.NET core API app running Kestrel with Https enabled. I have followed all the instructions available but nothing seems to work. A detailed issue is created here
[Docker with HTTPS ASP.NET Core 2.1](https://github.com/dotnet/dotnet-docker/issues/630#issuecomment-404865564). The link also provides the code and various methods that we are trying to get it working. 

Please help us in this regard

**Comment by Naragato** [comment]
Out of interest does your assembly name differ from your project name?

**Comment by VenkateshSrini** [comment]
@Naragato,
They are the same. You can see the code from here https://1drv.ms/u/s!AoG_S7xXx9nDhNITgRCH9z7tLzPsRw. There is a deploy.cmd in the project that has all the information as how we deploy the app to docker.

**Comment by javiercn** [comment]
@VenkateshSrini Your docker-compose file is not correct.
The key for the development certificate is Development and you don't have to specify the path.
You can specify the path and the password with Default, but then you need to provide the path to the certificate appropiately. In your case, it's trying to look for the file in your project folder.

```yaml
- ASPNETCORE_Kestrel__Certificates__Development__Password="crypticpassword"
```

**Comment by VenkateshSrini** [comment]
@javiercn,

Thanks you made it. It is working now. I need another help. In production the certificate is loaded in d:\certs. Now how do I make the docker image load the certificate from that path. Could you please put that instructions for me please.

**Comment by javiercn** [comment]
Closing the issue as the problem has been resolved.

@Rick-Anderson Can you help @VenkateshSrini there should be docs for how to do this, but I can't find them.

**Comment by VenkateshSrini** [comment]
Hi @Rick-Anderson , @javiercn ,
I definitely need some guidance here. Please share the same. Please let me know if  need to raise a new issue for this as I see this issue is closed.

**Comment by VenkateshSrini** [comment]
Hi,
I was able to get the same working. The sample code is at https://1drv.ms/u/s!AoG_S7xXx9nDhNITjOTbIKONyO006Q
