### ISSUE TITLE
Normalize URL

### ISSUE THREAD

**Issue by troydai** [aspnet/KestrelHttpServer#273]
It doesn't seem to me that Kestrel normalizes URL.

**Comment by muratg** [comment]
Can you give some details?  A few examples?

cc @Tratcher

**Comment by Tratcher** [comment]
https://www.ietf.org/rfc/rfc3987.txt
5.3.2.2.  Character Normalization
And maybe
5.3.2.4.  Path Segment Normalization

**Comment by muratg** [comment]
@Tratcher @troydai Do we need to do this? What's the user impact if we don't do it?

**Comment by Tratcher** [comment]
That's more a question for @blowdart. We're un-escaping arbitrary Unicode from remote users. Normalization helps avoid lots of known issues with strange unicode combinations. http://unicode.org/faq/normalization.html

**Comment by muratg** [comment]
@blowdart Please advise :smile:

**Comment by blowdart** [comment]
You must normalize. Just like IIS does.

**Comment by cesarbs** [comment]
Do we want to preserve the original URL as a field in the context i.e. the original bytes and path before normalization and dot segment removal?

**Comment by Tratcher** [comment]
Not right now.

**Comment by DamianEdwards** [comment]
Need for RC2
