### ISSUE TITLE
Flaky test: OnCompletedCallbacksAreCalledInLastInFirstOutOrder

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2749]
This test [fails](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.StreamReader.ReadBufferAsync()
   at System.IO.StreamReader.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Testing.TestConnection.ReceiveEnd(String[] lines) in /_/test/shared/TestConnection.cs:line 157
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.OnCompletedCallbacksAreCalledInLastInFirstOutOrder(ListenOptions listenOptions) in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 2742
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test OnCompletedCallbacksAreCalledInLastInFirstOutOrder-http://127.0.0.1:0 at 2018-07-24T22:27:33
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [0.005s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHMID37HQB" started.
| [0.006s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHMID37HQB" completed keep alive response.
| [0.006s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.2481ms 200 
| [0.006s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFHMID37HQB" received FIN.
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHMID37HQB" disconnecting.
| [0.006s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFHMID37HQB" sending FIN.
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFHMID37HQB" stopped.
| [0.057s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.060s] TestLifetime Information: Finished test OnCompletedCallbacksAreCalledInLastInFirstOutOrder-http://127.0.0.1:0 in 0.0590048s
```

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=514169&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
DoesNotThrowOnFin [failed again](http://aspnetci/viewLog.html?buildId=516243&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
SettingConnectionCloseHeaderInAppDoesNotDisableChunking [failed again](http://aspnetci/viewLog.html?buildId=516729&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RequestFeatureContainsRawTarget [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RequestFeatureContainsRawTarget [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
SettingConnectionCloseHeaderInAppDoesNotDisableChunking [failed again](http://aspnetci/viewLog.html?buildId=519360&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RequestFeatureContainsRawTarget [failed with about the same error](http://aspnetci/viewLog.html?buildId=520819&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RegisterIPEndPoint_Port443_Success [failed with about the same error](http://aspnetci/viewLog.html?buildId=523415&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ServerAcceptsRequestWithHeaderTotalSizeWithinLimit [failed with about the same error](http://aspnetci/viewLog.html?buildId=525059&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=530771&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionClosedTokenFiresOnServerFIN [failed with about the same error](http://aspnetci/viewLog.html?buildId=535429&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
@muratg was this resolved? Please assign someone to find out.

**Comment by muratg** [comment]
@Tratcher @halter73 @JunTaoLuo could one of you guys pick this up?

**Comment by halter73** [comment]
Given that it's been 17 days since the last error, it looks like the creation of the InMemory functional test project significantly reduced the occurrence of the random connection resets from the client like we hoped. Closing.
