### ISSUE TITLE
Mitigate UseIIS conflict

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2760]
Today CreateDefaultBuilder calls UseKestrel and then it calls UseIIS for conditional in-proc support. Each of these register IServer and the last one wins.

The conflict comes when you call UseKestrel again after CreateDefaultBuilder to set some options. This works fine when you run self-host (e.g. on your Mac), but when switch to IIS in-proc (like publishing to Azure) Kestrel replaces IIS in-proc and the server fails to start.

There's a workaround today where instead of calling UseKestrel you can call
```
                builder.ConfigureServices(services =>
                {
                    services.Configure<KestrelServerOptions>(options =>
                    {
                        // ...
                    });
                })
```

Proposal: Promote the workaround to a top level API
```
                builder.ConfigureKestrel(options =>
                {
                    // ...
                })
```

This becomes a drop in replacement for anyone already calling UseKestrel. Discovery would be a problem still, but we could update our samples to help with that.

@shirhatti @halter73 @pakrym @jkotalik

**Comment by halter73** [comment]
Would we deprecate the UseKestrel overload with an options configuration callback?

**Comment by Tratcher** [comment]
That's pretty agressive. Maybe in 3.0 if we saw a lot of people run into this conflict?

**Comment by shirhatti** [comment]
I'm with Chris on this. No need to deprecate it unless it proves to be a pit of failure
