### ISSUE TITLE
Flaky test: ThrowsOnReadAfterConnectionError

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2763]
This test [fails](http://aspnetci/viewLog.html?buildId=517557&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.ThrowsOnReadAfterConnectionError() in /_/test/Kestrel.FunctionalTests/RequestTests.cs:line 510
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.004s] TestLifetime Information: Starting test ThrowsOnReadAfterConnectionError at 2018-07-28T01:16:12
| [0.032s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.052s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.053s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
| [0.056s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK4TJPI61V" started.
| [0.058s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  1
| [0.071s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFK4TJPI61V" reset.
| [0.071s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK4TJPI61V" disconnecting.
| [0.072s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFK4TJPI61V" sending FIN.
| [0.073s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK4TJPI61V", Request id "0HLFK4TJPI61V:00000001": done reading request body.
| [0.074s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLFK4TJPI61V", Request id "0HLFK4TJPI61V:00000001": An unhandled exception was thrown by the application.
| System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() in /_/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs:line 36
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/MessageBody.cs:line 45
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 129
|    --- End of inner exception stack trace ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 133
|    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<>c__DisplayClass14_0.<<ThrowsOnReadAfterConnectionError>b__1>d.MoveNext() in /_/test/Kestrel.FunctionalTests/RequestTests.cs:line 485
| --- End of stack trace from previous location where exception was thrown ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 554
| [0.078s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 19.525ms 0 
| [0.078s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK4TJPI61V" stopped.
| [2.703s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [2.707s] TestLifetime Information: Finished test ThrowsOnReadAfterConnectionError in 2.70312s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517878&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517893&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517880&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyRequestLoggedAsDebug [failed again](http://aspnetci/viewLog.html?buildId=517677&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517546&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517539&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517537&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517997&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517995&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518078&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518080&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517986&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=517984&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518067&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518390&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518377&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518392&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518379&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518375&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518649&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518742&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518744&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518636&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518651&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518638&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518634&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyRequestLoggedAsDebug [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519040&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519048&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518882&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ClientHandshakeFailureLoggedAsDebug [failed again](http://aspnetci/viewLog.html?buildId=518816&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=518812&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519154&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519050&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyRequestLoggedAsDebug [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519046&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519471&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519358&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyRequestLoggedAsDebug [failed again](http://aspnetci/viewLog.html?buildId=519360&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519339&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519305&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519292&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519458&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519452&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519454&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519460&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519492&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519456&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed again](http://aspnetci/viewLog.html?buildId=519572&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=520823&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=522188&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=523386&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=524452&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=525083&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=525877&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=526890&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by halter73** [comment]
Thes failures should be fixed by dotnet/corefx#31685.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=527413&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=528727&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ThrowsOnReadAfterConnectionError [failed with about the same error](http://aspnetci/viewLog.html?buildId=529473&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
