### ISSUE TITLE
Flaky test: AppCanHandleClientAbortingConnectionMidResponse

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2764]
This test [fails](http://aspnetci/viewLog.html?buildId=517722&buildTypeId=Releases_22xPublic_OsxUniverse) occasionally with the following error:
```
Assert.Empty() Failure
Collection: [WriteContext { EventId = ConnectionError, Exception = System.IO.IOException: Protocol wrong type for socket ---> System.Net.Sockets.SocketException: Protocol wrong type for socket
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitable.GetResult() in /_/src/Kestrel.Transport.Sockets/Internal/SocketAwaitable.cs:line 40
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessSends() in /_/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs:line 264
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoSend() in /_/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs:line 207
   --- End of inner exception stack trace ---, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.Kestrel.Transport.Sock"..., LogLevel = Information, ... }]
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.AppCanHandleClientAbortingConnectionMidResponse(ListenOptions listenOptions) in /_/test/Kestrel.FunctionalTests/ResponseTests.cs:line 2504
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AppCanHandleClientAbortingConnectionMidResponse-http://127.0.0.1:0 at 2018-07-28T02:36:06
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.002s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK6BCT8FNS" started.
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
| [0.006s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFK6BCT8FNS" reset.
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK6BCT8FNS" disconnecting.
| [0.006s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Information: Connection id "0HLFK6BCT8FNS" communication error.
| System.IO.IOException: Protocol wrong type for socket ---> System.Net.Sockets.SocketException: Protocol wrong type for socket
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitable.GetResult() in /_/src/Kestrel.Transport.Sockets/Internal/SocketAwaitable.cs:line 40
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessSends() in /_/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs:line 264
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoSend() in /_/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs:line 207
|    --- End of inner exception stack trace ---
| [0.007s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFK6BCT8FNS" sending FIN.
| [3.670s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3665.804ms 200 
| [3.670s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [3.671s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFK6BCT8FNS" stopped.
| [3.673s] TestLifetime Information: Finished test AppCanHandleClientAbortingConnectionMidResponse-http://127.0.0.1:0 in 3.671811s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=523812&buildTypeId=Releases_22xPublic_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=524895&buildTypeId=Releases_22xPublic_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=526628&buildTypeId=Releases_22xPublic_OsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=532556&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=533292&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=536668&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=537534&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppCanHandleClientAbortingConnectionMidResponse [failed with about the same error](http://aspnetci/viewLog.html?buildId=538219&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Tratcher** [comment]
Good to close?

**Comment by halter73** [comment]
Yep. #2845 fixed this. I just didn't want the bot reopening the issue.
