### ISSUE TITLE
Flaky test: AppCanHandleClientAbortingConnectionMidRequest

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2765]
This test [fails](http://aspnetci/viewLog.html?buildId=517539&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): The request was aborted
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<>c__DisplayClass33_0.<<AppCanHandleClientAbortingConnectionMidRequest>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AppCanHandleClientAbortingConnectionMidRequest-http://127.0.0.1:0 at 2018-07-28T02:49:26
| [0.021s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Debug: Connection id "0HLFK6IT8SN2B" started.
| [0.047s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Debug: Connection id "0HLFK6IT8SN2B" disconnecting.
| [0.048s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Debug: Connection id "0HLFK6IT8SN2B", Request id "0HLFK6IT8SN2B:00000001": started reading request body.
| [0.049s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Debug: Connection id "0HLFK6IT8SN2B", Request id "0HLFK6IT8SN2B:00000001": done reading request body.
| [0.051s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Error: Connection id "0HLFK6IT8SN2B", Request id "0HLFK6IT8SN2B:00000001": An unhandled exception was thrown by the application.
| System.Threading.Tasks.TaskCanceledException: The request was aborted ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.<PumpAsync>d__4.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.<CopyToAsync>d__22.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
|    --- End of inner exception stack trace ---
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<CopyToAsyncInternal>d__23.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests.<>c__DisplayClass33_0.<<AppCanHandleClientAbortingConnectionMidRequest>b__1>d.MoveNext()
| --- End of stack trace from previous location where exception was thrown ---
|    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
|    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
|    at Xunit.Assert.<RecordExceptionAsync>d__79.MoveNext()
| [0.051s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.RequestTests Debug: Connection id "0HLFK6IT8SN2B" stopped.
| [0.064s] TestLifetime Information: Finished test AppCanHandleClientAbortingConnectionMidRequest-http://127.0.0.1:0 in 0.0637094s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=517537&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518067&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518375&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518649&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518651&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518638&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518816&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=518812&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519050&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519046&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519358&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519360&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519339&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519452&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519454&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519492&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed again](http://aspnetci/viewLog.html?buildId=519572&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=520895&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=522255&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=523386&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=524443&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=525083&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=525877&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=526890&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by halter73** [comment]
Thes failures should be fixed by dotnet/corefx#31685.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=527419&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=528727&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppCanHandleClientAbortingConnectionMidRequest [failed with about the same error](http://aspnetci/viewLog.html?buildId=529471&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
Looks like this is the same as https://github.com/aspnet/KestrelHttpServer/issues/2766.

The key here is the exception `at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()`. It's likely that this is also fixed by https://github.com/dotnet/corefx/pull/31685. Closing for now.
