### ISSUE TITLE
Test failure: RunIndividualTestCase

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2772]
This test [fails](http://aspnetci/viewLog.html?buildId=523153&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
System.Exception : Test failed: http2/6.9.2; 6.9.2. Initial Flow-Control Window Size
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.H2SpecCommands.RunTest(String testId, Int32 port, Boolean https, ILogger logger) in /_/test/Kestrel.FunctionalTests/TestHelpers/H2SpecCommands.cs:line 211
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests.RunIndividualTestCase(H2SpecTestCase testCase) in /_/test/Kestrel.FunctionalTests/Http2/H2SpecTests.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RunIndividualTestCase-http2/6.9.2/1, HTTPS:False, Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame at 2018-08-03T06:35:28
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.008s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.009s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests
| [0.060s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFP1CUJ1D0Q" started.
| [0.061s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFP1CUJ1D0R" started.
| [0.063s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0R received SETTINGS frame with flags 0x0 and length 6 for stream ID 0
| [0.064s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0R received SETTINGS frame with flags 0x1 and length 0 for stream ID 0
| [0.064s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0R received HEADERS frame with flags 0x5 and length 16 for stream ID 1
| [0.064s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET http://127.0.0.1:33394/  
| [0.065s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.462ms 200 
| [0.065s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0Q received SETTINGS frame with flags 0x0 and length 6 for stream ID 0
| [0.066s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0Q received SETTINGS frame with flags 0x1 and length 0 for stream ID 0
| [0.066s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0Q received SETTINGS frame with flags 0x0 and length 6 for stream ID 0
| [0.067s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0Q received HEADERS frame with flags 0x5 and length 16 for stream ID 1
| [0.067s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFP1CUJ1D0Q received SETTINGS frame with flags 0x0 and length 6 for stream ID 0
| [0.067s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET http://127.0.0.1:33394/  
| [15.068s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFP1CUJ1D0Q" received FIN.
| [15.069s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFP1CUJ1D0Q" sending FIN.
| [15.069s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 15001.4506ms 200 
| [15.069s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFP1CUJ1D0Q" stopped.
| [15.070s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFP1CUJ1D0R" received FIN.
| [15.070s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.H2SpecTests Debug: Hypertext Transfer Protocol Version 2 (HTTP/2)
|                                                                                          6. Frame Definitions
|                                                                                            6.9. WINDOW_UPDATE
|                                                                                              6.9.2. Initial Flow-Control Window Size
|                                                                                                  1: Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame
        × 1: Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame
|                                                                                                  -> The endpoint MUST adjust the size of all stream flow-control windows.
|                                                                                                     Expected: DATA Frame (length:1, flags:0x00, stream_id:1)
|                                                                                                       Actual: Timeout
|                                                                                        Failures: 
|                                                                                        Hypertext Transfer Protocol Version 2 (HTTP/2)
|                                                                                          6. Frame Definitions
|                                                                                            6.9. WINDOW_UPDATE
|                                                                                              6.9.2. Initial Flow-Control Window Size
|                                                                                                × 1: Changes SETTINGS_INITIAL_WINDOW_SIZE after sending HEADERS frame
|                                                                                                  -> The endpoint MUST adjust the size of all stream flow-control windows.
|                                                                                                     Expected: DATA Frame (length:1, flags:0x00, stream_id:1)
|                                                                                                       Actual: Timeout
|                                                                                        Finished in 15.0088 seconds
|                                                                                        1 test
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunIndividualTestCase [failed with about the same error](http://aspnetci/viewLog.html?buildId=523974&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunIndividualTestCase [failed with about the same error](http://aspnetci/viewLog.html?buildId=524045&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunIndividualTestCase [failed with about the same error](http://aspnetci/viewLog.html?buildId=524245&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
RunIndividualTestCase [failed with about the same error](http://aspnetci/viewLog.html?buildId=525035&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by halter73** [comment]
@Tratcher It looks like this started failing after #2769. This could be related to the change made to the H2SpecTests hello world app.

**Comment by Tratcher** [comment]
It looks like this test was disabling itself before. It sends an initial request with no body to check how big the server response is. If it gets a response length of 0 it no-ops.  The old test app used to copy the request body to the response body, so it would no-op for this scenario. The updated app drains the request body and then writes "Hello World" so there's always a response.

Now that the test is active we need to figure out why it's flaky.

**Comment by Tratcher** [comment]
Ah, the Settings Ack and the Data frame randomly switch order and the test client isn't expecting that. We can Ack earlier.

**Comment by ryanbrandenburg** [comment]
RunIndividualTestCase [failed with about the same error](http://aspnetci/viewLog.html?buildId=525931&buildTypeId=Releases_22xPublic_UbuntuUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Did #2790 fix this? It's a bit unclear.

**Comment by Tratcher** [comment]
Yes. We re-ordered the Settings Ack and that should make the test reliable.
