### ISSUE TITLE
Extract bitshift helper code

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2773]
RE: https://github.com/aspnet/KestrelHttpServer/pull/2771/files

The Http2Frame class has a lot of bitshift operations scattered throughout like `get => (Payload[0] << 24) | (Payload[1] << 16) | (Payload[2] << 8) | Payload[3];` We've already found several typos in these that caused to some very strange data corruption bugs.

Proposal: Extract these operations to specific helper APIs to allow testing them directly, reduce duplication, and make the Frame code easier to read. Session has a few examples: https://github.com/aspnet/Session/blob/92ee0bfe89c5136671d82a783799e1d5f7441b53/src/Microsoft.AspNetCore.Session/DistributedSession.cs#L360-L406

**Comment by davidfowl** [comment]
OR use the new BinaryPrimitives helpers in System.Memory

**Comment by Tratcher** [comment]
[Oooooooo](https://www.fuget.org/packages/System.Memory/4.5.1/netstandard2.0/lib/System.Memory.dll/System.Buffers.Binary/BinaryPrimitives#BinaryPrimitives)
