### ISSUE TITLE
Test failure: UsesProvidedServerCertificateSelectorEachTime

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2777]
This test [fails](http://aspnetci/viewLog.html?buildId=524221&buildTypeId=Releases_21Public_UbuntuUniverse) occasionally with the following error:
```
System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
---- System.Net.Sockets.SocketException : Operation canceled
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__46_1(String arg1, X509CertificateCollection arg2, SslProtocols arg3, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.HttpsConnectionAdapterTests.UsesProvidedServerCertificateSelectorEachTime() in /_/test/Kestrel.FunctionalTests/HttpsConnectionAdapterTests.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=540205&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=541633&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=542153&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=543367&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=544237&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=544504&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=545168&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
The comments including failures on master are failing with the error that's tracked in https://github.com/aspnet/KestrelHttpServer/issues/2701 and are unrelated to the error reported in the original comment in this issue. @ryanbrandenburg how do we determine which comments go to which issue?

I'm repurposing this issue to only address the 2.1 test failures.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=546427&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
The 2.1 tests should be more stable once we back port our in-memory functional test change: https://github.com/aspnet/KestrelHttpServer/issues/2886.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=548626&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=550025&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=551022&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=551780&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=553031&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=553996&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=554718&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@JunTaoLuo , looks like 'master' is having issues still.

**Comment by JunTaoLuo** [comment]
It is, but the issue that affects master should be tracked by https://github.com/aspnet/KestrelHttpServer/issues/2701 not here.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=556463&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
LargeUpload [failed with about the same error](http://aspnetci/viewLog.html?buildId=557724&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders [failed with about the same error](http://aspnetci/viewLog.html?buildId=558530&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=558831&buildTypeId=XPlat_Windows_Win10Universe) on master:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559382&buildTypeId=XPlat_Windows_Win10Universe) on master:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561003&buildTypeId=XPlat_Windows_Win10Universe) on master:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561507&buildTypeId=XPlat_Windows_Win10Universe) on master:
- LargeUpload


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=562797&buildTypeId=XPlat_Windows_Win10Universe) on master:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=564601&buildTypeId=XPlat_Windows_Win10Universe) on master at 11:38:26 AM:
- LargeUpload


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by halter73** [comment]
All the recent failures here seem to be instances of dotnet/corefx#30691

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=566237&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:00:14 PM:
- LargeUpload

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=566439&buildTypeId=XPlat_Windows_Win10Universe) on master at 3:50:23 PM:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=567386&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 9:15:41 AM:
- UsesProvidedServerCertificateSelectorEachTime

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=567928&buildTypeId=XPlat_Windows_Win10Universe) on master at 2:42:33 PM:
- LargeUpload

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=573274&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 1:17:09 AM:
- LargeUpload

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=575429&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 8:16:47 PM:
- UpgradedConnectionsCountsAgainstDifferentLimit

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=575922&buildTypeId=XPlat_Windows_Win10Universe) on master at 2:45:17 PM:
- ConnectionNotClosedWhenClientSatisfiesMinimumDataRateGivenLargeResponseHeaders

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=579029&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 1:27:05 PM:
- UsesProvidedServerCertificateSelectorEachTime

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=579562&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 10:45:48 AM:
- UsesProvidedServerCertificateSelectorEachTime

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580161&buildTypeId=Releases_21Public_UbuntuUniverse) on 2.1 at 1:58:41 PM:
- TestKeepAliveTimeout

**Comment by muratg** [comment]
@JunTaoLuo the issue will reopen in aspnetcore-
