### ISSUE TITLE
Test failure: RegisterIPEndPoint_DynamicPort_Success

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2778]
This test [fails](http://aspnetci/viewLog.html?buildId=524247&buildTypeId=Releases_22xPublic_OsxUniverse) occasionally with the following error:
```
System.Net.Sockets.SocketException : Address already in use
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterIPEndPoint_Success(IPEndPoint endPoint, String testUrl, Int32 testPort) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 306
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterIPEndPoint_DynamicPort_Success(IPEndPoint endPoint, String testUrl) in /_/test/Kestrel.FunctionalTests/AddressRegistrationTests.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test RegisterIPEndPoint_DynamicPort_Success-0.0.0.0:0-http://127.0.0.1 at 2018-08-06T16:17:31
| [0.001s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.005s] TestLifetime Information: Finished test RegisterIPEndPoint_DynamicPort_Success-0.0.0.0:0-http://127.0.0.1 in 0.00453s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
These tests should be more reliable after 0e99235 moved the binding tests to their own test group.
