### ISSUE TITLE
In case of exception at startup, Kestrel still starts the website

### ISSUE THREAD

**Issue by Flavien** [aspnet/KestrelHttpServer#278]
When an exception is thrown in the configuration methods of the Startup class, I would expect the program to exit. However Kestrel continues and starts listening on the port, as if everything was normal.

**Comment by Tratcher** [comment]
This is an intended feature of Hosting to facilitate debugging in hosted environments. In development mode the error will be displayed in the browser.

**Comment by Flavien** [comment]
Ok, that's all good if that's by design.
