### ISSUE TITLE
Test failure: GracefulShutdownWaitsForRequestsToFinish

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2786]
This test [fails](http://aspnetci/viewLog.html?buildId=525256&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
Assert.Contains() Failure
Not found: (filter expression)
In value:  ConcurrentQueue<LogMessage> [LogMessage { EventId = 3, Exception = null, LogLevel = Debug, Message = "Hosting starting" }, LogMessage { EventId = 4, Exception = null, LogLevel = Debug, Message = "Hosting started" }, LogMessage { EventId = 0, Exception = null, LogLevel = Debug, Message = "Loaded hosting startup assembly Sockets.Functional"... }, LogMessage { EventId = ConnectionStart, Exception = null, LogLevel = Debug, Message = "Connection id \"0HLFSMLDN670A\" started." }, LogMessage { EventId = 0, Exception = null, LogLevel = Trace, Message = "Connection id 0HLFSMLDN670A received SETTINGS fram"... }, ...]
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.Http2.ShutdownTests.GracefulShutdownWaitsForRequestsToFinish() in /_/test/Kestrel.FunctionalTests/Http2/ShutdownTests.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.003s] TestLifetime Information: Starting test GracefulShutdownWaitsForRequestsToFinish at 2018-08-07T22:30:19
| [0.023s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.093s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.093s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [1.354s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSMLDN670A" started.
| [1.427s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFSMLDN670A received SETTINGS frame with flags 0x0 and length 12 for stream ID 0
| [1.427s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFSMLDN670A received WINDOW_UPDATE frame with flags 0x0 and length 4 for stream ID 0
| [1.430s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFSMLDN670A received HEADERS frame with flags 0x5 and length 98 for stream ID 1
| [1.547s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/2 GET https://localhost:62432/  
| [1.592s] Microsoft.AspNetCore.Server.Kestrel Trace: Connection id 0HLFSMLDN670A received SETTINGS frame with flags 0x1 and length 0 for stream ID 0
| [1.714s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [1.717s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 169.5655ms 200 
| [1.745s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSMLDN670A" is closed. The last processed stream ID was 1.
| [1.755s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLFSMLDN670A" sending FIN.
| [1.766s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSMLDN670A" stopped.
| [1.963s] TestLifetime Information: Finished test GracefulShutdownWaitsForRequestsToFinish in 1.9604016s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Tratcher** [comment]
@JunTaoLuo was this fixed by https://github.com/aspnet/KestrelHttpServer/pull/2785?

**Comment by JunTaoLuo** [comment]
It should be.
