### ISSUE TITLE
Test failure: ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2788]
This test [fails](http://aspnetci/viewLog.html?buildId=525619&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
Assert.Empty() Failure
Collection: [WriteContext { EventId = 0, Exception = Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 463, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.Kestrel", LogLevel = Warning, ... }, WriteContext { EventId = 0, Exception = Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 463, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.Kestrel", LogLevel = Warning, ... }]
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug(ListenOptions listenOptions) in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 454
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.000s] TestLifetime Information: Starting test ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug-http://127.0.0.1:0 at 2018-08-08T02:52:01
| [0.005s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.007s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Libuv.FunctionalTests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TI" started.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TI" reset.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TI" disconnecting.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TI" sending FIN.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TJ" started.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TK" started.
| [0.009s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TL" started.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel Warning: Connection processing ended abnormally.
| Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted
|    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 463
| [0.009s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TL" reset.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TI" stopped.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TM" started.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TM" reset.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TL" disconnecting.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TN" started.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TM" disconnecting.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TL" sending FIN.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TM" sending FIN.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TL" stopped.
| [0.010s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TM" stopped.
| [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TO" started.
| [0.011s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TO" reset.
| [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TP" started.
| [0.011s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TP" reset.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TO" disconnecting.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TQ" started.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TR" started.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TQ" reset.
| [0.012s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HLFSR7ERE2TR" reset.
| [0.012s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.012s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFSR7ERE2TP" disconnec
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=526890&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=527413&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by halter73** [comment]
Thes failures should be fixed by dotnet/corefx#31685.

**Comment by ryanbrandenburg** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=528813&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=529471&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=536621&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug [failed with about the same error](http://aspnetci/viewLog.html?buildId=538192&buildTypeId=Releases_22xPublic_OsxUniverse) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by JunTaoLuo** [comment]
@halter73 you marked this one as done but should it be closed?

**Comment by halter73** [comment]
I'd like waiting until we stop getting new aspnet-hello comments. I looked at the last one from 6 hours ago, and it seems to have failed because Universe isn't updated yet.
