### ISSUE TITLE
Accept Socket handle is inherited by child process

### ISSUE THREAD

**Issue by ppekrol** [aspnet/KestrelHttpServer#2789]
Hi,

I've encountered an error with Kestrel. It appears that disposing the 'WebHost' in certain case is not stopping the server from listening and is causing incoming connections to hang.

I've created a repro for this:
https://github.com/ppekrol/KestrelIssue

Flow 1 (works):
```
dotnet restore
dotnet build
cd .\KestrelIssue\
dotnet run

Started server at: http://127.0.0.1:57741
Starting first request...
Finished first request...
No pingers!
Disposing server...
Disposed server...
NETSTAT:
  TCP    127.0.0.1:57741        127.0.0.1:57742        FIN_WAIT_2      22288
  TCP    127.0.0.1:57742        127.0.0.1:57741        CLOSE_WAIT      22288

Starting second request...

Unhandled Exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at KestreLIssue.Program.Main(String[] args) in C:\workspaces\Temp\KestrelIssue\KestrelIssue\Program.cs:line 88
   at KestreLIssue.Program.<Main>(String[] args)
```

As expected, after server was disposed we got an exception when doing a second request and `netstat` is showing that connections are in `FIN_WAIT_2` or `CLOSE_WAIT` state. Nothing is `LISTENING` on that port.

Flow 2 (hangs):

```
dotnet restore
dotnet build
cd .\KestrelIssue\
dotnet run pingers

Started server at: http://127.0.0.1:57785
Starting first request...
Finished first request...
Starting pingers...
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Ping: OK
Started pingers...
Disposing server...
Disposed server...
NETSTAT:
  TCP    127.0.0.1:57785        0.0.0.0:0              LISTENING       3948
  TCP    127.0.0.1:57785        127.0.0.1:57786        FIN_WAIT_2      3948
  TCP    127.0.0.1:57785        127.0.0.1:57787        FIN_WAIT_2      3948
  TCP    127.0.0.1:57785        127.0.0.1:57788        FIN_WAIT_2      3948
  TCP    127.0.0.1:57785        127.0.0.1:57789        FIN_WAIT_2      3948
  TCP    127.0.0.1:57786        127.0.0.1:57785        CLOSE_WAIT      3948
  TCP    127.0.0.1:57787        127.0.0.1:57785        CLOSE_WAIT      15336
  TCP    127.0.0.1:57788        127.0.0.1:57785        CLOSE_WAIT      21964
  TCP    127.0.0.1:57789        127.0.0.1:57785        CLOSE_WAIT      21104

Starting second request...
```

As you can see, the server was disposed, but it is still `LISTENING`, which hangs all connections infinitely. The second request will timeout after 12h (this is the default timeout that I've set on HttpClient). I would expect to get the exception immediately. Not sure how it is related to the 'pingers' which are a separate processes that are just issuing (in a loop) requests to this server.

`Please note that killing the 'pinger processes' while 'Starting second request...' is hanging will unhang it`

===================

My OS: Win10 x64
Using .NET Core 2.1.2 and 2.1.2 AspNet.Core and Kestrel

This might be related to the https://github.com/dotnet/corefx/issues/30691
We are also spawning a separate process there.

**Comment by Tratcher** [comment]
Do you get the same or different results if you switch to Libuv?
https://github.com/aspnet/Announcements/issues/296

**Comment by ppekrol** [comment]
With `.UseLibuv()` both flows are working the same and as expected (both throw `System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it`)

**Comment by Tratcher** [comment]
Thanks for the good repro. I tracked this down to https://github.com/dotnet/corefx/issues/306.

When StartPingers launches child processes those children inherit a reference to the socket handle. When you stop the server it closes the handle in the parent process, but the child processes keep the handle alive and it can still accept new TCP connections, though it won't serve HTTP requests because the server is gone.

One way to show this is to replace the call to StartPingers with a Console.ReadKey() to pause the app and then you can go start the KestrelPinger app manually. Once that's running press a key to let the original process continue. It will shut down the server as expected.

We'll investigate to see if this is possible for us to mitigate, and why Libuv is not affected.

**Comment by jhudsoncedaron** [comment]
@Tratcher : The general case of 306 not fixed is causing problems for me too, and probably a lot more people. Probably every single case of creating a process from a library function is bugged by this. Actually fixing it would take less time then mitigating it.

**Comment by jhudsoncedaron** [comment]
That's racy. Another thread doing Process.Start() could wreck your day.

**Comment by ppekrol** [comment]
@Tratcher can this be ported to 2.1?

**Comment by Tratcher** [comment]
Not unless you can demonstrate it's having a severe business impact. You'd rather ask for the corefx fix anyways, this was only a stopgap.
