### ISSUE TITLE
Kestrel should not accept invalid HTTP verbs

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/KestrelHttpServer#279]
In #270, Kestrel started the request pipeline with an HTTP method of `1POST` or `{}GET`, which was then translated to a confusing HTTP status of 404. These should not be accepted and give an HTTP status of 400 as early as possible.

**Comment by Eilon** [comment]
HTTP does not define a set of allowed HTTP methods. Any valid 'token' can be used as an HTTP method:

Per http://tools.ietf.org/html/rfc7230#appendix-B:

> request-line = method SP request-target SP HTTP-version CRLF
> ...
>   method = token
> ...
>    tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
>                "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
>    token = 1*tchar

**Comment by Eilon** [comment]
BTW `HTTP 405 Method not allowed` is perhaps more correct.

But ultimately, it's up to middleware to deal with that, not the server. The server can't know why the request wasn't allowed. Bad method? Bad header? Bad URL? It just knows that no middleware accepted the request.

**Comment by Tratcher** [comment]
This was a symptom of request corruption.

Having the server send a 400 for non-conforming methods would be appropriate, similar to how we're considering rejecting overlong request URLs and headers.

**Comment by Eilon** [comment]
@Tratcher but at least with respect to that method, nothing is invalid. Returning a 404 is I think perfectly reasonable. Maybe it *is* a valid verb but just not for the requested path.

**Comment by Tratcher** [comment]
Method/token has limits, it doesn't allow any of these chars: `><][)(:;,}{/\`, or controls, or > 0x7E, etc.. Checking the method would be one way of detecting the kind of request corruption that happened in #270.

**Comment by Eilon** [comment]
Yeah it might be reasonable to do *some* validation of the method, but that wouldn't affect the `1POST` case, which is 100% valid.

**Comment by Tragetaschen** [comment]
*Syntactically*, the [method] is `token` as outlined in Appendix B of RFC 7230, but RFC 7231 [makes all but two](http://tools.ietf.org/html/rfc7231#section-4) methods optional. Beyond that it specifies that standardized methods are to be registered with [IANA](http://www.iana.org/assignments/http-methods/http-methods.xhtml). Kestrel could decide to only support (some of) those methods.

**Comment by Eilon** [comment]
Yeah there's certainly no rule that says any "special" verb has to be accepted at all, but I don't see any reason to block anything either (except for blocking verbs that have an invalid syntax).

**Comment by benaadams** [comment]
@Tragetaschen as you point out IANA has 39 methods registered, and likely people would want to use more/different methods prior to them being standardised (or are not bothered about getting them standardised at all) and probably don't implement most of the standardised methods. 

The server layer (Kestrel in this case) should parse the requests, but shouldn't be interpreting them beyond general safeguards or unparseable requests (400 in your example). 

As @Eilon says an invalid method should be a 405; which would also suggest the path is correct, but the verb is unsupported on it. This issue would probably be better discussed in [aspnet/Routing](https://github.com/aspnet/Routing) than aspnet/KestrelHttpServer?

**Comment by Eilon** [comment]
The problem with 404 and 405 are that it's ambiguous which one to use. Was the path good but the verb bad? Or the path bad but the verb good? What if both are bad?

**Comment by Tratcher** [comment]
Verb is first in the request line so should be verified first. I agree we should only check for syntax errors in the verb. Any other verb verification can easily be handled in middleware.

**Comment by Eilon** [comment]
But the other problem is that only the app itself can make a determination around what's invalid. The web server knows nothing.

**Comment by blowdart** [comment]
I would suggest limiting to a subset of the registered verbs by default, much like IIS, and then allow configuration for more.

**Comment by Tratcher** [comment]
Yuck, more painful knobs. What's the harm in a method FOO being sent to an application?

**Comment by blowdart** [comment]
White list, rather than black list. You know as well as I do it's generally safer in case someone does something stupid.

**Comment by Tratcher** [comment]
If we go that route then make it a large list. http://stackoverflow.com/questions/19162825/web-api-put-request-generates-an-http-405-method-not-allowed-error is a very common customer issue.

**Comment by blowdart** [comment]
39 methods is hardly large. And I'm sure you'd want the full IANA list.

**Comment by Eilon** [comment]
Not a fan of protecting this :frowning: :panda_face:

**Comment by benaadams** [comment]
Some more clarity from [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5.5) 
> 405 Method Not Allowed

>   The 405 (Method Not Allowed) status code indicates that the method
   received in the request-line is known by the origin server but not
   supported by the target resource.  The origin server MUST generate an
   Allow header field in a 405 response containing a list of the target
   resource's currently supported methods.

Ignoring other implications, this would mean a 404 given in the example is the correct response (as the verb wouldn't have been an "allowed verb").

However it also says to return a 405; the path must exist, the verb must be acceptable generally, but not to this particular path; and with it you *must* return a header saying all the acceptable verbs. So the 404 route is probably the better one..?

**Comment by khellang** [comment]
Why is there any need to restrict this? A valid token is a valid token, no?

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
