### ISSUE TITLE
Test failure: TlsHandshakeRejectsTlsLessThan12

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/KestrelHttpServer#2792]
This test [fails](http://aspnetci/viewLog.html?buildId=525931&buildTypeId=Releases_22xPublic_UbuntuUniverse) occasionally with the following error:
```
System.IO.IOException : The reader completed without returning a frame.
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.ReceiveFrameAsync(PipeReader reader) in /_/test/Kestrel.InMemory.FunctionalTests/Http2/TlsTests.cs:line 113
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.WaitForConnectionErrorAsync(PipeReader reader, Boolean ignoreNonGoAwayFrames, Int32 expectedLastStreamId, Http2ErrorCode expectedErrorCode) in /_/test/Kestrel.InMemory.FunctionalTests/Http2/TlsTests.cs:line 75
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.TlsHandshakeRejectsTlsLessThan12() in /_/test/Kestrel.InMemory.FunctionalTests/Http2/TlsTests.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.008s] TestLifetime Information: Starting test TlsHandshakeRejectsTlsLessThan12 at 2018-08-08T20:00:55
| [0.060s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.090s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.090s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
| [0.090s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFTD6JCB5QA" started.
| [1.431s] Microsoft.AspNetCore.Server.Kestrel Error: HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
| [1.564s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [1.731s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLFTD6JCB5QA" stopped.
| [1.755s] TestLifetime Information: Finished test TlsHandshakeRejectsTlsLessThan12 in 1.7478597s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Tratcher** [comment]
Agent setup issue. Mike is trying to get this working on Ubuntu 14.04.
