### ISSUE TITLE
Make connection and stream windows configurable

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2814]
Meta issue: #2627

Today the connection and stream window sizes are hardcoded at the default 65kb. These need to be independently configurable.

This maps to SETTINGS_INITIAL_WINDOW_SIZE.

**Comment by Tratcher** [comment]
Http.Sys/IIS default: 1mb (observed)

**Comment by halter73** [comment]
Is this for both the connection and stream windows?

**Comment by Tratcher** [comment]
The setting applies to both and the window update applies to the connection (no requests were sent in my test).

**Comment by Tratcher** [comment]
@halter73 have you started on this or should I steal it?

**Comment by halter73** [comment]
As discussed, by all means steal it. Thanks.
