### ISSUE TITLE
SocketTransport: Remove rebind workaround?

### ISSUE THREAD

**Issue by drieseng** [aspnet/KestrelHttpServer#2820]
Can  [this](https://github.com/aspnet/KestrelHttpServer/blob/62a30a731d819bf060042d68556b0074d9f0912d/src/Kestrel.Transport.Sockets/SocketTransport.cs#L217) workaround removed since https://github.com/dotnet/corefx/issues/24562 has been fixed since?

**Comment by muratg** [comment]
@drieseng thanks for the catch! Would you be interested in sending a PR?
