### ISSUE TITLE
IIS/Kestrel Slow HTTP Post vulnerability mitigation

### ISSUE THREAD

**Issue by Antaris** [aspnet/KestrelHttpServer#2821]
Hi,

I'm running Qualys vulnerability test against a web application that is approaching production. A repeated failure I keep getting from my reports is a Slow HTTP Post vulnerability, whereby an initial request sends some (but not all data), and the webserver holds the connection open, which at scale could lead to a form of DDoS attack.

I'm having trouble finding the right values to mitigate this potential issue. Additionally, I don't know whether the configuration sits with IIS, or Kestrel (Kestrel isn't exposed publicly, using IIS as a front-webserver).

IIS settings:

```
<webLimits connectionTimeout="00:00:30" headerWaitTimeout="00:00:30" minBytesPerSecond="500" />

```

Kestrel settings:

```
public static IWebHost BuildWebHost() =>
            WebHost.CreateDefaultBuilder()
                .UseStartup<Startup>()
                .UseKestrel(options =>
                {
                    options.Limits.MaxConcurrentConnections = 100;
                    options.Limits.MaxConcurrentUpgradedConnections = 100;
                    options.Limits.MaxRequestBodySize = 10485760 /* 10mb */;
                    options.Limits.MinRequestBodyDataRate = new MinDataRate(500, TimeSpan.FromSeconds(3));
                })
                .Build();
```

I know that individual settings should be tailored based on the type of application, but is there a recommended set of values?

**Comment by Tratcher** [comment]
The recommended values to mitigate this are already the defaults. What does Qualys give as a minimum acceptable throughput? They may be more aggressive about this than IIS/Kestrel are.

**Comment by muratg** [comment]
@Antaris if you find an issue, please file another bug!
