### ISSUE TITLE
Change how HTTP/2 frames are parsed and generated

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2858]
The Http2FrameReader reads the exact structure of the incoming frame into a memory blob before it begins to parse it, first reading the header to get the length and then reading the payload.
https://github.com/aspnet/KestrelHttpServer/blob/b039fb73c41468b6d6a28770285ba432d328023e/src/Kestrel.Core/Internal/Http2/Http2FrameReader.cs#L22-L36

This amounts to triple buffering of some frames and is unnecessary for parsing. The Http2FrameWriter does something similar composing the exact frame bytes into a whole frame before sending it.
https://github.com/aspnet/KestrelHttpServer/blob/b039fb73c41468b6d6a28770285ba432d328023e/src/Kestrel.Core/Internal/Http2/Http2FrameWriter.cs#L198-L223

Alternative: Frames can be parsed directly from the incoming pipe buffer. The logical fields like flags, length, frametype, etc. can still be written to a Http2Frame object, but it doesn't have to be stored in it's serialized state. 
- E.g. Make sure you have received the 9 byte frame header,
- parse the individual fields in order,
 - check the frame type and flags, 
 - make sure you have enough bytes for any supplementary frame fields, parse those, 
 - wait for the rest of the frame body to arrive,
 - then pass the pipe buffer directly to the associated handler. 
 - The header parser can parse directly from that buffer. The data frame handler can copy directly from that buffer to the stream's request body pipe.

The only place you need to allocate a large buffer is for the response header compression, the whole frame needs to be compressed before you can know the exact headers length. Interestingly this compression takes place under the write lock, so that buffer could be rented from the pipe itself to avoid double buffering.

@davidfowl

**Comment by halter73** [comment]
Completely agreed. @davidfowl and I were discussing this last week.
