### ISSUE TITLE
Add default debug-level logging for selected TLS protocol and cipher suite

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2871]

**Comment by DavidParks8** [comment]
It would be nice if this info was exposed as part of the connectionInfo object on the HttpContext. That way people could use custom loggers and target levels other than debug. I know of a few services that need this feature to be able to know if they can disallow old protocols.

**Comment by Tratcher** [comment]
@DavidParks8 that was added in 2.2.0-preview1 via https://github.com/aspnet/KestrelHttpServer/issues/2661
