### ISSUE TITLE
Add HTTP/2 interop tests using chrome headless mode

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#2880]
https://stackoverflow.com/questions/45130993/how-to-start-chromedriver-in-headless-mode

Even a hello world integration test would have caught this regression: https://github.com/aspnet/KestrelHttpServer/issues/2874

**Comment by Tratcher** [comment]
Consider moving this to ServerTests and running it for all servers.

**Comment by muratg** [comment]
We can take a look at SignalR usage of headless Chrome.

**Comment by Tratcher** [comment]
Make sure this covers https://github.com/aspnet/KestrelHttpServer/issues/3027

**Comment by JunTaoLuo** [comment]
I think all the issues for this work item have been addressed.
