### ISSUE TITLE
Backport https://github.com/aspnet/KestrelHttpServer/pull/2780

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#2886]
We should back port the in-memory functional tests to 2.1 (https://github.com/aspnet/KestrelHttpServer/pull/2780). This improvement fixed a slew of flaky tests.

**Comment by JunTaoLuo** [comment]
@halter73 It might be a little tricky to make this change in 2.1 since the change in its current form also affects src files. cc @muratg @Eilon for shiproom.

**Comment by Eilon** [comment]
Yeah the src/ changes are a hard sell for 2.1.x.

**Comment by muratg** [comment]
Closing this one based on the offline discussions.
