### ISSUE TITLE
Feature request: something similar to app_offline.htm

### ISSUE THREAD

**Issue by lonix1** [aspnet/KestrelHttpServer#2890]
In regular ASP.NET I can dump an `app_offline.htm` file on the server, and that would signal IIS to take down the app. Then I can do some maintenance, and delete the file to restart the app.

Kestrel doesn't have such a feature (I think?). I realise there are other (perhaps better?) ways to do this, but most devs and companies are used to this because it is so easy, quick and intuitive.

Please consider it.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#1543
