### ISSUE TITLE
[Perf] High Allocator SocketOutput.Write

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#290]
Drill down on Issue #288
Measurements post PR #287

Item 2 on highest allocators in plaintext test

![most-memory](http://aoa.blob.core.windows.net/aspnet/most-memory1.png)

`Microsoft.AspNet.Server.Kestrel.Http.SocketOutput.Write`

Allocations (2003 requests)

![allocations](http://aoa.blob.core.windows.net/aspnet/socketoutput-allocations.png)

Bytes (2003 requests)

![bytes](http://aoa.blob.core.windows.net/aspnet/socketoutput-bytes.png)

**Comment by benaadams** [comment]
Have PR for this coming

**Comment by benaadams** [comment]
Hopefully resolved by https://github.com/aspnet/KestrelHttpServer/pull/309 will report back

**Comment by lodejard** [comment]
Closed, resolved by #315 per @benaadams

**Comment by benaadams** [comment]
@lodejard still open; is resolved by #363 instead now :)

**Comment by benaadams** [comment]
Resolved by #363 Resuse writes, initalize queues
