### ISSUE TITLE
Add timeout for initial handshake

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/KestrelHttpServer#2900]
Meta issue: https://github.com/aspnet/kestrelhttpserver/issues/2627

See initial handshake timeout

**Comment by halter73** [comment]
This is now subsumed by the keep-alive timeout which is started before we attempt to read the prefix:

https://github.com/aspnet/KestrelHttpServer/blob/1f2e704dd3ec02e3069c8f4b9b6d69423a9c9cf1/src/Kestrel.Core/Internal/Http2/Http2Connection.cs#L187-L189
