### ISSUE TITLE
RequestSizeLimit causes BadHttpRequestException and 500 status code instead of 413

### ISSUE THREAD

**Issue by ptupitsyn** [aspnet/KestrelHttpServer#2909]
I have a `[RequestSizeLimit]` on an API controller action:

```
    [HttpPut]
    [RequestSizeLimit(120_000_000)]
    public async Task<IActionResult> Put(IFormCollection form)
    {
       ...
    }
```

When the limit is exceeded, `BadHttpRequestException` is thrown, and HTTP code 500 is returned.
I would expect 413 error code instead, and no exception being thrown/logged, since this is a normal situation.

Another issue is that `BadHttpRequestException.StatusCode` and `Reason` are `internal`, so it is not possible to create a workaround with a custom `IMiddleware` (I can only rely on `Message`, which is culture-specific):

```
public class ExceptionMiddleware : IMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        try
        {
            await next(context);
        }
        catch (Exception ex)
        {
            if (ex is BadHttpRequestException badReqEx && badReqEx.Message == "Request body too large.")
            {
                context.Response.StatusCode = StatusCodes.Status413PayloadTooLarge;
            }
        }
    }
}
```

Related SO question: https://stackoverflow.com/questions/52243903/requestsizelimitattribute-http-500-instead-of-413-in-asp-net-core-2-1-401

**Comment by Tratcher** [comment]
Without that ExceptionMiddleware what is catching the BadHttpRequestException? The ExceptionHandlerMiddleware?

The main problem here is that the size limit is enforced inside of the request body stream. When the limit is reached it's only way to abort ReadAsync is with an exception. The secondary problem is that the exception gets handled by a middleware and a 500 response sent so the server doesn't get a chance to produce a 413 response.

**Comment by Tratcher** [comment]
That's an option.

**Comment by muratg** [comment]
We'll consider this in 3.x.

**Comment by Tratcher** [comment]
Bumping for re-triage.
