### ISSUE TITLE
FlushAsync doesn't actually write data to the client?

### ISSUE THREAD

**Issue by drauch** [aspnet/KestrelHttpServer#2912]
I have a Razor view which (as a minimal repro sample) looks like this:

    @{ var longStr = new string('x', 100 * 1024); /* more than 64KB */ }
    ...
    @functions { string Throw () { throw new Exception(); } }
    ...
    <p>@longStr</p>
    @await FlushAsync()
    <p>@Throw()</p>

I expected to see many x on the client, instead I see a proper error page. How is this possible if `FlushAsync` already sent `longStr` to the client? Is the data still buffered somewhere on the server?

**Comment by benaadams** [comment]
Think its an issue with [`HttpResponseStreamWriter` in `HttpAbstractions`](https://github.com/aspnet/HttpAbstractions/blob/02f55e181b19d8854672d05225e0dbbf991100db/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs) that `FlushAsync` never actually calls `FlushAsync` on the underlying stream.

**Comment by benaadams** [comment]
I think its a bug in the ` HttpResponseStreamWriter`

It even has the comment
```csharp
        // We want to flush the stream when Flush/FlushAsync is explicitly
        // called by the user (example: from a Razor view).
```

On pure Kestrel it should act the same; however if you have an intermediate stream like compression; a reverse proxy (IIS or ngnix) or are using a different server like HttpSysServer then it probably won't.

**Comment by muratg** [comment]
This issue was moved to aspnet/Home#3542
