### ISSUE TITLE
Add a new feature to expose the socket handle

### ISSUE THREAD

**Issue by westfin** [aspnet/KestrelHttpServer#2928]
In my specific case I need get access to incoming connection socket.Handle from application code. If I am correct understand current working model (#1980) I need some feature that will be transfer socket.Handle from transport layer to application code.
[More details](https://github.com/aspnet/KestrelHttpServer/issues/1980#issuecomment-420199729)

Please correct me if I am wrong.

**Comment by Tratcher** [comment]
It doesn't sound like you need the actual socket handle in application code, what you need is the security label, correct? What if there was an event inside the socket transport that fired when the socket was first connected, gave you access to the handle, and let you pass your own state up the stack via the feature collection?

**Comment by Tratcher** [comment]
Having arbitrary access to the handle from the application layer seems like a recipe for disaster.

**Comment by westfin** [comment]
> Having arbitrary access to the handle from the application layer seems like a recipe for disaster.

I agree with you.

> It doesn't sound like you need the actual socket handle in application code, what you need is the security label, correct? What if there was an event inside the socket transport that fired when the socket was first connected, gave you access to the handle, and let you pass your own state up the stack via the feature collection?

How it can looks like in code? Here I can fire the event.

https://github.com/aspnet/KestrelHttpServer/blob/55e5e564226e7b27742c91f46ea71841071e4ac3/src/Kestrel.Transport.Sockets/SocketTransport.cs#L153

Which place will be suitable to subscribe?

**Comment by davidfowl** [comment]
It’s completely fine to expose the socket handle via an obscure feature. That’s the entire point of features

**Comment by Tratcher** [comment]
I'd expect the subscription to happen through SocketTransportOptions:
https://github.com/aspnet/KestrelHttpServer/blob/55e5e564226e7b27742c91f46ea71841071e4ac3/src/Kestrel.Transport.Sockets/SocketTransportOptions.cs and you'd set it like this:

```
            hostBuilder.ConfigureServices(services =>
            {
                services.Configure<SocketTransportOptions>(options =>
                {
                     options.OnAccept = context => { .. };
                });
            })
```

**Comment by davidfowl** [comment]
I'm not sure this is the right approach but let me ask a question. @westfin how are you using the the handle? Are you reading from the socket itself or are you doing something else with it? What does the API handling it off

**Comment by westfin** [comment]
> I'm not sure this is the right approach but let me ask a question. @westfin how are you using the the handle? Are you reading from the socket itself or are you doing something else with it? What does the API handling it off

I just simple reading from the socket.

**Comment by davidfowl** [comment]
Yea that may not work well. As multiple parties would be reading from the socket. A transport level hook seems more appropriate. 

Or consider refactoring the native library to not do the actual reading.

**Comment by westfin** [comment]
> Or consider refactoring the native library to not do the actual reading.

I can't refactoring this library.


> Yea that may not work well. As multiple parties would be reading from the socket. A transport level hook seems more appropriate.

Ok, can I try work on this issue? @Tratcher if in pocess of work I have some question - can I ask you here? In your solutaion action should have two params?
`options.OnAccept => (context, socket) {/* Get socket handle */};`

**Comment by Tratcher** [comment]
I expect the context to be a new object that has the handle on it along with other connection information like the feature collection.

**Comment by westfin** [comment]
How I can put this information up to the top? In middleware I have HttpContext with Features.

Actualy I don't fully understand what is the context. Kestral has [HttpConnection ](https://github.com/aspnet/KestrelHttpServer/blob/d3d7c5519810ad97997f777c8a3683a9adbbe1e1/src/Kestrel.Core/Internal/HttpConnection.cs), [Http1Connection](https://github.com/aspnet/KestrelHttpServer/blob/d3d7c5519810ad97997f777c8a3683a9adbbe1e1/src/Kestrel.Core/Internal/Http/Http1Connection.cs), [TransportConnection ](https://github.com/aspnet/KestrelHttpServer/blob/68a08635244df0941b5edd4cc07b2fd0a3cbddcd/src/Kestrel.Transport.Abstractions/Internal/TransportConnection.cs)-> [SocketConnection](https://github.com/aspnet/KestrelHttpServer/blob/6dc55a04623c9bf37d9167cf02d7e3fdb6967e03/src/Kestrel.Transport.Sockets/Internal/SocketConnection.cs), [KestrelConnection](https://github.com/aspnet/KestrelHttpServer/blob/68a08635244df0941b5edd4cc07b2fd0a3cbddcd/src/Kestrel.Core/Internal/Infrastructure/KestrelConnection.cs) and etc. Most of them somehow use [ConnectionContext](https://github.com/aspnet/KestrelHttpServer/blob/83488886e0ed32e946af2a25ae7f29ce9bcc4273/src/Connections.Abstractions/ConnectionContext.cs), but I don't see where this inforamtion set up to middleware. 

My new object context have same function like all these connections? Or not?

**Comment by Tratcher** [comment]
That's definitely on the right track. 
- You'll want to move the OnAccept invocation from RunAcceptLoopAsync to HandleConnectionAsync to avoid blocking the accept loop. 
- SocketHandleContext could be named SocketAcceptContext.
- What kind of work do you plan on doing in OnAccept? Would it make sense for that to be async? `Func<SocketAcceptContext, Task>`

**Comment by westfin** [comment]
> * What kind of work do you plan on doing in OnAccept? Would it make sense for that to be async? `Func<SocketAcceptContext, Task>`

At the moment it sync work, but may be in future it can be async. Therefore, this makes sense.

**Comment by westfin** [comment]
@Tratcher I try it in my repository https://github.com/westfin/KestrelHttpServer/commit/a14b8854dcdcb385dc610739ed1c91534ca8588e. It works as expected for me.

Actualy I don't have any more questions about issue. It just about project structure.

- What place will be correct for new object class?

https://github.com/westfin/KestrelHttpServer/blob/a14b8854dcdcb385dc610739ed1c91534ca8588e/src/Kestrel.Transport.Sockets/SocketAcceptContext.cs#L6

- And this how I modify `HandleConnectionAsync `method

https://github.com/westfin/KestrelHttpServer/blob/a14b8854dcdcb385dc610739ed1c91534ca8588e/src/Kestrel.Transport.Sockets/SocketTransport.cs#L192-L199

If it's correct can I create PR for this issue?
Thanks for your help.

**Comment by Tratcher** [comment]
Yes that looks like a good place for SocketAcceptContext.

As for HandleConnectionAsync, I'd expect SocketConnection to make the Socket available as an internal property. Then SocketAcceptContext can be constructed inside HandleConnectionAsync rather than passed to it.

SocketAcceptContext should also take/expose the Socket as a parameter rather than just the handle, the handle can be retrieved by anybody from the Socket, but Socket provides much more functionality.

I'll talk to @shirhatti and @davidfowl on if we'd accept a PR for this feature. It's pretty dangerous to mess with the raw socket underneath the transport and we're not sure if there are enough scenarios to justify exposing it.

**Comment by Tratcher** [comment]
@westfin have you tested that this implementation works with your library yet? You can use the [sample](https://github.com/westfin/KestrelHttpServer/blob/a14b8854dcdcb385dc610739ed1c91534ca8588e/samples/SampleApp/Startup.cs) apps to try it.

**Comment by halter73** [comment]
Proxying also affords you opportunity to asynchronously buffer the security label before P/Invoking into a method that could block a managed thread and, depending on how you're trying to implement this, the entire accept loop! 😱

**Comment by westfin** [comment]
> Yes that looks like a good place for SocketAcceptContext.
> 
> As for HandleConnectionAsync, I'd expect SocketConnection to make the Socket available as an internal property. Then SocketAcceptContext can be constructed inside HandleConnectionAsync rather than passed to it.
> 
> SocketAcceptContext should also take/expose the Socket as a parameter rather than just the handle, the handle can be retrieved by anybody from the Socket, but Socket provides much more functionality.

I updated the repository with your recommendations https://github.com/westfin/KestrelHttpServer/commit/7797b99ed05d8798261aa0690cdc1e0ad24541e1

> @westfin have you tested that this implementation works with your library yet? You can use the [sample](https://github.com/westfin/KestrelHttpServer/blob/a14b8854dcdcb385dc610739ed1c91534ca8588e/samples/SampleApp/Startup.cs) apps to try it.

I create own test sample in repository
https://github.com/westfin/KestrelHttpServer/tree/release/2.2/samples/SocketAcceptContextSample

But without my native library. I use stub method
https://github.com/westfin/KestrelHttpServer/blob/75998b46b046a56d057c3f335caa149047743234/samples/SocketAcceptContextSample/Startup.cs#L42-L45
It works well for me.

**Comment by Tratcher** [comment]
You might want to at least simulate what operations the native module will perform on the socket. E.g. it's going to read x bytes?

**Comment by westfin** [comment]
> @westfin Have you considered writing connection middleware that proxies the security label from the Transport PipeReader to a managed Socket and then passes the handle from the managed socket to the GetSecurityLabel method? Connection middleware is invoked immediately after accept without anything else reading or writing to the socket, so in principle it seems like this should work.

> Proxying also affords you opportunity to asynchronously buffer the security label before P/Invoking into a method that could block a managed thread and, depending on how you're trying to implement this, the entire accept loop! 😱

@halter73 I do not fully understand your idea. I need get accepting `Socket.Handle`. In PipeReader I can't get this object. https://github.com/aspnet/KestrelHttpServer/blob/10458d5ecc548ba77541259dfcf954be714d9c7f/src/Kestrel.Transport.Sockets/SocketTransport.cs#L153

I create repository to try implement @Tratcher solution.
And I create a sample.
Maybe you'll try to explain on it?
https://github.com/westfin/KestrelHttpServer/tree/release/2.2/samples/SocketAcceptContextSample

**Comment by westfin** [comment]
> You might want to at least simulate what operations the native module will perform on the socket. E.g. it's going to read x bytes?

I unfortunately do not know how this library is implemented. But I think it's read some bytes from it.

**Comment by halter73** [comment]
The idea is to create your own acceptSocket in the connection middleware that listens on localhost. You would then establish a loopback connection where you proxy/send just the bytes containing the security label you read from the PipeReader over the client socket. You could then take the accepted server-side socket and pass that to GetSecurityLabel.

**Comment by westfin** [comment]
> The idea is to create your own acceptSocket in the connection middleware that listens on localhost. You would then establish a loopback connection where you proxy/send just the bytes containing the security label you read from the PipeReader over the client socket. You could then take the accepted server-side socket and pass that to GetSecurityLabel.

@halter73 What does mean connection middleware? Write own [ConnectionHandler](https://github.com/aspnet/KestrelHttpServer/blob/6fde01a825cffc09998d3f8a49464f7fbe40f9c4/src/Connections.Abstractions/ConnectionHandler.cs)?

**Comment by westfin** [comment]
@halter73  I think I understand what you mean. Maybe I am wrong but I can't read security label from PipeReader, because security label is in options IP datagram. And to get access to this bytes I need raw socket.

**Comment by halter73** [comment]
I think I understand now. Are the security labels your trying to read described by [RFC 1108](https://tools.ietf.org/html/rfc1108)? If that's the case, you're right that the IP header data cannot be read from the PipeReader. The RFC seems to indicate that each datagram is supposed to cary this option. Is it acceptable to check only the first datagram? I suppose it wouldn't make sense for the security option to change mid connection.

If the first datagram of the TCP connection always contains the security option you're looking for, blocking the accept loop isn't too much of a concern for your specific use case. However, if we want to ship SocketTransportOptions.OnAccept, as a supported API, we'll probably want to Task.Run the OnAccept callback.

**Comment by westfin** [comment]
> I think I understand now. Are the security labels your trying to read described by [RFC 1108](https://tools.ietf.org/html/rfc1108)?

Yes you are right 😃

> Is it acceptable to check only the first datagram? I suppose it wouldn't make sense for the security option to change mid connection.

Yes, I also think that this will be enough.

> Proxying also affords you opportunity to asynchronously buffer the security label before P/Invoking into a method that could block a managed thread

Can you explain this point in more detail or maybe provide a link to the docs? :) What you mean when say "block a managed thread" - that specific for p/invoke?

**Comment by halter73** [comment]
My point about how the P/Invoke could "block a managed thread" was theoretical.

Without knowing anything about GetSecurityLabel other than the fact that it takes a socket handle as a parameter, it seemed possible that GetSecurityLabel might not return immediately. For all I knew, GetSecurityLabel might make a blocking call to recv(). It would be bad if that were the case, because for as long as no security label arrived on the newly accepted socket, the server would be unable to accept any new connections.

Since I was under the impression that GetSecurityLabel was reading data instead of options from the socket, I thought you could wait to make sure data arrived before P/Invoking. Now that I know the security label arrives via an option in the TCP SYN packet, waiting for data doesn't seem useful.

I'm interested in how GetSecurityLabel can read options from a TCP packet via a socket handle at the app layer. I'm guessing the customized OS might have something to do with exposing the necessary metadata.

**Comment by westfin** [comment]
Now I understand. Thank you.

> I'm interested in how GetSecurityLabel can read options from a TCP packet via a socket handle at the app layer. I'm guessing the customized OS might have something to do with exposing the necessary metadata.

I don't know how.
But "OnAccept" solution works for me 😃

**Comment by westfin** [comment]
@Tratcher what to do with this issue?

**Comment by westfin** [comment]
@davidfowl 
> @davidfowl What's your current thought on this? It looks risky to expose this in general, no?

**Comment by davidfowl** [comment]
@westfin We don't think this is a general enough feature to add to the SocketsTransport. I recommend you fork the transport and add it. We'd be ok making something virtual on the transport so that you could derive instead of forking the entire code base.

**Comment by westfin** [comment]
Yes I agree. Yhis is not general feature.

Any way thank you.
