### ISSUE TITLE
Category of some loggers are wrong - Name of Type instead Namespace+Type

### ISSUE THREAD

**Issue by tiago-soczek** [aspnet/KestrelHttpServer#2929]
Hi,

While I was filtering log entries by category/source, I found these 2 loggers using just the Type name for the category of logging:

----

https://github.com/aspnet/KestrelHttpServer/blob/release/2.2/src/Kestrel.Core/Internal/HttpsConnectionAdapter.cs#L64

----

https://github.com/aspnet/KestrelHttpServer/blob/6fde01a825cffc09998d3f8a49464f7fbe40f9c4/src/Kestrel.Core/Adapter/ListenOptionsConnectionLoggingExtensions.cs#L33

----

In this case, would be better to use the full type name (Namespace+Type), right?

If needed, I'm available to work on this issue.

Thanks.

**Comment by Tratcher** [comment]
You're right, those should have been `.CreateLogger<HttpsConnectionAdapter>()`. A PR would be welcome.

**Comment by Tratcher** [comment]
Or like this:
https://github.com/aspnet/KestrelHttpServer/blob/6fde01a825cffc09998d3f8a49464f7fbe40f9c4/src/Kestrel.Transport.Sockets/SocketTransportFactory.cs#L41

Watch out for the tests: 
https://github.com/aspnet/KestrelHttpServer/blob/f70ba53253480a0c9b672537b8b13058b3e16160/test/Kestrel.InMemory.FunctionalTests/HttpsTests.cs#L386

**Comment by tiago-soczek** [comment]
OK! I'll take care of this issue, please assign to me.

**Comment by Tratcher** [comment]
Note: use the release/2.2 branch.

**Comment by halter73** [comment]
Breaking change announcement: aspnet/Announcements#317
