### ISSUE TITLE
Any way to provide custom body for HTTP errors returned from Kestrel?

### ISSUE THREAD

**Issue by grzesiek-galezowski** [aspnet/KestrelHttpServer#2947]
Hi,

I run an ASP.NET Core 2.0 app on top of kestrel and when I send it an HTTP request without Content-Length set, I get (as expected) the following error:

```
HTTP/1.1 411 Length Required
Connection: close
Date: Fri, 21 Sep 2018 12:38:10 GMT
Server: Kestrel
Content-Length: 0
```

My question is: is it possible to add custom body to this error? I tried doing it through ASP.NET Core features like middleware, error handlers, exception handlers and filters, but it appears the error is being returned from the Kestrel code before hitting any of these places.

**Comment by Tratcher** [comment]
No, this category of errors is not customisable.

**Comment by grzesiek-galezowski** [comment]
Thank you for your help!
