### ISSUE TITLE
Test failure: ResponseBodyWriteAsyncCanBeCancelled

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#2954]
This test [fails](http://aspnetci/viewLog.html?buildId=560679&buildTypeId=Releases_22xPublic_Win2012) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(Xunit.Sdk.FalseException): Assert.False() Failure
Expected: False
Actual:   True
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ResponseTests.<>c__DisplayClass2_0.<<ResponseBodyWriteAsyncCanBeCancelled>b__0>d.MoveNext() in /_/test/Kestrel.InMemory.FunctionalTests/ResponseTests.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.000s] TestLifetime Information: Starting test ResponseBodyWriteAsyncCanBeCancelled at 2018-09-25T04:28:27
| [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
| [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH2JT9V6KCA" started.
| [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http:///  
| [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH2JT9V6KCA" completed keep alive response.
| [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 7.1016ms 200 
| [0.017s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH2JT9V6KCA" disconnecting.
| [0.017s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [0.018s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLH2JT9V6KCA" stopped.
| [0.020s] TestLifetime Information: Finished test ResponseBodyWriteAsyncCanBeCancelled in 0.0195806s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@halter73 @Tratcher @JunTaoLuo
