### ISSUE TITLE
Add support for syslog compatible priority numbers to our console logger.

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/KestrelHttpServer#2955]
An important part of journalctl is priorities. The standard logger should do this, since this is the way you will run kestrel on Linux.

Add support for syslog compatible priority numbers to our console logger.

For more info, see https://github.com/aspnet/KestrelHttpServer/issues/2679

**Comment by davidfowl** [comment]
This is a logging question and it should be filed here https://github.com/aspnet/Logging/. Also this library (https://github.com/tmds/Tmds.Systemd) looks pretty good, so why not use it?

**Comment by mattiasw2** [comment]
I should not have to use a external library for something as basic as getting the logfile in the correct format for a platform. One of the reasons for using dotnet is that there are a lot of standard tooling with a rather long shell life, which is liked by business customers, where an application typically has a lifespan of 15 years. It all depends on how serious aspnet is in linux hosting, you decide.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Logging#882
