### ISSUE TITLE
Consuming request body allocates a lot

### ISSUE THREAD

**Issue by rynowak** [aspnet/KestrelHttpServer#296]
Introduced by this change: https://github.com/aspnet/KestrelHttpServer/commit/fb01ea39185c857dcf8230922a648e9b242427f3

Allocations for 3000 requests to a simple API site:
![image](https://cloud.githubusercontent.com/assets/1430011/10774035/23285594-7cbc-11e5-866d-05ba3bb2ce85.png)

This is 80kb per request. The `Stream` needs to override `CopyToAsync`

**Comment by Tratcher** [comment]
CopyToAsync isn't virtual. Really you want a Drain method that re-uses the buffer per connection.

**Comment by rynowak** [comment]
https://msdn.microsoft.com/en-us/library/hh158751(v=vs.110).aspx

The longest overload is

**Comment by benaadams** [comment]
Should be 81Kb? Just read to null buffer rather than Copy? (Read+Write)

https://github.com/aspnet/KestrelHttpServer/pull/300

**Comment by rynowak** [comment]
Oh my! you're right, numbers are hard. That is 80kb.

I was wondering why my buffer pooling prototype improved allocations by -240mb :laughing:

**Comment by benaadams** [comment]
Should also be resolved :+1:
