### ISSUE TITLE
Question: Is there a way of reloading certs without restart of server

### ISSUE THREAD

**Issue by vasicvuk** [aspnet/KestrelHttpServer#2967]
I wanted to know if there is a way of reloading certificate used for HTTPs without restarting Kestrel. For example i have next configuration:
```csharp
webBuilder.UseKestrel(options =>
                {
                    options.Listen(IPAddress.Any, 80);
                    options.Listen(IPAddress.Any, 443, listenOptions =>
                    {
                        listenOptions.UseHttps("localhost.pfx");
                    });
            });
```

And the localhost.pfx file is changed after the Kestrel is loaded. Can we somehow automatically reload certificate without restart of Kestrel?

**Comment by Tratcher** [comment]
2.1 added a call back designed for use with SNI, but it could also be used to reload a certificate. You'd have to build the change detection part.

**Comment by Tratcher** [comment]
Yeah, I couldn't find it on my phone earlier. See the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1#endpoint-configuration) and look under Kestrel support for SNI.

**Comment by samsosa** [comment]
```csharp
webBuilder.UseKestrel(options =>
{
   options.Listen(IPAddress.Any, 80);
   options.Listen(IPAddress.Any, 443, listenOptions =>
   {
      listenOptions.UseHttps(httpsOptions =>
      {
         httpsOptions.ServerCertificateSelector = (context, dnsName) =>
         {
            // here you can return your cert dynamically
            return X509Certificate2.CreateFromCertFile(" ... your cert filepath ... ");
         };
      });
   });
});
```

**Comment by Tratcher** [comment]
@samsosa careful there, you don't want to reload the cert on every new connection, you want to cache it and only reload when needed.

**Comment by vasicvuk** [comment]
@Tratcher  @samsosa  Thanks this solves my question

**Comment by samsosa** [comment]
@Tratcher yes you're right. I changed the example slightly.
