### ISSUE TITLE
Kestrel isn’t calling context.RequestAborted

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/KestrelHttpServer#297]
Currently Kestrel isn't calling callbacks registered via `context.RequestAborted.Register(...)`. This hurts us as it means we can't cleanup out SSE connections when the client aborts/closes the connection.

**Comment by Tratcher** [comment]
Yes, kestrel needs to implement IHttpRequestLifetimeFeature

**Comment by halter73** [comment]
This was a dup of #30
