### ISSUE TITLE
middleware to cancel request if custom timeout is reached

### ISSUE THREAD

**Issue by imxavi** [aspnet/KestrelHttpServer#2985]
Hi,
I need to cancel a request if an api is taking longer than a custom timout value.
make sense to do this?:

```
        public async Task InvokeAsync(HttpContext context)
        {
            int customTimeout = 500; //ms
                var timeoutToken = new CancellationTokenSource();
                timeoutToken.CancelAfter(customTimeout);
                context.RequestAborted = timeoutToken.Token;

                await _next(context);
            }
        }
```
will the client be able to cancel the request with the original request token?
what approach should I do then?
we can't call Cancel() on context.RequestAborted ...
thanks

**Comment by Tratcher** [comment]
You want CancellationTokenSource.CreateLinkedTokenSource which will let you combine the original RequestAborted token and your new timeout token. 

Also, dispose your CancellationTokenSource after _next completes using a finally block.

**Comment by imxavi** [comment]
Thanks @Tratcher for your comment.
something like this?

```
public async Task InvokeAsync(HttpContext context)
{
	int customTimeout = 500; //ms
	var timoutTokenSource = CancellationTokenSource.CreateLinkedTokenSource(context.RequestAborted);
	timoutTokenSource.CancelAfter(customTimeout);
	context.RequestAborted = timoutTokenSource.Token;

	try
	{
		await _next(context);
	}
	finally
	{
		timoutTokenSource.Dispose();
	}
}
```

**Comment by Tratcher** [comment]
Exactly.

**Comment by imxavi** [comment]
Many thanks @Tratcher
