### ISSUE TITLE
Sockets is much slower than Libuv is some cases

### ISSUE THREAD

**Issue by sebastienros** [aspnet/KestrelHttpServer#2991]
Some examples in the comments from this issue https://github.com/aspnet/KestrelHttpServer/issues/2621

**Comment by sebastienros** [comment]
It's definitely possible. Please try that.

**Comment by MatthewLymer** [comment]
Migrating to aspnetcore 2.1.5 solved the issue for me

**Comment by sebastienros** [comment]
Thank you for the update
