### ISSUE TITLE
h2spec test hangs during local functional test run

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#2999]
This is the second time I've observed this. I didn't catch which test was hanging the first time. This time it is `http2/4.2/3` during the netcoreap2.2 libuv functional tests. Here are the command line arguments for then hanging run. This is particularly odd because there's supposed to be a 15 second timeout but than hang lasted for at least 10 minutes.

> G:\dev\aspnet\KestrelHttpServer\test\Kestrel.Transport.Libuv.FunctionalTests\bin\Debug\netcoreapp2.2\h2spec\windows\h2spec.exe" http2/4.2/3 -p 52487 --strict -j C:\Users\shalter\AppData\Local\Temp\a7c18c2e-83ad-4ab8-8f57-05f105ed1b90.xml --timeout 15 --tls --insecure

**Comment by halter73** [comment]
Now I'm sure that I saw this twice with the exact same parameters.

**Comment by Tratcher** [comment]
RunIndividualTestCase(testCase: http2/4.2/3, HTTPS:True, Sends a large size HEADERS frame that exceeds the SETTINGS_MAX_FRAME_SIZE)
