### ISSUE TITLE
Malformed request: invalid headers cause endpoints to give status code 400

### ISSUE THREAD

**Issue by huanbd** [aspnet/KestrelHttpServer#3004]
This is log error, that I have caught in my website:
`2018-10-12 10:30:40.3584||Microsoft.AspNetCore.Server.Kestrel|INFO|Connection id "0HLHFUBTL1KAH" bad request data: "Malformed request: invalid headers." Malformed request: invalid headers.`

I found the root of error is cookie, my site embed some vendor advertising, and they add cookie with content: `[{"a":"194_ChÃºc táº¿t","d":25315269}]`

I have followed [#issue 311](https://github.com/aspnet/Announcements/issues/311) in my local but It still can't resolve

I have attached fiddler log bellow
[fiddler_request.zip](https://github.com/aspnet/KestrelHttpServer/files/2471686/fiddler_request.zip)

**Comment by Tratcher** [comment]
There is no workaround except for upgrading to [2.2.0-preview2](https://blogs.msdn.microsoft.com/webdev/2018/09/12/asp-net-core-2-2-0-preview2-now-available/).

**Comment by ionepaul** [comment]
hi @huanbd does upgrading to 2.2.0-preview2 worked for you ? I've made some tests in 2.2.0-preview3 and doesn't seems to work, do I need to set any additional options ? 

Thank you.

**Comment by huanbd** [comment]
Hi @ionepaul , It work for me, I've only updated to [https://blogs.msdn.microsoft.com/webdev/2018/09/12/asp-net-core-2-2-0-preview2-now-available/](2.2.0-preview2) and that all, I don't change any other

**Comment by ionepaul** [comment]
@huanbd thanks for the reply, I still got the error when trying to run it with IIS Express...have you manged to do that ?

**Comment by huanbd** [comment]
Have you try deploy to your environment stag/pro? I've deploy to Linux server and run direct kestrel

**Comment by ionepaul** [comment]
To staging but is on windows using iis as a proxy and seems to not be working like that...

**Comment by huanbd** [comment]
Oh, I see this doc [#issue 311](https://github.com/aspnet/Announcements/issues/311) follow that "If your application is behind a forwarding proxy such is Internet Information Server, Azure Application Gateway or nginx you will not be affected." In my case, I don't have a forwarding proxy like that, I use direct kestrel. I haven't yet try with a forwarding proxy ;(

**Comment by ionepaul** [comment]
Ok, I do understand, thank you for your help 👍
