### ISSUE TITLE
listening on ip = no site

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#301]
![kestrel-hosting](https://cloud.githubusercontent.com/assets/3924941/10797215/807f532c-7d99-11e5-985a-f2f6340905fb.png)
I'm listening on a IP that is local to the host machine; and port 80
as google APIs doesn't like localhost or ports for server keys :'(

but it looks like kestrel is listening but not receiving request for some reason; but when I switch back to local host all works fine?

**Comment by Tratcher** [comment]
Do you get a firewall prompt when using a public IP? And have you tried just using the host name instead?

**Comment by grahamehorner** [comment]
I'm not using public addresses; the address used is local to the development system which is running on a 192.168.0.x range; I have tried both the FQDN and hostname same results.  I have tuned off firewall on private network; still no joy.

**Comment by grahamehorner** [comment]
Oh found something odd it looks to occur only when using multiple URLs ?

**Comment by benaadams** [comment]
What happens if you give it the ports? e.g.

`--server.urls=http://*:80;https://*:443"`

**Comment by muratg** [comment]
@JunTaoLuo Could you investigate?

**Comment by cesarbs** [comment]
I can't repro. @grahamehorner are you still seeing this?

**Comment by cesarbs** [comment]
Closing since no repro and no response.
