### ISSUE TITLE
Potentially revert "Remove calls to MemoryMarshal.GetReference"

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#3013]
We may want to revert https://github.com/aspnet/KestrelHttpServer/commit/2999aa54cd7a4b572240378f2318d4b730ca42d8.

https://github.com/dotnet/corefx/pull/32669#issuecomment-429506746

cc @sebastienros

**Comment by benaadams** [comment]
Related https://github.com/dotnet/coreclr/pull/20428

**Comment by muratg** [comment]
@davidfowl so what's the plan in 2.2?

**Comment by muratg** [comment]
Triage: closing
