### ISSUE TITLE
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.

### ISSUE THREAD

**Issue by jakubsvobodacz** [aspnet/KestrelHttpServer#3018]
Hey all,

Today, out of nothing (no changes in project or with anything else) when trying to debug my aspnet core (ver. 2.1.402) project I ran into this: 

`System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.`

The suggestion in the error was to: `System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.`

I tried that, and it did not help. Further, I tried to run `dotnet dev-certs https
dotnet dev-certs https --clean` but the clean could not go through and threw this: `There was an error trying to clean HTTPS development certificates on this machine.
Sequence contains no matching element`

Any way how to fix this, so I can debug?

**Comment by Tratcher** [comment]
> threw this:

What was that last error? I think you pasted the wrong text.

**Comment by jakubsvobodacz** [comment]
> > threw this:
> 
> What was that last error? I think you pasted the wrong text.

Fixed

**Comment by javiercn** [comment]
@jakubsvobodacz For the specific certificate issue, see https://github.com/aspnet/DotNetTools/issues/464#issuecomment-430275944

If you clean the certificates manually and re-run the tool you should be good to go.

**Comment by JunTaoLuo** [comment]
Going to close this as dupe since there's an issue filed in DotNetTools.
