### ISSUE TITLE
Perf Questions around HttpClient using Http/2

### ISSUE THREAD

**Issue by AceHack** [aspnet/KestrelHttpServer#3020]
I created a multiplexed WebSocket client/server based on Pipelines and David Fowler's example here https://github.com/davidfowl/TcpEcho and compared the performance to HttpClient using Http/2 which has multiplexing as well. I get very different results. Am I doing something wrong with HttpClient? Here are my results.  Why is HttpClient so slow, I threw my MultiplexedWebSocket together very fast and have not really done any optimization to it either.  I'm hoping I'm just somehow using http/2 and the HttpClient incorrectly.  Thanks for your help.

MultiplexedWebSocket: 115,309 per second
HttpClient: 7,075 per second

https://github.com/AceHack/MultiplexedWebSockets

**Comment by Tratcher** [comment]
Note this is using the WinHttpHandler Http/2 implementation.

**Comment by AceHack** [comment]
@Tratcher yes that is correct, from the issues https://github.com/aspnet/KestrelHttpServer/issues/2993 it was my understanding that the default HttpHandler would not support http/2 until .NET core 3.0.  I'm happy to do the test with any supported http/2 client on any platform.  Thanks.

**Comment by Tratcher** [comment]
This issue was moved to dotnet/corefx#32849
