### ISSUE TITLE
Test failure: RequestBodyReadAsyncCanBeCancelled

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/KestrelHttpServer#3021]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](https://dnceng.visualstudio.com/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=31136) with the following error:

```
Assert.Equal() Failure
           ↓ (pos 1)
Expected: Hello 
Actual:   H
           ↑ (pos 1)
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on release/2.2.

CC muratg

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by muratg** [comment]
@halter73 @Tratcher @JunTaoLuo could one of you guys pick this up? Thanks.

**Comment by JunTaoLuo** [comment]
```
[xUnit.net 00:00:16.74]     RequestBodyReadAsyncCanBeCancelled [FAIL]
Failed   RequestBodyReadAsyncCanBeCancelled
Error Message:
 Assert.Equal() Failure
           ↓ (pos 1)
Expected: Hello 
Actual:   H
           ↑ (pos 1)
Stack Trace:
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.<>c__DisplayClass1_0.<<RequestBodyReadAsyncCanBeCancelled>b__0>d.MoveNext() in /_/test/Kestrel.InMemory.FunctionalTests/RequestTests.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.RequestBodyReadAsyncCanBeCancelled() in /_/test/Kestrel.InMemory.FunctionalTests/RequestTests.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
Standard Output Messages:
 | [0.001s] TestLifetime Information: Starting test RequestBodyReadAsyncCanBeCancelled at 2018-10-16T19:55:25
 | [0.003s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
 | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
 | [0.004s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly testhost
 | [0.004s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB" started.
 | [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  11
 | [0.013s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB", Request id "0HLHJK53GF8JB:00000001": started reading request body.
 | [0.015s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB" completed keep alive response.
 | [0.015s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3.8902ms 200 
 | [0.015s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLHJK53GF8JB", Request id "0HLHJK53GF8JB:00000001": the application completed without reading the entire request body.
 | [0.016s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB" closing because: "The client closed the connection."
 | [0.016s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB" disconnecting.
 | [0.016s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB", Request id "0HLHJK53GF8JB:00000001": done reading request body.
 | [0.016s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLHJK53GF8JB" bad request data: "Unexpected end of request content."
 | Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason) in /_/src/Kestrel.Core/BadHttpRequestException.cs:line 41
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync() in /_/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs:line 110
 |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
 |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
 |    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsyncAwaited() in /_/src/Kestrel.Core/Internal/Http/Http1MessageBody.cs:line 186
 | [0.017s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
 | [0.051s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLHJK53GF8JB" stopped.
 | [0.055s] TestLifetime Information: Finished test RequestBodyReadAsyncCanBeCancelled in 0.0542937s
```
