### ISSUE TITLE
Unusual HTTP response in ASP.NET Core web application

### ISSUE THREAD

**Issue by Jaffacakes82** [aspnet/KestrelHttpServer#3059]
### Disclaimer
I'm not 100% the issue I'm seeing is caused by Kestrel, however as the web server returning the unexpected status code I thought I'd raise this here and see if anyone clever has any bright ideas about what could be causing my issue!

### Problem
Our application is a ReactJS/ASP.NET Core web application hosted as a Web App in Azure. We use Okta for authentication and the login process looks like this:
1. User navigates to our website
2. On page load when not logged in, authorize attribute redirects to the `'/api/auth/login'` controller action
3. `'/api/auth/login'` invokes challenge and redirects to Okta
4. User logs in to Okta and is redirected back to callback URL specified in OpenID connect middleware
5. Web app redirects back to `'/api/auth/login'` to check if user is authenticated then redirects to `'/'` to render home page

When logging in to the Azure hosted application on Chrome using HTTPS, step 5 above does not redirect to `'/'` and instead the call to `'/api/auth/login'` is returning a 200. Nowhere in my controller action do I return a 200 here. This works locally when using chrome and HTTPS so it seems to be isolated to my application running in Azure.

**I do not experience this issue on any other browser apart from Chrome.**

### Login action
```csharp
[Route("login")]
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public IActionResult Login()
{
    if (!this.HttpContext.User.Identity.IsAuthenticated)
    {
          return this.Challenge(OpenIdConnectDefaults.AuthenticationScheme);
    }

    return this.Redirect("~/");
}
```

### Expected response when browsing over HTTP
<img width="589" alt="http azure" src="https://user-images.githubusercontent.com/4850159/47620418-d02e6b80-dae1-11e8-836f-c8e256af81d6.png">

### Unexpected response when browsing over HTTPS
<img width="593" alt="https azure" src="https://user-images.githubusercontent.com/4850159/47620421-d3c1f280-dae1-11e8-8c50-3afb45207d27.png">

I would appreciate any ideas, thanks.

**Comment by benaadams** [comment]
> Status Code 200 OK **(from ServiceWorker)**

Looks like its a Javascript [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) on your page that's poxying and returning the 200 (possibly caching it also)

**Comment by Jaffacakes82** [comment]
Super-star, I'm new to React and from your prompt and having a skim through our codebase it's pretty obvious that this is being registered by our React application.

Thanks for the swift reply.
