### ISSUE TITLE
Static files with whitespaces not working

### ISSUE THREAD

**Issue by devcube** [aspnet/KestrelHttpServer#306]
I'm serving two jpg files with KestrelHttpServer: "test.jpg" and "test with space.jpg".
The test jpg is served correctly but test%20with%20space.jpg gives me a 404.

I'm using DNX beta8 and I'm starting the server with "dnx web" where the web command in project.json is defined like this:
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  }

**Comment by Tratcher** [comment]
This was recently fixed in RC1 to correctly un-escape the path.

**Comment by devcube** [comment]
Whoa, that was fast. Thanks for the reply.
