### ISSUE TITLE
Kestrel listening port not released even after dotnet process is killed

### ISSUE THREAD

**Issue by TFTomSun** [aspnet/KestrelHttpServer#3060]
My setup:
I debug a client side test and start the asp.net core server application as a process from within the test. When I stop debugging, of course the dotnet process of the server application is still running. When I kill the application, the listen ports are still in use by the "System" process.

Any ideas how this can happen? How can I release the ports without a PC reboot?

netstat -abno states that the ports are in listening mode

**Comment by Tratcher** [comment]
This sounds a lot like https://github.com/aspnet/KestrelHttpServer/issues/2789, though inverted. Do you get different results if you try [Libuv](https://github.com/aspnet/Announcements/issues/296)?

**Comment by muratg** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
