### ISSUE TITLE
Interop tests cause chrome.exe console dialogs popups

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#3075]
Run the tests from VS on your dev machine and you'll get a series of console dialog boxes opening. These should be hidden. @JunTaoLuo

**Comment by JunTaoLuo** [comment]
I'm still seeing popups for https://github.com/aspnet/KestrelHttpServer/blob/ad3cba550955446cfa30db484c4160f569d16961/test/Kestrel.Transport.FunctionalTests/HandleInheritanceTests.cs#L40-L44 on full framework but we are just going to live with is as we plan to remove the full framework tests in 3.0
