### ISSUE TITLE
Server header still present after setting AddServerHeader to false

### ISSUE THREAD

**Issue by mmulhearn** [aspnet/KestrelHttpServer#3098]
Referring to https://github.com/aspnet/KestrelHttpServer/issues/852, the following code should remove the Server header from the response:

```
 public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseKestrel(k => k.AddServerHeader = false)
                .UseStartup<Startup>();
```

However, I am still seeing Server: Kestrel header in the response.  I have killed the process and re-built multiple times to no change.

Using Asp.Net Core 2.1.1.

**Comment by shirhatti** [comment]
Tried on 2.1,  does not repro.

**Comment by shirhatti** [comment]
@mmulhearn Feel free to re-open if you can provide more information on how you're seeing this.

**Comment by mmulhearn** [comment]
Just went and retired (having updated nugets and VS itself since then) and can no longer reproduce.  Not sure what happened there.  Looks good now.  Thanks.
