### ISSUE TITLE
IApplicationShutdown.RequestShutdown is does not serve the outstanding requests but dies

### ISSUE THREAD

**Issue by Praburaj** [aspnet/KestrelHttpServer#31]
Related# https://github.com/aspnet/WebListener/issues/71

Send a request to the application. It is expected to serve the outstanding requests and die. This works as expected on Helios. 

On Kestrel the event seems to be honored, but the outstanding request is not served. The host process simply gets killed. 

On weblistener this event is not being honored. This item tracks the issue for weblistener: https://github.com/aspnet/WebListener/issues/71
```
public void Configure(IApplicationBuilder app)
 {
app.UseServices();
app.Run(async context =>
                {
                    Console.WriteLine("Received shutdown request...");
                    var appShutdownToken = context.ApplicationServices.GetService<IApplicationShutdown>();
                    appShutdownToken.RequestShutdown();

                    try
                    {
                        if (!appShutdownToken.ShutdownRequested.IsCancellationRequested)
                        {
                            await Task.Delay(10 * 1000, appShutdownToken.ShutdownRequested);
                        }
                    }
                    catch (Exception exception)
                    {
                        Console.WriteLine(exception);
                    }

                    if (appShutdownToken.ShutdownRequested.IsCancellationRequested)
                    {
                        await context.Response.WriteAsync("Shutting down gracefully");
                    }
                    else
                    {
                        await context.Response.WriteAsync("Shutting down token not fired");
                    }
                });          
  }
```

**Comment by muratg** [comment]
I assume this bug is still valid?

@halter73

**Comment by muratg** [comment]
Yup, just checked with @anurse (who was playing with Kestrel) and Ctrl-C kills the process.

**Comment by muratg** [comment]
This is graceful shutdown (draining remaining requests after shutdown.)

@DamianEdwards Do you want this in RC1?  Pull to RC1 milestone if so.

**Comment by DamianEdwards** [comment]
I think post-RC is OK for this one.

**Comment by cesarbs** [comment]
I had to rewrite @Praburaj's code since a few things have changed since this issue was filed. I rewrote it as:

    Console.WriteLine("Received shutdown request...");
    var appLifeCycle = context.RequestServices.GetService<IApplicationLifetime>();
    appLifeCycle.StopApplication();

    try
    {
        if (!appLifeCycle.ApplicationStopping.IsCancellationRequested)
        {
            await Task.Delay(10 * 1000, appLifeCycle.ApplicationStopping);
        }
    }
    catch (Exception exception)
    {
        Console.WriteLine(exception);
    }

    if (appLifeCycle.ApplicationStopping.IsCancellationRequested)
    {
        await context.Response.WriteAsync("Shutting down gracefully");
    }
    else
    {
        await context.Response.WriteAsync("Shutting down token not fired");
    }

I can't repro the original issue. Kestrel shuts down gracefully after the request is received (the browser shows the respose `Shutting down gracefully`).

Let me know if I'm missing something here.

**Comment by cesarbs** [comment]
Closing since it's an old issue that does not repro anymore.

**Comment by yousifh** [comment]
Hi,

Maybe I'm misunderstanding the purpose of StopApplication() function, but if I do something like the following
```
app.Run(async context =>
{
	Console.WriteLine("Received shutdown request...");
	var appLifeCycle = context.RequestServices.GetService<IApplicationLifetime>();
	appLifeCycle.StopApplication();

	try
	{
		if (!appLifeCycle.ApplicationStopping.IsCancellationRequested)
		{
			await Task.Delay(10 * 1000, appLifeCycle.ApplicationStopping);
		}
	}
	catch (Exception exception)
	{
		Console.WriteLine(exception);
	}
        
       // Replace this with something that does long work, or maybe Task.Delay()?
	long total = 0;
	for (long i = 0; i < 9999999999; i++)
	{
		total =  i;
	}

	Console.WriteLine("Done?");

	if (appLifeCycle.ApplicationStopping.IsCancellationRequested)
	{
		await context.Response.WriteAsync("Shutting down gracefully");
	}
	else
	{
		await context.Response.WriteAsync("Shutting down token not fired");
	}
});
```

It never prints "Done?" on the console assuming of course it actually takes a relatively long time on your machine to go through the loop. Is StopApplication() supposed to make sure this thing completes its processing before it shuts down the process or no?

**Comment by halter73** [comment]
@yousifh If you remove the for loop do you see "Done?" and "Shutting down gracefully"?

Kestrel will not wait indefinitely for the application function to complete. In RC1-update1, I think it gives the app about 2.5 seconds to finish.

**Comment by yousifh** [comment]
@halter73 Yeah, it works fine once I remove the for loop. I wasn't aware the timeout Kestrel had while it waits to close down. I can see the 2.5 seconds timeout in KestrelEngine when it tries to stop each KestrelThread. Thanks.
