### ISSUE TITLE
How to add Security Headers in Response from server

### ISSUE THREAD

**Issue by Chetas1** [aspnet/KestrelHttpServer#3100]
Like in IIS server we have web.config file where if we add security headers like X-XSS-Protection , then in response we get that headers. Since i am using kestrel i am not getting where to add this security headers. Does this also has some configuration file where we could add security headers.

**Comment by Tratcher** [comment]
That wouldn't be done in Kestrel itself, it would be added via middleware. See https://github.com/aspnet/BasicMiddleware/issues/323 for the tracking issue and https://github.com/aspnet/Templating/issues/497#issuecomment-384765559 for an example.

Closing as a duplicate.
