### ISSUE TITLE
Publish 2.2 release to Nuget

### ISSUE THREAD

**Issue by TechnikEmpire** [aspnet/KestrelHttpServer#3104]
I see the 2.2 release is 20 hours old, but is not available on Nuget. Can you guys please upload it to Nuget? Excited to roll this into a project of mine.

**Comment by Tratcher** [comment]
Where'd you get the 20 hours figure?

We've got preliminary builds but we're still verifying them. We'll push them to to nuget as soon as we're ready.

**Comment by TechnikEmpire** [comment]
@Tratcher My spies in Microsoft told me. They helpfully posted it to the Releases page, which says 21 hours ago now. ;)

**Comment by TechnikEmpire** [comment]
Must have been auto generated when tagged. Thanks for all the hard work guys. :)
