### ISSUE TITLE
Provide option to not catch all request exceptions

### ISSUE THREAD

**Issue by sambauwens** [aspnet/KestrelHttpServer#3106]
When I'm debugging my server code, I like to break on unhandled exceptions right into context. I noticed that when debugging my aspnet core application it never breaks in my code.

The last line of my stacktrace is :
```
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I did some research, and noticed [HttpProtocol.ProcessRequestsAsync()](https://github.com/aspnet/KestrelHttpServer/blob/5d80016b4fb991acf6f639549b784ed5882d8de0/src/Kestrel.Core/Internal/Http/HttpProtocol.cs#L461) does seem to catch all exceptions unconditionnally.

So I would appreciate a configuration option that I set when the debugger is attached and which tells kestrel not to catch exceptions.

**Comment by benaadams** [comment]
You can change the debugger settings to break when the exception happens https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2017

**Comment by Tratcher** [comment]
What if we called Debugger.Break() for caught exceptions if the debugger was attached?

**Comment by muratg** [comment]
We won't be making any changes here. You can create a middleware to do a Debugger.Break with the try catch block.
