### ISSUE TITLE
Unit test : Could not load file or assembly 'Leadtools.Document.Writer, Version=20.0.4.0, Culture=neutral, PublicKeyToken=9cf889f53ea9b907' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by somsekhar** [aspnet/KestrelHttpServer#3107]
Created console application for OCR with LeadTools SDK and it works fine.
 
Added unit test application and given reference of OCR project.
When unit test runs throwing an error. **_Could not load file or assembly 'Leadtools.Document.Writer, Version=20.0.4.0, Culture=neutral, PublicKeyToken=9cf889f53ea9b907' or one of its dependencies. An attempt was made to load a program with an incorrect format._**

Both the applications are created using .Net Framework 4.6.1

**Comment by Tratcher** [comment]
What does this have to do with AspNet Core?
