### ISSUE TITLE
[Announcement] Kestrel on Linux now tries to load libuv.so instead of libuv.so.1

### ISSUE THREAD

**Issue by moozzyk** [aspnet/KestrelHttpServer#323]
Discussion for https://github.com/aspnet/Announcements/issues/100

**Comment by akoeplinger** [comment]
Loading the .so directly is a bad practice on Linux (it typically requires the `-dev` packages). Let's hope CoreCLR comes up with a solution soon, e.g. via dllmap functionality.

**Comment by moozzyk** [comment]
https://github.com/dotnet/coreclr/issues/930

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
