### ISSUE TITLE
UvTcpHandle life not managed explicitly

### ISSUE THREAD

**Issue by migueldeicaza** [aspnet/KestrelHttpServer#328]
While investigating the peformance problems of Kestrel on Mono we identified a strange pause and a strange set of socket errors that would happen every once in a while.

The problem is caused because Kestrel depends on the GC finalization to release its hold on the UvTcpHandle instead of explicitly disposing the objects.

**Comment by schani** [comment]
Specifically, the server will eventually become completely unresponsive after a while.  This can be exacerbated either by using a very large nursery (try `MONO_GC_PARAMS=nursery-size=1g`) or disabling finalization (`MONO_GC_DEBUG=do-not-finalize`).

**Comment by halter73** [comment]
I just added the following to UvTcpHandle:

        ~UvTcpHandle()
        {
            System.Diagnostics.Debugger.Launch();
        }

And ran build.cmd which runs all our unit and functional tests on core and desktop clr. As far as I can tell, the finalizer never got hit.

This makes sense as a quick scan of the code seems to show a corresponding call to Dispose for every `new UvTcpHandle`.

Does anyone have any details that could help me figure out what conditions are necessary to prevent UvTcpHandles from being disposed?

**Comment by schani** [comment]
Running the Kestrel server for this benchmark, on Mono: https://github.com/schani/benchmarks/tree/master/src/Benchmarks

I need to specify a small enough nursery, otherwise the GC never gets around to finalizing the objects.  I'm using

    MONO_GC_PARAMS=nursery-size=128k MONO_GC_DEBUG=log-finalizers

Then all I have to do is

    wrk -c 1024 -t 32 http://localhost:5001/plaintext

and I get lots of these:

    mono-gc-finalizers: <UvTcpHandle at 0x7fbd03fe0eb0> Starting finalizer checks.
    mono-gc-finalizers: <UvTcpHandle at 0x7fbd03fe0eb0> Registered finalizer as processed.
    mono-gc-finalizers: <UvTcpHandle at 0x7fbd03fe0eb0> Compiling finalizer.
    mono-gc-finalizers: <UvTcpHandle at 0x7fbd03fe0eb0> Calling finalizer.
    mono-gc-finalizers: <UvTcpHandle at 0x7fbd03fe0eb0> Returned from finalizer.

Running on 1.0.0-beta8, as per `project.json`.

**Comment by benaadams** [comment]
Is it because `UvTcpHandle`->`UvStreamHandle`->`UvHandle`->`UvMemory`->`SafeHandle` which has a finalizer?

**Comment by benaadams** [comment]
nvm inheritence chain implementation appears to be correct

**Comment by migueldeicaza** [comment]
Mark found that UvTcpHandles created here are not being disposed, perhaps there is a codepath that is not being taken?

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/TcpListener.cs#L39

@halter73 That would happen when Accept throws an exception.

**Comment by benaadams** [comment]
@migueldeicaza I had a look at the source for `SafeHandle` and not quite understanding how it works in mono - it doesn't seem to implement `IDisposable`

https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs#L64

as it does in the clr

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/InteropServices/SafeHandle.cs#L140

I assume Dispose still works on it, though it doesn't seem to have the method? As it should be being closed here: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/SocketOutput.cs#L541

**Comment by migueldeicaza** [comment]
That file has half the implementation, the other half is now part of reference source:

https://github.com/mono/referencesource/blob/mono/mscorlib/system/runtime/interopservices/safehandle.cs

**Comment by migueldeicaza** [comment]
But if the Accept throws, how is that ever recorded on the SocketOutput.cs for it to Dispose it?

**Comment by cesarbs** [comment]
@migueldeicaza It's not. I'm looking at this right now and will dispose the socket in the `catch` block.

**Comment by cesarbs** [comment]
With #328 merged, there should be no more sockets being leaked after calls to `Accept()`.
