### ISSUE TITLE
Kestrel and Windows 10 Universal Applications

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/KestrelHttpServer#333]
I'm not sure if this is even possible or weather it is a goal of the project; but I would like to host Kestrel and MVC 6 from inside a Windows Universal Application; in particular a background task running on the Raspberry PI.

Is this possible? is there any work on this? any information greatly appreciated.

**Comment by davidfowl** [comment]
Might be possible but nobody has tried it nor is it a priority for us. Feel free to try it out and hack around the code to make it work.

**Comment by grahamehorner** [comment]
@davidfowl I will investigate and start logging and issues that I come across, I understand RC is a priority.

**Comment by barnstee** [comment]
I had a look at this, got it compiling, but not running fully. Here is analysis:
1. UWP doesn't support System.Threading.Thread or System.Threading.ThreadPool, so Thread.CurrentThread.ManagedThreadId becomes Task.CurrentId, WaitCallback becomes Action<object>, Thread.Join() becomes Task.Wait() and ThreadPool.QueueUserWorkItem() becomes Task.Run().
2. UWP also doesn't support Microsoft.Extensions.FileProviders.Physical and Microsoft.Extensions.PlatformAbstractions, so ContentRootFileProvider was deleted (not used), ApplicationBasePath becomes Directory.GetCurrentDirectory() and ApplicationName becomes this.GetType().GetTypeInfo().Assembly.GetName().Name.
3. NuGet package references from referenced .NetStandard assemblies in UWP projects don't resolve yet, so I had to manually add all referenced NuGet package to my UWP project, including Libuv.
4. All changes above are backward compatible to .NetCore, so my .NetCore console test apps still work fine with these changes.
5. And here the pickle: Libuv uses named pipes internally, which are not supported in UWP (you get -4091 "address already in use" errors during pipe binding. I don't see an easy way to remove this dependency from Libuv. So close, but no cigar. :-/

**Comment by moozzyk** [comment]
I actually talked to @munyirik a few days ago and the problem is that you cannot run stock libuv in UWP sandbox and this is what Kestrel uses.

**Comment by muratg** [comment]
WebListener will be the the story for UWP.
