### ISSUE TITLE
RequestBody draining still allocates per-request buffers

### ISSUE THREAD

**Issue by rynowak** [aspnet/KestrelHttpServer#334]
This change: https://github.com/aspnet/KestrelHttpServer/commit/4bba074d778933b312011df0ade8ff875250cded

Fixed a serious allocation issue, but also added a 4kb buffer to each frame, which is more per-request allocation. Simply just making this `static` as well may not do what we want, as this might lead to a lot of contention for this cache line.

I think we need to revisit the original proposal which was to implement `CopyToStreamAsync` in a smarter way.

Allocation data for 3000 requests:
![image](https://cloud.githubusercontent.com/assets/1430011/10986424/b473327a-83de-11e5-8679-9a70ae95d450.png)

In my sample app, this is responsible for 12/82mb allocated

**Comment by benaadams** [comment]
This is only on fresh connections, not keep alive already open connections?

**Comment by benaadams** [comment]
Raised PR #335 "Use pooled array"

**Comment by halter73** [comment]
I guess I didn't look at the PR that added `_nullBuffer` closely enough. I thought `_nullBuffer` was static. Is there any reason it can't be static? I think that would even be more efficient.

**Comment by rynowak** [comment]
All of these solutions involve copy bytes from one location to another in memory. Wouldn't it be better to override `CopyToAsync` and special case `Stream.Null`?

**Comment by halter73** [comment]
@rynowak That's definitely an option. We were considering a change to make CopyToAsync bufferless in all cases, but that seemed to be a little to complex for a last minute rc1 fix.

It might make more sense just to add a new method to FrameRequestStream that efficiently consumes the rest of the request rather than overriding CopyToAsync and checking if the argument is Stream.Null only to do the same thing.

**Comment by rynowak** [comment]
:arrow_up: either of those would work.

**Comment by benaadams** [comment]
> I thought _nullBuffer was static. Is there any reason it can't be? I think that would even be more efficient.

Because you'll have multiple threads writing to it on different cores and cause cpu cache thrashing.

**Comment by benaadams** [comment]
>  add a new method to FrameRequestStream that efficiently consumes the rest of the request

:+1: 

Could even just call it directly in Frame

**Comment by benaadams** [comment]
Something that fasts forwards to the end rather than doing the copy to a buffer would be better; as should be less work?
