### ISSUE TITLE
KestrelHttpServer hangs when attacked with multiple requests, e.g. hit F5 multiple times in the browser

### ISSUE THREAD

**Issue by poparta** [aspnet/KestrelHttpServer#34]
This is easy to reproduce with the samples - tested with MusicStore and HelloMVC on ubunto 14.04, Kestrel 1.0.0-alpha4 and latest libuv 1.0.0.x, compiled from sources.

**Comment by Tragetaschen** [comment]
With #60:

```
Finished 3000 requests
[...]
Concurrency Level:      50
Time taken for tests:   2.627 seconds
Complete requests:      3000
Failed requests:        0
[...]
Requests per second:    1142.09 [#/sec] (mean)
```
Ending Kestrel after the run doesn't show any Finalizer warnings.

**Comment by muojp** [comment]
@Tragetaschen wow, great work! :smile: :cat:

**Comment by poparta** [comment]
Indeed, great work! :+1:

**Comment by teherty** [comment]
So is there any workaround for this issue as it still replicates?
