### ISSUE TITLE
Don't need extra ContainsKey check in Frame.FeatureCollection

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#348]
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.FeatureCollection.cs#L285

/cc @benaadams @lodejard @halter73

**Comment by benaadams** [comment]
Not sure about this?

Is saying if the response doesn't already have Upgrade header, overwrite with the request Upgrade header

**Comment by davidfowl** [comment]
Wow! I read that as the same collection. Closing :smile:
