### ISSUE TITLE
DNX Beta-8 Publish HttpPlatformHandler cannot be found. This error is random

### ISSUE THREAD

**Issue by CarlosFreire** [aspnet/KestrelHttpServer#355]
The description for Event ID 1001 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Process '4248' started successfully and is listening on port '12618'.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#32
