### ISSUE TITLE
IHttpRequestFeature.Scheme not set to HTTPS

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#365]
When using HTTPS/TLS the IHttpRequestFeature is not set accordingly, all requests are reported as http.

**Comment by NickCraver** [comment]
What's the expectation on reporting in the SSL termination (e.g. reverse proxy) case? For example, will Kestrel eventually be aware of the `X-Forwarded-Proto` chain or is that entirely up to the application to determine?

**Comment by halter73** [comment]
@NickCraver I think the expectation is that the developer needs to add our [OverrideHeaderMiddleware](https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderMiddleware.cs) if they're behind a reverse proxy.

**Comment by NickCraver** [comment]
@halter73 ah just what I was looking for, thanks! The middleware seems incorrect though. For example, X-Forwarded-Proto is a comma list as well, not a single entry...it's just *usually* a single entry. The "spec" is multiple though, for example CloudFlare adds one and HAProxy adds one in our case.

**Comment by NickCraver** [comment]
@halter73 I appreciate the link; I couldn't find that when looking. Issue opened on that repo: https://github.com/aspnet/BasicMiddleware/issues/18

**Comment by halter73** [comment]
Fixed by #385
