### ISSUE TITLE
Lots of byte[] arrays allocated by kestrel

### ISSUE THREAD

**Issue by rynowak** [aspnet/KestrelHttpServer#371]
Allocations for 3000 requests

![image](https://cloud.githubusercontent.com/assets/1430011/11108566/ac3eb094-889c-11e5-8cd9-ec421a95a5bd.png)

**Comment by rynowak** [comment]
Looks like we regressed here: https://github.com/aspnet/KestrelHttpServer/commit/d08b83a1c7241bca66c6934facb2410f118489c3

It should be safe to statically cache the platform right?

**Comment by DamianEdwards** [comment]
Probably should change to use `System.Runtime.InteropServices.RuntimeInformation` instead (package & a class).

**Comment by davidfowl** [comment]
Yep!

**Comment by troydai** [comment]
Fixed in https://github.com/aspnet/KestrelHttpServer/commit/2e2dfd87c1dcd5c286679276670becc9b34fc8c4
