### ISSUE TITLE
Throwing in async void methods crash Kestrel

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/KestrelHttpServer#398]
A customer reported that throwing in their `TagHelper` caused Kestrel to crash. Turns out they were using `async void` which resulted in the crash. The original thread is [here](https://github.com/aspnet/Razor/issues/607).

Validated that WebListener/IISExpress do not crash from the same bits. Helios must tie into the appdomain exceptions whereas IISExpress lets the underlying server crash and then reboots upon a new request. Here's the minimal repro `Startup.cs`:

```C#
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        app.Run(async (context) =>
        {
            Throw();

            await context.Response.WriteAsync("Hello World!");
        });
    }

    public async void Throw()
    {
        throw new InvalidOperationException("You do bad");
    }

    public static void Main(string[] args) => WebApplication.Run<Startup>(args);
}
```

**Comment by Tratcher** [comment]
I recommend moving this to Hosting, it's not a Kestrel specific issue.

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Hosting#484
