### ISSUE TITLE
Add tons of tracing

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#4]
Need to figure out what xplat apis that should be based on. 

_Updated by Troy_
Here's a task break down:
- [ ] Logging swallowed exceptions
- [x] Optimize the Kestrel trace interface (optional)
- [x] Remove `IKestrelTest` interface.

_Updated by @lodejard_
Never Log request/response headers

**Comment by troydai** [comment]
/cc @muratg @davidfowl @Tratcher 
since @JunTaoLuo  is take on the another round of refactory of Hosting, I believe this should be part of that work as well.

**Comment by JunTaoLuo** [comment]
I believe there is no longer any working items here after we decided not to log any headers of requests and responses due to security concerns. The logging of swallowed exceptions has already been implemented for Kestrel.
