### ISSUE TITLE
Don't wait to consume the entire request body for Connection: close requests

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#406]
If you hit a sample app running on Kestrel with ab (apache bench which makes HTTP/1.0 requests), every request times out.

This is caused by Kestrel becoming stuck on `await messageBody.Consume()` in `Frame.RequestProcessingAsync`.

I think we fix this by simply not consuming the rest of the request for non keep-alive connections.

**Comment by benaadams** [comment]
Was putting a PR together for this but it needs to go after "Precomputed header bytes" #367 if that's happening as its all change

**Comment by cesarbs** [comment]
@benaadams The fix is simple. I was thinking something like:

                                if (_keepAlive)
                                {
                                    // Finish reading the request body in case the app did not.
                                    await messageBody.Consume();
                                }

Is this what you were thinking? The only reason this isn't in a PR yet is we need a regression test.

**Comment by benaadams** [comment]
@cesarbs yes, good point :)

**Comment by cesarbs** [comment]
Closed by https://github.com/aspnet/KestrelHttpServer/commit/e4fd91bb68f535801ca8a79aa453ea3fb3f448fe.

**Comment by amcdnl** [comment]
@cesarbs Is this related? https://github.com/BrowserSync/browser-sync/issues/905

**Comment by cesarbs** [comment]
@amcdnl Looks like it.
