### ISSUE TITLE
Originating request IP address retrieval

### ISSUE THREAD

**Issue by sqmgh** [aspnet/KestrelHttpServer#414]
It appears that the ability to retrieve this information is governed by support for IHttpConnectionFeature.
However, [support for this is listed as 'No'](https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/servers.rst#supported-features-by-server). This is backed up by the fact that Kestrel returns null when you try and Get() the feature.

While the other two options on that page do support it, I was under the impression that they were either deprecated, or discouraged. When Kestrel being the recommended hosting platform circa beta 8(?).

Not having this information available seems like a strange oversight to me, so am I missing something?
Is there some other way that I am missing to get this information in Kestrel?
If not, does 'No' mean never, or is it just something that's on the roadmap which hasn't arrived yet? 
If it is something on the roadmap, then is there an approximate ETA for when support will be added?

I have a project that will require a flag to be set if the request is sent from within the internal network, and I would rather not get myself into a situation where I am going to need to be scrounging for third party hosting support because the official recommended hosting option doesn't support it.

**Comment by borgdylan** [comment]
Getting the requestor's IP is available in the CI packages destined for RC2 if I'm not mistaken.

**Comment by halter73** [comment]
@borgdylan That's correct.

**Comment by halter73** [comment]
Dup of https://github.com/aspnet/KestrelHttpServer/issues/67
