### ISSUE TITLE
rc1-final: Apache's "ab" load testing tool fails with "apr_poll: The timeout specified has expired"

### ISSUE THREAD

**Issue by kcraft** [aspnet/KestrelHttpServer#426]
Example output:

```
root@0ee5a943ade0:/# ab -r -c 1 -n 1 http://myurl.com/mypath/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking myurl.com (be patient)...apr_poll: The timeout specified has expired (70007)
```

Curl works fine:

```
root@0ee5a943ade0:/# curl http://myurl.com/mypath
{"Status":"OK"}
```

I found this issue on nodejs which mentions libuv as a possible culprit: https://github.com/nodejs/node-v0.x-archive/issues/1279

I'm running this inside of a base debian:wheezy docker container after running  ```apt-get install apache2-utils```. The Kestrel server is running in another docker container based on the ```microsoft/aspnet:latest``` image.

**Comment by benaadams** [comment]
Should be resolved by https://github.com/aspnet/KestrelHttpServer/pull/413 which was after rc1-final

**Comment by halter73** [comment]
Thanks for the report. Fortunately, the fix for this should be included in the next release.

dup of #406
