### ISSUE TITLE
Returns 200 for unhandled exceptions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#43]
When the application throws an exception and it is caught by the server, Kestrel returns the current response as is. See Frame.ExecuteAsync(). It should send a 500 error response instead.

Expected behavior:
- If the headers have been sent:
 - Abort the connection
- If the headers have not been sent:
 - Set the status code to 500
 - Clear the response headers
 - Do not fire the OnSendingHeaders event
 - Send the response

**Comment by davidfowl** [comment]
@muratg I moved this bug to beta6.
