### ISSUE TITLE
Proposal: Improve the precision and speed of DateHeaderValueManager

### ISSUE THREAD

**Issue by tenor** [aspnet/KestrelHttpServer#430]
The `System.Timer` that fetches the time from the RTC in DateHeaderValueManager has an interval of one second. That means the precision can not be higher than one second.
Also, calls to `GetDateHeaderValue` call `PumpTimer()` which involves a `lock`, effectively serializing all calls to this method.

The following proposal improves the precision and speed of DateHeaderValueManager:

Instead of `PumpTimer()`, have `StartTimer()` and `StopTimer()` methods.
`StartTimer` will:

1. Calculate a `_lastReadTime` long value. (more on this later)
2. Calculate a `_lastReadStringTime` string or byte array value.
3. If the object isn't disposed,  set a volatile\interlocked boolean value called `_timerIsRunning` to true and start the timer loop.

The timer loop, will read the UTC time from the RTC every 10 ms, convert it to ticks and store it in a long called `_currentTime`.

`GetDateValue()` will look like this:

```csharp
 byte[]/string GetDateValue()
{
  if(!_timerIsRunning){StartTimer();}
     return ReadDateValue();
}

private ReadDateValue()
{
long currentTime;
if(_disposed)
{
 currentTime = GetFromRTC();
}
else
{
  currentTime = ReadCurrentTime(); //This performs a dirty read on _currentTime, or Interlocked.Read on 32-bit systems.
}

if (_lastReadTime - currentTime > threshold \* 100 ms*\)
{
  if (interlocked.CompareExchange(ref _lastReadTime, ref currentTime)
  {
    var _newTimeString = CalculateTimeString(_lastReadTime);
    Interlocked.CompareExchange(ref _lastReadTimeString, ref _newTimeString);
  }
}

 return _lastReadTimeString;

}
```

This proposal eliminates the `lock` in `PumpTimer()` and increases the time precision to 100ms.
I'm not sure this will move the overall performance needle in Kestrel but I think it's worth checking out.

I can provide a PR if the team finds this approach interesting.

**Comment by davidfowl** [comment]
Make sure to show some performance results with the pull request. That'll be more convincing than anything else.

**Comment by khellang** [comment]
> That means the precision can not be higher than one second.

Just curious, why would you need a precision higher than one second when format used is RFC1123, e.g. `Sat, 28 Nov 2015 20:45:30 GMT`?

**Comment by tenor** [comment]
@khellang  :smile:  I didn't even look at that time format. I'll have to rethink this.
@davidfowl I'll have a PR ready in a day or two.

**Comment by benaadams** [comment]
The date header is used to workout if caches need to be updated vs max-age (which is normally minutes, hours, days, weeks, months or even a year) http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2.3 not sure a second here or there is that important in the scheme of things...

**Comment by muratg** [comment]
Looks like this has been merged. If there's additional work to be done, please feel free to open another one.

Thanks for the PR!
