### ISSUE TITLE
Kestrel connection limits on Windows?

### ISSUE THREAD

**Issue by marce155** [aspnet/KestrelHttpServer#435]
I'd like to test drive a .NET 4.6 application on Kestrel (so Linux doesn't work afaik) including some load testing.
I was able to grab a potent enough machine but no server OS and am now worried if Kestrel suffers from the same "10 concurrent requests" disease IIS has on client Windows?

If necessary I could install a Server 2012 trial just for the test, but it would be good to know in general.

**Comment by Daniel15** [comment]
It shouldn't, Kestrel is built using a totally different stack using libuv, the same library that powers connections in Node.js. It doesn't use any pieces of IIS.

**Comment by halter73** [comment]
@Daniel15 is correct. Kestrel does not share IIS/HTTP.sys concurrent connection limits unless it is behind an IIS module (i.e. [HttpPlatformHadler](http://www.iis.net/downloads/microsoft/httpplatformhandler)), so you are not going to run into the 10/20 concurrent requests "disease". I regularly test Kestrel on my Windows 10 laptop with hundreds of remote concurrent connections.
