### ISSUE TITLE
Kestrel build is failing (locally and in appveyor)

### ISSUE THREAD

**Issue by jonburney** [aspnet/KestrelHttpServer#442]
Kestrel build of dev is failing both locally and in build agents

https://ci.appveyor.com/project/aspnetci/KestrelHttpServer/branch/dev

```
Building Microsoft.AspNet.Server.Kestrel for DNX,Version=v4.5.1 
C:\projects\kestrelhttpserver\src\Microsoft.AspNet.Server.Kestrel\KestrelServer.cs(44,37): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'IHttpApplication<TContext>' could not be found (are you missing a using directive or an assembly reference?)
C:\projects\kestrelhttpserver\src\Microsoft.AspNet.Server.Kestrel\Http\FrameOfT.cs(15,26): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'IHttpApplication<TContext>' could not be found (are you missing a using directive or an assembly reference?) 
C:\projects\kestrelhttpserver\src\Microsoft.AspNet.Server.Kestrel\Http\FrameOfT.cs(17,22): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'IHttpApplication<TContext>' could not be found (are you missing a using directive or an assembly reference?) 
C:\projects\kestrelhttpserver\src\Microsoft.AspNet.Server.Kestrel\Http\FrameOfT.cs(23,22): DNX,Version=v4.5.1 error CS0246: The type or namespace name 'IHttpApplication<TContext>' could not be found (are you missing a using directive or an assembly reference?) 
C:\projects\kestrelhttpserver\src\Microsoft.AspNet.Server.Kestrel\KestrelServer.cs(14,34): DNX,Version=v4.5.1 error CS0535: 'KestrelServer' does not implement interface member 'IServer.Start(RequestDelegate)' 
```
Looks related to https://github.com/aspnet/KestrelHttpServer/commit/168f4770f450d3b3ca73c2330d42c8f64661b899

**Comment by jonburney** [comment]
@JunTaoLuo is this related to your last merge? https://github.com/aspnet/KestrelHttpServer/commit/168f4770f450d3b3ca73c2330d42c8f64661b899

**Comment by benaadams** [comment]
@jonburney think its ok now? Upstream packages needed some time to work through?

**Comment by muratg** [comment]
Travis also seems to be failing: https://travis-ci.org/aspnet/KestrelHttpServer/builds/94258362

**Comment by Tratcher** [comment]
Yes, there were breaking changes in Hosting, Kestrel, and WebListener. aspnetcidev might not be updated yet (that's what travis and build.cmd depend on). aspnetvolatiledev should work if you need to get unblocked.

**Comment by JunTaoLuo** [comment]
I believe @pranavkm is looking to fix the build after Roslyn updates broke our CI.

**Comment by JunTaoLuo** [comment]
Resolved. Closing

**Comment by JunTaoLuo** [comment]
Travis: https://travis-ci.org/aspnet/KestrelHttpServer

@jonburney @benaadams Please restore with the latest packages on aspnetcidev

**Comment by jonburney** [comment]
@JunTaoLuo @pranavkm thank, will do!
