### ISSUE TITLE
Sub-applications within IIS don't work anymore

### ISSUE THREAD

**Issue by Fosol** [aspnet/KestrelHttpServer#449]
I used to be able to publish an aspnet 5 beta 7 web application as a sub-application.  Since I'm upgrading to rc1-final I am no longer able to do it.

Here is the error I get when I attempt to call the sub-application within IIS.
> Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'httpplatformhandler' 

I can of course publish to a separate root IIS application and it will work, but of course that breaks the whole architecture of the application.

It's the result of the web.config changes that occurred.  
```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout.log"></httpPlatform>
  </system.webServer>
</configuration>
```

So how do I publish in the new world?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#44

**Comment by Fosol** [comment]
We tried removing the handler from the sub-application. The sub-application will only throw 404s from that point on.

This is a bug or a change that requires information to implement.
