### ISSUE TITLE
Manually set scheme to https in HttpContext

### ISSUE THREAD

**Issue by chinarosesz** [aspnet/KestrelHttpServer#454]
I am updating my website from beta7 to rc1. Since Microsoft.Aspnet.Server.IIS is not available in rc1, I replaced it with the following two references:

    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel.Https": "1.0.0-rc1-final",

I then added the following lines of code in order to get Kestrel to load my website in SSL. The website uses Azure AD for authentication, but the login redirect URL is not using "https" because the HttpContext scheme is always set to "http", that's why I had to update the scheme manually. Here is the code in Startup.cs.

       app.Use(Startup.ChangeContextToHttps);
       app.UseKestrelHttps(myCertificate);

        private static RequestDelegate ChangeContextToHttps(RequestDelegate next)
        {
            return async context =>
            {
                context.Request.Scheme = "https";
                await next(context);
            };
        }

Is this the correct fix?

**Comment by halter73** [comment]
@chinarosesz Thanks for the report.

What you have is the correct fix for now. In rc2 the scheme should be correctly set to https without the need for custom middleware. See https://github.com/aspnet/KestrelHttpServer/issues/365.
