### ISSUE TITLE
System.EntryPointNotFoundException: uv_loop_size when running "dnx web"

### ISSUE THREAD

**Issue by wycoconut** [aspnet/KestrelHttpServer#461]
Hi team,

Just took some time to take kestrel out for a spin today.
** Note that I am really new to this terminal thingy so there might be some stuff I missed along the way.

My environment:
- Mac OS X - 10.9.5

What happened:
Tried to follow instructions noted here : http://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html
I used the easy way but somehow it installed the old 1.0.0 versions and it was also telling omnisharp server was not running.

So I followed this link : http://stackoverflow.com/questions/34084694/visual-studio-code-mac-os-x-omnisharp-server-is-not-running to resolve the issue.

Then after I created a test empty app using yo aspnet, build (no errors) and do a "dnx web", I get this error:
![image](https://cloud.githubusercontent.com/assets/5443702/11658510/086ddc16-9dfe-11e5-8869-b950a4a8a531.png)

I googled and it seems that the libuv library was probably not of the right version of my machine, so I used homebrew to install libuv by running "brew install libuv", and according to this recommendation http://stackoverflow.com/questions/31976732/kestrel-command-throws-unable-to-load-libuv-make-sure-libuv-is-installed-and-av make the necessary adjustments to the ~/.bash_profile 

This is what I have on my Mac now:
**execute terminal command : "dnvm list"**
![image](https://cloud.githubusercontent.com/assets/5443702/11658766/665bdeda-9dff-11e5-9d68-a7a23c7b9acd.png)

**~/.bash_profile**
![image](https://cloud.githubusercontent.com/assets/5443702/11658423/767ced9c-9dfd-11e5-9a8a-fb678ac27824.png)

**TestEmptyApp project.json**
![image](https://cloud.githubusercontent.com/assets/5443702/11658629/9248380a-9dfe-11e5-9d72-aa13b6f985cb.png)

**project.lock.json**
[project.lock.json.zip](https://github.com/aspnet/KestrelHttpServer/files/55600/project.lock.json.zip)

**information about the libuv I installed through homebrew, this says its 1.7.5**
![image](https://cloud.githubusercontent.com/assets/5443702/11658709/f1fe4514-9dfe-11e5-8e45-0181a5f2ec0e.png)

Understandably it is still at RC2 but I wouldn't mind understanding what happened, and how I can link back the latest libuv to get KestrelHttpServer working again.  Would also be willing to help update the docs at https://github.com/aspnet/Docs too.

Thanks in advance for the help.

**Comment by acastaner** [comment]
I'm running into the same issue on CentOS 6.5, using 1.0.0-rc1-update1. It's been a while since I installed libuv so I will double check and update this issue.

Note that the same application works fine on Ubuntu 15.04.

**Comment by acastaner** [comment]
Actually this was a quick check. I'm using libuv 1.4.2 as per the installation instruction and get this error:

`[user@somewhere WebApi]$ dnx web
Could not determine OS version information. Defaulting to the empty string.
System.EntryPointNotFoundException: uv_loop_size
  at (wrapper managed-to-native) Microsoft.AspNet.Server.Kestrel.Networking.Libuv/NativeMethods:uv_loop_size ()
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.loop_size () [0x00000] in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNet.Server.Kestrel.Networking.Libuv uv) [0x00000] in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) [0x00000] in <filename unknown>:0 
[user@somewhere WebApi]$`

**Comment by davidfowl** [comment]
What version of mono!

**Comment by acastaner** [comment]
I'm running Mono 4.0.1

**Comment by cesarbs** [comment]
@wycoconut @acastaner Do you see the same on CoreCLR?

**Comment by wycoconut** [comment]
OK I did the following:
```
dnvm install 1.0.0-rc1-update1 -r coreclr -arch x64
```
then
```
dnvm use 1.0.0-rc1-update1 -r coreclr -arch x64
```
then
```
dnvm list
```
then go to my project and
```
dnx web
```
Looks like its working, here's a screenshot of the result:
![image](https://cloud.githubusercontent.com/assets/5443702/11829360/ebb1932c-a3d6-11e5-9d6c-c0dc09882206.png)

**Comment by cesarbs** [comment]
Ok. Then it seems like a Mono issue. You might want to forward this to them.

**Comment by wycoconut** [comment]
@davidfowl For the sake of completion of this post, I was running Mono 4.2.1

**Command**
```
mono --version
```

**Result**
![image](https://cloud.githubusercontent.com/assets/5443702/11833446/ab4d69a6-a3fd-11e5-9a65-c38a59eca7ef.png)

**How it was updated**
I had Xamarin Studio For Mac installed on my machine and it was through the application updates that updated the framework on my machine.

**Comment by lacostenycoder** [comment]
Can't figure this out... any ideas?
```
dnx web
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/Users/lancejordan/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
System.EntryPointNotFoundException: uv_loop_size
  at (wrapper managed-to-native) Microsoft.AspNet.Server.Kestrel.Networking.Libuv+NativeDarwinMonoMethods:uv_loop_size ()
  at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.loop_size () <0x10c166840 + 0x0001c> in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init (Microsoft.AspNet.Server.Kestrel.Networking.Libuv uv) <0x10c166780 + 0x0004b> in <filename unknown>:0 
  at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart (System.Object parameter) <0x10c166280 + 0x0008b> in <filename unknown>:0 

$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-rc1-update1    mono                 linux/osx       default
       1.0.0-rc2-16351      mono                 linux/osx       

```

**Comment by davidfowl** [comment]
Does mono 4.0.5 work?

**Comment by lacostenycoder** [comment]
@davidfowl I did brew log mono and don't see that version in a any previous commit.  It jumps from 4.0.2.5  to 4.2.0.179.  Is there another way to install 4.0.5 via homebrew?  Should I ditch brew version and install from http://www.mono-project.com ?

**Comment by crowdy** [comment]
having same trouble on centos7 mono 4.2.1

![centos7_mono_kestrel_trouble](https://cloud.githubusercontent.com/assets/145349/12467812/ed35fd5c-c021-11e5-9f04-c4e1a07461c7.png)

**Comment by wmeints** [comment]
I'm experiencing the exact same error on Mac OSX 10.11.2
Using Mono 4.2.1

Had to upgrade to RC2 to get things working again.
