### ISSUE TITLE
Can Middleware modify Response In OnCompleted callback?

### ISSUE THREAD

**Issue by tenor** [aspnet/KestrelHttpServer#471]
Looking at [FrameOfT#98](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/FrameOfT.cs#L98).

It doesn't seem like there's anything to prevent Middleware from modifying the response in the `OnCompleted` callback.

Does `OnCompleted` mean the application response has been received by the server, and so Middleware can add extra stuff to the response stream (diagnostics for instance) 
 or does it mean the response has been fully received and has been sent (or is being sent) to the client, so Middleware can clean up any resources attached to this request?

**Comment by Tratcher** [comment]
No, use OnStarting if you want to modify any headers. OnCompleted only fires after the response is finished sending to the client. It's primarily used for cleanup.

**Comment by tenor** [comment]
I'm able to append to the response stream in `OnCompleted`.

This action reproduces the issue:

```csharp
public IActionResult Index()
{
    var trailer = System.Text.Encoding.UTF8.GetBytes("Trailing ... Text");
    this.HttpContext.Response.OnCompleted(async () => { await Response.Body.WriteAsync(trailer, 0, trailer.Length); });

    return View();
}
```

Moving [lines96-101](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/FrameOfT.cs#L96-L101) to come after `_responseBody.StopAcceptingWrites();` will fix the issue.
