### ISSUE TITLE
Add header limit parameters

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#475]
Failure state: `431 Request Header Fields Too Large` *(ngnix returns `400 Bad Request`)*

*"The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large."* [RFC 6585](https://tools.ietf.org/html/rfc6585)

**http.sys** [default](https://support.microsoft.com/en-us/kb/820129) `MaxRequestBytes` 16384
**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) `large_client_header_buffers` 4 * 8k = 32768
**apache.tomcat** [default](http://tomcat.apache.org/tomcat-9.0-doc/config/http.html) `maxHttpHeaderSize` 8192 

Will currently be enforced by reverse proxy config (e.g. IIS/nginx) when deployed in recommended configuration - but not in pure Kestrel deployment.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/KestrelHttpServer/issues/479#issuecomment-164325646

**Comment by benaadams** [comment]
Question on whether not having a max url/start length (beyond total header size) would have any upstream issues?

Guessing it wouldn't have a great impact beyond anything else (like lots of headers)

**Comment by benaadams** [comment]
Probably simpler code wise if there was only one param.

**Comment by Tratcher** [comment]
@blowdart ?

**Comment by blowdart** [comment]
Work for me. We used to have this with IIS and UrlScan

**Comment by muratg** [comment]
@blowdart Is this required for RC2/RTM?   Or can we punt it to post RTM?

**Comment by blowdart** [comment]
Yes

**Comment by DamianEdwards** [comment]
post-RC2

**Comment by cesarbs** [comment]
@muratg Moving to 1.0.0 and assigning to myself.

**Comment by cesarbs** [comment]
So do we want just a single parameter to limit request line + header length? No checking request line length individually and individual header lengths?

Ping @Tratcher @halter73 @blowdart @davidfowl

**Comment by blowdart** [comment]
No, we want all the things.

**Comment by cesarbs** [comment]
So, rounding up the specific things we want:

* Request line length
* Request target length (I know @Tratcher would like this to be part of the previous one)
* Request query length? I'd rather have it as part of target length.
* Max single header length
* Max total headers length
* Max header count

What do you guys think?

**Comment by Tratcher** [comment]
There's a lot of overlap and a lot of knobs here. I think we only need:
- Request line length
- Max total headers length
- Max header count

**Comment by muratg** [comment]
@cesarbs Before starting to work on it, can we have a table of the knobs, and default values in a table to review?

cc @davidfowl

**Comment by cesarbs** [comment]
I like @Tratcher's list, keeps things simple. Plus we risk regressing perfs if we're doing too many checks all over the request line/headers processing.

Here's a proposed list of limits, default and response status codes when limits are exceeded:

Limit | Default | Status code
-------|-----------|---------------
Request line | 16K | 414 ("Request **URI** Too Long", but realistically that's 99% of legit cases where the request line would be rejected based on length limit)
Headers length | Default 16K | 431
Header count | Default 64 | 431

**Comment by halter73** [comment]
Is the 16K "Headers length" limit per header meaning there would be a total limit of 1MB for all headers? Would we indicate to the client which type of header limit it ran into?

**Comment by cesarbs** [comment]
@halter73 No, not per header. It would be a length limit on all headers collectively.

**Comment by mikeharder** [comment]
Would be nice to add table columns showing the behavior of other servers, particularly IIS.

**Comment by benaadams** [comment]
> Would be nice to add table columns showing the behavior of other servers, particularly IIS.

@cesarbs numbers should be in all the closed linked bugs at top
