### ISSUE TITLE
Add MaxPathLength parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#476]
Failure state: current `414 URI Too Long` old `414 Request-URI Too Large`

*"The URI provided was too long for the server to process. Often the result of too much data being encoded as a query-string of a GET request, in which case it should be converted to a POST request."* [RFC 7231](https://tools.ietf.org/html/rfc7231)

**.NET 4 - 4.6** [default](https://msdn.microsoft.com/en-us/library/system.web.configuration.httpruntimesection.maxurllength(v=vs.110).aspx) `HttpRuntimeSection.MaxUrlLength` 260 *(returns `400 Bad Request`)*
**IIS** [default](https://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits) `maxUrl` 4096 *(returns `404.14 URL Too Long`)*
**http.sys** [default](https://support.microsoft.com/en-us/kb/820129) `MaxFieldLength` 16384
**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) `large_client_header_buffers` 8192 (for path **+** query - returns `414 Request-URI Too Large`)
**apache.httpd** [default](http://httpd.apache.org/docs/2.4/mod/core.html#LimitRequestLine) `LimitRequestLine` 8190 (for path **+** query)

Browser source max url length ~2000 bytes http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Will currently be enforced by reverse proxy config (e.g. IIS/nginx) when deployed in recommended configuration  - but not in pure Kestrel deployment.

**Comment by benaadams** [comment]
As per https://github.com/aspnet/KestrelHttpServer/issues/479#issuecomment-164325646 merging to #475 and just having that instead.

**Comment by jocooler** [comment]
So what is the effective URL length if there aren't any special headers set (+/- 100 is fine)?

**Comment by cesarbs** [comment]
@jocooler Not entirely sure what you mean. Kestrel has a request line limit (`KestrelServerOptions.Limits.MaxRequestLineSize`), but target/URL length is not accounted for separately (since method and version normally add little to the request line size compared to the target).
