### ISSUE TITLE
Add MaxUploadBytes parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#478]
Fail fast on `Content-Length` header value, count for body in chunked when limit passed.

Failure state: current `413 Payload Too Large` old `413 Request Entity Too Large`

_"The request is larger than the server is willing or able to process."_ [RFC7231](https://tools.ietf.org/html/rfc7231#section-6.5.11)

**.NET 4 - 4.6** [default](https://msdn.microsoft.com/en-us/library/system.web.configuration.httpruntimesection.maxrequestlength%28v=vs.100%29.aspx) `HttpRuntimeSection.MaxRequestLength` 4MB
**IIS** [default](https://www.iis.net/configreference/system.webserver/asp/limits) `maxRequestEntityAllowed` 200kB
or filtered [default](https://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits) 28.6MB _(returns `404.13 Content Length Too Large`)_
**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) `client_max_body_size` 1MB
**apache.tomcat** [default](http://tomcat.apache.org/tomcat-9.0-doc/config/http.html) `maxPostSize` 2MB
**apache.httpd** [default](http://httpd.apache.org/docs/2.4/mod/core.html#LimitRequestBody) `LimitRequestBody` unlimited

Will currently be enforced by reverse proxy config (e.g. IIS/nginx) when deployed in recommended configuration - but not in pure Kestrel deployment.

**Comment by halter73** [comment]
I think we should be careful when implementing this not to limit upgraded/websocket requests.

**Comment by muratg** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/475

**Comment by muratg** [comment]
cc @blowdart

**Comment by DamianEdwards** [comment]
post-RC2

**Comment by natemcmaster** [comment]
I've forgotten what we were planning to do here. Should this be reopened since we reverted the issue that originally closed it? 

Closed #1244
Reverted: https://github.com/aspnet/KestrelHttpServer/pull/1253

**Comment by benaadams** [comment]
Solved in Kestrel by the back pressure https://github.com/aspnet/KestrelHttpServer/pull/1244#issuecomment-265546975 maybe be an issue further up the pipeline if it can't handle the data; but isn't a server issue per se

**Comment by Tratcher** [comment]
It was reverted because it wasn't granular enough. The size limit needs vary too much per endpoint, similar to authorization.
