### ISSUE TITLE
Add MaxHeaderLength parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#479]
Failure state: `431 Request Header Fields Too Large` *(ngnix returns `400 Bad Request`)*

*"The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large."* [RFC 6585](https://tools.ietf.org/html/rfc6585)

**http.sys** [default](https://support.microsoft.com/en-us/kb/820129) `MaxFieldLength` 16384
**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) `large_client_header_buffers` 8192
**apache.httpd** [default](http://httpd.apache.org/docs/2.4/mod/core.html#LimitRequestFieldSize) `LimitRequestFieldSize` 8190

In wild max supported cookie size ~4093 bytes http://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key

Will currently be enforced by reverse proxy config (e.g. IIS/nginx) when deployed in recommended configuration - but not in pure Kestrel deployment.

**Comment by Tratcher** [comment]
Let's not play the guessing game of dictating the size of individual headers or how many you can have.  The cookie headers have been a constant source of annoyance for doing this. Let's just limit the combine size of all the headers (and request line?). Fewer knobs, better overall protection.

**Comment by benaadams** [comment]
Merge all in to #475? You are right, should achieve same effect; while being simpler.

**Comment by Tratcher** [comment]
Yes please. #474, #476, #477, and #479.

**Comment by benaadams** [comment]
As per https://github.com/aspnet/KestrelHttpServer/issues/479#issuecomment-164325646 merging to #475 and just having that instead.
