### ISSUE TITLE
Add API to IKestrelServerInformation to enable/disable DelayedAcks 

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#480]
Linux > 2.4.4 `TCP_QUICKACK` option
Windows > 7 / Server 2008 R2 `WSAIoctl` with `IOCTL` code `SIO_TCP_SET_ACK_FREQUENCY` and value of `1`

**Comment by DamianEdwards** [comment]
Doesn't enabling TCP no-delay (our default) also disable the delayed acks? Or is it strictly for the nagling?

**Comment by benaadams** [comment]
Best I can do right now is link to John Nagle expaining it[in 2015](https://news.ycombinator.com/item?id=10607422) and [2006](http://developers.slashdot.org/comments.pl?cid=14515105&sid=174457)

**Comment by benaadams** [comment]
Also `SIO_TCP_SET_ACK_FREQUENCY` isn't currently documented in MSDN; but hopefully it will be shortly

**Comment by benaadams** [comment]
@DamianEdwards sorry, not sure if I made any sense. 

Is so you can keep the nagling on, but switch delayed acks off - what I linked to is why you might want to do that instead of just switching nagling off.

Obviously having them both on is terribad; and since you never used to be able to just switch delayed acks off, then switching off nagling was the best option.

I'm not certain what the impact will be (e.g. you might need the client also to have delayed acks off); but is something I'd like to have the option of using.

**Comment by DamianEdwards** [comment]
I see. Best case would be for this to be a switch in libuv so we can set it through there. We don't really want to be P/Invoking to platform specific APIs of we can help it.

**Comment by benaadams** [comment]
Oh, yeah - good point!
