### ISSUE TITLE
Add HeaderCompleteTimeout parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#483]
Time in which from the header preamble starts it must be completed. If exceeded the client is determined to be disconnected and the request aborted.

Failure state: `408 Request Timeout`

*"The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time."*

**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_timeout) `client_header_timeout` 60s

Implementation-wise the timer can use the same timer as [Keep-alive](https://github.com/aspnet/KestrelHttpServer/issues/464); as a multi stage/state timer.

When deployed in recommended configuration with a reverse proxy (e.g. IIS/nginx) this would be handled by the proxy - however, this wouldn't apply in a pure Kestrel deployment.

**Comment by benaadams** [comment]
@halter73 @DamianEdwards this still RC2? Will finish in next couple days if so.

**Comment by DamianEdwards** [comment]
We'll be in beginning of our ASK mode by then, which is very high bar. Late features like this don't meet the bar at this stage I'm afraid.

**Comment by benaadams** [comment]
Is ok, is just marked RC2 still rather than backlog

**Comment by benaadams** [comment]
Is ok - is handled by reverse poxies in suggested deployment, is just marked RC2 still rather than backlog

**Comment by benaadams** [comment]
Also its not a very simple change, so I wouldn't put it in RC2 at this time :)

**Comment by muratg** [comment]
This will be covered
