### ISSUE TITLE
Add ExecutionTimeout parameter

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#484]
Timeout between two successive body reads which if exceeded the client is determined to be disconnected and the request aborted.

Failure state: `408 Request Timeout`

**ngnix** [default](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout) `client_body_timeout` 60s

Implementation-wise the timer can use the same timer as [Keep-alive](https://github.com/aspnet/KestrelHttpServer/issues/464); as a multi stage/state timer.

When deployed in recommended configuration with a reverse proxy (e.g. IIS/nginx) this would be handled by the proxy - however, this wouldn't apply in a pure Kestrel deployment.

**Comment by Tratcher** [comment]
Make sure this doesn't break websockets.

**Comment by benaadams** [comment]
@Tratcher I don't think so; but https isn't an upgrade request is it?

**Comment by Tratcher** [comment]
>https isn't an upgrade request is it?

Huh?

**Comment by benaadams** [comment]
> Huh?

My plan is to switch off the timers on opaque stream upgrade and assume they were handling that interaction (would also need to be same for MaxUploadBytes) - just making sure there is no corner cases I hadn't thought of (https in this case)

**Comment by Tratcher** [comment]
Ah, sounds good.

https shouldn't be any different from http in this scenario.

**Comment by benaadams** [comment]
Would be easier to have this as a maxRequestExecutionTimeout, that includes body reads, that work?

/cc @blowdart

**Comment by benaadams** [comment]
Hmmm... may cause issue with large file uploads :-/

**Comment by blowdart** [comment]
Hurrah, timeouts :D

**Comment by DamianEdwards** [comment]
post RC-2
