### ISSUE TITLE
FireOnStarting/Completed await doesn't have ConfigureAwait(false)

### ISSUE THREAD

**Issue by tenor** [aspnet/KestrelHttpServer#490]
[Frame#356](https://github.com/aspnet/KestrelHttpServer/blob/83cff1671582d6fbeb0c3d9a7c206154f357c5b7/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L356) and [Frame#380](https://github.com/aspnet/KestrelHttpServer/blob/83cff1671582d6fbeb0c3d9a7c206154f357c5b7/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L380).
These awaits will be calling user code and should have `ConfigureAwait(false);`

**Comment by tenor** [comment]
I did a search for a custom `SynchronizationContext` in dnx, hosting and kestrel. I couldn't find any, so adding `ConfigureAwait(false)` seems a bit pointless here.
However, [FrameOfT#Application.ProcessRequestAsync()](https://github.com/aspnet/KestrelHttpServer/blob/83cff1671582d6fbeb0c3d9a7c206154f357c5b7/src/Microsoft.AspNet.Server.Kestrel/Http/FrameOfT.cs#L79) does call  `ConfigureAwait(false)`

**Comment by halter73** [comment]
We should probably get rid of all of our uses `ConfigureAwait(false)` since there is no real benefit with a SyncContext. In the vast majority of awaits we do not use `ConfigureAwait` (I think there are a total of 3 usage currently).

**Comment by davidfowl** [comment]
Until you start hosting asp.net in a windows store app :)

**Comment by muratg** [comment]
We would potentially accept a PR, but we're not going to spend time on this for RC2/RTM.
