### ISSUE TITLE
Use queue pool for _tasksPending, _tasksCompleted,_writeContextPool in socketOutput

### ISSUE THREAD

**Issue by Anderman** [aspnet/KestrelHttpServer#495]
Maybe it is possible to use a queue pool in `SocketOuput` to reduce memory allocation.
When profiling I found that memory was allocated for each request/response.

* _tasksPending 300 bytes
* _tasksCompleted 300 bytes
* _writeContextPool 172 bytes

**Comment by muratg** [comment]
__tasksCompleted was removed.  We don't think it's important to work on the other two unless the impact is huge.
