### ISSUE TITLE
Improve data flows

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#5]
Several places are doing array copies and growing-reallocations which should be an array of arraysegment of pooled byte[]... This relates to primary input/output data flows

**Comment by Eilon** [comment]
This is a super old bug but it was in the alpha4 milestone, so moving to RC1 to reevaluate.

**Comment by Eilon** [comment]
@lodejard was this done or not? Just wondering what label to tag it as.
