### ISSUE TITLE
Update libuv to 1.1.0 and automate build

### ISSUE THREAD

**Issue by akoeplinger** [aspnet/KestrelHttpServer#50]
Instead of installing the rc2 version of libuv, we should update to the latest 1.1.0 release:
https://github.com/libuv/libuv/releases/tag/v1.1.0

See https://github.com/aspnet/aspnet-docker/pull/22 for a related PR

**Comment by Eilon** [comment]
@lodejard

**Comment by DamianEdwards** [comment]
Let's figure out how to continually incorporate latest libuv bits from here on out.

**Comment by muratg** [comment]
@moozzyk

**Comment by moozzyk** [comment]
#147 - probably we could link statically

**Comment by moozzyk** [comment]
We are know at 1.7.3 for Windows and Darwin.
