### ISSUE TITLE
No need for IsLittleEndian check

### ISSUE THREAD

**Issue by Anderman** [aspnet/KestrelHttpServer#504]
@cesarbs I don't think this check is needed. The string will give an another value in big endian than in little endian. But that's the only difference.

Because the known string are converter in the same way as the string you want to check

in `GetAsciiStringAsLong`
            fixed (byte* ptr = bytes)
            {
                return *(long*)ptr;
            }
in `peeklong`
 fixed (byte* ptr = _block.Array)
                {
                    return *(long*)(ptr + _index);
                }

**Comment by cesarbs** [comment]
Closed by 36e9e8759a579a4d3e50c70490859f9ba99a98ec.
