### ISSUE TITLE
Iri request with only URI octet encoding in queryString is not suppored

### ISSUE THREAD

**Issue by Anderman** [aspnet/KestrelHttpServer#508]
@benaadams  In `TakeStartLine` the requestUrl is scaned on % (URI octet encoding) but if the
requestUrl contains a querystring no scanning is done on %

See [frame.cs line 728-748](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L728-L748)

**Comment by benaadams** [comment]
@Anderman Is that a problem? It scans for what the first of the three characters is. 
If its % then the path needs to be decoded
If its ? then everything past that point is querystring and is handled by querystring decoding
If its space then is neither has query string nor needs decoding.

**Comment by Anderman** [comment]
Thx @benaadams I did not know that the querystring decoder will also take care of this. But you probably right. 
I made some changes to the `TakeStartLine` to double the performance of that function. And looking for  more improvements I thought something was missing.

**Comment by benaadams** [comment]
I think it only does what is needed for routing to work and querystring parsing is defered until something asks for it? @Tratcher should know more

**Comment by Tratcher** [comment]
Yes this is intended. The server needs to process the path to enable routing, but the query isn't decoded until you call HttpContext.Request.Query.

**Comment by Anderman** [comment]
@Tratcher I don't see where it is decoded. If I run the sample application in kestrel I got this in the console window

```
info: Microsoft.AspNet.Hosting.Internal.WebApplication[1]
      Request starting HTTP/1.1 GET http://localhost:5000/21312/dsaf?M%C3%A4rz
GET /21312/dsaf?M%C3%A4rz
Method: GET
PathBase:
Path: /21312/dsaf
QueryString: ?M%C3%A4rz
Peer: 127.0.0.1 40023
Sock: 127.0.0.1 5000
IsLocal: True
dbug: LoggingConnectionFilter[0]
      Write[119] 48 54 54 50 2F 31 2E 31 20 32 30 30 20 4F 4B 0D 0A 44 61 74 65 3A 20 4D 6F 6E 2C 20 32 31 20 44 65 63 20 32 30 31 35 20 32 31 3A 34 37 3A 35 31 20 47 4D 54 0D 0A 43 6F 6E 74 65 6E 74
2D 4C 65 6E 67 74 68 3A 20 31 31 0D 0A 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 74 65 78 74 2F 70 6C 61 69 6E 0D 0A 53 65 72 76 65 72 3A 20 4B 65 73 74 72 65 6C 0D 0A 0D 0A
      HTTP/1.1 200 OK
      Date: Mon, 21 Dec 2015 21:47:51 GMT
      Content-Length: 11
      Content-Type: text/plain
      Server: Kestrel

```

**Comment by Tratcher** [comment]
Here? https://github.com/aspnet/KestrelHttpServer/blob/dev/samples/SampleApp/Startup.cs#L53
I said Request.Query, not Request.QueryString.

**Comment by Anderman** [comment]
Aha,ok looks meaningful to me.
