### ISSUE TITLE
System.IO.InvalidDataException in Kestrel.Http.MessageBody when posting large file

### ISSUE THREAD

**Issue by davenewza** [aspnet/KestrelHttpServer#520]
When trying to post a large file  to an API action using form-data, the following exception is thrown. I have found this to be around 1.5mb but appears to be inconsistent. 

This only seems to happen when hosting in an Azure Web App using the IISPlatformHandler. 

I am using ASP.NET 5 RC1 (1.0.0-rc1-final) packages.

Action:

        [HttpPost()]
        public IActionResult PostText()
        {
            if (Request.Body.CanSeek)
            {
                Request.Body.Position = 0;
            }

            var body = new StreamReader(Request.Body).ReadToEnd();

            ...
        }

 > System.IO.InvalidDataException: Unexpected end of request content at Microsoft.AspNet.Server.Kestrel.Http.MessageBody.ForContentLength.d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.WebUtilities.FileBufferingReadStream.d__27.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.WebUtilities.BufferedReadStream.d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.WebUtilities.MultipartReaderStream.d__36.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.WebUtilities.StreamHelperExtensions.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.AspNet.Http.Features.Internal.FormFeature.d__12.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Mvc.ModelBinding.FormValueProviderFactory.d__1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Mvc.ModelBinding.CompositeValueProvider.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.d__49.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.d__44.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.d__10.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Routing.RouteCollection.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Builder.RouterMiddleware.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.ApplicationInsights.AspNet.RequestTrackingMiddleware.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.d__8.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.d__3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.AspNet.Server.Kestrel.Http.Frame.d__79.MoveNext()

**Comment by davenewza** [comment]
The exception is thrown from [here](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/MessageBody.cs#L174).

**Comment by benaadams** [comment]
Have you upped the IIS post limits in web.config?

**Comment by BrennanConroy** [comment]
Could you give a small repro application? I'm not getting this behavior in the app I made

**Comment by davenewza** [comment]
@benaadams: Yes, I have. The web.config looks as followings:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="ASPNET_DETAILED_ERRORS" value="true" />
  </appSettings>
  <system.web>
    <customErrors mode="Off" />
    <httpRuntime maxRequestLength="1048576" />
  </system.web>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%DNX_PATH%" arguments="%DNX_ARGS%" forwardWindowsAuthToken="false" startupTimeLimit="3600" />
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="1073741824" />
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```

**Comment by muratg** [comment]
Apparently per #534 this also repro's when posting large request body. 

A repro app would be useful

**Comment by DamianEdwards** [comment]
We'll need some more information here to investigate for RC2 as we enter lock down.

**Comment by turtlebat** [comment]
I ran into this bug earlier today on another project. Here is a sample project that replicates the issue:

https://github.com/turtlebat/Kestrel520

Let me know if there is anything else I can do to help diagnose the bug.

**Comment by muratg** [comment]
@halter73 Could you investigate?

**Comment by aluitink** [comment]
Also seeing this, I was able to follow it back to libuv method uv_read_start, but at that point I am a bit lost.
..

   at Microsoft.AspNet.Server.Kestrel.Http.MessageBody.ForContentLength.<ReadAsyncImplementation>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by benaadams** [comment]
How are large form requests handled? https://github.com/aspnet/HttpAbstractions/issues/84 suggests they may be temp disk stored passed a certain point so it could be file permissions? /cc @Tratcher

**Comment by benaadams** [comment]
Though the stack trace looks like a disconnected connection

**Comment by JosephGarrone** [comment]
Any news on a work around for this? I am currently experiencing major issues with this. I have narrowed it down to files just above 28k causing the issue (On 1.0 RC1 Update 1). My IIS limits are set to the max values. If there are no known workarounds it looks like chunking might be the best option?

**Comment by chemitaxis** [comment]
Me too... Uploading file, I have this error...

**Comment by JosephGarrone** [comment]
I ended up just using FlowJS (via ngFlow). Worked fine if I set it to 1
simultaneous upload with forcedChunkSize and chunkSize set to 20000.

**Comment by cesarbs** [comment]
Do you guys see this issue on your own machines or is it only when running on Azure?

**Comment by turtlebat** [comment]
Only when running on Azure for me. I haven't tried installing on a IIS though, only IIS Express which seems to work fine.

**Comment by JosephGarrone** [comment]
Happens to me on IISExpress, haven't tested on IIS.

**Comment by cesarbs** [comment]
@JosephGarrone Are you on RC1? Can you provide more details about your app, settings, etc.?

**Comment by JosephGarrone** [comment]
@cesarbs I currently don't have my actual code repoing the issue, luckily I did make another project to test if the issue occurred on a clean project.

https://github.com/JosephGarrone/ASPNetUploadError

Repo's the problem for me. If I upload a 5GB file I get a 0ms request finished.

If I make a couple files in the 25->35mb range you can get a variance of responses (Some are errors as detailed above, others are the 0ms request finished)

**Comment by cesarbs** [comment]
@JosephGarrone I can't repro with your repo. I've also tried reproing on IIS, then tried deploying to Azure, no luck.

I'm trying to repro under these conditions:

* rc1-final
* Windows 10
* Tried both x86 and x64
* Tried uploading files ranging from 1.5MB to 1.8GB.

I'll need more info on your environments.

**Comment by JosephGarrone** [comment]
@cesarbs 

For the following file:

`fsutil file createnew 161mb 161740528`

I get (Highlighted on the `await file.SaveAsAsync(...)` in `HomeController.cs`:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The inner stream position has changed unexpectedly.
  Source=Microsoft.AspNet.Http
  StackTrace:
       at Microsoft.AspNet.Http.Internal.ReferenceReadStream.VerifyPosition()
       at Microsoft.AspNet.Http.Internal.ReferenceReadStream.<ReadAsync>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Microsoft.AspNet.Http.FormFileExtensions.<SaveAsAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at UploadTest.Controllers.HomeController.<Index>d__3.MoveNext() in C:\Users\joseph.garrone\Documents\Visual Studio 2015\Projects\UploadTest\src\UploadTest\Controllers\HomeController.cs:line 35
  InnerException: 
```

`dnx --version` gives:
```
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x86
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x86
```

`dnvm version` gives:
```
1.0.0-rc2-15545
```

**Comment by JosephGarrone** [comment]
Just tried again with:

`fsutil file createnew 1gb 1024000000` and received the same error.

**Comment by alexhelms** [comment]
I too am also getting this exception when uploading an image via a form. Small files (< 1mb) seem to get through. I set a breakpoint on the first line in the controller's method and it never gets there when the error occurs. I have the exact same stack trace, I'm not posting it for brevity but I will if you'd like.

**Comment by cesarbs** [comment]
@alexhelms Also on RC1?

**Comment by benaadams** [comment]
@cesarbs try in a far away datacenter to introduce some latency - I've come across some code in the upload chunking that might not work properly in my refactored code in https://github.com/aspnet/KestrelHttpServer/pull/619#issuecomment-183884481; though it might also be my refactor that is awry rather than the current code :)

**Comment by jiberan** [comment]
@cesarbs I have also seeing this issue. On Azure Web apps only, IIS Express is fine.

**Comment by cesarbs** [comment]
All: I'm able to repro now. Investigating.

**Comment by alexhelms** [comment]
Excellent!

@cesarbs Yes, RC1. Sorry, forgot to mention that. Also, I only get the problem in Azure, not IISExpress when running locally out of VS.

**Comment by JosephGarrone** [comment]
@cesarbs cheers!

**Comment by DavidObando** [comment]
@SajayAntony yes, that's covered, but in a local run you won't likely get data starvation from network latency (which may cause this). A more appropriate test would simulate rough network conditions. Let's take it offline.

**Comment by DavidObando** [comment]
Hey @cesarbs, I'm playing with a scenario around uploading large files. I found that we can't upload a multipart with a total message size larger than 4GB, basically because `int.Parse(contentLength)` doesn't like such `long` numbers while reading the [message body](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/MessageBody.cs#L123).

Is this covered by your work as part of this issue? Or should I start a new conversation around it? I'm not sure if there's any spec prohibiting this sort of scenario.

**Comment by muratg** [comment]
Thanks @DavidObando! I can see the issue with 2GB, though like you I'm not sure if that's supposed to be supported by default.  @lodejard any thoughts?

**Comment by lodejard** [comment]
Interesting - it's a little hard to tell if there are actually two or three different being reported. 

The https://github.com/aspnet/KestrelHttpServer/blob/bc56d11d8ca9ba3e3b6a3c84900b0f8027ff2e96/src/Microsoft.AspNetCore.Server.Kestrel/Http/MessageBody.cs#L123 can be changed to long - a few of the fields will also need to change to long, and the expressions will need to be double-checked.

That said - there are plenty of layers that could re-introduce limits. Azure ARR, the http platform handler, the multi-part form handler, etc. But even if they do have limits there's no reason for kestrel itself to have an upload limit.

**Comment by cesarbs** [comment]
I'll work on fixing that as part of #642.

**Comment by cesarbs** [comment]
Actually I'll start a separate PR for it.

**Comment by chemitaxis** [comment]
Hi @cesarbs, Im having this issue uploading images from browser to server... Images for example of 2Mb. Im using RC1, Azure Web App with no results... It fails sometimes, not always. In my local using IIS express I cant reply the bug. Thanks.

**Comment by mikeharder** [comment]
@chemitaxis: This issue is closed.  Please create a new issue for the latest problem you are having.

**Comment by jiberan** [comment]
@chemitaxis this issue was fixed after RC1. Check this 5435a45397bbbef34ea253dc156655a816dfbf39 commit as part of #642
