### ISSUE TITLE
question about pathing and nginx

### ISSUE THREAD

**Issue by nguyenm100** [aspnet/KestrelHttpServer#535]
I have multiple aspnet apps running on different ports on kestrel on the same machine and want to unify them behind nginx.

So I'll have 

location /app1/ {
  proxy_pass http://localhost:xxxx/;
}

location /app2/ {
  proxy_pass http://localhost:yyyy/;
}

etc.

My question is:

How do I path back to the "home" page from each app (so from app1, home = http://host/app1/).  Also related is how do I code things like BeginForm so the calls are subdirectory qualified?

**Comment by benaadams** [comment]
In html it ould just be the relative path `/` ?

**Comment by cesarbs** [comment]
I think they mean that in app1 they want `/` to go back to `/app1`, same for `/` in `/app2`. I'm looking into it. Not sure it's something that can/should be handled by Kestrel though.

**Comment by benaadams** [comment]
Oh like `~/` going to right place?

**Comment by nguyenm100** [comment]
Hey, thanks for investigating.  Wasn't sure whether to submit here or elsewhere.  Let me know if I should try another group.  

relative pathing seems to work for static files (js/css/etc) but '/' on an anchor tag will take me back to http://localhost.

Also, beginform is putting me at http://localhost/controller/action as opposed to http://localhost/app/controller/action.

**Comment by pranavkm** [comment]
Try using the  `Map` extension on `IApplicationBuilder`. Your Startup would look like:

```C#
public void Configure(IApplicationBuilder app)
{  
   app.Map("/app1", subApp => 
   {
      subApp.UseStaticFiles();
      subApp.UseMvc();
   });
}
```

**Comment by nguyenm100** [comment]
@pranavkm - this seems to work for me on windows but on linux, i get a blank page (whether I go through nginx or directly to the port).  are you able to get this to work on linux?

**Comment by pranavkm** [comment]
@Tratcher, any idea what could be wrong here?

**Comment by Tratcher** [comment]
Try:
```
public void Configure(IApplicationBuilder app)
{  
   app.Run(async context => 
   {
       async context.Response.WriteAsync($"Base: {context.Request.PathBase}, Path: {context.Request.Path}");
   });
}
```

**Comment by cesarbs** [comment]
@nguyenm100 Change nginx.conf as follows:

    location /app1/ {
        proxy_pass http://localhost:xxxx/app1;
    }

    location /app2/ {
        proxy_pass http://localhost:yyyy/app2;
    }

I also had to remove the `server_name  localhost;` line I had on my nginx.conf file.

**Comment by cesarbs** [comment]
@nguyenm100 Did that work for you?

**Comment by nguyenm100** [comment]
hi, sorry been busy with work.  plan to fiddle with .net again this weekend.  pls give me til monday to confirm. tx

**Comment by nguyenm100** [comment]
looks like removing server_name localhost; did the trick.  Thanks!
