### ISSUE TITLE
NativeCommandError with libuv.dll when executing Kestrel on Nano Server

### ISSUE THREAD

**Issue by jchable** [aspnet/KestrelHttpServer#539]
When running web.cmd of a published ASP.NET 5 project on Nano Server, we have an error message telling us that the libuv.dll could not be found. However the DLL looks like it's at the right place.

Sounds like it could be a nano Server issue since the web.cmd it works on my development machine.

![issue_nanoserver](https://cloud.githubusercontent.com/assets/10860719/12012215/77da90e4-ad3f-11e5-849f-2c671d0b4342.jpg)

**Comment by muratg** [comment]
@moozzyk

**Comment by benaadams** [comment]
@GuardRex has had some success with this https://github.com/aspnet/Docs/issues/194#issuecomment-168015119

**Comment by GuardRex** [comment]
@jchable Did you install the Reverse Forwarders package? https://github.com/aspnet/Hosting/issues/539

**Comment by jchable** [comment]
Looks like my VHD was not provisioned correctly with the Forwarders package. I fully rebuilt a Nano Server VHD from scratch and now works like a charm !

**Comment by moozzyk** [comment]
https://github.com/aspnet/Hosting/issues/539#issuecomment-167709309
