### ISSUE TITLE
Skip Null check and zero length checks of Pointers

### ISSUE THREAD

**Issue by Anderman** [aspnet/KestrelHttpServer#541]
pointers to byte arrays are use as 
`fixed(byte* ptr arr)` 
the code generated will check if this is an null or zero length array

To skip these tests the statement can be written as
`fixed(byte* ptr &arr[0])`

see generated code

`fixed(byte* ptr arr)` 
```
000007FF622857AB  mov         rax,rcx  
000007FF622857AE  test        rax,rax  
000007FF622857B1  je          000007FF622857BA  
000007FF622857B3  mov         ecx,dword ptr [rax+8]  
000007FF622857B6  test        ecx,ecx  
000007FF622857B8  jne         000007FF622857C3  
000007FF622857BA  xor         ecx,ecx  
000007FF622857BC  mov         qword ptr [rsp+20h],rcx  
000007FF622857C1  jmp         000007FF622857D1  
000007FF622857C3  cmp         ecx,0  
000007FF622857C6  jbe         000007FF622857FE  
000007FF622857C8  add         rax,10h  
000007FF622857CC  mov         qword ptr [rsp+20h],rax 
```

`fixed(byte* ptr &arr[0])`
```
000007FF6228582B  cmp         dword ptr [rcx+8],0  
000007FF6228582F  jbe         000007FF62285867  
000007FF62285831  add         rcx,10h  
000007FF62285835  mov         qword ptr [rsp+20h],rcx 
```

**Comment by benaadams** [comment]
Interesting :)

**Comment by Anderman** [comment]
This one is also nice to know [Optimize generated code for Fixed statement](https://github.com/dotnet/coreclr/issues/2480). Looks like a clr or roslyn issue

**Comment by clrjunkie** [comment]
+1

**Comment by halter73** [comment]
@Anderman did #542 address all the places where we should use the `fixed(byte* ptr &arr[0])` pattern?

**Comment by Anderman** [comment]
Yes, all that I could found. I skipped 1 or 2 because they didn't have much impact.

**Comment by Anderman** [comment]
@halter73  I think @benaadams  did already change some in his PR

**Comment by halter73** [comment]
I also noticed @benaadams used the same pattern in at least one of his PRs.

Thanks! Just wanted to double check before closing.

**Comment by benaadams** [comment]
@Anderman is making me up my game :)

**Comment by Anderman** [comment]
Ha, Thx there still is many things that can be improved

**Comment by halter73** [comment]
@Anderman No doubt there are many more things that can be improved, but we've decided we are going to lock down stop accepting new perf related prior to our 1.0 release. This is meant to give us more time to focus on other things like stability and security.

**Comment by clrjunkie** [comment]
@halter73 
:+1:
