### ISSUE TITLE
Use Buffer.MemoryCopy 

### ISSUE THREAD

**Issue by Anderman** [aspnet/KestrelHttpServer#544]
`Buffer.BlockCopy` has a large overhead for small size copy. This is because it has to find out a lot of things before it start copy see [blockcopy](https://github.com/dotnet/coreclr/blob/master/src/vm/comutilnative.cpp#L1410-L1456).

MemoryCopy is almost a direct call to memmove see [here](https://github.com/dotnet/coreclr/blob/bc146608854d1db9cdbcc0b08029a87754e12b49/src/mscorlib/src/System/Buffer.cs#L522-L533)

**Comment by benaadams** [comment]
Situation may have changed https://github.com/dotnet/coreclr/pull/3118

**Comment by cesarbs** [comment]
Indeed. I don't think it's worth it making the switch to `MemoryCopy`. @halter73 what do you think?

**Comment by halter73** [comment]
Yeah. This clearly seems fixed. If there is any evidence we should still switch, I'm open to reopening.
