### ISSUE TITLE
Kestrel as TcpListener

### ISSUE THREAD

**Issue by ru-sh** [aspnet/KestrelHttpServer#550]
Hello!
It is possible to use kestrel server as a simple TcpListener? 
If possible, any example, please.

**Comment by davidfowl** [comment]
You'd be better off using something like libuvsharp or copying the appropriate classes from kestrel

**Comment by cesarbs** [comment]
Why would you like to do that?

**Comment by ru-sh** [comment]
I need to start TcpListener in CoreClr runtime. As far as I know, cross-platform implementation of TcpListener today exists only in Kestrel.

**Comment by davidfowl** [comment]
Still, Kestrel isn't a TcpListener, it's a webserver. I'd file an issue like this on CoreFX, or just use the socket APIs on .NET Core. Those work cross platform as well.

**Comment by cesarbs** [comment]
As @davidfowl suggested, you could copy the relevant classes from Kestrel, or use sockets. We don't have any plans to separate out the listener part of Kestrel, so I'm closing this issue.
