### ISSUE TITLE
Calling https but getting http schema

### ISSUE THREAD

**Issue by imperugo** [aspnet/KestrelHttpServer#551]
Hi,
I've a strange issue running Kestrel with HTTPS.
It seems the schema is always **http** also if I call the endpoint using **https**.

![image](https://cloud.githubusercontent.com/assets/758620/12080529/b6a5854a-b25d-11e5-9fa0-86df5c4abb85.png)

Any hint?

For reference: https://github.com/IdentityServer/IdentityServer3/issues/2357

**Comment by khellang** [comment]
Are you hitting Kestrel directly or are you running behind a reverse proxy?? Maybe using IISPlatformHandler?

**Comment by imperugo** [comment]
Running directly from VS2015 Update1.

```app.UseIISPlatformHandler();``` is comment out

**Comment by khellang** [comment]
> Running directly from VS2015 Update1.

Does that mean using IIS Express?

**Comment by imperugo** [comment]
Nope, running ```web``` command from play button in VS.
Same problem using command line (```dnx web```)

**Comment by Tratcher** [comment]
Fixed in RC2: https://github.com/aspnet/KestrelHttpServer/issues/365

**Comment by imperugo** [comment]
Thx, 
I'll use [this](https://github.com/aspnet/KestrelHttpServer/issues/454) workaround in the meanwhile
