### ISSUE TITLE
how to open the access log for KestrelHttpServer 

### ISSUE THREAD

**Issue by wtc114** [aspnet/KestrelHttpServer#552]
i have a  aspnet 5 mvc 6 app run in  docker,the docker images is pull from docker hub，use the
docker pull microsoft/aspnet。but I can't find anylog in the container belong to  KestrelHttpServer 。

**Comment by benaadams** [comment]
Did you add a logger?

**Comment by muratg** [comment]
@wtc114 And which logger are you using?  Does this app log when not run in Docker?

**Comment by muratg** [comment]
Please feel free to file another bug if you still have issues.
