### ISSUE TITLE
Kestrel requires a TTY to stay alive, but should be daemonizable

### ISSUE THREAD

**Issue by s3ththompson** [aspnet/KestrelHttpServer#56]
See the [blog post](http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx) about Dockerizing ASP.NET and this issue https://github.com/aspnet/aspnet-docker/issues/13 for context.

Kestrel should be able to be run as a daemon.

**Comment by Tragetaschen** [comment]
This looks like it could be solved by Hosting#129, and it's Hosting that's doing the keepalive

**Comment by sklose** [comment]
Is there a workaround for this issue? I am trying to deploy to AWS Elastic Beanstalk, but there is no way to tell AWS EB to add the -t option to the docker run command.

**Comment by davidfowl** [comment]
Follow up on the hosting bug
