### ISSUE TITLE
Enable custom header encoding

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#564]
Officially request and response headers are restricted to ASCII. Historically however ANSI and local code pages were supported. There are also some cases where UTF-8 was used in for Unicode host names prior to the punycode standard (IE and HttpWebReqeuest on intranets), see Host and Location.

Default header encoding/decoding to utf-8. Allow this encoding to be set at startup. For performance reasons the encoding/decoding process can assume simple ASCII until it encounters 8bit values.

Related: https://github.com/aspnet/KestrelHttpServer/pull/491 pre-encoded response headers.

RE: https://github.com/aspnet/WebListener/issues/123#issuecomment-158533753 [private]

**Comment by benaadams** [comment]
As there are two servers, could take the IE11+Edge route. If you want to support historical non-standard stuff use WebListener (e.g. intranets/because your site uses them which you should know)?

**Comment by Tratcher** [comment]
It's primarily an interop issue. You often do not control what the client sends you (or expects back), you just have to find a way to make it work. Standards are definitely the default but we need a well defined behavior for addressing non-standard input/output.

How does Kestrel behave at the moment? Does it throw or mangle the data?

**Comment by benaadams** [comment]
> How does Kestrel behave at the moment? Does it throw or mangle the data?

It stays uninterpreted ([tests](https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNet.Server.KestrelTests/AsciiDecoder.cs#L13-L35)) so 255 or 0 stays as 0 or 255 in the string. 
As per last section of [rfc7230#section-3.2.4](https://tools.ietf.org/html/rfc7230#section-3.2.4)

> Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

So you could use binary headers if you wanted and that would work (assuming you stayed away from `\r\n` in the data)

**Comment by benaadams** [comment]
Also since it only encodes 0-255 of char (both on input and output) and doesn't do any interpretation of it; you can embed pre-encoded stuff in it currently by putting it in the string that way - although it will use slightly more room.

**Comment by Tratcher** [comment]
String is a very bad representation of opaque data, incoming or outgoing. I've tried the embed-utf-8-in-a-string hack before with HttpClient and it almost works, but it confuses anyone else that tries to look at the data.

I don't think it's appropriate for WebListener to have different behavior on something as basic as header encoding.

**Comment by benaadams** [comment]
Isn't embedding utf-8 in a string its just maintaining it in its input and output binary representation without changes (other than widening the data type)?

**Comment by benaadams** [comment]
Am suggesting something like typed headers so you could go
```csharp
string value;
value = header[value].AsUft8();
value = header[value].AsUft16();
value = header[value].AsUft32();
value = header[value].AsEncoding(encoder);

byte[] buffer;
buffer = header[value].AsBinary()
```

**Comment by benaadams** [comment]
Hmm, ok so that would work for inbound headers but would clobber outbound

**Comment by benaadams** [comment]
So historically non-ascii should be MIME (RFC 2047) encoded?

e.g. UTF-8 should start: `=?UTF-8?`...

**Comment by Tratcher** [comment]
No, that was for smtp and sometimes multipart headers, not http.

**Comment by benaadams** [comment]
Ok, to be clear, the scenario being supported is an old client communicating with new server-side code (as aspnet5 isn't lift and shift, the servers aside); and depending on the values in the headers to be not ascii?

**Comment by benaadams** [comment]
Ah so is a Windows only AD thing http://stackoverflow.com/questions/16837513/how-do-i-know-when-to-do-a-utf8-or-punycode-dns-query
> On Windows, there any two possibilities: either the domain name is a normal internet one, in which case it should be mapped to ASCII with punycode and looked up with normal DNS. Or, the domain name is a weird Windows one (eg. Active Directory DNS server) and the lookup should in fact be UTF-8.

**Comment by davidfowl** [comment]
> Ok, to be clear, the scenario being supported is an old client communicating with new server-side code (as aspnet5 isn't lift and shift, the servers aside); and depending on the values in the headers to be not ascii?

We totally don't care about this because we're not even testing it. We're just looking for a consistent way to decode headers when we find an unexpected characters.

**Comment by benaadams** [comment]
Am just not sure why you even want to try to decode the headers? String is quite happy with the full range of bytes 0-255 sitting in chars. If someone wants/has to use non-standard header encoding they can always decode/encode from that; using the `string[i]` indexer.

However if you decode it to utf8 when you encounter a byte >= 128 its a one way transform if its not utf8 that will garble the data.

e.g. http://haacked.com/archive/2012/01/30/hazards-of-converting-binary-data-to-a-string.aspx/

**Comment by benaadams** [comment]
HPACK for HTTP/2 has dropped the idea of other encodings? http://tools.ietf.org/html/draft-ietf-httpbis-header-compression-07#appendix-C

**Comment by Tratcher** [comment]
@benaadams More like HTTP/2 failed to address the ongoing issue of how to encode non-ascii data in HTTP headers. Ignoring it doesn't make it go away.

**Comment by DamianEdwards** [comment]
Not important for RC2.

**Comment by davidfowl** [comment]
This issue has been filed several times. I’ll leave one of them open
