### ISSUE TITLE
Consider extending the Package System to support Repo feeds

### ISSUE THREAD

**Issue by clrjunkie** [aspnet/KestrelHttpServer#568]
I like the new Package system and I think it’s a major step forward for managing dependencies and distributing software in general. However, this system does not address a scenario which I think is quite useful – ability to drill down into open source packages and make changes during development.

Consider the following workflow in VS:

1. You work on an ASP.NET project and you encounter an odd behavior or an Api that’s not well documented.

2. You branch into an “investigation branch” and change your project.json in a way that directs VS to reference and compile all possible dependencies which can be identified directly from repos

3. VS now allows you to drill down into package source code and put break points so you can understand what’s going on. You can even make changes, test them and submit a Pull request – *all in the context of your project*.

Example:
```
"frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "repositories": [
		{ location: "c:/clrjunkie/corefx/src", readonly: false }
      ],
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
       }
    }
}
```
Ideally, the example above would be front-ended by a Gui that would include the branching step and Repos would need to follow some structural convention or include a “Master Package File” which specifies exported packages and their source code locations.

Notice that I intentionally omitted “Step 4 – merge” as the obvious argument would be that the package binary interface is a “wall” built to enforce package consistency and reduce support cost and I argue that this binary interface is indeed a wall for some but a pure hologram for others, because today, it’s equally possible to make changes directly in the repo, compile, replace the package dll, just without any record that ties the change to particular user project. Simply put, I think the challenge with “merge” is completely orthogonal to this proposal.

**Comment by clrjunkie** [comment]
For those notified via email: made a slight change to the example -> readonly: false

**Comment by Tratcher** [comment]
This issue was moved to aspnet/dnx#3304
