### ISSUE TITLE
StreamSocketOutput.WriteAsync is Sync (SSL)

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#569]
This is used for wrapped streams such as Ssl. There is currently an issue with it being async; so it is [currently implemented as sync](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Filter/StreamSocketOutput.cs#L50-L55).

```csharp
public Task WriteAsync(ArraySegment<byte> buffer, bool immediate, bool chunk, CancellationToken cancellationToken)
{
    // TODO: Use _outputStream.WriteAsync
    Write(buffer, immediate, chunk);
    return TaskUtilities.CompletedTask;
}
```

Tests do catch the issue current; e.g. switching to async causes the following failures:

`Microsoft.AspNet.Server.KestrelTests.HttpsConnectionFilterTests.CanReadAndWriteWithHttpsConnectionFilter [FAIL]`
`Microsoft.AspNet.Server.KestrelTests.HttpsConnectionFilterTests.HttpsSchemePassedToRequestFeature [FAIL]`
`Microsoft.AspNet.Server.KestrelTests.HttpsConnectionFilterTests.AllowCertificateContinuesWhenNoCertificate [FAIL]`

Blockers
- [x] https://github.com/dotnet/corefx/pull/5534
- [x] https://github.com/dotnet/coreclr/pull/2724
- [x] https://github.com/dotnet/corefx/pull/5541
- [x] dotnet/corefx#7800
- [x] dotnet/corefx#7819

**Comment by muratg** [comment]
@benaadams Does this happen only with connection filters?

**Comment by benaadams** [comment]
Yes, so https/Ssl

**Comment by benaadams** [comment]
Might have this one; looks like there is a bad interaction with Stream's default implementation of BeginRead/EndRead which calls through to the synchronous Read then it all goes wrong.

**Comment by benaadams** [comment]
I think it might be SslStream causing this

**Comment by benaadams** [comment]
Looks like it goes something like this: Async->Sync->Async->Wait()

**Comment by benaadams** [comment]
Added https://github.com/dotnet/corefx/issues/5488

**Comment by benaadams** [comment]
@muratg this may now be unblocked depending on outcome of https://github.com/dotnet/corefx/pull/7819#issuecomment-211140332

Have rebased the fix

**Comment by muratg** [comment]
Nice!  Putting it back in 1.0.0 and we can make a decision based on the corefx issue resolution.

**Comment by benaadams** [comment]
Resolved for coreclr, rasing issue for full framework (kept it as sync)

**Comment by benaadams** [comment]
Full framework issue https://github.com/aspnet/KestrelHttpServer/issues/768
