### ISSUE TITLE
kestrel doesn't allow me to get around firewall warning

### ISSUE THREAD

**Issue by jrieken** [aspnet/KestrelHttpServer#57]
One windows I can get around the firewall warning when listen on ```InetAddress.getByName(null)``` but kestrel doesn't give me a change to do so (https://github.com/aspnet/KestrelHttpServer/blob/6b2099df28bb97d7495e47e07c257d487b211bec/src/Microsoft.AspNet.Server.Kestrel/Http/Listener.cs#L73).

**Comment by jrieken** [comment]
@davidfowl - ask discussed

**Comment by DamianEdwards** [comment]
Kestrel shouldn't be binding to all addresses by default. We should just throw an exception if no binding information was configured.
