### ISSUE TITLE
Change to build to use dotnet

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/KestrelHttpServer#571]
Kestrel has a "special" build:

- It invokes DNX as a post build step
- It relies on compilation modules
- Might (not sure) spin up a new server that's not in proc as part of the tests

cc @cesarbs @halter73

**Comment by victorhurdugaci** [comment]
At a minimum, you have to upgrade a few script and project.json files just like here: https://github.com/aspnet/Configuration/commit/9cfd22f1fc48d46d9aa35e645c4daf89b7987422

**Comment by victorhurdugaci** [comment]
cc @muratg

**Comment by halter73** [comment]
> * It invokes DNX as a post build step

I don't think this should be a huge issue. Basically all we need to do is run two command line apps (tools/Microsoft.AspNet.Server.Kestrel.GeneratedCode and tools/Microsoft.AspNet.Server.Kestrel.GeneratedCode) before building the main project.

> * It relies on compilation modules

I think we can remove this for now as long as we have a plan to move this to [an analyzer](https://github.com/aspnet/KestrelHttpServer/pull/518/files#r49260663).

> * Might (not sure) spin up a new server that's not in proc as part of the tests

Why do you think that? I'm pretty sure that's not the case.

**Comment by cesarbs** [comment]
>I think we can remove this for now as long as we have a plan to move this to an analyzer.

Why do we care about this only in Kestrel? I don't see anything similar in other projects.

**Comment by davidfowl** [comment]
We don't actually. We can remove it for now and fix it later. @lodejard wrote it to keep himself in check :smile:
