### ISSUE TITLE
IsLocal returns false when hosted through the TestServer

### ISSUE THREAD

**Issue by fermaem** [aspnet/KestrelHttpServer#576]
The following test fails when ran against rc2. 

Is this considered as a bug? Wouldn't that be the case, could you please help me working around it (maybe through some additional test configuration setup)?

```csharp
using System;
using System.Net;
using System.Net.Http;
using Microsoft.AspNet.Hosting;
using Microsoft.AspNet.TestHost;
using Newtonsoft.Json;
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Http;
using Xunit;

namespace ClassLibrary1
{
    public class Class
    {
        public class Model
        {
            public string RemoteIPAddress;
            public int RemotePort;
            public string LocalIPAddress;
            public int LocalPort;
            public bool IsLocal;
        }

        [Fact]
        public async void tada()
        {
            var builder = new WebApplicationBuilder()
            .Configure(app =>
            {
                app.Run(async context =>
                {
                    var connection = context.Connection;
                    await context.Response.WriteAsync(JsonConvert.SerializeObject(new Model
                    {
                        RemoteIPAddress = connection.RemoteIpAddress?.ToString(),
                        RemotePort = connection.RemotePort,
                        LocalIPAddress = connection.LocalIpAddress?.ToString(),
                        LocalPort = connection.LocalPort,
                        IsLocal = connection.IsLocal
                    }));
                });
            }); ;

            using (var server = new TestServer(builder))
            using (var client = server.CreateClient())
            {
                var request = new HttpRequestMessage(HttpMethod.Get, new Uri("http://localhost/Huh"));
                request.Headers.Host = request.RequestUri.Host;
                var response = await client.SendAsync(request);
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                var body = await response.Content.ReadAsStringAsync();

                var obj = JsonConvert.DeserializeObject<Model>(body);

                Console.WriteLine(body);
                Assert.True(obj.IsLocal);
            }
        }
    }
}
```

Below what the server returns

```json
{
  "RemoteIPAddress":null,
  "RemotePort":0,
  "LocalIPAddress":null,
  "LocalPort":0,"
  IsLocal":false
}
```

/cc @troydai (because of #284)

**Comment by troydai** [comment]
Thanks for reporting the issue. Can I know the implementation of the `TestServer`? It doesn't seem to be https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNet.Server.KestrelTests/TestServer.cs

**Comment by fermaem** [comment]
Thanks for the feedback.

>Can I know the implementation of the TestServer?

@troydai @Tratcher Indeed this is `Microsoft.AspNet.TestHost.TestServer`

>I really want to remove the IsLocal property, it's misleading.

@Tratcher Any chance you could elaborate further on this?

**Comment by troydai** [comment]
The logic which causes the misleading property is here: https://github.com/aspnet/KestrelHttpServer/blob/e9a60610236c53e9518fe80ccf75f14b7e5d02f8/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.cs#L125. Since obviously both addresses are actually `null` it should returns `true`.

**Comment by troydai** [comment]
@fermaem this is not an actual Kestrel issue, since the `TestServer` you're using doesn't use `Kestrel` instead it initialize the default http components like `HttpConnectionFeature` (https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/Features/HttpConnectionFeature.cs). Of which the property value of `IsLocal` is never set, so by default it is `False`. 

For `TestServer` the assumption is that the server code is aware of the situation that `IsLocal` property doesn't provide the most accurate information.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#570
