### ISSUE TITLE
Have a notification on successful startup

### ISSUE THREAD

**Issue by suhasj** [aspnet/KestrelHttpServer#58]
When we run 'k kestrel' from the command line or shell, we need to wait for sometime for the server to start and then send the request.

The Musicstore starts kestrel server via code and there is no way for it see when the server has started unless we keep pinging the url for success. Can there be some kind of notification when the startup is successful like setting a variable or writing to a file ?

**Comment by Tragetaschen** [comment]
This could be implemented as part of aspnet/Hosting#127

**Comment by DamianEdwards** [comment]
This will covered by aspnet/Hosting#328
