### ISSUE TITLE
Error when Running SampleApp

### ISSUE THREAD

**Issue by ochowie** [aspnet/KestrelHttpServer#591]
When I run the sample app using coreclr 1.0.0-rc2-16357 I get the following error:

KestrelHttpServer/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.FeatureCollection.cs(23,34): .NETPlatform,Version=v5.4 error CS0535: 'Frame' does not implement interface member 'IHttpConnectionFeature.IsLocal'

**Comment by BrennanConroy** [comment]
New bits were just pushed to the dev feed so this is fixed.
