### ISSUE TITLE
Expose raw request path/URL in HTTP context

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#594]
After normalization (see #573) we lose the raw request path/URL received from the client. Some applications might be interested in it, so we should expose the pre-normalized path/URL to them.

**Comment by Tratcher** [comment]
This will likely be exposed via a standard feature interface.

**Comment by DamianEdwards** [comment]
post RC2

**Comment by cesarbs** [comment]
Done https://github.com/aspnet/KestrelHttpServer/pull/880
