### ISSUE TITLE
Running aspnet web api stucks at benchmarking using siege

### ISSUE THREAD

**Issue by ArkadyB** [aspnet/KestrelHttpServer#595]
Hi,

Im not sure, but it looks to be some kind of server issue. I have tried same test with IIS/IISExpress and everything looks smooth.

Application: A small Web API project with only 1 endpoint that returns text value:
public string Test1()
{
          return "Test";
}

Accessing this endpoint in browser work fine, but as soon as i try to call it frm siege or console app (calling this url in multithread) it stuck. In some time i get timeout errors.

Any idea? We were getting ready to use this corefx in prod once release, but this is nonsense issues...

**Comment by DamianEdwards** [comment]
We'll need to try and reproduce this, so any other information you can provide would help, e.g. Core CLR or full CLR, x86 or x64, Windows or Linux, version you're using, etc. In our testing so far we haven't seen such a simple issue (see our plaintext benchmark results using pure middleware or MVC).

**Comment by benaadams** [comment]
@ArkadyB there was a issue in RC1 with non-keep alive or HTTP/1.0 which has been resolved in RC2 https://github.com/aspnet/KestrelHttpServer/issues/406 - and can be resolved in RC1 by making sure the connection is keep-alive similar to https://github.com/aspnet/KestrelHttpServer/issues/468

**Comment by ArkadyB** [comment]
Hi, 
im running app in Docker container built on top of microsoft/aspnet:1.0.0-rc1-update1.
Therefore its coreclr with Debian Linux. Test is very simple: 1 method webapi solution with DNX5. 
Siege utility command:
siege -c10 -t60s http://url

**Comment by benaadams** [comment]
@ArkadyB that question is for @DamianEdwards 

Are you using ngnix (if so you may need to add keep-alive to its proxy config)
Otherwise, for siege directly change `connection = close` to `connection = keep-alive` in its config file and see if that resolves the issue - which will mean it is the same cause.

**Comment by ArkadyB** [comment]
@benaadams ive tried with keep-alive and result is same. Any idea? Is there logs anywhere i may have a look to check for errors or so?

ive tried same with mono and xsp4 and it works fine...
