### ISSUE TITLE
Microsoft.AspNet.Server.Kestrel.Https Not Support dnxcore5

### ISSUE THREAD

**Issue by qin-nz** [aspnet/KestrelHttpServer#597]
In your example, dnxcore5 can use https.
But package in Nuget are only support dnx451.
https://www.nuget.org/packages/Microsoft.AspNet.Server.Kestrel.Https/1.0.0-rc1-final

**Comment by BrennanConroy** [comment]
That's because it wasn't made for dnxcore50 until RC2
https://github.com/aspnet/KestrelHttpServer/issues/345
