### ISSUE TITLE
http request to localhost kestrel server hangs when using node.js client

### ISSUE THREAD

**Issue by mypark** [aspnet/KestrelHttpServer#601]
This is more a of a quesiton than a confirmed issue.

I have some testing tools in node.js that I would like to run against my asp web-api running on my localhost kestrel server, but it seems to hang whenever I make the request using a node.js client.

Node.js makes the request but then seems to hang and timeout. I can see in the kestrel logs that the http request is made and successful, and making the request to the local kestrel server using postman and other client tools seem to work.

What is it about the interaction between node.js and kestrel that is making it hang on localhost?

**Comment by benaadams** [comment]
Kestrel version? May be an issue that was resolved in RC2 https://github.com/aspnet/KestrelHttpServer/issues/406

**Comment by mypark** [comment]
"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",

**Comment by mypark** [comment]
How do I install rc2 using nuget or dnu in my asp.net project?

**Comment by benaadams** [comment]
Its not released yet, so you'd need to use the myget feed from https://www.myget.org/gallery/aspnetvnext (urls are on page)

However, as you may have to make some changes between RC1 and RC2 and there is a rename going on which means you'll have to make some more changes; you may want to wait a little while otherwise you will need to male two sets of changes,

**Comment by mypark** [comment]
Ok, I'll wait.  When is the planned date for rc2?  Is that going to coincide with an update of the asp.net RC as well?

**Comment by muratg** [comment]
@mypark ASP.NET Core [roadmap](https://github.com/aspnet/Home/wiki/Roadmap) will be updated when we know the release date for RC2.  Like RC1 and previous releases, all of ASP.NET Core packages will be released, including Kestrel.

**Comment by muratg** [comment]
Dup of #406

**Comment by mshanak** [comment]
This[ blog post](https://medium.com/@mshanak/soved-dotnet-core-too-many-open-files-in-system-when-using-postgress-with-entity-framework-c6e30eeff6d1) could help
