### ISSUE TITLE
Add automated test coverage for concurrent connections/requests

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#604]
@muratg Anything else I should add to this issue?

**Comment by benaadams** [comment]
Very high connection counts would be a good test; @mgravell suggests SO is 40k+ per node https://twitter.com/marcgravell/status/673275023944216576

Something to watch out for is ephemeral port use; so you probably have a safe max of 32k connections per client ip address; so would need to have more than one client ip address to achieve the load.

**Comment by muratg** [comment]
@SajayAntony

**Comment by SajayAntony** [comment]
No automation or functional tests. We only have plan for a E2E kind of scenario with about 10-50k connection. 
@taoliseki has a PR out for the E2E scenario. aspnet/performance#82

**Comment by mgravell** [comment]
@benaadams re ephemeral ports: we made our server bind to multiple ports
internally for that reason - we then use smoke and mirrors at the NLB
(haproxy) to hide that detail from the outside world. IIRC, we currently
bind each process (one process per box) to 3 ports.

**Comment by muratg** [comment]
@SajayAntony's lab covers this
