### ISSUE TITLE
Running ApacheBench against empty RC1 template using kestrel results in timeout

### ISSUE THREAD

**Issue by christiansparre** [aspnet/KestrelHttpServer#605]
Hi, I'm having trouble doing some simple benchmarks using ApacheBench on a project we are experimenting with.

I'm on Windows 7 with rc1-update1.

When trying to use ApacheBench the tool fails with the below message, I tried creating a new project using the empty RC1 template, this also failed.

```
ab -c 1 -n 100 http://localhost:5000/
```
```
Benchmarking localhost (be patient)...
Test aborted after 10 failures

apr_socket_connect(): No connection could be made because the target machine actively refused it.   (730061)
```

When using IISExpress from with VS it works fine. I have tried using different ports with kestrel with no luck. I have tried with the latest available RC2 builds with no luck. I tried the ab -k switch (KeepAlive) as I was told that might be the issue.

Any idea what might be causing this?

**Comment by khellang** [comment]
@christiansparre Are you sure the application successfully binds to port 5000? Have you tried running it as an administrator?

**Comment by christiansparre** [comment]
Yes. It's running as admin and I can get to it from a browser and PostMan etc. :)

**Comment by christiansparre** [comment]
This is how it looks :)

![image](https://cloud.githubusercontent.com/assets/620770/12720370/d4b29e20-c8fa-11e5-9764-21b1804e5e79.png)

**Comment by khellang** [comment]
What if you use `127.0.0.1` instead of `localhost`? :confused:

**Comment by christiansparre** [comment]
After trying a bit more I have had success with this example: https://github.com/roydukkey/moist/tree/stackoverflow-34615917

It uses rc2-*

It is configured for http://localhost:1234 but that does not work. With **http://127.0.0.1:1234** works as expected in ApacheBench, yay! :)

I still have not had success with RC1, have tried 127.0.0.1 also, netstat reports dnx.exe listening on the right port.

So something changed in the current RC2 builds, but I can still not make localhost work.

**Comment by christiansparre** [comment]
I'm going to dig a bit into this, from what I can see when it works I hit this method

https://github.com/aspnet/KestrelHttpServer/blob/b062f851dcb1fc9013952fe72e9a087ae36323fe/src/Microsoft.AspNetCore.Server.Kestrel/Http/TcpListenerSecondary.cs#L20

But not otherwise, have not looked at the kestrel code before so I'm a bit lost as to where it all starts. But I'll nose around a bit :)

**Comment by christiansparre** [comment]
Ok, I'm way in over my head not known a thing about how libuv works :). The only thing I have found out is that when using localhost nothing that I can track down in krestrel is called.

There seems to be some related issues around like: #601, #406 and #426

**Comment by Tratcher** [comment]
Localhost binds to [::1] right now, not 127.0.0.1.
https://github.com/aspnet/KestrelHttpServer/issues/231

**Comment by christiansparre** [comment]
@Tratcher thank you, that explains it I think. At least for RC2, RC1 still does not work either way.

**Comment by amici** [comment]
> 
> 
> What if you use `127.0.0.1` instead of `localhost`? 😕 Could be worth looking at `netstat -anb` to see the interface it's bound to.

After having the same problem (but on port localhost:80), trying with the 127.0.0.1 worked for me.
