### ISSUE TITLE
Cannot load System.Reflection Assembly

### ISSUE THREAD

**Issue by Lutando** [aspnet/KestrelHttpServer#606]
I have a Simple barebones mvc example that seems to be re-producible across a few of my workstations

The ASPNETCore application seems to startup however when I try to make an API call I get the following error

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5200/app/thing
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.IO.FileNotFoundException
      Could not load file or assembly 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 93,2095ms 200`

Startup.cs

```
public void ConfigureServices(IServiceCollection services)
 {
       services.AddMvc();
 }

public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
 {
        loggerFactory.AddConsole();            
        app.UseMvc();
        app.UseStaticFiles();
 }
public static void Main(string[] args)
 {
        var configuration = WebHostConfiguration.GetDefault(args);
        var host = new WebHostBuilder()
            .UseStartup<Startup>()
            .UseConfiguration(configuration)
           .UseServer("Microsoft.AspNetCore.Server.Kestrel")
           .Build();

         host.Run();
}
```

**Comment by davidfowl** [comment]
Can you push a application to a github repo so we can reproduce the problem. Also a copy of the lock file would be useful.

**Comment by Lutando** [comment]
Can be found here - https://github.com/Lutando/KestrelIssue606

**Comment by adrien-constant** [comment]
I've got the same error since I upgraded to the latest AspNetCore versions. Adding 
`        "System.Reflection": "4.1.0-rc2-23728" `
in project.json did not help. I guess version 4.1.0.0 is expected.

> 
> FileNotFoundException: Could not load file or assembly 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()

**Comment by cesarbs** [comment]
I can only repro this when using `dotnet`. It runs fine on `dnx`. @Lutando can you confirm you're using `dotnet`?

**Comment by Lutando** [comment]
On the contrary I get it when using dnx (latest unstable)

**Comment by cesarbs** [comment]
I *think* this is fixed by https://github.com/dotnet/cli/commit/a6bfc67e8ad486998043795b418bb62189951130. Will confirm with @pakrym.

**Comment by cesarbs** [comment]
Unfortunately that's not the case.

**Comment by cesarbs** [comment]
Issue does not repro on dnx 1.0.0-rc2-16453 nor CLI from the latest source. Looks like it's been fixed indirectly.

**Comment by Lutando** [comment]
How do I get dnx 1.0.0-rc2-16453? When I `dnvm upgrade - u` the latest is still  1.0.0-rc2-16357

**Comment by adrien-constant** [comment]
I reproduce this with dotnet (I can't use dnx because of another bug with dnx in the latest version).
I'm also on dnx-clr-win-x86.1.0.0-rc2-16357 and I cannot get 1.0.0-rc2-16453

**Comment by Lutando** [comment]
Can confirm that this bug cannot be reproduced on dnx 1.0.0-rc2-16453

**Comment by adrien-constant** [comment]
That's a good news, but how do we get dnx 1.0.0-rc2-16453 ?
dnvm upgrade -u 1.0.0-rc2-16453 ends up with 1.0.0-rc2-16357
It's not publicly available yet? I'm stuck so whatever it takes to get the version, I will do it.

**Comment by Lutando** [comment]
set your system/user environment variable  DNX_UNSTABLE_FEED to https://www.myget.org/F/aspnetcidev/api/v2/

```
set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/api/v2/
dnvm upgrade -u
```

**Comment by adrien-constant** [comment]
That fixed the problem. Thanks a lot.

**Comment by Lutando** [comment]
closing the issue
