### ISSUE TITLE
Shrink the size of memory pools when usage decreases

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#609]
Currently the memory pool implementation will only grow in size. This means if there is burst of high load that subsided, memory usage for the Kestrel process will not decrease as much as it could.

**Comment by benaadams** [comment]
Apply common server/cluster load balancing model? 

Round robin pools per slab? Move slabs move out of rotation; but accept returns. When all blocks are returned dispose slab; if alloc is needed prior, move slab back into rotation; if no slabs being deallocated allocate new.

**Comment by benaadams** [comment]
Probably need some heuristics on whether growing, shrinking or static to determine whether to take slabs out of rotation

**Comment by muratg** [comment]
Closing because @davidfowl thinks this is not problem.
