### ISSUE TITLE
How to specify / modify request timeout

### ISSUE THREAD

**Issue by ayende** [aspnet/KestrelHttpServer#611]
I couldn't find a way in the API to set the request timeout, and (preferably) a way to dynamically change it.
Like this:

HttpContext.Current.Server.ScriptTimeout = 60 * 60 * 6;

Is this possible?

(Also, is this the right place to ask, is there a mailing list / forum?)

**Comment by davidfowl** [comment]
> HttpContext.Current.Server.ScriptTimeout = 60 * 60 * 6;

That only worked for synchronous requests in ASP.NET not async ones (AFAIK)

> Is this possible?

There's no http request timeout in kestrel. https://github.com/aspnet/KestrelHttpServer/issues/484

> (Also, is this the right place to ask, is there a mailing list / forum?)

@ayende if it's kestrel specific you can ask here. Otherwise, best to ask on aspnet/Home and have it be redirected.

**Comment by ayende** [comment]
@davidfowl Thanks,.

So what would be the behavior if I'm making an async operation in the request that doesn't timeout?
Do we rely on the client to give up on this?

I'm actually very happy that I don't need to manage that, by the way.

The issue is that I have a client that is uploading a large dataset, and I had to manage this with the previous version of ASP.Net.
Note having limits that I constantly have to manage is great, but on the other hand, what happens if a client open a request, write three bytes, and keep the connection open?

Do we rely on TCP to close the connection?

What happens if we have a client that send a byte per second? And thus creating tens of thousands of connections? That can cause us to hold a lot of state in memory.

**Comment by davidfowl** [comment]
> So what would be the behavior if I'm making an async operation in the request that doesn't timeout?
Do we rely on the client to give up on this?

Currently yes. There's going to be a pass done to make sure there's limits for things like these (the issue I pointed you to), along with other limits (max body, max query, max headers etc).

> The issue is that I have a client that is uploading a large dataset, and I had to manage this with the previous version of ASP.Net.
Note having limits that I constantly have to manage is great, but on the other hand, what happens if a client open a request, write three bytes, and keep the connection open?

> Do we rely on TCP to close the connection?

> What happens if we have a client that send a byte per second? And thus creating tens of thousands of connections? That can cause us to hold a lot of state in memory.

https://en.wikipedia.org/wiki/Slowloris_(computer_security)

All of these things are why we recommend that you host kestrel behind a reverse proxy like nginx. That's not to say we won't address some of these features in general. Some we will, some we want.

**Comment by davidfowl** [comment]
Here's a PR from @benaadams adding some timeout logic https://github.com/aspnet/KestrelHttpServer/pull/485

**Comment by muratg** [comment]
Closing this one (#485)

**Comment by mskryvonos** [comment]
@muratg @davidfowl  That PR hasn't actually went through, do you know if there are any plans to add this functionality to Kestrel in 1.1 release?

**Comment by muratg** [comment]
cc @cesarbs

**Comment by cesarbs** [comment]
I'm currently working on adding timeouts to Kestrel. There's a PR out for keep-alive (https://github.com/aspnet/KestrelHttpServer/pull/1066) and I will be sending another one soon for request headers and request body timeouts.

**Comment by MelbourneDeveloper** [comment]
I've got a WCF timeout occurring. I've set all the WCF timeouts to 24 hours. Is it possible that Kestrel is timing out? How do I set the timeouts for Kestrel?

**Comment by davidfowl** [comment]
What kind of timeout are you looking for?

**Comment by paulgmiller** [comment]
Is there an equivalent of SendTimout in kestrel?  
https://msdn.microsoft.com/en-us/library/system.servicemodel.channels.binding.sendtimeout(v=vs.100).aspx

DIdn't see a direct equivalent in kestreal server limits. 
https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0/src/Microsoft.AspNetCore.Server.Kestrel.Core/KestrelServerLimits.cs

**Comment by Tratcher** [comment]
@paulgmiller not a global one. MinResponseDataRate is as close as it gets.

Call WriteAsync with a CancellationToken.
