### ISSUE TITLE
What is the best way to return a response in gzip?

### ISSUE THREAD

**Issue by mwalterXML** [aspnet/KestrelHttpServer#613]
Hello 

We are using kestrel server to run differens Web APIs, 
We need to return the json response compress in gzip.

Is posible using only Kestrel?

Thanks
Best regards,
Mitchell

**Comment by davidfowl** [comment]
> Is posible using only Kestrel?

This has nothing to do with kestrel. You can just write a middleware that does gzipping. You can even do it in MVC if you want to.

**Comment by GuardRex** [comment]
@mwalterXML You can see the `System.IO.Compression` tests here: https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/tests/GZipStreamTests.cs

**Comment by muratg** [comment]
This issue was moved to aspnet/Home#1276
