### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Server.Kestrel

### ISSUE THREAD

**Issue by ltheONEl** [aspnet/KestrelHttpServer#620]
I am upgrading a test asp core up from rc1 to 1.0.0-rc2-16522
I am using this feed: https://www.myget.org/F/aspnetcidev/api/v3/index.json

I used the MusicStore sample to aid with making changes to my rc1 version to use the new startup procedure.  I think I am mostly there but I cannot resolve this issue:

An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not load file or assembly 'Microsoft.AspNetCore.Server.Kestrel' or one of its dependencies. The system cannot find the file specified.

this occurs in the main program entry point:
public static class Program
{
    public static void Main(string[] args)
    {
         var host = new WebHostBuilder()
         .UseDefaultConfiguration(args)
         .UseIISPlatformHandlerUrl()
         .UseStartup("TestApi")
         .Build();
         host.Run();
      }
}
Kestrel Server is set in the hosting.json file.
{
  "server": "Microsoft.AspNetCore.Server.Kestrel"
}

Is there some other configuration that is required?

**Comment by muratg** [comment]
What's your project.json look like?  Did you update the package name to Microsoft.AspNet.Server.Kestrel to Microsoft.AspNetCore.Server.Kestrel there?

**Comment by ltheONEl** [comment]
Sweet,  I missed that namespace change.  Thanks.
