### ISSUE TITLE
Problems with performance testing (stops responding)

### ISSUE THREAD

**Issue by ArkadyB** [aspnet/KestrelHttpServer#626]
Hello guys,

Ive been writing a while ago about problems with server to respond to siege stress tests and ur recommendation to use keep-alive header worked, but now it seem to be broken again and even keep alive does not help.

Having siege set to run with 15 users i see first 15 requests to be served and thats it, no more request is being processed. I have keep-alive enabled.

Any suggesting? Was something changed in last 4 days?

**Comment by ArkadyB** [comment]
It seems not even required to run it on Linux. I have tried to run web endpoint frm Visual Studio 2015 and behavior is same - having started benchmarking utility server stops responding after few requests processed.

**Comment by benaadams** [comment]
project.json and resolved package version used would be helpful

**Comment by ArkadyB** [comment]
Project.json:
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Formatters.Xml": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "System.Net.Http": "4.0.0",
    "System.Xml.XDocument": "4.0.11-beta-23516"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://0.0.0.0:5000"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "System.Net.Http": "4.0.1-beta-23516"
      }
    },
    "dnxcore50": {
      "dependencies": {
        "System.Xml.XmlDocument": "4.0.1-beta-23516",
        "System.Xml.XPath.XmlDocument": "4.0.1-beta-23516"
      }
    }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}

What package u mean?

One more notice. While testing i found strange coincidence with return value size.
Problem happens when the return json document size is around 130Kb. I have changed to return empty document instead - about 12 bytes (rest of logic remain same - all the calculations and data manipulation) and it works much more stable...

**Comment by yuwaMSFT** [comment]
Was the server running on Windows or Linux? Behind any HTTP server?
I did a quick test with kind of latest runtime 1.0.0-rc2-16453. The server is on Linux with Nginx as proxy. It's an MVC with one action returning about 225KB json. 

I ran 500 clients for 10 minutes, with avg about 220 req/s. All seemed fine...Will let it run longer and see.

**Comment by ArkadyB** [comment]
Hi @yuwaMSFT ,
Its both, for windows and ubuntu, same behavior. I have Web Api project. 

What u use for testing? Is RC2 available yet?

**Comment by ArkadyB** [comment]
Hello,
Any feedback on that, is it a bug and should be fixed sometime soon or am i doing somethin wrong?

**Comment by ArkadyB** [comment]
i have some way of replicating and issue and play around with server settings to let it get timouted and keep workin until next timeout. Having a parallel environment with Kestrel running behind of Nginx i found nginx configuration option called "keepalive_timout" to have affect on Kestrel stucks.
Changing this value i can push Kestrel to shoot a portion of failed connection and then start working once again before next timeout...

**Comment by halter73** [comment]
> Was something changed in last 4 days?

Considering that you are using the rc1-update1 packages, certainly not. Was the same scenario working correctly before that point.

If you don't mind testing on rc2, you can update your NuGet.Config to include "https://www.myget.org/F/aspnetcidev/api/v3/index.json" as a package source.

I assume your using this tool for load testing? https://github.com/JoeDog/siege

Could you give us which parameters your using for siege, your nginx configuration (are you using nginx to reproduce on Windows too?), and the application you're testing against?

The EPIPE errors shouldn't be a big concern. It means there was a write failure, but that shouldn't bring Kestrel to a halt. In rc2 we no longer throw an exception for these kinds of error by default, we simply log them.

**Comment by ArkadyB** [comment]
Yes, i do use siege as:
siege -t1M -c150 -d1s -v http://endpoint

Failing configuration: 1. Ubuntu VM with DNX or 2. Run application from Visual Studio 2015 - Kestrel endpoint (web).
When I do mentioned above siege, both installations fail regardless of number of cores or RAM assigned to VM. In case of Visual Studio I run on local machine which is i7 Xenon with 16GB RAM...

A successful configuration is: 
Ubuntu VM (2 cores/1Gb RAM) with DNX and Nginx installed. Nginx is used to proxy requests. Nginx.conf has 2 processes with 512 connections allowed in each.  Nginx is set to keep-living connection with 5s for keep-livinf timeout. 

No idea where the problem is, but sieging Kestrel directly failing. Is there some way I can forward you my app directly?

**Comment by halter73** [comment]
@ArkadyB If you can't push your app to a github repo, you can email it to me. My email address is set to public on my github profile. Did you try rc2?
