### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'libuv'

### ISSUE THREAD

**Issue by munyirik** [aspnet/KestrelHttpServer#627]
I hit this issue when trying to run an asp.net 5 server on my Raspberry Pi 2 (with Windows IoT Core).

**Repro steps:**
1. Installed arm coreclr with: dnvm install latest -r coreclr -arch arm -u
2. Created new asp.net 5 web application in VS (with no modifications of my own) and published with: dnu publish --out C:\projects\asp5 --runtime dnx-coreclr-win-arm.1.0.0-rc2-16357.
3. Copied the published files to RPi2 and ran the application.

**Result:**
.\asparm\approot\web.cmd : System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception
from HRESULT: 0x8007007E)
    + CategoryInfo          : NotSpecified: (System.DllNotFo...LT: 0x8007007E):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNet.Server.Kestr
el.Networking.Libuv.loop_size()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)

**Workaround**
Copied \approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\runtimes\win10-arm\native\libuv.dll to \approot\packages\Microsoft.AspNet.Server.Kestrel\1.0.0-rc1-final\lib\dnxcore50

**Comment by munyirik** [comment]
Looks like the same issue as https://github.com/aspnet/KestrelHttpServer/issues/216

**Comment by moozzyk** [comment]
This was fixed post RC1

**Comment by munyirik** [comment]
@moozzyk where can I get RC1 from?

**Comment by shahid-pk** [comment]
@munyirik  you need to wait for rc2 release. until then use the workaround.

**Comment by munyirik** [comment]
Got it. Thanks.
