### ISSUE TITLE
Throw InvalidOperationException if the user tries to modify response headers after the body starts

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#628]
Sometimes users accidentally set response headers after the response starts and it can be very hard to debug why the client did not receive the header.
https://github.com/aspnet/Mvc/issues/4065#issuecomment-181638058

Throw an InvalidOperationException if the user tries to modify response headers after the first write to the body.

WebListener already does this. Helios used to as well.

**Comment by benaadams** [comment]
Readonly or full on disposed?

**Comment by Tratcher** [comment]
readonly, you may still want to enumerate and log them

**Comment by benaadams** [comment]
Is in https://github.com/aspnet/KestrelHttpServer/pull/608
