### ISSUE TITLE
[Question] Kestrel behind IIS, remote IP address

### ISSUE THREAD

**Issue by andreigorlov** [aspnet/KestrelHttpServer#632]
Is there a way to retrieve remote IP in Kestrel behind IIS configuration?

HttpContext.Connection?.RemoteIpAddress?.ToString() is always "127.0.0.1"

(Microsoft.AspNet.Server.Kestrel v1.0.0-rc2-16236)

**Comment by ayende** [comment]
Probably this?
https://en.wikipedia.org/wiki/X-Forwarded-For

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Tratcher** [comment]
https://github.com/aspnet/Mvc/issues/4072#issuecomment-183464866, also for x-forwarded-for

**Comment by andreigorlov** [comment]
Thanks!
