### ISSUE TITLE
Kestrel + Proxying ( nginx/browsersync/etc ) = No response

### ISSUE THREAD

**Issue by amcdnl** [aspnet/KestrelHttpServer#636]
When using Krestel with Browser-sync my requests never respond. If I launch IISExpress and proxy the requests it works.

```
var gulp = require('gulp');
var browserSync = require('browser-sync');
var proxyMiddleware = require('http-proxy-middleware');
var historyApiFallback = require('connect-history-api-fallback');
var path = require('path');
var dnx = require('gulp-dnx');

gulp.task('start', ['web', 'api']);

gulp.task('web', function(done){
  var apiProxy = proxyMiddleware('/api', { 
    target: options.baseUrl,
    ws: true,
    changeOrigin: true
  });

  browserSync({
    files: ['wwwroot/index.html'],
    server: {
      baseDir: ['wwwroot'],
      middleware: [ apiProxy, historyApiFallback() ]
    }
  }, done);
});

var options = {
  cwd: path.resolve(path.join(__dirname, '..', '..', 'API')),
  baseUrl: 'http://localhost:5000/',
  restore: false,
  build: false,
  run: true
};

gulp.task('api', dnx('web', options));
```

Many others have had this issue too:

- https://github.com/BrowserSync/browser-sync/issues/905
- http://stackoverflow.com/questions/34025282/browser-sync-not-loading-asp-net-5-website-using-proxy

**Comment by amcdnl** [comment]
@cesarbs lets move the convo here since its related.

**Comment by cesarbs** [comment]
What version of Kestrel are you using?

**Comment by amcdnl** [comment]
RC1

**Comment by replete** [comment]
I've been having this exact problem and been pulling my hair out trying to fix it.

IT seems like Kestrel in this context is sending as `chunked` but doesn't seem to send the last 0-length chunk (which would end the data).

Closing kestrel while browserSync is waiting kills the connection and the browser starts trying to use what it did download.

**Comment by amcdnl** [comment]
@replete Use WebListener, its a known bug that is fixed already in master but not published

**Comment by replete** [comment]
@amcdnl Thanks, I did figure this out on my own in the end.

As an aside, do you personally feel that it is anywhere near a good time for someone to start moving from an (incompelte) RC1 project to RC2?

**Comment by amcdnl** [comment]
@replete its not for the light hearted.... 

- most third-party packages don't support it yet
- obvs issues like ^^
- I think RC2 is gonna have some major changes too so moving target.

**Comment by cesarbs** [comment]
@amcdnl Have you tried this with the latest Kestrel from the dev feed?

**Comment by amcdnl** [comment]
@cesarbs I have not, I actually dropped browsersync recently too.

**Comment by MarkPieszak** [comment]
@amcdnl I recently had to give up on this (for the time being as well).
Somehow getting webpack with browserSync & Kestrel to play together seems impossible... :(

I'm guessing it's because Kestrel & Node just don't play well together yet??

**Comment by amcdnl** [comment]
@MarkPieszak you can use weblistener. Its not just Node, I tried nginx too and had same issue. Its basically anything other than a browser ( proxy in these cases ) receiving the requests. This is claimed to be fixed in latest but have not personally tried.

**Comment by MarkPieszak** [comment]
How do you set up weblistener in .NET core? I see the options for IISExpress & Web (kestrel) but nothing for weblistener.

Oh I'll have to try it again today to see if it's actually fixed!

**Comment by amcdnl** [comment]
In Project.json 

```
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "weblistener": "Microsoft.AspNet.Server.WebListener"
  },
```

**Comment by MarkPieszak** [comment]
Oh excellent, so it all works with that? That's amazing I'll just use that for the time being then. :)
Thanks @amcdnl

**Comment by peterblazejewicz** [comment]
@cesarbs 
I'm using RC2 dotnet bits on OS X and have this problem with public dotnet build. Can I somehow help with solving the problem?
Thanks!

**Comment by amcdnl** [comment]
@peterblazejewicz I updated Friday and can concur this issue is still present with any type of proxying.

**Comment by dmikov** [comment]
+1 Very noticable

**Comment by halter73** [comment]
@amcdnl @dmikov If you change `proxy_pass http://localhost:5000;` to `proxy_pass http://127.0.0.1:5000;` does that fix the issue. We think this might be caused by #231.

**Comment by cesarbs** [comment]
I've figured out what's wrong. Right now, Kestrel will only listen on IPv4 when you bind to localhost. If you look at the network traffic when reproing this issue, you'll see nging trying to establish an IPv6 connection with Kestrel, failing, waiting for `proxy_connect_timeout`, then establishing an IPv4 connection and completing the request.

The delay after the IPv6 failure is out of our control. @Tratcher has pointed out to me that this is a known issue with winsock - it takes a long time for it to realize a connection failure on IPv6 before trying IPv4.

I'm going to fix #231 so binding to localhost will not cause this issue because Kestrel will be listening on both IPv4 and IPv6. For now you can workaround by either listening on both `127.0.0.1` and `::1`, or by proxying to `127.0.0.1` as @halter73 pointed above.

**Comment by amcdnl** [comment]
@halter73 Yes, that seems to work.

@cesarbs So the solution is to turn off IP6 until this is fixed officially?

**Comment by cesarbs** [comment]
@amcdnl If you bind Kestrel to both `http://127.0.0.1` and `http://[::1]`, it should work when nginx uses `proxy_pass http://localhost`.

**Comment by amcdnl** [comment]
@cesarbs I'm trying to get Parrallels proxying to work too reason I ask. I tried disabling IPv6 in that and no dice. It **doesn't** even respond when I try `http://127.0.0.1:5000/` or `http://localhost:5000/` either.

![p](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/f1af2470-d4ac-43ad-abb4-71402ba3da2a/2016-05-23_18-16-28.png)

I would probably be safe to assume this would not work with docker proxying too?

**Comment by mikeharder** [comment]
@amcdnl: You typically want to configure Kestrel to accept external requests when running inside a VM or container.  URLs `http://127.0.0.1` and `http://localhost` only accept requests from localhost.  Use a URL like `http://+` to listen for external requests.

**Comment by mikeharder** [comment]
To summarize, there are two valid workarounds for nginx proxying to Kestrel in RC2:

Workaround | nginx `proxy_pass` | Kestrel `UseUrls()`
--- | --- | ---
IPv4-only | `http://127.0.0.1` | `http://127.0.0.1`
IPv4 and IPv6 | `http://localhost` | `http://127.0.0.1;http://[::1]`

**Comment by amcdnl** [comment]
@mikeharder Can you provide an example of the config to make it accept external requests?

**Comment by mikeharder** [comment]
Accept external requests on both IPv4 and IPv6, port 5000:

```C#
var host = new WebHostBuilder()
    .UseUrls("http://+:5000")
    .UseKestrel()
```

**Comment by amcdnl** [comment]
@mikeharder Works! Thanks for your help!

**Comment by peterblazejewicz** [comment]
@mikeharder  Thanks!

**Comment by amcdnl** [comment]
@mikeharder shouldn't that be the default?

**Comment by halter73** [comment]
@amcdnl Rejecting external requests by default and when "localhost" is specified was a design decision we made to make Kestrel more secure by default: https://github.com/aspnet/Announcements/issues/80

I do think that Kestrel should bind to both the IPv4 and IPv6 loopback intervaces which is tracked by #231 and fixed by #870.

**Comment by erandros** [comment]
I'm having the same problem with browser-sync and kestrel.
Tried using this without success:
`.UseUrls("http://127.0.0.1;http://[::1]")`
I'm using kestrel dev branch.

Is there another workaround to try for this?

**Comment by peterblazejewicz** [comment]
I've used [this](https://github.com/aspnet/KestrelHttpServer/issues/636#issuecomment-221117020) with RC2 relase + BS 2.*

**Comment by erandros** [comment]
@peterblazejewicz that doesn't work for me either, sorry.  
I'm on Windows 10 (10586.318 build). Visual Studio 2015 Update 2, dotnet 1.0.0-preview1-002702, browser-sync 2.12.8, and tried with the RC2 release this time.

**Comment by peterblazejewicz** [comment]
@erandros 
The above solution definitely works for me (i've just tried at work):
```
$ gulp serve --reload --open
[08:40:47] Using gulpfile C:\dev\recipes\src\gulp-dotnet-browser-sync\StarterWeb\gulpfile.js
[08:40:47] Starting 'dotnet:hosting'...
[08:40:47] Finished 'dotnet:hosting' after 3.17 ms
[08:40:47] Starting 'serve'...
watching for changes ...
[BS] Proxying: http://127.0.0.1:5000
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://10.6.3.101:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.6.3.101:3001
 -----------------------------------
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 12580
Project StarterWeb (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hosting environment: Development
Content root path: C:\dev\recipes\src\gulp-dotnet-browser-sync\StarterWeb\
Now listening on: http://+:5000
Application started. Press Ctrl+C to shut down.
```
I'm using `+:5000` to setup Kestrel urls in above example but 'localhost:5000' and 'localhost:3000' when configuring BS

**Comment by okuz** [comment]
@peterblazejewicz 
I don't get it ...
this is what I did:
1) Microsoft.AspNetCore.Server.WebListene => in project.json
2) `"web": "Microsoft.AspNetCore.Hosting --server Microsoft.AspNetCore.Server.WebListener --server.urls http://+:5000"` => in project.json
3) I don't know where to put this:
`var host = new WebHostBuilder()
    .UseUrls("http://+:5000")
    .UseKestrel()`
4) this is the command line for BS: 

> browser-sync start --proxy "http://localhost:5000" --files "wwwroot/css/*.css"
(I'm not sure for the proxy)

**Comment by halter73** [comment]
@okuz Are you trying to use RC2? We no longer support adding commands (like the "web" command) to the project.json.

`"web": "Microsoft.AspNetCore.Hosting --server Microsoft.AspNetCore.Server.WebListener --server.urls http://+:5000" ` makes it look like your trying to use WebListener, but I assume it doesn't matter to you what server you use.

`var host = new WebHostBuilder() .UseUrls("http://+:5000") .UseKestrel()` belongs in your `Program.Main`. You should also have something like `.UseContentRoot(Directory.GetCurrentDirectory()).UseStartup<Startup>().Build();` after ` .UseKestrel()`, and add  `"buildOptions": { "emitEntryPoint": true ...` to your `project.json`.

I would see if you can get this sample running first: https://github.com/aspnet/cli-samples/tree/master/HelloMvc

I would also make sure that everything is working without a proxy trying anything else like browser-sync.

**Comment by amcdnl** [comment]
@halter73 upgraded to 1.0 and having same issue again :( ... Something change?
