### ISSUE TITLE
Create a logging scope per connection

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#640]
After seeing [HostingLogScope](https://github.com/aspnet/Hosting/blob/906ed5f0fb5408a0af5726e6bb201f7e67f88fe7/src/Microsoft.AspNetCore.Hosting/Internal/HostingLoggerExtensions.cs#L91), I realized we need the equivalent for Kestrel connections.

11 of the 13 special log functions defined in `KestrelTrace` take the connect id as a logging parameter. Of the remaining 2, `KestrelTrace.ApplicationError` _really should_ log the connection id but doesn't. It would be far more elegant to create a logging scope that includes the connection id assuming that these can be nested. This will also prevent future oversights like the one in `ApplicationError`.

An added benefit is that we could lazily serialize the connection id like we do with the request id since we're not constantly passing a connection id string to logging methods. See #638

_Note:_ we will have to be careful when logging outside of the connection's async loop (such as in callbacks on the libuv thread) since the AsyncLocal backing for the scope (I assume that what's being used) won't be available. In those cases I imagine we log connection id's like we do today, but check the loglevel before calling the log method so we don't have to serialize the connection id unnecessarily. That's assuming we can't delay the logging until we get back on the async loop.

**Comment by benaadams** [comment]
Isn't `AsyncLocal` for `HostingLogScope` as `AsyncLocal` modifies the execution context from default and would be seeing lots of `ExectionContext` allocations like you see when using the `HttpContextAccessor`

**Comment by halter73** [comment]
Ultimately I think it's up to the logger how they implement scopes. The [console logger uses AsyncLocal/CallContext](https://github.com/aspnet/Logging/blob/46c6d523fd323eba101f230b96111d3fa4dcfa46/src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs#L48), but it seems you would only pay for it if you use it.

It looks like our [NLogLoggerProvider uses a NestedDiagnosticsContext](https://github.com/aspnet/Logging/blob/4528bdbc2816a8b5f933d9c6cf2da806ce4a72ea/src/Microsoft.Extensions.Logging.NLog/NLogLoggerProvider.cs#L95) for scopes which is only backed by [a thread-local structure](https://github.com/jkowalski/NLog/blob/72f649596504d832eae0b9535c2d2e7583382182/src/NLog/NestedDiagnosticsContext.cs#L48). I imagine this would be more efficient, but completely break `HostingLogScope` and the suggested connection scope. Maybe we should use [MappedDiagnosticsLogicalContext](https://github.com/NLog/NLog-Contrib/blob/master/NLog.Contrib/MappedDiagnosticsLogicalContext.cs#L30) instead?

I don't think performance should be a concern here since Hosting creates even more scopes, and Hosting's request scopes will be implemented the same way as connection scopes.

**Comment by benaadams** [comment]
> I don't think performance should be a concern here since Hosting creates even more scopes,

Working on it ;-) https://github.com/aspnet/Hosting/pull/609 and https://github.com/aspnet/Logging/issues/366

**Comment by halter73** [comment]
Cool. We can follow whatever pattern we decide on for Hosting then :smile:

**Comment by benaadams** [comment]
Max pooling (https://github.com/aspnet/Performance/pull/67) allocs cirrently looks like this over 1M req

![pooled](http://aoa.blob.core.windows.net/aspnet/pooled.png)

**Comment by muratg** [comment]
Backlogging for now, we'll bring it back as needed.

**Comment by muratg** [comment]
cc @shirhatti, what's the wanted behavior?

**Comment by davidfowl** [comment]
We should do this in 2.1

**Comment by davidfowl** [comment]
Turns out this is a little more complicated than the current implementation as it doesn't work for multiple requests.

**Comment by davidfowl** [comment]
Turns out this is a false alarm. Seems like I was running old kestrel bits...
