### ISSUE TITLE
Dotnet affinity to a node/group prevents CPU saturation multi-socket hardware

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/KestrelHttpServer#650]
This is most likely due to using Processor groups and we need to configure the ThreadPool to use all processor groups using `Thread_UseAllCpuGroups `
Pointers to configuring different Knobs for CLR
* [CLR Configuration Knobs](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md)
* [Runtime Configuration](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md)

This is currently blocked by CLR Issue- [configuration settings for spanning processor groups not being set](https://github.com/dotnet/coreclr/issues/3380)

**Comment by benaadams** [comment]
Related https://github.com/aspnet/benchmarks/issues/56

**Comment by SajayAntony** [comment]
For now we are setting Clustering  mode `Numa Group size optimization` to `flat` so that all the cores belong to a single group. 

![biosconfiguration-cropped](https://cloud.githubusercontent.com/assets/1821104/13372784/95edadbc-dd07-11e5-993f-473a40d9459b.png)


Output from CoreInfo

![coreinfo](https://cloud.githubusercontent.com/assets/1821104/13372780/55518f1c-dd07-11e5-907d-b09d5221cf45.png)

Thanks to [this thread](http://stackoverflow.com/questions/28098082/unable-to-use-more-than-one-processor-group-for-my-threads-in-a-c-sharp-app) on stackExchange.

**Comment by SajayAntony** [comment]
@nathana1 were you able to verify if increasing the kestrel threads actually helped?

**Comment by SajayAntony** [comment]
This has currently been resolved - CLR needs to identify if there are issues with processor group affinity.
