### ISSUE TITLE
Include libuv.so in Kestrel NuGet package

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#651]
We already distribute libuv.dll and libuv.dylib for Windows and OS X, but so far we have required libuv.so to be manually installed globally on Linux platforms.

This has forced Linux users to either [build libuv from source](http://docs.asp.net/en/latest/getting-started/installing-on-linux.html#install-libuv) or install libuv from a non-default package repository and add a symlink from libuv.so to libuv.so.1 which breaks proper versioning of the shared libuv library.

I would not worry about defying Linux conventions by not relying on a system-wide shared library since Node.js statically links libuv on all platforms including Linux. Transitive dependencies also shouldn't be an issue since libuv [only requires libc](http://packages.ubuntu.com/wily/libuv1) and glibc provides binary backwards compatibility.

**Comment by Eilon** [comment]
cc @DamianEdwards because this affects experience (though, in a *good* way).

**Comment by Tragetaschen** [comment]
Which platforms would be included? x64 is rather obvious, but what about ARM? Big/Little Endian? Hard Float? If ARM is not included, there still needs to be a way to fall back to a system-wide installation

**Comment by halter73** [comment]
@Tragetaschen @moozzyk and I talked about this, and the plan is to be very specific with our linux runtime identifiers.

Depending on what type of granularity RIDs provide us, we'll probably specify which specific distros we are providing libuv for, and require a system-wide libuv install for everything else. Ideally we wouldallow any distro that uses glibc >= SOME_VERSION. I think we plan on supporting/testing [RHEL/CentOS and Debian/Ubuntu](https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps) with x64/x86/ARM support.

**Comment by davidfowl** [comment]
Tell me we aren't going to embed that many libuv assemblies in kestrel right? right?

**Comment by halter73** [comment]
Since libuv only requires libc and glibc provides binary backwards compatibility (and all of our supported distros use glibc) we should only need to build once per instruction set. We already have x64/x86/ARM builds for Windows in the kestrel package.

I don't think we can use a "linux-{instruction set}" RID though because some distros don't use glibc like docker's new default base image Alpine Linux.

**Comment by Tragetaschen** [comment]
For ARM, it might not be enough to just differentiate via instruction set. If Kestrel would only look at the instruction set and include a Hard Float, Little Endian (the reasonable choice IMHO, at least for me :grin:) precompiled `*.so`, it'll die horribly on an ARM SoC without FPU or one that's compiled for Big Endian.

It might be necessary to include an explicit method of opting out of using the binary shipped with the *.nuget. This might also be enough to support "specialized" distributions that are based off of a different C library.

**Comment by moozzyk** [comment]
Maybe we should not include a version for ARM non-windows?

**Comment by ayende** [comment]
One of our use cases is to run on ARM on Linux, anything that make it
easier is preferred.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Tragetaschen** [comment]
@moozzyk I think it's perfectly fine to limit the provided, compiled `so`s to the "95%" case as long as Kestrel notifies developers in case of the remaining "5%".

For example for "Linux x64", I don't see a need for Kestrel to ship support for anything other than "[g]libc > x.yz" out of the box as long as there is an understandable and actionable error in case "Linux-x64" doesn't imply glibc like in @halter73's example with Alpine Linux.

The same goes for ARM, IMHO. The "Linux-ARM" `so` shipped with Kestrel should require a Little Endian system with hardware FPU, but again provide an actionable error in case these requirements are not met.

In both cases, the ability to tell Kestrel where to load an `so` from or telling it to use them from the "environment" instead of the included object files can solve the remaining "5%". For example Docker with the mentioned base image already offers all infrastructure to provide a "system-wide" libuv that Kestrel can use.

**Comment by moozzyk** [comment]
@ayende - you would compile libuv as you have to today.

**Comment by muratg** [comment]
@moozzyk Will you be able to do this?

**Comment by moozzyk** [comment]
Yes, if we decided to do this.

**Comment by moozzyk** [comment]
This is fixed with 5f6293110cbde66efd1c73572882206fd1d8af3a. However this https://github.com/dotnet/corefx/issues/6756 needs to be fixed for the change to work end to end on ubuntu

**Comment by moozzyk** [comment]
https://github.com/dotnet/corefx/commit/93609c50d3a68b8eed939c1e5252ab7230f2070d - closing.
