### ISSUE TITLE
Return different status codes depending on condition

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#653]
Surface different error types, possibles

400 Bad Request + close connection? https://github.com/aspnet/KestrelHttpServer/issues/181 (Resolved by https://github.com/aspnet/KestrelHttpServer/pull/619)
408 Request Timeout (Resolved by https://github.com/aspnet/KestrelHttpServer/pull/485)
413 Payload Too Large https://github.com/aspnet/KestrelHttpServer/issues/478
414 URI Too Long / 431 Request Header Fields Too Large https://github.com/aspnet/KestrelHttpServer/issues/475

**Comment by muratg** [comment]
This will partially be covered by @cesarbs's other assigned items

**Comment by cesarbs** [comment]
@muratg I'll actually do those changes first and then work on this one.
