### ISSUE TITLE
Get tests working on Travis / Linux

### ISSUE THREAD

**Issue by dougbu** [aspnet/KestrelHttpServer#654]
Kestrel builds have been erroring or failing consistently on Travis for a while. Looks like the last successful Travis run was 20 days ago. (Admittedly, that span may include runs where Linux succeeded but OS X failed.)

Current failures appear limited to `FunctionalTests.AddressRegistrationTests.RegisterAddresses_IPv6_Success` (3 variants) and `FunctionalTests.RequestTests.RemoteIPv6Address`. No cause is obvious though these may be the only tests using IPv6.

See failures in https://travis-ci.org/aspnet/KestrelHttpServer/builds/111586273 for example.

**Comment by benaadams** [comment]
Is a `Fact` test that should be a `ConditionalFact` these were the issues (and fixes) for what I saw https://github.com/aspnet/KestrelHttpServer/pull/648

**Comment by dougbu** [comment]
Good point @benaadams Looks like a quick fix. So I'm self-assigning.

**Comment by dougbu** [comment]
3705551
