### ISSUE TITLE
Serving static files by default?

### ISSUE THREAD

**Issue by iamthemovie** [aspnet/KestrelHttpServer#66]
I've just been looking into serving some JS with Kestrel. I'm going to assume that I'll need to write a static asset middleware handler? Is there something built in already? I can't see anything.

**Comment by iamthemovie** [comment]
Ahh I see. UseStaticFiles dependency in AspNet. http://forums.asp.net/t/2023148.aspx?vNext+webroot+files+not+available+when+using+WebListener+Kestrel

**Comment by Eilon** [comment]
Indeed, the Kestrel web server (much like WebListener, but unlike IIS) has effectively no features or functionality on its own. You need to add middleware such as the Static File middleware to have it do anything useful. This way you know exactly what it does and don't have to go turn off all kinds of features you don't want.

**Comment by iamthemovie** [comment]
I wish there was a like button on github issue comments...
