### ISSUE TITLE
RemoteIpAddress is not set by Kestrel

### ISSUE THREAD

**Issue by borgdylan** [aspnet/KestrelHttpServer#67]
Currently, getting the IP address for a request when running on Kestrel yields nothing instead of the remote client's IP.

**Comment by borgdylan** [comment]
I have been working on thsi and will open a PR. @loudej @lodejard

**Comment by troydai** [comment]
The change is nearly done. But we need more tests on various platform to ensure the quality. Move to 1.0.0-rc2.

**Comment by troydai** [comment]
Finished in e9a60610236c53e9518fe80ccf75f14b7e5d02f8
