### ISSUE TITLE
Use IOCP on secondary Windows threads

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#679]
@geoffkizer did some perf analysis and discovered that Kestrel's secondary threads weren't using IOCP on Windows. I [brought this up on the libuv mailing list](https://groups.google.com/forum/#!topic/libuv/5DAW1hViw0Q). Here is an excerpt of what I wrote:

> After doing some profiling, we noticed that the connections accepted on the duplicated socket on the secondary threads are using event handles instead of IOCP for async completion on windows, e.g.:

    int uv_tcp_write(uv_loop_t* loop,
                     uv_write_t* req,
                     uv_tcp_t* handle,
                     const uv_buf_t bufs[],
                     unsigned int nbufs,
                     uv_write_cb cb) {
      int result;
      DWORD bytes;

      uv_req_init(loop, (uv_req_t*) req);
      req->type = UV_WRITE;
      req->handle = (uv_stream_t*) handle;
      req->cb = cb;

     

      /* Prepare the overlapped structure. */
      memset(&(req->u.io.overlapped), 0, sizeof(req->u.io.overlapped));
      if (handle->flags & UV_HANDLE_EMULATE_IOCP) {
        req->event_handle = CreateEvent(NULL, 0, 0, NULL);
        if (!req->event_handle) {
          uv_fatal_error(GetLastError(), "CreateEvent");
        }
        req->u.io.overlapped.hEvent = (HANDLE) ((ULONG_PTR) req->event_handle | 1);
        req->wait_handle = INVALID_HANDLE_VALUE;
      }

      ...

      if (handle->flags & UV_HANDLE_EMULATE_IOCP &&
            !RegisterWaitForSingleObject(&req->wait_handle,
              req->event_handle, post_write_completion, (void*) req,
              INFINITE, WT_EXECUTEINWAITTHREAD | WT_EXECUTEONLYONCE)) {
          SET_REQ_ERROR(req, GetLastError());
          uv_insert_pending_req(loop, (uv_req_t*)req);
      }

> This seems to occur because we accept the socket on both the primary loop and secondary loop. The first call to uv_tcp_accept associates the socket with the primary loop's completion port which causes the second call to CreateIoCompletionPort (via uv_pipe_accept->uv_tcp_import) to fail on the duplicated socket on the secondary thread. This sequence of events is what causes the UV_HANDLE_EMULATE_IOCP flag to be set.

    static int uv_tcp_set_socket(uv_loop_t* loop,
                                 uv_tcp_t* handle,
                                 SOCKET socket,
                                 int family,
                                 int imported) {

    ...

      /* Associate it with the I/O completion port. */
      /* Use uv_handle_t pointer as completion key. */
      if (CreateIoCompletionPort((HANDLE)socket,
                                 loop->iocp,
                                 (ULONG_PTR)socket,
                                 0) == NULL) {
        if (imported) {
          handle->flags |= UV_HANDLE_EMULATE_IOCP;
        } else {
          return GetLastError();
        }
      }

#602 Was the first attempt to fix this issue, but it wasn't using libuv as intended and we are concerned that such off-label usage might break things now or in the future in subtle ways. In the mailing list it was suggested that we could use `FileReplaceCompletionInformation` to detach the socket from the primary loop's IOCP, but that API is only available on Windows 8.1 and above.

**Comment by benaadams** [comment]
> but that API is only available on Windows 8.1 and above.

Also Windows Server 2012 R2

**Comment by moozzyk** [comment]
Fixed in 75adbc18a2b6fda212322e3068b6e9f99d64cdd8
