### ISSUE TITLE
White screen of death on error

### ISSUE THREAD

**Issue by juzzbott** [aspnet/KestrelHttpServer#69]
Hi, 

I'm trying to develop an asp.net 5 website using Mono and Kestrel development server. When the website compiles properly, I'm able to load the website without any dramas on the local development port after launching `k kestrel`

However, if there is an error with my .cshtml view file (referencing wrong model), or even something as simple as a null reference exception error, the Kestrel web server just returns a white screen of death, without any explanation to the cause of the error, either on the webpage (like the traditional asp.net yellow error pages) or within the terminal running Kestrel. 

Is there any way that I can determine what is causing the error? The null reference exceptions aren't too bad, by I'm unable to determine the error within my view. 

Cheers, 
Justin

**Comment by davidfowl** [comment]
By design. If you want to see errors, then use the Diagnostics middleware https://github.com/aspnet/Diagnostics/blob/dev/samples/ErrorPageSample/Startup.cs#L10

**Comment by juzzbott** [comment]
Thanks for the info, makes sense :)
