### ISSUE TITLE
New ChunkedRequestTests.TrailingHeadersAreParsed failure

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#693]
Investigate:

    Microsoft.AspNetCore.Server.KestrelTests.ChunkedRequestTests.TrailingHeadersAreParsed(testContext: TestServiceContext { App = null, AppLifetime = LifetimeNotImplemented { ApplicationStarted = (throws NotImplementedException), ApplicationStopped = (throws NotImplementedException), ApplicationStopping = (throws NotImplementedException) }, DateHeaderValueManager = TestDateHeaderValueManager { }, FrameFactory = null, Log = TestKestrelTrace { }, ... }) [FAIL]
      Assert.Equal() Failure
                                       ↓ (pos 209)
      Expected: ···Hello WorldHTTP/1.1 200 OK\r\nContent-Length: 11\r\n\r\nHello World···
      Actual:   ···Hello WorldHTTP/1.1 400 Bad Request\r\nDate: Sun, 13 Mar 2016 0···
                                       ↑ (pos 209)
      Stack Trace:
           at Microsoft.AspNetCore.Server.KestrelTests.TestConnection.<Receive>d__8.MoveNext()

**Comment by cesarbs** [comment]
Seen on Windows and Mac. Haven't tried on Linux.

**Comment by cesarbs** [comment]
Same test was failing on #672.

**Comment by halter73** [comment]
Can you link to a Travis/AppVeyor test run were it failed in this way?

**Comment by cesarbs** [comment]
https://ci.appveyor.com/project/aspnetci/kestrelhttpserver/build/1.0.2478

**Comment by cesarbs** [comment]
Not seeing this anymore.
