### ISSUE TITLE
Allocations of Frame(Request|Response)Headers

### ISSUE THREAD

**Issue by rynowak** [aspnet/KestrelHttpServer#695]
These allocs started showing up recently and it's a bit suspicious

![image](https://cloud.githubusercontent.com/assets/1430011/13750415/97fd42bc-e9c2-11e5-924e-1818800c255a.png)

This is only 3002 requests being profiled, notice that these counts are twice that.

**Comment by benaadams** [comment]
by design see: https://github.com/aspnet/Performance/tree/dev/testapp/PooledKestrel to get rid of them

**Comment by benaadams** [comment]
e.g. is controlled by config setting

**Comment by benaadams** [comment]
e.g. is controlled by config setting

A lot of proxy/gateways re-use the connections for different requests from their clients; so a kestrel connection is not necessarily unique to a "into gateway" connection; so the connection can be shared between users - so a mechanism to control some of what is reused on the connection has been introduced; headers being one of these.

**Comment by benaadams** [comment]
Exact PR is https://github.com/aspnet/KestrelHttpServer/pull/608

**Comment by rynowak** [comment]
So why does that result in 2 allocations of `FrameRequestHeaders` per request?

**Comment by benaadams** [comment]
Ahh, fair point; let me look

**Comment by rynowak** [comment]
Any updates here? this is a pretty significant source of allocations

**Comment by benaadams** [comment]
Doing some Build stuff atm, will have to wait till next week for me to look at it - that work for you?

**Comment by rynowak** [comment]
> Doing some Build stuff atm, will have to wait till next week for me to look at it - that work for you?

It would be great to have your help, but I'm sure there are other people who can investigate as well :sunglasses: 

@muratg - possible to have someone look at this for RC2?

**Comment by muratg** [comment]
@mikeharder Do you have some time to look into this?
