### ISSUE TITLE
Make Kestrel work automatically when installed into a .csproj project

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#696]
Right now Kestrel breaks when used from a classic .NET project using MSBuild, because libuv.dll is not automatically copied to the build's output directory. This can be worked around by manually adding libuv to the referencing project and configuring it to be copied. [NuGet can do this for us though](https://docs.nuget.org/release-notes/nuget-2.5#automatic-import-of-msbuild-targets-and-props-files).

@natemcmaster pointed out that [Microsoft.Data.Sqlite already does this](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/6a3d31d68f2da69b2561643bfec978847a4d5a5e/src/Microsoft.Data.Sqlite/build/net451/Microsoft.Data.Sqlite.props).

**Comment by halter73** [comment]
@bricelam Does .NET automatically load DLLs from `./x86/` or `./x64/` based on the bitness of the loading process?

**Comment by natemcmaster** [comment]
NB you'll need to manually find libuv.dll as we do in SQLite. https://github.com/aspnet/Microsoft.Data.Sqlite/blob/6a3d31d68f2da69b2561643bfec978847a4d5a5e/src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs#L52

**Comment by halter73** [comment]
Oh... That explains why the subfolder thing works. Kestrel used to do manually load libuv.dll/so/dylib, but we really want to avoid that.

`#if NET451` doesn't seem to be the perfect condition for calling `NativeLibraryLoader.TryLoad` since it can still be true for non-msbuild projects. I guess that's why there's the `IsLoaded()` check. This definitely seems like a hack.

Do you know of any NuGet issues to better support this scenario?

**Comment by natemcmaster** [comment]
> #if NET451 doesn't seem to be the perfect condition for calling NativeLibraryLoader.TryLoad since it can still be true for non-msbuild projects.

I believe this is why the include is conditional on "project.json".
```xml
 <ItemGroup Condition="!Exists('$(MSBuildProjectName).project.json') And !Exists('project.json')">
```

> Do you know of any NuGet issues to better support this scenario?

Not AFAIK

**Comment by moozzyk** [comment]
I guess this is similar to what SignalR-Client-Cpp does: https://github.com/aspnet/SignalR-Client-Cpp/blob/dev/NuGet/Microsoft.AspNet.SignalR.Client.Cpp.WinDesktop.targets.template#L45-L46

**Comment by natemcmaster** [comment]
In the meantime, users can workaround this manually using MSBuild. Here is the snipping in my csproj:

```xml
    <Reference Include="Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AspNetCore.Server.Kestrel.1.0.0-rc2-20202\lib\net451\Microsoft.AspNetCore.Server.Kestrel.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Content Include="..\..\packages\Microsoft.AspNetCore.Server.Kestrel.1.0.0-rc2-20202\runtimes\win7-x86\native\*" Condition="'$(Platform)' == 'x86'">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
    </Content>
    <Content Include="..\..\packages\Microsoft.AspNetCore.Server.Kestrel.1.0.0-rc2-20202\runtimes\win7-x64\native\*" Condition="'$(Platform)' == 'x64'">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Visible>False</Visible>
    </Content>
```

**Comment by mburumaxwell** [comment]
@natemcmaster Is there a similar workaround for a situation where a csproj uses `project.json` for nuget references?

**Comment by halter73** [comment]
I imagine you could still add `<Content Include=`. The issue is you have to find a way to reliably reference the nuget packages folder. With `project.json` that's usually `~/.nuget/packages`.

**Comment by muratg** [comment]
MSBuild migration in the overall ecosystem will fix this

**Comment by springy76** [comment]
When? In the year 2099? 1.1 was announced weeks ago and the tooling (=SDK) still does not do what is announced in the blog posts (get rid of project.json etc.).

**Comment by bricelam** [comment]
SDK | Runtime | project.json | MSBuild
--- | ------ | ------------ | -------
preview2 | 1.0 | ✔️ | ❌
preview2.1 | 1.1 | ✔️ | ❌
preview3 | 1.0 | ❌ | ✔️
