### ISSUE TITLE
Establish which ipv4/ipv6 socket addresses to open

### ISSUE THREAD

**Issue by lodejard** [aspnet/KestrelHttpServer#7]
Assumption is localhost should be ipv4+ipv6 loopback, numeric addresses should be that address in ipv4 or ipv6, and any other name including + and * should be ipv4+ipv6 any ip

**Comment by Eilon** [comment]
This is a super old bug but it was in the alpha4 milestone, so moving to RC1 to reevaluate.

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/KestrelHttpServer/issues/231

**Comment by stevedesmond-ca** [comment]
this and aspnet/Announcements#80 have the milestone as rc1, but based on the description of aspnet/Announcements#80, should they be beta8 instead / in addition?

**Comment by Eilon** [comment]
@Tratcher ?

**Comment by Tratcher** [comment]
Updated. The initial change was in beta8: https://github.com/aspnet/KestrelHttpServer/commit/f0137b7b9ea25ee4769931da1e8d255a47605e85

**Comment by guyajun0** [comment]
var remoteIp = context.Connection.RemoteIpAddress.ToString();
why it is always null after I upgrade it from beta7 to beta8? Thank you!

**Comment by guyajun0** [comment]
I Used asp.net 5, VS beta8 and dnx beta8 get null remote ip, when I use dnx beta7,it is ok to get the remote ip address,I am confused.
