### ISSUE TITLE
How to exit?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/KestrelHttpServer#70]
Other than doing `kill` of course. Ctrl+C doesn't do anything.

**Comment by davidfowl** [comment]
hit enter

**Comment by davidfowl** [comment]
You might be running into #9

**Comment by Daniel15** [comment]
Oh, got it! Hitting enter //does// work to quit. Pressing Ctrl+C puts it into a hung state where pressing enter doesn't work, and the next HTTP request kills it (as someone mentioned on #9)
