### ISSUE TITLE
Reliability: NullReferenceException - Linux-HelloWorldMVC crash after few hours of test run.

### ISSUE THREAD

**Issue by sivagms** [aspnet/KestrelHttpServer#707]
HelloWorldMVC App |||
-------------------|------------------------|--------------------------------------
 Azure A2 VM | 80% CPU Usage | 300 concurrent connections 

5 hours of into the reliability test run  The app crashes. 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.ReturnAllBlocks()
   at Microsoft.AspNetCore.Server.Kestrel.Http.SocketOutput.WriteContext.DoDisconnectIfNeeded()
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvShutdownReq.UvShutdownCb(IntPtr ptr, Int32 status)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.run(UvLoopHandle handle, Int32 mode)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
```

**Comment by cesarbs** [comment]
How could I run the test myself? I don't think this would happen exclusively on Linux. If we can repro on Windows it will be much easier to debug.

**Comment by sivagms** [comment]
Not sure why, but this doesn't repro on Windows.  
On Linux, Run HelloWorldMVC for more that 8 hours and you'll see the crash..

**Comment by sivagms** [comment]
This seems to be showing up when running on WorkStation GC

**Comment by muratg** [comment]
@sivagms Let us know if it repros with server GC.

**Comment by RussKeldorph** [comment]
@muratg @sivagms @cesarbs It's conceivable that this is the same issue as #723, for which @llitchev has a fix.  If you guys have a consistent repro and can take a private coreclr binary to try, we can provide one.  This would be to done to mitigate the high latency in getting fixes through the pipeline.  However, if it's too hard to test with a private, nevermind.

**Comment by sivagms** [comment]
@RussKeldorph  Please send me the private binary and instructions to use. I can try it if I see this issue again in tonight's test run

**Comment by RussKeldorph** [comment]
@llitchev Could you share out the binaries and work with @sivagms, etc. to see if your fix suppresses the repro?

**Comment by LLITCHEV** [comment]
@RussKeldorph Sure. Taking it offline.

**Comment by halter73** [comment]
@sivagms Have we seen this since #723 was closed? If so, can we get a memory dump? Thanks.

**Comment by muratg** [comment]
Putting this to 1.0.1.

**Comment by muratg** [comment]
Closing this one. If we still get a repro, please re-open.
