### ISSUE TITLE
Dealing with OPTIONS * requests

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#709]
Today Kestrel will take the \* from an OPTIONS \* request and put it in the Path. However, \* isn't a path and PathString throws.

When Kestrel sees a lone \* in the request line it should leave both Path and PathBase empty.

https://github.com/aspnet/ServerTests/issues/20#issuecomment-200049192

**Comment by muratg** [comment]
Per triage meeting, this was done.
