### ISSUE TITLE
Running in Production?

### ISSUE THREAD

**Issue by markrendle** [aspnet/KestrelHttpServer#71]
I suspect this may be a can of worms I'm opening, but I'll start with a simple question:

Is Kestrel the planned long-term solution for running applications on Linux in production?

**Comment by davidfowl** [comment]
Yep! We'll likely recommend running behind a reverse proxy like ngnix.

**Comment by markrendle** [comment]
Cool, I'm actually doing that already on a prototype-stage project.

Right, follow-up question in a new issue, then.
