### ISSUE TITLE
Consider adding UseKestrel extension method to IWebHostBuilder

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#713]
A comment from @NickCraver here https://github.com/aspnet/IISIntegration/issues/105#issuecomment-201623725. It would be nice if we started to follow this pattern. It would allow servers to expose strongly typed extension methods (similar to our middleware pattern).

**Comment by ArieJones** [comment]
+1 on this as it does feel very unnatural passing a string to .UseServer()

**Comment by Tratcher** [comment]
Do it.

Should there also be an overload that takes some ketrel Options / configureOptions and registers them in DI so they can be injected into the ServerFactory? Most of IKestrelServerInformation would qualify.

**Comment by davidfowl** [comment]
@Tratcher I was thinking about that as well. It would be a cleaner way to configure the server settings.

```C#
var host = new WebHostBuilder()
    .UseKestrel()
    .UseStartup<StartupHelloWorld>()
    .Build();

host.Run();
```

```C#
var host = new WebHostBuilder()
    .UseKestrel(options =>
     {
         options.NoDelay = true;
         options.ThreadCount = 4;
         options.UseKestrelHttps(...);
     })
    .UseStartup<StartupHelloWorld>()
    .Build();

host.Run();
```

**Comment by smbecker** [comment]
Isn't options.UseKestrelHttps redundant since you are inside the UseKestrel configure block?

**Comment by davidfowl** [comment]
@smbecker Fixed

**Comment by Eilon** [comment]
Looks nice to me.

**Comment by davidfowl** [comment]
We should also remove these as a result of this:

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsApplicationBuilderExtensions.cs

It clears up the fact that these aren't actually pieces of middleware but server configuration.

**Comment by muratg** [comment]
Putting it optimistically in RC2.

**Comment by smbecker** [comment]
Should this issue be closed yet since the pull request that was merged only included the no-args extension method and didn't include the configure options overload?

**Comment by mikeharder** [comment]
You're correct.  Leaving open for the options overload.

**Comment by mikeharder** [comment]
Created #720 to track configure options overload, and closing this issue.
