### ISSUE TITLE
k kestrel --verbose/debug

### ISSUE THREAD

**Issue by ricardoalcantara** [aspnet/KestrelHttpServer#72]
Hi I am creating a experimental website with most of the complexities I would use on my real world website, It runs on windows okay with Kestrel but on linux after I post the page nothing happens and I would like to see or debug this error. Does someone know how could I do it?

**Comment by markrendle** [comment]
I use a combination of Logging and a request-tracing middleware to output debug information on Linux, with an environment variable setting to turn it on in development.

**Comment by ricardoalcantara** [comment]
I tried to log something but when I Request POST the connection gets closed and I receive only one header: Connection: close. Seems like nothing is happening for some internal error.

**Comment by Tragetaschen** [comment]
Is it aspnet/HttpAbstractions#168?
I have to start ASP.NET 5 with `TEMP=something …` for POST requests to work.

Did you already activate the error page `app.UseErrorPage(…)`?

**Comment by ricardoalcantara** [comment]
Thank you very much @Tragetaschen , this TEMP situation was my problem about the POST request. And also I hadn't activated the app.UseErrorPage(), it was what I wanted about the 'debug/verbose'.

**Comment by felipepaixao** [comment]
hi @ricardoalcantara , could you please explain how do you set the Temporary folder?
I'm having trouble when my application is trying to access the default temporary folder on Lnux.

**Comment by Tragetaschen** [comment]
`TEMP=/tmp sh kestrel`
