### ISSUE TITLE
Add IWebHostBuilder.UseKestrel(options) overload to configure Kestrel

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#720]
Copied from #713:

```C#
var host = new WebHostBuilder()
    .UseKestrel(options =>
     {
         options.NoDelay = true;
         options.ThreadCount = 4;
         options.UseHttps(...);
     })
    .UseStartup<StartupHelloWorld>()
    .Build();

host.Run();
```

We should also remove these as a result of this:

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsApplicationBuilderExtensions.cs

It clears up the fact that these aren't actually pieces of middleware but server configuration.

**Comment by DamianEdwards** [comment]
YES PLS RIGHT NOW LOVE IT :shipit:

**Comment by davidfowl** [comment]
I did a test implementation and there are some problems around extension methods that require resolved services to configure. `UseConnectionLogging()` requires an `ILoggerFactory`and `UseHttps()` and requires the base path to the x509cert.

**Comment by davidfowl** [comment]
Kestrel
- Add `KestrelServerOptions` and remove `KestrelServerInformation`
- Remove `KestrelServerInformation` from server features
- Add `IServiceProvider` to `KestrelServerOptions`
- Change UseKestrel() to add the IServerFactory to the container directly
- Add `UseKestrel(Action<KestrelServerOptions>)` which adds 
- Change connection filter extension methods to extension methods on `KestrelServerOptions`
