### ISSUE TITLE
502 when hosting a managed WebApi site in IIS as a sub-app under a unmanaged site running on kestrel

### ISSUE THREAD

**Issue by larswise** [aspnet/KestrelHttpServer#724]
When hosting a asp.net mvc 6 site in iis, running kestrel, with a sub app below running in managed mode the sub app fails with a 502 - Web server received an invalid response while acting as a gateway or proxy server. 

Structure:
Default Web site -> (SubApp) ASPNETMVC6/Kestrel, Unmanaged -> (SubSubApp) WebApi .NET 4.6 Managed

Don't know if this is by design but this setup works when all app-pools are managed.
I moved the WebApi alongside with the ASP.NET MVC6 site like this

Default Web site -> ASPNETMVC6/Kestrel, Unmanaged
Default Web site -> WebApi .NET 4.6 Managed

And it worked.
Not sure why this happened but I would suspect kestrel?

IIS 8
Microsoft.AspNet.Server.Kestrel 1.0.0-rc1-final
Windows Server 2012 R2

**Comment by larswise** [comment]
<system.webServer>
    <handlers>
      <remove name="httpPlatformHandler"/>
on the webapi site did not seem to solve it.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/IISIntegration#113
