### ISSUE TITLE
Remove the thread.Abort on the kestrel thread

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#725]
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Infrastructure/KestrelThread.cs#L120

We should try to avoid different behavior on .NET Core vs .NET Framework where possible. What happens on .NET Core when the timeout elapses and the UV thread still hasn't stopped running?

/cc @halter73 @cesarbs

**Comment by benaadams** [comment]
Meh, can just drop these; the threads are background so they will just die anyway

**Comment by cesarbs** [comment]
@benaadams Agreed. I had thought something similar right when I started working on Kestrel, but thought there was an important reason for those `Abort`s

**Comment by benaadams** [comment]
@cesarbs wasn't till 19th Feb they went to background mode https://github.com/aspnet/KestrelHttpServer/pull/646

**Comment by cesarbs** [comment]
@benaadams Ah, thanks for pointing that out.
