### ISSUE TITLE
Include libuv in shared runtime instead of Kestrel packages

### ISSUE THREAD

**Issue by muratg** [aspnet/KestrelHttpServer#730]
_From @muratg on April 5, 2016 22:8_

We need to 
- Make libuv a Kestrel dependency (instead of including it IN the package)
- Include the libuv package in shared runtime.

Benefits:
- Being able to service libuv without touching Kestrel
- Clean up the kestrel dependency graph
- Simplify project-to-project references (where you have to include libuv-build package in the project currently)
- Much smaller size for Kestrel package

_Copied from original issue: aspnet/Coherence-Signed#244_

**Comment by muratg** [comment]
_From @halter73 on April 5, 2016 22:28_

@weshaggard This should be tracking the creation of the libuv package.

@muratg Is there a reason we're tracking this in a private repo? I was going to link to it from https://github.com/dotnet/cli/issues/2277

**Comment by halter73** [comment]
Sorry. Wrong issue to close. The Libuv package is now on the https://www.myget.org/F/aspnetcirelease feed, but not in the shared runtime yet.

**Comment by weshaggard** [comment]
Do we know when this is going to happen?

**Comment by muratg** [comment]
This is done.

**Comment by cesarbs** [comment]
For reference: https://github.com/dotnet/cli/issues/2277
