### ISSUE TITLE
Kestrel Content-Length GZip Bug

### ISSUE THREAD

**Issue by Maksim-Volk** [aspnet/KestrelHttpServer#733]
I'm working with SOAP service.
Client sends to server header `Accept: */*` (default on linux and not default on win).

Server sends response with:
```
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Length: 2896
```
Here comes **zipped length**.
**But kestrel server sends to client unzipped response body by it's zipped length.**
So, from real body with over 5000+ length I get only 2896.
Thus, my ASP backend gets only a part of SOAP response and fails by deserealizing it.

Server must work with GZip, its length and Content-Length header correctly.

Additional info:
**Project.json:**
```
"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final"
"frameworks": { "dnxcore50": {  } }
```

**DNVM:**
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-rc1-update2    coreclr x64          linux           default
```

**OS:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```

**Comment by davidfowl** [comment]
> Server sends response with:

> Content-Encoding: gzip
> Vary: Accept-Encoding
> Content-Length: 2896

Who is doing the gzipping? Can you make a repro project and put it on github?

**Comment by Maksim-Volk** [comment]
> Can you make a repro project and put it on github?

Sorry, I can't share my project for security reasons.

> Who is doing the gzipping?

Datasource vendor's server sends the response with gzipped message body.

Here are other headers from it:

```
HTTP/1.1 200 OK
Cache-Control: no-store
Content-Type: application/soap+xml; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Content-Length: 2896
```

As **temporary workaround** I've added IClientMessageInspector.BeforeSendRequest to my WCF client and manually added header **Accept-Encoding: identity** to request.
But It's not acceptable for a long period of time.

**Comment by smbecker** [comment]
Maybe some background about what your trying to do or what your environment looks like would help? Are you fetching a SOAP response from a 3rd-party server and then using Kestrel to forward that response onto your clients? If that is the case, then at some point in your pipeline, someone is un-gzipping the SOAP response from the 3rd-party server and then must not be re-gzipping the response before sending it onto your clients.

**Comment by halter73** [comment]
I think @smbecker is correct. Kestrel will not set the `Content-Length` header itself (except for to 0 sometimes), and it will not do any response/request decompression.

**Comment by Maksim-Volk** [comment]
I'm using ASP 5 solution running on Kestrel for consuming SOAP, process it and send the final response to clients.

Kestrel is not sending `Content-Length`, it can't understand it correctly.

> it will not do any response/request decompression

Then who does? SOAP server (IIS) sends GZipped response and my ASP application can't understand it because of GZip.

**Comment by davidfowl** [comment]
> Then who does? SOAP server (IIS) sends GZipped response and my ASP application can't understand it because of GZip.

The application needs to do it. As in, some component configured in the pipeline needs to do it. Kestrel does not decompress anything.

**Comment by Maksim-Volk** [comment]
> The application needs to do it. As in, some component configured in the pipeline needs to do it. Kestrel does not decompress anything.

OK, can you please redirect me? Where can I get answer for this? 
Maybe `System.ServiceModel.ClientBase` is the problem point?
I can't even catch response by using `IClientMessageInspector.AfterReceiveReply`, it fails before that.

**Comment by rvfernandes** [comment]
As you are making the call to your SOAP server? If you are using System.Net.Http.HttpClient  use parameter AutomaticDecompression = DecompressionMethods.None

var handler = new HttpClientHandler
{
    AutomaticDecompression = DecompressionMethods.None,
};
var client = new HttpClient (handler);

**Comment by Maksim-Volk** [comment]
No, SOAP server is not mine. 
I'm generatign proxy using [this extension](https://blogs.msdn.microsoft.com/webdev/2015/12/15/wcf-connected-service-visual-studio-extension-preview-for-asp-net-5-projects/)

Them I'm creating `System.ServiceModel.ClientBase<IClientChannel>` instance and making calls to SOAP.

I want to find a solution with correct work with GZip:
- any server can use GZip, and app must work with it
- gzip shorts data amount sent through network

**Comment by Maksim-Volk** [comment]
Fixed in RC2
