### ISSUE TITLE
Only for development?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/KestrelHttpServer#74]
The readme refers to Kestrel as a "development web server". Does this mean it wouldn't be appropriate for a production site? Currently I'm running ASP.NET MVC 4 + Nginx + Mono FastCGI, will Kestrel take the place of Mono FastCGI or will there be another type of server for production scenarios?

**Comment by akoeplinger** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/71

**Comment by Daniel15** [comment]
Thank you @akoeplinger!
