### ISSUE TITLE
Change LoggingThreadPool to run actions that take a state argument

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#740]
Right now it only runs `Action`, we should run `Action<T>` to prevent creating closures in places like https://github.com/aspnet/KestrelHttpServer/blob/7b6384635796d99bdb74ba24d80dbdc50731fd5e/src/Microsoft.AspNetCore.Server.Kestrel/Http/Connection.cs#L157

**Comment by benaadams** [comment]
Issue is it already takes a object as parameter which is the logger :cry:

**Comment by cesarbs** [comment]
I'm thinking of closing this. Not worth the time investment. The closure is not created on a critical code path so there's no perf impact.

cc @muratg @halter73 @mikeharder @davidfowl

**Comment by davidfowl** [comment]
Sounds fine to me

**Comment by muratg** [comment]
:+1:

**Comment by benaadams** [comment]
ofc could always have an event on the threadpool that could be listened to rather than crashing the process, then it would free up the slot https://github.com/dotnet/coreclr/issues/2144
