### ISSUE TITLE
Add doc comments for HttpsApplicationBuilderExtensions.UseKestrelHttps() methods.

### ISSUE THREAD

**Issue by Eilon** [aspnet/KestrelHttpServer#743]
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel.Https/HttpsApplicationBuilderExtensions.cs

**Comment by Tratcher** [comment]
@mikeharder You're re-doing these right now anyways... https://github.com/aspnet/KestrelHttpServer/issues/720
