### ISSUE TITLE
Kestrel configuration changes

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#752]
We have introduced changes to simplify configuration of the Kestrel web server:
- `KestrelServerInformation` has been replaced by `KestrelServerOptions`.
  - `KestrelServerPoolingParameters` properties have been moved to `KestrelServerOptions`.
- `IWebHostBuilder.UseKestrel()` should be used instead of `IWebHostBuilder.UseServer(“Microsoft.AspNetCore.Server.Kestrel”)`.
  - Overload `UseKestrel(Action<KestrelServerOptions>)` allows you to configure Kestrel when configuring the `WebHostBuilder`.
- `IApplicationBuilder.UseKestrelHttps()` has been replaced by `KestrelServerOptions.UseHttps()`.
  - Overloads `UseHttps(string fileName)` and `UseHttps(string fileName, string password)` allow you to directly specify the name of a certificate file plus an optional password.
- `IApplicationBuilder.UseKestrelConnectionLogging()` has been replaced by `KestrelServerOptions.UseConnectionLogging()`.
- Kestrel options are no longer read from hosting config.

Here is an example of the previous way to configure Kestrel:

``` csharp
public static void Main()
{
    var host = new WebHostBuilder()
        .UseServer("Microsoft.AspNetCore.Server.Kestrel")
        ...
}

public void Configure(IApplicationBuilder app)
{
    app.ServerFeatures.Get<IKestrelServerInformation>().ThreadCount = 4;
    app.UseKestrelHttps(new X509Certificate2(...));
    app.UseKestrelConnectionLogging();
}
```

Here is the same configuration expressed in the new way:

``` csharp
public static void Main()
{
    var host = new WebHostBuilder()
        .UseKestrel(options => {
            options.ThreadCount = 4;
            options.UseHttps(new X509Certificate2(...));
            options.UseConnectionLogging();
        })
        ...
}
```

You can also modify the KestrelServerOptions in ConfigureServices():

``` csharp
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<KestrelServerOptions>(options =>
    {
        options.ThreadCount = 4;
        options.UseHttps(new X509Certificate2(...));
        options.UseConnectionLogging();
    });
}
```

See aspnet/KestrelHttpServer#1234 for discussion.

**Comment by MegaMax93** [comment]
How can I set the URL in RC2, where the web host will listen on? Like in [this](https://github.com/aspnet/KestrelHttpServer/issues/639) issue.

I need to specifiy different ports, because I have two ASP.NET RC2 services in one Service Fabric application. When I deploy the services, I got a `Error -4091 EADDRINUSE address already in use` exception.
Unfortunately I was not able to find the change, that was made in RC2.

**Comment by moozzyk** [comment]
if you have code like this: 
```
public static void Main(string[] args)
{
    var config = new ConfigurationBuilder().AddCommandLine(args).Build();
     var host = new WebHostBuilder()
                     .UseConfiguration(config)
...
```
you can pass your url(s) as an application arguments --server.urls

Alternatively you can specify urls in your hosting.json and add this line:

```
 .AddJsonFile("hosting.json", optional: true)
``` 
when building the host.

**Comment by benaadams** [comment]
@MegaMax93 also programmaticly with `.UseUrls`
```csharp
var host = new WebHostBuilder()
    .UseKestrel()
    .UseUrls("http://*:8181")
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseIISIntegration()
    .UseStartup<Startup>()
    .Build();
```

**Comment by MegaMax93** [comment]
Thanks to all for your quickly support.
I had a configuration typo in my parameter configuration files for the deployment (`Local.xml`), what caused a multiple creation of web hosts on the same location. So, even when I did changed the URL via `.UseConfiguration(config)` or `.UseUrls("http://*:8181")`, Service Fabric tried to create multiple instances on my machine. But it's good to know about having this possibilities in Kestrel.

Thank you again and sorry for the inconvenience.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
