### ISSUE TITLE
Remove first class pooling support from KestrelOptions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#754]
- Remove first class support for pooling parameters in `KestrelOptions`
- Expose `IHttpComponentFactory` as something that can be configured from the outside
- Remove `IHttpComponentFactory` from server features

We should decide if we want to add `IHttpComponentFactory` as part of `KestrelOptions` or have it be a service in the DI container.

**Comment by benaadams** [comment]
With the new Options is it possible to add extension methods that add to the config options?

**Comment by benaadams** [comment]
Go generic?

```csharp
interface IComponentFactory<T>
{
   T CreateComponent();
   void DisposeComponent(T component);
}
```

Not sure how the init params would work; maybe


```csharp
interface IComponentFactory<T, TInit>
{
   T CreateComponent(TInit init);
   void DisposeComponent(T component);
}
```

**Comment by davidfowl** [comment]
Nope, too generic is always bad. That looks like a generic `IFactory<T>` thats trying to replace `new()`

**Comment by muratg** [comment]
@DamianEdwards @Eilon 

If we decide to do this, we'll need to do design and make the changes in RC2. Thoughts?

**Comment by DamianEdwards** [comment]
@davidfowl can you provide some more detail here? As it stands, this doesn't seem like a an area that will be exposed enough to warrant making this change now, i.e. if we change it RTM we're going to break hardly anybody as almost nobody will set this option on `KestrelOptions`.

**Comment by benaadams** [comment]
Hardly anybody... :stuck_out_tongue_winking_eye:

**Comment by benaadams** [comment]
Related: #780

**Comment by benaadams** [comment]
Resolved by  #815 ?

**Comment by cesarbs** [comment]
@benaadams Did you reference the right PR?

**Comment by benaadams** [comment]
@cesarbs lol no, should be https://github.com/aspnet/KestrelHttpServer/pull/791
