### ISSUE TITLE
Random Port is not updated

### ISSUE THREAD

**Issue by brunolauze** [aspnet/KestrelHttpServer#758]
**dotnet run -c Release -- --server.urls=http://*:0**

In the context where we want to fire kestrel with a random port ; where consul or others will receive registration and update load balancing according to new process/port.

the command above is working, and we know Tcp Listener created with port 0 will get a random usable port from the kernel on any operating system. Win32, Linux and BSD

But still Kestrel doesn't check the assigned port and lies in the output.

PS D:\dev\n3.acronyms\ui\web\home> dotnet run -c Release -- --server.urls=http://*:0
Project N3.Acronyms.UI.Web.Home (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
Hosting environment: Production
Content root path: D:\dev\n3.acronyms\ui\web\home

**Now listening on: http://*:0**

Application started. Press Ctrl+C to shut down.
Application started. Press Ctrl+C to shut down.

Where we should have seen the new port assigned:

**Now listening on: http://*:19246**

I am asking either to fix this error or report a correct way to assign free random port in Kestrel.

**Comment by ayende** [comment]
+1 o that, this is something that we would need for running tests
