### ISSUE TITLE
Error 502 Uploading files randomly

### ISSUE THREAD

**Issue by chemitaxis** [aspnet/KestrelHttpServer#759]
Hi, I'm trying to upload images using AJAX to my Web App deployed in Azure. Randomly, I get an error 502. I have tested many times using my IIS Express on VS2015 Update 2 without errors.

For more information, I upload a Data64 string... in a DTO, no form files included in my POST.

I'm using ASP.NET Core RC1.

Thanks!!

**Comment by mikeharder** [comment]
As @jiberan noted at https://github.com/aspnet/KestrelHttpServer/issues/520#issuecomment-212571504, we believe this may be fixed by commit 5435a45397bbbef34ea253dc156655a816dfbf39 in  #642.  Can you please try with a recent RC2 build?

**Comment by chemitaxis** [comment]
Thanks @mikeharder Can you please give me a link of how to upgrade to RC2? :)

**Comment by cesarbs** [comment]
@chemitaxis You need to use the `aspnetrelease` feed:

    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetrelease/api/v3/index.json" />

Are you using `-*` versions in `project.json`?

A lot has changed, you'll have to update your code to use new APIs, etc.

**Comment by chemitaxis** [comment]
In some cases yes, I use -*, but in others I specific the version like this:
"Microsoft.AspNet.DataProtection.Extensions": "1.0.0-rc1-final",

Where I need to add the code? Is RC2 stable? Thank you so much!

**Comment by cesarbs** [comment]
You'll have to switch to `-*` versions. RC2 hasn't been released yet and there are still changes coming in.

**Comment by chemitaxis** [comment]
Ok, thanks for the info...

**Comment by mikeharder** [comment]
A few more suggestions:

1. Many ASP.NET repositories include samples, and you can compare the samples in the RC1 tag against the current Release branch.  For Kestrel and its dependencies, you can compare https://github.com/aspnet/KestrelHttpServer/tree/1.0.0-rc1/samples with https://github.com/aspnet/KestrelHttpServer/tree/release/samples.

2. Major changes between RC1 and RC2 should be documented as issues in the Announcements repo.  Here are the announcements for RC2: https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by chemitaxis** [comment]
Hi guys... I think the problem is other in my case.  I'm sending just a string in a DTO with a Data64 img. Not files involved in the request... Are any problem with content-length of the request? Thanks again...

**Comment by chemitaxis** [comment]
And another question... How can I fix it without upload to RC2? Any ideas? Thanks again

**Comment by cesarbs** [comment]
You'll need RC2. The RC1 bug really prevented Kestrel from reliably taking in incoming data because we were incorrectly handling 0-size reads. We were treating those as connection termination when it actually means that there's no coming data now but there will be in the future. There's no workaround.

**Comment by jiberan** [comment]
@chemitaxis or you can take RC1 source code a manually apply fix for this issue. But it might be better idea to wait to RC2 or use daily builds.

**Comment by sk29110** [comment]
Is RC2 ready? I can't seem to get get the RC2 version from changing project.json.

**Comment by cesarbs** [comment]
We've RTM'd a while ago. You can use version 1.1.0 in your dependencies.

**Comment by sk29110** [comment]
My visual studio 2015 said 1.1.0-rc2-final is not available.

![capture](https://cloud.githubusercontent.com/assets/626182/21911562/28991ffa-d8d6-11e6-8cdd-854a9846f18b.PNG)

**Comment by cesarbs** [comment]
You shouldn't be trying to use RC2 packages. Change your package versions to `"1.1.0"`.

**Comment by sk29110** [comment]
The same result. 1.0.0-rc1-final is the latest shows up with the intellisense. I am developing on VS 2015 Update 3

**Comment by cesarbs** [comment]
What's in your `NuGet.config`?

**Comment by sk29110** [comment]
I am not aware of NuGet.config. I don't see in my project.

**Comment by cesarbs** [comment]
In Visual Studio, if you go to Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources, what do you see there?

**Comment by sk29110** [comment]
The screen shot attached
![capture](https://cloud.githubusercontent.com/assets/626182/21912744/9f6873e6-d8dc-11e6-80c2-0135e3951af2.PNG)

**Comment by cesarbs** [comment]
That looks correct.

What if you ignore intellisense and just try to use version 1.1.0?

**Comment by sk29110** [comment]
I can't compile. "The dependency Microsofft.AspNet.Server.Kestrel >= 1.1.0 could not be resolved."

**Comment by cesarbs** [comment]
Can you post your `project.json` here?

**Comment by sk29110** [comment]
![capture](https://cloud.githubusercontent.com/assets/626182/21912852/8b488f94-d8dd-11e6-937e-1f6e6df056d4.PNG)

**Comment by Tratcher** [comment]
AspNetCore, not AspNet

**Comment by cesarbs** [comment]
Under `frameworks`, change `dnx451` to `net451`. Also, the `commands` section is no longer valid.

I suggest you take a look at MusicStore's (our sample app) `project.json` file: https://github.com/aspnet/MusicStore/blob/rel/1.1.0/samples/MusicStore/project.json

**Comment by sk29110** [comment]
Thanks for the tip. So there is no workaround for this 502 problem other than upgrading aspnet to aspnetcore? I was hoping I don't need to do the upgrade.

**Comment by cesarbs** [comment]
You can try 1.0.0 RTM - likely less work to upgrade your app. But you'll still have to update package names and versions, target, etc. Here's the `project.json` for MusicStore 1.0.0: https://github.com/aspnet/MusicStore/blob/1.0.0/src/MusicStore/project.json
