### ISSUE TITLE
Error -4089 EAFNOSUPPORT address family not supported on Azure App Service deployment

### ISSUE THREAD

**Issue by TsengSR** [aspnet/KestrelHttpServer#766]
I am using the rc1-update1 to deploy an application to Azure App Service (free plan for testing). 

Using dnx-clr-win-x86.1.0.0-rc1-update1. After deploying I can't connect to the url, it just times out. 

Executing web.cmd from the Azure Commandline returns

```
Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4089 EAFNOSUPPORT address family not supported
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
   at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.tcp_bind(UvTcpHandle handle, sockaddr& addr, Int32 flags)
   at Microsoft.AspNet.Server.Kestrel.Networking.UvTcpHandle.Bind(ServerAddress address)
   at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNet.Server.Kestrel.Http.Listener.<>c__DisplayClass5_0.<StartAsync>b__0(Object _)
```

Not sure what's causing it, I've tried changing the ports of kestrel and just using one url, but nothing helped.

**Comment by TsengSR** [comment]
Got it. I used http://*:8081 as port. This seems to want to bind IPv6 too which the app service instance do not seem to support. http://0.0.0.0:8081 worked though

**Comment by halter73** [comment]
Thanks for the report. This does seem like a bug semi-related to https://github.com/aspnet/KestrelHttpServer/issues/231. If we can't bind to `::` (which also binds to `0.0.0.0`), we should try binding to `0.0.0.0` explicitly in [UvTcpHandle.Bind](https://github.com/aspnet/KestrelHttpServer/blob/179b57b01f73b7b10ddce87cd0e57d196922462b/src/Microsoft.AspNetCore.Server.Kestrel/Networking/UvTcpHandle.cs#L27).

I'm glad you found a workaround for now.

**Comment by mikeharder** [comment]
I'm unable to reproduce this in either Azure App Service or self-host.

For Azure App Service, in RC2 the configuration code was changed so `UseIISIntegration()` overrides `UseUrls()` (if it is called *after*).  So applications configured with `UseUrls("http://*:5000").UseIISIntegration()` work fine in App Service, regardless of IPv6.

For self-host, I tested both Windows and Linux, and they allow you to bind to IPv6Any (`[::]`) even when IPv6 is disabled.  So applications configured with `UseUrls("http://*:5000")` should work fine in Windows and Linux with IPv6 disabled.

**Comment by xavierjohn** [comment]
I have got the same error on Azure Web App.
"Error -4089 EAFNOSUPPORT address family not supported"

Here is the startup code
`
        public static void Main(string[] args)
        {
            var whb = new WebHostBuilder();

            var environment = whb.GetSetting("environment");
            var subjectName = GetCertificateSubjectNameBasedOnEnvironment(environment);
            var certificate = GetServiceCertificate(subjectName);

            var host = whb
                .UseKestrel( options =>
                {
                    var httpsOptions = new HttpsConnectionFilterOptions();
                    httpsOptions.ServerCertificate = certificate;
                    httpsOptions.ClientCertificateMode = ClientCertificateMode.RequireCertificate;
                    httpsOptions.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
                    options.UseHttps(httpsOptions);
                })
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseUrls("https://*:4430")
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();
        }
`

**Comment by halter73** [comment]
@xavierjohn The EAFNOSUPPORT log during Azure Web App startup is a pretty benign warning indicating the the environment doesn't support IPv6, but Kestrel is still listening over IPv4.

In our upcoming patches, we plan to remove the warning since it looks pretty scary even though it's not a big deal.
