### ISSUE TITLE
Kestrel fails to run on OS X - unable to find libuv module

### ISSUE THREAD

**Issue by San7hos** [aspnet/KestrelHttpServer#767]
I am trying out asp core and it seems I have a trouble with running kestrel in RC2.

My project.json:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
        "Microsoft.AspNet.Hosting": "1.0.0-rc1-final"
    },
    "frameworks": {
        "dnx451": {},
        "dnxcore50": {}
    },
    "commands": {
        "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --server.urls http://localhost:5000"
    },
    "exclude": [
        "wwwroot",
        "node_modules"
    ]
}
```

Trying to run the web command:

> Arrakis:AndaronWebApp Santhos$ dnx web
> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found.
>  (Exception from HRESULT: 0x8007007E)
>    at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
>    at Microsoft.AspNet.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
>    at Microsoft.AspNet.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)

Looking for the libuv library:

> Arrakis:AndaronWebApp Santhos$ find ~/.dnx -name "libuv*"
> /Users/Santhos/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libuv.dylib
> /Users/Santhos/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/win10-arm/native/libuv.dll
> /Users/Santhos/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/win7-x64/native/libuv.dll
> /Users/Santhos/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/win7-x86/native/libuv.dll

I am not sure why the module is not found.

**Comment by davidfowl** [comment]
Looks like you're using RC1 not RC2 by the looks of your `project.json`. RC2 no longer works with DNX, you can look at the samples here to get going with the new .NET CLI https://github.com/aspnet/cli-samples

**Comment by San7hos** [comment]
@davidfowl Right now I have reversed all the steps that I used to install RC1, basically these two:

https://docs.asp.net/en/latest/getting-started/installing-on-mac.html
http://johnpapa.net/getting-started-with-asp-net-5-on-osx/

And I have reinstalled dotnet cli using this:

http://dotnet.github.io/getting-started/

Right now I was able to restore packages and build the project, but when I hit dotnet run I am getting a different error:

> Unhandled Exception: System.InvalidOperationException: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider)
>    at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
>    at Microsoft.AspNet.Hosting.WebApplication.Run(Type startupType, Stringrgs)
>    at Santhos.Andaron.Startup.Main(Stringrgs)

**Comment by davidfowl** [comment]
You should start from scratch and use the samples I posted. Then you can read the announcements to handle the breaking changes between RC1 and RC2 https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2

**Comment by San7hos** [comment]
Thanks, I think I am on the right path now. The only thing I am missing is a bit more explanation about the project file, specifically frameworks and dependencies.

From what I have learnt, netcoreapp1.0 is the new RC2 dotnet core, I am not sure though about the imports section.

I am confused about 
```
"Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
```
in the dependencies section. Is it related to the chosen framework? And what is "type"?

The goal is to strip the web application to a bare minimum for OS X. I would like to get a deeper understanding of asp core, not just "here is a sample project and have fun with asp". Maybe even write a blog post about using RC2, dotnet core and cli.

**Comment by davidfowl** [comment]
It's brand new, docs are being written, we're still making changes, when we're done there'll be lots of documentation and blog posts. 

You can look at the early stage in-progress docs here https://github.com/dotnet/core-docs/pull/391/files

**Comment by San7hos** [comment]
I know it is brand new, that is why I want to get into it. Thanks again

**Comment by davidfowl** [comment]
@San7hos Things are still changing and the Kestrel repository isn't really the place to have a conversation about the in-progress changes in RC2.
