### ISSUE TITLE
StreamSocketOutput.WriteAsync is Sync on Full framework (SSL) 

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#768]
From #569; PR #588 resolves coreclr, however full framework still has the issue.

Issue on full framework if made sync (it blocks)
![](http://aoa.blob.core.windows.net/aspnet/sslstream-async-issue.png)

Fullframework uses framework's SSL stream the corefx SSL steam only supports 

net46 (.NETFramework,Version=v4.6)
netstandard1.3 (.NETStandard,Version=v1.3)

So would currently need to version bump from v4.5.1 to use it or get the sslstream retargeted (if that would even work?)

**Comment by benaadams** [comment]
Being looked at https://github.com/dotnet/corefx/pull/7800#issuecomment-214267754

**Comment by benaadams** [comment]
See https://github.com/dotnet/corefx/issues/8358

**Comment by muratg** [comment]
Let's try this in RTM.
