### ISSUE TITLE
HttpDelete throws 404

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/KestrelHttpServer#769]
Controller:

```c#
[HttpGet]
public async Task<IActionResult> DeleteMyStuff()
{
  return View ( await _myService.LoadStuff(this) );
}

[HttpDelete]
public async Task<IActionResult> DeleteMyStuff(string namedStuff)
{
  ViewData["Message"] = "Success"; // <----------------- breakpoint

  if ( !await  _myService.DeleteMyStuff(namedStuff) )
  {
    ViewData["Message"] = "Failed";
  }

  return View ( _myService.LoadStuff(this) );
}
```

View:

```html
<p> @ViewData["Message"] </p>
<form asp-action="DeleteMyStuff">
  <input name="namedStuff" type="text" placeholder="Enter stuff name to delete" />
  <button type="submit" />
</form>
```

Never hits the `breakpoint` in controller, instead throws 404 when running app with standalone Kestrel.

Do I need to modify `web.config` for Kestrel too to make it work:

```xml
<add name="httpplatformhandler"
     path="*"
     verb="*"
     modules="httpPlatformHandler"
     resourceType="Unspecified" />
```
? If so, why can't we have `HttpDelete` and `HttpPut` out of the box enabled in this modern age?

**Comment by moozzyk** [comment]
Kestrel does not read web.config. It's only meant for IIS.

**Comment by jasonwilliams200OK** [comment]
So does this mean this is actually a bug in kestrel?

**Comment by Tratcher** [comment]
I doubt this is related to Kestrel, Kestrel does not consider the Method. I suspect this is an MVC issue.

**Comment by jasonwilliams200OK** [comment]
@Tratcher, I think https://github.com/aspnet/Mvc/issues/3563 was the same issue which got closed as a duplicate of https://github.com/aspnet/KestrelHttpServer/issues/270. I cannot deduce the workaround from #270 (and the related links) for this typical use-case. Could you suggest where should I go with this next?

**Comment by Tratcher** [comment]
#270 was a data corruption issue that has long been fixed. Run the following to see if you're hitting that issue:
```
app.Run(context =>
{
  return context.Response.WriteAsync(context.Request.Method);
});
```

**Comment by muratg** [comment]
@jasonwilliams200OK did you get a chance to try @Tratcher's suggestion?
