### ISSUE TITLE
System.Numerics.Vectors, Version=4.1.1.0 not found

### ISSUE THREAD

**Issue by nil4** [aspnet/KestrelHttpServer#773]
Using dotnet CLI 1.0.0-rc2-002485 and `Microsoft.AspNetCore.Server.Kestrel/1.0.0-rc2-20682` from the `aspnetcirelease` feed in an application targeting framework `net461` with RID `win7-x64`. The application fails to start with the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MyApp.Startup.Main(String[] args)
```

After running `dotnet build -f net461`, `System.Numerics.Vectors.dll` is not present in `bin\Debug\net461\win7-x64`. Manually copying the DLL from the NuGet package cache to this folder fixes the issue. 

Not sure whether this is relevant, but thought I should mention it: when copying the DLL manually I noticed that the NuGet package cache folder contains both the `_._` placeholder as well as the actual DLL/XML files, in both `ref\net46` and `lib\net46`:

```
 Directory of C:\Users\ME\.nuget\packages\System.Numerics.Vectors\4.1.1-rc2-24018\lib\net46

2016-04-17  21:01           111 328 System.Numerics.Vectors.dll
2016-04-17  21:01            50 223 System.Numerics.Vectors.xml
2016-04-17  21:01                 0 _._
               3 File(s)        161 551 bytes
```

**Comment by davidfowl** [comment]
Can you publish a full repro project on github?

**Comment by nil4** [comment]
@davidfowl please see https://github.com/nil4/Kestrel_773_Repro. I included the `obj` and `bin` folder for completeness.

**Comment by nil4** [comment]
If I download `System.Numerics.Vectors.4.1.1-rc2-24018.nupkg` from the `aspnetcirelease` feed, it does not have the `_._` placeholder in either the `ref\net46` or `lib\net46` folders. However, the placeholder **is** present in the NuGet package cache location if it is installed by `dotnet restore`. Could this be a CLI/NuGet bug?

**Comment by davidfowl** [comment]
Looks like a nuget bug actually. This looks bizzare https://github.com/nil4/Kestrel_773_Repro/blob/master/project.lock.json#L3892-L3905

/cc @emgarten

**Comment by smbecker** [comment]
I am also seeing this after updating cli-samples/HelloWeb to target net46.

**Comment by muratg** [comment]
Looks like a nuget issue to me as well. @emgarten move to NuGet/home?

**Comment by emgarten** [comment]
Moving to https://github.com/NuGet/Home/issues/2687
