### ISSUE TITLE
Error -4081 ECANCELED operation canceled

### ISSUE THREAD

**Issue by PMExtra** [aspnet/KestrelHttpServer#774]
When action return a FileResult.
Most of browsers will appear a dialog to prompt select download path.
If user cancel the dialog, the download task will be canceled.
It's a too ordinary operation. But in kestrel, that will throw a exception:
`Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4081 ECANCELED operation canceled.`
Important ! The log level is "fail".

It make lots of junk log to cover up other really useful logs.

**Comment by halter73** [comment]
Is there a stack trace associated with that exception?

Generally speaking, an exception like that would be bubbled up to the caller to `Request.ReadAsync` or similar. I don't think it would be correct to just close the request stream normally.
