### ISSUE TITLE
reallocating new Headers and Streams on Frames is slow

### ISSUE THREAD

**Issue by nathana1** [aspnet/KestrelHttpServer#780]
Additionally the existing pooling support doesn't scale well so it is actually slower than not pooling.  Proposal is to add an option to cache the Headers/Streams on the Frame object and remove current pooling scheme.

**Comment by benaadams** [comment]
Related: https://github.com/aspnet/KestrelHttpServer/issues/754

**Comment by muratg** [comment]
@cesarbs Could you dupe this?

**Comment by cesarbs** [comment]
Dupe of #754.
