### ISSUE TITLE
Limit request target length

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#785]
Currently there's no limit; add configurable limit and reject requests for targets that are too long.

Related: #683 #784

**Comment by cesarbs** [comment]
cc @muratg putting in 1.0

**Comment by Tratcher** [comment]
I think this is redundant with #784. The only other things on the request line are the method and version, both very short.

**Comment by cesarbs** [comment]
I'd prefer to keep the distinction because there is a specific status for too long targets (414), whereas a line that is too long would be rejected with a 400. Besides, the method and version are only very short when coming from well behaved clients :smile:

**Comment by benaadams** [comment]
Related https://github.com/aspnet/KestrelHttpServer/issues/475

**Comment by Tratcher** [comment]
True, but we want to keep the number of nobs down to a sane level.

**Comment by cesarbs** [comment]
Agreed that it's redundant with #784. Closing.
