### ISSUE TITLE
improve performance of known headers

### ISSUE THREAD

**Issue by nathana1** [aspnet/KestrelHttpServer#795]
When I remove most of the headers from KnownHeaders.cs we see a good throughput increase:

|Scenario|Reqs/sec|
|---|---|
|Baseline| 1009999 |
|IOCP| 1114899 |
|Cache Headers/Streams| 1157813 |
|Known header removal| 1189857 |
|All 3| 1449341 |

Need to find the right headers to remove or other techniques to realize this gain.  See https://github.com/aspnet/KestrelHttpServer/commit/f40f4fbf069ecc7fc2bf2ddfbae3f6a3f4ff8757 for prototype code.

**Comment by benaadams** [comment]
wrk only includes Host header, which wouldn't match real world use.

Would outputting the headers in a particular order help? E.g. always have Host as the first check for request?

**Comment by geoffkizer** [comment]
There are a ton of known headers, and it's not clear we really should predefine these, since there's some cost to it.  We should at least look at removing some of the pretty uncommon ones.

**Comment by nathana1** [comment]
I was able to taking a closer at the profiles and there's 2 primary issues:

1. FrameHeaders objects are huge so they take time to allocate, we are also addressing this with the pooling/caching work.
2. CopyToFast isn't that fast when we are creating response headers probably because there are so many different headers it checks for.

One approach is to be slightly less draconian than my prototype linked above (reinclude the ones @benaadams listed and the ones kestrel actually uses).  I'll also take a look for other approaches.

**Comment by geoffkizer** [comment]
I think there's one other potential issue too:  Even with pooling, Reset on the Headers objects are expensive because they are so large.  Nathan do you see that in your profiles?

**Comment by nathana1** [comment]
Yeah, it does seem to be smaller than the other 2 though.

**Comment by nathana1** [comment]
I hoped to get an additional improvement from #812 since CopyToFast spends half its time doing bitwise comparisons and the other half block copies but I'm not seeing any perf difference between safe and unsafe whether I include the header trim or not.

**Comment by benaadams** [comment]
@nathana1 if you are reducing them, I might have something...

**Comment by benaadams** [comment]
Known headers have known offsets; have a look at /MemoryPoolIterator2.Generated.cs https://github.com/benaadams/KestrelHttpServer/commit/f09696445822c2d0c6337735ccb8a2f57ba29d0a

**Comment by benaadams** [comment]
nvm CopyToFast is output not input

**Comment by muratg** [comment]
Moving to 1.0.1 as we're closing on 1.0 ATM.

**Comment by halter73** [comment]
@muratg I think our current header dictionaries are good enough now that we cache by default.

We should probably close this, unless we have a good way to come up with a representative sample of common/known headers, and a good way to determine a cutoff of how common a header should be to get its own field in our optimized dictionaries.
