### ISSUE TITLE
AddressRegistrationTests should get local IPs from System.Net.NetworkInformation

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#796]
AddressRegistrationTests should get local IPs from System.Net.NetworkInformation rather than System.Net.Dns, since it's more reliable across different OS and networking configurations.

**Comment by mikeharder** [comment]
Blocked on https://github.com/dotnet/corefx/issues/8458

**Comment by halter73** [comment]
The blocking PR has been merged.

**Comment by mikeharder** [comment]
Yes, now we need to wait until KoreBuild moves to a CLI version which includes the fix.
