### ISSUE TITLE
Test to ensure multiple concurrent HTTPS connections has adequate performance

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#798]
Draft: https://github.com/mikeharder/KestrelHttpServer/tree/mikeharder/https-parallel-test

**Comment by cesarbs** [comment]
Shouldn't we just keep track of the numbers with HTTPS in our benchmarks automation? I don't think this belongs in a Kestrel test.

**Comment by mikeharder** [comment]
This is about the performance of establishing HTTPS connections, which isn't directly tested by existing benchmarks automation since it establishes connections once and re-uses them.  But I would be fine moving this bug to the Performance repo and treating it as a perf test rather than a unit test.  Measure the time to establish N HTTPS connections.

**Comment by Drawaes** [comment]
This is important for a couple of reasons. Https is becoming critical even inside companies with service 2 service calls. Next techempower have it on their future tests list.

Remember that using SSLStream can give false numbers or changing numbers depending on system settings. I can give a little bit of advice if anyone is interested

**Comment by cesarbs** [comment]
This issue was moved to aspnet/Performance#222
