### ISSUE TITLE
Move MemoryBlock return outside lock

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#809]
In SocketInput.ConsumingComplete the memory pool block return is inside the local lock while the return is contends on a KestrelThread `ConcurrentQueue`

```csharp
while (returnStart != returnEnd)
{
    var returnBlock = returnStart;
    returnStart = returnStart.Next;
    returnBlock.Pool.Return(returnBlock);
}
```
https://github.com/aspnet/KestrelHttpServer/blob/7ca0fbeb3dd9325d4dfc58981908112ac33e27ad/src/Microsoft.AspNetCore.Server.Kestrel/Http/SocketInput.cs#L204-L209

The return should be adjusted so it is outside the lock and releases it earlier

**Comment by muratg** [comment]
What's the impact? I wonder if this was done for a reason...

**Comment by benaadams** [comment]
Resolved by #815

**Comment by halter73** [comment]
@muratg This code specifically doesn't need to be done in a lock. It is only referencing local variables. I was just a little over-aggressive when reintroducing locks in some places where it is necessary in SocketInput. I also wonder the magnitude of the perf impact.

**Comment by muratg** [comment]
Sounds, good, thanks @benaadams and @halter73.
