### ISSUE TITLE
React to https://github.com/dotnet/corefx/pull/8378

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KestrelHttpServer#813]
We'll be able to remove our ifdefs! 😄

**Comment by muratg** [comment]
https://github.com/dotnet/corefx/pull/8378

**Comment by benaadams** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/768

**Comment by benaadams** [comment]
https://github.com/dotnet/coreclr/issues/4908
