### ISSUE TITLE
Don't bind if only port is specified.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/KestrelHttpServer#814]
You can pass just a port integer into Kestrel as the address to bind to. Currently Kestrel assumes this means to bind to the given port publicly for all IPs. https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/ServerAddress.cs#L87

Kestrel should only bind to localhost unless explicitly specified. Note WebListener already behaves this way.

**Comment by Tratcher** [comment]
https://github.com/aspnet/WebListener/blob/dev/src/Microsoft.Net.Http.Server/UrlPrefix.cs#L128

**Comment by Tratcher** [comment]
Change of plans (as reflected in the title). Remove support for only specifying the port. People make bad assumptions about the rest of the prefix.

**Comment by mikeharder** [comment]
Since this is a breaking change, I plan to create an issue under https://github.com/aspnet/Announcements after this is merged.
