### ISSUE TITLE
Resetting connection via interface is expensive

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#819]
A not insignificant time in frame reset is spent resetting the connection addresses via interface when in all likelyhood they have not changed.

![reset connection info](http://aoa.blob.core.windows.net/aspnet/reset.png)

**Comment by benaadams** [comment]
Resolved by  #793

**Comment by muratg** [comment]
@halter73 Can you look into this? If this is low hanging fruit, let's take it.
