### ISSUE TITLE
Hot reload on Linux

### ISSUE THREAD

**Issue by idarous** [aspnet/KestrelHttpServer#820]
Hello,

I've tried to develop an ASP.net  5 project with Visual studio code and Kestrel on Linux.
I can build the project with dnx build and I can run it with dnx run.
However, after each change in my code, I need to build and run again the project.
I come from Play Framework (Java) and this technology support hot reload that is very usefull because you don't have to run again the project after each change.

Does Kestrel support hot reload on Gnu/Linux ?
If not is it possible to add this feature on Kestrel ?

Thank you

**Comment by moozzyk** [comment]
For RC1 you may want to take a look at dnx-watch tool which became dotnet-watch tool post RC1.
