### ISSUE TITLE
Responses crossing 2s boundaries may see torn Date header values

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#821]
If date header bytes set but request tasks longer than 2s (or multiples of 2s) it may catch the underlying byte date being updated.

Low probability as it will occur on 2s beats for under 1μs but still possible

**Comment by benaadams** [comment]
Resolved by #810

**Comment by DamianEdwards** [comment]
Can you explain this a little more? I'm not quite following. Isn't the date header value bytes marked volatile and read/written to as such?

**Comment by benaadams** [comment]
The latency between the date bytes header being set and being copied to the "wire" may mean that the byte buffer may have transitioned to non active and then be updated. So it could be being updated at the same time it is being copied.

**Comment by DamianEdwards** [comment]
Oh this code has changed a little since last I looked.

**Comment by benaadams** [comment]
Don't think its huge
