### ISSUE TITLE
After debugging ends - focus back to default browser - not Command prompt

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/KestrelHttpServer#822]
I'm not sure if this is more of a Kestrel issue, than perhaps Visual Studio 2015 (update 1), but when Continuing debugging (no more breakpoints) it pops up the Command line where Kestrel is running than going back to the browser.  Let me know if this should be posted elsewhere! Just wanted to get in on the radar.

OS: **Win 7**
Visual Studio 2015 (update 1)

**Comment by davidfowl** [comment]
The bug should be filed here https://github.com/aspnet/Tooling

**Comment by MarkPieszak** [comment]
Ahh there it is! Thank you David, I'll close it out and let them know over there.
