### ISSUE TITLE
Support Https

### ISSUE THREAD

**Issue by Meai1** [aspnet/KestrelHttpServer#83]
This is getting more and more important, especially with Http2 coming as well.

**Comment by muratg** [comment]
Design/prototype in Beta 7, and we can finish it up in Beta 8.

cc @lodejard @davidfowl @DamianEdwards

**Comment by glennc** [comment]
Get this working with SSLStream on desktop clr, then we will make it work on core clr when it is ready.

**Comment by blowdart** [comment]
Please ensure you're leaving the decryption of process, e.g. in http.sys, so worker processes never see the private keys. Without this protection you cannot release.

**Comment by muratg** [comment]
Kestrel doesn't use http.sys.

**Comment by blowdart** [comment]
I never said it did @muratg. I said you need to guarantee the same protections for key information.

**Comment by muratg** [comment]
We'll finish this work off in RC1 

@DamianEdwards @davidfowl
