### ISSUE TITLE
generated code for Frame doesn't always reuse result of typeof

### ISSUE THREAD

**Issue by nathana1** [aspnet/KestrelHttpServer#831]
The types of various features gets cached in Frame.Generated.cs: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/Frame.Generated.cs#L9

But that cached value doesn't get reused in FastFeatureGet/Set: https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/Http/Frame.Generated.cs#L66

There is a small win (2.5%) on the TechEmpower hardware when reusing those values instead of calling typeof again:

|Scenario|Million Reqs/Sec|
|---|---|
|Baseline|5.57|
|Reuse|5.71|

**Comment by benaadams** [comment]
Heh a mere 200,000 rps ;-)

Related, I saw this branch from @jkotas that hasn't been PR'd but looks interesting:  https://github.com/jkotas/KestrelHttpServer/commit/31d93d19a2c02f750cb49f686a598c8831d5524f

**Comment by muratg** [comment]
cc @mikeharder
