### ISSUE TITLE
DotNet Core RC2 causes unicode issue in Chrome

### ISSUE THREAD

**Issue by AustinWinstanley** [aspnet/KestrelHttpServer#838]
It works fine in Edge and Firefox.

Every page in Chrome is messed up with the unicode character &#65279; being inserted at the top causing the <head> content to be inserted in the body. It happens on all pages. Tested first on an upgraded site and then on a default web project created through Visual Studio.

[Referred from Core](https://github.com/dotnet/core/issues/94)

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349270/377ea46e-1c97-11e6-955d-97f13c797a55.png)

**Comment by AustinWinstanley** [comment]
Running through the command line does not have the problem.

`dotnet restore`
`dotnet run`

![untitled](https://cloud.githubusercontent.com/assets/4576933/15349636/d7ddbf92-1c99-11e6-8702-5d720906ed1f.png)

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/StaticFiles/issues/130

**Comment by Tratcher** [comment]
I've been able to repro this. The site is sending a BOM at the beginning:
```
???<!DOCTYPE html>
<html>
<head>
```
This happens for both Kestrel and IIS Express. It's only visible in Chrome when using IIS Express, and I think this is because IIS Express is adding dynamic gzip compression and Chrome is handling it differently.

@rynowak why are there BOMs coming from MVC / Razor?

**Comment by halter73** [comment]
@Tratcher should we move this issue again? As much as @davidfowl might object it doesn't appear that it's a Kestrel issue :wink:

**Comment by rynowak** [comment]
@Tratcher - I'll come by to see your repro - Everywhere I can think of in MVC we use `HttpResponseStreamWriter` which doesn't write a BOM https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs#L14

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Mvc#4671
