### ISSUE TITLE
Reject requests that don't have a Host header

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#839]
RFC 7230 section 5.4 - https://tools.ietf.org/html/rfc7230#section-5.4

> A server MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request message that lacks a Host header field and to any request message that contains more than one Host header field or a Host header field with an invalid field-value.

**Comment by muratg** [comment]
@cesarbs What's our current behavior for requests that don't have a Host header?

**Comment by cesarbs** [comment]
We process them as we would any other request.
