### ISSUE TITLE
Make kestrel nonblocking

### ISSUE THREAD

**Issue by krippz** [aspnet/KestrelHttpServer#84]
It would be great to have kestrel to be nonblocking while running. I was thinking of splitting the main kestrel process in two. Having one to listen to commands like stop, start, while the other being the normal request handler. 
This would be similar to how nginx works.

**Comment by davidfowl** [comment]
Kestrel is non blocking. You're thinking about the hosting library

**Comment by krippz** [comment]
Ah ok, so I'm still on beta 3 so that would be k in my case?
And on beta 4 that would be dnx?

**Comment by Tragetaschen** [comment]
You are mixing up a couple of things.
Blocking the program is done by [aspnet/Hosting](https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNet.Hosting/Program.cs#L67), which is one of the ASP.NET 5 libraries.
Kestrel [spins up](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/KestrelEngine.cs#L78) a number threads (defaults to just one) where each one runs a [libuv](https://github.com/libuv/libuv) loop.

**Comment by krippz** [comment]
Ok thanks, now I have a better picture of how it all ties together.
