### ISSUE TITLE
Very slow server response or 502.3 Gateway Error with default project using asp.net core RC2

### ISSUE THREAD

**Issue by plouveau** [aspnet/KestrelHttpServer#854]
I'm currently encountered a strange bug while debugging the default web project with asp.net core RC2.

Steps to reproduce :
1- I created an ASP.NET Core Web Application (.Net Core or .Net Framework)
2 - Once the project is created, I click on debug using IISExpress
Result -> After a long time, it gives me "Error 503.2 Bad Gateway" (from ASP.NET CORE Module)
![iisexpresserror](https://cloud.githubusercontent.com/assets/11669084/15422866/e47bd1c0-1e7a-11e6-8c48-431780169922.PNG)
3 - I change IISExpress by using the {project.name}.exe
Result -> See image below
![slowdebug](https://cloud.githubusercontent.com/assets/11669084/15422761/5239cb6e-1e7a-11e6-865d-8078cb95cb7a.PNG)

The problem occured on every browser.

**Comment by plouveau** [comment]
I'm adding additional informations from the output console : (I've put in bold what seems to be relevant)
Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60:Information: Connection id "0HKS0JTC7RVJ4" communication error

**Microsoft.AspNetCore.Server.Kestrel.Networking.UvException: Error -4077 ECONNRESET connection reset by peer**
Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler:Information: Executed action WebApplication1.Controllers.HomeController.Index (WebApplication1) in 131264.8781ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 131955.0043ms 200 text/html; charset=utf-8

**Comment by plouveau** [comment]
I've finally find the solution : 
I disable the "BrowerLink" functionality and it runs fine now !

**Comment by chemitaxis** [comment]
Hi @plouveau , what is BrowerLink? Thanks!

**Comment by khellang** [comment]
@chemitaxis See http://www.asp.net/visual-studio/overview/2013/using-browser-link

**Comment by chemitaxis** [comment]
Thanks ;)

**Comment by plouveau** [comment]
Sorry, I couldn't give you a response sooner. You can disable Browser Link next  to the debug selection.

Envoyé à partir de mon Windows Phone
________________________________
De : Chema<mailto:notifications@github.com>
Envoyé : ‎26/‎05/‎2016 16:40
À : aspnet/KestrelHttpServer<mailto:KestrelHttpServer@noreply.github.com>
Cc : LOUVEAU PASCAL<mailto:pascal.louveau@viacesi.fr>; Mention<mailto:mention@noreply.github.com>
Objet : Re: [aspnet/KestrelHttpServer] Very slow server response or 502.3 Gateway Error with default project using asp.net core RC2 (#854)


Thanks ;)

**Comment by dkvhin** [comment]
same issue, thanks @plouveau
