### ISSUE TITLE
Unix Socket Permissions - Nginx Unable to Connect

### ISSUE THREAD

**Issue by tonemackay** [aspnet/KestrelHttpServer#856]
When using Unix Sockets, is it possible to change the permissions of the created **.sock** file so that nginx has the correct access rights.

I am using the following code in Program.cs to start the server:

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseUrls("http://unix:/run/kestrel-test.sock")
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```
The file is created at  **/run/kestrel-test.sock**. The problem is nginx does not have permission to write to the file unless it is modified with the following command:
 
    sudo chmod 666 /run/kestrel-test.sock

Is there a way for kestrel to create the file with 666 permissions or am I doing something wrong?

Thanks

**Comment by mikeharder** [comment]
One option is to run Kestrel and nginx as the same user.  The nginx user is set via the `user` directive in nginx.conf: http://nginx.org/en/docs/ngx_core_module.html#user.  This way the file permissions work correctly with no changes.

If you run Kestrel and nginx as different users, you'll need to modify the file permissions on your own.

**Comment by tonemackay** [comment]
Thanks Mike. That worked.

I changed the nginx user from **www-data** to the local user I login to to the server with. Would this be secure though? Or would I need to leave nginx running with **www-data** and make Kestrel run with **www-data**?

I also had to change the directory the socket was created in from **/run** to **/tmp** because the local user running Kestrel did not have permission to write to the **/run** folder.

**Comment by mikeharder** [comment]
We recommend running Kestrel as `www-data`.  See https://docs.asp.net/en/latest/publishing/linuxproduction.html.

**Comment by tonemackay** [comment]
When I run Kestrel as `www-data` I get the following error message:

Access to the path '/home/viewmodel/cli-samples/HelloMvc/obj/Debug/netcoreapp1.0/.SDKVersion' is denied.

I assume this is because `www-data` does not have any permissions to access the folder. What would the recommended permissions be and on what folders.

Thanks

**Comment by tonemackay** [comment]
Turns out it was the `-H` flag changing the home directory. I removed this and now it works.
