### ISSUE TITLE
ServerAddress.FromUrl("http://") throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KestrelHttpServer#860]
## Repro
```C#
ServerAddress.FromUrl("http://")
```

## Expected
Return either `null` or a valid `ServerAddress`

## Actual
```
Unhandled Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.ServerAddress.FromUrl(String url)
```

**Comment by khellang** [comment]
Don't you think it should throw *something* for invalid URLs? Returning `null` could lead to an equally vague `NullReferenceException`.

**Comment by mikeharder** [comment]
@khellang: Thanks for the suggestion, we agree ServerAddress.FromUrl() should throw instead of returning null.  Tracked by https://github.com/aspnet/KestrelHttpServer/issues/875.
