### ISSUE TITLE
Async sync fast-paths aren't fast pathing

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#864]
ProduceStartAndFireOnStarting only goes async if the user has set an `OnStarting` task - which may also complete sync. 

In normal circumstances `_onStarting != null` which means it returns a `CompletedTask` and doesn't need to go async or await.

The mechanism for fast-pathing this is already there, however its checking the wrong thing (whether a function needs to be called, rather than whether the task the function returns  `RanToCompletion`)

The red below shows the unnecessary call stack this creates (5% of WriteAsync):

![too much await](http://aoa.blob.core.windows.net/aspnet/too-much-await-3.png)

**Comment by muratg** [comment]
@benaadams Do you have any measurements for the perf gains?

**Comment by benaadams** [comment]
@muratg is 5% of WriteAsync numbers are in the PR #863; can provide more info if needed?

**Comment by muratg** [comment]
Backlogging for now

**Comment by halter73** [comment]
Closed since the benchmarks didn't show a significant perf gain.

**Comment by benaadams** [comment]
It does still bother me at a holistic level :)
