### ISSUE TITLE
Don't call uv_async_send when loop already active

### ISSUE THREAD

**Issue by benaadams** [aspnet/KestrelHttpServer#865]
~20% of `Frame.WriteAsync` is `async_send` which is used to wake up the libuv loop.

![async-send](http://aoa.blob.core.windows.net/aspnet/async-send.png)

However if the loop is already active and processing requests it doesn't need to be woken up and the call does not need to be made.

**Comment by muratg** [comment]
@benaadams Do you know what's the perf gain (before/after numbers?)

**Comment by benaadams** [comment]
I haven't measured an after as it would need a tweak to the KestrelThread processing loop, but in a way that avoids a race condition and doesn't hit performance to avoid it.

Although a naive implementation would probably only cost as much as the safehandle add+release. Will look into it further.

**Comment by benaadams** [comment]
Added PR #943 for this; still need to measure

**Comment by benaadams** [comment]
Closing this, has been tested
