### ISSUE TITLE
Kestrel RC2 not working on full framework (dnx451)

### ISSUE THREAD

**Issue by mrgleba** [aspnet/KestrelHttpServer#873]
Is it possible to run Kestrel under full framework (for example mono)?
Af far as I can see Microsoft.AspNetCore.Server.Kestrel\1.0.0-rc2-final provides a net451 lib
but some of the dependencies it uses provide only netstandard libs (for example System.Buffers)

**Comment by mrgleba** [comment]
I was able to make it compile.
The problem is the binary is compiled to bin\Debug\dnx451 but
the debugger tries to run from bin\Debug\dnx451\win7-x64 (which doesn't exist)

I'm not sure it's Kestrel's bug after all (perhapse the VS tooling).

**Comment by moozzyk** [comment]
I guess you need to publish your app for ubuntu with net451 framework. Try `dotnet publish --framework net451 --runtime ubuntu.14.04-x64` 

Out of curiosity - why not use coreclr?

**Comment by davidfowl** [comment]
You dont need to specify anything, it should just work

**Comment by moozzyk** [comment]
@davidfowl  If you are developing on windows and publish without RID it will use the RID of the machine used for development. As a result you will get win7-x64 version of Kestrel - how this is supposed to work on Linux?

**Comment by davidfowl** [comment]
Ahh, I'm not sure we support cross publish on .NET Framework. I guess the syntax you proposed would work if we supported it.

@pakrym, any ideas?

**Comment by mrgleba** [comment]
Got it to work in VisualStudio by setting "executablePath" explicitly in launchSettings.json

@moozzyk I'm still reliant on some external libraries that are not yet ported so for the time being I'm stuck with the full framework.

I'll report this issue to buildtools, as it seems a more relevant place

**Comment by davidfowl** [comment]
That's not a more relevant place. Can you explain you provide explicit repro steps for the problem you're seeing?

**Comment by mrgleba** [comment]
The result is the same (no win10-x64 dir created, libuv not copied) when using commandline "dotnet build". I'm trying to come up with a test case but everything seems to work well in a newly created solution. The project files (json, xproj) seem not to have any significant differences and still the outcome is somehow different. I will dig into it a bit further (maybe recreate project structure from scratch) and see when/if it breaks then.

**Comment by davidfowl** [comment]
What happens when you use visual studio? In fact better yet, can you make a project that reproduces the issue so I can try it myself?

**Comment by muratg** [comment]
@mrgleba any luck coming up with a simple repro app?

**Comment by mrgleba** [comment]
Yes. I was able to narrow it down to a small reproductible case.
I've checked and the outcome is the same with vs 2015 comunity and dotnet cli on both win and linux.
in bin/Debug/net451 no subfolder win10-x64 is created
Thus "dotnet run" doesn't work as it's unable to find the exe.

[Repr.zip](https://github.com/aspnet/KestrelHttpServer/files/287648/Repr.zip)

**Comment by mrgleba** [comment]
Yet more simple repro case (for CLI only)
cd App
dotnet restore
dotnet run

Returns file not found because the compiled exe doesn't go in 

If you copy the files manually to win7-x64 subdirectory then it works fine.

So I believe it's actually a CLI issue after all.

[App.zip](https://github.com/aspnet/KestrelHttpServer/files/287662/App.zip)

**Comment by mrgleba** [comment]
Finally I was able to pinpoint the problem.

If "buildOptions" is specified in the global scope of project.json everything works well.
If it's specified within "frameworks"/"net451" then the problem occurs.

**Comment by davidfowl** [comment]
Cool!
