### ISSUE TITLE
Reset Frame's IHttpRequestFeature.Headers and IHttpResponseFeature.Headers between requests

### ISSUE THREAD

**Issue by khellang** [aspnet/KestrelHttpServer#879]
See https://github.com/aspnet/KestrelHttpServer/pull/862#discussion_r64489390

Also, look into consolidating `RequestHeaders` and `FrameRequestHeaders`. See https://github.com/aspnet/KestrelHttpServer/pull/862#discussion_r64484432

**Comment by cesarbs** [comment]
@muratg I think this is important enough for 1.0.0. @halter73 do you agree?

**Comment by muratg** [comment]
CC @mikeharder & @davidfowl for their thoughts as well.

**Comment by davidfowl** [comment]
Lets do it.

**Comment by halter73** [comment]
This change should be very simple even if it might not affect (m)any real apps.
