### ISSUE TITLE
overriding max upload limit

### ISSUE THREAD

**Issue by Ryuuke** [aspnet/KestrelHttpServer#891]
Hello, 
I encountered this error when uploading large file (~200MB).

> An unhandled exception occurred while processing the request.
> Multipart body length limit 134217728 exceeded
> at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)

I already tried to modify my web.config file :
httpRuntime maxRequestLength="1073741824" executionTimeout="300000"
and requestLimits maxAllowedContentLength="1073741824"

but still, I get the same error.

I'm using the RC2 version, is there a way to override that limit ?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/HttpAbstractions#641
