### ISSUE TITLE
Using command-line options in RC2?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/KestrelHttpServer#893]
My blog is currently running on ASP.NET 5 RC1. I have commands for live vs staging configured in `project.json`:
```
  "commands": {
    "web-live": "Microsoft.AspNet.Server.Kestrel --server.urls http://unix:/run/dan-live.sock",
    "web-staging": "Microsoft.AspNet.Server.Kestrel --server.urls http://unix:/run/dan-staging.sock"
  },
```

And then I run a command like this to actually run the site:
```
/var/www/.dnx/runtimes/dnx-mono.1.0.0-rc1-final/bin/dnx --appbase /var/www/dan.cx/live/site/approot/packages/Daniel15.Web/1.0.0/root Microsoft.Dnx.ApplicationHost --configuration Release web-live
```

With RC2, it looks like my site compiles into a .exe file that I can execute directly via `mono`:

```
% mono Daniel15.Web.exe
Hosting environment: Production
Content root path: /var/www/dan.cx/staging/site
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

However, I can't figure out how to specify the `server.urls`. Do I need to have separate config files for staging vs live? How do I specify which one to use?

(note that my site is currently not compatible with .NET Core, so I am using Mono + .NET Framework 4.5.1)

**Comment by davidfowl** [comment]
https://github.com/aspnet/Hosting/issues/737

**Comment by Daniel15** [comment]
Thanks @davidfowl! Once I added the config:

```
var config = new ConfigurationBuilder()
	.AddCommandLine(args)
	.Build();

var host = new WebHostBuilder()
	.UseConfiguration(config)
	// ......
	.Build();
```

It worked as expected :smile:
