### ISSUE TITLE
windows authentication

### ISSUE THREAD

**Issue by zigzag95** [aspnet/KestrelHttpServer#894]
Hello,
How to enable windows authentication.

I used to use 

```C#
  var listener = app.ServerFeatures.Get<WebListener>();
            if (listener != null)
            {
                listener.AuthenticationManager.AuthenticationSchemes =
                    Microsoft.Net.Http.Server.AuthenticationSchemes.NTLM;
            }
```

But listener is null when running from console dot net run
It's not null when running from VS

**Comment by Tratcher** [comment]
Please file WebListener issues in Hosting.

Try this for RC2:
```
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseStartup<Startup>()
                .UseWebListener(options =>
                {
                    options.Listener.AuthenticationManager.AuthenticationSchemes = AuthenticationSchemes.NTLM;
                })
                .Build();

            host.Run();
        }
```

**Comment by zigzag95** [comment]
Thank you
I'm confused, any doc explaining this stuff kestrel iis web listener?

**Comment by zigzag95** [comment]
If I don't want use weblistener how to use Windows authentication with kestrel?

**Comment by Tratcher** [comment]
Kestrel does not directly support Windows Auth, you must use WebListener or IIS + Kestrel. Here are the current server docs: https://docs.asp.net/en/latest/fundamentals/servers.html
Just add `forwardWindowsAuthToken="true"` in the Web.Config:
https://github.com/aspnet/IISIntegration/blob/dev/samples/IISSample/web.config#L13

**Comment by cesarbs** [comment]
Closing since a solution was provided.

**Comment by vanslly** [comment]
@Tratcher I cannot seem to get IIS + Kestrel working with Windows Auth by setting `forwardWindowsAuthToken="true"` and according to the docs, Kestrel doesn't support the `IHttpAuthenticationFeature` feature; which I'm guessing is what Windows Auth would be part of?

**Comment by zigzag95** [comment]
Strange because it works here with IIS Express and IIS
Did you use IISIntegration() ?

**Comment by vanslly** [comment]
Sorry guys - it does work. My mistake was not using `credentials: true` in my fetch API calls:
```
fetch('http://myhost:8080/api/customers', { credentials: 'include' }).then(
    response => console.log(response),
    err => console.log(err));
```
