### ISSUE TITLE
Redirect to Https on the same port

### ISSUE THREAD

**Issue by logankd** [aspnet/KestrelHttpServer#898]
In order to allow the user to forget they need https with less confusion
I want to be able to redirect from http to https.

UseUrls with the same port, but different scheme like so:
```
var host = new WebHostBuilder().UseUrls("http://*:9001", "https://*:9001") 
.UseKestrel(options =>
                 {
                     options.NoDelay = true;
                    options.UseHttps(testCertPath, configuration["pfxPassword"]);
                     options.UseConnectionLogging();
                 })....
```

gives an Error -4091 EADDRINUSE address already in use exceptions at run time.

It'd be even better if I could use
```
services.AddMvc(config =>
{
  // this was causing a loopin redirect in RC2
  //config.Filters.Add(new RequireHttpsAttribute());
})
```
but I get stuck in a loop.

I have it setup manually with app.Use, but it is hacky
```
app.Use(async (httpContext, next) =>
{
	var url = httpContext.Request.GetDisplayUrl();
	var httpPort = url.EndsWith(":9001") || url.EndsWith(":9001/");
	if (httpPort)
	{
		// force to https
		var uri = new Uri(url);
		httpContext.Response.Redirect($"https://{uri.Host}:9000");
		return;
	}
```

**Comment by Tratcher** [comment]
http and https can never be hosted on the same port as there's no way to negotiate the protocol after connecting. RequireHttpsAttribute is the correct solution. If that's not working for you then share the details so we can investigate.

**Comment by benaadams** [comment]
Probably better to check the scheme rather than the ports; that way if you change the ports it still works

e.g.

`if (!string.Equals(context.Address.Scheme, "https", StringComparison.OrdinalIgnoreCase))`

**Comment by logankd** [comment]
I understand the port issue now. this is where I've been leaning on IIS for a long time and trying to get into the kestrel/middleware thinking
I was thinking about the http://www.something.com redirecting to https://www.something.com without thinking about ports. So I was in the wrong mindset
IIS + MVC attributes + a long time since I've done a new website
that's my excuse anyways.

About the looping, it may have been my middleware setup.

I'll close this as it was my mis-understanding, but it would be nice to see some documentation/walk through on.

Using
`.UseUrls("http://*:80", "https://*:443")`
with 
```
services.AddMvc(config =>
{
  config.Filters.Add(new RequireHttpsAttribute());
})
```

**Comment by logankd** [comment]
I did a write up, maybe it will help someone: https://gooroo.io/GoorooTHINK/Article/16767/Https-Redirect-with-AspNet-Core-RC2-And-Kestrel-on-Windows/22781
