### ISSUE TITLE
Unable to resolve 'Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/KestrelHttpServer#902]
Unable to resolve 'Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0-rc3-21157)' for '.NETCoreApp,Version=v1.0'.

**Comment by yury-stepanov** [comment]
It seams I have the same problem. What was the issue in your case?

**Comment by GuardRex** [comment]
Possibly feeds. Which feed(s) are you on and which version of the package did you target?
