### ISSUE TITLE
kestrel font awesome fonts issue

### ISSUE THREAD

**Issue by jrock2004** [aspnet/KestrelHttpServer#92]
So I am running my MVC6 server and I am using font awesome. In my console I am noticing errors for failed to load resource

``` bash
http://localhost:5004/fonts/fontawesome-webfont.woff2?v=4.3.0 Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5004/fonts/glyphicons-halflings-regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
```

 I have found a way in Windows(IIS) to fix this issue but not sure how I can fix it on my side with using k kestrel

``` bash
1.       Open the file “C:\Users\YOUR_USERNAME_HERE\Documents\IISExpress\config\applicationhost.config
2.       Around line 769, you’ll see:
<mimeMap fileExtension=".woff" mimeType="font/x-woff" />
3.       Right after that line, add the same thing, but for the .woff2 extension:
<mimeMap fileExtension=".woff2" mimeType="font/x-woff" />
```

Thanks for any help

**Comment by akoeplinger** [comment]
Which version are you using? The woff2 mime type was recently added to the StaticFiles middleware which I suppose you're using: https://github.com/aspnet/StaticFiles/pull/30.

**Comment by jrock2004** [comment]
How can I tell the version? 

➜  VendorNext.Web git:(master) ✗ k --version
1.0.0-beta3-11030

**Comment by akoeplinger** [comment]
Beta3 doesn't include that commit, so what you're seeing is expected :)

**Comment by jrock2004** [comment]
So what options do I have?

**Comment by akoeplinger** [comment]
You should be able to add the content type yourself:

``` csharp
var myProvider = new FileExtensionContentTypeProvider();
myProvider.Mappings.Add(".woff2", "application/font-woff2");

app.UseStaticFiles(new StaticFileOptions() { ContentTypeProvider = myProvider });
```

**Comment by Eilon** [comment]
Yup, should be exactly what @akoeplinger said.
