### ISSUE TITLE
Add doc comments to all KestrelServerOptions properties

### ISSUE THREAD

**Issue by halter73** [aspnet/KestrelHttpServer#922]
There are currently a few undocumented properties in [KestrelServerOptions](https://github.com/aspnet/KestrelHttpServer/blob/b4632c273edf15f627df18d964baf5f4479c8285/src/Microsoft.AspNetCore.Server.Kestrel/KestrelServerOptions.cs). This [pretty visible](https://github.com/aspnet/KestrelHttpServer/blob/b4632c273edf15f627df18d964baf5f4479c8285/samples/SampleApp/Startup.cs#L44) as far as Kestrel APIs are concerned, so it might be worth adding before 1.0.

@Eilon @muratg

**Comment by muratg** [comment]
@halter73 please enlist help from @cesarbs as needed.

**Comment by Eilon** [comment]
Anything planned here? Need to get this done today, or it'll have to wait.

**Comment by cesarbs** [comment]
@halter73 How busy are you with other things? I can take this.

**Comment by halter73** [comment]
@cesarbs I had already started on this. Please feel free to make/suggest improvements to the PR. A thorough review would be greatly appreciated.
