### ISSUE TITLE
KestrelServerOptions.ApplicationServices null when using UseKestrel overload with action to change options

### ISSUE THREAD

**Issue by fubar-coder** [aspnet/KestrelHttpServer#923]
I'm currently using `UseKestrel(ConfigureHttpsCertificate)` and found that `KestrelServerOptions.ApplicationServices` is `null`.

My assumption is, that `services.Configure(options)` in the `UseKestrel` overload interferes with `services.AddTransient<IConfigureOptions<KestrelServerOptions>, KestrelServerOptionsSetup>();`~~, because the call to `services.Configure(options)` is implemented as `services.AddSingleton<IConfigureOptions<TOptions>>(new ConfigureOptions<TOptions>(configureOptions))`. So, we have an `IConfigureOptions<KestrelServerOptions>` as transient, and one as singleton, which is at least somewhat confusing and inconsistent~~.

The question is: Is it a bug in the KestrelHttpServer? Or is it a problem coming from AutoFac?

**Comment by fubar-coder** [comment]
Found it. AutoFac returns all items in reverse order (Authfac Issue #755)[https://github.com/autofac/Autofac/issues/755]

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/785
