### ISSUE TITLE
Typescript files from .js and .map files served by kestrel return default page not source

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/KestrelHttpServer#931]
I have an angular site setup like so:

wwwroot
        ---App
             --Controllers
                     --some .js files with their .map files
scripts
       --Controllers
              --Some .ts files that match the .js files above

When using Visual Studio with IIS Express debugging occurs properly into those .ts files without issue. However using Kestrel RC2 the homepage html is instead returned for the .ts files making debugging impossible.

Given the issues with forcing ssl via web.config blocking debugging with IISExpress I was hoping to use Kestrel is a workaround on our debug machines but can't as a result.

Any ideas on how to resolve this or is this a bug?

**Comment by davidfowl** [comment]
Sounds like you don't have the static files middleware enabled. Kestrel doesn't have an support for static files by default, you need to enable the static files middleware:

https://docs.asp.net/en/latest/fundamentals/static-files.html?highlight=staticfiles

**Comment by JohnGalt1717** [comment]
UseStaticFiles() is enabled in the Configure method and works fine for images etc. It just doesn't work for Typescript files that are outside of what Kestrel should be serving anyhow. I'd guess that IISExpress has special logic for local pathing that is outside of it's control being passed back to Vs.net instead of being served.

**Comment by davidfowl** [comment]
Only files under the webroot are servable.

**Comment by JohnGalt1717** [comment]
Right and thus it should do as IISExpress does and pass those back to VS.net properly so that you can debug your typescript that obviously should never be in your webserver because they're source code.

So this is definitely a bug that stops proper debugging.

**Comment by mikeharder** [comment]
@JohnGalt1717: A few questions:

- Could you please share a small application which reproduces this issue?
- When you say "Visual Studio with IIS Express", do you mean "Visual Studio with IIS Express proxying to Kestrel, running .NET Core" or "Visual Studio with IIS Express, running .NET Framework (e.g. 4.6.1)"?
- Can you elaborate on the "issue with forcing ssl via web.config blocking debugging with IISExpress"?

**Comment by JohnGalt1717** [comment]
(I'm on vacation and do not have access to a machine I can be creating code so I'm copying out of our source control in a browser)

Here's the issue with the web.config: http://stackoverflow.com/questions/35675747/asp-net-5-mvc-unable-to-connect-to-web-server-iis-express

I've found I can work around it by deleting the applicationhost.config and having it recreate it every time it starts hanging. There is a separate git issue that has been closed as fixed in the June 26th release hopefully.

Repro this: Open VS.net, create an empty ASP.NET Core RC2 application.  By default it will use IIS when you click the play button on the toolbar. This will work until it corrupts the applicathost.config file. 

Make sure you have the following dependancies in the project.json:

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final"
  },

Note that StaticFiles is enabled in the startup.config

And here's the routes:

             app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "legacy",
                    template: "view/lesson",
                    defaults: new { controller = "Lesson", action = "Index" }
                    );
                routes.MapRoute(
                    name: "plugin",
                    template: "plugin/lesson/{id}",
                    defaults: new { controller = "Lesson", action = "PlayBack" }
                    );
                routes.MapRoute(
                    name: "default",
                    template: "{*anything}", defaults: new { controller = "Home", action = "Index" }

                );
            });


In a scripts folder in the root of the project add a tsconfig.json file and set it with this:

{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es5",
    "outDir": "../wwwroot/app"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ],
  "compileOnSave": true
}

Create a .ts file in the scripts folder and make sure it has a module section on it so that it indeed creates the right tree under the /wwwroot/app when it saves. Add a line in there that pops up an alert on the screen or a debugger; statement. Anything that you can break on.

Note that in the /wwwroot/app folder that it creates the .js and the .map files and the .map files correctly refrence the relative path to the /scripts folder and the .ts file in there.

When you run this with the default IIS instance IIS correctly does not try and process the .ts files and you'll get debugging directly to the right line in the source .ts file at the break point. 

Click on the drop down beside the Play button on the toolbar and choose the one named the same as your project which is kestral and run that. Note that it either ignores it entirely or fails to find the source .ts file and returns the default index.html from the root instead so you get html for the .ts instead of the actual contents of the .ts which of course doesn't match up and you can't debug it.

Obviously it should do as IISExpress (however it's setup in a default project) and pass it through so that Vs.net can handle it.

**Comment by markrendle** [comment]
It should be quite easy to create a middleware that recognises requests for
´.ts´ files and serves them from the scripts folder.

The fact that Kestrel does not implement a very specific feature that
IISExpress has when working with Visual Studio is not a bug, though, any
more than it not picking up site definitions from an XML file in your My
Documents folder is a bug.

**Comment by JohnGalt1717** [comment]
Given that it completely breaks debugging of typescript in Visual Studio as a result of this "non-bug" I'd strongly disagree.

The end user shouldn't have to write custom middleware just to make something like Typescript work in visual studio. There's already WAY too many configuration files and crap to build basic websites in asp.net core under Visual studio as it is, making people seek out an undocumented solution that has performance penalties as well is just silly.  The whole point to full Vs.net is to make this stuff not have to be a PITA. If you want to make people do this stuff in ms code, fine. Fill your boots. But for the vast majority of us using the Microsoft stack and tools you're just making things vastly harder for absolutely no benefit.

As for your comparison of site definitions from my documents folder, that is not the same and has nothing to do with basic debug support for a microsoft technology within a microsoft product using a microsoft stack.

**Comment by benaadams** [comment]
`.map` files under the wwwroot would by default be served by StaticFiles https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/FileExtensionContentTypeProvider.cs#L163

**Comment by JohnGalt1717** [comment]
It isn't the map files that are the problem. Those return just fine. It's the lookup of the typescript source files that are outside of the wwwroot that is being served that is.  They shouldn't be served at all because the relative path is outside of the wwwroot and thus should allow whatever is causing IE when using IISExpress to get the typescript files in VS.net to debug into the typescript.

**Comment by markrendle** [comment]
Kestrel is a cross-platform production web server. IIS Express is a
development web server built for Visual Studio on Windows. If you need the
VS-integrated development experience, use IIS Express.

Alternatively, if you make the source files available over the web server,
whether by copying them into wwwroot or adding middleware, then you'll be
able to debug the TypeScript using the browser tools in Chrome or Firefox
(and probably Edge). In my experience, that works far better than the VS
debugging ever did.

**Comment by JohnGalt1717** [comment]
I hope you don't work for Microsoft. If you do you should be fired.

This is a bug. You can't debug typescript using the design layout as recommended by the documentation if you use Kestrel. There is nothing else more to say. Making excuses and telling people to write custom code for what should be there out of the box or worse telling people to use a competitor's product is not an answer, it's ignoring the problem.

**Comment by muratg** [comment]
@halter73 Could you please investigate?

**Comment by muratg** [comment]
@cesarbs Can you investigate?

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#810
