### ISSUE TITLE
Provide information on RTM to mono community

### ISSUE THREAD

**Issue by mrgleba** [aspnet/KestrelHttpServer#945]
Right now Kestrel RTM doesn't run right out of the box on mono (although RC2 worked fine).
The issue is `System.DllNotFoundException: System.Native`  - the issue and workaround are discussed here: https://github.com/aspnet/KestrelHttpServer/issues/942

Right now people upgrading from RC2 or trying for the first time on mono (many libs are not ported to Core yet, so this still IMHO would be large user base on *nix systems) would face this problem. Right now the only hope of finding the solution is either finding the aforementioned, closed bug (being lucky) or figuring one oneself (lots of time & skill needed).

There should be information for mono users with clear communication what is supported and what is not what is working and what is not and what potential steps are needed to make Kestrel work lest a lot of people would get frustrated and waste a lot of their time.

**Comment by davidfowl** [comment]
Mono is not supported. It's a best effort. We don't test it. We should just put it somewhere on our docs site.

/cc @Eilon

**Comment by pompomJuice** [comment]
Well then M$ should really throw some money at this problem. Don't you guys understand what a major issue this is. It is HUGE!!!!!! Get it to work, hire some code monkeys. Anything! 

I guarantee you there are just very small issues with mono that could easily sorted out by core developers. Heck you guys are basically 99% there, hosting a asp.net core app on ubuntu linux 451 almost almost works. Mere inches away from total success, we just need a little push over the line here. 

Linux has such a rich environment for devops, with .net core on board we could finally settle on the development platform of the future! Get it done! We want it now!

**Comment by benaadams** [comment]
Core is moving to full framework compatibility https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/

**Comment by borgdylan** [comment]
Kestrel works on mono if you install the right native dependencies namely libuv and System.Native.

**Comment by borgdylan** [comment]
https://github.com/borgdylan/corefx/tree/sysnative_standalone2/src/Native/System.Native
For Linux a simple ```make``` and ```sudo make install``` will suffice.

**Comment by borgdylan** [comment]
@benaadams core still lacks 32 bit support. It is why I made System.Native build standalone on Linux for both x86 and x64.

**Comment by pompomJuice** [comment]
@borgdylan Thanks for the goodies.

**Comment by borgdylan** [comment]
@pompomJuice I just shared what I needed myself. Mono will not be dying out until .NET Core is on all major architectures and until it has feature parity with Mono/.NET.

**Comment by newsash** [comment]
I'm trying to run Kestrel on FreeBSD on raw mono (`mono WebApplication.exe`). After installing libuv I get "WS2_32.dll not found". It looks like 1 step from working server, but [this](https://github.com/aspnet/KestrelHttpServer/issues/956#issuecomment-232621027) workaround doesn't work. What can I do to fix this error?

**Comment by newsash** [comment]
Solution was simple. To run Kestrel with raw mono just delete `System.Runtime.InteropServices.RuntimeInformation.dll` from project files and the correct dll from mono will be used.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
