### ISSUE TITLE
Question about threading

### ISSUE THREAD

**Issue by csmith93** [aspnet/KestrelHttpServer#947]
Given that Kestrel is different from IIS I was wondering how background threads are handled with Kestrel. Is it possible to have a reliable process running within ASP.NET Core?

**Comment by davidfowl** [comment]
You own the process when hosting with Kestrel, background threads aren't different here, they are just normal threads. The process will stay alive for as long as you run it (unless it crashes or something). Also, nothing will reboot your process if it dies.

**Comment by csmith93** [comment]
Gotcha, I was referring to things like how IIS would recycle the application pool every 29 hours or so.

**Comment by davidfowl** [comment]
Yea, nothing will do that for you.

**Comment by csmith93** [comment]
Thanks for the confirmation!
