### ISSUE TITLE
Have to stop and start web server for any code change.

### ISSUE THREAD

**Issue by paranoid-android** [aspnet/KestrelHttpServer#95]
Hello,

I am evaluating ASP.NET 5. One of the features that peaked my experience was the no-compile experience mentioned [here](http://www.hanselman.com/blog/IntroducingASPNETVNext.aspx). My question is how do I include it in my project? 

I had a sample ASP.NET 5 app. I could execute `k run` and it would start the site. I've migrated to `dnx`. I can start the site. However, since updating the project from k to dnx, I can't even change client-side JavaScript without having to kill Kestrel. At this time, my project.json file looks like the following:

```
{
  "version": "1.0",
  "description": "My App",
  "dependencies": {
    "Kestrel": "1.0.0-*",
    "Microsoft.AspNet.Diagnostics": "1.0.0-*",
    "Microsoft.AspNet.Mvc": "6.0.0-*",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-*",
    "Microsoft.AspNet.Server.WebListener": "1.0.0-*",
    "Microsoft.AspNet.StaticFiles": "1.0.0-*",
    "Microsoft.Framework.ConfigurationModel": "1.0.0-*",
    "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-*",
    "System.Data.Common": "1.0.0-*",
    "System.Data.SqlClient": "1.0.0-*"
  },
  "commands": {
    "run": "Microsoft.AspNet.Hosting --server Kestrel --server.urls http://localhost:5004",
    "web": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener --server.urls http://localhost:5001"
  },
  "frameworks": {
    "dnx451": { },
    "dnxcore50" : { }
  }
}
```

I am trying to do this on Mac OS X. What am I doing wrong? How do I use the No-Compile experience on Mac OS X?

**Comment by DamianEdwards** [comment]
That feature is actually implemented by DNX and it doesn't do the restart for you, something else watching the process has to do that. In Visual Studio, it's Visual Studio itself that sees that IIS Express stops and restarts it. VS will support other servers (like Kestrel) in a future update (we're aiming for our RC in November).

For command line scenarios, we plan to build a global command that can do the watching of DNX and subsequent restart. That's tracked in aspnet/dnx#1795

**Comment by jasselin** [comment]
@DamianEdwards Is there a way to prevent Visual Studio from restarting IIS Express, just like old times?
