### ISSUE TITLE
Advancing Kestrel to the point of making it a full-fledged Internet-facing web server

### ISSUE THREAD

**Issue by GuardRex** [aspnet/KestrelHttpServer#957]
On the question of running Kestrel out in the open (not behind IIS/ngnix), the common response is that it shouldn't be done primarily based upon security concerns. For example @DamianEdwards in https://github.com/aspnet/IISIntegration/issues/220 ...

> we still recommend that kestrel not be directly exposed to the internet due to it not containing mitigations for common types of DOS and other attacks.

Given that perf is significantly hampered by either or both of IIS and the ANCM module (or ngnix for that matter), it will probably be an on-going feature request to get whatever these needed protections are into Kestrel to make it capable of acting as a standalone Internet-facing web server*.

[* Let's set aside the issues of port sharing and process management for a second, because those won't apply to all cases where one may desire to use Kestrel in this capacity and some workarounds exist for those issues.]

Can you say anything about adding the needed protections to Kestrel? Is there a long-term plan (or even just desire) to do this work?

**Comment by ronnyek** [comment]
I wont argue or try to minimize implications of these efforts, but can we call out exactly what would be required here? Does IIS contain anti-DOS / attack code? Seems like that specific requirement... knowing what sort of guidelines were supported, could probably be handled by some clever rx stuff.

**Comment by DamianEdwards** [comment]
There is a plan to add these protections to Kestrel for the next minor release (1.1). No timelines to announce for that right now, but it's months, not weeks or years.

**Comment by GuardRex** [comment]
*That's excellent news!* :+1:
