### ISSUE TITLE
SocketOutputTests.OnlyAllowsUpToThreeConcurrentWrites test failure on AppVeyor

### ISSUE THREAD

**Issue by cesarbs** [aspnet/KestrelHttpServer#958]
xUnit.net .NET CLI test runner (64-bit Desktop .NET win81-x64)
      Discovering: Microsoft.AspNetCore.Server.KestrelTests
      Discovered:  Microsoft.AspNetCore.Server.KestrelTests
      Starting:    Microsoft.AspNetCore.Server.KestrelTests
        Microsoft.AspNetCore.Server.KestrelTests.SocketOutputTests.OnlyAllowsUpToThreeConcurrentWrites [FAIL]
          System.InvalidOperationException : Collection was modified after the enumerator was instantiated.
          Stack Trace:
               at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
               at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
            SocketOutputTests.cs(594,0): at Microsoft.AspNetCore.Server.KestrelTests.SocketOutputTests.OnlyAllowsUpToThreeConcurrentWrites()
      Finished:    Microsoft.AspNetCore.Server.KestrelTests
    === TEST EXECUTION SUMMARY ===
       Microsoft.AspNetCore.Server.KestrelTests  Total: 657, Errors: 0, Failed: 1, Skipped: 0, Time: 11.425s

https://ci.appveyor.com/project/aspnet-ci/kestrelhttpserver/build/1.0.1824

**Comment by mikeharder** [comment]
I saw this today as well
