### ISSUE TITLE
Cannot run tests or SampleApp with vanilla install of VS 2015 RC

### ISSUE THREAD

**Issue by SteveArr** [aspnet/KestrelHttpServer#96]
I expected that with a fresh instance of the Azure VS 2015 RC Community edition machine that I would be able to run the Kestrel unit tests or SampleApp.

If I set the Tests as the startup-project and run I get a fairly quick: "The program '[3868] dnx.exe' has exited with code 1 (0x1)."

If I run the tests from the command line with "dnx . test" from within the tests project folder I get:  System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.AspNet.Program.Main(String[] args)

"dnu restore" shows everything in cache.

"dnvm list" shows active, default as "1.0.0-beta4 clr".

This is reproducible by making an instance of the Azure VS 2015 RC Community edition image, git clone the KestrelHttpServer project and trying to run in Visual Studio or command line.

**Comment by SteveArr** [comment]
In addition, installed version xunit.runner.aspnet is 2.0.0-aspnet-beta5-10345

**Comment by davidfowl** [comment]
First of all, file any bugs like this on aspnet/Home. It has nothing to do with kestrel.

That's the wrong xunit version to use. You **cannot**, I repeat, you **cannot** cross the streams while we're in beta. That means if you're using the beta4 dnx, try to make sure all of the packages that come from our stuff (the aspnet org) are also beta4. We make breaking changes between beta releases so if you take beta5 xunit runner and run it on the beta4 dnx, you're gonna have a bad time.

Anyways to make it work, add an entry to your `nuget.config` to point to `https://www.myget.org/F/xunit/` and read https://github.com/xunit/dnx.xunit#.

**Comment by SteveArr** [comment]
This put me on the right path for resolution.  
For posterity:  I updated to beta5 by cloning and building aspnet/dnx and that resolved my issues.
