### ISSUE TITLE
HttpContext.Connection.RemoteIpAddress is null when using Nginx

### ISSUE THREAD

**Issue by hamu01** [aspnet/KestrelHttpServer#961]
We have a website developed by asp.net core rc2。We publish the website to linux server, use nginx as reverse proxy. We have added "proxy_set_header X-Forwarded-For $remote_addr;" config.The problem is HttpContext.Connection.RemoteIpAddress is null, LocalIpAddress,LocalPort is also null, we cannot get the value of these properties.  

Nginx config:
```
server{
    listen 80;
    server_name  localhost;

    location / {
        proxy_pass http://unix:/var/aspnet/kestrel.sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host:80;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Original-For $server_addr;
        proxy_cache_bypass $http_upgrade;
    }
}
```

Program.cs(simplified)
```
public class Program
{
        public static void Main(string[] args)
        {
            IConfiguration configuration = new ConfigurationBuilder().SetBasePath(Directory.GetCurrentDirectory()).AddJsonFile("host.json").Build();
            var host = new WebHostBuilder()
                .UseConfiguration(configuration)
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
 }
```

Startup.cs(simplified)
```
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            app.Run(async (context) =>
                {
                    try
                    {
                        StringBuilder requestBuilder = new StringBuilder();
                        var remoteIp = context.Connection.RemoteIpAddress;
                        string remoteIpstring = remoteIp != null ? remoteIp.ToString() : "-";
                        requestBuilder.Append(string.Format("remoteIp={0};", remoteIpstring));
                        
                        var serverIp = context.Connection.LocalIpAddress;
                        string serverIpstring = serverIp != null ? serverIp.ToString() : "-";
                        requestBuilder.Append(string.Format("serverIp={0};", serverIpstring));

                        string serverPort = context.Connection.LocalPort.ToString();
                        requestBuilder.Append(string.Format("serverPort={0};", serverPort));

                        await context.Response.WriteAsync(requestBuilder.ToString());
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                });
        }
 }
```

OS：Centos 7.1
Nginx version：1.10.1
.NET Core version：RC2

**Comment by vas6ili** [comment]
@hamu01 I think you have to add the [ForwardedHeadersMiddleware ](https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersMiddleware.cs) to the pipeline.

```
   app.UseForwardedHeaders();
```

**Comment by Tratcher** [comment]
A) You need to specify ForwardedHeadersOptions.ForwardedHeaders = ForwardedHeaders.XForwardedFor in UseForwardedHeaders
B) Please show the headers so we can see if something is wrong.
C) We recommend updating from RC2 to RTM

**Comment by hamu01** [comment]
@Tratcher Thx, it works now.
But the forward configuration really confuse me. I have following questions need to be answered:
1. If I use IIS as reverse proxy, asp.net core rc2 website do not need add the forward middleware to the pipeline. In that situation HttpContext.Connection.RemoteIpAddress is not null, I still can get the remoteip value. Why?It seems the behavior in IIS and Nginx is inconsistent
2. The context.Connection.LocalIpAddress and LocalPort is also inconsistent when use IIS as reverse proxy and when only use kestrel server, donot use the IIS as reverse proxy. If the asp.net core rc2 website get the real remoteip in IIS, then it also should get the real serverip, I think.
3. Only specify ForwardedHeadersOptions.ForwardedHeaders = ForwardedHeaders.XForwardedFor works, if specify ForwardedHeaders.All, HttpContext.Connection.RemoteIpAddress is still null, I think when specify ForwardedHeaders.All, it means forward the x-forward-for,x-forward-host and x-forward-protocol, so HttpContext.Connection.RemoteIpAddress shouldnot be null. The real case seems to forward one of them, not all of them.

(If any of the question fixed in RTM version, please ignore it, I have not upgraded to RTM version)

Bellow is the demo code and output：
1. Startup.cs(simplified)，display the HttpContext.Connection's property and all the headers
```csharp
public class Startup
{
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            //ForwardedHeadersOptions options = new ForwardedHeadersOptions();
            //options.ForwardedHeaders = ForwardedHeaders.XForwardedFor;
            //app.UseForwardedHeaders(options);
            app.Run(async (context) =>
                {
                    try
                    {
                        StringBuilder requestBuilder = new StringBuilder();
                        var remoteIp = context.Connection.RemoteIpAddress;
                        string remoteIpstring = remoteIp != null ? remoteIp.ToString() : "-";
                        requestBuilder.Append(string.Format("remoteIp={0};", remoteIpstring));

                        string remotePort = context.Connection.RemotePort.ToString();
                        requestBuilder.Append(string.Format("remotePort={0};", remotePort));

                        var serverIp = context.Connection.LocalIpAddress;
                        string serverIpstring = serverIp != null ? serverIp.ToString() : "-";
                        requestBuilder.Append(string.Format("serverIp={0};", serverIpstring));

                        string serverPort = context.Connection.LocalPort.ToString();
                        requestBuilder.Append(string.Format("serverPort={0};", serverPort));

                        foreach (string key in context.Request.Headers.Keys)
                        {
                            string value = context.Request.Headers[key];
                            requestBuilder.Append(string.Format("{0}={1};", key, value));
                        }

                        await context.Response.WriteAsync(requestBuilder.ToString());
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                });
        }
    }
```
2. use IIS, the output is: 
```
remoteIp=10.200.200.113;remotePort=62242;serverIp=127.0.0.1;serverPort=30791;Cache-Control=no-cache;Connection=Keep-Alive;Accept=text/html, application/xhtml+xml, */*;Accept-Encoding=gzip, deflate;Accept-Language=zh-CN;Host=10.200.50.201:6000;User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko;MS-ASPNETCORE-TOKEN=7c45ff68-2c0d-499e-bb53-f89ab8c33554;X-Original-Proto=http;X-Original-For=127.0.0.1:51137;
```

You can see that I can get the context.Connection.RemoteIpAddress value, but I donot add the forwardmiddle to the pipeline.

3.not use IIS, only use the kestrel server,listening on the 5000 port, the output is:
```csharp
remoteIp=10.200.200.113;remotePort=63149;serverIp=10.200.50.201;serverPort=5000;Cache-Control=no-cache;Connection=Keep-Alive;Accept=text/html, application/xhtml+xml, */*;Accept-Encoding=gzip, deflate;Accept-Language=zh-CN;Host=10.200.50.201:5000;User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko;
```
You can see in this situation, the context.Connection.LocalIpAddress isnot 127.0.0.1, it is the server Intranet IP. But in previous situation the context.Connection.LocalIpAddress is 127.0.0.1

**Comment by Tratcher** [comment]
UseForwardedHeaders is added by UseIISIntegration (https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/IISSetupFilter.cs#L23) with some default settings (https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L47).

We could consider doing something similar for NGinx, but we haven't outlined what a standard NGinx deployment should look like yet.

There's a catch when you use All. See RequireHeaderSymmetry (https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L34-L38)

**Comment by hamu01** [comment]
@Tratcher Got it, Thx.  
I upgrade to RTM now. But the other problem is still exists.
1. When use IIS as reverse proxy, I can't get the real localip(context.Connection.LocalIpAddress), I get the 127.0.0.1 instead.
2. If specify ForwardedHeaders.All, HttpContext.Connection.RemoteIpAddress is still null, why?

**Comment by Tratcher** [comment]
Don't use All, don't customize the settings for RTM.

Sharing your request headers as observed on the server may be the best way to understand the problem.

**Comment by hamu01** [comment]
I already list the request header in previous comment, I list them again now.
```
Cache-Control=no-cache;Connection=Keep-Alive;Accept=text/html, application/xhtml+xml, */*;
Accept-Encoding=gzip, deflate;Accept-Language=zh-CN;Host=10.200.50.201:6000;
User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko;
MS-ASPNETCORE-TOKEN=7c45ff68-2c0d-499e-bb53-f89ab8c33554;
X-Original-Proto=http;X-Original-For=127.0.0.1:51137;
```

**Comment by Tratcher** [comment]
Sorry, I had not read your posts thoroughly enough. LocalIpAddress is the address Kestrel listens on behind IIS. There's no way to get IIS's external IP. However you can get the host and port from the Host header.

It looks like you've gotten everything else working that's expected to work.

**Comment by karldodd** [comment]
Looking forward to `UseIISIntegration()` equivalent for Nginx and an update to https://docs.asp.net/en/latest/publishing/linuxproduction.html  : )

**Comment by Tratcher** [comment]
@karldodd is there a specific bug open tracking your request for UseNginxIntegration? Can you add a link here?

**Comment by hamu01** [comment]
@Tratcher I have no question, the issue can close for me.
