### ISSUE TITLE
Does IIS rewrites work with Kestrel?

### ISSUE THREAD

**Issue by nitro52** [aspnet/KestrelHttpServer#966]
i'm currently looking at converting an old asp.net project to core and having some problem running it under kestrel. We have a few URL rewrites in our web.config like this. 

```
<system.webServer>
      <rewrite>
         <rules>
            <rule name="styles mapping">
              <match url="^styles/([_0-9a-z-\.]+)" />
              <action type="Rewrite" url="lib/my-bower-component/dist/styles/{R:1}" />
            </rule>
            <rule name="script mapping" enabled="true">
              <match url="^scripts/([_0-9a-z-\.]+)" />
              <action type="Rewrite" url="lib/my-bower-component/dist/scripts/{R:1}" />
            </rule>  
        </rules>
    </rewrite>
  </system.webServer>
```

We need to remap a relative path to a path that's managed by bower. These work with IIS Express

**Comment by davidfowl** [comment]
What do you mean works with Kestrel? Do you mean Kestrel without IIS (Express)? No they won't work. We do have an intern @ZestyBread working on rewrite middleware though that will be a generic ASP.NET component and able to import rules from both UrlRewrite and ModRewrite

**Comment by nitro52** [comment]
i thought it was either one or the other? 

basically my understanding was if i wanted to be able to deploy to say linux, i would need to host it with Kestrel?

So i assume things that are IIS specific features that get configured in web.config would no longer work. Having to recreate them using some sore of middle ware would make sense, i though i read somewhere that it should read from web.config though. 

Is UrlRewrite and ModRewrite the IIS/Kesteral equivalents? does that mean the rules you create would work on any environment it is deployed to?

**Comment by benaadams** [comment]
@nitro52 if you are hosting behind IIS, then IIS reads the web.config (where is picks up the `AspNetCoreModule` handler) and the URL rewrites would still work as they are for an IIS handler.

Kestrel itself does not read the web.config and nor does nginx - however nginx has its own rewrite rules which you could use if you were on linux https://www.nginx.com/blog/creating-nginx-rewrite-rules/

**Comment by nitro52** [comment]
Thanks @benaadams, that makes sense, So i guess the question is more of an asp.net core question then, how can we do these rewrites and still be able to deploy to multiple platforms.

**Comment by benaadams** [comment]
@nitro52 could do a middleware early in the pipeline that does that match and on match alters `Path`?

**Comment by ZestyBread** [comment]
@nitro52 The goal for now is to have ports for both UrlRewrite (IIS) and ModRewrite (Apache) as a static extension middleware. Therefore, it would be able to work on any environment it is deployed too. Timeline wise, this feature should be finished by late August, and should be on a alpha/beta build shortly after.

**Comment by nitro52** [comment]
Thanks for the explanation. At the moment i can work around it and i'll check back in later for the middleware

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
