### ISSUE TITLE
libUV or SocketAsyncEventArgs for .NetCore 1.0 

### ISSUE THREAD

**Issue by enginekit** [aspnet/KestrelHttpServer#968]
@aspnet team,
Since .net standard 1.6 has SocketAsyncEventArgs.
from your opinion,
What is better for future KestrelHttpServer 
between libUV  and SocketAsyncEventArgs  ?
:)

**Comment by davidfowl** [comment]
We would need to measure to know for sure. We haven't spent anytime analyzing the performance differences between SocketAsyncEventArgs and libuv as we started writing kestrel before that implementation became available on Linux and OS X.

**Comment by enginekit** [comment]
👍 Thank you :)
