### ISSUE TITLE
Update application files without stop IIS

### ISSUE THREAD

**Issue by mojtabakaviani** [aspnet/KestrelHttpServer#970]
Now, when I want update application file on IIS server. show error that the action can't be completed because the folder or a file in it is open in another program. and must stop IIS and copy/paste file and then start IIS.

**Comment by moozzyk** [comment]
AspNetCoreModule supports app offline feature. You drop the app_offline.htm file which will make IIS stop your application (and serve the contents of the app_offline.htm file) then you can update your app. Once you are done you remove the app_offline.htm file. WebDeploy does this for you when you publish to Azure. I think it does not do this when publishing to file system but @vijayrkn knows how to configure this.

**Comment by vijayrkn** [comment]
If you are using a "filesystem" profile to publish (which has `<WebPublishMethod>FileSystem</WebPublishMethod>`), then you need to add 
`<EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>` to support app_offline. While publishing to Azure, this property is automatically added to your pubxml.

**Comment by GuardRex** [comment]
Cross ref issues ...
https://github.com/aspnet/IISIntegration/issues/226
https://github.com/aspnet/Home/issues/694

**Comment by muratg** [comment]
This issue was moved to aspnet/IISIntegration#238
