### ISSUE TITLE
Implement IHttpSendFileFeature in Kestrel

### ISSUE THREAD

**Issue by Yves57** [aspnet/KestrelHttpServer#981]
I have made some performance tests to see the difference between using a cache and using directly a physical file stream.
- When using a cache, I use a dictionary to store the last modification date (in case of the file is modified) and the file content.
- When using directly the file, I have more or less copy/paste the `StaticFiles.StaticFileContext` code (including `StreamCopyOperation.CopyToAsync()`).
I created a Console application, and I made tries with different file sizes. For each file size, I loop 1000 times on the same file to copy it to the `Null` stream (to avoid uninteresting overhead). So it is the most favorable case for the physical file stream, because Windows and the hard disc can do the best use of their caches.

Here are the results on my computer:
```
Test with cache
10K --> 52 ms
30K --> 38 ms
100K --> 36 ms
500K --> 35 ms
1M --> 36 ms
5M --> 42 ms
10M --> 51 ms

Test direct stream
10K --> 148 ms
30K --> 132 ms
100K --> 179 ms
500K --> 425 ms
1M --> 728 ms
5M --> 4138 ms
10M --> 8525 ms
```

The performance difference is significant!

So I suggest to add the following API:
```
public class SendPhysicalFileCacheOptions
{
   public int CacheMaximumSize { get; set; }   // The maximum dedicated size in MB (i.e. the sum of all file contents)
   public long FileMaximumSize { get; set; }   // The maximum size of a file to be saved in cache in Bytes (so lower than CacheMaximumSize)
   public IEnumerable<Func<string, long, bool>> Filters { get; set; } // Optional filters F(filePath, fileLength)->bool that allows user the reject files from cache
}
```

And a new property `SendPhysicalFileCacheOptions SendPhysicalFileCache {get; set; }` in `KestrelServerOptions`. If the property is set, it would add a `IHttpSendFileFeature` implementation.

**Comment by davidfowl** [comment]
I don't see the advantage of this being part of kestrel and not another piece of middleware (that is, if we used this technique).

**Comment by Yves57** [comment]
In fact my first idea was to add it in the StaticFiles module.
But:
- `IHttpSendFileFeature` is used in the MVC module, so it would be strange to have to add StaticFiles to use it.
- The `IHttpSendFileFeature.SendFileAsync()` has no information about the output Body stream in its parameters, so I suppose it would have to use `IHttpResponseFeature` for instance. So the implementation has to be Transient. But I don't know any solution to make a `HttpContent.Features` item Transient.

But maybe I miss something...

**Comment by davidfowl** [comment]
I'm not sure what you mean "Make it transient". The pattern is that features are added to the `HttpContext` on a per request basis. The middleware would be configured as a file cache middleware and at that point it has full control over the `HttpContext`:

```C#
app.UseFileCache(new FileCacheOptions
{
  ...
});
```

If you put it before StaticFiles and MVC it would replace or set the `IHttpSendFileFeature`

**Comment by Yves57** [comment]
I didn't know that a middleware was able to modify the `HttpContext.Features` collection on each request.
I made quick try to understand and the implementation is correctly called, thank you!
But in which module can be added this middleware? Microsoft.AspNetCore.Buffering?

**Comment by benaadams** [comment]
@Yves57 would be more ResponseCaching? https://github.com/aspnet/ResponseCaching

**Comment by davidfowl** [comment]
I'm not sure it would go into any existing middleware we have today. If we did something like this it would probably be a separate middleware (like ResponseCaching).

**Comment by Yves57** [comment]
I have moved the issue in ResponseCaching.
